add replace enforce with glog switch for debug
PaddlePaddle/Paddle pull request #11244
Opened 2018-06-06 10:44 UTC by Superjomn

2018-06-07 09:13 UTC, jacquesqiao commented
Please run with gdb and enforce and see if we can also see the message with line number.

2018-06-07 09:30 UTC, Superjomn commented
Run the program in gdb with exception cannot get any call stack calling `bt` command.

2018-06-30 08:22 UTC, luotao1 approved these changes
LGTM！

2018-06-30 08:25 UTC, gongweibao requested changes

2018-06-30 08:25 UTC, gongweibao commented on CMakeLists.txt
> +if (REPLACE_ENFORCE_GLOG)
put into configure.cmake?

2018-06-30 08:25 UTC, gongweibao commented on paddle/fluid/platform/enforce.h
> +#define PADDLE_ENFORCE(...) ::paddle::platform::throw_on_error(__VA_ARGS__);
这个地方为何去掉了try, catch部分？

2018-06-30 08:25 UTC, gongweibao commented on paddle/fluid/string/printf.h
> +std::string Sprintf(const char* fmt = "", const Args&... args) {
默认参数一般是最后一个吧？

2018-06-30 09:18 UTC, gongweibao approved these changes

2018-06-30 12:33 UTC, merged