Fix api reference docs
PaddlePaddle/Paddle pull request #11314
Opened 2018-06-08 09:49 UTC by typhoonzero

Some document polish work.

2018-06-08 10:08 UTC, reyoung commented
I just polish `templatedoc()` a little bit to generate better documentation. Make it support inline math and correct the google style comments. See #11308.

Also, as discussed with @shanyi15 yesterday, we decided to use a new repo to manage documentation of fluid for several reasons.

1. We need cross hyperlink between API-reference, API-Guide and User story. In Paddle, we separate API, use case into many sphinx projects( around 10 sphinx projects before... T_T ). They cannot be cross-link well.
2. It is hard to build documentation before. Use `cmake` to drive `sphinx-build` is tricky. We can separate them into two projects. It is easy to complete i18n later if we use a standard sphinx project structure.

Current, this repo(https://github.com/reyoung/FluidDoc) is in very early stage and flux. However, it is very simple to build a documentation site follow the readme. 

You can install your developing version of paddle, and `make html`. The documentation will be generated well at `build/html` directory.


The develop branch of this documentation will be generated to `readthedocs.org`. http://fluiddoc.readthedocs.io/zh_CN/develop/ . It uses our latest release paddle to generate.

2018-06-08 10:42 UTC, typhoonzero commented
@reyoung Thanks for polishing `templatedoc`, I was looking into the format problem using local compiled server. Glad that you already make a fix.

2018-06-11 06:38 UTC, typhoonzero commented on paddle/fluid/framework/details/fuse_vars_op_handle.cc
> +  this->RunAndRecordEvent([] {});
This line is intended to fix build on macos

2018-06-12 05:15 UTC, skylarch submitted a review, later dismissed

2018-06-12 05:27 UTC, skylarch commented
dynamic_lstm解释公式变量的部分改为列表形式，和之前的保持一致。

2018-06-13 02:27 UTC, skylarch requested changes
request changes as commented

2018-06-13 04:55 UTC, skylarch commented
@typhoonzero 
现在@reyoung 老师可能对注释内容有新的建议，API注释标准暂时待定，之前的comment可以先不做修改。

2018-06-13 09:23 UTC, skylarch commented
@typhoonzero 
comment已根据最新标准更新，可以开始做修改。

2018-06-14 03:28 UTC, typhoonzero commented
@skylarch Added screen shot of the document preview.

2018-06-14 05:08 UTC, skylarch commented
@typhoonzero 

chunk_eval: 
缺标题；
缺examples；
“see below for details"指的是哪一部分呢？这些可能是有问题的${chunk_scheme_comment}，${num_chunk_types_comment}，${excluded_chunk_types_comment}

iou_similarity
标题格式除介词外首字母大写，无句号，加粗

ctc_greedy_decoder
截图不全

ListenAndServ
标题格式除介词外首字母大写，无句号，加粗
缺return

autoincreased_step_counter
缺例子

conv2d_transpose
标题格式除介词外首字母大写，无句号，加粗
截图不全

roi_pool
标题格式除介词外首字母大写，无句号，加粗
例子或截图不全

crf_decoding
例子

scale
例子

cos_sim
标题格式除介词外首字母大写，无句号，加粗
例子

2018-06-14 12:34 UTC, reyoung commented
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41412352-50b0577c-7012-11e8-8fa5-6405b314d657.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41412354-55062266-7012-11e8-8920-16a3813a774b.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41412360-574852ba-7012-11e8-899f-e6787b1eecbd.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41412362-59c36cc8-7012-11e8-8917-1b1b4b6ac990.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41412365-5c1e0c3a-7012-11e8-8f8d-44e189029443.png">

2018-06-15 07:29 UTC, reyoung submitted a review, later dismissed
Excellent

2018-06-15 07:30 UTC, skylarch submitted a review, later dismissed

2018-06-17 05:30 UTC, reyoung approved these changes
Cool

2018-06-17 05:30 UTC, merged