update split_lod_tensor, create_array and array_length doc
PaddlePaddle/Paddle pull request #11383
Opened 2018-06-12 04:48 UTC by jacquesqiao

2018-06-12 04:50 UTC, jacquesqiao commented
@skylarch 求检查一下格式是否符合要求

2018-06-12 05:55 UTC, skylarch commented
需要添加function description、formula、和formula中符号的解释。示例可见：http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/dev/api_doc_std_cn.html

2018-06-12 06:09 UTC, jacquesqiao commented
@skylarch 这几个api没有公式呢

2018-06-12 13:13 UTC, skylarch commented
@jacquesqiao 
那么现在的API reference就都没问题了。
你还在添加不包括在pr标题中的API的commit，所以如果之后还会添加新的commit，我就先不approve；如果之后的commit会新开pr，我就把这个pr approve。

2018-06-12 13:16 UTC, skylarch commented
@jacquesqiao 
create_tensor:
标题格式除介词外首字母大写，无句号;
[(Data Type, Default Value)]：缺default
缺Formula（如果现在还没有就不用改）

2018-06-12 13:26 UTC, skylarch requested changes
request changes as commented

2018-06-13 04:56 UTC, skylarch commented
@jacquesqiao 
现在@reyoung 老师可能对注释内容有新的建议，API注释标准暂时待定，之前的comment可以先不做修改。

2018-06-14 05:22 UTC, jacquesqiao commented
![image](https://user-images.githubusercontent.com/3048612/41392823-84313310-6fd5-11e8-9818-ec59b5546c67.png)

![image](https://user-images.githubusercontent.com/3048612/41392830-93cf7408-6fd5-11e8-8a1a-be42ea02a2a0.png)

![image](https://user-images.githubusercontent.com/3048612/41392858-b1224d8c-6fd5-11e8-957d-22e46bd1ed62.png)

![image](https://user-images.githubusercontent.com/3048612/41392872-bfbc5a5e-6fd5-11e8-87a2-5883205caad7.png)

![image](https://user-images.githubusercontent.com/3048612/41392897-da114414-6fd5-11e8-9446-0ba19067652b.png)

2018-06-14 05:38 UTC, skylarch commented
@jacquesqiao 

split_lod_tensor
删除function description的标题（更多标准见http://agroup.baidu.com/paddlepaddle/md/article/976426）

<img width="173" alt="screen shot 2018-06-14 at 1 29 57 pm" src="https://user-images.githubusercontent.com/16292809/41393161-10c6e1fc-6fd7-11e8-9a6a-81c100f2c6ec.png">

batch_norm
参数介绍不全
缺return，example

switch
缺参数介绍，return

如果API没有return，需在return项标出。

2018-06-14 06:21 UTC, jacquesqiao commented
1. split_lod_tensor已删除
2. batch_norm 的后半部分。
![image](https://user-images.githubusercontent.com/3048612/41394855-1ddaa2e6-6fde-11e8-9e81-626ac5b3835a.png)

2018-06-14 06:47 UTC, skylarch submitted a review, later dismissed

2018-06-14 12:59 UTC, reyoung commented
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413449-c21ced96-7015-11e8-9b89-38eba782e75a.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413451-c36aec48-7015-11e8-9779-a363bacb78f5.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413455-c5b6f154-7015-11e8-88c4-b9aaa71d6288.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413459-c860adbe-7015-11e8-84a3-82149929ff2e.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413465-ca9b86a8-7015-11e8-8bf7-d167b4c312bc.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413467-ccaef48e-7015-11e8-8905-8c28a3968514.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413472-cee15a9e-7015-11e8-8cc8-04e81c622540.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413474-d1085354-7015-11e8-8c47-dd6491e9746a.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41413477-d32e0854-7015-11e8-847d-78e371cabc7c.png">

2018-06-14 12:59 UTC, reyoung commented
另外，似乎`reverse` 的文档找不到。

2018-06-15 02:37 UTC, reyoung commented
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447462-f6a7c1fe-7087-11e8-969d-a4662d69253a.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447465-f97705e8-7087-11e8-85b3-35363eb16a0e.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447468-fbaec30a-7087-11e8-86a7-8ae0ccc432fd.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447469-fddce59e-7087-11e8-89ff-75f7f252c9af.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447470-0000c9ee-7088-11e8-8198-a3909e131dc1.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447473-02641fe2-7088-11e8-8a3c-d7f663d1686c.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447477-04556b26-7088-11e8-9405-7a227f3cf29e.png">
<img width="415" alt="default" src="https://user-images.githubusercontent.com/728699/41447478-0672ae46-7088-11e8-9283-d178c1cd25b0.png">

2018-06-17 03:14 UTC, reyoung commented
![default](https://user-images.githubusercontent.com/728699/41504356-b536ef68-721e-11e8-87fd-f205b46402bd.png)
![default](https://user-images.githubusercontent.com/728699/41504364-fe8afb96-721e-11e8-94fa-fc7cd4eebeb0.png)
![default](https://user-images.githubusercontent.com/728699/41504371-465e0710-721f-11e8-8308-30b2588a8892.png)

2018-06-17 06:37 UTC, reyoung approved these changes
Finally done. Thanks.

2018-06-17 06:37 UTC, merged