[Important] MKLDNN version of the code must have all space of memory
PaddlePaddle/Paddle pull request #11481
Opened 2018-06-14 10:50 UTC by mozga-intel

Problem with the MKLDNN performance after this change : [commit](https://github.intel.com/AIPG/paddle/commit/9300212701505e0cf35b5570f3881950525ec73c)

Description and solution 
The mkldnn performance of the newest Paddle is a worse than the code before the changes: nearly **50%**, The mkldnn version of code need to have all space of memory to work correctly. During the tests with htop the loss of power of the threads is significant and we can not keep the fluency. 

The code shows the solution to this problem. Summary: this is the  fall back to the previous version of the code with MKLDNN flag.

2018-06-14 11:02 UTC, luotao1 commented
@mozga-intel I couldn't open https://github.intel.com/AIPG/paddle/commit/9300212701505e0cf35b5570f3881950525ec73c

2018-06-14 11:39 UTC, mozga-intel commented
@luotao1. I am sorry. The link is up-to-date

2018-06-14 17:06 UTC, tensor-tang commented
I am afraid you can not change like this, because `initial_cpu_memory_in_mb` should be also used when WITH_MKLDNN.

The performance drop is only caused by the changes of memory size, you can try to get the necessary memory size for MKLDNN, like 1G not 500M. Then change the default size with `ifdef PADDLE_WITH_MKLDNN`.

Because online service also need the memory as a target, so we should keep as small memory as possible, The original default flag would take about 3% of system memory, which would be too large sometimes,

2018-06-14 17:11 UTC, tensor-tang requested changes
Please try to keep this flag available no matter with or without MKLDNN.

The recommend way: change the default size when use MKLDNN. At least, we can know MKLDNN need how much memory to get the best performance.

2018-06-15 17:39 UTC, tensor-tang commented
@mozga-intel
I can refine it later, please wait a moment.

2018-06-15 21:03 UTC, mozga-intel commented
@tensor-tang Thank you for your the quickly answer. 

I stay in touch with you.

2018-06-15 21:03 UTC, mozga-intel commented
@tensor-tang Thank you for your quickly answer.

I stay in touch with you.

2018-06-19 06:35 UTC, closed without merging