change im2sequence for ctc batch inference
PaddlePaddle/Paddle pull request #11696
Opened 2018-06-25 11:35 UTC by lemon34

2018-06-27 17:19 UTC, wanghaoshuang requested changes

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.cc
> +    AddInput("Y", "image real size.").AsDispensable();
说名下`Y`的类型和shape

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.cc
> +    AddAttr<std::vector<int>>("out_stride",
是不是要说明只有input(Y)存在的时候，该attribute才生效。而且还要解释下其含义。

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.cc
> +#include "paddle/fluid/platform/mkldnn_helper.h"
这个头文件有用到么？

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +#include <fstream>
这个用在哪里？

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +    const Tensor* imgRealSize = ctx.Input<Tensor>("Y");
变量命名格式需要统一。

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +      std::vector<int> imgReal_H;
变量命名格式需要规范统一。

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +      // TODO(fuhailong): fix gpu inference
这个TODO什么意思，还需要么？

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +        int tmp_real_H = static_cast<int>((cpu_shape_tensor.data<T>())[2 * i]);
注意变量命名规范。

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +        // TODO(fuhailong): compute dims of output
这个TODO是不是可以删掉了？

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +      const std::vector<int> dilations({1, 1});
用户不能指定dilations么？

2018-06-27 17:19 UTC, wanghaoshuang commented on paddle/fluid/operators/im2sequence_op.h
> +      // TODO(fuhailong): out_dims has two index,
这个TODO有用么？

2018-06-27 17:19 UTC, wanghaoshuang commented on python/paddle/fluid/layers/nn.py
> +                inputImgSize,
这个应该是可选input

2018-06-27 17:19 UTC, wanghaoshuang commented on python/paddle/fluid/layers/nn.py
> +                out_stride=1,
这个也是可选arguments

2018-06-27 17:19 UTC, wanghaoshuang commented on python/paddle/fluid/layers/nn.py
> +    Add inputImgSize and out_stride to deal with ctc batch inference for
不应该加这句吧，batch infer只是这个op的部分功能。

2018-06-27 17:19 UTC, wanghaoshuang commented on python/paddle/fluid/layers/nn.py
> +    if isinstance(out_stride, int):
注意`out_stride`应该是可选输入。

2018-06-28 02:05 UTC, lemon34 commented on paddle/fluid/operators/im2sequence_op.h
> +    const Tensor* imgRealSize = ctx.Input<Tensor>("Y");
命名格式应该怎么统一？

2018-06-28 02:05 UTC, lemon34 commented on paddle/fluid/operators/im2sequence_op.h
> +      const std::vector<int> dilations({1, 1});
这个之前的op里面写的就是const，我也不是很清楚！

2018-06-30 09:02 UTC, lemon34 commented
@wanghaoshuang  重新的提交的PR，CI已经过了，请review一下，谢谢

2018-07-11 09:16 UTC, wanghaoshuang approved these changes
LGTM.

2018-07-11 09:17 UTC, merged