Make cos_sim layer support static parameter.
PaddlePaddle/Paddle pull request #1173
Opened 2017-01-17 11:11 UTC by reyoung

* Fix #1171

2017-01-22 05:07 UTC, qingqing01 commented on paddle/gserver/layers/CosSimLayer.cpp
> +    } else {
首先，[Layer::initNeedFlags()]( https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.cpp#L265)函数里会判断该层是否需要计算gradient(主要是value对应的grad吧)。

然后，每层再分配output对应的grad时，会依据是否需要needGradient()来判断：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/Layer.cpp#L139
```
 if (passType_ != PASS_TEST && needGradient()) {...}
```

所以，所以会出现 getInputGrad()为null的情况。

这个PR里感觉可以不用写else，注释也可以去掉。

ps:  感觉每层计算时都得加上是否要计算input的grad的判断，才合理些。

2017-01-22 05:17 UTC, qingqing01 requested changes

2017-01-22 05:17 UTC, qingqing01 commented on paddle/gserver/layers/CosSimLayer.cpp
> +      outG->cosSimDerivative(*outV, *inV0, *inV1, *inG0, *inG1, scale);
一种情况：inG0, inG1可能其中一个是非空，也就是其中一边需要回传gradient，所以得考虑这种情况。

2019-02-01 04:35 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:35 UTC, closed without merging