fix mac build and whl pkg
PaddlePaddle/Paddle pull request #12020
Opened 2018-07-06 11:16 UTC by typhoonzero

2018-07-09 02:10 UTC, luotao1 commented on python/setup.py.in
> +        command = "patchelf --set-rpath '$ORIGIN/' ${MKLDNN_SHARED_LIB}"
mac情况下，也需要对MKLDNN_SHARED_LIB进行install_name_tool

2018-07-09 02:10 UTC, luotao1 commented on python/setup.py.in
>  if os.system(command) != 0:
135行和151行的错误提示只针对linux，对mac情况下的错误提示需要再修改下。

2018-07-09 02:21 UTC, typhoonzero commented on python/setup.py.in
> +        command = "patchelf --set-rpath '$ORIGIN/' ${MKLDNN_SHARED_LIB}"
Mac 还不支持MKL，但编译可能指定了`WITH_MKL=OFF`但`WITH_MKLDNN`还是ON

2018-07-09 02:24 UTC, luotao1 commented on python/setup.py.in
> +        command = "patchelf --set-rpath '$ORIGIN/' ${MKLDNN_SHARED_LIB}"
> 但编译可能指定了WITH_MKL=OFF但WITH_MKLDNN还是ON

WITH_MKL=OFF的情况下，WITH_MKLDNN也是OFF。

2018-07-09 02:40 UTC, typhoonzero commented on python/setup.py.in
>  if os.system(command) != 0:
Thanks, Done

2018-07-09 12:50 UTC, Superjomn commented on paddle/contrib/inference/CMakeLists.txt
> +    DEPS ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
这里是刚删掉 DEPS 的，现在应该没有依赖这个 lib 的地方吧，保持原样就可以了

2018-07-09 12:51 UTC, luotao1 submitted a review, later dismissed
LGTM！

2018-07-09 12:52 UTC, Superjomn requested changes
paddle_inference_api 会出 bug

2018-07-09 12:52 UTC, typhoonzero commented on paddle/contrib/inference/CMakeLists.txt
> +    DEPS ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
不加这个貌似会编译出错。

2018-07-09 13:08 UTC, Superjomn commented on paddle/contrib/inference/CMakeLists.txt
> +    DEPS ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
DEPS 会 link 那些，只需要加一个 `add_dependencies(paddle_inference_api_shared ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})`

![image](https://user-images.githubusercontent.com/328693/42452304-3bb0727c-83bc-11e8-8f6c-22226ee78184.png)

的确可以删了，但可能不影响这里的错误。

2018-07-09 13:11 UTC, Superjomn commented on paddle/contrib/inference/CMakeLists.txt
> +    DEPS ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/generic.cmake#L221

这里会 `target_link` 把 DEPS 链接进去

2018-07-10 01:14 UTC, typhoonzero commented on paddle/contrib/inference/CMakeLists.txt
> +    DEPS ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
没有加DEPS，会在依赖（比如proto_desc）编译完成之前编译这个lib，导致CI错误。需要用其他的方法解决链接的问题。

2018-07-10 04:24 UTC, tensor-tang commented on cmake/external/mkldnn.cmake
> +    ENDIF()
这里是为了修复哪个问题？如果要disable MKL，不建议在external里面disable.

直接在这里https://github.com/PaddlePaddle/Paddle/blob/ef4895df3bc247c5449a9a0a524839561225bd56/CMakeLists.txt#L92 改吧。只要加上Windows的判断就好了。

因为后面还打算依靠MKL去开启别的开关。

2018-07-10 10:36 UTC, Superjomn approved these changes
LGTM

2018-07-10 12:11 UTC, merged