fix mac build
PaddlePaddle/Paddle pull request #12102
Opened 2018-07-11 13:32 UTC by jacquesqiao

2018-07-11 13:39 UTC, luotao1 reviewed
1. 请在comment里贴下错误日志。
2. 需要尽快把mac ci给建立起来。

2018-07-11 13:39 UTC, luotao1 commented on paddle/contrib/inference/CMakeLists.txt
> +    SRCS paddle_inference_api.cc paddle_inference_api_impl.cc DEPS paddle_fluid_api ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
这里不能这样改，原因：https://github.com/PaddlePaddle/Paddle/pull/12020#discussion_r200989415

2018-07-11 13:47 UTC, jacquesqiao commented on paddle/contrib/inference/CMakeLists.txt
> +    SRCS paddle_inference_api.cc paddle_inference_api_impl.cc DEPS paddle_fluid_api ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
用DEPS有啥问题么

2018-07-11 13:54 UTC, Superjomn commented on paddle/contrib/inference/CMakeLists.txt
> +    SRCS paddle_inference_api.cc paddle_inference_api_impl.cc DEPS paddle_fluid_api ${FLUID_CORE_MODULES} ${GLOB_OP_LIB})
业务线之前4.8上编译会有问题, 所以才这样修改了.

2018-07-11 13:55 UTC, Superjomn requested changes
这样业务线4.8 编译会有问题.

贴上错误日志吧, 感觉这里不应该有问题的

2018-07-11 13:58 UTC, jacquesqiao commented
求修复，我这一周被这个问题浪费了很多时间

2018-07-11 14:02 UTC, luotao1 commented
@typhoonzero 请问你用mac编译的时候，有遇到过这个问题么？

2018-07-11 14:28 UTC, typhoonzero commented
@luotao1 cmake检查executable的问题是有的。dependency的问题应该没有了，或者可能是我在mac编译只开2个线程没有触发

2018-07-12 05:43 UTC, jacquesqiao commented
mac上选择 WITH_CONTRIB=OFF

2018-07-12 05:43 UTC, closed without merging