Benchmark tool for imgnet
PaddlePaddle/Paddle pull request #12305
Opened 2018-07-23 06:18 UTC by typhoonzero

2018-07-31 07:08 UTC, typhoonzero commented
Added `scope` paramter in `ParallelExecutor`, when train with NCCL2 distributed mode, the default scope will have an initialized NCCLID variable which should not be used for testing with `ParalllelExecutor`

2018-08-15 03:54 UTC, gongweibao requested changes

2018-08-15 03:54 UTC, gongweibao commented on benchmark/fluid/Dockerfile
> +ENV http_proxy=http://172.19.32.197:9988/
It doesn't work now.

2018-08-15 03:54 UTC, gongweibao commented on benchmark/fluid/fluid_benchmark.py
> +    # if args.gpus == 1:
Comment?

2018-08-15 03:54 UTC, gongweibao commented on paddle/fluid/API.spec
> +paddle.fluid.ParallelExecutor.__init__ ArgSpec(args=['self', 'use_cuda', 'loss_name', 'main_program', 'share_vars_from', 'exec_strategy', 'build_strategy', 'num_trainers', 'trainer_id', 'scope'], var
Maybe split to another PR can speed the merge process.

2018-08-15 03:55 UTC, gongweibao commented on benchmark/fluid/Dockerfile
> +ENV http_proxy=http://172.19.57.47:8899/
Do we need to reserve them?

2018-08-17 06:34 UTC, reyoung submitted a review, later dismissed

2018-09-06 11:46 UTC, gongweibao submitted a review, later dismissed
LGTM

2018-09-07 04:52 UTC, panyx0718 commented on paddle/fluid/API.spec
> +paddle.fluid.ParallelExecutor.__init__ ArgSpec(args=['self', 'use_cuda', 'loss_name', 'main_program', 'share_vars_from', 'exec_strategy', 'build_strategy', 'num_trainers', 'trainer_id', 'scope'], var
where is the new ParallelExecutor used?

2018-09-07 04:56 UTC, panyx0718 commented on python/paddle/fluid/parallel_executor.py
> +                 scope=None,
comment?

2018-09-07 05:01 UTC, panyx0718 commented
Does it affect testing if the ncclid is in the scope?

2018-09-07 05:10 UTC, typhoonzero commented
@panyx0718 NCCLID in the scope will affect testing using ParallelExecutor, pass a new scope and share `local_scopes` to the test executor will be fine.

2018-09-07 06:12 UTC, reyoung approved these changes

2018-09-07 10:09 UTC, panyx0718 approved these changes

2018-09-08 08:05 UTC, merged