hide operator API
PaddlePaddle/Paddle pull request #12543
Opened 2018-08-05 13:16 UTC by typhoonzero

2018-08-13 02:41 UTC, reyoung submitted a review, later dismissed

2018-08-13 09:32 UTC, gongweibao requested changes

2018-08-13 09:32 UTC, gongweibao commented on paddle/fluid/pybind/protobuf.cc
> +      .def("_block_attr", &pd::OpDesc::GetBlockAttr)
_block_attr=>_block_attr_id ?
GetBlockAttr => GetBlockAttrId?

2018-08-13 09:32 UTC, gongweibao commented on paddle/fluid/pybind/protobuf.cc
>        .def("set_block_attr", &pd::OpDesc::SetBlockAttr)
set_block_attr暴露出来以后，为何block_attr要隐藏？

2018-08-13 09:41 UTC, gongweibao commented on python/paddle/fluid/backward.py
> +            sub_block = program.block(op._block_attr("sub_block"))
Use a protected class method?

2018-08-13 12:27 UTC, gongweibao submitted a review, later dismissed
I'll fix them

2018-08-14 03:30 UTC, panyx0718 submitted a review, later dismissed

2018-09-19 06:42 UTC, panyx0718 submitted a review, later dismissed

2018-09-21 08:35 UTC, reyoung submitted a review, later dismissed

2018-09-21 08:39 UTC, qingqing01 submitted a review, later dismissed

2018-09-25 11:57 UTC, qingqing01 approved these changes

2018-09-25 11:58 UTC, panyx0718 approved these changes

2018-09-26 12:22 UTC, merged