Fuse Convolution and Eltwise Add into MKLDNN's Conv+Bias
PaddlePaddle/Paddle pull request #12669
Opened 2018-08-13 10:51 UTC by Sand3r-

### Purpose
Currently, the networks which use Convolution with bias, divide the process into two steps (or operations):
`conv_op->elementwise_add->next_op`. In order to increase the performance, the elementwise_add is removed and instead an mkldnn biased convolution is used.
### What has been done
Convolution now accepts an optional parameter called "Bias" of dimension = 1, which size of is equal to the number of output channels produced by conv operation.
Inference transpiler has been updated to replace conv and successing elementwise_add with a single conv op.

2018-08-13 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=12669) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=12669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=12669) it.</sub>

2018-08-14 08:54 UTC, mozga-intel requested changes

2018-08-14 08:54 UTC, mozga-intel commented on paddle/fluid/operators/conv_mkldnn_op.cc
> +             : std::vector<int>();
Does it's necessary to the vector of bias will be empty?

2018-08-14 08:54 UTC, mozga-intel commented on paddle/fluid/operators/conv_mkldnn_op.cc
> +          strides,  // No jokes, there is smth srsly messed up with that.
?

2018-08-14 08:54 UTC, mozga-intel commented on paddle/fluid/operators/conv_mkldnn_op.cc
> +      std::vector<mkldnn::primitive>& pipeline) {  // NOLINT
Does this `//NOLINT` is necessary, maybe this vector can be const.

2018-08-14 08:54 UTC, mozga-intel commented on paddle/fluid/operators/conv_op.cc
> +
Whiteline

2018-08-14 09:28 UTC, Sand3r- commented on paddle/fluid/operators/conv_mkldnn_op.cc
> +      std::vector<mkldnn::primitive>& pipeline) {  // NOLINT
The vector is modified by AcquireMemory when reorders need to be applied.

2018-08-16 17:30 UTC, mozga-intel commented
Could you upgrade this code.

2018-08-16 17:30 UTC, mozga-intel commented
LGTM

2018-08-16 17:30 UTC, mozga-intel submitted a review, later dismissed

2018-08-17 01:51 UTC, luotao1 reviewed
please merge the latest code to pass the teamcity. And fix the code style to pass the travis ci.

2018-08-17 01:51 UTC, luotao1 commented on paddle/fluid/operators/conv_op.cc
> +  }
Is input "Bias" only used in MKLDNN?

2018-08-17 06:30 UTC, Sand3r- commented on paddle/fluid/operators/conv_op.cc
> +  }
Yes, it is.

2018-08-17 06:48 UTC, luotao1 commented on paddle/fluid/operators/conv_op.cc
> +  }
how about
```
#ifdef #PADDLE_WITH_MKLDNN
if (ctx->HasInput("Bias")) {
    PADDLE_ENFORCE_EQ(bias_dims.size(), 1, "Conv bias should one-dimensional in MKLDNN.");
  }
#endif
```

2018-08-17 06:48 UTC, luotao1 commented on paddle/fluid/operators/conv_op.cc
> +           "to the number of output channels.")
Could you update the annotation of "Bias", make users know "Bias" in only used in MKLDNN?

2018-08-17 08:29 UTC, luotao1 commented
For code style, you can install `pre-commit` to auto modify the style. see https://github.com/PaddlePaddle/Paddle/blob/develop/CONTRIBUTING.md

2018-08-17 09:05 UTC, Sand3r- commented
Yup, it's done :) sorry, I've forgotten to do it when uploading the latest changes.

2018-08-20 10:20 UTC, Sand3r- commented
In the most recent commit, I have added check for retrieving the Bias tensor, as on some topologies (such as ResNet-50) it was causing crashes, since no "Bias" Tensor could've been found.

2018-08-21 07:52 UTC, Sand3r- commented
I had to remove the dimension check from `InferShape`, since for some reason it was causing conv3d_op test to crash upon calling `ctx->HasInput("Bias")`. This check is already performed at `conv_mkldnn_op.cc:280` anyway.

2018-08-21 11:48 UTC, luotao1 approved these changes
LGTM! Thanks very much!

2018-08-21 11:48 UTC, merged