hange part doc on aankin
PaddlePaddle/Paddle pull request #12856
Opened 2018-08-22 04:15 UTC by chenjiaoAngel

2018-08-22 04:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=12856) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=12856) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=12856) it.</sub>

2018-08-22 08:32 UTC, Superjomn requested changes
fluid 目前也在做 CPU 的性能优化，具体 benchmark 我们自己后续会自行发出

这里的相关 benchmark 也是很久之前测的，不需要列出来

2018-08-22 10:04 UTC, chenjiaoAngel commented
delete 请查阅

2018-09-19 12:28 UTC, shanyi15 commented
close for all the docs will be updated in Fluiddoc Repo

2018-09-19 12:28 UTC, closed without merging