Create a new paddle build option to build documentation library
PaddlePaddle/Paddle pull request #13063
Opened 2018-08-29 20:47 UTC by jetfuel

2018-08-31 04:17 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +        ;;
请加注释，这三个分别有什么区别。lite和lite2的命名能否更规范一点。

2018-08-31 04:17 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +    make -j `nproc` framework_py_proto
这三个函数，除了make这一句不同外，其他都是一样的，因此，能否抽出一个gen_doc_lib_cmake()公共函数。

2018-08-31 05:34 UTC, jetfuel commented on paddle/scripts/paddle_build.sh
> +        ;;
In theory, we only need the gen_doc_lib. however, building gen_doc_lib will timeout and we can't even cache any built library. It is very unfortunately, that `make copy_paddle_pybind` takes about 49 minutes to build  (and Travis CI times out around 50 minutes.) I basically create `gen_doc_lib_lite2 ` in hope just to build a small portion so we can cache.

2018-08-31 05:35 UTC, jetfuel commented on paddle/scripts/paddle_build.sh
> +    make -j `nproc` framework_py_proto
I wish we can actually just need one `gen_doc_lib` function. Is there any we that can speed up the build process even more?

2018-08-31 05:53 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +    make -j `nproc` framework_py_proto
目前没有其他加速的方法了。但travis ci的时间多跑几次有缓存后，会降到10min的。

2018-08-31 05:53 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +        ;;
timeout的话（差不多是44分钟timeout），多跑几次就能过travis ci的。

2018-09-03 03:46 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +}
如果433行-450行不需要的话，可以直接去掉了。

2018-09-03 04:08 UTC, shanyi15 requested changes
为保证0.15.0文档顺利发版，防止此pr被提前merge，先不通过此pr，谢谢

2018-09-14 06:59 UTC, shanyi15 approved these changes
LGTM

2018-09-15 04:45 UTC, merged

2018-09-15 12:31 UTC, luotao1 commented on paddle/scripts/paddle_build.sh
> +}
@shanyi15 433行-450行不需要的话，需要去掉。