Trainer auto wait pserver ports
PaddlePaddle/Paddle pull request #13341
Opened 2018-09-11 08:44 UTC by typhoonzero

2018-09-11 09:19 UTC, gongweibao requested changes

2018-09-11 09:19 UTC, gongweibao commented on python/paddle/fluid/transpiler/details/checkport.py
> +           check_port_open(["127.0.0.1:8080", "127.0.0.1:8081"])
wait_server_ready

2018-09-11 09:19 UTC, gongweibao commented
1. Do we need to clean these? for example:
https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/fluid_benchmark.py#L166
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/distributed/rpc_server.cc#L69

2018-09-11 09:25 UTC, gongweibao commented
是不是用一个OP来实现这个等待更好一点？

2018-09-11 09:38 UTC, typhoonzero commented
@gongweibao 分布式都改到pass里之后可能会需要用op

2018-09-11 09:44 UTC, typhoonzero commented on python/paddle/fluid/transpiler/details/checkport.py
> +           check_port_open(["127.0.0.1:8080", "127.0.0.1:8081"])
Done

2018-09-13 06:11 UTC, gongweibao commented on python/paddle/fluid/transpiler/distribute_transpiler.py
> +    def get_trainer_program(self, wait_port=True):
Maybe we can add  a parameter `dry_run` to control wait or not.

2018-09-13 06:13 UTC, gongweibao approved these changes
LGTM

2018-09-13 06:44 UTC, qingqing01 approved these changes
Approved for API.

2018-09-13 07:26 UTC, reyoung approved these changes

2018-09-13 14:15 UTC, merged