[MKLDNN] Pass: Fuse Conv + Bias
PaddlePaddle/Paddle pull request #13368
Opened 2018-09-12 13:05 UTC by Sand3r-

Fuses Convolution with Elementwise used as bias using Pass mechanism. Applying this fuse at CRNN-CTC when python transpiler and mkldnn was used, **doubled** the number of FPS #12669.

2018-09-24 12:28 UTC, sfraczek requested changes
You may want to take a look how I have skipped deletion of convolution :) 
https://github.com/PaddlePaddle/Paddle/pull/13552

2018-09-24 12:28 UTC, sfraczek commented on paddle/fluid/framework/ir/conv_bias_mkldnn_fuse_pass.cc
> +  std::unordered_set<Node*> nodes2delete;
This looks like unused variable

2018-10-01 13:12 UTC, Sand3r- commented
@sfraczek Unfortunately I cannot reuse the conv op, since setting the bias buffer to inexistant tensor causes the biases to have no assigned operator. As a result aren't linked to anything and remain floating "in air".

2018-10-01 14:16 UTC, sfraczek submitted a review, later dismissed
LGTM!

2018-10-08 13:15 UTC, Sand3r- commented
@luotao1 Is there anything I could do to improve this PR?

2018-10-08 13:52 UTC, luotao1 reviewed
> Is there anything I could do to improve this PR

You can merge the latest code to see whether `conv+bias` fuse pass is successful in `test_analyzer_resnet50`

2018-10-08 13:52 UTC, luotao1 commented on paddle/fluid/framework/naive_executor.cc
> +void NaiveExecutor::EnableMKLDNN(const ProgramDesc &program) {
#13727 has the duplicated code. You can merge with the latest code.

2018-10-09 12:18 UTC, Sand3r- commented
@luotao1 I have enabled MKLDNN in the `test_analyzer_resnet50`, but it fails due to inaccuracy reasons discussed in: #13646 

Can I disabled it for now and have this PR merged and then ask @sfraczek to enable it in his own PR of #13486 which fixes the aforementioned problem?

2018-10-09 16:06 UTC, luotao1 commented
>  Testing it with resnet50 doesn't make much sense without conv+bn fuse, since convolutions in resnet50 don't have their own biases anyway.

The model in `test_analyzer_resnet50` is `conv+elementwise_add+batch_norm`. After conv+bn fuse, it still has `conv+elementwise_add`. Thus, your PR will be used in `test_analyzer_resnet50` case.

2018-10-09 16:09 UTC, luotao1 commented
> Can I disable it for now and have this PR merged

Yes, you can disable MKLDNN in `test_analyzer_resnet50` and have this PR merged at first.

2018-10-11 02:14 UTC, luotao1 approved these changes
LGTM

2018-10-11 02:14 UTC, merged