Add use_cudnn parameters to softmax_with_xe op
PaddlePaddle/Paddle pull request #14087
Opened 2018-10-26 07:30 UTC by sneaxiy

2018-10-26 07:31 UTC, reyoung submitted a review, later dismissed

2018-10-26 11:42 UTC, chengduoZH commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +          ctx, batch_size* feature_size);                                    \
line 307~308 can be placed out of `if ... else ...`.

2018-10-26 13:52 UTC, qingqing01 submitted a review, later dismissed

2018-10-26 14:50 UTC, panyx0718 commented on paddle/fluid/API.spec
> +paddle.fluid.layers.softmax_with_cross_entropy ArgSpec(args=['logits', 'label', 'soft_label', 'ignore_index', 'use_cudnn'], varargs=None, keywords=None, defaults=(False, -100, True))
I don't like putting `use_cudnn` in the API. what if there is other nvidia library, or mkl, mkldnn, ngraph in the future? are we going to put more use_xxx in the api?

2018-10-26 14:52 UTC, panyx0718 requested changes
Can you just make `use_cudnn` the default one? and don't update api? I don't think user will know use_cudnn=False is more stable and use it.

2018-10-30 03:40 UTC, panyx0718 approved these changes
LG API

2018-10-30 05:13 UTC, qingqing01 approved these changes

2018-11-02 13:13 UTC, merged