add generate mask target op
PaddlePaddle/Paddle pull request #14379
Opened 2018-11-13 04:08 UTC by jerrywgz

2018-11-14 11:41 UTC, xingyuanbu requested changes

2018-11-14 11:41 UTC, sefira commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +                wh = xywh[2:4] * (16 - xy1)
Don't hard write 16 for image size

2018-11-14 11:41 UTC, sefira commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +                roi = [bno, xy1[0], xy1[1], xy2[0], xy2[1]]
bno is unnecessary

2018-11-14 12:57 UTC, jerrywgz commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +                wh = xywh[2:4] * (16 - xy1)
Done

2018-11-14 12:58 UTC, jerrywgz commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +                roi = [bno, xy1[0], xy1[1], xy2[0], xy2[1]]
Removed

2018-11-14 14:15 UTC, xingyuanbu requested changes

2018-11-14 14:15 UTC, sefira commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +        boxes_from_masks[i, :] = np.array([xmin, ymax, xmin, ymax],\
xmin, ymax, xmin, ymax, typo?

2018-11-15 02:12 UTC, jerrywgz commented on python/paddle/fluid/tests/unittests/test_generate_mask_target_op.py
> +        boxes_from_masks[i, :] = np.array([xmin, ymax, xmin, ymax],\
Fixed

2018-11-21 04:13 UTC, closed without merging