Optimize the layer_norm operator with AVX intrinsic function
PaddlePaddle/Paddle pull request #14417
Opened 2018-11-15 02:56 UTC by yihuaxu

According to the performance status of Layer Norm, just implemented the intrinsic function's optimization to accelerate the data processing.

Platform: Intel(R) Xeon(R) Gold 6151 CPU @ 2.30GHz / Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
Batch Size: 1
Command: build/paddle/fluid/inference/tests/api/test_analyzer_dam --infer_model=PaddlePaddle/pretrained_models/dam --infer_data=third_party/inference_demo/dam/data.txt --gtest_filter=Analyzer_dam.profile --batch_size=1 --repeat=1 --test_all_data=true --num_threads=1 --use_analysis=false 

The following is the comparison with the different scenarios.
![image](https://user-images.githubusercontent.com/4131969/48527141-1b5bc300-e8c5-11e8-94b2-1f7b15d1b967.png)

2018-11-15 03:09 UTC, yihuaxu commented
@tensor-tang @luotao1 Please help us review this PR

2018-11-16 04:37 UTC, tensor-tang approved these changes
Thanks for your contribution @yihuaxu 

The jit_kernel is migrating to jit code, and we are using jitcode to generate the runtime code on different platform, instead of using intrinsic now. 

We will let you know when it's ready.

2018-11-16 04:38 UTC, tensor-tang commented on paddle/fluid/operators/CMakeLists.txt
> +        op_library(layer_norm_op DEPS jit_kernel)
As for windows part @dzhwinter is this ok to you?

2018-11-16 06:12 UTC, tensor-tang requested changes
@yihuaxu 我突然意识到这部分code在Mac也需要被注释掉吧，我们线下也会测试Mac上的单测。

2018-11-16 06:12 UTC, tensor-tang commented on paddle/fluid/operators/CMakeLists.txt
> +        op_library(layer_norm_op DEPS jit_kernel)
这一部分与@dzhwinter @wopeizl 沟通后是没什么问题。

2018-11-19 08:29 UTC, yihuaxu reviewed
Remove the remnant code

2018-11-19 10:26 UTC, tensor-tang approved these changes

2018-11-19 10:28 UTC, merged