Transpose-Flatten-Concat fusion operator.
PaddlePaddle/Paddle pull request #14568
Opened 2018-11-23 13:10 UTC by qingqing01

Support patter:

```
concat _op [ flatten_op(transpose(x1)),   flatten_op(transpose(x2)), flatten_op(transpose(x3)), .... ]
```

like:

<img width="889" alt="default" src="https://user-images.githubusercontent.com/7845005/48945104-18676f00-ef64-11e8-96db-a1a136dedfd7.png">

2018-11-23 13:15 UTC, Superjomn submitted a review, later dismissed
LGTM

2018-11-23 13:16 UTC, Superjomn requested changes
fix the CMakeFiles

2018-11-23 13:16 UTC, Superjomn commented on paddle/fluid/CMakeLists.txt
> +#add_subdirectory(inference)
recover these

2018-11-23 13:18 UTC, qingqing01 commented on paddle/fluid/CMakeLists.txt
> +#add_subdirectory(inference)
Done, thanks!

2018-11-23 13:19 UTC, Superjomn approved these changes
LGTM

2018-11-26 07:54 UTC, qingqing01 commented
The doc will update in next PR.

2018-11-26 07:54 UTC, merged