Remove BinarySearch from Adam Op
PaddlePaddle/Paddle pull request #14891
Opened 2018-12-14 05:31 UTC by velconia

针对CPU情况，假设参数大小为 N, 梯度大小为M, 则原有算法复杂度为 O(N * M * log(M))
修改后，复杂度为: O(M * log(M) + N);

this is for #14861

2018-12-21 05:59 UTC, jacquesqiao commented on paddle/fluid/operators/optimizers/adam_op.h
> +struct SparseAdamFunctor<T, CPUAdam> {
Can this functor be merged to SparseAdamFunctor?

2018-12-21 06:27 UTC, velconia commented on paddle/fluid/operators/optimizers/adam_op.h
> +struct SparseAdamFunctor<T, CPUAdam> {
Good advice, GPU part will be fixed in the follow ups

2018-12-21 08:02 UTC, jacquesqiao commented on paddle/fluid/operators/optimizers/adam_op.h
> +          T mom1 = moment1_[i * row_numel_ + k];
can call 
```cpp
inline HOSTDEVICE void adam_update(size_t i, T g) const {}
```
directly

2018-12-21 08:08 UTC, jacquesqiao commented on paddle/fluid/operators/optimizers/adam_op.h
> +          T mom1 = moment1_[i * row_numel_ + k];
can call 
```cpp
inline HOSTDEVICE void adam_update(size_t i, T g) const {}
```
directly

2018-12-21 08:12 UTC, jacquesqiao commented on paddle/fluid/operators/optimizers/adam_op.h
>          platform::ForRange<DeviceContext> for_range(
GPU should support lazy mode

2018-12-21 08:24 UTC, jacquesqiao commented
Please pull the develop code and run test again.

2018-12-21 08:25 UTC, jacquesqiao requested changes
Please pull the develop code and run test again.

2018-12-25 08:00 UTC, jacquesqiao approved these changes
LGTM

2018-12-25 08:00 UTC, merged