add mkl,ctc support for windows
PaddlePaddle/Paddle pull request #14931
Opened 2018-12-18 03:37 UTC by wopeizl

2018-12-18 03:42 UTC, luotao1 requested changes
mkl的windows支持能否单独提一个PR呢？因为mkl有专门的windows包：https://github.com/intel/mkl-dnn/releases/tag/v0.17 中的mklml_win_2019.0.1.20180928.zip。

2018-12-18 05:40 UTC, wopeizl commented
Now there is mkl related fixes only.

2018-12-18 05:46 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
因为mkl有专门的windows包：https://github.com/intel/mkl-dnn/releases/tag/v0.17 中的mklml_win_2019.0.1.20180928.zip，可以下载这个包，而不是让用户自己下载么

2018-12-18 05:50 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
This package is pretty large and we would recommend users to download by themseleves as we have done to openblas.
Anyway, we can add it into the script to make the automatically download if insist, maybe add this package into CDN would be a better choice.

2018-12-18 06:10 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
> maybe add this package into CDN would be a better choice.

请放到CDN上把，windows的mkl只有29MB，linux的mkl有69.5MB，也是放到CDN上了。

> we would recommend users to download by themseleves as we have done to openblas

用户并不知道如何下载。openblas是开源的，和mkl不太一样。

2018-12-18 06:11 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
同时，需要验证windows上使用mkl的win版本，编译+单测是否都能过。

2018-12-18 06:12 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
好

2018-12-18 06:21 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    "Please download the MKLML and and put it at " ${THIRD_PARTY_PATH}/install/mklml)
linux的包还停留在：https://github.com/intel/mkl-dnn/releases/tag/v0.16 ，可以一起升级，或者一起维持现状。

2018-12-19 06:30 UTC, luotao1 reviewed
windows上能跑mkldnn么？可以先把mkl的win32开了，再看mkldnn么？

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/cub.cmake
> +LIST(APPEND external_project_dependencies cub)
`cub.cmake` and `dlpack.cmake`可以不用更新，和mkl没关系。

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/mklml.cmake
> +        SET(MKLML_URL "https://github.com/intel/mkl-dnn/releases/download/v0.16/${MKLML_VER}.zip" CACHE STRING "" FORCE)
请将win的包放到cdn上。

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/python.cmake
>  if(WIN32)
请问为什么要修改`python.cmake`，和mkl没关系

2018-12-19 06:30 UTC, luotao1 commented on cmake/inference_lib.cmake
> +            )
请问为什么要修改这个文件？WIN32支持MKL后，就不会走elseif这个分支，那逻辑保持原来一致即可。

2018-12-19 06:30 UTC, luotao1 commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +#if defined(PADDLE_WITH_CUDA) && !defined(_WIN32)
这个文件和mkl无关，可以不在这个PR里修改。

2018-12-19 06:30 UTC, luotao1 commented on paddle/fluid/operators/elementwise/elementwise_mul_mkldnn_op.cc
> +#endif
为什么只在这一个elementwise_mul_mkldnn_op.cc里面加呢？
能否加到`mkldnn_helper.h`里呢？

2018-12-19 06:30 UTC, luotao1 commented on paddle/fluid/platform/port.h
> +#endif
这个文件的修改和mkl有关么？

2018-12-19 06:30 UTC, luotao1 commented on paddle/fluid/train/demo/CMakeLists.txt
>  if(WITH_MKLDNN)
train/demo请 @jacquesqiao review下。

2018-12-19 06:30 UTC, luotao1 commented on python/setup.py.in
> +    if os.name == 'nt':
请问nt是什么？是windows标志么？能否加comment说明下

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/mklml.cmake
>      DOWNLOAD_NO_PROGRESS  1
为什么把`DOWNLOAD_COMMAND`给去掉了？那无法自动下载了。

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/mklml.cmake
> -  "        DESTINATION ${MKLML_DST_DIR})\n")
为什么把`FILE(WRITE `给删了？

2018-12-19 06:30 UTC, luotao1 commented on cmake/external/mklml.cmake
>  INCLUDE(ExternalProject)
对mklml.cmake, 应该只是换一下下载包的路径和名字，其他地方基本可以维持一样。

2018-12-19 06:50 UTC, wopeizl commented on cmake/inference_lib.cmake
> +            )
win下openblas和mkl都会设置CBLAS_FOUND，而且没有预装blas库的情况，所以调整后保证win下两个库必选其一

2018-12-19 06:51 UTC, wopeizl commented on paddle/fluid/operators/elementwise/elementwise_mul_mkldnn_op.cc
> +#endif
这个flag只对xbyak有影响，因为xbyak在win默认会加载一些操作系统相关的库，与当前设置冲突

2018-12-19 06:51 UTC, wopeizl commented on paddle/fluid/platform/port.h
> +#endif
有，mkl会引入xbyak，产生冲突

2018-12-19 06:52 UTC, wopeizl commented on python/setup.py.in
> +    if os.name == 'nt':
是。。。

2018-12-19 06:52 UTC, wopeizl commented on cmake/external/mklml.cmake
>  INCLUDE(ExternalProject)
tar在win下不支持

2018-12-19 06:53 UTC, wopeizl commented on cmake/external/mklml.cmake
> -  "        DESTINATION ${MKLML_DST_DIR})\n")
不需要了，externproject_Add中的参数就能做到

2018-12-19 06:53 UTC, wopeizl commented on cmake/external/mklml.cmake
>      DOWNLOAD_NO_PROGRESS  1
可以。。。URL指定了

2018-12-19 07:01 UTC, luotao1 commented on cmake/external/mklml.cmake
>      DOWNLOAD_NO_PROGRESS  1
URL指定后，tar那步在哪里做呢？

2018-12-19 07:01 UTC, wopeizl commented on cmake/external/python.cmake
>  if(WIN32)
removed

2018-12-19 07:02 UTC, wopeizl commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +#if defined(PADDLE_WITH_CUDA) && !defined(_WIN32)
removed

2018-12-19 07:04 UTC, luotao1 commented on cmake/inference_lib.cmake
> +            )
可以不调整，这样win下默认会选择mkl了。

2018-12-19 08:12 UTC, tensor-tang commented on cmake/external/mklml.cmake
> +    ADD_DEPENDENCIES(mklml ${MKLML_PROJECT})
这个为什么win不需要deps

2018-12-19 08:12 UTC, tensor-tang commented on cmake/external/xbyak.cmake
> +if(APPLE)
这个library不属于mkl的范畴

2018-12-19 08:12 UTC, tensor-tang commented on cmake/generic.cmake
> +          target_link_libraries(${TARGET_NAME} ${MKLML_IOMP_LIB})
window下不使用iomp的flag，可以正确link到下载的iomp5吗。

2018-12-19 08:12 UTC, tensor-tang commented on paddle/fluid/operators/elementwise/elementwise_mul_mkldnn_op.cc
> +#endif
做mkl的enable不要考虑xbyak吧，xbyak目前window下不是重点，在window上目前也根本没有用到，所以enable了之后只会使得后面开发linux下的xbyak的功能变得很复杂。

2018-12-19 08:12 UTC, tensor-tang commented on paddle/fluid/platform/port.h
> +#endif
> mkl会引入xbyak

mkl并不会**引入**xbyak。
mkl，mkldnn和xbyak是3个独立的library，mkldnn可以依赖mkl，也可以不依赖，paddle目前是依赖的。
但是xbyak跟着两者都没有关系。mkldnn自己在code里面写死了xbyak。
所以不明白这里为什么会产生冲突，指的是什么？

2018-12-19 08:21 UTC, tensor-tang requested changes
Great work @wopeizl , window在这三者的支持是个很重要的工作，能做好不容易，但是我建议我们分开来做。

xbyak在window上的支持不属于mkl的一部分，这个功能的enable会导致linux下开发xbayk的性能变得很复杂，并且linux下的功能都还完善中，并且在window下只有mkldnn的elementwise mul 可能用到了xbyak（这部分还要挪走），这是属于mkldnn的window支持的一部分，
所以建议先不要enable xbyak的windows。

另外mkldnn依赖mkl，支持mkl的window的过程中如果遇到mkldnn的编译问题，可以暂时先disable掉，应该就不会遇到xbyak的问题。

2018-12-19 08:21 UTC, tensor-tang commented on paddle/fluid/operators/math/jit_gen.h
> +#endif
这里如果不考虑xbyak的enable，应该可以不用加吧

2018-12-19 08:21 UTC, tensor-tang commented on paddle/fluid/operators/math/detail/lstm_cpu_kernel.h
> +
这个哪里用到了？

2018-12-19 08:22 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    ADD_DEPENDENCIES(mklml ${MKLML_PROJECT})
这个是弄错了，加回来

2018-12-19 08:23 UTC, wopeizl commented on cmake/generic.cmake
> +          target_link_libraries(${TARGET_NAME} ${MKLML_IOMP_LIB})
这个就是用来link的

2018-12-19 08:23 UTC, wopeizl commented on paddle/fluid/operators/math/jit_gen.h
> +#endif
可以，那就去掉

2018-12-19 08:24 UTC, wopeizl commented on paddle/fluid/operators/math/detail/lstm_cpu_kernel.h
> +
windows编译检查会查到操作符不支持

2018-12-19 09:17 UTC, tensor-tang commented on cmake/generic.cmake
> +          target_link_libraries(${TARGET_NAME} ${MKLML_IOMP_LIB})
我的意思是这里link为什么要区分win，和linux保持一致不可以吗。因为这里linux下一般的link是会link到系统gomp，所以特意制定了下。window下是不是也需要确认下。

2018-12-19 09:44 UTC, wopeizl commented on paddle/fluid/platform/port.h
> +#endif
xbyak 在win下会引入一些文件，比如winsock2.h，这个默认情况下和默认的win头文件windows.h是冲突的，解决方案就是加一些限定条件，来规避冲突

2018-12-19 10:40 UTC, tensor-tang commented on paddle/fluid/platform/port.h
> +#endif
嗯，看起来跟mkl还是无关的吧。

2018-12-19 10:44 UTC, tensor-tang commented on paddle/fluid/operators/elementwise/elementwise_mul_mkldnn_op.cc
> +#endif  // PADDLE_WITH_XBYAK
不需要加xbyak的宏，可以直接替换原来的。

2018-12-19 12:19 UTC, wopeizl commented on paddle/fluid/operators/elementwise/elementwise_mul_mkldnn_op.cc
> +#endif  // PADDLE_WITH_XBYAK
ok

2018-12-19 17:39 UTC, tensor-tang commented on cmake/external/mklml.cmake
> +        SET(MKLML_URL "https://github.com/intel/mkl-dnn/releases/download/v0.16/${MKLML_VER}.zip" CACHE STRING "" FORCE)
这里好像还是并没有用cdn上的？

2018-12-19 17:41 UTC, tensor-tang submitted a review, later dismissed
LGTM for my part.

2018-12-20 05:57 UTC, wopeizl commented on cmake/external/mklml.cmake
> +        SET(MKLML_URL "https://github.com/intel/mkl-dnn/releases/download/v0.16/${MKLML_VER}.zip" CACHE STRING "" FORCE)
done

2018-12-20 10:31 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    ENDIF()
```
if(WIN32)
  SET(MKLML_VER "mklml_win_2019.0.20180710" CACHE STRING "" FORCE)
else()
   SET(MKLML_VER "mklml_lnx_2019.0.20180710" CACHE STRING "" FORCE)
ENDIF()
SET(MKLML_URL "http://paddlepaddledeps.cdn.bcebos.com/${MKLML_VER}.tgz" CACHE STRING "" FORCE)
```
51和54行重复，可以去掉一个

2018-12-20 10:31 UTC, luotao1 commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
为什么要加64-69行？

2018-12-20 10:31 UTC, luotao1 commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
为什么加72行，CMAKE_POSITION_INDEPENDENT_CODE是什么用呢？

2018-12-20 10:31 UTC, luotao1 commented on paddle/fluid/train/demo/CMakeLists.txt
>  if(WITH_MKLDNN)
train/demo不确定是否需要修改，请咨询下 @jacquesqiao

2018-12-20 10:31 UTC, luotao1 commented on python/setup.py.in
> +    if os.name == 'nt':
请加comment说下nt是什么。

2018-12-20 10:31 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    SET(MKLML_SHARED_IOMP_LIB     ${MKLML_LIB_DIR}/libiomp5.so)
40-43行，`MKLML_LIB`和`MKLML_SHARED_LIB`是重复的，`MKLML_IOMP_LIB`和`MKLML_SHARED_IOMP_LIB`也是重复的，为什么要定义两遍呢？

2018-12-20 10:31 UTC, luotao1 commented on cmake/inference_lib.cmake
>              DSTS ${dst_dir}/lib ${dst_dir}/lib ${dst_dir}
请问这里验证过么？linux下拷贝`MKLML_IOMP_LIB`和`MKLML_LIB`两个包就够了，win下有四个包，只拷贝两个就够了？
win下的预测代码能跑通么？

2018-12-20 10:31 UTC, luotao1 commented on cmake/inference_lib.cmake
> +            )
这里的逻辑不建议换。

2018-12-20 10:31 UTC, luotao1 commented on paddle/fluid/inference/api/demo_ci/CMakeLists.txt
> +            ${PADDLE_LIB}/third_party/install/mklml/lib/libiomp5md${CMAKE_SHARED_LIBRARY_SUFFIX})
win包里有4个，这里只需要2个就够了？如果验证过只需要2个，mklml.cmake里就不用写4个变量。https://github.com/PaddlePaddle/Paddle/pull/14931/files#diff-bb6e47700dda71cb10714ade0931f849R35

2018-12-20 10:31 UTC, luotao1 commented on python/setup.py.in
> +    shutil.copy('${MKLML_SHARED_IOMP_LIB}', libs_path)
167和168行，维持和原来一样把。

2018-12-20 10:31 UTC, luotao1 commented on python/setup.py.in
> +        package_data['paddle.libs'] += ['openblas' + ext_name]
173行的逻辑不太对，在`if '${WITH_MKL}' == 'ON':`的情况下，拷贝openblas的内容？

2018-12-20 10:31 UTC, luotao1 commented on python/setup.py.in
> +        if os.name != 'nt':
179-188行不用缩进。将177行和178行合并在一行即可。
`if '${CMAKE_BUILD_TYPE}' == 'Release' and os.name != 'nt':`

2018-12-20 10:31 UTC, luotao1 commented on paddle/fluid/platform/port.h
> +#endif
> 嗯，看起来跟mkl还是无关的吧。

为什么还要修改呢？

2018-12-20 11:15 UTC, wopeizl commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
debug支持选项是不一样的

2018-12-20 11:15 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    SET(MKLML_SHARED_IOMP_LIB     ${MKLML_LIB_DIR}/libiomp5.so)
。。。win下导出符号跟linux不一样的，两种不同的文件

2018-12-20 11:15 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    ENDIF()
url不一样

2018-12-20 11:16 UTC, wopeizl commented on cmake/inference_lib.cmake
>              DSTS ${dst_dir}/lib ${dst_dir}/lib ${dst_dir}
不同的后缀名的包不同的用途

2018-12-20 11:16 UTC, wopeizl commented on paddle/fluid/inference/api/demo_ci/CMakeLists.txt
> +            ${PADDLE_LIB}/third_party/install/mklml/lib/libiomp5md${CMAKE_SHARED_LIBRARY_SUFFIX})
不同的后缀名的包不同的用途

2018-12-20 11:16 UTC, wopeizl commented on python/setup.py.in
> +    shutil.copy('${MKLML_SHARED_IOMP_LIB}', libs_path)
？改是有原因的 ，

2018-12-20 11:18 UTC, wopeizl commented on python/setup.py.in
> +        if os.name != 'nt':
ok

2018-12-20 11:23 UTC, wopeizl commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
1. keep consistence with other cmake script
2. https://cmake.org/cmake/help/v3.4/command/try_compile.html#command:try_compile

2018-12-20 11:25 UTC, wopeizl commented on python/setup.py.in
> +        package_data['paddle.libs'] += ['openblas' + ext_name]
??? It can be reached when mkl is off

2018-12-20 11:27 UTC, wopeizl commented on python/setup.py.in
> +    shutil.copy('${MKLML_SHARED_IOMP_LIB}', libs_path)
.lib is different with .dll, that is the difference with .so

2018-12-20 11:28 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    ENDIF()
没有重复

2018-12-20 11:28 UTC, wopeizl commented on cmake/external/mklml.cmake
> +    SET(MKLML_SHARED_IOMP_LIB     ${MKLML_LIB_DIR}/libiomp5.so)
用处不一样

2018-12-20 11:31 UTC, luotao1 commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
> debug支持选项是不一样的

如果只有debug支持选项不一样，只要改debug那一行即可。

2018-12-20 11:31 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    ENDIF()
可以放到paddlepaddledeps么？也便于后续一起更新

2018-12-20 11:31 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    ENDIF()
可以放到paddlepaddledeps么，也便于后续一起更新

2018-12-20 11:31 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    SET(MKLML_SHARED_IOMP_LIB     ${MKLML_LIB_DIR}/libiomp5md.dll)
这里35-38行说明下，MKLML_LIB和MKLML_IOMP_LIB用于C++代码，MKLML_SHARED_LIB和MKLML_SHARED_IOMP_LIB用于whl包？（我的理解可能不太准确，但从后面代码的用法看是这样的）

2018-12-20 11:35 UTC, luotao1 commented on python/setup.py.in
> +        package_data['paddle.libs'] += ['openblas' + ext_name]
`else if os.name == 'nt':`
请问windows下的openblas不是源码编译的么？

2018-12-21 03:10 UTC, wopeizl commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
根cmakelists.txt文件中定义了/MT /MTD选项分别对应release和debug模式，这样做第一是为了把这些flags标记都传过来，第二点是在后续更新中（比如警告项调整），只需要调整根级别文件就可以了

2018-12-21 03:10 UTC, wopeizl commented on python/setup.py.in
> +        package_data['paddle.libs'] += ['openblas' + ext_name]
openblas不支持windows原生编译，需要调整，所以是预编译包

2018-12-21 03:15 UTC, luotao1 commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
- 编译第三方库，不一定需要和paddle同样的编译选项，还是维持现状比较好。
- debug编译不过，也不要使用paddle的debug编译选项，直接加上编译不过的命令即可。

2018-12-21 05:28 UTC, wopeizl commented on cmake/external/mkldnn.cmake
> +    CMAKE_ARGS          -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
默认是/MD，会链接错误

2018-12-21 08:02 UTC, luotao1 reviewed
LGTM！解决下冲突吧

2018-12-21 08:02 UTC, luotao1 commented on cmake/external/mklml.cmake
> +    ENDIF()
放到paddlepaddledeps后，可以去掉重复的54行了。

2018-12-24 02:26 UTC, luotao1 approved these changes

2018-12-24 02:26 UTC, merged