refactor rpc base framework
PaddlePaddle/Paddle pull request #15135
Opened 2019-01-02 05:48 UTC by typhoonzero

2019-01-28 03:31 UTC, seiriosPlus commented on paddle/fluid/operators/distributed/handlers/get_handler.cc
> +    const std::string& varname, RPCRequest* request) {
```request ``` is not be used.

2019-01-28 09:20 UTC, gongweibao requested changes

2019-01-28 09:20 UTC, gongweibao commented on cmake/generic.cmake
> +  # set_source_files_properties(
Clean up?

2019-01-28 09:20 UTC, gongweibao commented on paddle/fluid/operators/distributed/brpc/brpc_server.cc
> +      // rpc_server_->GetThreadNum(distributed::kRequestGetNoBarrier)));
Why not use the registed threadnum?

2019-01-28 09:20 UTC, gongweibao commented on paddle/fluid/operators/distributed/brpc/brpc_server.cc
> +      // rpc_server_->GetThreadNum(distributed::kRequestPrefetch)));
Clean?

2019-01-28 09:20 UTC, gongweibao commented on paddle/fluid/operators/distributed/brpc/brpc_server.cc
> +      // rpc_server_->GetThreadNum(distributed::kRequestPrefetch)));
Clean?

2019-01-29 03:20 UTC, typhoonzero commented on paddle/fluid/operators/distributed/brpc/brpc_server.cc
> +      // rpc_server_->GetThreadNum(distributed::kRequestPrefetch)));
Done.

2020-05-22 06:42 UTC, closed without merging