Add check: conv_fusion op runs with cudnn version > 7100 .
PaddlePaddle/Paddle pull request #15504
Opened 2019-01-24 03:56 UTC by NHZlX

2019-01-24 03:59 UTC, luotao1 requested changes
这个修改不太对吧，应该在cudnn5的时候，把conv2d_fuse的pass给去掉，而不是关掉整个demo。这个demo应该在cudnn5的时候也要能跑。

2019-01-24 05:31 UTC, luotao1 commented
请重跑下 http://ci.paddlepaddle.org/viewLog.html?buildId=52577&buildTypeId=Manylinux1_Cuda80cudnn5cp27cp27mu&tab=buildLog ，保证能在manylinux上过。

2019-01-24 06:41 UTC, qingqing01 approved these changes
LGTM.

2019-01-25 02:58 UTC, luotao1 approved these changes

2019-01-25 02:59 UTC, merged