init lite
PaddlePaddle/Paddle pull request #15908
Opened 2019-02-25 05:55 UTC by Superjomn

2019-05-14 10:28 UTC, luotao1 commented on CMakeLists.txt
> +option(LITE_WITH_LIGHT_WEIGHT_FRAMEWORK  "Enable light-weight framework" OFF)
light-weight framework和lite framework有什么区别呢？注释能否更清晰一点。
`LITE_WITH_LIGHT_WEIGHT_FRAMEWORK`这个是指mobile么？这个选项改成`LITE_WITH_MOBILE`?是否更清晰

2019-05-14 10:28 UTC, luotao1 commented on CMakeLists.txt
> +
可去掉113，116，118，120多余的空行。

2019-05-14 10:28 UTC, luotao1 commented on cmake/configure.cmake
> +endif(WITH_WBAES)
请问`WITH_WBAES`是用在哪里呢？没有看到这个选项。

2019-05-14 10:28 UTC, luotao1 commented on paddle/CMakeLists.txt
>  add_subdirectory(fluid)
```
add_subdirectory(fluid)
if (NOT LITE_WITH_LIGHT_WEIGHT_FRAMEWORK)
  return()
endif()
add_subdirectory(scripts)
add_subdirectory(testing)
set(PYTHON_TESTS_DIR ${PADDLE_BINARY_DIR}/python/paddle/fluid/tests CACHE INTERNAL "python tests directory")
```
这样更加清晰。

2019-05-14 10:28 UTC, luotao1 commented on paddle/fluid/CMakeLists.txt
> +add_subdirectory(lite)
17行重复加了`add_subdirectory(lite)`？
是想表达lite这个目录一直都要加么？下面改法可能更为清晰。
```
add_subdirectory(lite)
if (LITE_WITH_LIGHT_WEIGHT_FRAMEWORK)
  return()
endif()
add_subdirectory(memory)
...
```

2019-05-14 10:28 UTC, luotao1 commented on paddle/fluid/framework/CMakeLists.txt
> +    shape_inference data_transform lod_tensor profiler transfer_scope_cache op_kernel_type data_feed_proto)
data_feed_proto是从哪儿来的？

2019-05-15 07:50 UTC, Superjomn commented on CMakeLists.txt
> +option(LITE_WITH_LIGHT_WEIGHT_FRAMEWORK  "Enable light-weight framework" OFF)
暂时不会暴露 mobile 的信息，轻量级框架不分平台和硬件

2019-05-15 07:53 UTC, Superjomn commented on paddle/fluid/framework/CMakeLists.txt
> +    shape_inference data_transform lod_tensor profiler transfer_scope_cache op_kernel_type data_feed_proto)
这个是framework 里的依赖有问题，加上才能正常编译

2019-05-15 07:56 UTC, XiaoguangHu01 submitted a review, later dismissed

2019-05-15 12:25 UTC, jacquesqiao requested changes
这个pr还是慎重点吧..

2019-05-15 12:36 UTC, Superjomn commented
这个一阶段是预测的迁移 @jacquesqiao

2019-05-15 13:55 UTC, jacquesqiao approved these changes
这个操作只是为了撤销 request change

2019-05-15 13:57 UTC, jacquesqiao commented on paddle/fluid/framework/framework.proto
> +//option optimize_for = LITE_RUNTIME;
what is the purpose of this line?

2019-05-15 14:00 UTC, jacquesqiao commented on paddle/fluid/framework/op_desc.h
> +  explicit OpDesc(const proto::OpDesc &desc, BlockDesc *block = nullptr);
only constructor with one parameter need to add `explict`

2019-05-15 14:13 UTC, Superjomn commented
More validation will be done later, close temporarily.

2019-05-15 14:13 UTC, closed without merging