Detection output layer for SSD
PaddlePaddle/Paddle pull request #1593
Opened 2017-03-09 11:10 UTC by Noplz

Split from #1158
Detection_output layer 负责将SSD网络预测的结果进行处理得到最终的bounding box的位置以及分类结果。
Reference:https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/detection_output_layer.cpp

2017-03-17 06:52 UTC, qingqing01 requested changes

2017-03-17 06:52 UTC, qingqing01 commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  // Each layer input has different size
Each layer input ->  Each input layer

2017-03-17 06:52 UTC, qingqing01 commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +    confOffset += confChannels * imgPixels;
NCHW -> NHWC的转换作为Matrix的一个公共函数会比较好~

2017-03-17 06:52 UTC, qingqing01 commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  resetOutput(numKept, 7);
7 会是一个固定值吗？

2017-03-17 07:03 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  }
应该是3种输入的层 一个是产生的anchor这个只有一个输入，Location和Confidence的输入数量是一样的但是可能不止一个

2017-03-17 07:11 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  resetOutput(numKept, 7);
是定值 分别是 ImageId, label, confidence, xmin, ymin, xmax, ymax 稍后添加注释

2017-03-17 07:16 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> + * - Input: This layer need three input layers: This first input layer
已修改

2017-03-17 07:16 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> + * - Output: The predict bounding box location.
已修改

2017-03-17 07:17 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  // Each layer input has different size
已修改

2017-03-17 07:21 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +  size_t keepTopK_;
已修改

2017-03-17 07:33 UTC, Noplz commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +    confOffset += confChannels * imgPixels;
这里我是照着BatchNormalizationLayer的NCHW->NHWC写的。。。

2017-03-17 07:46 UTC, qingqing01 commented on paddle/gserver/layers/DetectionOutputLayer.cpp
> +    confOffset += confChannels * imgPixels;
可以先只改这里~

2019-02-01 04:38 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:38 UTC, closed without merging