Refine ParallelExecutor
PaddlePaddle/Paddle pull request #16393
Opened 2019-03-22 09:01 UTC by chengduoZH

2019-03-23 12:17 UTC, gongweibao submitted a review, later dismissed
单测好像有问题呀。

2019-03-26 11:13 UTC, panyx0718 commented on paddle/fluid/framework/details/build_strategy.cc
> +        // all_reduce_deps_pass here.
how much faster?

2019-03-26 11:13 UTC, panyx0718 commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +    sync_nccl_allreduce, true,
how much faster?

2019-03-28 10:59 UTC, gongweibao commented on paddle/fluid/framework/details/all_reduce_deps_pass.cc
> +  if (VLOG_IS_ON(10)) {
Maybe we can split it to a function.

2019-03-28 10:59 UTC, gongweibao commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +    sync_nccl_allreduce, true,
It's not useful now:
With sync:
![image](https://user-images.githubusercontent.com/10721757/55152463-6ba83300-518b-11e9-8d27-2a3d61646e1f.png)

Withou sync:
![image](https://user-images.githubusercontent.com/10721757/55152483-782c8b80-518b-11e9-9a67-6e60fbd1b9c6.png)

2019-03-28 11:00 UTC, gongweibao commented on paddle/fluid/framework/details/build_strategy.cc
> +    if (strategy.reduce_ == BuildStrategy::ReduceStrategy::kAllReduce) {
赞。终于统一了。

2019-04-02 07:10 UTC, gongweibao requested changes

2019-04-02 07:10 UTC, gongweibao commented on paddle/fluid/framework/details/all_reduce_deps_pass.cc
> +      out << "Oder " << var.first << " [";
输出这行和141行，不利于对比。

2019-04-02 07:10 UTC, gongweibao commented on paddle/fluid/framework/details/all_reduce_deps_pass.cc
> +           return left_in_vars[0]->Name() < right_in_vars[0]->Name();
\>

2019-04-02 07:17 UTC, gongweibao submitted a review, later dismissed
LGTM

2019-04-02 11:35 UTC, chengduoZH commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +    sync_nccl_allreduce, true,
About 10%.

2019-04-02 11:54 UTC, gongweibao approved these changes

2019-04-03 00:17 UTC, merged