Design Draft for using map in protobuf.
PaddlePaddle/Paddle pull request #1665
Opened 2017-03-21 04:22 UTC by reyoung

这是使用代码生成 Paddle Layer配置的一部分设计。目的是解耦 Paddle C++中Layer的实现，和Paddle Protobuf消息。

2017-03-21 04:48 UTC, typhoonzero commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +现阶段如何编写一个Layer呢？可以参考[文章](http://www.paddlepaddle.org/doc/dev/new_layer/index.html)。主体可以分为一下几个步骤:
一下 => 以下

2017-03-21 04:48 UTC, typhoonzero commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +   required string type = 2;
是否需要description字段，文字描述这个layer？

2017-03-21 05:34 UTC, jacquesqiao commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* `oneof`与`map`是`protobuf2`语法，但是这是在`Protobuf 3.0`之后的代码库中添加的功能，如果Paddle依赖这个功能，那么Paddle必须依赖Protobuf 3.0以上的Protobuf版本。
看到有地方是oneof是比较晚的protobuf2版本才支持，这个有说明文章的链接么，了解下细节

2017-03-21 05:36 UTC, jacquesqiao commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +	* 需要先完善config_parser的单测，增加单测覆盖率
新旧两种方式又共存的可能性么，比如老的还在，新的重新在另外一个地方加入，但是parse的时候拼接在一起，然后逐步替换，还是说直接修改老的config_parser更加合理

2017-03-21 06:17 UTC, QiJune commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +
这里是用户在C++代码里面说明Layer的属性吗？
然后用户在Python配置Layer时获取这些属性，所以需要在C++中暴露出这个获取属性的api？

2017-03-21 06:32 UTC, QiJune commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* 解决办法: 用`map`和`oneof`，将属性变成一个多种类型的字典
这个字典是否可以考虑直接用C++里面的map来做呢？即给每一个Layer定义一个map成员变量，用来描述属性，干脆移除proto中LayerConfig，Attribute这两个message。

2017-03-21 06:47 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +   required string type = 2;
这里的LayerConfig是每一个Layer实际的一些参数，例如某一个具体的fc_layer的size是多大，activation是啥。

Description写到了LayerDef里面，LayerDef是说一个FC Layer可以有哪些参数，在那里面加一个Description作为Layer的注释即可。

2017-03-21 06:49 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +
参见第一个`00.how_to_write_a_layer.md`

2017-03-21 06:50 UTC, typhoonzero commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +   required string type = 2;
明白了！

2017-03-21 06:52 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* `oneof`与`map`是`protobuf2`语法，但是这是在`Protobuf 3.0`之后的代码库中添加的功能，如果Paddle依赖这个功能，那么Paddle必须依赖Protobuf 3.0以上的Protobuf版本。
https://developers.google.com/protocol-buffers/docs/proto#oneof

我记得官网之前有一些说明，但是现在我找不到了，你可以google再搜一下。。

map和oneof应该是protobuf2的library都不支持的，只有protobuf3的library支持。但是map和oneof是proto2的语法(Syntax)。

2017-03-21 06:54 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* 解决办法: 用`map`和`oneof`，将属性变成一个多种类型的字典
理论上当然可以。但是现实里会比较麻烦。

Protobuf在这里只是用来做多语言之间的通信协议。如果不使用这个通信协议，那就要直接调用C++的函数。对于比较复杂的消息类型，直接调用C++函数还挺麻烦的。

2017-03-21 06:55 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +	* 需要先完善config_parser的单测，增加单测覆盖率
真正实现的时候，肯定还是得一个Attribute一个Attribute的改(估计不是一个Layer一个Layer的改)。。所以会是一个渐近的过程，不会有突变。

2017-03-21 07:06 UTC, jacquesqiao commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* `oneof`与`map`是`protobuf2`语法，但是这是在`Protobuf 3.0`之后的代码库中添加的功能，如果Paddle依赖这个功能，那么Paddle必须依赖Protobuf 3.0以上的Protobuf版本。
嗯，好的，我刚才也是搜了下没找到，不过明确了就行了

2017-03-21 07:25 UTC, jacquesqiao commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* 对于每一种类型的Layer，Paddle根据Layer的名字约定两个全局函数的名字。例如，对于FC Layer，全局函数的名字是 `__get_fc_layer_definition__` 和 `__get_fc_layer_output_definition__`。 这两个全局函数通过`REGISTER_LAYER`自动生成。
这两个全局函数通过`REGISTER_LAYER`自动生成，没太明白

2017-03-21 07:30 UTC, jacquesqiao commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static void getLayerDefinition(LayerDef& def) {
看起来流程是，cpp端也是构造了一个proto，来描述这个layer的性质(input/output)，然后python get这个proto，再对应的构造出python class，如果都是proto作为属性，是不是都不需要python专门生成一段对应的代码了，而是类似v2的converter那样，把proto信息convert成函数定义，用户如果想查看某个layer的定义，也是直接解析这两个proto就行了。

2017-03-21 07:37 UTC, jacquesqiao commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static void getLayerDefinition(LayerDef& def) {
不过在layer拼接的时候，应该有一些特殊的逻辑，这些信息需要表现在layer定义里边么

2017-03-21 07:37 UTC, qingqing01 commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +    // so parameter_attr.size() == inputs.size()
parameter_attr.size() <= inputs.size()

2017-03-21 07:37 UTC, qingqing01 commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +	// Output name, Each Paddle Layer could have multiple outputs.
Paddle目前一个layer只有一个output。

我理解layer的input, output是相同的类型，ArgumentDef。 这里似乎只看到:

```
message LayerDef {
    ...
    repeated ArgumentDef inputs = 3;
    ...
}
...
message  LayerOutputDef {}
```
没有看到layer的output是啥类型？还是 ArgumentDef嘛？

2017-03-21 07:37 UTC, qingqing01 commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +message ArgumentDef {
ArgumentDef 是否和 function/BufferArg(用来描述function的input/output)有一定的对应关系？

2017-03-21 07:37 UTC, qingqing01 commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +message LayerConfig {
这里说是 "简单的示例代码"， LayerConfig其实并不全吧？ 最终会降 https://github.com/PaddlePaddle/Paddle/blob/develop/proto/ModelConfig.proto#L284  里所有的属性都以代码生成吗？

2017-03-21 09:16 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +    // so parameter_attr.size() == inputs.size()
```
parameter_attr.size() == inputs.size()
```
如果是这个输入不应该有参数，那就传一个空的ParameterDef。 `inputs`和`parameter_attr`两个数组是使用数组下标一一对应的。

2017-03-21 09:17 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +	// Output name, Each Paddle Layer could have multiple outputs.
Layer的输出并不在Layer的元信息中指定。

因为每一个Layer的输出形状是解析配置时计算的，而不是元信息可以规定的。所以在LayerDef里面没有outputs

2017-03-21 09:22 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* 对于每一种类型的Layer，Paddle根据Layer的名字约定两个全局函数的名字。例如，对于FC Layer，全局函数的名字是 `__get_fc_layer_definition__` 和 `__get_fc_layer_output_definition__`。 这两个全局函数通过`REGISTER_LAYER`自动生成。
```cpp
#define REGISTER_LAYER(name, cls)\
    extern "C" void __get_#name#_layer_definition__(LayerDef& def) {\
        cls::getLayerDefinition(def);\
    }\
    \
    std::vector<LayerOutputType> __get_#name#_layer_output__(const std::vector<LayerOutputType>& inputs,\
      LayerConfig& self) {\
        return cls::getLayerOutputType(inputs, self);\
    }\
    \
    static InitFunction initFunction([]{\
      Layer::registerLayer(#name, cls);
    })
```

2017-03-21 09:23 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static void getLayerDefinition(LayerDef& def) {
> 看起来流程是，cpp端也是构造了一个proto，来描述这个layer的性质(input/output)，然后python get这个proto，再对应的构造出python class，如果都是proto作为属性，是不是都不需要python专门生成一段对应的代码了，而是类似v2的converter那样，把proto信息convert成函数定义，用户如果想查看某个layer的定义，也是直接解析这两个proto就行了。

对于Python这种动态类型语言，直接生成函数比代码生成器更简单。

2017-03-21 09:25 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static void getLayerDefinition(LayerDef& def) {
> 不过在layer拼接的时候，应该有一些特殊的逻辑，这些信息需要表现在layer定义里边么

没有想好具体有哪些『特殊的逻辑』。如果有这个结构覆盖不到的问题，譬如`recurrent_group`，可能定义到代码生成器里面也好？因为这个本身是一种语言一个最佳实践的。

2017-03-21 09:28 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +message LayerConfig {
有道理。。LayerInputConfig，OperatorConfig我没考虑周全，那个是一个repeated所以不能这么搞。

2017-03-21 09:37 UTC, QiJune commented on doc/design/layer_generation/00.how_to_write_a_layer.md
>  1. 讲这个调用图传递给Paddle Core，生成真正的`ModelConfig`。
讲=>将
从调用图GraphProtobuf转换成真正的ModelConfig的具体过程是什么样的，是在哪一步转的啊

2017-03-21 09:37 UTC, QiJune commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +	* 进而顺序执行 `getLayerOutputType`获得这个Layer的输出，并完成神经网络参数推导过程。再将这个LayerConfig传递给下一个Layer。
推导的过程是在初始化GradientMachine时做的吗

2017-03-22 04:25 UTC, lzhao4ever commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  "parameter_attr": [
可以继承base layer 元信息吗？这样可以简化parameter_attr等说明。

2017-03-22 04:30 UTC, lzhao4ever commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  void backward() { ... }
可以定义loss layer, 它的gradient 是在python中计算后传入吗？

2017-03-22 06:51 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  "parameter_attr": [
这段protobuf是在Paddle C++部分生成的。所以，虽然这里有重复的信息，但是在C++部分可以使用同一个函数来生成Protobuf数据。

2017-03-22 06:52 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  void backward() { ... }
有道理。

2017-03-22 09:56 UTC, QiJune commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +	* 这个过程同时也可以是在线的过程。比如对于Python这种动态类型语言，运行时生成函数比较简单，就没必要先生成代码，再生成函数了。
这里生成config_parser是先于读取用户定义的网络结构的，那就是需要对所有的layer元信息都遍历一遍。
是否可以考虑先读取用户配置的网络结构，得知需要哪些layer的元信息，然后再生成config_parser。

2017-03-22 14:52 UTC, lzhao4ever commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  "parameter_attr": [
知道了。

2017-03-22 16:56 UTC, emailweixu commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerOutputType 表示的是，某一个Layer输入输出具体是什么类型的(不是输入输出具体是什么值)。这是在运行时中计算出来的。
need to consider the possibility of multiple outputs.

2017-03-22 16:56 UTC, emailweixu commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static std::vector<LayerOutputType> getLayerOutputType(const std::vector<LayerOutputDef>& inputs,
need to check whether inputs are consistent (e.g., whether dimensions and types match)

2017-03-22 16:56 UTC, emailweixu commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +* 解决办法: 用`map`和`oneof`，将属性变成一个多种类型的字典
我们需要支持动态图，那还需要确保构造模型的overhead不大。python的protobuf很慢，所以也可以考虑直接通过C++API来构造图是否可行。

2017-03-22 16:57 UTC, emailweixu commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerOutputType 表示的是，某一个Layer输入输出具体是什么类型的(不是输入输出具体是什么值)。这是在运行时中计算出来的。
目前的LstmStepLayer实际上是2个output。第二个output是通过另一个GetOutputLayer来获得的。

2017-03-23 02:41 UTC, qingqing01 commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerOutputType 表示的是，某一个Layer输入输出具体是什么类型的(不是输入输出具体是什么值)。这是在运行时中计算出来的。
同意需要支持多个output，在网络配置时能够支持取其中的某些层连接到不同的层~

2017-03-23 02:46 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerOutputType 表示的是，某一个Layer输入输出具体是什么类型的(不是输入输出具体是什么值)。这是在运行时中计算出来的。
是的，所以`getLayerOutputType`返回的是`std::vector<LayerOutputType>`

2017-03-23 03:15 UTC, reyoung commented
@emailweixu 

> 我们需要支持动态图，那还需要确保构造模型的overhead不大。python的protobuf很慢，所以也可以考虑直接通过C++API来构造图是否可行。

如果直接全部通过C++ API来构造图，那么之前`paddle_trainer`解析配置的部分就没办法兼容了。之前`paddle_trainer`是 C++内嵌了一个Python解释器，这个Python的解释器应该不太有办法再调用回C++的API。所以，纯粹的用C++ API构造图不太可行。

不过，目前来看，这个设计里把原来`config_parser.py`的工作拆成了两部分，一部分是接受用户的参数，一部分是网络参数的推导(参数大小，检查是否输入合法等等。这块在`getLayerOutputType`里面执行)。Python这边的工作只是接受用户的参数，然后序列化成字符串给C++，相对来说轻了一些。

另一方面，支持动态图的话，就是纯粹用Python驱动Paddle Core来做了。这个功能没有什么历史负担。到时候，我们可以直接用 @hedaoyuan 写的Function为基础，然后用全局变量(tape)来记录每一次调用的结果即可？到时候完全不需要 Protobuf来构造图了吧？直接在Python端维护一个图结构就好了。

2017-03-24 01:01 UTC, QingSunVT commented
可以加入Param 和 layer output之间转换的功能吗？例如，将Param转换成layer output, 然后进行操作或者输出到API的python代码中。

2017-03-24 01:02 UTC, QingSunVT commented
用layer output来初始化Params? 将Params的初始化变得灵活一些，例如，直接初始化Params为单位矩阵。

2017-03-24 09:49 UTC, luotao1 commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +  static void getLayerDefinition(LayerDef& def) {
对`recurrent_group`来说，使用代码生成器是否会太晦涩，现在v2版本转的那块，已经挺难懂的了。

2017-03-27 05:56 UTC, reyoung commented
> 用layer output来初始化Params? 将Params的初始化变得灵活一些，例如，直接初始化Params为单位矩阵。


这个PR不涉及这个内容。这里主要说明如何简化/清理Paddle定义网络结构时的实现工作。

至于初始化Params的工作，在v2 API里面，用户可以直接将一个numpy矩阵赋值给Paddle的parameter.

2017-03-27 05:59 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +	* 这个过程同时也可以是在线的过程。比如对于Python这种动态类型语言，运行时生成函数比较简单，就没必要先生成代码，再生成函数了。
确实也是可以的。这个工作也可以是Lazy的。即用户使用某一个函数的时候，Python找不到这个函数，然后代码生成器再生成这个函数。

不过为了生成Sphinx文档方便，在解析配置之前生成config_parser可能更有道理。这样，Sphinx才能查找到所有支持的Layer，进而生成文档。

2017-03-28 02:41 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +现阶段如何编写一个Layer呢？可以参考[文章](http://www.paddlepaddle.org/doc/dev/new_layer/index.html)。主体可以分为一下几个步骤:
Done.

2017-03-28 02:43 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +message ArgumentDef {
已线下和道远聊过。

结论

```cpp
enum DataType {
   Dense = 1;
   Sparse = 2;
   SparseBinary = 3;
   Index = 4;
};

enum SequenceNestedLevel {
    NO_SEQUENCE=0;
    PLAIN_SEQUENCE = 1;
    NESTED_SEQUENCE = 2;
};

InputType = DataType << 16 | SequenceNestedLevel

```

2017-03-28 02:44 UTC, reyoung commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +message LayerConfig {
已经添加实例

2017-03-28 03:27 UTC, wangkuiyi requested changes

2017-03-28 03:27 UTC, wangkuiyi commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +## 基本目标
建议修改成三部分：

1. 现状
2. 问题何在
3. 应该怎么修改

由此一步一步地论证修改的“道理”。

2017-03-28 03:27 UTC, wangkuiyi commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +用户只需要写Layer的计算信息，而不需要写配置解析器，也不修改写Protobuf的内容。就可以完成Layer的书写。
Protobuf ==> protobuf

2017-03-28 03:27 UTC, wangkuiyi commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* 在注册Layer的时候，不只注册Layer的C++类型，同时注册Layer的元信息，元信息使用Protobuf来表示。
Layer ==> layer

2017-03-28 03:27 UTC, wangkuiyi commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerDef 是描述了每**种**Layer的元信息，他包含每种Layer的类型名，注释，可以接受的输入类型，参数类型，Layer的其他属性。不包括这个Layer输出什么类型
Github compatible Markdown 里的bullet用 `-` 而不是 `*`

2017-03-28 03:28 UTC, wangkuiyi commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* 在注册Layer的时候，不只注册Layer的C++类型，同时注册Layer的元信息，元信息使用Protobuf来表示。
为什么metadata要用protobuf来描述？

2017-03-28 03:32 UTC, typhoonzero commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +"""json
""" -> ```

2017-03-28 03:32 UTC, typhoonzero commented on doc/design/layer_generation/01.use_map_in_protobuf.md
> +"""
格式问题，同上：""" -> ```

2017-03-31 10:42 UTC, reyoung commented on doc/design/layer_generation/00.how_to_write_a_layer.md
> +* LayerDef 是描述了每**种**Layer的元信息，他包含每种Layer的类型名，注释，可以接受的输入类型，参数类型，Layer的其他属性。不包括这个Layer输出什么类型
https://guides.github.com/features/mastering-markdown/
都可以。

2017-04-10 03:30 UTC, luotao1 commented on doc/design/layer_generation/00.ways_to_define_layer.md
> +	* 最后完成这个Layer配置文件解析`config_parser.py`，`trainer_config_helpers`和`paddle.v2`
新写一个layer要加上下面两点么：
1. 写gpu的时候，要设置一个extern和inline的函数
2. 好几种单测，test_layerGrad, python接口的单测，cpu和gpu核心函数的单测(test_matrixCompare)等

2017-05-10 14:23 UTC, wangkuiyi reviewed
这篇文档还是没有说明白问题是什么，以及应该如何解决问题呀？

2017-05-10 14:23 UTC, wangkuiyi commented on doc/design/topology.md
> +# Topology Overview
> Topology Overview

==>

> Design Doc: Add New Layers

to make the title of this document consistent with the title of this PR.

2017-05-10 14:23 UTC, wangkuiyi commented on doc/design/topology.md
> +Topology is a concept in Paddle for representing neural networks.  A neural network contains one topology, which describes how layers connected to each other, and many parameters. The other deep lear
I think this paragraph can be shortened as:

> In PaddlePaddle, we represent a neural network by its *topology* and *parameters*. The topology is a directed graph of *layers*.

2017-05-10 14:23 UTC, wangkuiyi commented on doc/design/topology.md
> +The topology is not only an API level concept but also how we organize the computation codes for each `Layer` or `Function` in Paddle. The Paddle should maintain a dictionary from `Layer Type` to Lay
这段话问题挺多，看不明白想说什么。

1. “Topology不仅是。。。。”，然后应该接“而且是。。。”。但是没有接上。
1. Layer Type是什么？
1. 后面的例子里，mul显然不是一个layer，不仅没有解释前面的话，而且引入新的疑问。
1. 接下来“manipulate topology”又是指什么？

2017-05-10 14:37 UTC, wangkuiyi requested changes
通篇读下来，不知道想解决什么问题。我努力猜了猜，好像是说每个layer或者function要增加一些配置参数的说明，比如某个参数的值域，以便unit test？

这事儿为什么紧急，需要现在做？

而且这事儿（增加一个机制，可以动态检查一个data member的值域）和layer以及function并不直接依赖，看上去可以写成一个独立的package。

2017-05-10 14:37 UTC, wangkuiyi commented on doc/design/topology.md
> +BEGIN_REGISTER_FUNCTION(cos, cos_kernel)
为什么function不能用C++语法定义，而是要引如 BEGIN/END_REGISTER_FUNCTION 这么难读懂的方式？读者还得去grep BEGIN/END_REGISTER_FUNCTION 的定义，才能明白。

2017-05-10 14:37 UTC, wangkuiyi commented on doc/design/topology.md
> +Alan is a professional developer in CPU and GPU. He can write kernel functions of a new `Layer` with the best performance. However, he is not a familiar with Paddle API language, Python. Alan just ne
这个例子和“让增加layers变得更方便”有什么关系呢？

2017-05-10 14:37 UTC, wangkuiyi commented on doc/design/topology.md
> +func.addAttribute("scale", "The scale of cos layer").defaultValue(1.0).largerThan(0.0);
`func`是什么？上面没有定义。

2017-05-10 14:37 UTC, wangkuiyi commented on doc/design/topology.md
> +auto cos = function::Register("cos");
这里为什么要用registerer？直接调用cos函数不就行了吗？

2017-05-10 14:58 UTC, reyoung commented on doc/design/topology.md
> +Alan is a professional developer in CPU and GPU. He can write kernel functions of a new `Layer` with the best performance. However, he is not a familiar with Paddle API language, Python. Alan just ne
新写Layer的开发者不需要写Python Code了。只需要写『如何计算』即可。

2017-05-10 15:01 UTC, reyoung commented on doc/design/topology.md
> +BEGIN_REGISTER_FUNCTION(cos, cos_kernel)
这不是定义『Function』的过程，而是『注册』Function或者Layer的过程。这里确实有点难懂。我也在想更好的表达方式。。不过看起来其他框架都用了类似的手法注册函数或者Layer。

[mxnet](https://github.com/dmlc/mxnet/blob/master/src/operator/concat.cc#L81)
[tensorflow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ctc_ops.cc#L84)

2017-05-10 15:02 UTC, reyoung commented on doc/design/topology.md
> +func.addAttribute("scale", "The scale of cos layer").defaultValue(1.0).largerThan(0.0);
这个是宏定义里面生成的变量。不过看起来并不直观，我再想想怎么表示更好。

2017-05-10 15:03 UTC, reyoung commented on doc/design/topology.md
> +auto cos = function::Register("cos");
不太行呀。。这就和层的register一样。用Register来管理Paddle所有支持的层和函数，这样其他语言就可以用这个函数了。

2017-05-10 15:08 UTC, reyoung commented on doc/design/topology.md
> +The topology is not only an API level concept but also how we organize the computation codes for each `Layer` or `Function` in Paddle. The Paddle should maintain a dictionary from `Layer Type` to Lay
* topology不仅仅是一个End Users看到的API接口，更重要的是，拓扑结构的设计也关乎到了Paddle的计算代码(Layer)如何组织
* Layer Type是一个字符串来表示Layer的类型，譬如一个fc_layer，他的type就是"fc"。
* Paddle总要维护一个 `map<string, LayerCreator>`的一个映射，用来根据用户配置创建Layer对象。
* `manipulate topology`， 创建、修改一个拓扑结构。我改成create and modify

2017-05-10 15:11 UTC, reyoung commented
@wangkuiyi 
> 这事儿为什么紧急，需要现在做？

这个事情非常紧急。Paddle目前使用上的大部分问题都需要完成这个重构来解决。可以解决的问题包括:

* Paddle网络配置调用关系复杂，一层调用一层导致无法阅读，调试。
* Paddle新增一个Layer非常困难，导致GPU开发人员还要写Python Code
* Paddle API文档不完备。缺少一个机制在C++端完成文档。
* Paddle错误提示不友好，缺乏合理的错误提示。

2017-05-10 18:56 UTC, emailweixu commented on doc/design/topology.md
> +func.addAttribute("scale", "The scale of cos layer").defaultValue(1.0).largerThan(0.0);
感觉可以不需要func。让addAttribue(), addInput()是一个类的成员函数就可以了。BEGIN_REGISTER_FUNCTION（）定义了一个类来做registration. registration就在这个类的构造函数完成。在END_REGISTRER_FUNCTION()那里声明一个这个类的instance。

2017-05-10 18:56 UTC, emailweixu commented on doc/design/topology.md
> +
另外还需要有函数检查input, output的shape是否match。

2017-05-10 18:56 UTC, emailweixu commented on doc/design/topology.md
> +BEGIN_REGISTER_FUNCTION(cos, cos_kernel)
Another possible way of achieving this is to make all of these part of Function (i,e. virtual member of Function class).  Beside computation, a Function needs to also implement the interfaces for specifying inputs&outputs, shape inferer, shape checker, estimating flops  etc. 

Need to think which is a better way.

2017-05-10 18:56 UTC, emailweixu commented on doc/design/topology.md
> +The topology is not only an API level concept but also how we organize the computation codes for each `Layer` or `Function` in Paddle. The Paddle should maintain a dictionary from `Layer Type` to Lay
I think we should make Function, Layer, Projection the same thing in the new design.

2017-05-16 06:43 UTC, reyoung commented on doc/design/topology.md
> +The topology is not only an API level concept but also how we organize the computation codes for each `Layer` or `Function` in Paddle. The Paddle should maintain a dictionary from `Layer Type` to Lay
Make Layer and Projection are the same thing is simple, but Function didn't contain `backward` method.

2017-05-16 07:05 UTC, reyoung commented on doc/design/topology.md
> +BEGIN_REGISTER_FUNCTION(cos, cos_kernel)
我觉得直接注册函数到元信息要比使用virtual member要好。原因有如下几个方面:

1. 如果我们使用virtual member，我们必须强制开发者使用『继承』来实现自己的代码。
    1. 我们如果想要将Caffe或者Torch的某些Op 拿到Paddle中，就要重新写一个类。
    1. 如果用注册函数的方式，我们就可以直接把其他框架的函数注册进Paddle就好。举例:
        ```CPP
        #include "torch/some_ops.h"

        REGISTER_TORCH_OPS("torch_something",  some_ops);
        ```
1. 如果使用virtual member，BaseFunction里面会有很多接口。
     1. 这些接口子类不一定会全部实现。譬如，estimating flops的函数如果不实现只是做不了benchmark，不影响计算本身。但使用注册，可以对某些OP不注册这个"estimating flops"的函数就好。
     1. 这些接口很难一次想清楚。BaseFunction很有可能在开发过程中，再增加新的接口。改一个基类会影响很多子类。

使用注册函数的方式，好处就是kernel developer确实只用实现一个计算kernel，然后用一种手法注册到Paddle中就好。简化kernel developer的思想负担。

2017-05-16 07:13 UTC, reyoung commented on doc/design/topology.md
> +
这个会交由Paddle本身来完成。用户只需要注册这个函数需要哪些shape的input，能够生成哪些shape的output，合法性检查是Paddle本身完成的。

2017-05-16 08:27 UTC, hedaoyuan commented on doc/design/topology.md
> +
同意上述观点，另外，可能还需要考虑一下输入参数和输出参数不定的情况，比如https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/function/ContextProjectionOp.cpp#L111
这里，ContextProjection的计算，input是一个参数或者两个参数都可以。

2019-02-01 04:39 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:39 UTC, closed without merging