lstm and gru runtime switch SIMD
PaddlePaddle/Paddle pull request #1714
Opened 2017-03-28 11:28 UTC by gangliao

2017-03-28 16:12 UTC, wangkuiyi approved these changes
学习了！赞！

没有测试过，只是努力学了CMakeLists文件的写法，以及学习了逐步分而治之的解法。

赞细致的C++ style。

2017-03-28 16:12 UTC, wangkuiyi commented on paddle/cuda/include/hl_base.h
> +#define SIGMOID_THRESHOLD_MIN -40.0
constant value是不是用 

```cpp
const double kSigmoidRangeMin = -40.0;
const double kSigmoidRangeMax = 13.0;
```

这样比较好？编译的时候有类型检查。

2017-03-29 02:33 UTC, hedaoyuan requested changes
修改的地方比较多，大概解释一下code refine的思路。最好是解释一下原来的code逻辑，比如包含在那些文件中，怎么编译；refine后包含在哪些文件中，怎么编译。
另外，refine之后的命名还需要在看一下，simd_gru_op.cc，simd_lstm_op.cc里面也包含了非AVX的代码，simd命名不是很合适。

2017-03-29 02:33 UTC, hedaoyuan commented on paddle/cuda/src/simd_math.cc
> +#include "simd_math.h"
这个文件不能修改名字，最好也不要修改内容。另外，没有看到simd_math.h文件。

2017-03-29 12:11 UTC, Xreki commented on paddle/cuda/CMakeLists.txt
> +target_link_libraries(paddle_cuda naive_rnn avx_rnn)
这条命令的目的应该是把`naive_rnn`和`avx_rnn`这两个库合并到`paddle_cuda`库把，`target_link_libraries`好像没有这个功能。

2017-03-30 04:22 UTC, Xreki commented on paddle/cuda/CMakeLists.txt
> +    src/hl_warpctc_wrap.cc
在`WITH_GPU`的时候，`src/hl_warpctc_wrap.cc`的编译也需要定义宏`__NVCC__`，因为需要给warp-ctc设置stream

2019-02-01 04:40 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:40 UTC, closed without merging