Polish fuse_all_reduce_op_pass
PaddlePaddle/Paddle pull request #17652
Opened 2019-05-26 09:16 UTC by chengduoZH

2019-05-28 07:18 UTC, gongweibao commented on paddle/fluid/operators/ngraph/ops/activation_op.h
> -REGISTER_NG_OP(sqrt, BuildUnaryNode<ngraph::op::Sqrt>);
Why delete this?

2019-05-28 07:18 UTC, gongweibao commented on paddle/fluid/framework/details/multi_devices_helper.h
> +    GroupParamsAndGrads;
👍

2019-05-28 07:18 UTC, gongweibao commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +    if (num_params_grads == 0) {
LOG(WARNING) here？

2019-05-28 07:18 UTC, gongweibao commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +
It's not persistable if use memory optimization？

2019-05-28 07:19 UTC, gongweibao requested changes
We need a unit test to guarantee correctness.

2019-06-04 16:09 UTC, chengduoZH commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +    if (num_params_grads == 0) {
I think it doesn't matter.

2019-06-04 16:09 UTC, chengduoZH commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +
`params_grads[i].first` is the parameter's name, and it is persistable.

2019-06-04 16:10 UTC, chengduoZH commented
>  We need a unit test to guarantee correctness.

@gongweibao Done

2019-06-10 08:26 UTC, gongweibao commented on paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
> +      if (node->IsOp()) {
```
If(!node->IsOp()){
    continue;
}
```

2019-06-10 08:27 UTC, gongweibao commented on paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
> +        if (all_reduce_op_handle) {
```
if(nullptr == all_reduce_op_handle) continue;
```

2019-06-26 12:37 UTC, chengduoZH commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +// framework::proto::VarType::Type::VarType_Type_BOOL;
Please remove line65~66

2019-06-27 07:55 UTC, gongweibao commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +    SetGroupAccordingToGroupSize(var_nodes, group_params_grads);
This function is not needed now.

2019-06-27 07:59 UTC, gongweibao commented on paddle/fluid/framework/ir/alloc_continuous_space_for_grad_pass.cc
> +        if (local_group_memory_size >= group_memory_size ||
Use left lines 281~290

2019-07-03 11:27 UTC, gongweibao approved these changes
LGTM

2019-07-04 02:10 UTC, merged