fix prepare context redundant code problem, optimize executor by cach…
PaddlePaddle/Paddle pull request #17743
Opened 2019-05-30 03:35 UTC by guru4elephant

…ing create_varaiables

test=develop

optimize executor by caching create_variable results. User only need to open use_program_cache to use this optimization. 

Take Bert model as example:

Before optimization:
![image](https://user-images.githubusercontent.com/35550832/58606595-bc90f080-82ce-11e9-8e52-a4b891209b49.png)

After optimization：
![image](https://user-images.githubusercontent.com/35550832/58606602-c4509500-82ce-11e9-9d8a-6bdb6a387632.png)

This optimization is generalized that all models training can be applied.

2019-05-30 03:39 UTC, gavin1332 commented on python/paddle/fluid/executor.py
> +            #exe.run_cached_prepared_ctx(ctx, scope, True, True, False)
remove this line

2019-05-30 03:43 UTC, gavin1332 requested changes
a commented line need to be removed

2019-05-30 03:57 UTC, guru4elephant commented on python/paddle/fluid/executor.py
> +            #exe.run_cached_prepared_ctx(ctx, scope, True, True, False)
fixed, thx

2019-05-30 05:13 UTC, gavin1332 submitted a review, later dismissed

2019-05-30 08:22 UTC, gavin1332 submitted a review, later dismissed

2019-05-30 12:58 UTC, gavin1332 commented on python/paddle/fluid/executor.py
> +        return self.var_caches.get(program_cache_key, None)
missing definition of self.var_caches

2019-05-30 12:58 UTC, gavin1332 commented on python/paddle/fluid/executor.py
> +        return self.scope_caches.get(program_cache_key, None)
missing definition of self.scope_caches

2019-05-30 13:29 UTC, gavin1332 commented on python/paddle/fluid/executor.py
> +            exe.run_cached_prepared_ctx(ctx, scope, False, False, False)
as executor.run() method allows user inputting None scope, it should be set scope to default when it is None

2019-05-30 23:36 UTC, guru4elephant commented on python/paddle/fluid/executor.py
> +        return self.var_caches.get(program_cache_key, None)
fixed. thx

2019-05-30 23:37 UTC, guru4elephant commented on python/paddle/fluid/executor.py
> +        return self.scope_caches.get(program_cache_key, None)
fixed.

2019-05-31 01:37 UTC, jacquesqiao commented on paddle/fluid/pybind/pybind.cc
> +      .def("create_variables", &Executor::CreateVariables,
CreateVariables has no return value.

2019-05-31 03:09 UTC, gavin1332 approved these changes

2019-05-31 03:09 UTC, merged

2019-05-31 03:11 UTC, guru4elephant commented on paddle/fluid/pybind/pybind.cc
> +      .def("create_variables", &Executor::CreateVariables,
will remove this later, thx