Add multi process reader
PaddlePaddle/Paddle pull request #18115
Opened 2019-06-15 03:31 UTC by chengduoZH

Add multi process reader.

2019-06-15 12:01 UTC, raindrops2sea requested changes
涉及API变动，请先给出设计文档走评审。

2019-06-16 02:44 UTC, xsrobin submitted a review, later dismissed
LGTM

2019-06-19 09:12 UTC, raindrops2sea approved these changes

2019-06-19 11:37 UTC, Xreki approved these changes

2019-06-19 11:40 UTC, luotao1 approved these changes

2019-06-19 11:58 UTC, xsrobin approved these changes

2019-06-19 12:58 UTC, merged