Add match_matrix_tensor op
PaddlePaddle/Paddle pull request #18525
Opened 2019-07-05 09:24 UTC by Aurelius84

- **match_matrix_tensor**:

Example:
```python
import numpy as np
from paddle.fluid import layers
x_lod_tensor = layers.data(name='x', shape=[10], lod_level=1)
y_lod_tensor = layers.data(name='y', shape=[10], lod_level=1)
out, out_tmp = layers.match_matrix_tensor(x=x_lod_tensor, y=y_lod_tensor, channel_num=3)
```
<img width="1131" alt="match_matrix_tensor" src="https://user-images.githubusercontent.com/9301846/60712468-b1725580-9f49-11e9-8083-59b1852bae56.png">

2019-07-15 11:37 UTC, lanxianghit requested changes

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +                 "Out(Output) of Fully Connected should not be null.");
the error infomation is wrong...

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +  //   PADDLE_ENFORCE(ctx->HasInput(framework::GradVarName("Tmp")),
remove

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +void lego_cpu_gemm_with_lda(const math::BlasT<DeviceContext, T>& blas,
change the name

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +    // int M = x->dims()[0], N = dim_t * dim_in, K = dim_in;
remove

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.h
> +  //  framework::OpKernelType GetExpectedKernelType(
remove

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.h
> +  //  framework::OpKernelType GetExpectedKernelType(
remove

2019-07-15 11:37 UTC, lanxianghit commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +void lego_cpu_gemm(const math::BlasT<DeviceContext, T>& blas,
change the name, maybe you should use the func in 'search_compute.h'

2019-07-16 03:03 UTC, Aurelius84 commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +void lego_cpu_gemm_with_lda(const math::BlasT<DeviceContext, T>& blas,
Fixed. I moved the function into search_compute.h header file.

2019-07-29 10:10 UTC, lanxianghit submitted a review, later dismissed

2019-07-31 02:44 UTC, lanxianghit submitted a review, later dismissed

2019-08-05 08:49 UTC, lanxianghit submitted a review, later dismissed

2019-08-06 02:52 UTC, luotao1 submitted a review, later dismissed
LGTM for `op_use_default_grad_op_maker.spec`

2019-08-15 02:46 UTC, luotao1 submitted a review, later dismissed

2019-08-15 03:09 UTC, luotao1 commented on paddle/fluid/operators/search_compute.h
> +#if defined(TYPE_USE_FLOAT)
`TYPE_USE_FLOAT`, `USE_SSE`, 等宏都没有用到。可以确认下这里到底走了哪个分支，删去不用的宏和分支。

2019-08-15 03:10 UTC, luotao1 commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +                 "X(Input) of MatchMatrix should not be null.");
PADDLE_ENFORCE接口需要修改下。

2019-08-15 06:33 UTC, Aurelius84 commented on paddle/fluid/operators/search_compute.h
> +#if defined(TYPE_USE_FLOAT)
删除了不必要的TYPE_USE_DOUBLE分支，去掉了没有用到的函数

2019-08-15 07:14 UTC, Aurelius84 commented on paddle/fluid/operators/match_matrix_tensor_op.cc
> +                 "X(Input) of MatchMatrix should not be null.");
已按照规范修改

2019-08-19 02:52 UTC, lanxianghit approved these changes
LGTM

2019-08-19 03:28 UTC, luotao1 approved these changes

2019-08-19 07:42 UTC, guoshengCS approved these changes

2019-08-19 09:00 UTC, merged