Enhance multiclass nms
PaddlePaddle/Paddle pull request #18607
Opened 2019-07-12 03:15 UTC by jerrywgz

Add one more Output(Index) for multiclass nms.
Index is the absolute index of selected bbox cross batches.
If the index is used to gather other attribute such as age, one needs to reshape the input(N, M, 1) to (N * M, 1) as first.

2019-07-12 03:35 UTC, jerrywgz commented
API doc preview:
detection_output
![image](https://user-images.githubusercontent.com/22989727/61100486-f7bf3b80-a498-11e9-866c-a25956816b08.png)
![image](https://user-images.githubusercontent.com/22989727/61100497-0279d080-a499-11e9-973a-ccb01fd2b0d9.png)

multiclass_nms
![image](https://user-images.githubusercontent.com/22989727/61100511-11608300-a499-11e9-91a5-1752d03e916f.png)
![image](https://user-images.githubusercontent.com/22989727/61100521-18879100-a499-11e9-8cb0-af4e14dafe51.png)

2019-07-15 02:32 UTC, qingqing01 commented on python/paddle/fluid/layers/detection.py
> +        input(N, M, 1) to (N * M, 1) as first.
1. If the index is used to gather ...  最后这个注释不是个通用的注释，觉得可以不写。
2. 告诉用户 类型是 int

2019-07-15 02:32 UTC, qingqing01 commented on python/paddle/fluid/layers/detection.py
> +        input(N, M, 1) to (N * M, 1) as first.
同上

2019-07-15 05:37 UTC, jerrywgz commented on python/paddle/fluid/layers/detection.py
> +        input(N, M, 1) to (N * M, 1) as first.
Done

2019-07-15 05:37 UTC, jerrywgz commented on python/paddle/fluid/layers/detection.py
> +        input(N, M, 1) to (N * M, 1) as first.
Done

2019-07-18 12:13 UTC, Superjomn requested changes
Do not change the definition of the existing operators, or the different version of training and inference model will be incompatible.

You can add another op called  multi_nms2, and that will add version information to this Op, the latter trained model will use nms2_op, not nms_op; while the old training will save model base on nms_op. 
Both the nms_op and nms2_op are compatible with the new inference, and for the old inference, the nms2 in the newly trained model will remind the users that a new version of inference lib is needed.

2019-07-18 12:13 UTC, Superjomn commented on paddle/fluid/API.spec
> +paddle.fluid.layers.detection_output (ArgSpec(args=['loc', 'scores', 'prior_box', 'prior_box_var', 'background_label', 'nms_threshold', 'nms_top_k', 'keep_top_k', 'score_threshold', 'nms_eta', 'retur
Do not change the definition of the existing operators, or the different version of training and inference model will be incompatible.

You can add another op called  multi_nms2, and that will add version information to this Op, the latter trained model will use nms2_op, not nms_op; while the old training will save model base on nms_op. 
Both the nms_op and nms2_op are compatible with the new inference, and for the old inference, the nms2 in the newly trained model will remind the users that a new version of inference lib is needed.

2019-07-18 12:42 UTC, Superjomn approved these changes

2019-07-19 01:48 UTC, xsrobin approved these changes

2019-10-29 11:46 UTC, jerrywgz commented
改动已在https://github.com/PaddlePaddle/Paddle/pull/19228中合入

2019-10-29 11:46 UTC, closed without merging