Add requantize squash
PaddlePaddle/Paddle pull request #18676
Opened 2019-07-17 13:26 UTC by wozna

FP32: avg top1 accuracy: 0.7050

changed accuracy from 
 INT8: avg top1 accuracy: 0.7017 
to 
 INT8: avg top1 accuracy: 0.7022

2019-07-17 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=18676) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=18676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=18676) it.</sub>

2019-07-17 14:27 UTC, sfraczek reviewed
LGTM. I just have one request

2019-07-17 14:27 UTC, sfraczek commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
>                    found_squash_count);
Please change the name of found_squash_count to something like found_quantize_dequantize_squash_count/found_quant_dequant_squash_count

2019-07-22 12:36 UTC, wojtuss requested changes

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
>  TEST(CpuQuantizeSquashPass, branch_to_equal_inequal_and_fp32) {
`_unequal_`

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
>    use_mkldnn = !use_mkldnn;
Testing with `use_mkldnn=false` should be dropped as quantization can be enabled only when `use_mkldnn=true`.
Here and below.

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
>  TEST(CpuQuantizeSquashPass, inequal_scales) {
`unequal_scales`

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
Please, verify that a proper output scale is set in `conv1` after the squash.

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
> +
Please, verify that a proper output scale is set in `conv1` after the squash.

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
> +     inequal_scales_squash_dequantize_quantize_into_requantize) {
`unequal_...`

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass_tester.cc
> +  CountNodeTest(BuildProgramDesc2(use_mkldnn, scale, scale, scale2),
If you pass scales in a different order (`scale`, `scale2`, `scale`) the test would fail probably (see a comment to `ConvRequantSquash` above).

2019-07-22 12:36 UTC, wojtuss commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +    float requant_scale_out =
This squash will fail in the following situation with `scale1 != scale2`:
```
a->conv2d->b->requantize(scale1)->c
b->requantize(scale2)->f
```
In such a case we cannot fuse `conv2d` with `requantize`.
Please make a distinction between such cases and add test cases for them.

2019-07-22 19:45 UTC, closed without merging