add eye op, kernel and unitest test=develop
PaddlePaddle/Paddle pull request #18917
Opened 2019-07-31 02:21 UTC by ForFishes

Add eye op implementation and the unit test codes of it. This op constructs an identity matrix or a batch of matrices.

2019-07-31 02:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=18917) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=18917) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=18917) it.</sub>

2019-07-31 05:15 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +/* Copyright (c) 2016 PaddlePaddle Authors. All Rights Reserved.
why not 2019?

2019-07-31 05:17 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +    auto num_rows = ctx->Attrs().Get<int64_t>("num_rows");
Is any reference to this attribute name `num_rows`? Is this common enough?

2019-07-31 05:17 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +    PADDLE_ENFORCE(num_rows >= 0,
why is it valid to be equal to `0`?

2019-07-31 05:21 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +        num_columns >= 0,
the same problem with `num_rows`

2019-07-31 05:24 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +Return an identity tensor
lack of descriptions about this op

2019-07-31 05:25 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cc
> +                       ops::EyeKernel<CPU, int64_t>, ops::EyeKernel<CPU, int>,
strange format

2019-07-31 05:25 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.cu
> +/* Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
why not 2019?

2019-07-31 05:26 UTC, gavin1332 commented on paddle/fluid/operators/eye_op.h
> +/* Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
why not 2019?

2019-07-31 06:10 UTC, gavin1332 commented on python/paddle/fluid/tests/unittests/test_eye_op.py
> +#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
why not 2019?

2019-07-31 06:12 UTC, gavin1332 commented on python/paddle/fluid/tests/unittests/test_eye_op.py
> +            'num_columns': 3019,
is the number a little large?

2019-07-31 06:13 UTC, gavin1332 commented on python/paddle/fluid/tests/unittests/test_eye_op.py
> +
missing test for `batch_shape`

2019-07-31 06:14 UTC, gavin1332 requested changes
fix copyright and response to the questions

2019-08-01 13:13 UTC, ForFishes commented
![MacHi 2019-08-01 21-09-10](https://user-images.githubusercontent.com/19485646/62296186-28dfca00-b4a1-11e9-9bd4-0342c414c57b.png)

2019-08-01 13:15 UTC, ForFishes commented
![MacHi 2019-08-01 21-09-10](https://user-images.githubusercontent.com/19485646/62296316-66dcee00-b4a1-11e9-8bbb-e67a499d5ae5.png)

2019-08-02 06:18 UTC, closed without merging