[WIP]Sync mode fix
PaddlePaddle/Paddle pull request #18984
Opened 2019-08-02 08:47 UTC by seiriosPlus

2019-08-12 11:18 UTC, gongweibao commented on python/paddle/fluid/transpiler/distribute_transpiler.py
> +                    "sync_mode": True,
Why hard code `True`?

2019-08-12 11:19 UTC, gongweibao requested changes
Some need fix.

2019-08-22 03:54 UTC, seiriosPlus commented on python/paddle/fluid/transpiler/distribute_transpiler.py
> +                    "sync_mode": True,
取消trainer端 rpc client内部的计数，修改为send_op/recv_op内部计数， op不再需要sync_mode

2019-08-23 06:14 UTC, guru4elephant approved these changes
LGTM

2019-08-23 06:21 UTC, luotao1 approved these changes
LGTM for paddle_enforce

2019-08-26 01:32 UTC, gongweibao approved these changes
LGTM++

2019-08-26 02:04 UTC, merged