test=develop, Optimized error reporting information
PaddlePaddle/Paddle pull request #19173
Opened 2019-08-13 07:04 UTC by silingtong123

将paddle windows安装成功时import出现的dll相关错误信息进行了优化，给出了Visual C++ Redistributable的下载地址

2019-08-20 11:25 UTC, liupluswei approved these changes
LGTM

2019-08-20 11:32 UTC, liupluswei requested changes

2019-08-20 11:32 UTC, liuwei1031 commented on python/paddle/importScipy.py
> +# Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
maybe better use check_import_scipy.py as the filename?

2019-08-20 11:32 UTC, liuwei1031 commented on python/paddle/importScipy.py
> +def funcImportScipy(OsName):
funcImportScipy => check_import_scipy

2019-08-20 11:32 UTC, liuwei1031 commented on python/paddle/fluid/tests/unittests/test_import_Paddlefluid.py
> +# Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
test_import_Paddlefluid.py => test_check_import_scipy.py

2019-08-20 11:33 UTC, silingtong123 commented on python/paddle/fluid/tests/unittests/test_import_Paddlefluid.py
> +# Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
OK

2019-08-20 11:33 UTC, silingtong123 commented on python/paddle/importScipy.py
> +def funcImportScipy(OsName):
ok

2019-08-20 11:34 UTC, silingtong123 commented on python/paddle/importScipy.py
> +def funcImportScipy(OsName):
ok

2019-08-26 02:35 UTC, liupluswei approved these changes
LGTM

2019-08-26 02:35 UTC, merged