add python coverage launch when WITH_COVERAGE=ON
PaddlePaddle/Paddle pull request #19264
Opened 2019-08-16 13:45 UTC by kh2se2013

resolve #19261

2019-08-18 02:00 UTC, gongweibao requested changes

2019-08-18 02:00 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            ps_cmd = "%s -m coverage run --branch -p %s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver"
Duplicate with 498

2019-08-18 02:00 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            tr_cmd = "%s -m coverage run --branch -p %s --role trainer --endpoints %s --trainer_id %d --current_endpoint %s --trainers %d --update_method pserver --lr %f"
Duplicate with 601

2019-08-18 02:00 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            tr_cmd = "%s -u -m coverage run --branch -p %s --role trainer --endpoints %s --trainer_id %d --current_endpoint %s --update_method %s --lr %f"
Duplicate with 682

2019-08-18 02:00 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            env['COVERAGE_FILE'] = os.getenv('COVERAGE_FILE', '')
env['COVERAGE_FILE'] = 'ON'

2019-08-18 02:46 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            ps_cmd = "%s -m coverage run --branch -p %s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver"
与 #498 相比，#502 增加了 -m coverage run --branch -p 以启用覆盖率。下同

2019-08-18 02:48 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            env['COVERAGE_FILE'] = os.getenv('COVERAGE_FILE', '')
当 WITH_COVERAGE = ON 时，设置 COVERAGE_FILE 以设定覆盖率数据文件路径。

2019-08-18 02:51 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            ps_cmd = "%s -m coverage run --branch -p %s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver"
你不觉得这段出现了两回？
`%s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver`

2019-08-19 02:22 UTC, kolinwei approved these changes

2019-08-19 02:26 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            ps_cmd = "%s -m coverage run --branch -p %s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver"
Done

2019-08-19 05:35 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            env['COVERAGE_FILE'] = os.getenv('COVERAGE_FILE', '')
IGNORED

2019-08-19 05:42 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            ps_cmd = "%s -m coverage run --branch -p %s --role pserver --endpoints %s --trainer_id 0 --current_endpoint %s --trainers %d --update_method pserver"
Done

2019-08-19 05:42 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            tr_cmd = "%s -m coverage run --branch -p %s --role trainer --endpoints %s --trainer_id %d --current_endpoint %s --trainers %d --update_method pserver --lr %f"
Done

2019-08-19 05:49 UTC, kh2se2013 commented on python/paddle/fluid/tests/unittests/test_dist_base.py
> +            env['COVERAGE_FILE'] = os.getenv('COVERAGE_FILE', '')
Ignored

2019-08-19 06:02 UTC, gongweibao approved these changes
LGTM

2019-08-19 06:03 UTC, merged