add pool2d quantization support, only for max-pooling.
PaddlePaddle/Paddle pull request #19310
Opened 2019-08-20 14:24 UTC by wzzju

Add pool2d quantization support, but only for max-pooling. Because average-pooling is not suitable for the fake quantization. For example, 
![image](https://user-images.githubusercontent.com/17102274/63355576-ec650700-c398-11e9-88a5-736c456ee821.png)
![image](https://user-images.githubusercontent.com/17102274/63355708-2930fe00-c399-11e9-93a3-74c6ec0f7100.png)

2019-08-22 10:08 UTC, xyoungli approved these changes
add support for max-pooling

2019-08-22 12:02 UTC, wanghaoshuang requested changes

2019-08-22 12:02 UTC, wanghaoshuang commented on python/paddle/fluid/contrib/slim/quantization/quantization_pass.py
> +                 skip_pattern='skip_quant'):
Please add some comments for `skip_pattern`.

2019-08-22 12:02 UTC, wanghaoshuang commented on python/paddle/fluid/contrib/slim/tests/test_quantization_pass.py
> +    with fluid.name_scope(quant_skip_pattern):
Please add a document to explain the usage of name scope in quantization task.

2019-08-22 12:02 UTC, wanghaoshuang commented on python/paddle/fluid/contrib/slim/quantization/quantization_pass.py
> +    "dropout", "split", "prelu", "conv2d_transpose", "leaky_relu"
pylint will format `["mul", "conv2d", "pool2d",]` into

```
["mul", 
"conv2d", 
"pool2d",
]
```
which is the recommended style in paddle repo. 
Such as https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L38

2019-08-22 12:11 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/quantization_pass.py
> +    "dropout", "split", "prelu", "conv2d_transpose", "leaky_relu"
应该是都可以的吧，我语法检测ci过了，进行了clang-format格式化。

2019-08-23 02:12 UTC, wanghaoshuang approved these changes

2019-08-23 02:12 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/quantization_pass.py
> +                 skip_pattern='skip_quant'):
> Please add some comments for `skip_pattern`.

Thx, it will be added in next pr.

2019-08-23 02:13 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_quantization_pass.py
> +    with fluid.name_scope(quant_skip_pattern):
Thx, it will be added soon.

2019-08-23 02:17 UTC, luotao1 approved these changes
LGTM for framework.py

2019-08-23 02:40 UTC, merged