bug fix for ce
PaddlePaddle/Paddle pull request #19360
Opened 2019-08-22 11:31 UTC by wangchaochaohu

dropout make the image_classicification model test_acc drop ,fix the bug

2019-08-22 11:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=19360) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=19360) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=19360) it.</sub>

2019-09-05 06:47 UTC, zhaoyuchen2018 approved these changes

2019-09-06 02:23 UTC, kolinwei approved these changes

2019-09-11 01:51 UTC, chengduoZH requested changes
Can you explain what problem this PR solves?

2019-09-11 03:47 UTC, wangchaochaohu commented
> Can you explain what problem this PR solves?
to improve the performance of dropout

2019-09-27 07:21 UTC, closed without merging