Fix build error in MacOS
PaddlePaddle/Paddle pull request #1937
Opened 2017-04-28 05:01 UTC by reyoung

* Because protobuf 3.1.0 uses a deprecated API.
* Partially fix issue #1936.

2017-05-01 02:31 UTC, wangkuiyi requested changes

2017-05-01 02:31 UTC, wangkuiyi commented on cmake/flags.cmake
> +    -Wno-error=deprecated-declarations)
`no-error-deprecated-declarations` 是个我们不希望增加的flag。为什么需要加上呢？

2017-05-02 05:04 UTC, reyoung commented on cmake/flags.cmake
> +    -Wno-error=deprecated-declarations)
因为我们使用了Protobuf 3.1.0，但是Protobuf 3.1.0自己有一个地方使用了 deprecated API。Protobuf的issue在[这里](https://github.com/google/protobuf/issues/2182)

如果要根治这个问题，我们需要将Prootbuf升级到3.2.0。但是，目前临时fix这个问题，我们先将这个warning在develop branch中，不将其看成error。

2019-02-01 12:07 UTC, luotao1 commented
Close due to Mac build is successful now.

2019-02-01 12:07 UTC, closed without merging