Improve elementwise operators performance in same dimensions.
PaddlePaddle/Paddle pull request #19763
Opened 2019-09-11 09:45 UTC by danleifeng

changes are included:
1. add mkl(for cpu) and cuda kernel(for gpu) codes  for performance in same dimensions.(add/sub/div)
2. import cuda math api(__hadd2, etc)  for float16 performance in same dimensions.(add/sub/mul/div)
3. use macro define and template functions for code conciseness.

2019-09-11 10:08 UTC, luotao1 commented
It's better to separate this PR into two PRs, one for CPU, and one for GPU.

2019-09-11 11:31 UTC, zhaoyuchen2018 commented
Could you please give some performance data?  
@kuke   maybe  can check performance improves on your model.

2019-09-18 04:18 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_add_op.cc
> +    VLOG(5) << "====into eigen ===";
Delete these vlog after debug!

2019-09-18 05:10 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
> +#define PADDLE_CUDA_FP16
duplicate code with float16.h.

2019-09-18 05:11 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
> +#define PADDLE_CUDA_FP16
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/float16.h#L36

2019-09-18 05:12 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_mul_op.cu
>  #define TILE_SIZE 512
Duplicate defination.

2019-09-18 05:15 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_add_op.cu
> +template struct SameDimsElemwiseAdd<platform::CUDADeviceContext, float>;
下边这几行可以用宏，因为不是需要对用户可读友好的代码！

2019-09-18 05:16 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_div_op.cu
> +class ElementwiseDivGradKernel<plat::CUDADeviceContext, T>
Clear this class!

2019-09-19 01:32 UTC, gongweibao requested changes

2019-09-19 01:32 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_add_op.cu
> +    getAddFunctor<T> functor(x->data<T>(), y->data<T>(), z->data<T>());
AddFunctor?

2019-09-24 12:37 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_add_op.cc
> +    VLOG(5) << "====into eigen ===";
done.

2019-09-24 12:47 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_mul_op.cu
>  #define TILE_SIZE 512
done.

2019-09-24 12:48 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_add_op.cu
> +template struct SameDimsElemwiseAdd<platform::CUDADeviceContext, float>;
done.

2019-09-24 12:48 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_div_op.cu
> +class ElementwiseDivGradKernel<plat::CUDADeviceContext, T>
done.

2019-09-24 12:51 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_add_op.cu
> +    getAddFunctor<T> functor(x->data<T>(), y->data<T>(), z->data<T>());
AddFunctor is defined in elementwise_op_function.cu.h
maybe AddRangeFunctor better.

2019-09-24 12:51 UTC, gongweibao requested changes

2019-09-24 12:51 UTC, gongweibao commented on paddle/fluid/operators/math/blas_impl.h
> +  // VLOG(5) << "====into PADDLE_WITH_MKLML =>CBlas<T>::VDIV ===";
Clear this and other comments!

2019-09-24 12:57 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_op_function.h
> +#define TILE_SIZE 512
Is this needed?

2019-09-25 03:50 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
> +#define PADDLE_CUDA_FP16
done.

2019-09-25 03:50 UTC, danleifeng commented on paddle/fluid/operators/math/blas_impl.h
> +  // VLOG(5) << "====into PADDLE_WITH_MKLML =>CBlas<T>::VDIV ===";
done.

2019-09-25 03:51 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_op_function.h
> +#define TILE_SIZE 512
no need. 
already deleted.

2019-09-30 05:19 UTC, gongweibao approved these changes
LGTM

2019-09-30 05:19 UTC, merged