Avoid treating broadcast as initialization operation
PaddlePaddle/Paddle pull request #19857
Opened 2019-09-18 09:32 UTC by ForFishes

When the mode is localsgd mode, an error of two initializations will occur. The broadcast should be treated as a non-initialized operation here. Think of broadcast as a special case here.
<img width="1288" alt="MacHi 2019-09-18 17-31-10" src="https://user-images.githubusercontent.com/19485646/65136454-2ed24000-da3a-11e9-9af0-154d06270c70.png">

2019-09-24 05:58 UTC, gavin1332 commented on python/paddle/fluid/tests/unittests/test_avoid_broadcast.py
> +class Test_Avoid_Broadcast(unittest.TestCase):
the class name is illegal

2019-09-24 05:59 UTC, gavin1332 requested changes
The class name of TestAvoidBroadcast is illegal

2019-09-25 02:16 UTC, gavin1332 approved these changes
LGTM

2019-09-25 02:42 UTC, luotao1 approved these changes
LGTM for framework.py

2019-09-25 05:07 UTC, merged