update operator compatible info, test=develop
PaddlePaddle/Paddle pull request #19978
Opened 2019-09-24 18:05 UTC by Shixiaowei02

2019-09-25 02:39 UTC, Superjomn reviewed
想想怎么加上单测，验证下load那块的逻辑

2019-09-25 02:39 UTC, Superjomn commented on paddle/fluid/framework/compatible.proto
> +
放到原来的proto里，不要单独增加 proto 文件

不然所有第三方仓库比如lite 的适配都很麻烦

2019-09-25 12:39 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
此处的逻辑会限制后续版本向前兼容，所以更改为未实现。

2019-09-25 12:39 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
此处的逻辑会限制后续版本向前兼容，所以更改为未实现。

2019-09-25 12:41 UTC, Shixiaowei02 commented on paddle/fluid/framework/framework.proto
> +  reserved 2;
由于较早版本 paddle/fluid/framework/version.cc 的限制，为向后兼容（此更改之后使用 save_inference_model 接口保存的模型能在旧版本执行预测），此处需更改 version 域的标号，并弃用之前的标号。

2019-09-25 12:46 UTC, Shixiaowei02 commented on python/paddle/fluid/io.py
> +        main_program.desc._set_version()
使用 save_inference_model 保存模型时，ProgramDesc 对象的创建使用的是 C++ ProgramDesc::ProgramDesc(const std::string &binary_str) 构造函数，这个构造函数只负责反序列化 ProgramDescProto，所以 version 域的更改 Python 代码在保存前显式完成。

2019-09-25 12:48 UTC, Shixiaowei02 commented on paddle/fluid/framework/framework.proto
> +
Protobuf 3.1.0 的 src/map.h 存在 const 类型语法问题，所以此处使用 message 替代原生 proto map 数据结构。

2019-09-25 12:52 UTC, Shixiaowei02 commented on cmake/version.cmake
> +add_definitions(-DPADDLE_VERSION_INTEGER=${PADDLE_VERSION_INTEGER})
代码内部使用 int 表示版本号，1.5.2 内部表示为 1005002。

2019-09-26 02:46 UTC, Superjomn requested changes

2019-09-26 02:46 UTC, Superjomn commented on cmake/version.cmake
> +string(REPLACE "." ";" PADDLE_VER_LIST ${PADDLE_VERSION})
这个，可以尝试本地打个跟官方版本一致的 tag，看看能不能解析

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/framework.proto
> +message CompatibleInfo {
核心数据结构，加注释描述下

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/framework.proto
> +message OpCompatibleMap {
同上

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/op_compatible_info.h
> +  bool Save(proto::OpCompatibleMap* desc) const;
核心方法，所有的函数都加注释，必要的话加例子，到能看懂大致功能的程度
防止后续其他人看不懂，自己重新写

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/version.cc
> +  return true;
打一个 FATAL？避免用了，没报错，结果错了，也不知道来改这里

```c++
LOG(FATAL) << "int64 version comparison not supported yet."
```

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/version.cc
> +  return true;
同上

2019-09-26 02:46 UTC, Superjomn commented on paddle/fluid/framework/version.cc
> +std::string VersionString(const int64_t version) {
DumpVersion?

2019-09-26 02:50 UTC, Shixiaowei02 commented on cmake/version.cmake
> +string(REPLACE "." ";" PADDLE_VER_LIST ${PADDLE_VERSION})
可以解析，功能试过了

2019-09-26 03:04 UTC, phlrain commented on paddle/fluid/framework/op_compatible_info.h
> +  bool Load(const proto::OpCompatibleMap& desc);
这个save load，并没有存储到文件，或者一个buffer中，用一个别的表述 convert 这类 是不是会好一点

2019-09-26 03:24 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_compatible_info.h
> +  bool Load(const proto::OpCompatibleMap& desc);
好的，我改一下。

2019-09-26 05:58 UTC, Shixiaowei02 commented on paddle/fluid/framework/framework.proto
> +message CompatibleInfo {
> 核心数据结构，加注释描述下

已经添加注释。

2019-09-26 05:59 UTC, Shixiaowei02 commented on paddle/fluid/framework/framework.proto
> +message OpCompatibleMap {
> 同上

已经添加注释。

2019-09-26 05:59 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
> 打一个 FATAL？避免用了，没报错，结果错了，也不知道来改这里
> 
> ```c++
> LOG(FATAL) << "int64 version comparison not supported yet."
> ```

已经添加注释信息，此接口一直都不起作用且影响向后兼容，所以暂时停用，后续可能取消。

2019-09-26 06:00 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
> 同上

已经添加注释信息，此接口一直未作用且影响向后兼容，所以暂时停用，后续可能取消。

2019-09-26 06:00 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
> 同上

> 同上

已经添加注释信息，此接口一直未作用且影响向后兼容，所以暂时停用，后续可能取消。

2019-09-26 06:00 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
> 同上

已经添加注释信息，此接口一直未作用且影响向后兼容，所以暂时停用，后续可能取消。

2019-09-26 06:01 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +  return true;
> 同上

已经添加注释信息，此接口一直未作用且影响向后兼容，所以暂时停用，后续可能取消。

2019-09-26 06:02 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_compatible_info.h
> +  bool Save(proto::OpCompatibleMap* desc) const;
> 核心方法，所有的函数都加注释，必要的话加例子，到能看懂大致功能的程度
> 防止后续其他人看不懂，自己重新写

已更改接口名称，并添加注释。

2019-09-26 06:03 UTC, Shixiaowei02 commented on paddle/fluid/framework/version.cc
> +std::string VersionString(const int64_t version) {
> DumpVersion?

已更改接口名称。

2019-09-26 06:03 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_compatible_info.h
> +  bool Load(const proto::OpCompatibleMap& desc);
> 这个save load，并没有存储到文件，或者一个buffer中，用一个别的表述 convert 这类 是不是会好一点

已更改接口名称，并添加注释。

2019-09-26 09:27 UTC, phlrain commented on paddle/fluid/pybind/protobuf.cc
> +      .def("_set_version",
_ 打头的python接口的建议好像是 不建议用户使用，只是我们开发人员用 我们这个地方 _ 是这个意思吗

2019-09-26 10:36 UTC, Shixiaowei02 commented on paddle/fluid/pybind/protobuf.cc
> +      .def("_set_version",
是的。原来只有获取版本的接口，不能设置版本。这里开放了设置版本号的接口。

2019-09-27 10:56 UTC, phlrain approved these changes

2019-09-27 11:51 UTC, sneaxiy approved these changes

2019-09-27 12:59 UTC, Superjomn approved these changes
LGTM

2019-09-27 13:00 UTC, merged