Modify doc for shuffle, firstn, save_vars, load_vars, L1DecayRegularizer, L2DecayRegularizer
PaddlePaddle/Paddle pull request #20287
Opened 2019-10-09 06:02 UTC by juncaipeng

* reader.shuffle
![image](https://user-images.githubusercontent.com/52520497/66454684-1aaebb00-ea9b-11e9-8a4f-90ae58135db7.png)
![image](https://user-images.githubusercontent.com/52520497/66454698-21d5c900-ea9b-11e9-8060-19849da0e9bd.png)

* fluid.io.shuffle
![image](https://user-images.githubusercontent.com/52520497/66454752-53e72b00-ea9b-11e9-92f4-6becce419e59.png)
![image](https://user-images.githubusercontent.com/52520497/66455376-2ef3b780-ea9d-11e9-8d05-44f50250567b.png)

* reader.firstn
![image](https://user-images.githubusercontent.com/52520497/66454728-387c2000-ea9b-11e9-9da4-eefcc2c1bab8.png)
![image](https://user-images.githubusercontent.com/52520497/66454732-3e720100-ea9b-11e9-9985-700207e90a78.png)

* fluid.io.firstn
![image](https://user-images.githubusercontent.com/52520497/66454809-83963300-ea9b-11e9-8310-9b3efe0395f7.png)
![image](https://user-images.githubusercontent.com/52520497/66454814-898c1400-ea9b-11e9-8f79-ea2ed766ae2f.png)

* save_vars
![image](https://user-images.githubusercontent.com/52520497/66454866-ba6c4900-ea9b-11e9-9c19-bf02d47a1ea6.png)
![image](https://user-images.githubusercontent.com/52520497/66454893-cb1cbf00-ea9b-11e9-9a68-3ec586fc2031.png)
![image](https://user-images.githubusercontent.com/52520497/66454909-d40d9080-ea9b-11e9-883c-2618857b5e24.png)

* load_vars
![image](https://user-images.githubusercontent.com/52520497/66454929-e25bac80-ea9b-11e9-8c62-0339a780a1d3.png)
![image](https://user-images.githubusercontent.com/52520497/66454941-e982ba80-ea9b-11e9-9867-ff335210d75f.png)
![image](https://user-images.githubusercontent.com/52520497/66454966-fc958a80-ea9b-11e9-94aa-dc34adc74baa.png)
![image](https://user-images.githubusercontent.com/52520497/66454975-028b6b80-ea9c-11e9-87ef-7d269057a6cd.png)

* L1DecayRegularizer
![image](https://user-images.githubusercontent.com/52520497/66455032-2babfc00-ea9c-11e9-953e-4ed61cb6ea1b.png)
![image](https://user-images.githubusercontent.com/52520497/66455418-4894ff00-ea9d-11e9-9055-02f60e46d075.png)

* L1Decay
![image](https://user-images.githubusercontent.com/52520497/66455052-39618180-ea9c-11e9-8148-d37b7b878862.png)

* L2DecayRegularizer
![image](https://user-images.githubusercontent.com/52520497/66455116-66159900-ea9c-11e9-99dd-b8f9dd9b1498.png)
![image](https://user-images.githubusercontent.com/52520497/66455128-6ca41080-ea9c-11e9-9776-71840157a71f.png)

* L2Decay
![image](https://user-images.githubusercontent.com/52520497/66455140-788fd280-ea9c-11e9-8bbc-85a5f81bab85.png)

2019-10-09 07:29 UTC, wzzju requested changes

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +	    # outputs are 0~4 disordered arrangemen
distordered --> unordered
`def reader():`及下面的示例代码行与import左对齐。
imprt之后空一行。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +    Creates a decorated reader that outputs the shuffled data.
祈使句，Creates不需要加s。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +    Creates a decorated reader, and limits the max number of samples that reader could return.
祈使句，Creates以及limits不需要加s。

Create a decorated reader and limit the max number of samples that the input `reader` could return.

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +    :param reader: the input reader.
这种格式改成 `Args:`和`Returns:`的，保持与其他API的写法统一。参考 #20274 中的chain。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +    :param reader: the original reader whose data will be shuffled.
这种格式改成 `Args:`和`Returns:`的，保持与其他API的写法统一。参考 #20274 中的chain。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/reader/decorator.py
> +            import paddle.fluid as fluid
`def reader():`及下面的示例代码行与import左对齐。
imprt之后空一行。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/regularizer.py
> +    Implements the L2 Weight Decay Regularization, which helps to prevent the model over-fitting.
感觉这中动词开头的都不要加s吧，类似祈使句？

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/regularizer.py
> +    Implements the L1 Weight Decay Regularization, which encourages the weights to be sparse.
感觉这中动词开头的都不要加s吧，类似祈使句？

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/regularizer.py
> +        regularization_coeff(float): regularization coeff, the default value is 0.0.
若是该参数是可选的，请写成`regularization_coeff(float, optional)`.

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/io.py
>          main_program(Program|None): The program whose variables will be saved.
`main_program(Program|None)`改成`main_program(Program, optional)`，并在注释中说明默认值。类似的都改一下吧。

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/io.py
> +    This function saves the specific variables in the `Program` to files.
This API

2019-10-09 07:29 UTC, wzzju commented on python/paddle/fluid/io.py
> +    The `dirname` is used to specify the folder where to save the variables.
the variables，复数前不需要加the，其余的类似.

2019-10-09 10:43 UTC, juncaipeng commented on python/paddle/reader/decorator.py
> +	    # outputs are 0~4 disordered arrangemen
> distordered --> unordered
> `def reader():`及下面的示例代码行与import左对齐。
> imprt之后空一行。

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/reader/decorator.py
> +    Creates a decorated reader that outputs the shuffled data.
> 祈使句，Creates不需要加s。

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/reader/decorator.py
> +    Creates a decorated reader, and limits the max number of samples that reader could return.
> 祈使句，Creates以及limits不需要加s。
> 
> Create a decorated reader and limit the max number of samples that the input `reader` could return.

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/reader/decorator.py
> +    :param reader: the input reader.
> 这种格式改成 `Args:`和`Returns:`的，保持与其他API的写法统一。参考 #20274 中的chain。

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/reader/decorator.py
> +    :param reader: the original reader whose data will be shuffled.
> 这种格式改成 `Args:`和`Returns:`的，保持与其他API的写法统一。参考 #20274 中的chain。

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/fluid/regularizer.py
> +    Implements the L1 Weight Decay Regularization, which encourages the weights to be sparse.
> 感觉这中动词开头的都不要加s吧，类似祈使句？

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/fluid/regularizer.py
> +        regularization_coeff(float): regularization coeff, the default value is 0.0.
> 若是该参数是可选的，请写成`regularization_coeff(float, optional)`.

Done

2019-10-09 10:44 UTC, juncaipeng commented on python/paddle/fluid/io.py
>          main_program(Program|None): The program whose variables will be saved.
> `main_program(Program|None)`改成`main_program(Program, optional)`，并在注释中说明默认值。类似的都改一下吧。

Done

2019-10-09 10:45 UTC, juncaipeng commented on python/paddle/fluid/io.py
> +    This function saves the specific variables in the `Program` to files.
> This API

Done

2019-10-09 10:45 UTC, juncaipeng commented on python/paddle/fluid/io.py
> +    The `dirname` is used to specify the folder where to save the variables.
> the variables，复数前不需要加the，其余的类似.

Done

2019-10-09 12:20 UTC, wzzju submitted a review, later dismissed
LGTM.

2019-10-10 03:08 UTC, wanghaoshuang submitted a review, later dismissed

2019-10-10 03:53 UTC, Superjomn submitted a review, later dismissed
LGTM

2019-10-10 09:22 UTC, wzzju submitted a review, later dismissed
LGTM.

2019-10-10 11:00 UTC, Superjomn submitted a review, later dismissed

2019-10-10 11:25 UTC, wanghaoshuang submitted a review, later dismissed

2019-10-10 12:53 UTC, heavengate submitted a review, later dismissed

2019-10-11 02:23 UTC, Superjomn approved these changes

2019-10-11 02:32 UTC, heavengate approved these changes

2019-10-11 03:04 UTC, merged