fix document for swish, thresholded_relu, gaussian_randdom, test=document_fix
PaddlePaddle/Paddle pull request #20284
Opened 2019-10-09 05:41 UTC by iclementine

![图片](https://user-images.githubusercontent.com/16222986/66454393-539a6000-ea9a-11e9-9142-f9c2d961a85e.png)
![Screenshot_2019-10-09 swish — fluiddoc dev documentation](https://user-images.githubusercontent.com/16222986/66454412-6745c680-ea9a-11e9-9243-d1eae9f8f404.png)
![Screenshot_2019-10-09 gaussian_random — fluiddoc dev documentation](https://user-images.githubusercontent.com/16222986/66454441-7af12d00-ea9a-11e9-85e2-74952b1272a9.png)

2019-10-09 09:58 UTC, kuke submitted a review, later dismissed
LGTM

2019-10-09 10:55 UTC, wanghaoshuang submitted a review, later dismissed

2019-10-09 11:11 UTC, shippingwang requested changes

2019-10-09 11:11 UTC, shippingwang commented on python/paddle/fluid/layers/nn.py
> +            x = fluid.layers.gaussian_random((2, 3), std=2., seed=10)
it should be ```swish```

2019-10-09 11:44 UTC, iclementine commented on python/paddle/fluid/layers/nn.py
> +            x = fluid.layers.gaussian_random((2, 3), std=2., seed=10)
done, it is fixed!

2019-10-09 14:40 UTC, wanghaoshuang submitted a review, later dismissed

2019-10-09 15:27 UTC, guoshengCS commented on python/paddle/fluid/layers/nn.py
> +    Elementwise swish activation function. Se `Searching for Activation Functions <https://arxiv.org/abs/1710.05941>`_ for more details.
Se->See

2019-10-09 15:27 UTC, guoshengCS commented on python/paddle/fluid/layers/nn.py
> +        x(Variable): dtype: float32 or float64, the input.
加上Variable的类型Tensor or LoDTensor

2019-10-10 04:58 UTC, iclementine commented on python/paddle/fluid/layers/nn.py
> +    Elementwise swish activation function. Se `Searching for Activation Functions <https://arxiv.org/abs/1710.05941>`_ for more details.
Done!

2019-10-10 04:58 UTC, iclementine commented on python/paddle/fluid/layers/nn.py
> +        x(Variable): dtype: float32 or float64, the input.
Done!

2019-10-10 06:25 UTC, shippingwang approved these changes
good job!

2019-10-10 06:27 UTC, guoshengCS approved these changes

2019-10-10 06:58 UTC, kuke approved these changes

2019-10-10 08:29 UTC, wanghaoshuang approved these changes

2019-10-10 09:48 UTC, merged