add input type and dtype check for accuracy_op
PaddlePaddle/Paddle pull request #20399
Opened 2019-10-10 07:59 UTC by JesseyXujin

2019-10-10 08:16 UTC, JesseyXujin commented
**fluid.layers.accuracy**
+ Check accuracy shape
```python
import paddle.fluid as fluid
import numpy as np
x1 = fluid.layers.data(name='input', shape=[-1,1], dtype="float32")
label = fluid.layers.data(name='label', shape=[-1], dtype="int32")
fluid.layers.accuracy(x1,label=label)
```
**before:** `label's rank must be 2`
**after:** `ShapeError: label's dimensions of AccuracyOp must be 2. But received label's dimensions = 1`
```python
import paddle.fluid as fluid
import numpy as np
x1 = fluid.layers.data(name='input', shape=[-1,1], dtype="float32")
label = fluid.layers.data(name='label', shape=[-1,2], dtype="int32")
fluid.layers.accuracy(x1,label=label)
```
**before:** `label's second dimension must be 1`
**after:** `ShapeError: label's second dimension of AccuracyOp must be 1. But received label's second dimension is = 2.`
```python
import paddle.fluid as fluid
import numpy as np
data = fluid.layers.data(name="input", shape=[-1, 32, 32], dtype="float16")
label = fluid.layers.data(name="label", shape=[-1,1], dtype="int32")
fc_out = fluid.layers.fc(input=data, size=10)
predict = fluid.layers.softmax(input=fc_out)
result = fluid.layers.accuracy(input=predict, label=label, k=5)
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
x = np.random.rand(3, 32, 32).astype("float16")
y = np.array([[1],[0],[1]])
output= exe.run(feed={"input": x,"label": y},
                 fetch_list=[result[0]])
print(output)```
**before:** `the inference tensor's num_rows must be the same as label.`
**after:** `ShapeError:the output's num_rows of AccuracyOp must be the same as label's num_rows. But received output's shape = [1, 32, 1], label's shape = [3, 1], output's num_rows = 1, label's num_rows = 3`

2019-10-10 08:22 UTC, xyzhou-puck commented on paddle/fluid/operators/metrics/accuracy_op.cc
> +                                 "ShapeError: label's second dimension of "
embedding，one-hot等op已经去掉了这个要求，可以确认一下是否ok。

2019-10-10 08:29 UTC, xyzhou-puck submitted a review, later dismissed
LGTM

2019-10-10 08:48 UTC, chenwhql commented on python/paddle/fluid/layers/metric_op.py
> +            "The type of 'input' in softmax must be Variable, but received %s" %
softmax -> accuracy

2019-10-10 08:51 UTC, chenwhql commented on paddle/fluid/operators/metrics/accuracy_op.cc
> +                      "ShapeError: label's dimensions of AccuracyOp must be 2. "
请遵守规则，打印出的具体的dim

![image](https://user-images.githubusercontent.com/22561442/66553683-26bf7900-eb7e-11e9-91b6-5cad979d129d.png)

参照示例：https://github.com/PaddlePaddle/Paddle/pull/19998

2019-10-10 08:53 UTC, chenwhql commented on paddle/fluid/operators/metrics/accuracy_op.cc
> +                                 label_dim[1]);
同上

2019-10-10 08:58 UTC, chenwhql commented on paddle/fluid/operators/metrics/accuracy_op.cc
> +        "ShapeError:the output's num_rows of AccuracyOp must be"
`ShapeError:`后面增加一个空格

2019-10-10 08:59 UTC, chenwhql reviewed
accuracy_op.h，这个文件没有实际修改，为什么要提交？建议checkout回去

2019-10-10 09:29 UTC, chenwhql approved these changes
LGTM

2019-10-11 03:36 UTC, chenwhql requested changes
accuracy op是支持float1.6的，请增加python端类型的检查

2019-10-11 06:50 UTC, chenwhql commented on python/paddle/fluid/layers/metric_op.py
> +    if convert_dtype(input.dtype) not in ['float16', 'float32', 'float64']:
请添加fp16的warning提示

2019-10-11 06:54 UTC, chenwhql approved these changes

2019-10-11 12:05 UTC, merged