add assertions on whether elementwise_div divison is zero
PaddlePaddle/Paddle pull request #20618
Opened 2019-10-14 11:20 UTC by danleifeng

type `int, int64`: throw exception action
```
PaddleCheckError: Expected y_data_ != 0, but received y_data_:0 == 0:0.
InvalidArgumentError: Integer division by zero encountered in divide.Please check. 
[operator < elementwise_div > error]
```
type `float16,float32,float64`: only throw warnings and return inf.
```
ArgumentWarning: division by zero encountered in divide
```

2019-10-17 03:08 UTC, gongweibao requested changes

2019-10-17 03:08 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_div_op.cc
> +/*
cleanup this!

2019-10-17 03:08 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
> +  template <typename T, class Enable = void>                                  \
Where `enable` is used?

2019-10-17 07:26 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_div_op.cc
> +/*
done.

2019-10-17 07:26 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_op_function.cu.h
> +  template <typename T, class Enable = void>                                  \
#86

2019-10-17 10:14 UTC, gongweibao submitted a review, later dismissed
LGTM

2019-10-20 12:34 UTC, luotao1 approved these changes

2019-10-20 13:25 UTC, merged