Make shape tensor support int32
PaddlePaddle/Paddle pull request #20757
Opened 2019-10-21 10:47 UTC by silingtong123

Make shape tensor support int32

2019-10-21 12:25 UTC, liuwei1031 commented on paddle/fluid/operators/uniform_random_op.h
> +    std::vector<int64_t> vec_new_data(new_data,
why create a new vector here?

2019-10-21 13:12 UTC, silingtong123 commented on paddle/fluid/operators/uniform_random_op.h
> +    std::vector<int64_t> vec_new_data(new_data,
这个分支只创建了一个vector，这个vetcor是返回值所需要的

2019-10-22 09:29 UTC, wanghaoshuang submitted a review, later dismissed

2019-10-22 10:28 UTC, Superjomn requested changes
不允许使用临时 tensor

2019-10-22 10:28 UTC, Superjomn commented on paddle/fluid/operators/uniform_random_op.cc
> +             "uniform_ranodom "
uniform_random?

2019-10-22 10:28 UTC, Superjomn commented on paddle/fluid/operators/uniform_random_op.cc
> +             "it has the highest priority compare with Input(ShapeTensor) and "
comparing?

2019-10-22 10:28 UTC, Superjomn commented on paddle/fluid/operators/uniform_random_op.h
> +      framework::Tensor cpu_starts_tensor;
不允许创建临时 tensor，会引发 allocator 的全局单例 mutex，在多线程预测会带来严重的性能问题。

2019-10-22 10:28 UTC, Superjomn commented on paddle/fluid/operators/uniform_random_op.h
> +      framework::Tensor cpu_starts_tensor;
去掉全局所有临时 tensor

2019-10-22 11:10 UTC, silingtong123 commented on paddle/fluid/operators/uniform_random_op.h
> +      framework::Tensor cpu_starts_tensor;
done

2019-10-22 11:11 UTC, silingtong123 commented
> 不允许使用临时 tensor

Done, 已全部改为指针

2019-10-22 11:11 UTC, silingtong123 commented on paddle/fluid/operators/uniform_random_op.cc
> +             "uniform_ranodom "
done

2019-10-22 11:11 UTC, silingtong123 commented on paddle/fluid/operators/uniform_random_op.cc
> +             "it has the highest priority compare with Input(ShapeTensor) and "
done

2019-10-28 09:53 UTC, Superjomn approved these changes
@Shixiaowei02 后续重构预测 allocator，以支持这类临时变量

2019-10-29 01:43 UTC, wanghaoshuang approved these changes

2019-10-29 02:47 UTC, merged