extend elementwise broadcast function
PaddlePaddle/Paddle pull request #20957
Opened 2019-11-01 07:14 UTC by danleifeng

目前的elementwise不支持功能：
1. Y矩阵比X矩阵维度大。
```
A:   (4,5)
B:(2,3,4,5)
```
2. Y矩阵与X矩阵同维度，但中间维度有多个1
```
ep1:
A:(2,1,4,1)
B:(1,3,1,5)
ep2:
A:(1,1,5)
B:(4,4,5)
```

因此本pr扩展了elementwise的功能，能够支持上述的case。并添加了相应的单测进行验证。

2019-11-12 10:07 UTC, gongweibao requested changes

2019-11-12 10:07 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_executor_return_tensor_not_overwriting.py
> +        self.op_type = "mul"
Why?

2019-11-12 10:07 UTC, gongweibao commented on paddle/fluid/operators/elementwise/elementwise_add_op.h
> +    ElementwiseComputeEx<AddFunctor<T>, DeviceContext, T>(ctx, x, y, axis,
>=?

2019-11-14 02:30 UTC, danleifeng commented on python/paddle/fluid/tests/unittests/test_executor_return_tensor_not_overwriting.py
> +        self.op_type = "mul"
它的例子用的矩阵点乘np.dot，这不是elementwise_mul,而是mul。

2019-11-14 02:30 UTC, danleifeng commented on paddle/fluid/operators/elementwise/elementwise_add_op.h
> +    ElementwiseComputeEx<AddFunctor<T>, DeviceContext, T>(ctx, x, y, axis,
大于ElementwiseComputeEx < AddFunctor > ，如果那些外部直接调用default_elementwise_add的地方有可能会有=的情况，也默认走这个。

2019-11-19 02:43 UTC, gongweibao reviewed
LGTM

2019-11-19 02:48 UTC, gongweibao commented
Please add document of the new broadcast function in the next pr.

2019-11-19 03:55 UTC, raindrops2sea approved these changes

2019-11-19 04:10 UTC, gongweibao approved these changes
LGTM

2019-11-19 04:11 UTC, luotao1 commented
> Please add document of the new broadcast function in the next pr.

@danleifeng @gongweibao 现在elementwise相关的注释都是copy，并没有用函数生成，导致重复注释很多。
能否下个PR补充文档的时候，修改下这块，也就是elementwise_xxx的注释需要生成出来，不要一个api复制一份，导致难以维护。
```
for func in []:
    op_proto = OpProtoHolder.instance().get_op_proto(func.__name__)
    func.__doc__ = _generate_doc_string_(
        op_proto,
        additional_args_lines=[
            "act (basestring|None): Activation applied to the output.",
            "name (basestring|None): Name of the output."
        ])
    func.__doc__ = func.__doc__ + """
```
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L10684

2019-11-19 04:11 UTC, luotao1 approved these changes
LGTM for paddle_enforce

2019-11-19 04:53 UTC, merged