Add decay rate on adam optimizer
PaddlePaddle/Paddle pull request #2097
Opened 2017-05-11 04:35 UTC by reyoung

2017-05-11 09:30 UTC, pengli09 requested changes

2017-05-11 09:30 UTC, pengli09 commented on paddle/math/TrainingAlgorithmOp.cu
> +    value - ((mom + dacayRate * value) * alpha) / (v.sqrt() + epsilon));
adam不像rmsprop之类的单纯只是算learning rate出来，而是对梯度本身也做了一些修正，建议整体上严格按论文中公式来改吧

2017-05-11 09:30 UTC, pengli09 commented on paddle/math/TrainingAlgorithmOp.cu
> +    value - (alpha / ((real)1 - (real)std::pow(beta1, step))) * ((mom + decayRate * value) / u));
adam不像rmsprop之类的单纯只是算learning rate出来，而是对梯度本身也做了一些修正，建议整体上严格按论文中公式来改吧

2017-05-11 09:30 UTC, pengli09 commented on paddle/math/TrainingAlgorithmOp.cu
> +  value -=  ((mom+decayRate*value) * alpha) / (v.sqrt() + epsilon);
adamax不像rmsprop之类的单纯只是算learning rate出来，而是对梯度本身也做了一些修正，建议整体上严格按论文中公式来改吧

2017-05-11 09:30 UTC, pengli09 commented on paddle/math/TrainingAlgorithmOp.cu
> +  value -= (alpha / ((real)1 - (real)std::pow(beta1, step))) * ((mom+decayRate*value) / u);
adamax不像rmsprop之类的单纯只是算learning rate出来，而是对梯度本身也做了一些修正，建议整体上严格按论文中公式来改吧

2017-05-11 09:30 UTC, pengli09 commented on paddle/parameter/FirstOrderOptimizer.cpp
> +  real dacayRate = (real)config.decay_rate();
需要检查applyDecay变量，参见rmsprop中的实现

2017-05-11 09:30 UTC, pengli09 commented on paddle/parameter/FirstOrderOptimizer.cpp
> +              (real)config.decay_rate());
获取decay_rate时，需要检查applyDecay变量，参见rmsprop中的实现

2019-02-01 04:43 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:43 UTC, closed without merging