Add Amsgrad optimizer
PaddlePaddle/Paddle pull request #20995
Opened 2019-11-04 09:13 UTC by jinxing94

Amsgrad optimizer is a variant of the Adam optimizer. It is proposed in the ICLR 2018 paper titled [on the convergence of Adam and beyond](https://openreview.net/pdf?id=ryQu7f-RZ) .  

The paper argues that the exponential moving average used in Adam optimizer may cause the model fail to converge to an optimal solution, even in some simple convex optimization settings.  Amsgrad is proposed to address the issue by endowing the algorithm with “long-term memory” of past gradients.

Both tensorflow and pytorch have added the amsgrad optimizer in their official APIs.  See the amsgrad option in the Adam APIs of tensorflow and pytorch for reference.

2019-11-04 09:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=20995) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=20995) before we can accept your contribution.<br/><hr/>**yujinxing** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=20995) it.</sub>

2019-11-06 06:17 UTC, shippingwang requested changes
*haven't finished the review yet

2019-11-06 06:17 UTC, shippingwang commented on paddle/fluid/operators/optimizers/amsgrad_op.cc
> +/* Copyright (c) 2016 PaddlePaddle Authors. All Rights Reserved.
2016->2019

2019-11-06 06:17 UTC, shippingwang commented on paddle/fluid/operators/optimizers/amsgrad_op.cc
> +This implements the Amsgrad optimizer from Section 2 of the Amsgrad
same as Adam??

2019-11-06 07:03 UTC, jinxing94 commented on paddle/fluid/operators/optimizers/amsgrad_op.cc
> +/* Copyright (c) 2016 PaddlePaddle Authors. All Rights Reserved.
Thanks for pointing this. I have changed it in a new commit.

2019-11-06 07:04 UTC, jinxing94 commented on paddle/fluid/operators/optimizers/amsgrad_op.cc
> +This implements the Amsgrad optimizer from Section 2 of the Amsgrad
No. Thanks for pointing the typo.  I have updated it in a new commit.

2020-11-18 10:46 UTC, closed without merging