[WIP]Fix dgc nan & alloc buffer illegal
PaddlePaddle/Paddle pull request #21012
Opened 2019-11-05 05:21 UTC by wangxicoding

2019-11-08 03:31 UTC, gongweibao requested changes
Small needs fix!

2019-11-08 03:31 UTC, gongweibao commented on paddle/fluid/framework/details/sparse_all_reduce_op_handle.cc
> +    // auto tmp_ious_data = memory::Alloc(place, buf_size);
clean up these codes!

2019-11-08 03:48 UTC, wangxicoding commented on paddle/fluid/framework/details/sparse_all_reduce_op_handle.cc
> +    // auto tmp_ious_data = memory::Alloc(place, buf_size);
Done.

2019-11-12 09:54 UTC, gongweibao approved these changes
LGTM

2019-11-12 09:54 UTC, merged