support set model_filename and params_filename in post_training_quantization, test=develop
PaddlePaddle/Paddle pull request #21213
Opened 2019-11-18 01:43 UTC by juncaipeng

* support set model_filename and params_filename in post_training_quantization
* modify the inputs name

2019-11-18 07:41 UTC, wzzju requested changes

2019-11-18 07:41 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +                 model_params_path,
`model_params_path` --> `model_dir`或者`model_dirname`?

2019-11-18 07:41 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +            params_filename = None
`model_params_path`注意改一下。`model_filename `和`params_filename `可以注明默认是None，所以在此也可不设置。

2019-11-18 07:41 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +                        model_params_path=model_params_path,
`model_params_path `这里同样需要改一下。

2019-11-19 11:52 UTC, juncaipeng commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +            params_filename = None
Done

2019-11-19 11:52 UTC, juncaipeng commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +            params_filename = None
model_filename 和params_filename说明白，免得大家需要仔细查看文档，因为大部分模型的权重都是保存成一个文件。

2019-11-20 03:27 UTC, wzzju approved these changes
Mostly LGTM.

2019-11-20 03:27 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/post_training_quantization.py
> +            # sample generator must return a simple every time. The reference
`return a simple every time` --> `return one sample every time`

2019-11-20 04:15 UTC, merged