Enrich ConvShift to support sequence data input
PaddlePaddle/Paddle pull request #2133
Opened 2017-05-15 03:30 UTC by pkuyym

fixes #2132

2017-05-15 03:44 UTC, luotao1 requested changes
建议将修改逻辑放进matrix函数里面，现在修改的和原有matrix里的重复太多。代码可读性不好。

2017-05-15 04:53 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  }
将circularConvSeq函数挪到matrix.cpp里面，这个函数的接口应该类似circularConv。即
outV->circularConv(*inV0, *inV1, *seqstartposition);

这样200-207行，可以修改为
```
if (inLayer0.sequenceStartPositions !=nullptr) {
} else {
}
```
去掉isSeqType这个函数。

2017-05-15 05:04 UTC, luotao1 reviewed
添加[单测](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/test_LayerGrad.cpp#L905)

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +    circularConvSeqDerivative();
这里修改同forward函数

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  for (size_t x = 0; x < numSeqs - 1; x++) {
for循环最后的x++统一改成++x，下同

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        int outVColOffset = i % width0;
113和114行只和i有关，应该放在109行的for循环里面，不要放在110行的for循环里面，这样会多算很多次。

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        index = (index + curSeqWidth) % curSeqWidth;
111行和112行可以写在一块。

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  CHECK_EQ(width0, outG->getWidth());
cheack_eq有点多，可以只保留143,148,149三行

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  real* inGV1 = inG1->getData();
命名的时候，GV都可以改成G，下同。

2017-05-15 05:04 UTC, luotao1 commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        int outGVColOffset = i % width0;
修改意见同forward

2017-05-15 07:40 UTC, lcy-seso requested changes
请先保证单测通过。

2017-05-15 07:40 UTC, lcy-seso commented on paddle/gserver/layers/ConvShiftLayer.cpp
22  ~ 42行的注释也需要对应地修改。

2017-05-15 07:40 UTC, lcy-seso commented on paddle/gserver/layers/ConvShiftLayer.cpp
> -bool ConvShiftLayer::isSeqType() {
请先加单测保证 test_layer_grad 一定可以通过。计算程序，硬看很难保证计算结果的正确。

2017-05-15 08:23 UTC, pkuyym commented
@luotao1 谢谢review，卷积逻辑已merge到matrix，现在ConvShift层应该比较清爽，对sequence和non-sequence的卷积逻辑已经并在一起

2017-05-16 07:49 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  }
done

2017-05-16 07:49 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  for (size_t x = 0; x < numSeqs - 1; x++) {
done

2017-05-16 07:49 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        index = (index + curSeqWidth) % curSeqWidth;
done

2017-05-16 07:50 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        int outVColOffset = i % width0;
done

2017-05-16 07:50 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  CHECK_EQ(width0, outG->getWidth());
这个check是必要的，梯度、输入等的维度必须严格一致

2017-05-16 07:51 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +  real* inGV1 = inG1->getData();
延伸了Matrix函数的命名方式，GV代表真实的矩阵，感觉比较合适

2017-05-16 07:51 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +        int outGVColOffset = i % width0;
done

2017-05-16 07:51 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> +    circularConvSeqDerivative();
done

2017-05-16 07:51 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
已经移到Matrix中

2017-05-17 03:22 UTC, pkuyym commented on paddle/gserver/layers/ConvShiftLayer.cpp
> -bool ConvShiftLayer::isSeqType() {
done

2017-05-23 08:59 UTC, luotao1 commented on paddle/gserver/tests/LayerGradUtil.cpp
> +        }
406-408行可以去掉，这里不会用prelu这个layer

2017-05-24 06:38 UTC, pkuyym commented on paddle/gserver/tests/LayerGradUtil.cpp
> +        }
done

2019-02-01 04:43 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:43 UTC, closed without merging