fix: fail to call ZeroCopyTensor::mutable_data() when device_id is no…
PaddlePaddle/Paddle pull request #21461
Opened 2019-11-29 11:12 UTC by rensilin

allocator may check faild, because devide 0 is not initialized.

Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)
[Hint: Expected pos < devices_.size(), but received pos:1 >= devices_.size():1.] at (baidu/paddlepaddle/paddle/paddle/fluid/memory/allocation/naive_best_fit_allocator.cc:128)

2019-12-02 12:09 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/paddle_api.h
> +
成员函数定义移动到 paddle/fluid/inference/api/details/zero_copy_tensor.cc 可以避免编译函数重复定义的问题

2019-12-02 12:10 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/paddle_api.h
> +    return mutable_data<T>(place(), device());
不建议修改这个函数

2019-12-04 07:11 UTC, NHZlX commented
这个看起来确实是个比较严重的bug

2019-12-04 12:38 UTC, rensilin commented
@Shixiaowei02 请问这个覆盖率问题怎么解决呢

2019-12-06 04:15 UTC, Shixiaowei02 requested changes
> @Shixiaowei02 请问这个覆盖率问题怎么解决呢

参见 #21581，我帮你做修改了

2019-12-06 04:15 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/paddle_api.h
>    PaddleDType type() const;
@NHZlX 一起看下这样改是否可以吧

2019-12-09 02:58 UTC, rensilin commented on paddle/fluid/inference/api/paddle_api.h
>    PaddleDType type() const;
也可以不用加，由用户在框架外自行维护

2019-12-10 08:34 UTC, Shixiaowei02 approved these changes

2019-12-10 08:34 UTC, merged