add CI check for OperatorBase. test=develop
PaddlePaddle/Paddle pull request #21549
Opened 2019-12-04 10:28 UTC by jiweibo

为支持动态图，所有op不建议在继承OperatorBase，需要继承OperatorWithKernel，为此，添加CI增量监控

2019-12-04 12:26 UTC, Shixiaowei02 approved these changes

2019-12-04 12:28 UTC, Shixiaowei02 requested changes
请问 #21531 提交和这个的联系是什么，CI 没有通过

2019-12-04 12:31 UTC, jiweibo commented
> 请问 #21531 提交和这个的联系是什么，CI 没有通过

制造了一个例子，op继承了OperatorBase，然后check_api_approvals.sh检测出了这个问题，报错

起到一个验证作用！此pr合入后 关掉那个pr

2019-12-04 12:41 UTC, Shixiaowei02 commented
> > 请问 #21531 提交和这个的联系是什么，CI 没有通过
> 
> 制造了一个例子，op继承了OperatorBase，然后check_api_approvals.sh检测出了这个问题，报错
> 
> 起到一个验证作用！此pr合入后 关掉那个pr

好的，知道了

2019-12-04 12:41 UTC, Shixiaowei02 submitted a review, later dismissed

2019-12-04 14:24 UTC, luotao1 commented on tools/check_api_approvals.sh
> +    echo_line="Inherit OperatorBase is not recommended. Please use OperatorWithKernel instead.\nYou must have one RD (luotao1, XiaoguangHu01, lanxianghit or phlrain) approval for the usage (either ad
1. 目前的错误截图并没有报出具体的行，希望报出具体的行（可以参考其他CI监控的PR），如。
```
class SelectOutputForTestOp : public framework::OperatorBase
```
2. Inherit OperatorBase is not recommended. Please use OperatorWithKernel instead. 这句说明太简单了，需要说一下为什么不推荐，也就是“为支持动态图，所有op不建议继承OperatorBase，需要继承OperatorWithKernel。”
3. approval for the usage (either add or delete) of OperatorBase
- 删OperatorBase会有问题么？
- 并不是用了OperatorBase就会报错，是继承了才会报错，
  approval for the inherit of OperatorBase?

2019-12-04 14:24 UTC, luotao1 commented
请使用`test=develop test=document_fix`来节省CI时间

2019-12-05 01:57 UTC, luotao1 commented on tools/check_api_approvals.sh
> +    echo_line="Inherit OperatorBase is not recommended. Please use OperatorWithKernel instead.\nYou must have one RD (luotao1, XiaoguangHu01, lanxianghit or phlrain) approval for the usage (either ad
因为和动态图相关，所以审核人顺序调整为
(phlrain (Recommend), luotao1, lanxianghit or XiaoguangHu01)

2019-12-05 03:33 UTC, jiweibo commented on tools/check_api_approvals.sh
> +    echo_line="Inherit OperatorBase is not recommended. Please use OperatorWithKernel instead.\nYou must have one RD (luotao1, XiaoguangHu01, lanxianghit or phlrain) approval for the usage (either ad
已按照要求修改

2019-12-05 04:03 UTC, luotao1 commented on tools/check_api_approvals.sh
> +    echo_line="In order to support dynamic graph, all ops are not recommedned to inherit OperatorBase. Please use OperatorWithKernel instead.\nYou must have one RD (phlrain (Recommend), luotao1, lanx
1. ${HAS_OPERATORBASE_FLAG}这个前面要说一下：出现的错误如下，不然直接出现错误，估计大家会懵。
2. 行号能否不显示？

2019-12-05 13:51 UTC, jiweibo commented on tools/check_api_approvals.sh
> +    echo_line="In order to support dynamic graph, all ops are not recommedned to inherit OperatorBase. Please use OperatorWithKernel instead.\nYou must have one RD (phlrain (Recommend), luotao1, lanx
已按照要求修改，感谢建议！

感谢 https://github.com/PaddlePaddle/Paddle/pull/21528 提供换行支持

2019-12-06 02:51 UTC, luotao1 approved these changes
LGTM! Thanks very much!

2019-12-06 04:48 UTC, merged