support elu_op double grad
PaddlePaddle/Paddle pull request #21822
Opened 2019-12-18 12:45 UTC by LDOUBLEV

as title, add double grad to elu activation function

2019-12-27 06:01 UTC, heavengate commented on paddle/fluid/operators/activation_op.cu
> +
/* ========================================================================== */  加下

2019-12-27 06:10 UTC, LDOUBLEV commented on paddle/fluid/operators/activation_op.cu
> +
好的

2019-12-29 11:54 UTC, ceci3 reviewed
LGTM

2019-12-30 04:15 UTC, heavengate approved these changes

2019-12-31 04:16 UTC, qingqing01 approved these changes

2019-12-31 04:20 UTC, qingqing01 requested changes

2019-12-31 04:20 UTC, qingqing01 commented on paddle/fluid/operators/activation_op.h
> +    functor(place, X, ddX, ddOut, dOut, dX);
“ELUDoubleGradKernel”只能用于ELU，核心计算没必要写成ELUGradGradFunctor，直接展开即可。

2019-12-31 06:05 UTC, LDOUBLEV commented on paddle/fluid/operators/activation_op.h
> +    functor(place, X, ddX, ddOut, dOut, dX);
这里主要是和SquareGradGradFunctor，SqrtGradGradFunctor保持一致了，也是可以把ELUGradGradFunctor写到ELUDoubleGradKernel里的

2020-01-06 02:08 UTC, qingqing01 approved these changes

2020-01-06 12:27 UTC, merged