remove the useless third_party library from C++ inference library
PaddlePaddle/Paddle pull request #22021
Opened 2019-12-30 15:09 UTC by silingtong123

1. remove the useless third_party library from C++ inference library, such as: xxhash, zlib, eigen3, boost, dlpack, protobuf
2. remove the useless third_party library ofprotobuf  from C++ inference library,

2020-01-06 06:15 UTC, liupluswei submitted a review, later dismissed
LGTM

2020-01-06 06:39 UTC, luotao1 requested changes
去掉install目录的话，会使得所有使用预测库和train_demo的用户更新他们的cmake文件，改动量非常大。

2020-01-06 06:53 UTC, luotao1 reviewed
@fc500110 
- 请review `demo_ci/CMakeLists.txt`
- 移除不必要的第三方库，是有必要的。但将`install`目录去掉，觉得没有必要
- 以后`demo_ci/CMakeLists.txt`发生变化，是否需要你approve呢？

@mapingshuo @guru4elephant 
- 请review `imdb_demo/CMakeLists.txt`
- 将`install`目录去掉，觉得没有必要。
- 以后`imdb_demo/CMakeLists.txt`改动，是否需要 @mapingshuo @guru4elephant approve呢？

2020-01-06 07:03 UTC, liuwei1031 commented
因为移除非必要的第三方库已经会造成用户改动了，所以我是想顺带把目录整理干净一些，所以提出了移除install 目录这个事情。   install目录是否保留这个事，如果反对意见比较多，我也不坚持。 

但是我提出一个问题，如果不好的设计始终因为兼容性的考虑不敢修改，那么越往后拖，以后想改就更难改了

2020-01-06 07:16 UTC, luotao1 commented
> 如果不好的设计始终因为兼容性的考虑不敢修改，那么越往后拖，以后想改就更难改了

同意。请 @fc500110 @guru4elephant 评估下移除`install`目录的风险。

2020-01-06 08:56 UTC, silingtong123 commented
> 去掉install目录的话，会使得所有使用预测库和train_demo的用户更新他们的cmake文件，改动量非常大。

移除三方库时，就会使所有使用预测库和train_demo的用户更新他们的cmake文件,所以后面install的修改可以和前面让用户一起更新cmake文件

2020-01-07 09:28 UTC, guru4elephant commented
清理install目录没有问题，对应的demo示例可以做修改。是否有方法评估对在线任务的影响面有多大，离线使用的体验伤害不算大。@luotao1

2020-01-07 13:56 UTC, luotao1 commented
> 是否有方法评估对在线任务的影响面有多大

在线部署任务请 @Superjomn @fc500110 @cyj1986 评估下？

2020-01-08 03:42 UTC, silingtong123 commented
根据@fc500110的意见，已取消移除install目录

2020-01-13 11:17 UTC, fc500110 reviewed
我这边没什么问题了

2020-01-13 11:24 UTC, luotao1 approved these changes

2020-01-13 11:26 UTC, luotao1 approved these changes

2020-01-14 08:55 UTC, merged