Implement InterencePassTest for testing precision of inference passes
PaddlePaddle/Paddle pull request #22387
Opened 2020-01-21 09:23 UTC by FrostML

* #22209 提供了一种普适性的用于passes正确性检测的单测框架。
经过 on-line/off-line 讨论以及验证，采用executor.run()的方式 因为没有提供接口对TensorRT或是Lite子图的相关参数进行设置，所以不能完成对TensorRT的passes的验证。
另外，我们希望确保目前预测中不同passes相互关联的特性，保证无论是单个pass还是多个passes作用于同一个pattern，都能得出正确的精度。
因此提出此PR，采用predictor进行结果验证，使用`AnalysisConfig`默认的`PassStrategy`策略。
采用Python的原因：方便搭建相应的模型从而验证passes。
* 具体的实现部分，参考了#22209 ：
  * 使用`setUp(self)`完成对每个pass单测的设置，需要提供，`self.main_program`、`self.startup_program`完成对需要验证的pass结构的搭建，另外需要提供输入的字典`self.feeds`，以及输出的`var`的列表`self.fetch_list`。最后，需要指明，是否是使用TensorRT（`self.enable_trt`）或是MKLDNN（`self.enable_mkldnn`），Lite子图因为尚无Python API的缘故，没有启用。
  * 使用`check_output()`完成对所有支持的place上进行验证（目前只包括CPU和GPU）。
  * 使用`check_output_with_option()`来针对是否使用TensorRT、MKLDNN的结果进行验证。
  * 以上的验证的范围包括，最后的结果是否在精度diff可以忍受的范围之内（`1e-05`）、得出的结果的个数是否是相同的。
* 比对的方式包括：
 | 基准 | Pass的结果 |
 |---|---|
 | CPU计算的训练前向 | CPU的计算结果 |
 | GPU计算的训练前向 | GPU的计算结果 |
 | GPU计算的训练前向 | 使用TRT子图计算结果 |
 | CPU计算的训练前向 | 应用MKLDNN的计算结果 |

2020-02-07 01:48 UTC, fc500110 requested changes
请回复代码中的comment

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +    def setUpClass(self):
类方法的第一个参数命名用cls

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            tensor.copy_from_cpu(list(self.feeds.values())[i])
``` python
for i, name in enumerate(names):
    shape = tensor_shapes[name]
    shape[0] = 1
    tensor = predictor.get_input_tensor(name)
    tensor.copy_from_cpu(list(self.feeds.values())[i])
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            outs.append(output_tensor.copy_to_cpu())
用列表推导式
``` python
outs = [predictor.get_output_tensor(name).copy_from_cpu() for name in output_names]
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            self.assertTrue(False, "The inputs of the model is None. ")
``` python
self.assertFalse(self.feeds is None, "The inputs of the model is None. ")
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            self.check_output_with_option(use_gpu[i], atol)
``` python
for _ in use_gpu:
  self.check_output_with_option(_, atol)
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                format(place))
``` python
for o, ao in zip(outs, analysis_outputs):
  self.assertTrue(np.allclose(o, ao, atol=atol), "...")
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                    "Output has diff between GPU and TensorRT. ")
同上，改为用zip

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +        return use_gpu
``` python
return [False, core.is_compiled_with_cuda()]
```

2020-02-07 01:48 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                    "Output has diff between CPU and MKLDNN. ")
同上，改为用zip

2020-02-07 02:26 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +    def setUpClass(self):
Done. Thanks.

2020-02-07 02:28 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            tensor.copy_from_cpu(list(self.feeds.values())[i])
Done. Thanks.

2020-02-07 02:28 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            outs.append(output_tensor.copy_to_cpu())
Done. Thanks.

2020-02-07 02:31 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                    "Output has diff between CPU and MKLDNN. ")
Done. Thanks.

2020-02-07 02:31 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +        return use_gpu
修改成
``` python
return list(set([False, core.is_compiled_with_cuda()]))
```
确保可以去重。

2020-02-07 02:31 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                    "Output has diff between GPU and TensorRT. ")
Done. Thanks.

2020-02-07 02:31 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                format(place))
Done. Thanks.

2020-02-07 02:31 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            self.check_output_with_option(use_gpu[i], atol)
Done. Thanks.

2020-02-07 02:32 UTC, FrostML commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +            self.assertTrue(False, "The inputs of the model is None. ")
Done. Thanks.

2020-02-10 09:25 UTC, fc500110 approved these changes
LGTM

2020-02-10 09:26 UTC, merged