add WITH_NCCL option for cmake.
PaddlePaddle/Paddle pull request #22384
Opened 2020-01-21 02:02 UTC by jiweibo

1. cmake选项中添加了WITH_NCCL，显示指定是否单机
2. 添加了PADDLE_WITH_NCCL定义
3. 修改了部分代码文件，使得关闭NCCL的时候，编译通过

2020-01-21 03:29 UTC, Shixiaowei02 reviewed
TODO: 后续预测库编译时不再提供 NCCL 依赖，目前 NCCL 默认打开应该是暂时的

2020-01-21 03:29 UTC, Shixiaowei02 commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +#if defined(PADDLE_WITH_CUDA) && !defined(_WIN32) && defined(PADDLE_WITH_NCCL)
请问是否合并一下逻辑。比如 PADDLE_WITH_NCCL 的前提一定是 PADDLE_WITH_CUDA 打开；PADDLE_WITH_CUDA 和 PADDLE_WITH_NCCL 的处理可以移到 cmake 中判断。

2020-01-21 07:33 UTC, jiweibo commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
> +#if defined(PADDLE_WITH_CUDA) && !defined(_WIN32) && defined(PADDLE_WITH_NCCL)
done

2020-01-21 09:29 UTC, Shixiaowei02 submitted a review, later dismissed

2020-02-03 01:29 UTC, luotao1 submitted a review, later dismissed

2020-02-03 01:36 UTC, luotao1 commented on CMakeLists.txt
> +  add_definitions("-DPADDLE_WITH_NCCL")
```
if(NOT WITH_GPU)
 set(WITH_NCCL OFF)
endif()
```
CPU情况下有默认关闭NCCL么？

2020-02-03 01:36 UTC, luotao1 commented on paddle/fluid/operators/collective/CMakeLists.txt
> +if(WITH_GPU AND NOT WIN32 AND WITH_NCCL)
这里简化成`if(WITH_NCCL)`?

2020-02-03 01:36 UTC, luotao1 commented on paddle/fluid/operators/distributed_ops/CMakeLists.txt
> +if(WITH_GPU AND NOT WIN32 AND WITH_NCCL)
这里简化成`if(WITH_NCCL)`?

2020-02-03 01:39 UTC, jiweibo commented on CMakeLists.txt
> +  add_definitions("-DPADDLE_WITH_NCCL")
目前nccl与代码耦合比较严重，直接设置nccl为off在mac下编译不过，还需要添加nccl的同学来帮忙处理

2020-02-03 01:40 UTC, jiweibo commented on paddle/fluid/operators/collective/CMakeLists.txt
> +if(WITH_GPU AND NOT WIN32 AND WITH_NCCL)
收到，下次修改的时候处理

2020-02-03 01:46 UTC, luotao1 commented on CMakeLists.txt
> +  add_definitions("-DPADDLE_WITH_NCCL")
mac下没有gpu，理论上应该是要能编译通过的。

2020-02-03 02:00 UTC, jiweibo commented on CMakeLists.txt
> +  add_definitions("-DPADDLE_WITH_NCCL")
收到，我在mac本机上测试下编译

2020-02-03 08:46 UTC, jiweibo commented on paddle/fluid/operators/distributed_ops/CMakeLists.txt
> +if(WITH_GPU AND NOT WIN32 AND WITH_NCCL)
done

2020-02-03 08:47 UTC, jiweibo commented on paddle/fluid/operators/collective/CMakeLists.txt
> +if(WITH_GPU AND NOT WIN32 AND WITH_NCCL)
done

2020-02-03 08:47 UTC, jiweibo commented on CMakeLists.txt
> +  add_definitions("-DPADDLE_WITH_NCCL")
WITH_NCCL默认打开，但cpu情况下关闭WITH_NCCL。

2020-02-03 10:05 UTC, Shixiaowei02 submitted a review, later dismissed

2020-02-04 04:20 UTC, luotao1 submitted a review, later dismissed

2020-02-04 08:19 UTC, raindrops2sea requested changes

2020-02-04 08:19 UTC, raindrops2sea commented on CMakeLists.txt
> +            "Disable NCCL when compiling for WINDOWS" FORCE)
Windows？

2020-02-04 08:19 UTC, raindrops2sea commented on paddle/fluid/framework/details/all_reduce_op_handle.h
> +#if !(defined(PADDLE_WITH_CUDA) && !defined(_WIN32) && \
redundant？

2020-02-04 08:29 UTC, raindrops2sea commented
> 1. cmake选项中添加了WITH_NCCL，显示指定是否编译NCCL的部分代码，WITH_NCCL默认打开，但如果WITH_GPU为OFF，则关闭WITH_NCCL
> 2. 添加了PADDLE_WITH_NCCL定义
> 3. 修改了部分代码文件，使得关闭NCCL的时候，编译通过
对第三条细化一下带来收益的具体场景，以及误操作时的影响。

2020-02-04 08:35 UTC, raindrops2sea commented
> TODO: 后续预测库编译时不再提供 NCCL 依赖，目前 NCCL 默认打开应该是暂时的
预测库编译时不再提供 NCCL 依赖需要排期来实施了。

2020-02-04 09:07 UTC, jiweibo commented on CMakeLists.txt
> +            "Disable NCCL when compiling for WINDOWS" FORCE)
done

2020-02-04 09:07 UTC, jiweibo commented on paddle/fluid/framework/details/all_reduce_op_handle.h
> +#if !(defined(PADDLE_WITH_CUDA) && !defined(_WIN32) && \
done

2020-02-05 02:54 UTC, luotao1 approved these changes

2020-02-05 02:54 UTC, Shixiaowei02 approved these changes

2020-02-05 05:46 UTC, raindrops2sea approved these changes

2020-02-05 06:01 UTC, merged