unify operator behavior with element op, test=develop
PaddlePaddle/Paddle pull request #23051
Opened 2020-03-17 07:23 UTC by kinghuin

In paddle 1.x, operator behavior is different with elementwise op. For example

```python
import paddle.fluid as fluid
import numpy as np
x = fluid.data(name="x", shape=[20, 10, 10], dtype='float32')
y = fluid.data(name="y", shape=[-1, 10], dtype='float32')
c = fluid.layers.elementwise_add( x, y )
d = x + y
place = fluid.CPUPlace()
exe = fluid.Executor(place)
x_np = np.random.uniform( -1, 1, [20, 10, 10]).astype("float32")
y_np = np.random.uniform( -1, 1, [1, 10]).astype("float32")
out = exe.run(feed={ "x" : x_np , "y" : y_np }, fetch_list=[ c, d] )
print( np.array_equal( out[0], out[1])) ## result is False
```

In this PR, they are unified. Some warning log will be print to  prompt Paddle 1.x users

2020-03-17 07:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23051) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23051) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=23051) it.</sub>

2020-03-18 03:40 UTC, lanxianghit requested changes

2020-03-18 03:40 UTC, lanxianghit commented on python/paddle/fluid/layers/math_op_patch.py
> +                    % (EXPRESSION_MAP[method_name], op_type, op_type,
这里的warning信息不合理，这个pr已经统一了elementwise_add和“+”的行为，那么如果用户代码在新版本上有问题，从“+”改成使用elementwise_add并不会有任何变化，解决不了问题。

2020-03-18 03:40 UTC, lanxianghit commented on python/paddle/fluid/layers/math_op_patch.py
> +                       EXPRESSION_MAP[method_name]))
“+”行为修改之前已经做过一次，但是merge中引起了一些问题，有模型跑不通或者不收敛的情况，所以本次该pr在merge之前需要先做好验证，比如在CE和benchmark上都验证通过

2020-03-19 07:19 UTC, kinghuin commented on python/paddle/fluid/layers/math_op_patch.py
> +                    % (EXPRESSION_MAP[method_name], op_type, op_type,
warning中建议改成elementwise_add(..., axis=0)，这里axis=0就能和之前的+的行为是一致的了

2020-03-19 07:20 UTC, kinghuin commented on python/paddle/fluid/layers/math_op_patch.py
> +                       EXPRESSION_MAP[method_name]))
好的~正在联系相关负责人

2020-04-16 06:52 UTC, closed without merging