[Paddle-TRT]: Ernie Dynamic shape support.
PaddlePaddle/Paddle pull request #23138
Opened 2020-03-22 06:37 UTC by NHZlX

```
std::map<std::string, std::vector<int>> min_input_shape 
             = {{"read_file_0.tmp_0", {1,128,1}}, {"read_file_0.tmp_1", {1,128,1}}, {"read_file_0.tmp_2", {1,128,1}}, {"stack_0.tmp_0", {1,12, 128, 128}}};
  std::map<std::string, std::vector<int>> max_input_shape 
             = {{"read_file_0.tmp_0", {1,128,1}}, {"read_file_0.tmp_1", {1,128,1}}, {"read_file_0.tmp_2", {1,128,1}},{"stack_0.tmp_0", {1,12, 128, 128}}};
  std::map<std::string, std::vector<int>> opt_input_shape  
             = {{"read_file_0.tmp_0", {1,128,1}}, {"read_file_0.tmp_1", {1,128,1}}, {"read_file_0.tmp_2", {1,128,1}},{"stack_0.tmp_0", {1,12, 128, 128}}};

  config.EnableTensorRtEngine(1 << 20, 1, 5, 
      AnalysisConfig::Precision::kFloat32, false, true, min_input_shape,
       max_input_shape, opt_input_shape);

```

2020-03-24 05:16 UTC, Superjomn requested changes

2020-03-24 05:16 UTC, Superjomn commented on paddle/fluid/inference/analysis/argument.h
> +  DECL_ARGUMENT_FIELD(close_trt_plugin_fp16, CloseTrtPluginFp16, bool);
这里4个字段都加下注释描述吧，是只有 trt 用吗

2020-03-24 05:16 UTC, Superjomn commented on paddle/fluid/inference/analysis/ir_pass_manager.cc
> +      pass->Set("close_trt_plugin_fp16",
加下描述

2020-03-24 05:16 UTC, Superjomn commented on paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
> +  // When set close_trt_plugin_fp16 to true, the plugin
这里看不太懂，再描述一些

2020-03-24 05:16 UTC, Superjomn commented on paddle/fluid/inference/api/paddle_analysis_config.h
> +   *  #param close_trt_plugin_fp16, setting this variable to true
# -> @ ?

2020-03-24 08:16 UTC, NHZlX commented on paddle/fluid/inference/api/paddle_analysis_config.h
> +   *  #param close_trt_plugin_fp16, setting this variable to true
done

2020-03-24 08:16 UTC, NHZlX commented on paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
> +  // When set close_trt_plugin_fp16 to true, the plugin
done!

2020-03-24 08:16 UTC, NHZlX commented on paddle/fluid/inference/analysis/argument.h
> +  DECL_ARGUMENT_FIELD(close_trt_plugin_fp16, CloseTrtPluginFp16, bool);
done!

2020-03-25 06:31 UTC, Shixiaowei02 submitted a review, later dismissed

2020-03-25 06:31 UTC, Shixiaowei02 commented on cmake/cuda.cmake
> +    add_definitions("-DSUPPORT_CUDA_FP16")
建议改成 SUPPORTS_CUDA_FP16 或者 CUDA_FP16_SUPPORTED

2020-03-25 06:31 UTC, Shixiaowei02 commented on paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
> +  bool close_trt_plugin_fp16 = Get<bool>("close_trt_plugin_fp16");
用 disable 还是 close 好一些

2020-03-25 06:31 UTC, Shixiaowei02 commented on paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
> +                         const float *input, float *output,
如果此处传 void*，是否下面的 reinterpret_cast 可以变成 static_cast

2020-03-25 09:30 UTC, NHZlX commented on paddle/fluid/inference/tensorrt/plugin/qkv_to_context_plugin.cu
> +                         const float *input, float *output,
有half 的时候trt_emb_elt_layernorm 貌似避免不了

2020-03-25 09:30 UTC, NHZlX commented on paddle/fluid/inference/analysis/ir_passes/tensorrt_subgraph_pass.cc
> +  bool close_trt_plugin_fp16 = Get<bool>("close_trt_plugin_fp16");
done！

2020-03-25 09:30 UTC, NHZlX commented on cmake/cuda.cmake
> +    add_definitions("-DSUPPORT_CUDA_FP16")
Done！

2020-03-25 09:34 UTC, NHZlX commented on paddle/fluid/inference/analysis/ir_pass_manager.cc
> +      pass->Set("close_trt_plugin_fp16",
done

2020-03-25 09:45 UTC, Shixiaowei02 approved these changes

2020-03-26 07:34 UTC, XiaoguangHu01 approved these changes

2020-03-26 09:33 UTC, raindrops2sea approved these changes
LGTM

2020-03-26 12:44 UTC, Superjomn approved these changes

2020-03-26 13:04 UTC, merged