Add three PASS tests.
PaddlePaddle/Paddle pull request #23170
Opened 2020-03-23 14:45 UTC by haozech

This commit add threes pass tests: conv_elementwise_add, conv_elementwise_add_act and conv_elementwise_add2_act. Also it standardize the supported patterns of former two fusions. Pattern of [conv2d(bias_attr = False) + elementwise_add] is not supported.

2020-03-23 14:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23170) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: chenhaoze<br/>:x: haozech<br/><hr/>**chenhaoze** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=23170) it.</sub>

2020-03-23 14:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=23170) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: chenhaoze<br/>:x: haozech<br/><hr/>**chenhaoze** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=23170) it.</sub>

2020-03-24 11:13 UTC, fc500110 submitted a review, later dismissed
LGTM

2020-03-26 02:04 UTC, fc500110 requested changes

2020-03-26 02:04 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// \param[out] passes_ list of the passes.
这个不是param[out]，应该是\return

2020-03-26 02:04 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// \param[out] passes_ list of the passes.
param[out]是指指针和非const引用

2020-03-26 02:04 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +  std::vector<std::string> passes_;///< the list of passes
protected不需要doxygen注释

2020-03-26 02:04 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// \brief Constructor of the class. It stores the input passes.
缩进有问题

2020-03-26 02:04 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +  std::string DebugString(); ///< Human-readable information of the passes.
这种注释方式仅用于枚举

2020-03-27 06:19 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// \brief Constructor of the class. It stores the input passes.
> 缩进有问题

已修改，感谢！

2020-03-27 06:21 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +  std::vector<std::string> passes_;///< the list of passes
好的，已修改

2020-03-27 06:21 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +  std::vector<std::string> passes_;///< the list of passes
> protected不需要doxygen注释

好的，已修改

2020-03-27 06:22 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +  std::string DebugString(); ///< Human-readable information of the passes.
> 这种注释方式仅用于枚举

了解，已修改

2020-03-27 06:22 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// \param[out] passes_ list of the passes.
> param[out]是指指针和非const引用

了解，已修改。感谢！

2020-03-27 07:52 UTC, fc500110 requested changes

2020-03-27 07:52 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +
多余的空行

2020-03-27 10:42 UTC, haozech commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +
已修改，感谢！

2020-04-01 03:12 UTC, fc500110 submitted a review, later dismissed
LGTM

2020-04-01 03:12 UTC, fc500110 commented on paddle/fluid/inference/api/paddle_pass_builder.h
> +/// Build a new pass.
这儿可以多缩进四个空格

2020-04-01 07:48 UTC, closed without merging