add linear interpolate operator
PaddlePaddle/Paddle pull request #23357
Opened 2020-03-31 13:45 UTC by FDInSky

add linear interpolate operator

2020-04-16 11:30 UTC, tink2123 commented on paddle/fluid/operators/interpolate_op.cc
>                     "Input(X) dimension must be 4 or 5");
must be 3 4 or 5

2020-04-16 11:30 UTC, tink2123 commented on paddle/fluid/operators/interpolate_op.cc
>            Nearest neighbor interpolation is to perform nearest neighbor interpolation
加相应mode说明

2020-04-16 11:30 UTC, tink2123 commented on python/paddle/fluid/layers/nn.py
> +    'resize_linear',
要不要加在2.0里呢？

2020-04-21 10:20 UTC, FDInSky commented on paddle/fluid/operators/interpolate_op.cc
>                     "Input(X) dimension must be 4 or 5");
修改了

2020-04-21 10:20 UTC, FDInSky commented on paddle/fluid/operators/interpolate_op.cc
>            Nearest neighbor interpolation is to perform nearest neighbor interpolation
修改了

2020-04-24 04:53 UTC, FDInSky commented on paddle/fluid/operators/interpolate_op.cc
>            Nearest neighbor interpolation is to perform nearest neighbor interpolation
加在2.0啦

2020-04-24 05:11 UTC, FDInSky commented on python/paddle/fluid/layers/nn.py
> +    'resize_linear',
加在2.0啦

2020-04-26 04:13 UTC, tink2123 commented on python/paddle/fluid/tests/unittests/test_linear_interp_op.py
> +
添加一下调用 Upsample 和 interpolate API的单测吧

2020-04-26 04:19 UTC, tink2123 commented on python/paddle/fluid/tests/unittests/test_linear_interp_op.py
> +        self.check_output(atol=1e-5)
atol=1e-5 是不是太大了？

2020-04-26 04:24 UTC, FDInSky commented on python/paddle/fluid/tests/unittests/test_linear_interp_op.py
> +        self.check_output(atol=1e-5)
linux下1e-7可以，但win、mac下不行

2020-04-27 08:12 UTC, FDInSky commented on python/paddle/fluid/tests/unittests/test_linear_interp_op.py
> +
这个在UpSample里统一测试了

2020-04-29 03:05 UTC, qingqing01 submitted a review, later dismissed

2020-04-29 13:04 UTC, Boyan-Liu submitted a review, later dismissed

2020-04-30 05:20 UTC, XiaoguangHu01 submitted a review, later dismissed
LG API

2020-04-30 07:32 UTC, raindrops2sea submitted a review, later dismissed

2020-05-09 03:50 UTC, chenwhql submitted a review, later dismissed
时间关系先approve，但代码中大部分报错检查都只是说了必须是什么值，而没有提示用户实际输入的是什么值，这样调试体验可能不太好，麻烦记个TODO，之后完善下该PR涉及文件的报错信息

2020-05-11 02:27 UTC, chenwhql approved these changes
LGTM for error message

2020-05-11 02:42 UTC, Xreki commented
LGTM for me. mac和win上面精度阈值从`1e-7`调到了`1e-5`，linux精度还是默认值，但请@lanxianghit 来确认下。

2020-05-11 02:51 UTC, chenwhql requested changes
![image](https://user-images.githubusercontent.com/22561442/81519854-23d77180-9375-11ea-97f6-57be0839f215.png)

CI又出现了不应该被通过的报错不合规现象，请修改

2020-05-11 06:18 UTC, chenwhql submitted a review, later dismissed
LGTM for error message

2020-05-11 06:28 UTC, lanxianghit requested changes

2020-05-11 06:28 UTC, lanxianghit commented on python/paddle/fluid/layers/nn.py
>      if resample not in resample_methods:
对于用户输入的resample，应该能兼容各种大小写问题，比如LINEAR，linear，Linear等，建议这里先对该值做lowercase处理

2020-05-11 06:28 UTC, lanxianghit commented on python/paddle/nn/layer/common.py
> +                 actual_shape=None,
新增API为什么还要保留actual_shape这个待废弃参数？后续再废弃会引起不兼容

2020-05-11 06:28 UTC, lanxianghit commented on python/paddle/nn/layer/common.py
> +                 data_format='NCHW'):
这个API的所有参数名、顺序、默认值，请再与 @XiaoguangHu01 仔细确认一下

2020-05-12 02:33 UTC, FDInSky commented on python/paddle/nn/layer/common.py
> +                 actual_shape=None,
修改了

2020-05-12 02:33 UTC, FDInSky commented on python/paddle/fluid/layers/nn.py
>      if resample not in resample_methods:
修改了

2020-05-12 02:34 UTC, FDInSky commented on python/paddle/nn/layer/common.py
> +                 data_format='NCHW'):
统一提一个PR，修改interpolate，UpSample两个api及对应的单测、文档。

2020-05-12 06:15 UTC, lanxianghit approved these changes
approve for precision threshold changing on Mac & Windows

2020-05-12 06:53 UTC, Boyan-Liu approved these changes

2020-05-12 07:00 UTC, raindrops2sea approved these changes

2020-05-12 08:31 UTC, raindrops2sea approved these changes

2020-05-12 09:01 UTC, merged