API (BuildStrategy) error message enhancement.
PaddlePaddle/Paddle pull request #23462
Opened 2020-04-03 12:01 UTC by liym27

2020-04-04 01:31 UTC, Aurelius84 commented on paddle/fluid/framework/details/build_strategy.cc
> +            "But received strategy_.trainer_id_ = %d.",
这里的逗号要改为句点，或者`But`改为`but`

2020-04-04 01:31 UTC, Aurelius84 commented on paddle/fluid/framework/details/build_strategy.cc
> +              "But received strategy_.trainer_id_ = %d, "
同上

2020-04-04 15:48 UTC, liym27 commented on paddle/fluid/framework/details/build_strategy.cc
> +            "But received strategy_.trainer_id_ = %d.",
谢谢。Done

2020-04-04 15:48 UTC, liym27 commented on paddle/fluid/framework/details/build_strategy.cc
> +              "But received strategy_.trainer_id_ = %d, "
Done

2020-04-06 01:48 UTC, Aurelius84 submitted a review, later dismissed

2020-04-08 13:18 UTC, zhhsplendid commented on paddle/fluid/framework/details/build_strategy.cc
> +            "But received strategy_.trainer_id_ = %d.",
事实上英语的话，But改为but是更常见的正解。但是已经这样了，我虽然approve下，但有空还是改一下。。。

2020-04-08 13:22 UTC, zhhsplendid commented on paddle/fluid/framework/details/build_strategy.cc
> +              "But received strategy_.trainer_id_ = %d, "
同上

2020-04-08 13:22 UTC, zhhsplendid approved these changes
LGTM

2020-04-08 13:23 UTC, zhhsplendid requested changes
un-LGTM, please see my comment under Liujie's comment. Tell me if you don't like to change then I will approve

2020-04-09 02:33 UTC, liym27 commented on paddle/fluid/framework/details/build_strategy.cc
> +            "But received strategy_.trainer_id_ = %d.",
已修改

2020-04-09 02:33 UTC, liym27 commented on paddle/fluid/framework/details/build_strategy.cc
> +              "But received strategy_.trainer_id_ = %d, "
Done

2020-04-10 03:22 UTC, liym27 commented
> un-LGTM, please see my comment under Liujie's comment. Tell me if you don't like to change then I will approve

Thanks. Done

2020-04-10 03:49 UTC, zhhsplendid approved these changes
LGTM

2020-04-10 03:51 UTC, Aurelius84 approved these changes

2020-04-10 03:52 UTC, merged