Mix precision3
PaddlePaddle/Paddle pull request #23551
Opened 2020-04-07 09:03 UTC by mapingshuo

Recompute和mix_precision混合使用时，会有两个错误，本PR修复了两个错误：添加了一个接口，修改了一个接口。

2020-04-09 09:45 UTC, gongweibao requested changes
Some small problems.

2020-04-09 09:45 UTC, gongweibao commented on python/paddle/fluid/contrib/tests/test_fp16_utils.py
> +class MAPTest(unittest.TestCase):
MAP?

2020-04-09 09:45 UTC, gongweibao commented on python/paddle/fluid/incubate/fleet/collective/__init__.py
> +                self.raiseOptimizeError("forward_recompute",
More error info is needed.

2020-04-09 09:45 UTC, gongweibao commented on python/paddle/fluid/incubate/fleet/collective/__init__.py
> +        if self._use_amp:
More error info is needed.

2020-04-09 09:45 UTC, gongweibao commented on python/paddle/fluid/contrib/mixed_precision/fp16_utils.py
> +            print("append op")
Clean up?

2020-04-09 09:46 UTC, mapingshuo commented on python/paddle/fluid/contrib/tests/test_fp16_utils.py
> +class MAPTest(unittest.TestCase):
AMP，尽快会改

2020-04-09 09:49 UTC, mapingshuo commented on python/paddle/fluid/incubate/fleet/collective/__init__.py
> +                self.raiseOptimizeError("forward_recompute",
这里有更多报错：https://github.com/PaddlePaddle/Paddle/pull/23551/files/56ca7f02a4cf2fa3fd71d6283f48cf57034713c3#diff-ac77dbc570acc11d5622d9af814ef685R582

2020-04-09 09:49 UTC, mapingshuo commented on python/paddle/fluid/contrib/mixed_precision/fp16_utils.py
> +            print("append op")
尽快会删除

2020-04-09 09:50 UTC, mapingshuo commented on python/paddle/fluid/incubate/fleet/collective/__init__.py
> +        if self._use_amp:
这里有更多报错：https://github.com/PaddlePaddle/Paddle/pull/23551/files/56ca7f02a4cf2fa3fd71d6283f48cf57034713c3#diff-ac77dbc570acc11d5622d9af814ef685R582

2020-04-15 04:13 UTC, gongweibao approved these changes
LGTM

2020-04-15 08:53 UTC, sneaxiy approved these changes
LGTM for backward.py.

2020-04-15 09:12 UTC, merged