OP clip, merge_lod_tensor, convert/elementwise error message enhancement
PaddlePaddle/Paddle pull request #23742
Opened 2020-04-11 03:56 UTC by haozech

test=develop

2020-04-13 10:16 UTC, NHZlX commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +                          "check if the op_type is correct."));
打印下具体的type

2020-04-13 11:01 UTC, haozech commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +                          "check if the op_type is correct."));
已修改 感谢

2020-04-13 14:27 UTC, NHZlX submitted a review, later dismissed
LGTM to the eltwise convert err message.

2020-04-14 03:59 UTC, fc500110 requested changes

2020-04-14 03:59 UTC, fc500110 commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +            "only support"
空格

2020-04-14 03:59 UTC, fc500110 commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +                "support"
"support "

2020-04-14 04:39 UTC, haozech commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +            "only support"
已修改 感谢

2020-04-14 04:39 UTC, haozech commented on paddle/fluid/inference/tensorrt/convert/elementwise_op.cc
> +                "support"
Done. THX

2020-04-17 06:15 UTC, fc500110 approved these changes
LGTM

2020-04-17 06:15 UTC, merged