Update err message
PaddlePaddle/Paddle pull request #24422
Opened 2020-05-12 06:52 UTC by ceci3

update following op error message:
1. batch_norm
2. instance_norm
3. dropout

2020-05-12 07:21 UTC, wanghaoshuang requested changes

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cc
> +            "Input(MomentumTensor) size must be 1"
Input(MomentumTensor) ... 改成 
The input tensor MomentumTensor's size must be 1. But received: MomentumTensor's size = [%d]

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cc
> +                          "The Input X dimension size should be larger than 1."
‘Input’为什么要大写？
这么写是不是更合适？
The size of input X's dimensions should be larger than 1.

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +          "The size of dimension about variance must equal to 1."
dimension -》dimensions?

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +          "The size of dimension about variance must equal to 1."
dimension about variance?

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +          "But received: the shape of variance is [%s]"
应该先说dimensions' size = [%d]，然后再说dimensions是什么？另外dimensions和shape的定义是一样吧？都用dimensions是不是更合适？

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +                          "The Input dim size should be between 2 and 5"
dim不要用缩写

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +                          "But received: the dimension of Input is [%d]",
是不是把dimensions和dimension size弄错了？

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/batch_norm_op.cu
> +            "the size of dimension about scale is [%d]",
about?

2020-05-12 07:21 UTC, wanghaoshuang commented on paddle/fluid/operators/instance_norm_op.cu
> +                          "Channels([%d]). But received: "
尽量避免'括号'这种表达方式

2020-05-12 08:45 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cc
> +            "Input(MomentumTensor) size must be 1"
done,thanks

2020-05-12 08:45 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cc
> +                          "The Input X dimension size should be larger than 1."
done,thanks

2020-05-12 08:45 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cu
> +          "The size of dimension about variance must equal to 1."
done,thanks

2020-05-12 08:45 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cu
> +          "But received: the shape of variance is [%s]"
done,thanks

2020-05-12 08:46 UTC, ceci3 commented on paddle/fluid/operators/instance_norm_op.cu
> +                          "Channels([%d]). But received: "
done,thanks

2020-05-12 08:46 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cu
> +            "the size of dimension about scale is [%d]",
done,thanks

2020-05-12 08:46 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cu
> +                          "But received: the dimension of Input is [%d]",
done,thanks

2020-05-12 08:46 UTC, ceci3 commented on paddle/fluid/operators/batch_norm_op.cu
> +                          "The Input dim size should be between 2 and 5"
done,thanks

2020-05-13 02:01 UTC, wanghaoshuang approved these changes

2020-05-13 06:58 UTC, merged