update interpolate & upsample api
PaddlePaddle/Paddle pull request #24553
Opened 2020-05-14 08:28 UTC by FDInSky

update interpolate & upsample api

2020-05-15 05:55 UTC, tink2123 commented on python/paddle/nn/layer/common.py
> +        ValueError: data_format can only be 'NCW', 'NWC', 'NCHW', 'NHWC', 'NCDHW' or 'NDHWC'.
> A 3-D Tensor of the shape (num_batches, channels, out_w) or (num_batches, out_h, channels),
> data_format can only be 'NCW', 'NWC',
确认下支持数据类型

2020-05-18 02:37 UTC, FDInSky commented on python/paddle/nn/layer/common.py
> +        ValueError: data_format can only be 'NCW', 'NWC', 'NCHW', 'NHWC', 'NCDHW' or 'NDHWC'.
linear的模式是应用在维度为3的数据上

2020-05-18 06:37 UTC, lanxianghit requested changes

2020-05-18 06:37 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
> +        name(str|None): A name for this layer(optional). If set None, the layer
这个参数有统一解释，参见其他文档

2020-05-18 06:37 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
> -	:alias: paddle.nn.functional.interpolate,paddle.nn.functional.common.interpolate
为什么删除了alias定义？

2020-05-18 06:37 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
>                                 Default: True
检查一下各个参数默认值设置是否合理

2020-05-18 06:37 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
> +                            for src_idx = scale_factor*(dst_indx+0.5)-0.5 , can be \'1\' for
这个参数没有解释清楚

2020-05-18 07:10 UTC, FDInSky commented on python/paddle/nn/functional/common.py
> -	:alias: paddle.nn.functional.interpolate,paddle.nn.functional.common.interpolate
没有删，看下最后一个commit，里面是有的

2020-05-18 07:13 UTC, FDInSky commented on python/paddle/nn/functional/common.py
> +                            for src_idx = scale_factor*(dst_indx+0.5)-0.5 , can be \'1\' for
这个得结合者上面的文档来看，是新坐标生成的两种方式。

2020-05-18 07:14 UTC, FDInSky commented on python/paddle/nn/functional/common.py
>                                 Default: True
之前的默认值，是针对bilinear方式的resize；现在是跟pytorch对齐，采用neares方式的resize采用的默认值设置；

2020-05-18 09:18 UTC, FDInSky commented on python/paddle/nn/functional/common.py
> +        name(str|None): A name for this layer(optional). If set None, the layer
修改了

2020-05-19 06:47 UTC, lanxianghit requested changes

2020-05-19 06:47 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
> +            will be consistent with that of the input. An optional string from:'NCW', `"NCHW"`, `"NHWC"`, `"NCDHW"`,
缺少NWC？

2020-05-19 06:47 UTC, lanxianghit commented on python/paddle/nn/functional/common.py
> +    resample = mode.upper()
对于data_format没有进行大小写处理？

2020-05-19 06:47 UTC, lanxianghit commented on python/paddle/nn/layer/common.py
>              will be consistent with that of the input. An optional string from:'NCW', `"NCHW"`, `"NHWC"`, `"NCDHW"`,
同上，缺少NWC

2020-05-19 06:47 UTC, lanxianghit commented on python/paddle/nn/layer/common.py
> +        ValueError: data_format can only be 'NCW', 'NWC', 'NCHW', 'NHWC', 'NCDHW' or 'NDHWC'.
其他地方出现的也需要全面检查一下，还有其他地方有遗漏

2020-05-19 06:47 UTC, lanxianghit commented on python/paddle/nn/layer/common.py
>          self.data_format = data_format
对 data_format的大小写处理，涉及str类型的参数，都全面检查一下

2020-05-19 06:52 UTC, FDInSky commented on python/paddle/nn/functional/common.py
> +            will be consistent with that of the input. An optional string from:'NCW', `"NCHW"`, `"NHWC"`, `"NCDHW"`,
已修改

2020-05-19 06:52 UTC, FDInSky commented on python/paddle/nn/functional/common.py
> +    resample = mode.upper()
已修改

2020-05-19 06:52 UTC, FDInSky commented on python/paddle/nn/layer/common.py
>              will be consistent with that of the input. An optional string from:'NCW', `"NCHW"`, `"NHWC"`, `"NCDHW"`,
已修改

2020-05-19 06:53 UTC, FDInSky commented on python/paddle/nn/layer/common.py
>          self.data_format = data_format
这个调用的是function下的interpolate，所以在interpolate里做统一的处理

2020-05-20 02:26 UTC, FDInSky commented on python/paddle/nn/layer/common.py
> +        ValueError: data_format can only be 'NCW', 'NWC', 'NCHW', 'NHWC', 'NCDHW' or 'NDHWC'.
> 其他地方出现的也需要全面检查一下，还有其他地方有遗漏

全部查了一遍

2020-05-20 07:57 UTC, lanxianghit approved these changes

2020-05-21 03:15 UTC, swtkiwi approved these changes
LGTM

2020-05-21 03:27 UTC, merged