fix conv3d_transpose_test timeout error
PaddlePaddle/Paddle pull request #25004
Opened 2020-06-10 09:53 UTC by FDInSky

### PR types

Bug fixes

### PR changes

Others

### Describe

fix conv3d_transpose_test timeout error

2020-06-12 04:00 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
1. If there any other unit testing check the non-cudnn implementation？
2. You can try double for gradient check

2020-06-12 04:15 UTC, qingqing01 requested changes

2020-06-12 04:15 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
1. 这样改动GPU编译下，没有测试非cuDNN的实现。
2. 这个单测文件测试了很多单测，有26个Class的测试，其中25个继承 TestConv3dTransposeOp，每个里面都有4个测试。3D卷积计算量本身就大，

```
    def test_check_output(self):
    def test_check_grad(self):
    def test_check_grad_no_filter(self):
    def test_check_grad_no_input(self):
```

timeout的话，还是因为计算量大，测试多导致。


办法:
1. 一些单测去掉test_check_grad_no_filter和test_check_grad_no_input的测试。 这个测试主要是为了确保其中一个可以停止掉梯度。  可以只选典型的case测试即可。

2.  最后实在不行，拆分多个文件都行。

2020-06-12 05:14 UTC, luotao1 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
```

[18:39:43][Step 1/1] 158/216 Test  #353: test_conv3d_transpose_op ....................................***Timeout 350.01 sec
[18:39:43][Step 1/1] W0611 18:33:57.542786 32556 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
[18:39:43][Step 1/1] W0611 18:33:57.547647 32556 device_context.cc:273] device: 0, cuDNN Version: 7.3.
```
从错误日志看，是第一个case就hang住了，如果是由于计算量大测试多导致的，应该会打出很多日志吧。

2020-06-12 05:50 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
http://10.87.145.41:8111/viewLog.html?buildId=358160&buildTypeId=Paddle_PaddleManylinux_PrCiManylinuxCoverage&tab=buildLog


```
[18:26:00]        Start  353: test_conv3d_transpose_op


[18:31:50]
147/216 Test  #353: test_conv3d_transpose_op ....................................***Timeout 350.03 sec
[18:31:50]
W0610 18:26:03.890372 29274 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
[18:31:50]
W0610 18:26:03.895416 29274 device_context.cc:273] device: 0, cuDNN Version: 7.3.

```


@luotao1  现在的log是，有个start， end时报错timeout.

2020-06-12 06:40 UTC, FDInSky commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
![image](https://user-images.githubusercontent.com/48318485/84472657-2dc4fb00-acba-11ea-9e4c-b680a132e26a.png)

self.use_cudnn默认是false，从开始的10多个case默认cpu执行，然后timeout，不是这个原因吗？
test_conv3d_transpose在P40下是60ms，timeout是305ms，感觉不是case多导致的timeout吧？

2020-06-12 07:11 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +            self.use_cudnn = False
@FDInSky 如果不是因为单测太耗时，timeout的话，那需要再分析下。(之前以为是单测太耗时的原因)

2020-06-19 09:49 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
> +        self.filter_size = [f_c, 3, 3, 3, 3]
Need to revert these testing

2020-06-19 09:49 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/test_conv3d_transpose_op.py
else分支不要直接删除，非cudnn的cuda实现和cpu实现，得选1个case测试下。

2020-06-23 08:02 UTC, qingqing01 approved these changes

2020-06-24 02:13 UTC, merged