Encryption infer
PaddlePaddle/Paddle pull request #25119
Opened 2020-06-18 07:29 UTC by MRXLT

### PR types
Others

### PR changes
Others

### Describe

将模型加密相关的api加入到inference lib中

2020-06-24 02:50 UTC, Shixiaowei02 requested changes
请考虑两个建议：
1、暴露的类有点底层了，比如工厂暴露给了用户，建议将这部分改为内部实现；
2、尽量不将带模板参数的类和实现直接暴露给用户，由于类模板不能自动推导，增加了用户的理解成本和 C 兼容难度。
总的建议是封装一层再暴露出来。

2020-06-30 09:31 UTC, Shixiaowei02 submitted a review, later dismissed

2020-06-30 09:31 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/paddle_api.h
> +namespace framework {
建议不暴露 framework 名称空间

2020-06-30 09:31 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/paddle_api.h
> +#include "paddle/fluid/framework/io/crypto/cipher.h"
这个路径可能有问题

2020-06-30 09:51 UTC, MRXLT commented on paddle/fluid/inference/api/paddle_api.h
> +#include "paddle/fluid/framework/io/crypto/cipher.h"
done

2020-06-30 09:51 UTC, MRXLT commented on paddle/fluid/inference/api/paddle_api.h
> +namespace framework {
done

2020-07-02 03:00 UTC, Shixiaowei02 approved these changes

2020-07-02 03:10 UTC, Superjomn approved these changes
LGTM

2020-07-02 03:25 UTC, merged