resolve inference_pass_test input lodtensor case
PaddlePaddle/Paddle pull request #25541
Opened 2020-07-15 07:11 UTC by OliverLPH

### PR types

Others

### PR changes

Others

### Describe

1. If feed data type is LoDtensor, the analysis predictor will fail to copy data.
2. function check_output_with_option need bool input, but receive list.

2020-07-16 06:09 UTC, fc500110 commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                tensor.copy_from_cpu(feed_data)
``` python
feed_data = list(self.feeds.values())[i]
tensor.copy_from_cpu(np.array(feed_data))
if type(feed_data) == fluid.LoDTensor:
  tensor.set_lod(feed_data.lod())
```

2020-07-16 06:11 UTC, fc500110 requested changes
copy_from_cpu的参数需要是一个numpy.ndarray

2020-07-16 06:37 UTC, OliverLPH commented on python/paddle/fluid/tests/unittests/ir/inference/inference_pass_test.py
> +                tensor.copy_from_cpu(feed_data)
Done, thanks

2020-07-17 02:25 UTC, fc500110 approved these changes
LGTM

2020-07-17 02:35 UTC, merged