Auto pruning
PaddlePaddle/Paddle pull request #2603
Opened 2017-06-26 07:28 UTC by NHZlX

###Auto pruning
现在的static pruning，用户必须多次迭代的达到每个层的稀疏度，每次迭代用户必须再次启动模型训练，如果迭代次数过多，比较浪费时间。auto 的方式， 
用户指定每个层稀疏度所要达到的upperbound，网络只需要一次启动，sparsity 在interation过程中自动的达到所需的upperbound。

### Process of sparsity changes
![](https://raw.githubusercontent.com/NHZlX/Auto_pruning/master/examples/photo/log.png)
整个fine-tune过程，稀疏变化次数为  `end_pass / inter_pass`，每过`inter_pass` 次pass变化一次. 正如上图所示，变化过程为一个log曲线，到训练后期重要参数很多， 一次性prune掉较多参数会导致accuracy严重下降， 因而前期稀疏度上升比较大，越到后期上升幅度小。

### note
这是一个初步的实现，由于训练端的bug， 具体的模型还没有进行测试，同时在函数命名以及其他方面也需要一定的改进。eg： 每次sparisity变化是讲weights直接砍掉， 设置为0的元素，以后不会再拿回来。

2017-07-03 13:21 UTC, NHZlX commented
It exits bug, i am trying to settle it.

2017-07-06 07:17 UTC, luotao1 commented on paddle/api/PaddleAPI.h
> +  void preprocess(Parameter* param, size_t currentPass, size_t currentBatch);
.h文件中新加的函数都请添加注释，下同

2017-07-06 07:17 UTC, luotao1 commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    */
138-143行注释的代码请删掉。

2017-07-06 07:17 UTC, luotao1 commented on paddle/parameter/ParameterUpdaterHook.cpp
> +   */
169-178注释的代码请删掉。

2017-07-06 07:17 UTC, luotao1 commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  } else if (type == "dpruning") {
dpruning需要写全称dynamic_pruning，以便用户更好理解呢？

2017-07-07 14:49 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +   */
Done

2017-07-07 14:49 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    */
Done

2017-07-07 14:49 UTC, NHZlX commented on paddle/api/PaddleAPI.h
> +  void preprocess(Parameter* param, size_t currentPass, size_t currentBatch);
Done

2017-07-07 14:49 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  } else if (type == "dpruning") {
Done

2017-07-10 12:25 UTC, Xreki requested changes

2017-07-10 12:25 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  void handleBeforeFetch(Parameter *para) override {
1. 应该是在每个`forward`计算之前调用的吧，函数命名不直观。
2. 所有增加的接口都通过api接口，在python端调用控制train的流程，是否可以改成在`ParameterUpdaterBase.h`的`update`函数中调用：
```
 55   // between startBatch() and finishBatch(), update() will be called
 56   // by the trainer multiple times, each time for updating one Parameter
 57   // with its gradient in PARAMETER_GRADIENT
 58   void update(Parameter* para) {
 59     SetDevice setDevice(para->getDeviceId());
 60     para->updateHook();
 61     this->updateImpl(para);
        // Call handleBeforeFetch(para) here
 62   }
```

2017-07-10 12:25 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  }
我理解整个`dynamic pruning`流程是这样的：
1. 每隔`inter_pass`增大`sparsity_ratio`，并将参数保存到`weightTemp`中，下一个`inter_pass`中，`weightTemp`不会改变，`maskVec`不会改变。
2. 每次调用`backward`函数，在更新`parameter`之前，将`weightTemp`的数据拷贝到`para->getBuf(PARAMETER_VALUE)`中，相当于是在使用`weightTemp`来计算梯度更新，这里是会改变`para->getBuf(PARAMETER_VALUE)`的内容？改变的内容不需要保存到`weightTemp`里面？
3. 每次调用`forward`函数、即在使用`parameter`之前，先调用`handleBeforeFetch()`函数，将参数稀疏化`vec->dotMul(*maskVec_);`，他所使用的参数实际是对`weightTemp`做了更新的参数。

2017-07-11 06:23 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  virtual void generateMask(Parameter *para, size_t nonZeroNum) {
嗯， 好的

2017-07-11 06:36 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  }
1. preprocess(...)是每次forward都会调用的，所以weightTemp 每次都改变， maskVec是每隔inter_pass 才会改变一次 
2. 首先weightTemp 存储的是本次forward之前没有进行稀疏化的参数，前向的时候， 参数首先和mask相乘进行稀疏化，然后forwardbackward， 计算出梯度后， 我们更新的是本次forward之前没有进行稀疏化的参数， 原因是我们没有办法去改变momentum的稀疏度。
3. 由于没有办法改变momentum的稀疏度，所以每次更新paramters后，parameters的并不是mask代表的稀疏度，所以 handleBeforeFetch() 是在python api， paramter.tor_tar()的时候，先让parameter * mask，然后存储。

2017-07-13 03:48 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  }
1. `weightTemp`这个我理解了。而`preprocess`和`handleBeforeFetch()`都会在每次`forward`之前调用，并且执行`parameter * mask`，将`parameter`变成稀疏的。这两处应该可以合并一下。
2和3. 我们实际上只需要在梯度更新也就是`updateImpl()`的时候，才需要用到稠密的`weightTemp`，那么梯度更新完了之后，实际上就可以`parameter * mask`，使`parameter`的常态是稀疏的，这样也不用在`forward`计算和`to_tar`保存参数之前额外地执行一次`parameter * mask`，所以，请考虑在line 166行提出的建议。

2017-07-14 03:25 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  }
嗯， 在updateImpl()后进行parameter * mask，可以保证parameter 是稀疏的，这样是可以的，perfect！

2017-07-17 08:41 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    this->endPass_ = hookConfig.end_pass();
upper_bound 改成了 sparsity_upper_bound   inter_pass 改成 interval_pass ，属性名字太长的话用户体验不是太好，end_pass  的话我认为是有必要有的，num_passes 是整个训练过程经过的pass， 而end_pass 是我们sparsity_ratio 变化期间经过的pass

2017-07-17 08:41 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +      std::cout << para->getName()
Done

2017-07-17 08:41 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +  void handleBeforeFetch(Parameter *para) override {
Done

2017-12-12 08:08 UTC, hedaoyuan commented
@NHZlX @Xreki 这个PR还有问题吗？@NHZlX这周看看有时间把这个PR Refine一下Merge了吧。

2017-12-19 08:00 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +      this->maskVec_ = Vector::create(para->getSize(), para->useGpu());
`Hook`应该在整个训练过程中一直存在吧，也就是说，这里应该用`resizeOrCreate`？就是`maskVec_`如果已经被`create`过了，应该就不用再次`create`了。在`static pruning`里面，`generateMask`函数只被调用一次；在`dynamic pruning`里面，`generateMask`函数会被调用多次。

2017-12-19 08:00 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    paraVec->dotMul(*this->maskVec_);
这里只是有个疑问，`*this->maskVec_`是等价于`*(this->maskVec_)`的？为何要加`this`呢？

2017-12-19 08:00 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
>                                  "in same ParamterUpdater";
`invoke` -> `be invoked`
`same` -> `the same`

2017-12-19 08:00 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    auto &vec = para->getBuf(PARAMETER_VALUE);
看起来像是原来的`pruning`根本没生效啊，-____-

2017-12-19 08:00 UTC, Xreki commented on paddle/parameter/ParameterUpdaterHook.cpp
> +                                "in same ParamterUpdater";
同上

2017-12-19 08:00 UTC, Xreki commented on paddle/trainer/ThreadParameterUpdater.cpp
> +    para->updateHook();
这里为何需要调用`updateHook`，我理解，在每次调用`para->update()`的时候同时调用`updateHook()`即可？

2017-12-19 08:00 UTC, Xreki commented on proto/ParameterConfig.proto
> +  // More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
这里可以改成具体见实现代码，还是不要引用这个pr吧。

2017-12-19 08:00 UTC, Xreki commented on python/paddle/trainer_config_helpers/attrs.py
> +                        More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
这里也是，不要引用pr。可以把计算的公式在这里列出来，在对`dynamic pruning`的总体介绍里面。

2017-12-19 08:00 UTC, Xreki commented on python/paddle/trainer_config_helpers/attrs.py
> +        if self.interval_pass is not None:
`dynamic pruning`类型时，`interval_pass`和`end_pass`是必须设置的吧，这里要`check`下。另外，`pruning`类型时，不需要设置这些参数，打个warning提醒这些设置是不生效的，提醒使用`dynamic pruning`类型。

2017-12-19 08:00 UTC, Xreki commented on paddle/api/PaddleAPI.h
> +  void preprocess(Parameter* param, size_t currentPass, size_t currentBatch);
参数名，我觉得还是叫`passId`和`batchId`比较好。

2017-12-19 09:14 UTC, NHZlX commented on python/paddle/trainer_config_helpers/attrs.py
> +        if self.interval_pass is not None:
interval_pass 和end_pass 可以使用默认的， 不过可以设置一下提醒

2017-12-19 09:15 UTC, NHZlX commented on python/paddle/trainer_config_helpers/attrs.py
> +                        More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
@Xreki  ok

2017-12-19 09:16 UTC, NHZlX commented on proto/ParameterConfig.proto
> +  // More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
ok

2017-12-19 09:32 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterBase.h
> +    if (para->useGpu()) {
这里的updateImpl(para) 只在gpu下会更新 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/ThreadParameterUpdater.cpp#L85   cpu的在调用finishBatch() 时候会更新参数, 不是太清楚当时为什么这么设计，但是这块我确实找了很长时间。。。

2017-12-19 09:35 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    auto &vec = para->getBuf(PARAMETER_VALUE);
我们先进行梯度更新，由于momentum， 可能param之前为0的又变化了， 然后调用update() 重新将param 设置为0.

2017-12-19 09:35 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +      this->maskVec_ = Vector::create(para->getSize(), para->useGpu());
ok 这里应该使用resizeOrCreate

2017-12-19 09:36 UTC, NHZlX commented on paddle/parameter/ParameterUpdaterHook.cpp
> +    paraVec->dotMul(*this->maskVec_);
this 可以去掉...

2017-12-19 09:37 UTC, NHZlX commented on paddle/trainer/ThreadParameterUpdater.cpp
> +    para->updateHook();
原因是，cpu更新权重（w = w - w_diff）在finishbatch 中gpu在 updateImpl()中，即
 https://github.com/NHZlX/Paddle/blob/7c9d5e5653155aa2a9106ba9621a1fa7f3b3bc0f/paddle/trainer/ThreadParameterUpdater.cpp#L202  所以得分开进行update

2017-12-19 09:38 UTC, NHZlX commented on proto/ParameterConfig.proto
> +  // More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
ok

2017-12-19 09:38 UTC, NHZlX commented on python/paddle/trainer_config_helpers/attrs.py
> +                        More details can be found https://github.com/PaddlePaddle/Paddle/pull/2603
ok

2018-08-09 04:15 UTC, closed without merging