add intepolte_v2
PaddlePaddle/Paddle pull request #26520
Opened 2020-08-21 03:46 UTC by tink2123

### PR types
Performance optimization

### PR changes
APIs

### Describe

Update interpolate API

* Support list in scale_factor
* Modify parameter default values

2020-08-21 11:29 UTC, willthefrog requested changes

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
>          Bilinear interpolation:
remove `:alias` from docstring

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
>          Bilinear interpolation:
`Variable` -> `Tensor`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
>          Bilinear interpolation:
update code samples to 2.0 API

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
>      if align_mode != 0 and align_mode != 1:
add fast path for dygraph mode

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +        raise ValueError(
also enforce in v2 op.

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +                "Attr(scale)'s type should be float, int, list or Variable.")
`Variable` -> `Tensor`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +        input (Variable): 3-D, 4-D or 5-D Tensor, its data type is float32, float64, or uint8,
`Variable`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +    **Warning:** the parameter :attr:`actual_shape` will be deprecated in the
remove

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +    Align_corners and align_mode are optional parameters,the calculation method
`align_corners`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +            import paddle.fluid.dygraph as dg
update to 2.0 API

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/layer/common.py
> +    **Warning:** the parameter :attr:`actual_shape` will be deprecated in the
remove

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/layer/common.py
> +    def __init__(self, size=None, scale_factor=None, data_format='NCHW'):
`name`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/layer/common.py
> +    def forward(self, input):
`input` -> `x`

2020-08-21 11:29 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +def upsample(input,
`input` -> `x`

2020-08-24 09:45 UTC, LDOUBLEV commented on python/paddle/nn/functional/common.py
> +            output = F.interpolate(x=x, size=[12,12])
是否需要多举个例子说明不同mode的区别

2020-08-24 11:22 UTC, tink2123 commented on python/paddle/nn/functional/common.py
> +            output = F.interpolate(x=x, size=[12,12])
Done~ thx!

2020-08-24 11:22 UTC, tink2123 commented on python/paddle/nn/functional/common.py
> +def upsample(input,
Above problems has been fixed, please review again

2020-08-25 02:26 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +    Align_corners and align_mode are optional parameters,the calculation method
Align -> align

2020-08-25 03:28 UTC, tink2123 commented on python/paddle/nn/functional/common.py
> +    Align_corners and align_mode are optional parameters,the calculation method
Done, thx~

2020-08-25 10:12 UTC, jzhang533 approved these changes, later dismissed
lgtm

2020-08-25 11:30 UTC, willthefrog submitted a review, later dismissed

2020-08-27 05:02 UTC, willthefrog approved these changes
LGTM

2020-08-27 05:44 UTC, jzhang533 approved these changes
lgtm

2020-08-27 05:59 UTC, XiaoguangHu01 approved these changes
LGTM

2020-08-27 07:31 UTC, luotao1 commented
```
2020-08-27 14:24:06 1. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 (Recommend) or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_accuracy_white_list.py, which manages the white list of upgrading the precision of op test to float64. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
2020-08-27 14:24:06 2. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_threshold_white_list.py, which manages the white list of error threshold for op test with float64 precision. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
2020-08-27 14:24:06 5. Please use the default precision parameters of 'atol, rtol, eps, max_relative_error'. If you don't use the default value, you must have one RD (Xreki (Recommend), luotao1, lanxianghit or phlrain) approval for the usage of other values. The detailed information is in the link: https://github.cor/PaddlePaddle/Paddle/wiki/OP-test-accuracy-requirements. The error line is 
2020-08-27 14:24:06 +            self.check_output(atol=1e-7)
2020-08-27 14:24:06 +            self.check_output(atol=1e-5)
2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-7)
2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-5)
2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
2020-08-27 14:24:06 There are 6 approved errors.
2020-08-27 14:24:06 ****************
```
@XiaoguangHu01 @lanxianghit 因为这个OP不符合精度规范，请问可以豁免么？
@tink2123 可以说下原因

2020-08-27 07:40 UTC, tink2123 commented
> ```
> 2020-08-27 14:24:06 1. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 (Recommend) or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_accuracy_white_list.py, which manages the white list of upgrading the precision of op test to float64. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
> 2020-08-27 14:24:06 2. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_threshold_white_list.py, which manages the white list of error threshold for op test with float64 precision. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
> 2020-08-27 14:24:06 5. Please use the default precision parameters of 'atol, rtol, eps, max_relative_error'. If you don't use the default value, you must have one RD (Xreki (Recommend), luotao1, lanxianghit or phlrain) approval for the usage of other values. The detailed information is in the link: https://github.cor/PaddlePaddle/Paddle/wiki/OP-test-accuracy-requirements. The error line is 
> 2020-08-27 14:24:06 +            self.check_output(atol=1e-7)
> 2020-08-27 14:24:06 +            self.check_output(atol=1e-5)
> 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> 2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-7)
> 2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-5)
> 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> 2020-08-27 14:24:06 There are 6 approved errors.
> 2020-08-27 14:24:06 ****************
> ```
> 
> @XiaoguangHu01 @lanxianghit 因为这个OP不符合精度规范，请问可以豁免么？
> @tink2123 可以说下原因

这个问题应该是因为 numpy 和 c++ 在非整数计算插值的时候精度达不到要求。这次没有改旧的OP，之前的版本一直就在白名单里，新版本也需要加上才能过单测。对比过pytorch和paddle的输出结果，精度误差在1e-6可以对齐。

2020-08-27 08:51 UTC, XiaoguangHu01 commented
> > ```
> > 2020-08-27 14:24:06 1. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 (Recommend) or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_accuracy_white_list.py, which manages the white list of upgrading the precision of op test to float64. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
> > 2020-08-27 14:24:06 2. It is an Op accuracy problem, please take care of it. You must have one RD (juncaipeng (Recommend), zhangting2020 or luotao1) approval for the python/paddle/fluid/tests/unittests/white_list/op_threshold_white_list.py, which manages the white list of error threshold for op test with float64 precision. For more information, please refer to: https://github.com/PaddlePaddle/Paddle/wiki/Upgrade-OP-Precision-to-Float64. 
> > 2020-08-27 14:24:06 5. Please use the default precision parameters of 'atol, rtol, eps, max_relative_error'. If you don't use the default value, you must have one RD (Xreki (Recommend), luotao1, lanxianghit or phlrain) approval for the usage of other values. The detailed information is in the link: https://github.cor/PaddlePaddle/Paddle/wiki/OP-test-accuracy-requirements. The error line is 
> > 2020-08-27 14:24:06 +            self.check_output(atol=1e-7)
> > 2020-08-27 14:24:06 +            self.check_output(atol=1e-5)
> > 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> > 2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-7)
> > 2020-08-27 14:24:06 +            self.check_output_with_place(place=core.CPUPlace(), atol=1e-5)
> > 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> > 2020-08-27 14:24:06 +        self.check_output_with_place(place=core.CPUPlace(), atol=1)
> > 2020-08-27 14:24:06 There are 6 approved errors.
> > 2020-08-27 14:24:06 ****************
> > ```
> > 
> > 
> > @XiaoguangHu01 @lanxianghit 因为这个OP不符合精度规范，请问可以豁免么？
> > @tink2123 可以说下原因
> 
> 这个问题应该是因为 numpy 和 c++ 在非整数计算插值的时候精度达不到要求。这次没有改旧的OP，之前的版本一直就在白名单里，新版本也需要加上才能过单测。对比过pytorch和paddle的输出结果，精度误差在1e-6可以对齐。

确认可以先加入白名单。跟之前的op保持一致。@luotao1

2020-08-27 09:23 UTC, raindrops2sea approved these changes
增补一个pr注释说明一下新增v2 op的考量。

2020-08-27 09:25 UTC, luotao1 approved these changes
LGTM

2020-08-27 09:27 UTC, merged