fix syncbn, test=develop
PaddlePaddle/Paddle pull request #26523
Opened 2020-08-21 05:19 UTC by ceci3

### PR types

Others

### PR changes

APIs

### Describe

use_global_stats  only  support use_global_stats = false, fix it

2020-08-23 12:31 UTC, willthefrog requested changes

2020-08-23 12:31 UTC, willthefrog commented on python/paddle/nn/layer/norm.py
> +            logging.warn(
use `warnings` instead of `logging`

2020-08-23 14:40 UTC, ceci3 commented on python/paddle/nn/layer/norm.py
> +            logging.warn(
done, thanks

2020-08-24 07:18 UTC, XiaoguangHu01 approved these changes
LGTM

2020-08-24 07:41 UTC, jzhang533 approved these changes
lgtm

2020-08-24 08:29 UTC, willthefrog approved these changes
LGTM

2020-08-24 08:30 UTC, merged