【2.0 API】Add CUDA kernel and enhance options for grid_sample
PaddlePaddle/Paddle pull request #26576
Opened 2020-08-23 10:49 UTC by wanghaoshuang

### PR types

New features

### PR changes

OPS

### Describe

This PR enhance CPU kernel and add new CUDA kernel to make grid_sample support:
1. align_corners: with bool type.
2. padding mode: which can be in ['zeros', 'reflect', 'border']
3. Interpolation mode:  which ca be in ['bilinear', 'nearest']

The old CPU and CUDNN version only support align_corners=true, padding_mode='zeros' and interpolation_mode='bilinear'.

The behavior of the new version op in default mode is compatible with the old version.

2020-08-23 12:20 UTC, heavengate submitted a review, later dismissed

2020-08-23 12:27 UTC, willthefrog requested changes

2020-08-23 12:27 UTC, willthefrog commented on paddle/fluid/operators/grid_sampler_op.cu
> +using Mode = paddle::operators::Model;
`Model`?

2020-08-23 12:27 UTC, willthefrog commented on python/paddle/nn/functional/vision.py
> +            import paddle.fluid as fluid
update sample

2020-08-23 12:27 UTC, willthefrog commented on paddle/fluid/operators/grid_sampler_op.h
> +enum class Model {
`Model`?

2020-08-23 12:27 UTC, willthefrog commented on python/paddle/nn/functional/vision.py
> +            out = fluid.layers.grid_sampler(x=x, grid=grid)
`sampler` -> `sample`

2020-08-23 12:27 UTC, willthefrog commented on python/paddle/nn/functional/vision.py
> +    helper = LayerHelper("grid_sampler", **locals())
`sampler` -> `sample`

2020-08-23 12:27 UTC, willthefrog commented on paddle/fluid/operators/grid_sampler_op.cc
> +    ctx->SetOutputDim("Output",
make sure not to break backward compatibility, otherwise a new OP should be  added

2020-08-23 13:39 UTC, wanghaoshuang commented on paddle/fluid/operators/grid_sampler_op.cu
> +using Mode = paddle::operators::Model;
Fixed.

2020-08-23 13:39 UTC, wanghaoshuang commented on python/paddle/nn/functional/vision.py
> +            import paddle.fluid as fluid
Done.

2020-08-23 13:39 UTC, wanghaoshuang commented on python/paddle/nn/functional/vision.py
> +    helper = LayerHelper("grid_sampler", **locals())
Updated.

2020-08-23 13:41 UTC, wanghaoshuang commented on paddle/fluid/operators/grid_sampler_op.cc
> +    ctx->SetOutputDim("Output",
Yes. It is compatibility with old version.

2020-08-24 02:36 UTC, heavengate approved these changes

2020-08-24 06:00 UTC, raindrops2sea approved these changes

2020-08-24 06:25 UTC, raindrops2sea commented
> ### PR types
> New features
> 
> ### PR changes
> OPS
> 
> ### Describe
> Add CUDA kernel and enhance options for grid_sample

a more detailed description is needed.

2020-08-24 06:38 UTC, willthefrog approved these changes

2020-08-24 06:42 UTC, lanxianghit approved these changes
LGTM

2020-08-24 06:47 UTC, merged