TensorDump through overloading operator<<
PaddlePaddle/Paddle pull request #26606
Opened 2020-08-24 09:43 UTC by lidanqing-intel

### PR types

### PR changes

### Describe

2020-08-31 08:10 UTC, lidanqing-intel commented
@jczaja @wojtuss  Please review.

2020-08-31 09:02 UTC, lidanqing-intel commented
@arogowie-intel  Hi Adam, please review

2020-08-31 12:19 UTC, jczaja reviewed
1.  When I want to dump all oneDNN ops. Do i I have to list them all fc, conv matmul etc. , or there exist key "all"  so I do not have to list it?
2.  This is only for oneDNN ops e.g. We cannot use this mechanism for native CPU ops ?
3. This mechanism is always enabled e.g. even when we do not dump anything there is TensorDumpConfig for each op will at least check that executed op is not in the list of ops to be dumped. So there is tiny overhead. Have you checkd impact of this mechanics on performance of mobiletnet_v2/mobilenet_ssd INT8 inference ?

2020-08-31 12:19 UTC, jczaja commented on paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
> +  if (algorithm == mkldnn::algorithm::eltwise_tanh) {
This if-else is only to get a name "tanh" or "relu"  put into ::execute as first param. Perhaps it would be good to make
a macro that translates algorith into string rather than go into this kind of if-else blocks. That just suggesstion for future improvement.

2020-08-31 12:19 UTC, jczaja commented on paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
> +  setenv("TENSOR_DUMP_OPERATORS",
why this is here?

2020-08-31 12:19 UTC, jczaja commented on paddle/fluid/platform/mkldnn_reuse.h
> +constexpr const char* RESET() { return "\033[0m"; }
Are those colors (terminal sequences) terminal specific? I think There will be no colors on tmux terminals just text value of control sequences?

2020-09-01 07:57 UTC, arogowie-intel requested changes

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/operators/mkldnn/activation_mkldnn_op.cc
> +  if (algorithm == mkldnn::algorithm::eltwise_tanh) {
Macro or a type trait structure with string member type_name holding character representation of a function.

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
> +#include <stdlib.h>
Why are you adding here this header with no other changes in this file? Is it really needed?

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/operators/mkldnn/fc_mkldnn_op.cc
> +#include "paddle/fluid/platform/mkldnn_reuse.h"
Why are you adding here this header with no other changes in this file? Is it really needed?

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/platform/mkldnn_reuse.h
> +
I think this is not the best place for this code. Please move it to separate file and put in a specific namespace.

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/platform/mkldnn_reuse.h
> +    // TensorDumpConfig();
Please remove commented code leftovers.

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/platform/mkldnn_reuse.h
> + public:
This keyword here is unnecessary. It's continuation of `public` symbols.

2020-09-01 07:57 UTC, arogowie-intel commented on paddle/fluid/platform/mkldnn_reuse.h
> + public:
This keyword here is unnecessary. It's continuation of public symbols.

2020-09-01 21:34 UTC, lidanqing-intel commented
@jczaja 
Maybe I should use VLOG, it will not influence running time, and should add it in op. Like in operator.cc file: `VLOG(4) << place << " " << DebugStringEx(&scope);`  But to save to different output file names, do you know how to save to different files with VLOG ?

2020-09-04 11:14 UTC, lidanqing-intel commented on paddle/fluid/platform/mkldnn_reuse.h
> +constexpr const char* RESET() { return "\033[0m"; }
Yes, color is shown in tmux

2020-09-15 08:41 UTC, wojtuss commented on paddle/fluid/operators/mkldnn/transpose_mkldnn_op.cc
> +    auto out_name = ctx.OutputName("Out");
I think this change is not needed.

2020-09-15 08:41 UTC, wojtuss commented on paddle/fluid/platform/mkldnn_reuse.h
> +DECLARE_int64(dump_limit);
I would prefer a unified name like `tensor_dump_limit`

2020-09-15 08:41 UTC, wojtuss commented on python/paddle/fluid/tests/unittests/mkldnn/test_fc_mkldnn_op.py
> +# class TestMKLDNNTensorDumpOp(unittest.TestCase):
Should the commented out code be removed?

2020-09-15 08:41 UTC, wojtuss commented on paddle/fluid/operators/mkldnn/test_mkldnn_op_inplace.cc
> +#include <stdlib.h>
Why is this include added?

2020-10-08 08:47 UTC, closed without merging

2020-10-08 08:50 UTC, lidanqing-intel commented
Not good way to dump in each op.
Add in operator.cc DebugStringEx 
https://github.com/otcshare/iags-pl-wiki/blob/master/tutorials/print_any_var_values.md