Implement the function of OueScaleForTraining/OutScaleForInference in dygraph
PaddlePaddle/Paddle pull request #26601
Opened 2020-08-24 08:22 UTC by gfwm2013

### PR types
New features

### PR changes
 APIs

### Describe
Implement the function of OutScaleForTraining / OutScaleForInference in dygraph

2020-09-27 12:00 UTC, wzzju requested changes

2020-09-27 12:00 UTC, wzzju commented on paddle/fluid/pybind/op_function_generator.cc
> +    {"amp_check_finite_and_scale", {"Out", "FoundInfinite"}},
?? This is not needed.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +from paddle.nn.layer import ReLU, LeakyReLU, Sigmoid, ReLU6, Tanh, Softmax, PReLU
I prefer to write codes as follow (from its definition location), but you can choose it or not.

```python
from paddle.nn.layer.activation import ReLU, LeakyReLU, Sigmoid, ReLU6, Tanh, Softmax, PReLU
```

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +                     'Conv2D', 'Pool2D', 'ReLU', 'BatchNorm', 'PRelu',
Why not include `Linear` and `PReLU`?

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            moving_rate(float): the parameter for 'moving_average_abs_max_scale' quantization.
Use `The decay coefficient of moving average. The default value is 0.9.` instead.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +                Default is ['Conv2D', 'ReLU', 'PReLU', 'LeakyReLU', 'Sigmoid', 'BatchNorm', 'ReLU6', 'Tanh', 'Softmax', 'Conv2DTranspose']
Why not include `Linear` and `PReLU`?

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            'Conv2DTranspose': Conv2DTranspose
Why not include `Linear` and `PReLU`?

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_out_scale.py
> +    def forward(self, inputs):
Add `Softmax` test in UT.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_out_scale.py
> +        imperative_out_scale = ImperativeOutScale()
imperative_out_scale = ImperativeOutScale(target_layer_types = ['Conv2D', 'BatchNorm', 'ReLU', 'Pool2D', 'PRelu', 'Linear', 'LeakyReLU', 'Sigmoid', 'Softmax'])

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +                 out_scale_layer_type=[
Replace `out_scale_layer_type ` with `target_layer_types`.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +    def __init__(self,
Replace `ImperativeOutScale` with `ImperativeCalcOutScale`.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +    def get_out_scale(self, model):
Replace `get_out_scale` with `calc_out_scale`.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            if not hasattr(layer, "_out_scale"):
Why need this `if` statement ?

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        self._out_scale_dict[layer.full_name()] = scale_out_list
Use the following codes instead.
```python
def _forward_post_hook(self, layer, input, output):
    if not isinstance(output, list):
        output = [output]
    out_scales = {}
    for var in output:
        if var.dtype not in [
                core.VarDesc.VarType.FP32, core.VarDesc.VarType.FP64
        ]:
            continue
        calc_out_scale = quant_nn.MovingAverageAbsMaxScale(
            var.name, self._moving_rate, var.dtype)
        scale_out = calc_out_scale(var)
        out_scales[var.name] = scale_out
    self._out_scale_dict[layer.full_name()] = out_scales
```

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            handle.remove()
Use the following codes instead.

```python
def set_out_scale(self, model):
    """
    Set the output quantization scale to the corresponding Layer of model.
    Args:
        model(fluid.dygraph.Layer): The output scale would be added to the model.
    Returns:
        None
    """
    assert isinstance(
        model, dygraph.Layer), "model must be the instance of dygraph.Layer"
    for _, layer in model.named_sublayers():
        if not isinstance(layer, self._out_scale_layer_type):
            continue
        out_scales = self._out_scale_dict[layer.full_name()]
        for name, scale in out_scales.items():
            # `name + '_out_threshold'` may not the proper name.
            layer.__setattr__(name + '_out_threshold', np.float32(scale.numpy()))
    for handle in self._register_hook_handle_list:
        handle.remove()
```

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        self._register_hook_handle_list = []
Put the definition of `self._register_hook_handle_list` in `__init__`.

2020-09-27 12:00 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        self._out_scale_dict = {}
Put the definition of `self._out_scale_dict` in `__init__`.

2020-09-27 12:11 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +                layer.__setattr__('out_threshold', scale_var)
What do you want to do here? 🤒

2020-10-10 09:02 UTC, gfwm2013 commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +    def __init__(self,
Thanks, done.

2020-10-10 09:06 UTC, gfwm2013 commented on paddle/fluid/pybind/op_function_generator.cc
> +    {"amp_check_finite_and_scale", {"Out", "FoundInfinite"}},
Thanks, it has been deleted.

2020-10-13 10:03 UTC, juncaipeng reviewed
收集输出scale的功能是量化训练的一部分，所以这部分api可以不用暴露给用户。
如果可以在ImperativeQuantAware中调用ImperativeCalcOutScale，可以更加简洁

2020-10-13 10:03 UTC, juncaipeng commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        self._out_scale_layers_map = {
More ops should be supported.

2020-10-14 12:24 UTC, zhiqiu approved these changes
LGTM for op_function_generator.cc

2020-10-14 13:39 UTC, wzzju approved these changes
LGTM.

2020-10-14 13:39 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_out_scale.py
> +            op_object_list = (Conv2D, ReLU, ReLU6, LeakyReLU, Sigmoid, Pool2D,
This is useless here.

2020-10-14 13:39 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_out_scale.py
> +        imperative_out_scale = ImperativeCalcOutScale()
Use `target_layer_types` to create the object of `ImperativeCalcOutScale`.

2020-10-14 13:43 UTC, merged