Implemented AddQuantDequantPass in imperative quantization.
PaddlePaddle/Paddle pull request #26692
Opened 2020-08-26 05:56 UTC by huangxu96

### PR types

New features
### PR changes

APIs
### Describe

Finished API for imperative quantization. Now it can support the AddQuantDequantPass in imperative quantization.

2020-09-27 09:04 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/quant_nn.py
> +        self.layer = layer
Please use `self._layer` instead.

2020-09-27 09:04 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/quant_nn.py
> +                 activation_quantize_type='abs_max'):
According to static quantization, this should always be `moving_average_abs_max`. Just refine as follow,

```python
    def __init__(self,
                 layer,
                 weight_bits=8,
                 activation_bits=8,
                 moving_rate=0.9,
                *args,
                **kwargs):
```

2020-09-27 09:04 UTC, wzzju commented on python/paddle/fluid/contrib/slim/quantization/imperative/quant_nn.py
> +            quant_on_weight=False)
Just refine as follow,
```python
        self._fake_quant_input = _get_fake_quant_type(
            'moving_average_abs_max',
            name=layer.full_name(),
            moving_rate=moving_rate,
            quant_bits=activation_bits,
            dtype=self._dtype,
            quant_on_weight=False)
```

2020-09-27 09:04 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +    conv1 = paddle.fluid.layers.leaky_relu(conv1)
```python
conv1 = paddle.fluid.layers.leaky_relu(conv1,  alpha=0.02)
```

2020-09-27 12:25 UTC, wzzju requested changes

2020-09-27 12:25 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +        paddle.jit.save(
Use `paddle.jit.save(lenet.eval(), ...)` instead.

2020-09-27 12:25 UTC, wzzju commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +            layer=lenet,
Use `paddle.jit.save(lenet.eval(),...)` instead.

2020-09-27 12:40 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/quantization/imperative/quant_nn.py
> +        self.layer = layer
Done.

2020-09-27 13:00 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/quantization/imperative/quant_nn.py
> +                 activation_quantize_type='abs_max'):
Done.

2020-09-27 13:58 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +    conv1 = paddle.fluid.layers.leaky_relu(conv1)
Done

2020-09-27 13:58 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +        paddle.jit.save(
Done

2020-09-27 13:58 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/tests/test_imperative_qat_AddQuantDequant.py
> +            layer=lenet,
Done.

2020-11-04 02:46 UTC, juncaipeng reviewed
Cannot quantize multiple input ops, such as elementwise_add

这个暂时不考虑，后面再支持

2020-11-17 06:21 UTC, juncaipeng commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            quantizable_layer_type(list[str]): List the type of layers that will be quantized.
参考pytorch和tf，建议这里用户传入paddle.nn.Conv2D等layer，不要传入str

2020-11-17 06:21 UTC, juncaipeng commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        if quantized_counterpart[index] in no_weight_layer:
后续会有很多无权重op的量化，建议这个if判断调换一下顺序，判断是否是有权重量化op

2020-11-20 08:42 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +        if quantized_counterpart[index] in no_weight_layer:
Done.

2020-11-20 08:42 UTC, huangxu96 commented on python/paddle/fluid/contrib/slim/quantization/imperative/qat.py
> +            quantizable_layer_type(list[str]): List the type of layers that will be quantized.
下个PR 会考虑改成这总写法。

2020-11-25 03:50 UTC, juncaipeng submitted a review, later dismissed
LGTM

2021-01-13 02:57 UTC, XieYunshen approved these changes

2021-01-13 03:17 UTC, juncaipeng approved these changes
LGTM

2021-01-13 03:17 UTC, juncaipeng approved these changes
LGTM

2021-01-13 03:20 UTC, wzzju approved these changes
LGTM.

2021-01-13 04:32 UTC, merged