Pass version check
PaddlePaddle/Paddle pull request #26887
Opened 2020-09-01 12:20 UTC by shangzhizhou

### PR types

### PR changes

### Describe

2020-09-01 12:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=26887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=26887) before we can accept your contribution.<br/><hr/>**Shang Zhizhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=26887) it.</sub>

2020-09-02 07:08 UTC, Shixiaowei02 requested changes

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +  uint32_t GetVersionID() { return static_cast<uint32_t>(checkpoints_.size()); }
是否可标注 `const` 成员方法

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +  bool IsMatched() {
是否可标注 `const` 成员方法

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +      if (!(*cmp.get())()) {
考虑使用 `if (!(*cmp)())` 或者 `if ((*cmp)() == false)`

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +    for (auto& checker : pass_version_checkers_) {
在上面的 review 修改完成后，此处可修改为常量引用 `const auto&`

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +  bool IsPassCompatible(const std::string& fuse_pass_name) {
`const` 成员函数

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +  virtual ~OpVersionComparator() {}
可声明为默认 `= default`

2020-09-02 07:08 UTC, Shixiaowei02 commented on paddle/fluid/framework/op_version_registry.h
> +  uint32_t GetVersionID(const std::string& op_type) {
同上

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +  uint32_t GetVersionID() { return static_cast<uint32_t>(checkpoints_.size()); }
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +  uint32_t GetVersionID(const std::string& op_type) {
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +  virtual ~OpVersionComparator() {}
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +      if (!(*cmp.get())()) {
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +    for (auto& checker : pass_version_checkers_) {
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +  bool IsMatched() {
done

2020-09-02 10:36 UTC, shangzhizhou commented on paddle/fluid/framework/op_version_registry.h
> +  bool IsPassCompatible(const std::string& fuse_pass_name) {
done，同时修改了下实现，因为直接取map的key可能生成一个default value，行为也不是const的。
```c++
    auto iter = pass_version_checkers_map_.find(fuse_pass_name);
    if (iter == pass_version_checkers_map_.end()) {
      return true;
    }
    return iter->second.IsPassCompatible();
```

2020-09-02 11:00 UTC, Shixiaowei02 approved these changes

2020-09-02 12:34 UTC, Superjomn approved these changes
LGTM

2020-09-03 01:53 UTC, merged