【cherry-pick 1.8】fix ports conflict when use paddlecloud to launch analogue multi-nodes
PaddlePaddle/Paddle pull request #27117
Opened 2020-09-07 07:33 UTC by danleifeng

### PR types

Bug fixes
### PR changes

APIs
### Describe

在Paddlecloud提交GPU多节点任务时，若Paddlecloud内部分配多节点到一台机器上，则使用launch/fleetrun命令时会出现端口冲突问题。
新增对 DISTRIBUTED_TRAINER_ENDPOINTS环境变量的解析（Paddlecloud 1.8.4之后提供）。

2020-09-08 02:49 UTC, gongweibao requested changes

2020-09-08 02:49 UTC, gongweibao commented on python/paddle/distributed/cloud_utils.py
> +    trainer_endpoints = os.getenv("DISTRIBUTED_TRAINER_ENDPOINTS")
DISTRIBUTED_TRAINER_ENDPOINTS需要举一个例子说明其格式。

2020-09-08 02:49 UTC, gongweibao commented on python/paddle/distributed/utils.py
> +            endpoint for endpoint in trainer_endpoints if ip in endpoint
endpoints应该是按照顺序来的吧？为何要判断 `ip in endpoint`， 如果一个node上启动多个pod?

2020-09-08 02:49 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_launch.sh
> +export DISTRIBUTED_TRAINER_ENDPOINTS=127.0.0.1:6170,127.0.0.1:6171,127.0.0.2:6170,127.0.0.2:6171
使用DISTRIBUTED_TRAINER_ENDPOINTS 和不使用的两种协议都要测试到。
这个单测并且写上说明测试的是什么。

2020-09-08 03:49 UTC, danleifeng commented on python/paddle/distributed/utils.py
> +            endpoint for endpoint in trainer_endpoints if ip in endpoint
trainer_endpoints 是 多机所有的ip:port， 这里需要取得当前ip（本机）的ip:port，paddlecloud上多机不同node的pod_ip也是不同的（eg: node1: job-a-trainer-0.b, node2: job-a-trainer-1.b)

2020-09-08 03:50 UTC, danleifeng commented on python/paddle/distributed/cloud_utils.py
> +    trainer_endpoints = os.getenv("DISTRIBUTED_TRAINER_ENDPOINTS")
done，thanks!

2020-09-08 05:01 UTC, gongweibao commented on python/paddle/distributed/utils.py
> +            endpoint for endpoint in trainer_endpoints if ip in endpoint
`paddlecloud上多机不同node的pod_ip也是不同的` 他们可能会给物理ip，而不是hostname。

2020-09-08 05:34 UTC, danleifeng commented on python/paddle/fluid/tests/unittests/test_launch.sh
> +export DISTRIBUTED_TRAINER_ENDPOINTS=127.0.0.1:6170,127.0.0.1:6171,127.0.0.2:6170,127.0.0.2:6171
#21 行就是测试了没有设置DISTRIBUTED_TRAINER_ENDPOINTS 时的情况
#54 行这里是测试了设置DISTRIBUTED_TRAINER_ENDPOINTS 时的情况
已加注释，thanks！

2020-09-09 12:16 UTC, gongweibao commented on python/paddle/distributed/utils.py
> +        assert len(cur_node_endpoints) >= len(
==

2020-09-09 12:42 UTC, danleifeng commented on python/paddle/distributed/utils.py
> +        assert len(cur_node_endpoints) >= len(
>= 是因为有可能paddlecloud指定的单机8卡，但它使用launch --selected_gpus 只用了4卡，这时endpoints的个数就会大于selected_gpus的个数。

2020-09-09 12:44 UTC, danleifeng commented on python/paddle/distributed/utils.py
> +        assert len(cur_node_endpoints) >= len(
这个get_cluster是cloud和非cloud共用的，接口传入的selected_gpus是用户的参数，endpoints是所有卡的endpoints，若和所有的卡数比较，那么就是自己和自己比较，没有意义。

2020-09-10 08:38 UTC, gongweibao submitted a review, later dismissed
LGTM

2020-09-15 04:03 UTC, gongweibao approved these changes
LGTM

2020-09-15 05:18 UTC, merged