windows lib size crop from 5.4G to 3.9G
PaddlePaddle/Paddle pull request #27477
Opened 2020-09-22 12:33 UTC by jiweibo

### PR types

Others
### PR changes

Others
### Describe

Revert pr https://github.com/PaddlePaddle/Paddle/pull/25593. 

Windows static lib size from 5.4G to 3.9G by remove /Zi flag.

2020-09-23 11:08 UTC, T8T9 requested changes

2020-09-23 11:08 UTC, T8T9 commented on tools/windows/paddle_win.props
> +            <Defines></Defines>
这些没有修改的参数，删掉有影响么？

2020-09-23 11:12 UTC, jiweibo commented on tools/windows/paddle_win.props
> +            <Defines></Defines>
之前把HostCommandLineTemplate之外的都删掉了，该文件就不起作用了

后来折衷把ItemDefinitionGroup之外的properties都删掉了，保留了所有cuda ItemDefinitionGroup的内容

2020-09-23 11:13 UTC, jiweibo commented on tools/windows/paddle_win.props
> +<?xml version="1.0" encoding="utf-8"?>
感觉windows props属性表文件放到cmake下 是不是有点突兀啊？

2020-09-24 03:21 UTC, jiweibo commented on tools/windows/paddle_win.props
> +<?xml version="1.0" encoding="utf-8"?>
done

2020-09-24 03:21 UTC, jiweibo commented on tools/windows/paddle_win.props
> +            <Defines></Defines>
done

2020-09-24 07:36 UTC, T8T9 commented
LGTM

2020-09-24 07:36 UTC, T8T9 approved these changes

2020-09-24 07:39 UTC, Shixiaowei02 approved these changes

2020-09-24 07:40 UTC, merged