[cherry-pick]fix optimizer init
PaddlePaddle/Paddle pull request #27994
Opened 2020-10-15 14:05 UTC by zhouwei25

### PR types

Bug fixes
### PR changes

APIs
### Describe

fix optimizer init.

2020-10-15 14:17 UTC, iclementine approved these changes
LGTM

2020-10-15 14:23 UTC, iclementine requested changes
为何 MomentumOptimizer 不在 import 里面但是在 all 里面，
以及为何 Adagrad 在 import 里面但是不在 all 里面
是不是还要改改？

2020-10-16 02:42 UTC, zhouwei25 commented
> 为何 MomentumOptimizer 不在 import 里面但是在 all 里面，
> 以及为何 Adagrad 在 import 里面但是不在 all 里面
> 是不是还要改改？

Done

2020-10-19 02:38 UTC, iclementine approved these changes
LGTM

2020-10-19 05:40 UTC, jzhang533 approved these changes
lgtm

2020-10-19 06:03 UTC, XiaoguangHu01 approved these changes
LGTM

2020-10-19 06:54 UTC, merged