add paddle.distributed.send/recv and the corresponding ops.
PaddlePaddle/Paddle pull request #28208
Opened 2020-10-22 04:03 UTC by sandyhouse

### PR types

New features
### PR changes

APIs
### Describe

add paddle.distributed.send/recv and the corresponding ops.

2020-11-11 02:28 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective_scatter_api.py
>                  shape=[10, 1000],
类型改变的原因是？

2020-11-11 02:40 UTC, sandyhouse commented on python/paddle/fluid/tests/unittests/collective_scatter_api.py
>                  shape=[10, 1000],
类型改动的原因如下：其它collective api相关单测的数据类型都是"float32", 为了规范在此处把所有collective api相关单测的数据类型都统一成float32。

2020-11-11 02:40 UTC, gongweibao requested changes
pr说明里边是否要给出程序运行的结果？

2020-11-11 02:40 UTC, gongweibao commented on paddle/fluid/operators/collective/recv_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
这个guard没有也可以？

2020-11-11 02:40 UTC, gongweibao commented on paddle/fluid/operators/collective/recv_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
if else之间的代码行数太多，能优化一下？

2020-11-11 02:40 UTC, gongweibao commented on paddle/fluid/operators/collective/send_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
同上

2020-11-11 02:40 UTC, gongweibao commented on python/paddle/distributed/collective.py
> +def send(tensor, dst=0, group=0):
dst=>dst_rank?

2020-11-11 02:40 UTC, gongweibao commented on python/paddle/distributed/collective.py
> +def send(tensor, dst=0, group=0):
group的意思没有看懂。

2020-11-11 02:40 UTC, gongweibao commented on python/paddle/distributed/collective.py
> +    op_type = 'send_v2'
之前的send_op和send_v2在python端如何区别？

2020-11-11 02:40 UTC, gongweibao commented on python/paddle/distributed/collective.py
> +def recv(tensor, src=0, group=0):
src=>src_rank?

2020-11-11 02:40 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective_scatter_api.py
>                  shape=[10, 1000],
其他的类型是否都要测试到？

2020-11-12 07:26 UTC, sandyhouse commented on paddle/fluid/operators/collective/recv_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
没有这个guard的话，NCCL_VERSION_CODE是未定义的，后面把这个和guard和NCCL_VERSION_CODE放在一起了。

2020-11-12 07:27 UTC, sandyhouse commented on paddle/fluid/operators/collective/recv_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
done.

2020-11-12 07:27 UTC, sandyhouse commented on paddle/fluid/operators/collective/send_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
done.

2020-11-12 07:27 UTC, sandyhouse commented on python/paddle/distributed/collective.py
> +def send(tensor, dst=0, group=0):
src和dst的定义是为了和其它相关api的参数统一。

2020-11-12 07:29 UTC, sandyhouse commented on python/paddle/distributed/collective.py
> +    op_type = 'send_v2'
目前，send_op没有对外暴露api，所以暂时不存在需要区分的问题。如果后续需要保留send_op对应的api，只能统一看一下是不是放在别的目录下面，或者是通过参数区分。

2020-11-12 07:29 UTC, sandyhouse commented on python/paddle/distributed/collective.py
> +def recv(tensor, src=0, group=0):
src和dst是为了保持和其它api的参数统一。

2020-11-13 04:02 UTC, gongweibao requested changes

2020-11-13 04:02 UTC, gongweibao commented on paddle/fluid/operators/collective/recv_v2_op.cu.cc
> +#if defined(PADDLE_WITH_NCCL)
其实，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/collective_helper.h#L18 已经加过guard了。再加重复了。

2020-11-13 04:02 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective_scatter_api.py
>                  shape=[10, 1000],
其他的类型要测试吗？

2021-04-23 14:36 UTC, closed without merging