Add Region Proposal Network for Faster R-CNN, including AnchorLayer, …
PaddlePaddle/Paddle pull request #2828
Opened 2017-07-12 13:04 UTC by guoshengCS

Add Region Proposal Network for Faster R-CNN, including AnchorLayer, RPNLossLayer and ProposalLayer.

There are correspondences between RPN and SSD:
 - AnchorLayer corresponding to PriorboxLayer
 - RPNLossLayer corresponding to MultiBoxLossLayer 
 - ProposalLayer corresponding to DetectionOutputLayer

2017-07-13 08:11 UTC, wanghaoshuang requested changes

2017-07-13 08:11 UTC, wanghaoshuang commented on paddle/gserver/tests/test_Proposal.cpp
> +  dataLayers[0]->getOutputValue()->copyFrom(*inputAnchor);
It seems that the size of dataLayers[*]->outputvalue is wrong.
You can use `LOG(INFO)<< "dataLayers[0] size: "<<dataLayers[0]->getOutputValue()->getElementCnt();` to check if the size  of OuptValue equals to size of inputAnchor.

2017-07-13 09:55 UTC, guoshengCS commented on paddle/gserver/tests/test_Proposal.cpp
> +  dataLayers[0]->getOutputValue()->copyFrom(*inputAnchor);
Done. I have checked it as you said, and the result shows the same size.

2019-02-01 04:47 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:47 UTC, closed without merging