adapt pad const
PaddlePaddle/Paddle pull request #28585
Opened 2020-11-12 11:34 UTC by littletomatodonkey

### PR types
New features

### PR changes
APIs

### Describe
adapt pad apis to contain the apis before.

2020-11-13 01:45 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +    if mode == "constant" and isinstance(pad, list) and len(pad) == x_dim * 2:
would be nice to add some comments about how this works

2020-11-13 01:45 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +from paddle import fluid
why?

2020-11-13 01:45 UTC, willthefrog commented on python/paddle/fluid/tests/unittests/test_pad3d_op.py
> +        if mode == "constant" and len(pad) == len(input_data.shape) * 2:
better comment in code that the padding input is different

2020-11-16 03:08 UTC, littletomatodonkey commented on python/paddle/fluid/tests/unittests/test_pad3d_op.py
> +        if mode == "constant" and len(pad) == len(input_data.shape) * 2:
代码中已添加注释，谢谢~

2020-11-16 03:08 UTC, littletomatodonkey commented on python/paddle/nn/functional/common.py
> +from paddle import fluid
已删除~

2020-11-16 03:10 UTC, littletomatodonkey commented on python/paddle/nn/functional/common.py
> +    if mode == "constant" and isinstance(pad, list) and len(pad) == x_dim * 2:
api注释中和代码中添加注释，多谢提醒

2020-11-16 05:36 UTC, willthefrog requested changes

2020-11-16 05:36 UTC, willthefrog commented on python/paddle/nn/functional/common.py
> +        print(
please remove, too much noise in stdout.

2020-11-16 06:40 UTC, littletomatodonkey commented on python/paddle/nn/functional/common.py
> +        print(
已删除，多谢~

2020-11-16 09:10 UTC, willthefrog submitted a review, later dismissed
LGTM

2020-11-17 05:57 UTC, ceci3 approved these changes

2020-11-17 05:57 UTC, merged