add_xpu_collective init
PaddlePaddle/Paddle pull request #28594
Opened 2020-11-13 04:13 UTC by vslyu

### PR types

New features
### PR changes

Others
### Describe

support multi  kunlun card training

2020-11-17 06:39 UTC, wangxicoding commented on paddle/fluid/framework/parallel_executor.cc
> +  }
漏了else

2020-11-19 09:48 UTC, gongweibao requested changes
注意else，否则容易造成很难找的问题。

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/broadcast_op_handle.cc
> +    VarHandle *out_handle = nullptr;
放到一个函数中去。

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/broadcast_op_handle_test.cc
> +/*
多余

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/op_handle_base.cc
> +#endif
else

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
> +  }
else？

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/parallel_ssa_graph_executor.cc
>          }
else？

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/details/reduce_op_handle.cc
> +      auto pre_in = pre_in_var->Get<framework::LoDTensor>();
放到一个函数中去。

2020-11-19 09:48 UTC, gongweibao commented on paddle/fluid/framework/ir/multi_devices_graph_pass/fuse_all_reduce_op_pass.cc
> +      SetCommunicationContext(places, op_handle);
else

2021-04-15 08:09 UTC, closed without merging