Clean up the redundant files and unify the launch interface.
PaddlePaddle/Paddle pull request #28928
Opened 2020-11-22 03:58 UTC by gongweibao

### PR types
New features 

### PR changes
Others

### Describe
1. There are many `launch` scripts and so clean up the redundant files.
2. Unify the launch interface to support `cpu` `gpu` `xpu`

2020-11-23 09:26 UTC, wangxicoding requested changes

2020-11-23 09:26 UTC, wangxicoding commented on python/paddle/distributed/fleet/cloud_utils.py
> +    args_node_ips:string, device_per_proc:list, args_port: int
device_mode加个说明

2020-11-23 09:26 UTC, wangxicoding commented on python/paddle/distributed/fleet/launch_utils.py
> +    OHTERS = 3
OTHERS改成UNKNOWN或者UNSUPPORT是不是更好些

2020-11-23 09:26 UTC, wangxicoding commented on python/paddle/distributed/spawn.py
> +            "`paddle.distributed.fleet.launch` instead.")
paddle.distributed.launch为啥删掉，可以把distributed.launch下的实现删掉，调用distirbuted.fleet.launch下的实现。否则用户一跑全是报没有distributed.launch

2020-11-23 09:26 UTC, wangxicoding commented on python/paddle/fluid/dygraph/parallel.py
> +    The parallel execution in dynamic mode needs to be started using ``paddle.distributed.fleet.launch``
改回paddle.distributed.launch

2020-11-23 09:28 UTC, gongweibao commented on python/paddle/distributed/spawn.py
> +            "`paddle.distributed.fleet.launch` instead.")
参数不一样了，一跑肯定出错了。

2020-11-23 09:29 UTC, gongweibao commented on python/paddle/fluid/dygraph/parallel.py
> +    The parallel execution in dynamic mode needs to be started using ``paddle.distributed.fleet.launch``
如上

2020-11-23 10:08 UTC, wangxicoding commented on python/paddle/distributed/spawn.py
> +            "`paddle.distributed.fleet.launch` instead.")
那至少运行时可以给报错信息，否则没有distributed.launch都不知道具体什么地方出问题了。。

2020-11-23 11:14 UTC, gongweibao commented on python/paddle/distributed/fleet/cloud_utils.py
> +    args_node_ips:string, device_per_proc:list, args_port: int
done

2020-11-23 11:14 UTC, gongweibao commented on python/paddle/distributed/fleet/launch_utils.py
> +    OHTERS = 3
done.

2020-11-23 11:48 UTC, gongweibao commented on python/paddle/distributed/spawn.py
> +            "`paddle.distributed.fleet.launch` instead.")
Done.

2020-11-23 11:50 UTC, gongweibao commented on python/paddle/fluid/dygraph/parallel.py
> +    The parallel execution in dynamic mode needs to be started using ``paddle.distributed.fleet.launch``
Done.

2020-11-23 12:44 UTC, wangxicoding submitted a review, later dismissed
LGTM

2020-11-24 03:00 UTC, danleifeng commented on python/paddle/distributed/cloud_utils.py
>  def get_cloud_cluster(args_node_ips, args_node_ip, args_port, selected_gpus):
paddle/distributed/fleet/cloud_utils.py 也有一个get_cloud_cluster, 这里没有用到就删除？
用到的话能把 paddle/distributed/fleet/cloud_utils.py和 paddle/distributed/cloud_utils.py 里的函数整合成一个文件么？现在有2个cloud相关的util文件，可读性不强

2020-11-24 03:00 UTC, danleifeng commented on python/paddle/distributed/utils.py
> +    if selected_gpus is None:
python/paddle/distributed/fleet/launch_utils.py 之前是复制了一份python/paddle/distributed/utils.py进行修改的，launch_utils.py里也有get_gpus()函数，辛苦检查一下重复函数，也整合一下，保留一个文件吧

2020-11-24 03:00 UTC, danleifeng commented on python/paddle/distributed/fleet/launch.py
> +        " bound to one or average number of gpus. It will be ignored if you set --gpus arguments."
看get_device_proc_info()里的实现 同时设置了gpus和nproc_per_node，也会根据gpus的个数平分nproc_per_node，和这里解释不一致。

2020-11-24 06:43 UTC, gongweibao commented on python/paddle/distributed/cloud_utils.py
>  def get_cloud_cluster(args_node_ips, args_node_ip, args_port, selected_gpus):
相似而不相同，下个pr吧。

2020-11-24 06:43 UTC, gongweibao commented on python/paddle/distributed/utils.py
> +    if selected_gpus is None:
相似而不相同，下个pr吧。

2020-11-24 06:49 UTC, gongweibao commented on python/paddle/distributed/fleet/launch.py
> +        " bound to one or average number of gpus. It will be ignored if you set --gpus arguments."
Done.

2020-11-24 09:10 UTC, raindrops2sea approved these changes, later dismissed

2020-11-24 09:17 UTC, TCChenlong approved these changes, later dismissed
LGTM

2020-11-26 01:19 UTC, TCChenlong approved these changes
LGTM

2020-11-26 01:45 UTC, raindrops2sea approved these changes

2020-11-26 02:21 UTC, kolinwei approved these changes

2020-11-26 02:35 UTC, merged

2020-12-07 15:44 UTC, shippingwang commented
把--selected_gpus 改成--gpus 对于调rc和dev模型diff的 也太烦了，跑一次改一次这种不兼容升级呀