Add eigen gru
PaddlePaddle/Paddle pull request #28990
Opened 2020-11-23 08:37 UTC by joey12300

### PR types

Bug fixes
### PR changes

OPs
### Describe

Add eigen gru

2020-11-26 02:03 UTC, ZeyuChen requested changes
整体的函数接口和函数名，变量名弱化下eigen。Eigen只是个底层计算库，不用再各种地方突显。这样会对将来计算库更换造成很大的修改成本。

2020-11-26 02:03 UTC, ZeyuChen commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +      if (OpFinalOutput::avx && (frame_size > static_cast<int>(8 - 1)) &&
这个判断里面又hard coding 8-1是为了？

2020-11-26 02:03 UTC, ZeyuChen commented on paddle/fluid/operators/rnn_op.h
> +  auto eigen_dropout_mask = EigenVector<uint8_t>::Flatten(*mask);
我觉得整体的代码不用将eigen作为前缀来描述变量。一方面冗余，第二方面没必要，就是个数据计算库，没什么特殊需要对变量进行前缀引入

2020-11-26 02:03 UTC, ZeyuChen commented on paddle/fluid/operators/rnn_op.h
> +    eigen_y.device(place) = static_cast<T>(0) * eigen_x;
就用普通的x和y来描述如何？

2020-11-26 02:03 UTC, ZeyuChen commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +  auto eigen_value_reset_gate =
是否可以去掉eigen的变量名前缀？

2020-11-26 02:03 UTC, ZeyuChen commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +  auto eigen_value_reset_gate =
再变量名这里弱化下eigen吧

2020-11-26 02:34 UTC, joey12300 commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +      if (OpFinalOutput::avx && (frame_size > static_cast<int>(8 - 1)) &&
这里的代码应该写错了，应该是`frame_size & (8 - 1)`，为了用位操作判断frame_size是否为8的倍数,这是使用avx需要满足的条件。

2020-11-26 04:01 UTC, joey12300 commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +  auto eigen_value_reset_gate =
已经将所有涉及eigen前缀的函数、变量删除eigen前缀

2020-11-27 02:04 UTC, wawltor commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +    gru_backward(context, value, grad, frame_size);
这块直接把之前的gru_backward会不会有影响？ 因为这块的测速结论还没有真正在inference确定

2020-11-27 02:13 UTC, wawltor approved these changes
LGTM

2020-11-27 03:23 UTC, joey12300 commented on paddle/fluid/operators/math/detail/gru_cpu_kernel.h
> +    gru_backward(context, value, grad, frame_size);
这是全新的函数，把avx去掉不影响以前版本GRU的使用

2020-11-27 07:42 UTC, ZeyuChen commented
LGTM

2020-11-27 07:42 UTC, ZeyuChen approved these changes
LGTM

2020-11-27 08:01 UTC, merged