Recompute Offload v1
PaddlePaddle/Paddle pull request #30111
Opened 2021-01-05 06:46 UTC by JZ-LIANG

### PR types
New features

### PR changes
OPs

### Describe
Recompute Offload version 1： memcpy & calc in same stream

2021-01-06 08:20 UTC, gongweibao requested changes

2021-01-06 08:20 UTC, gongweibao commented on paddle/fluid/operators/assign_op.cc
> +    auto kind = ctx.Attr<int>("kind");
`kind` 这个名字过于 general了，用`place_type`?

2021-01-06 08:20 UTC, gongweibao commented on paddle/fluid/operators/assign_op.h
> +  const int kind_;
Set default value?

2021-01-06 08:20 UTC, gongweibao commented on paddle/fluid/operators/fill_constant_op.cc
> +        "pinned",
`place_type`?

2021-01-06 08:20 UTC, gongweibao commented on python/paddle/fluid/optimizer.py
> +        total_op = len(self.block.ops)
Add more comments?

2021-01-06 08:20 UTC, gongweibao commented on python/paddle/fluid/optimizer.py
> +        for i, op in enumerate(self.block.ops[self.fw_strart_op_idx:
This function is too long, split it?

2021-01-06 08:20 UTC, gongweibao commented on python/paddle/fluid/optimizer.py
> +                # self.checkpoint_name2load_name[checkpoint_var.name] = offload_var_name
Clean up this?

2021-01-07 06:13 UTC, JZ-LIANG commented on paddle/fluid/operators/assign_op.cc
> +    auto kind = ctx.Attr<int>("kind");
done

2021-01-07 06:13 UTC, JZ-LIANG commented on paddle/fluid/operators/fill_constant_op.cc
> +        "pinned",
done

2021-01-07 06:13 UTC, JZ-LIANG commented on python/paddle/fluid/optimizer.py
> +        total_op = len(self.block.ops)
done

2022-01-11 06:52 UTC, closed without merging