Added support for inference using quantization aware trained dygraph
PaddlePaddle/Paddle pull request #30288
Opened 2021-01-11 06:04 UTC by alncat

### PR types

Others
### PR changes

Others
### Describe

This PR added support for paddle inference using quantization aware trained dynamic graph. It included a new pass which delete fake_quantize_dequantize ops after the weights. It also modified conv2d_elementwise_add_fuse_pass and fc_fuse_pass to set the out_thresholds of conv2d or fc ops.

2021-01-11 12:37 UTC, cryoco commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        quantized_weight_data[j] /= weight_scale[0];
是否可能会除零？

2021-01-11 12:37 UTC, cryoco commented on paddle/fluid/inference/tensorrt/convert/conv2d_op.cc
> +    auto* weight_tensor = scope.FindVar(op_desc.Input("Bias").front());
这里变量名是否应该为`bias_tensor`？

2021-01-12 07:34 UTC, shangzhizhou reviewed
需补充单测

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/inference/tensorrt/convert/fc_op.cc
> +#if IS_TRT_VERSION_GE(5000)
TRT小于6.0不支持了，直接tensorRT的cmake文件里判断下把。

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/inference/tensorrt/convert/fc_op.cc
> +      if (enable_int8) {
TRT小于6.0不支持了，直接tensorRT的cmake文件里判断下把。

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        arg_name = name_m.first;
`break` ?

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      }
if (dequant_type == "fake_channel_wise_quantize_dequantize_abs_max") {
}
else 报错

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +              weight_scale[j % w_dims[1]] != 0, 1,
严格使用bool类型
1 --> true

2021-01-12 07:34 UTC, shangzhizhou commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      }
同上，加else

2021-01-12 08:03 UTC, Superjomn requested changes

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.cc
> +    auto elementwise_add_op_desc = elementwise_add_op->Op();
这个是指针还是元素？ 
指针的话，会写 `auto*` 表示复制不耗时； 如果是元素会避免拷贝
另外，语句比较短且不耗时的话，可以不单独拷贝值

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.cc
> +    auto out_threshold_attr =
这个也是一样，如果有 auto， 如果是简单的类型，比如 `int`, `string` 啥的，最好避免写auto，不然没法判断拷贝的代价是否可控

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +    CHECK(arg_name.size() > 0) << "can not find the input "
PADDLE_ENFORCE_GT

这里应该都是用 PADDLE_ENFORCE_XXX 相关的check，paddle内部会有异常管理。

GT, GE, LT, LE, EQ 等等写清楚，报错信息会更详细

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          scope->FindVar(scales_name[0])->Get<LoDTensor>();
FindVar 可能是 null
需要先check not null, 之后再获取值，否则会 segmentfault

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      PADDLE_ENFORCE_EQ(
PADDLE_ENFORCE() ? 

不需要 == true

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          scope->FindVar(scale_name)->Get<LoDTensor>();
同上

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        scope->FindVar(quant_dequant_op_x->Name())->GetMutable<LoDTensor>();
全局所有 FindVar 都必须先 check 非空，确保其存在，之后再获取其数据

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +                static_cast<size_t>(w_dims[1]), weight_scale.size()));
size_t 是不是对应 `%zu` 不是 `%d` ？

https://www.tutorialspoint.com/what-is-the-correct-way-to-use-printf-to-print-a-size-t-in-c-cplusplus

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          PADDLE_ENFORCE_EQ(weight_scale[(j / inner_size) % w_dims[1]] != 0, 1,
PADDLE_ENFORCE ?

不需要 != 0

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/fc_fuse_pass.cc
> +    auto elementwise_add_op_desc = elementwise_add->Op();
同上

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/fc_fuse_pass.cc
> +    auto out_threshold_attr =
简单类型，不需要用auto，写明有助于读代码

全局其他也是

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +    flag = flag && !transpose_X && !transpose_Y &&
flag 这个后面很多地方用，名字可以写的更具体写

比如 pattern_actived, 类似这样，true 的话就是 active ，否则就是 inactive

flag true 和false 没啥意义

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +    bool flag = true;
这里加下注释，解释下，为啥要有这么多规则约束 flag

这是PR目前是一个bugfix，我们只能针对目前有限的case 做优化，类似这样的背景注释写下，以便于别人看到这块代码能对大概逻辑有一个认识，知道需要进一步去cover更多场景

其他地方，有类似奇怪的限制，也最好注释写下

2021-01-12 08:03 UTC, Superjomn commented on paddle/fluid/inference/api/analysis_config.cc
> +          (pass == "conv_bn_fuse_pass")) {  // || pass == "fc_fuse_pass")) {
无用代码可以删除

2021-01-12 12:09 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        quantized_weight_data[j] /= weight_scale[0];
Done.

2021-01-12 12:09 UTC, alncat commented on paddle/fluid/inference/tensorrt/convert/conv2d_op.cc
> +    auto* weight_tensor = scope.FindVar(op_desc.Input("Bias").front());
Done.

2021-01-12 12:09 UTC, alncat commented on paddle/fluid/inference/tensorrt/convert/fc_op.cc
> +#if IS_TRT_VERSION_GE(5000)
Removed version check macro. Done.

2021-01-12 12:10 UTC, alncat commented on paddle/fluid/inference/tensorrt/convert/fc_op.cc
> +      if (enable_int8) {
Done.

2021-01-12 12:10 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        arg_name = name_m.first;
Done.

2021-01-12 12:10 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      }
Done.

2021-01-12 12:11 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +              weight_scale[j % w_dims[1]] != 0, 1,
Changed to PADDLE_ENFORCE. Done.

2021-01-12 12:11 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      }
Done.

2021-01-12 12:12 UTC, alncat commented on paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.cc
> +    auto elementwise_add_op_desc = elementwise_add_op->Op();
已修改成auto*.

2021-01-12 12:13 UTC, alncat commented on paddle/fluid/framework/ir/conv_elementwise_add_fuse_pass.cc
> +    auto out_threshold_attr =
因为这个类型是Attribute，实际上是boost::variant类型, 比较复杂，所以我选择了使用auto.

2021-01-12 12:13 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +    CHECK(arg_name.size() > 0) << "can not find the input "
Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          scope->FindVar(scales_name[0])->Get<LoDTensor>();
加入了相应的PADDLE_ENFORCE信息。Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +      PADDLE_ENFORCE_EQ(
Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          scope->FindVar(scale_name)->Get<LoDTensor>();
Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +        scope->FindVar(quant_dequant_op_x->Name())->GetMutable<LoDTensor>();
加入了相应的PADDLE_ENFORCE信息。Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +                static_cast<size_t>(w_dims[1]), weight_scale.size()));
Done.

2021-01-12 12:14 UTC, alncat commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          PADDLE_ENFORCE_EQ(weight_scale[(j / inner_size) % w_dims[1]] != 0, 1,
Done.

2021-01-12 12:15 UTC, alncat commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +    flag = flag && !transpose_X && !transpose_Y &&
改成了pattern_found. Done.

2021-01-12 12:15 UTC, alncat commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +    bool flag = true;
Done.

2021-01-12 12:15 UTC, alncat commented on paddle/fluid/inference/api/analysis_config.cc
> +          (pass == "conv_bn_fuse_pass")) {  // || pass == "fc_fuse_pass")) {
Done.

2021-01-12 12:33 UTC, shangzhizhou submitted a review, later dismissed
LGTM

2021-01-13 02:24 UTC, Superjomn commented on paddle/fluid/framework/ir/delete_quant_dequant_filter_op_pass.cc
> +          scope->FindVar(scales_name[0])->Get<LoDTensor>();
这里 FindVar 两次了，每次都是耗时。

为啥不

```
auto* var = scope->FindVar(xxx);
PADDLE_ENFORCE(var);
var->Get<LodTensor>();
```

FindVar 要check有很多地方会用到。 

你可以在 scope.h 里面增加一个 GetVar(xxx) 里面自带 FindVar 和 PADDLE_ENFORCE

最后代码可以直接

```c++
scope->GetVar(xxx)->Get<LoDTensor>();
```

2021-01-13 07:15 UTC, Superjomn approved these changes
LGTM

2021-01-13 07:31 UTC, luotao1 approved these changes
LGTM for scope.h

2021-01-13 10:58 UTC, merged