test=develop, add distributed_infer
PaddlePaddle/Paddle pull request #30300
Opened 2021-01-11 07:28 UTC by 123malin

### PR types

Others

### PR changes

Others

### Describe

Add Distributed Infer

2021-01-11 08:51 UTC, seiriosPlus submitted a review, later dismissed
LGTM

2021-01-12 12:26 UTC, chenwhql submitted a review, later dismissed
LGTM for PADDLE_ENFORCE using

2021-01-12 12:46 UTC, chalsliu approved these changes, later dismissed

2021-01-12 13:19 UTC, kolinwei submitted a review, later dismissed

2021-01-12 14:05 UTC, seiriosPlus submitted a review, later dismissed
LGTM

2021-01-13 03:40 UTC, raindrops2sea commented
> ### Describe
> Add Distributed Infer and fix fleet.metrics
请描述的更具体一些。

2021-01-13 05:39 UTC, raindrops2sea requested changes

2021-01-13 05:39 UTC, raindrops2sea commented on python/paddle/distributed/fleet/metrics/metric.py
>  from paddle.fluid.framework import Variable
新增代码整体请调用2.0API体系，包括注释里的示例。其他文件也同样。

2021-01-13 05:39 UTC, raindrops2sea commented on python/paddle/distributed/fleet/metrics/metric.py
>          util = fleet.util
直接写全路径不要再额外一行import了吧。

2021-01-14 02:44 UTC, raindrops2sea approved these changes
LGTM

2021-01-14 03:02 UTC, chenwhql approved these changes
LGTM for PADDLE_ENFORCE

2021-01-14 03:03 UTC, seiriosPlus approved these changes

2021-01-14 03:08 UTC, chalsliu approved these changes

2021-01-14 03:11 UTC, merged