Ascendrc
PaddlePaddle/Paddle pull request #31065
Opened 2021-02-19 14:55 UTC by xymyeah

PR types
New features

PR changes
Others

Describe
delete ascend_npus parameter

2021-02-24 11:58 UTC, gongweibao requested changes

2021-02-24 11:58 UTC, gongweibao commented on python/paddle/distributed/fleet/ascend_utils.py
> -                    devices_per_proc=None,
为什么删了这个？

2021-02-24 11:58 UTC, gongweibao commented on python/paddle/distributed/fleet/launch_utils.py
> -def get_ascend_npus(npus):
这个可以用来做检查？

2021-02-25 12:36 UTC, xymyeah commented on python/paddle/distributed/fleet/ascend_utils.py
> -                    devices_per_proc=None,
这个是针对ascend的处理流程，不会影响到其他的

2021-02-25 12:37 UTC, xymyeah commented on python/paddle/distributed/fleet/launch_utils.py
> -def get_ascend_npus(npus):
这里是通过ascend的api获取的机器上的所有设备，可能跟当前用的npu个数不一致，所以去掉了

2021-02-25 12:54 UTC, merged

2021-02-25 12:54 UTC, gongweibao commented
需要补充对应的单测!

2021-02-26 05:21 UTC, xymyeah commented
> 需要补充对应的单测!

done
https://github.com/PaddlePaddle/Paddle/pull/31249