[Kunlun]multi xpu dygraph performance optimization
PaddlePaddle/Paddle pull request #31130
Opened 2021-02-22 15:17 UTC by vslyu

### PR types

 Performance optimization
### PR changes

Others
### Describe

multi xpu dygraph performance optimization

2021-02-23 08:58 UTC, wangxicoding requested changes

2021-02-23 08:58 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +    multi_device_op_count_ = 0;
这个放在Reducer构造函数中吧

2021-02-23 08:58 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +      // cnt -= 1; // lock
delete

2021-02-23 08:58 UTC, wangxicoding commented on python/paddle/distributed/spawn.py
> +        else:
elif device == 'xpu'

2021-02-23 09:14 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.h
> +  ::ThreadPool multi_device_op_pool_;
名字就改成上面的comm_pool，或者想一个更好的。再加些注释，这个线程用于调度通信allreduce

2021-02-23 09:14 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.h
> +  uint32_t multi_device_op_count_;
这个也改一下，comm_op_count，或者想个更好的

2021-02-23 09:32 UTC, QingshuChen commented on paddle/fluid/imperative/reducer.cc
> +    // For CUDA or XPU, compute_stream --event--> comm_stream.
event也加进去了吗？

2021-02-23 09:36 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +    // For CUDA or XPU, compute_stream --event--> comm_stream.
没有，通信库现在还是阻塞的，加进去也没有效果

2021-02-23 15:04 UTC, vslyu commented on paddle/fluid/imperative/reducer.h
> +  uint32_t multi_device_op_count_;
just  comm_op_count_?

2021-02-23 15:04 UTC, vslyu commented on python/paddle/distributed/spawn.py
> +        else:
done.

2021-02-23 15:04 UTC, vslyu commented on paddle/fluid/imperative/reducer.cc
> +      // cnt -= 1; // lock
done.

2021-02-23 15:04 UTC, vslyu commented on paddle/fluid/imperative/reducer.cc
> +    multi_device_op_count_ = 0;
done.

2021-02-23 15:33 UTC, vslyu commented on paddle/fluid/imperative/reducer.h
> +  ::ThreadPool multi_device_op_pool_;
just comm_pool_?

2021-02-24 02:47 UTC, wangxicoding requested changes

2021-02-24 02:47 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +#else
GPU的WaitCompute丟了

2021-03-02 02:16 UTC, chenwhql commented on python/paddle/distributed/spawn.py
> +        args.selected_gpus = options.get('xpus', None)
xpu也使用的是`args.selected_gpus`吗？感觉代码读起来有点乱

2021-03-02 02:16 UTC, chenwhql commented on python/paddle/distributed/spawn.py
> +                    "The number of selected gpus(%s) is not equal to "
`gpus` -> `xpus`?

2021-03-02 02:16 UTC, chenwhql commented on python/paddle/distributed/spawn.py
> +                    "correct `nprocs` and `gpus` arguments are passed." %
`gpus` -> `xpus`?

2021-03-02 02:16 UTC, chenwhql commented on python/paddle/distributed/spawn.py
> +                    raise ValueError("The selected gpu card %s cannot found in "
`gpu` -> `xpu`?

2021-03-02 08:25 UTC, wangxicoding requested changes

2021-03-02 08:25 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +      parallel_ctx_->WaitCompute(run_order);
SetXPUDevice呢

2021-03-02 08:58 UTC, vslyu commented on paddle/fluid/imperative/reducer.cc
> +#else
done, add it again.

2021-03-02 08:58 UTC, vslyu commented on python/paddle/distributed/spawn.py
> +                    "correct `nprocs` and `gpus` arguments are passed." %
done.

2021-03-02 08:58 UTC, vslyu commented on python/paddle/distributed/spawn.py
> +        args.selected_gpus = options.get('xpus', None)
Done, uniformally define args.selected_devices for multi gpus training or multi xpus training, delete args.selected_gpus.

2021-03-02 08:58 UTC, vslyu commented on python/paddle/distributed/spawn.py
> +                    raise ValueError("The selected gpu card %s cannot found in "
done.

2021-03-02 09:10 UTC, hutuxian commented on paddle/fluid/imperative/reducer.cc
> +      comm_op_count_(0) {
only wrap the added code

2021-03-02 14:52 UTC, vslyu commented on paddle/fluid/imperative/reducer.cc
> +      parallel_ctx_->WaitCompute(run_order);
done, add it.

2021-03-02 14:52 UTC, vslyu commented on paddle/fluid/imperative/reducer.cc
> +      comm_op_count_(0) {
done.

2021-03-03 03:45 UTC, ForFishes commented on paddle/fluid/imperative/reducer.cc
> +
这里为什么需要拿place，place不是已经有了吗？这里涉及gpu和xpu的混合通信？

2021-03-03 03:55 UTC, ForFishes commented on paddle/fluid/imperative/reducer.cc
> +void Reducer::FusedAllReduceSchedule(int run_order, Group group) {
换成常量引用，不然影响性能。

2021-03-03 04:03 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +
reducer.h 里已经有 _place了，不用获取了。

2021-03-03 04:03 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
>      parallel_ctx_->WaitCompute(run_order);
这个后续试一下WaitCompute放到这里，还是放到allreduce里面的性能好

2021-03-03 04:03 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +    if (paddle::platform::is_xpu_place(place)) {
可以不用判断place了，直接BKCL宏定义线程调度。其余正常调度

2021-03-03 04:03 UTC, wangxicoding commented on paddle/fluid/imperative/reducer.cc
> +        FusedAllReduceSchedule(run_order, group);
线程调度，记个TOTO，后续加上try cache

2021-03-03 07:18 UTC, Xreki approved these changes, later dismissed
LGTM for the modification of compiler.py

2021-03-03 08:55 UTC, wangxicoding submitted a review, later dismissed
LGTM

2021-03-04 12:47 UTC, ForFishes approved these changes
LGTM

2021-03-04 12:52 UTC, wangxicoding approved these changes

2021-03-04 13:19 UTC, Xreki approved these changes

2021-03-04 13:33 UTC, luotao1 approved these changes

2021-03-05 03:18 UTC, merged