[NPU] npu support `transpose`
PaddlePaddle/Paddle pull request #31486
Opened 2021-03-09 03:26 UTC by Meiyim

### PR types
New features
### PR changes
OPs

### Describe

+ support npu kernel for `transpose`

2021-03-09 03:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31486) before we can accept your contribution.<br/><hr/>**Paddle CI_MAC** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=31486) it.</sub>

2021-03-17 05:10 UTC, zhiqiu commented on paddle/fluid/operators/transpose_op_npu.cc
> +        //.Wait();
Remove usunsed code.

2021-03-17 05:38 UTC, Meiyim commented on paddle/fluid/operators/transpose_op_npu.cc
> +        //.Wait();
removed

2021-03-17 05:44 UTC, liym27 requested changes

2021-03-17 05:44 UTC, liym27 commented on python/paddle/fluid/tests/unittests/npu/test_transpose_op_npu.py
> +        self.dtype = np.float32
Add a unittest for `float16`

2021-03-17 09:47 UTC, Meiyim commented on python/paddle/fluid/tests/unittests/npu/test_transpose_op_npu.py
> +        self.dtype = np.float32
added

2021-03-17 11:11 UTC, liym27 commented on python/paddle/fluid/tests/unittests/npu/test_transpose_op_npu.py
> +
TestTransposeOpFP16 中没有测试，可以参考 pow 单测写。另外需要提供调用 fp16 npu kernel 的日志截图。

2021-03-17 12:10 UTC, Meiyim commented on python/paddle/fluid/tests/unittests/npu/test_transpose_op_npu.py
> +
<img width="1440" alt="infoflow 2021-03-17 20-09-41" src="https://user-images.githubusercontent.com/10281949/111465195-bc403e80-875c-11eb-9fec-4127f85ae153.png">

2021-03-17 12:45 UTC, liym27 approved these changes
LGTM

2021-03-17 12:45 UTC, merged