NPU Mean Op
PaddlePaddle/Paddle pull request #31562
Opened 2021-03-11 14:49 UTC by OleNet

### PR types

### PR changes

### Describe

2021-03-15 11:43 UTC, OleNet commented
![image](https://user-images.githubusercontent.com/3206718/111148115-37232100-85c6-11eb-840b-2e6004af8ce3.png)
![image](https://user-images.githubusercontent.com/3206718/111148404-8d905f80-85c6-11eb-8d23-e216c21b2d95.png)

2021-03-16 07:04 UTC, liym27 requested changes
1. 将单测验证截图，移到 PR 描述中。
2. 补充 npu kernel 被调用的截图，否则无法确定 npu kernel 是否被调用。

2021-03-16 10:56 UTC, zhiqiu approved these changes
LGTM

2021-03-16 10:57 UTC, merged

2021-03-16 10:58 UTC, liym27 commented on paddle/fluid/operators/mean_op_npu.cc
> +    out->Resize(framework::make_ddim(out_dims));
Don't need to resize tensor `out`, which has been set size in `InferShape` .

2021-03-16 10:58 UTC, liym27 commented on paddle/fluid/operators/mean_op_npu.cc
> +    reduced_out.mutable_data<T>(ctx.GetPlace());
It seems that this tensor `reduced_out` has never been used.

2021-03-16 10:58 UTC, liym27 commented on paddle/fluid/operators/mean_op_npu.cc
> +                  {"axes", axes}};
According to `MeanParser`, `axes` should be  an empty vector.

2021-03-16 10:59 UTC, pangyoki commented on paddle/fluid/operators/mean_op_npu.cc
> +    std::vector<int64_t> reduced_dout_dims;
`reduced_dout_dims`这个变量有什么用吗？

2021-03-16 10:59 UTC, pangyoki commented on paddle/fluid/operators/mean_op_npu.cc
> +    out->Resize(framework::make_ddim(out_dims));
InferShape阶段，输出的shape已经设置为{1}了，不需要重复设置

2021-03-16 11:23 UTC, liym27 reviewed
For `MeanGradNPUKernel`, please better to call ascend ops according to `MeanGradParser`  https://github.com/PaddlePaddle/Paddle/blob/ascendrc/python/paddle/distributed/fleet/meta_optimizers/ascend/ascend_parser.py#L2048

2021-03-16 11:23 UTC, liym27 commented on paddle/fluid/operators/mean_op_npu.cc
> +    ones.mutable_data<T>(context.GetPlace());
lines 84 - 89, can be replaced by one line:
```
ones.mutable_data<T>(IG->dims(), context.GetPlace());
```

2021-03-16 11:23 UTC, liym27 commented on paddle/fluid/operators/mean_op_npu.cc
> +    runner_mul_2.Run(stream);
Lines 103-112, why not use only one "Mul", which input are "mean_tensor" and "*grad", output is "*IG"?