add Increment op
PaddlePaddle/Paddle pull request #31563
Opened 2021-03-11 14:51 UTC by OleNet

### PR types

### PR changes

### Describe

2021-03-15 11:58 UTC, OleNet commented
![image](https://user-images.githubusercontent.com/3206718/111149963-7c485280-85c8-11eb-8da9-7cd451b897f2.png)
![image](https://user-images.githubusercontent.com/3206718/111150050-97b35d80-85c8-11eb-88dd-3c5a7e624f6e.png)

2021-03-16 07:05 UTC, liym27 requested changes
1. 将单测验证截图，移到 PR 描述中。
2. 补充 npu kernel 被调用的截图，否则无法确定 npu kernel 是否被调用。

2021-03-16 10:32 UTC, liym27 commented on paddle/fluid/operators/increment_op_npu.cc
> +    std::cout << "step: " << step << std::endl;
delete line 43

2021-03-16 10:32 UTC, liym27 commented on python/paddle/fluid/tests/unittests/npu/test_increment_op_npu.py
> +
1. 需要加单测测试一下 python API `paddle.increment`  的正确性
2. 检测 API `paddle.increment` 的输入输出是同一个变量。因为`increment` 是一个 inplace 的操作，即 输入、输出是同一个变量。

2021-03-17 06:39 UTC, liym27 approved these changes
LGTM

2021-03-17 07:27 UTC, merged