Log softmax temorary PR
PaddlePaddle/Paddle pull request #31630
Opened 2021-03-15 07:20 UTC by AshburnLee

### PR types

Performance optimization
### PR changes

OPs
### Describe

Log softmax temorary PR

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> -// Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
这个文件不是今年新增的，不用改copyright吧。

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +                        ops::LogSoftmaxKernel<plat::CUDADeviceContext, double>);
为什么把float16类型去掉了？

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +__device__ __forceinline__ void warp_reduce_sum(T* sum) {
函数名应准确地表达函数的功能，函数命名也需要符合[Google C++代码风格](https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/naming/#id6)。`warp_reduce_sum` -> `BatchWarpReduceSum`

下同

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T, int WARP_BATCH, int WARP_SIZE_SOFTMAX>
- 模板中变量名用`AxxBxx`这种驼峰式命名方式。
- 这里WARP_BATCH应该是说一个warp负责计算几个batch吧，那不如直接叫`NumBatch`或`BatchSize`

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +int log2_ceil(int value);
函数名除一些类里面的setter、getter函数外，都采用`AxxBxx`这种命名方式，看一下[Google C++代码规范](https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/naming/#id6)

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  constexpr int WARP_BATCH = (next_power_of_two <= 128) ? 2 : 1;
常量变量名命名方式需统一，且符合[Google C++编码规范](https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/naming/#id6)里面的常量变量命名规范。

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  assert(softmax_elements >= 0 && softmax_elements <= 1024);
检查用`PADDLE_ENFORCE_XXX`。

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    int along_axis = (axis < 0) ? axis + X->dims().size() : axis;
CanonicalAxis已经对axis做了换算了。

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +      inner_size *= X->dims()[i];
SizeToAxis和SizeFromAxis可以分别计算outer_size和inner_size

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +struct LogSoftmaxCUDAFunctor {
感觉这一层的封装没有必要。

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    auto* Out = context.Output<framework::Tensor>("Out");
变量名命名：`axx_bxx`

2021-03-17 07:50 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +void LogSoftmaxForwardAxisLast(T* dst, const T* src, int softmax_elements,
这个函数主要的功能是启动CUDA Kernel，所以可以叫`LaunchLogSoftmaxForwardForLastAxis`。

2021-03-17 07:51 UTC, Xreki commented
PR title和描述都再补充详细一点。

2021-03-17 08:04 UTC, xingfeng01 commented on paddle/fluid/operators/log_softmax_op.cu
> +      sum[i] += std::exp(elements[i][it] - max_value[i]);
float16的时候会有问题吗？

2021-03-17 08:08 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +      sum[i] += std::exp(elements[i][it] - max_value[i]);
是因为__shfl_xor_sync&__shfl_xor不支持fp16。应该是可以处理的

2021-03-17 13:59 UTC, AshburnLee reviewed
已经按照review意见做了修改

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +                        ops::LogSoftmaxKernel<plat::CUDADeviceContext, double>);
Done，支持了float16。

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +      sum[i] += std::exp(elements[i][it] - max_value[i]);
Done，已处理。

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> -// Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +int log2_ceil(int value);
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T, int WARP_BATCH, int WARP_SIZE_SOFTMAX>
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +__device__ __forceinline__ void warp_reduce_sum(T* sum) {
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +void LogSoftmaxForwardAxisLast(T* dst, const T* src, int softmax_elements,
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  assert(softmax_elements >= 0 && softmax_elements <= 1024);
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    int along_axis = (axis < 0) ? axis + X->dims().size() : axis;
Done。已删除

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +      inner_size *= X->dims()[i];
outer_size可以用SizeToAxis()得到；inner_size的计算与SizeFromAxis()有差别。这里应该调SizeOutAxis()。但是SizeOutAxis()定义在其他.cu文件中，在该文件中不能直接调用。（nvcc 没有开启 --relocatable-device-code=true --compile，开启后可以调用）。

所以保留inner_size，用SizeToAxis()获得outer_size。

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  constexpr int WARP_BATCH = (next_power_of_two <= 128) ? 2 : 1;
Done.

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    auto* Out = context.Output<framework::Tensor>("Out");
变量名都改为了这种形式。

2021-03-17 13:59 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +struct LogSoftmaxCUDAFunctor {
Done.

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    WarpLogSoftmaxForward<T, double, L2E><<<blocks, threads, 0>>>(         \
不要都用double，double速度会很慢。

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +            static_cast<double>(src[i * element_count + it * kernel_warp_size]);
不要都用double

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    if (i >= local_batches) break;
这种if语句分行写，并且都加上{}。

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T, typename AccT, int log2_elements>
模板里面的变量其实是常量，命名用`AxxBxx`形式，以跟函数里面的变量区分。

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    auto* Out = context.Output<framework::Tensor>("Out");
X、Out还没改。

2021-03-18 04:04 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    outer_size = SizeToAxis(axis, X->dims());
191和192可以合成1行。

2021-03-23 02:42 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    outer_size = SizeToAxis(axis, X->dims());
Done.

2021-03-23 02:42 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T, typename AccT, int log2_elements>
Done.

2021-03-23 02:42 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    if (i >= local_batches) break;
Done.

2021-03-23 04:33 UTC, qili93 requested changes

2021-03-23 04:33 UTC, qili93 commented on paddle/fluid/operators/log_softmax_op.cu
> +#include <cuda_runtime.h>
HIP上会找不到cuda_runtime.h，可以试试看删掉这个头文件应该也可以运行，或者写成

```c++
#ifdef __HIPCC__
#include <hip/hip_runtime.h>
#else
#include <cuda_runtime.h>
#endif

```

2021-03-23 05:54 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +#include <cuda_runtime.h>
Done.

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    if (inner_size == 1 && dim_size <= 1024 && dim_size * sizeof(T) <= 4096) {
if里面为什么要加`&& dim_size * sizeof(T) <= 4096`这个判断呢？不支持double吗？

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +__device__ __forceinline__ void ReduceSumForWarpBatch(T &sum) {
C++一般都传`const T&`，不推荐这种方式修改传进来的实参。另外这个函数既然去掉了计算batch的循环，那函数名就应该去掉batch。

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +        dst, src, outer_size, dim_size, dim_size);                           \
为什么要传2个dim_size？

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int blocks = (outer_size + warps_per_block - 1) / warps_per_block;
对于输入[N, 32]和[N, 128]，kernel_warp_size=32，warps_per_block=4，这2种情况都是一个线程block分成4组，每组线程（即一个warp）计算1个batch？

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +__global__ void ComputeForwardInWarp(T *dst, const T *src, int batch_size,
函数名还是要体现功能，LogSoftmaxForwardXxx

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  if (effective_warp_id > 1) effective_warp_id = 1;
这2行代码的逻辑有些怪异，不易于理解。

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int warp_id = blockDim.y * blockIdx.x + threadIdx.y;
应该是global_batch_id。

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +      elements[it] = static_cast<double>(
double -> AccT

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T>
模板设置：
```cpp
template <typename T, typename AccT>
void LaunchSoftmaxForwardForLastAxis(....) {
    ...
}
```

外层调用：`LaunchSoftmaxForwardForLastAxis<T, MPTypeTrait<T>::Type>(...)`，即可解决模板调用中的double。MPTypeTrait的定义见：
https://github.com/PaddlePaddle/Paddle/blob/3f66e7deab7c2ddec30ffe015bc4597af48f68ae/paddle/fluid/operators/amp/fp16_type_traits.h#L23-L33

2021-03-23 14:08 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +    PADDLE_ENFORCE_GT(x->numel(), 0, platform::errors::InvalidArgument(
这种检查不需要，InferShape中的检查一般能覆盖到。

2021-03-24 07:22 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    if (inner_size == 1 && dim_size <= 1024 && dim_size * sizeof(T) <= 4096) {
支持double。当把`&& dim_size * sizeof(T) <= 4096`删去，可以正确执行，但是一致性的diff从0.0 变为1.0728e-6（atol=1.00e-6）。

` && dim_size <= 1024`是必要的。

当outer_size=128，dim_size=1024时，有config<<<32, (32, 4)>>>，warp_iter=32，正确执行。
当outer_size=128，dim_size=**1025**时，有config<<<32, (32, 4)>>>，warp_iter=64，不能得到结果。

warp_iter表示一个thread使用到的寄存器，应该是warp_iter=64超过硬件限制了。

2021-03-24 07:22 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +__device__ __forceinline__ void ReduceSumForWarpBatch(T &sum) {
将两个WarpReduce函数的返回值从void改为T。

其实可以调用math_cuda_utils.h的函数，只是其中的函数WARP_SIZE为常量32，但这里的WARP_SIZE不一定是32。

改名Done.

2021-03-24 07:22 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +        dst, src, outer_size, dim_size, dim_size);                           \
一个就够，Done.

2021-03-24 07:22 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  int blocks = (outer_size + warps_per_block - 1) / warps_per_block;
每组线程确实计算1个batch。

当N确定，通过观察configure`<<<blocks, threads>>>`随dim_size变化的变化，可以发现：
当dim_size>16时，`threads`始终为（32，4），**变化的是`blocks`，和`warp_iter`，batch是1**。

假设N=128，变量有以下变化

- 对于输入[N, 32]：`dim_size: 32, kernel_warp_size: 32, warp_iter: 1, warp_batch: 1, config<<<4, (32, 4)>>>, numElem: 512 numThreads: 512`

- 对于输入[N, 128]: `dim_size: 128, kernel_warp_size: 32, warp_iter: 4, warp_batch: 1, config<<<4, (32, 4)>>>, numElem: 2048 numThreads: 2048`

这里numThreads表示线程数及其循环次数。

确认是计算1个batch。

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +__global__ void ComputeForwardInWarp(T *dst, const T *src, int batch_size,
Done.

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  if (effective_warp_id > 1) effective_warp_id = 1;
**最终目**的是区分寄存器中是写入待处理数值还是负无穷。

解释一下：
batch_size: 即outer_size样本个数。
warp_id: grid中warp的id。（需要改成**global_warp_id**）

想象这种情形，batch_size=6（6个样本），2个block，4warp/block。

由global_warp_id的计算得到8个warp的id是0~7。8个中的前6个有效 warp处理6个样本。这里**为了区分有效warp和无效warp，才做了上述两步操作**：

- `int effective_warp_id = batch_size - warp_id`: 6-(0,1,2,3,4,5,6,7)=(6,5,4,3,2,1,0,-1)
- `if (effective_warp_id > 1) effective_warp_id = 1`: (6,5,4,3,2,1,0,-1)->(1,1,1,1,1,1,0,-1)。即有效warp的id都为1，无效的不为1。

紧接着根据`int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;` 得到有效warp对应的element_count为实际元素个数（即dim_size），无效的设为0。

再接着根据`if (element_index < effective_element_count) {}`，判断是写入实际值呢还是负无穷。0不会大于element_index，此情况下寄存器（无效warp的）中写入负无穷；否则写入待处理值。

所以说这两句最终目的是将无效warp对应的寄存器值写为负无穷，有效工作的warp对应寄存器写入实际数值。

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  int warp_id = blockDim.y * blockIdx.x + threadIdx.y;
根据上一条回复，我觉得改为global_warp_id 更合适。

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +      elements[it] = static_cast<double>(
Done.

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +template <typename T>
Done. 谢谢提供的解决方案！

2021-03-24 07:23 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +    PADDLE_ENFORCE_GT(x->numel(), 0, platform::errors::InvalidArgument(
Done.

2021-04-07 13:53 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +        T, AccT, near_greater_power_of_two><<<blocks, threads, 0>>>( \
CUDA Kernel启动要传入stream。

2021-04-07 13:53 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int global_warp_id = blockDim.y * blockIdx.x + threadIdx.y;
- 输入为`[batch_size, element_count]`，near_greater_power_of_two代表了elemen_count。所以这个kernel是使用kernel_warp_size个线程来计算一行，所以global_warp_id也就是全局的行号。

- 另外，kernel_warp_size也就是blockDim.x。

- 在CUDA里面，warp是硬件层面的概念，这里说的一个warp其实是一行，概念上容易引起困惑。

2021-04-07 13:53 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;
这一行改成`int effective_element_count = (global_warp_id < batch_size) ? 0 : element_count;`，可删除L68 ~ L71。

2021-04-07 13:53 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  max_value = elements[0];
L92和L93可以合并成一行。

2021-04-07 13:53 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +          elements[it] - max_value - sum;
写回数据使用`static_cast`显式转换成T类型吧。

2021-04-08 06:48 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +        T, AccT, near_greater_power_of_two><<<blocks, threads, 0>>>( \
Done.

2021-04-08 08:10 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;
对于上次回复review给出的那种情形，这种修改可行。但似乎不实用于所有情况。测试结果有些单测不能通过。还保持原状吧。

2021-04-08 08:10 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  max_value = elements[0];
Done.

2021-04-08 08:10 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +          elements[it] - max_value - sum;
Done.

2021-04-08 12:33 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  int global_warp_id = blockDim.y * blockIdx.x + threadIdx.y;
- 是的。global_warp_id是全局的行号。
- 是的。
- 一个warp处理一行，所以这个global_warp_id 改名为 batch_id。

2021-04-09 01:21 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;
不通过的单测是哪种情况？

2021-04-10 01:31 UTC, Xreki approved these changes
LGTM

2021-04-10 03:41 UTC, qili93 approved these changes
LGTM

2021-04-10 05:01 UTC, merged

2021-04-12 05:41 UTC, Xreki commented on paddle/fluid/operators/log_softmax_op.cu
> +  int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;
> 这一行改成int effective_element_count = (global_warp_id < batch_size) ? 0 : element_count;，可删除L68 ~ L71。

这个review意见中，条件和赋值写反了，应该是`int effective_element_count = (global_warp_id < batch_size) ? element_count : 0;`

2021-04-12 11:31 UTC, AshburnLee commented on paddle/fluid/operators/log_softmax_op.cu
> +  int effective_element_count = (effective_warp_id <= 0) ? 0 : element_count;
Done。其反向计算也做了修改。