softmax reconstruction and optimization
PaddlePaddle/Paddle pull request #31821
Opened 2021-03-23 11:51 UTC by xingfeng01

### PR types

### PR changes

### Describe

2021-03-23 11:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31821) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=31821) it.</sub>

2021-03-29 06:09 UTC, lanxianghit commented
description为空，这是开发规范不允许的，请按照要求说清本PR类型、主要修改、以及相关能够使其他人清楚pr目的的信息。

2021-03-29 06:24 UTC, lanxianghit requested changes

2021-03-29 06:24 UTC, lanxianghit commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +__device__ __forceinline__ void WarpReduceSum(T* sum) {
代码整体结构变动较大，需要在pr描述或者代码注释中说清重构的设计思想，以及重要的优化点，便于其他人后续维护或者学习

2021-03-29 06:24 UTC, lanxianghit commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +__device__ __forceinline__ void WarpReduceSum(T* sum) {
同样需要考虑是否针对具体case要补充单测

2021-03-29 08:34 UTC, Xreki commented
OP Benchmark CI失败与本PR无关，https://github.com/PaddlePaddle/Paddle/pull/31920 已经在修复了。

2021-03-29 09:20 UTC, Xreki reviewed
PR描述里面写一下PR所涉及到的修改、优化工作，以及优化效果吧。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +  constexpr int BATCH_SIZE = (dim_ceil <= 128) ? 2 : 1;
常量命名，推荐命名成`constexpr int kBatchSize = xxx;`的形式。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +template <typename T, typename VECT, typename ACCT, int Log2Elements,
模板里面的命名，推荐统一成`AxxBxx`这种驼峰式命名。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +        };
`}`后面都习惯加`;`吗？

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +          (max_value[i] > (ACCT)valmax) ? max_value[i] : (ACCT)valmax;
用C++风格的类型转换，`static_cast`

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      T* valvp = reinterpret_cast<T*>(&srcdata[i][it]);
这个变量名缩写有点不好理解啊。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +};
这个函数超过100行了，相对独立的功能用函数封装一下吧。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    SOFTMAX_WARP_FORWARD_CASE(0, T, T);
- VECT传的是T，那实际上并没有向量化加载？

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#undef isLog
代码这么写有些赘余了，可以使用下面这个数据类型：
https://github.com/PaddlePaddle/Paddle/blob/51eb29de18adcf8c20272218f105eb1c2135cc09/paddle/fluid/operators/amp/fp16_type_traits.h#L23-L33

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#define isLog true
isLog这么传也不好。

2021-03-29 09:20 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +};
上述CUDA Kernel应该是会服用到softmax_with_cross_entropy OP里面，代码建议放到一个单独的文件（比如softmax_impl.cuh）中。

2021-04-06 03:29 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +__device__ __forceinline__ void WarpReduceSum(T* sum) {
在代码注释中加入了描述和主要的计算逻辑

2021-04-06 03:29 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +  constexpr int BATCH_SIZE = (dim_ceil <= 128) ? 2 : 1;
常量命名均已修改为推荐格式。

2021-04-06 03:30 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +template <typename T, typename VECT, typename ACCT, int Log2Elements,
命名均已修改为驼峰式命名。

2021-04-06 03:30 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +        };
已全部去掉分号。

2021-04-06 03:30 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +          (max_value[i] > (ACCT)valmax) ? max_value[i] : (ACCT)valmax;
已全部使用staci_cast

2021-04-06 03:32 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      T* valvp = reinterpret_cast<T*>(&srcdata[i][it]);
valvp 已修改为srcptr：与srcdata相关的ptr。

2021-04-06 03:33 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    SOFTMAX_WARP_FORWARD_CASE(0, T, T);
已经分情况实例化，dim%4==0的情况使用4倍数加载，dim%2的情况使用2倍数加载。

2021-04-06 03:33 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#undef isLog
已修改。

2021-04-06 03:34 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#define isLog true
已修改，使用MPTypeTrait解决这个问题。

2021-04-06 03:34 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +};
这两个函数已经放到softmax_impl.cuh文件中。

2021-04-06 03:36 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +__device__ __forceinline__ void WarpReduceSum(T* sum) {
这个PR没有功能性的改动，没有改变外部接口。目前单测应该可以覆盖各种情况。

2021-04-06 15:04 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +};
这个PR涵盖内容有点多了，为了更快的收敛merge，觉得另外做一个PR处理这类问题比较好。

2021-04-09 02:22 UTC, xingfeng01 commented
CI 中报错的case用develop最新的代码(不包含此PR)会报错。case为 test_trt_activation_pass： Paddle/python/paddle/fluid/tests/unittests/ir/inference/test_trt_activation_pass.py

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#include "paddle/fluid/platform/gpu_launch_config.h"
这个头文件需要用到吗？

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +                                   const int element_count) {
我看stride和element_count都是传的相同的值，没有必要传2个参数了。

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    for (int it = 1; it < kIterationsV; ++it) {
计算部分没有向量化吧，那kVSize和kIterationsV两个循环可以合成1个吗？

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    if (isLog) {
直接初始化0可以吗？性能上有影响？这么写代码显得有点赘余了。

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      idx_max_v[i] = idx_max / kVSize;
这里应该不用加`if else`吧，kVSize是常量，`kVSize==1`时，编译器应该能优化`idx_max / kVSize`。

2021-04-09 11:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +template <typename T, bool isLog = false>
isLog -> LogMode

2021-04-09 11:34 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      }
cudnn函数调用是不是softmax_with_cross_entropy里面也会用到啊，后续可以封装成一个函数，方便复用。

2021-04-09 11:35 UTC, Xreki commented
另外，针对小size情况下的微调，主要是做了哪些挑战呢，能否在PR里面说明一下。

2021-04-14 02:17 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +#include "paddle/fluid/platform/gpu_launch_config.h"
已删除。

2021-04-14 02:18 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +                                   const int element_count) {
这两个参数可以是不同的，element_count可以小于stride。建议保留。

2021-04-14 02:19 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    for (int it = 1; it < kIterationsV; ++it) {
合并起来减少代码可读性，因为有unroll，所以对性能没有影响。建议保留。

2021-04-14 02:20 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    if (isLog) {
对性能有影响，减少一个比较运算。

2021-04-14 02:20 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +template <typename T, bool isLog = false>
已修改。

2021-04-14 02:20 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      idx_max_v[i] = idx_max / kVSize;
已修改。

2021-04-14 02:21 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      }
后续PR把复用的都封装。

2021-04-14 02:24 UTC, xingfeng01 commented
小size下微调主要包括如下几个方面：减少加法和比较运算的数量，控制每个block处理的行数，非向量化读取的情况代码优化等。

2021-04-14 03:32 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +    for (int it = 1; it < kIterationsV; ++it) {
我觉得是分成2个循环比较影响可读性，代码长了快一倍。

2021-04-14 07:27 UTC, Xreki approved these changes
LGTM. 

代码书写层面，可以下个PR再封装、优化下。

2021-04-14 07:27 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +      }
感觉代码变得更长了，一个有for语句，一个没有for语句。在kVSize为1时，for循环不能被自动地优化掉吗？

2021-04-14 07:27 UTC, Xreki commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +                                   const int element_count) {
目前没有发现使用stride参数的情况，可不必做这个考虑。

2021-04-14 08:28 UTC, lanxianghit approved these changes

2021-04-14 08:33 UTC, merged