run the sample codes added by `add_sample_code` in ops.py
PaddlePaddle/Paddle pull request #31863
Opened 2021-03-25 06:05 UTC by wadefelix

### PR types
New features | Bug fixes | Others

### PR changes
Docs | Others

### Describe

https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-23536/show

1 bugfix: the sample codes added py `add_sample_code` not run in Doc CI, all then are in the file : https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/ops.py 
2 using `argparse` in `sampcd_processor.py` to handle the program parameters.
3 unittests `test_sampcd_processor.py` for `sampcd_processor.py`
4 add class `Flowers` into the wlist_temp_api, IT waste so many times to print the downloaded datasets.

2021-04-06 07:00 UTC, lelelelelez approved these changes
LGTM

2021-04-06 07:00 UTC, lelelelelez commented on tools/test_sampcd_processor.py
> +    unittest.main()
这个单测看看是不是需要加入到全量单测中？@XieYunshen

2021-04-06 07:17 UTC, XieYunshen commented on tools/test_sampcd_processor.py
> +    unittest.main()
将这个单测加入到全量单测中的原因是？

2021-04-06 10:18 UTC, lelelelelez requested changes
单测既然写了，在paddle_build.sh中cpu_py2这条ci里加个逻辑，检测到有人修改这个文件了，就跑一下这个单测。否则这个单测会将成为"历史中的无效代码"。

2021-04-13 01:12 UTC, wadefelix reviewed
> 单测既然写了，在paddle_build.sh中cpu_py2这条ci里加个逻辑，检测到有人修改这个文件了，就跑一下这个单测。否则这个单测会将成为"历史中的无效代码"。

https://github.com/PaddlePaddle/Paddle/pull/31863/commits/6d2de971ea08a29dfb91b3d65d9c7f3ffea03a5f
done, added in the `tools/check_file_diff_approvals.sh`

2021-04-13 01:12 UTC, wadefelix commented on tools/test_sampcd_processor.py
> +    unittest.main()
> 将这个单测加入到全量单测中的原因是？

参考回复。还是加到单元测试中吧，任何代码都应该保证质量，都应该有足够的测试保证。这是好的实践。

2021-04-13 02:27 UTC, lelelelelez approved these changes
LGTM

2021-04-13 02:28 UTC, merged