optimizaiton softmax entropy
PaddlePaddle/Paddle pull request #31888
Opened 2021-03-26 09:23 UTC by xingfeng01

### PR types

### PR changes

### Describe

2021-03-26 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=31888) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=31888) it.</sub>

2021-03-29 06:09 UTC, lanxianghit commented
description为空，这是开发规范不允许的，请按照要求说清本PR类型、主要修改、以及相关能够使其他人清楚pr目的的信息。

2021-03-29 06:18 UTC, lanxianghit requested changes

2021-03-29 06:18 UTC, lanxianghit commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +// }
为什么使用注释？如果是确定不需要的代码，应该直接删除，如果确实需要注释，也需要写明原因。

2021-03-29 06:18 UTC, lanxianghit commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +__global__ void CrossEntropySoftKernel(T* loss, const T* softmax,
代码整体结构变动比较大，有较多增删，最好在关键位置加一些简要的注释，说明目的，也便于后续其他人维护

2021-03-29 06:20 UTC, lanxianghit commented
代码整体改动较多，需要看一下是否需要增加单测

2021-04-06 11:12 UTC, xingfeng01 commented
性能， GPU运行时间均减少：
softmax_with_cross_entropy_0: -36% (forward), -30% (backward)
softmax_with_cross_enttropy_1: - 89% (forward), -79% (backward)

2021-04-06 11:19 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_cudnn_op.cu
> +// }
注释已删除。

2021-04-06 11:20 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +__global__ void CrossEntropySoftKernel(T* loss, const T* softmax,
注释已经加如代码中，解释函数功能和主要的实现。

2021-04-07 01:38 UTC, xingfeng01 commented
Failure CI PR-CI-APPROVAL 显示 Using ShareDataWith or ShareBufferWith is not recommended. 这部分代码非新加入。

2021-04-09 07:08 UTC, Xreki reviewed
代码改动太多，有2个小建议：

- 对相同功能的代码块进行封装。
- 代码拆成多个PR

2021-04-09 07:08 UTC, Xreki commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +__global__ void CrossEntropySoftLabel(T* loss, const T* softmax,
这2个函数的差别是什么？

2021-04-09 07:08 UTC, Xreki commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +}
这个函数有140行了，太长了。

2021-04-09 07:08 UTC, Xreki commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +#endif
rocm是不是不走下面这个版本？这里应该用`#else`？

2021-04-14 02:26 UTC, xingfeng01 commented on paddle/fluid/operators/softmax_with_cross_entropy_op.cu
> +#endif
rocm相关问题已修改。

2021-05-11 11:36 UTC, xingfeng01 commented
此PR不再需要。已合入PR 31821 实现同样功能。

2021-05-11 11:36 UTC, closed without merging