[Rocm] fix python test of multinomial
PaddlePaddle/Paddle pull request #32158
Opened 2021-04-08 11:54 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

APIs
### Describe

[Rocm] fix python test of multinomial
![image](https://user-images.githubusercontent.com/70498791/114022226-218ed780-98a4-11eb-8797-e7748e6ddf5c.png)

2021-04-09 04:13 UTC, qili93 requested changes

2021-04-09 04:13 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_multinomial_op.py
>          x_numpy = np.random.rand(3, 4)
备注一下为什么这个单测在ROCM上无法通过呢？失败的原因是什么？

2021-04-09 04:13 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_multinomial_op.py
> +            return
同上，解释一下为什么ROCM需要return的原因

2021-04-09 04:13 UTC, qili93 commented on python/paddle/tensor/random.py
> +        raise Exception('This api is not support in ROCM platform.')
为什么multinomial无法支持ROCM？

2021-04-09 04:20 UTC, qili93 commented
对于ROCM无法支持的OP，API上加warning可以，但是不要修改单测文件，把单测放到rocm的disable ut list就可以了，留待以后修复。

2021-04-09 09:43 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_multinomial_op.py
>          x_numpy = np.random.rand(3, 4)
https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/202，该issue尚未解决。

2021-04-09 09:44 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_multinomial_op.py
> +            return
同上。

2021-04-09 09:44 UTC, Ray2020BD commented on python/paddle/tensor/random.py
> +        raise Exception('This api is not support in ROCM platform.')
同上。

2021-04-09 10:12 UTC, qili93 requested changes

2021-04-09 10:12 UTC, qili93 commented on python/paddle/tensor/random.py
>      if in_dygraph_mode():
这个warning完还是会继续走后续的代码，建议改成asset直接报错，例如

assert core.is_compiled_with_rocm() == false, ("multinomial op is not supported on ROCM yet.")

2021-04-09 10:14 UTC, Ray2020BD commented on python/paddle/tensor/random.py
>      if in_dygraph_mode():
done.

2021-04-12 09:12 UTC, qili93 approved these changes
LGTM

2021-04-12 09:12 UTC, merged