remove fluid for auto_checkpoint.
PaddlePaddle/Paddle pull request #32157
Opened 2021-04-08 11:41 UTC by xiemoyuan

### PR types
Function optimization

### PR changes
APIs

### Describe
remove fluid for auto_checkpoint.

2021-04-09 02:31 UTC, willthefrog requested changes

2021-04-09 02:31 UTC, willthefrog commented on python/paddle/incubate/__init__.py
> +from ..fluid.incubate import checkpoint
建议还是只暴露需求里的API。

2021-04-09 02:57 UTC, xiemoyuan commented on python/paddle/incubate/__init__.py
> +from ..fluid.incubate import checkpoint
是指只暴露auto_checkpoint模块吗？

2021-04-09 06:53 UTC, xiemoyuan commented on python/paddle/incubate/__init__.py
> +from ..fluid.incubate import checkpoint
已修改。谢谢~

2021-04-09 08:29 UTC, willthefrog reviewed
LGTM

2021-04-13 02:39 UTC, jzhang533 approved these changes
lgtm

2021-04-20 12:13 UTC, XiaoguangHu01 approved these changes
LGTM

2021-04-20 13:35 UTC, willthefrog approved these changes

2021-04-21 00:40 UTC, merged