refator paddle inference c api interface
PaddlePaddle/Paddle pull request #32225
Opened 2021-04-13 03:28 UTC by winter-wang

### PR types

New features 
### PR changes

APIs 
### Describe

Paddle inference C api列表

2021-04-15 02:49 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/demo.cc
> +    // 创建 PD_AnalysisConfig
不用中文注释

2021-04-15 03:54 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/demo.cc
> +    // 创建 PD_AnalysisConfig
这个demo只是方便review,对应的是官网上的样例

2021-04-15 05:39 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/demo.cc
> +    PD_TensorReshape(input_tensor, 4, input_shape);
加一个带 lod 的 demo 吧

2021-04-20 03:19 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_utils.h
> +/// \date 20210-04-21
日期需要改下

2021-04-20 03:20 UTC, Shixiaowei02 commented on paddle/fluid/inference/tests/api/analyzer_capi_exp_ner_tester.cc
> +  CHECK(PD_PredictorRun(predictor) == TRUE) << "NO";
这里不要和之前的测试一样写`"NO"`了，没有意义

2021-04-20 03:25 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +__pd_give PD_Predictor* PD_PredictorClone(
需要加一个 Clone + 多线程的单测

2021-04-20 03:29 UTC, Shixiaowei02 commented
为了满足 go 接口开发需要，可以先合入一次代码；非运行正确性问题后续处理

2021-04-20 03:29 UTC, Shixiaowei02 approved these changes

2021-04-20 03:30 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/utils_internal.h
> +/// \date 20210-04-21
日期都是错误的

2021-04-20 03:32 UTC, Shixiaowei02 requested changes
明显的错误需要改一下

2021-04-20 08:47 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/demo.cc
> +    PD_TensorReshape(input_tensor, 4, input_shape);
已加

2021-04-20 08:47 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_utils.h
> +/// \date 20210-04-21
已改

2021-04-20 08:47 UTC, winter-wang commented on paddle/fluid/inference/tests/api/analyzer_capi_exp_ner_tester.cc
> +  CHECK(PD_PredictorRun(predictor) == TRUE) << "NO";
已改

2021-04-20 08:47 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/utils_internal.h
> +/// \date 20210-04-21
已改

2021-04-20 12:06 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +__pd_give PD_Predictor* PD_PredictorClone(
已补充。见 Paddle/paddle/fluid/inference/tests/api/analyzer_capi_exp_pd_threads_tester.cc。

2021-04-21 02:29 UTC, winter-wang commented
> 明显的错误需要改一下

好的

2021-04-21 10:27 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +void PD_ConfigSetModel(__pd_keep PD_Config* pd_config,
对于uncombined格式的模型 c++ 还支持 config.SetModel() 传入模型路径的方式

为兼容uncombined模型，这个也需要支持下

2021-04-21 10:28 UTC, Shixiaowei02 commented on paddle/fluid/inference/tests/api/analyzer_capi_exp_pd_tensor_tester.cc
> +// TEST(PD_Tensor, int8) {
这部分注释是否影响合入

2021-04-21 10:30 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +      CHECK(false) << "Unsupport paddle precision.";
非单测文件里要用规范的报错形式

2021-04-21 10:32 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +void PD_ConfigSetModel(__pd_keep PD_Config* pd_config,
非combined模型以 PD_ConfigSetModelDir()的接口进行支持。

2021-04-21 10:33 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +    // case PD_DATA_INT8:
需删除注释

2021-04-21 10:33 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +    // case DataType::INT8:
同上

2021-04-21 10:36 UTC, winter-wang commented on paddle/fluid/inference/tests/api/analyzer_capi_exp_pd_tensor_tester.cc
> +// TEST(PD_Tensor, int8) {
因为目前的C++代码中，int8类型的tensor调用 type()接口返回的是float类型，所以暂时注释c api中对int8 tensor类型的支持以及相关单元测试，等后续C++对int8 tensor的支持完善了，再取消注释。不会影响合入。

2021-04-21 10:38 UTC, Shixiaowei02 commented on go/demo/mobilenet_c_exp.cc
> +  // PD_ConfigSwitchIrOptim(config, FALSE);
注释删除

2021-04-21 11:03 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +      CHECK(false) << "Unsupport paddle precision.";
已改

2021-04-21 11:03 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +    // case PD_DATA_INT8:
已删除

2021-04-21 11:03 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +    // case DataType::INT8:
已改

2021-04-21 11:04 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  // PD_ConfigSwitchIrOptim(config, FALSE);
已删

2021-04-21 11:04 UTC, winter-wang commented on paddle/fluid/inference/tests/api/analyzer_capi_exp_pd_tensor_tester.cc
> +// TEST(PD_Tensor, int8) {
这部分注释已删除

2021-04-22 02:54 UTC, XieYunshen submitted a review, later dismissed

2021-04-22 03:32 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_config.h
> +typedef struct PD_Config PD_Config;
这句话的作用是什么

2021-04-22 03:48 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_config.h
> +typedef struct PD_Config PD_Config;
前置声明结构体啊

2021-04-22 05:19 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +  return reinterpret_cast<PD_Config*>(new Config());
这里使用 `reinterpret_cast` 是必须的么

2021-04-22 05:20 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +  return reinterpret_cast<PD_Config*>(new Config());
我觉得是必须的

2021-04-22 06:29 UTC, Shixiaowei02 approved these changes, later dismissed

2021-04-22 06:32 UTC, Superjomn commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchUseFeedFetchOps(config, FALSE);
我们新的API，这个config是不是没用了？ 如果只要zerocopy的话 @Shixiaowei02 @winter-wang

2021-04-22 06:32 UTC, Superjomn commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
这个是不是也没用 @Shixiaowei02

2021-04-22 06:32 UTC, Superjomn commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* input_name = PD_PredictorGetInputNames(predictor);
input_names

2021-04-22 06:32 UTC, Superjomn commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* output_name = PD_PredictorGetOutputNames(predictor);
output_names

2021-04-22 06:32 UTC, Superjomn commented on paddle/fluid/inference/capi_exp/lod_demo.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
上面两行配置应该是不需要的，C++里面这两个是否要去掉 @Shixiaowei02

2021-04-22 06:32 UTC, Superjomn commented on paddle/fluid/inference/capi_exp/pd_common.h
> +#ifndef __pd_give
加一些注释，表明这个是干啥的
有一些用户会参考头文件

2021-04-22 06:41 UTC, Shixiaowei02 commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchUseFeedFetchOps(config, FALSE);
`PD_ConfigSwitchUseFeedFetchOps` 的确在这里不起作用；但我们新的 C++ `Config` 类因为是直接封装的旧 `AnalysisConfig`，所以这个成员函数还没去除，@winter-wang 删掉这行吧

2021-04-22 06:44 UTC, Shixiaowei02 commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
是的，`PD_ConfigSwitchSpecifyInputNames` 接口不设置的话默认为 `True`，@winter-wang 删掉这个接口吧

2021-04-22 06:45 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchUseFeedFetchOps(config, FALSE);
> `PD_ConfigSwitchUseFeedFetchOps` 的确在这里不起作用；但我们新的 C++ `Config` 类因为是直接封装的旧 `AnalysisConfig`，所以这个成员函数还没去除，@winter-wang 删掉这行吧
好的

2021-04-22 06:45 UTC, Shixiaowei02 commented on paddle/fluid/inference/capi_exp/lod_demo.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
目前 C++ 的接口仍是旧类的简单封装，后续会删除这个接口

2021-04-22 06:46 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
好的

2021-04-22 06:48 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* input_name = PD_PredictorGetInputNames(predictor);
好的

2021-04-22 06:48 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* output_name = PD_PredictorGetOutputNames(predictor);
好的

2021-04-22 07:07 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/lod_demo.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
已删除这两个接口

2021-04-22 07:07 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* output_name = PD_PredictorGetOutputNames(predictor);
已改

2021-04-22 07:07 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_OneDimArrayCstr* input_name = PD_PredictorGetInputNames(predictor);
已改

2021-04-22 07:08 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchSpecifyInputNames(config, TRUE);
已改

2021-04-22 07:08 UTC, winter-wang commented on go/demo/mobilenet_c_exp.cc
> +  PD_ConfigSwitchUseFeedFetchOps(config, FALSE);
已删除

2021-04-22 07:08 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_common.h
> +#ifndef __pd_give
已加

2021-04-22 07:17 UTC, Superjomn approved these changes
LGTM

2021-04-22 07:18 UTC, Superjomn requested changes
注释错了

2021-04-22 07:19 UTC, Superjomn commented on paddle/fluid/inference/capi_exp/pd_common.h
> +/// __pd_keep means that the function will only use the object temporarily. When
keep 的意思是不会 take over ownership

2021-04-22 07:27 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_common.h
> +/// __pd_keep means that the function will only use the object temporarily. When
已改

2021-04-22 07:29 UTC, winter-wang commented
> 注释错了

已改

2021-04-22 07:34 UTC, Superjomn approved these changes
LGTM

2021-04-22 11:33 UTC, XieYunshen approved these changes

2021-04-23 16:05 UTC, raindrops2sea approved these changes

2021-04-24 05:47 UTC, merged