[Rocm] fix test of grid_sampler_op
PaddlePaddle/Paddle pull request #32254
Opened 2021-04-14 02:49 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

APIs
### Describe

[Rocm] fix test of grid_sampler_op

2021-04-14 03:19 UTC, qili93 commented
这个OP的API也得修改use_cudnn

2021-04-14 03:28 UTC, Ray2020BD commented
> 这个OP的API也得修改use_cudnn

HIP不支持cudnnSpatialTfGridGeneratorForward

2021-04-21 09:15 UTC, qili93 requested changes

2021-04-21 09:15 UTC, qili93 commented on python/paddle/nn/functional/vision.py
> +    ) and align_corners and mode == 'bilinear' and padding_mode == 'zeros':
这个直接在后面跟上 and not core.is_compiled_with_rocm(): 就好了

2021-04-30 06:18 UTC, closed without merging