[Rocm] fix test_var_base
PaddlePaddle/Paddle pull request #32325
Opened 2021-04-17 03:21 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

APIs
### Describe

[Rocm] fix test_var_base
![image](https://user-images.githubusercontent.com/70498791/115100416-04769a80-9f6f-11eb-9937-c1ae42241726.png)

2021-04-21 09:20 UTC, qili93 requested changes

2021-04-21 09:20 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_var_base.py
> +            _test_place("cpu")
解释一下为什么这里的_test_place在ROCM下不能工作，to_tensor在ROCM下应该是能跑的

2021-04-21 09:20 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_var_base.py
>              _test_place(core.CUDAPlace(0))
这里也是一样，为什么to_tensor在ROCM下不能跑

2021-04-21 09:20 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_var_base.py
> +            self.assertTrue(np.allclose(x.grad, [20.0]))
这里不要直接这么修改，用if判断下保持CUDA下的行为不变

2021-04-25 06:53 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_var_base.py
> +            self.assertTrue(np.allclose(x.grad, [20.0]))
done.

2021-04-25 06:53 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_var_base.py
>              _test_place(core.CUDAPlace(0))
done.

2021-04-25 06:53 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_var_base.py
> +            _test_place("cpu")
done.

2021-04-28 02:19 UTC, qili93 approved these changes
LGTM

2021-04-28 03:20 UTC, closed without merging