add tensor.tolist() support
PaddlePaddle/Paddle pull request #32366
Opened 2021-04-19 12:30 UTC by zhiboniu

### PR types

New features
### PR changes

OPs
### Describe

add tensor.tolist() support

2021-04-20 06:01 UTC, willthefrog requested changes
please add some tests

2021-04-20 10:09 UTC, zhiboniu commented
> please add some tests

done. add unittest test_tensor_to_list.py

2021-04-22 01:59 UTC, willthefrog approved these changes, later dismissed

2021-04-22 03:03 UTC, jzhang533 commented on python/paddle/tensor/manipulation.py
> +def tolist(x):
please do have docstring.

2021-04-22 06:34 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +def tolist(x):
done

2021-04-22 10:19 UTC, jzhang533 commented on python/paddle/tensor/manipulation.py
> +            import numpy as np
numpy可以不需要的。

2021-04-22 10:19 UTC, jzhang533 commented on python/paddle/tensor/manipulation.py
> +        list: A list that contain the same value of current Variable.
统一都用Tensor概念，不用Variable。

2021-04-22 10:20 UTC, jzhang533 commented on python/paddle/tensor/manipulation.py
> +    This OP translate the paddle.Tensor to python list.
这个不是OP吧？

2021-04-22 10:29 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +            import numpy as np
done

2021-04-22 10:29 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +        list: A list that contain the same value of current Variable.
done

2021-04-22 10:30 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +    This OP translate the paddle.Tensor to python list.
done, 改成function

2021-04-22 10:36 UTC, jzhang533 submitted a review, later dismissed
LGTM

2021-04-23 06:22 UTC, zhouwei25 commented on python/paddle/tensor/manipulation.py
> +setattr(core.VarBase, 'tolist', tolist)
manipulation应该会被自动加入到Tensor类成员API，这个可以不用写

2021-04-23 06:22 UTC, zhouwei25 commented on python/paddle/tensor/manipulation.py
> +            t = paddle.to_tensor([0,1,2,3,4])
这里的示例可以加个 paddle.tolist(x) 和 x.tolist()两种类型

2021-04-23 07:01 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +setattr(core.VarBase, 'tolist', tolist)
math_op_patch.py里加入属性api需要加到列表里，而且列表是动态图静态图共用的。但是这个函数只是Tensor的属性，Variable不能用，所以在这里单独加了。

2021-04-23 07:13 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +            t = paddle.to_tensor([0,1,2,3,4])
done

2021-04-23 07:19 UTC, zhouwei25 commented on python/paddle/tensor/manipulation.py
> +setattr(core.VarBase, 'tolist', tolist)
但是variable可能还是会加进来

2021-04-23 07:20 UTC, zhouwei25 approved these changes
LGTM

2021-04-23 07:31 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +setattr(core.VarBase, 'tolist', tolist)
tolist应该只能支持Tensor操作，所以应该只能是动态图使用

2021-04-24 00:58 UTC, XiaoguangHu01 approved these changes
LGTM

2021-04-24 01:02 UTC, merged

2022-01-10 07:03 UTC, Huntersdeng commented
It seems the tolist() op is much slower than the pytorch implementation. In my test, the time for paddle.tensor.tolist() is about 1e-3, while the torch.tensor.tolist() is 1e-6.