Fix CMake golang rebuild problems
PaddlePaddle/Paddle pull request #3270
Opened 2017-08-05 10:29 UTC by reyoung

* In previous cmake, golang target will always rebuild no matter
go sources are changed or not.

2017-08-05 19:54 UTC, wangkuiyi approved these changes
It would be helpful if we can have an issue that describes the problem encountered and the reason, and mark this PR as fixing the issue.

2017-08-05 19:54 UTC, wangkuiyi commented on cmake/generic.cmake
> +    COMMAND ${TOUCH_CMD} ${dummyfile} ${GO_SOURCE}
If we change this line into 

```
COMMAND ${PROJ_ROOT}/paddle/scripts/build/touch_if_newer.sh ${dummyfile} ${GO_SOURCE}
```

we can remove L310 which defines `TOUCH_CMD`.

2017-08-05 19:54 UTC, wangkuiyi commented on paddle/scripts/build/if_newer_then_touch.sh
> +#!/bin/bash
I think we need a comment here

```
# Usage: 
#    touch_if_newer.sh <reference_file> <source_file_1> <source_file_2> ...
# Touch a source file if it is newer than the reference file.
```

2017-08-06 06:16 UTC, helinwang requested changes
Thanks for trying to fix this!

There is no easy solution to this problem, since the Go source files is not just the ones in the specified folder. All the dependencies in other folders are the source files are well.

Rebuilding every time is done intentionally since there is no easy fix, and we can't risk not building the code when the source have changed.

However, even if we rebuild every time, Go already caches the build result (for all the source that is in $GOPATH), so rebuild should be very fast.

2020-05-22 06:37 UTC, closed without merging