[Rocm] fix tests of inplace_abn_op & grid_sampler_op
PaddlePaddle/Paddle pull request #32703
Opened 2021-04-30 06:56 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

APIs 
### Describe

[Rocm] fix tests of inplace_abn_op & grid_sampler_op
![image](https://user-images.githubusercontent.com/70498791/116659521-4b7b7b80-a9c4-11eb-9f72-8bcd68a6fee7.png)

2021-04-30 08:34 UTC, qili93 requested changes

2021-04-30 08:34 UTC, qili93 commented on python/paddle/nn/functional/vision.py
> +            cudnn_version is not None
这个格式有点奇怪，为什么括号会单独一行？最好修正一下格式

2021-04-30 08:47 UTC, Ray2020BD commented on python/paddle/nn/functional/vision.py
> +            cudnn_version is not None
这是pre-commit自动修改的，原本格式不是这样的

2021-05-06 02:14 UTC, qili93 requested changes

2021-05-06 02:14 UTC, qili93 commented on python/paddle/fluid/layers/nn.py
> +        dtype = 'float32'
grid_sampler 的 use_cudnn 为 False，因此不使用MIOPEN，为什么这里的dtype要改成fp32?

2021-05-06 02:14 UTC, qili93 commented on python/paddle/nn/functional/vision.py
> +            cudnn_version is not None
可以尝试pre-commit uninstall之后再提交，或者手动断行，类似这个样子
```bash
    while not (os.path.exists(DATA_OUT_PATH) and
               os.path.getsize(DATA_OUT_PATH) == BIN_FULLSIZE and BIN_TARGETHASH
               == hashlib.md5(open(DATA_OUT_PATH, 'rb').read()).hexdigest()):
```

2021-05-06 05:58 UTC, Ray2020BD commented on python/paddle/fluid/layers/nn.py
> +        dtype = 'float32'
已删除

2021-05-06 05:58 UTC, Ray2020BD commented on python/paddle/nn/functional/vision.py
> +            cudnn_version is not None
已修改

2021-05-06 07:05 UTC, qili93 commented
LGTM

2021-05-06 07:06 UTC, qili93 approved these changes

2021-05-06 08:31 UTC, merged