[Rocm] fix expand as
PaddlePaddle/Paddle pull request #32704
Opened 2021-04-30 07:21 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

APIs
### Describe

[Rocm] fix expand as
![image](https://user-images.githubusercontent.com/70498791/116661813-95b22c00-a9c7-11eb-82ca-efc3547ddcd9.png)

2021-04-30 08:31 UTC, qili93 requested changes

2021-04-30 08:31 UTC, qili93 commented on cmake/external/eigen.cmake
> +        file(TO_NATIVE_PATH ${EIGEN_SOURCE_DIR}/unsupported/Eigen/CXX11/src/Tensor/TensorReductionGpu.h native_dst)
这里修改的不对，会把上一个的patch覆盖掉了，当存在多个patch的时候，需要参考这个修改 https://github.com/qili93/Paddle/blob/rocm_dev_0207/cmake/external/eigen.cmake#L61

2021-04-30 08:41 UTC, Ray2020BD commented on cmake/external/eigen.cmake
> +        file(TO_NATIVE_PATH ${EIGEN_SOURCE_DIR}/unsupported/Eigen/CXX11/src/Tensor/TensorReductionGpu.h native_dst)
done.

2021-04-30 08:47 UTC, qili93 approved these changes
LGTM，再给 expand_as op的负责人帮忙看一下有没有问题

2021-05-06 06:08 UTC, HexToString commented
LGTM

2021-05-06 07:00 UTC, Superjomn approved these changes
LGTM

2021-05-06 07:04 UTC, merged