Simple authors change
PaddlePaddle/Paddle pull request #32763
Opened 2021-05-06 15:46 UTC by andreazanetti

### PR types

Others
### PR changes

Docs
### Describe

Update list of authors

2021-05-06 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=32763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=32763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=32763) it.</sub>

2021-05-06 16:07 UTC, jakpiase requested changes
Please, add me (Jakub Piasecki) as well

2021-05-07 07:43 UTC, arlesniak commented on AUTHORS.md
> +| ddokupil | Darius Dokupil |
Typo: Dariusz

2021-05-11 06:54 UTC, lidanqing-intel commented on AUTHORS.md
> -| [sfraczek](https://raw.githubusercontent.com/jczaja/Paddle/paddle-poland-team/doc/images/paddle_poland_team.jpg)| Sylwester Fraczek |
These name are removed because they left Intel or they left PaddlePaddle? But they also contributed some code in PaddlePaddle

2021-05-11 07:11 UTC, lidanqing-intel commented on AUTHORS.md
> -| [sfraczek](https://raw.githubusercontent.com/jczaja/Paddle/paddle-poland-team/doc/images/paddle_poland_team.jpg)| Sylwester Fraczek |
I confirmed with Luotao. @andreazanetti  Do you delete their names since they contributed before.

2021-05-11 15:13 UTC, jakpiase approved these changes
LGTM!

2021-05-11 15:33 UTC, arlesniak approved these changes
LGTM

2021-05-12 04:23 UTC, luotao1 approved these changes

2021-05-12 04:24 UTC, merged