[Rocm] fix test of random_crop_op
PaddlePaddle/Paddle pull request #32824
Opened 2021-05-10 09:24 UTC by Ray2020BD

### PR types

Bug fixes
### PR changes

OPs
### Describe

[Rocm] fix test of random_crop_op ( under release-compile )
![image](https://user-images.githubusercontent.com/70498791/117637495-6dd77b00-b1b4-11eb-9269-ea9a0b21b37b.png)

2021-05-13 04:03 UTC, qili93 requested changes

2021-05-13 04:03 UTC, qili93 commented on paddle/fluid/operators/random_crop_op.h
> +#endif
看了下你的分析文档，但当前这个修复方式不能满足OP要，我们OP修复的原则是
（1）不可以因为这两段代码会挂就不检查x_stride和out_stride，而是需要找到能工作的代码替换这两段代码，或者修复PADDLE_ENFORCE的逻辑使其能够工作

我们修复OP的目的不是为了单测可以通过，而是保证功能的正确性，当前的diff只是简单跳过了x_stride和out_stride的检查，不符合我们OP修复的目的。

2021-05-14 12:23 UTC, Ray2020BD commented on paddle/fluid/operators/random_crop_op.h
> +#endif
好的，已修改。

2021-05-17 09:09 UTC, qili93 requested changes

2021-05-17 09:09 UTC, qili93 commented on paddle/fluid/operators/random_crop_op.h
> +#endif
这个直接printf不符合paddle msg的标准，请参考这个文档写关于paddle的error msg
https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification

2021-05-18 07:04 UTC, Ray2020BD commented on paddle/fluid/operators/random_crop_op.h
> +#endif
已删除

2021-05-18 07:21 UTC, haozech submitted a review, later dismissed
LGTM

2021-05-18 07:44 UTC, qili93 requested changes

2021-05-18 07:44 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_logsumexp.py
> +        return dy * np.exp(x - y)
这里能解释一下为什么get_numeric_gradient得到的结果在ROCm上无法对齐，需要定义user_defined_grads呢？CUDA上为什么可以直接使用get_numeric_gradient？

2021-05-18 07:44 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_simple_rnn_op.py
> +            [12, 11, 10, 9, 8], dtype=np.int32)
MIOPEN不支持sequence_length的话，SimpleRNN的API也同样需要修改，对于sequence_length非空的输入需要抛出正确的error msg.

2021-05-18 07:44 UTC, qili93 commented on python/paddle/fluid/tests/unittests/test_simple_rnn_op.py
> +
这里能解释一下为什么需要对flat_w的数据做交换吗？是miopenSetRNNDescriptor_V2 里面的 miopenRNNbidirection 和 cudnnSetRNNDescriptor_v6 的 CUDNN_BIDIRECTIONAL 的行为不一致？

2021-05-18 08:11 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_logsumexp.py
> +        return dy * np.exp(x - y)
logsumexp这个op本身运算出来的analytic_grads是没问题的，有问题的是numeric_grads（cuda下该计算没问题），所以干脆自己计算numeric_grads

2021-05-18 08:19 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_simple_rnn_op.py
> +            [12, 11, 10, 9, 8], dtype=np.int32)
simpleRNN的修改以及该单测的修改从本pr中删除，将和其他rnn单测修改统一放到其他的pr中。

2021-05-18 08:19 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/test_simple_rnn_op.py
> +
miopen相关api的实现中，layout并没有和cuda相关pai对齐，需要手动调节。

2021-05-19 02:57 UTC, Xreki approved these changes
LGTM for op benchmark ci

2021-05-19 09:50 UTC, qili93 approved these changes
LGTM

2021-05-19 09:50 UTC, merged