[Inference] Update go inference api based on new capi.
PaddlePaddle/Paddle pull request #33113
Opened 2021-05-25 11:44 UTC by jiweibo

### PR types

New features
### PR changes

APIs
### Describe

1、基于预测新版CAPI更新了预测Go API
2、demo及文档pr：https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/138

2021-05-25 11:48 UTC, jiweibo commented on paddle/fluid/inference/goapi/go.mod
> +module github.com/jiweibo/paddle/paddle/fluid/inference/goapi
组织名需要更正为paddlepaddle

2021-05-25 11:48 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +您可以选择直接下载[paddle_inference_c]()预测库，或通过源码编译的方式安装，源码编译方式参考官网文档，注意这里cmake编译时打开`-DON_INFER=ON`,在编译目录下得到`paddle_inference_c_install_dir`。
更新 c预测库下载链接

2021-05-25 11:49 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +# 此处使用上一步记录的CommitId，假设为76e5724
组织更好的表达语义

2021-05-25 11:49 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +cd /root/gopath/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi\@v0.0.0-20210517084506-76e5724c16a5/
如何做到通用化？

2021-05-25 11:50 UTC, jiweibo commented on paddle/fluid/inference/goapi/predictor_test.go
> +	// t.Log(outHandle.Data().([][]float32))
删除无用注释代码

2021-05-25 11:50 UTC, jiweibo commented on paddle/fluid/inference/goapi/predictor_test.go
> +}
添加从内存加载的测试代码

2021-05-25 13:24 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +
添加注释说明

2021-05-25 13:26 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +	defer func() {
可以考虑去除defer，直接free

2021-05-26 02:52 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) SetOptionCacheDir(cacheDir string) {
拼写错误

2021-05-26 03:09 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) EnableXpu(l3WorkspaceSize int32) {
C API及GO API xpu接口需要更新

2021-05-26 03:11 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) XpuDeviceId() int32 {
C++ 需确认目前是否支持选择xpu卡

2021-05-26 03:21 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +///        ..., IBuilder.getNbDLACores() - 1
注释引用了C++

2021-05-26 06:29 UTC, jiweibo commented on paddle/fluid/inference/goapi/tensor.go
> +// -------------------------
考虑去除其它获取输出的方式

2021-05-26 07:23 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) SetOptionCacheDir(cacheDir string) {
done

2021-05-26 07:23 UTC, jiweibo commented on paddle/fluid/inference/goapi/predictor_test.go
> +}
done

2021-05-26 07:24 UTC, jiweibo commented on paddle/fluid/inference/goapi/predictor_test.go
> +	// t.Log(outHandle.Data().([][]float32))
done

2021-05-27 03:42 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +	defer func() {
两者均可，done

2021-06-04 02:51 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +
done

2021-06-04 02:52 UTC, jiweibo commented on paddle/fluid/inference/goapi/go.mod
> +module github.com/jiweibo/paddle/paddle/fluid/inference/goapi
done

2021-06-04 02:52 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) XpuDeviceId() int32 {
go接口同C++

2021-06-04 02:54 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +///        ..., IBuilder.getNbDLACores() - 1
go没有对应的trt语义注释，保留

2021-06-04 06:46 UTC, jiweibo commented on paddle/fluid/inference/goapi/config.go
> +func (config *Config) EnableXpu(l3WorkspaceSize int32) {
done

2021-06-04 06:47 UTC, jiweibo commented on paddle/fluid/inference/goapi/tensor.go
> +// -------------------------
done

2021-06-04 11:18 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +您可以选择直接下载[paddle_inference_c]()预测库，或通过源码编译的方式安装，源码编译方式参考官网文档，注意这里cmake编译时打开`-DON_INFER=ON`,在编译目录下得到`paddle_inference_c_install_dir`。
done

2021-06-04 11:18 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +# 此处使用上一步记录的CommitId，假设为76e5724
done

2021-06-04 11:19 UTC, jiweibo commented on paddle/fluid/inference/goapi/README.md
> +cd /root/gopath/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi\@v0.0.0-20210517084506-76e5724c16a5/
done

2021-06-07 11:54 UTC, winter-wang requested changes

2021-06-07 11:54 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_common.h
> +    PD_DATA_INT64,    PD_DATA_UINT8,   PD_DATA_INT8,
我记得INT8推理功能目前好像不是很完善，会有奇怪的问题。如果只加一个枚举值，却没有配套的函数，感觉意义好像也不是很大

2021-06-07 11:54 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +  return paddle_infer::CvtVecToOneDimArrayCstr(version);
这个确定返回的是 vector<string>吗？我记得好像返回的是string吧

2021-06-07 11:54 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +      return DataType::INT8;
同之前

2021-06-07 11:54 UTC, winter-wang commented on paddle/fluid/inference/goapi/tensor.go
> +		C.PD_TensorCopyFromCpuInt8(t.c, (*C.int8_t)(unsafe.Pointer(&data[0])))
这个PD_TensorCopyFromCpuInt8好像缺乏定义。。

2021-06-07 11:56 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +  return paddle_infer::CvtVecToOneDimArrayCstr(version);
GetVersion返回的是string，这里直接复用了已有的C对vector<string>的方式，不用再新增对string的单独处理了

2021-06-07 11:58 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +  return paddle_infer::CvtVecToOneDimArrayCstr(version);
这个version在运行时应该是不会变得吧，是不是直接用static string，返回一个  const char*好一点？

2021-06-07 12:01 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_common.h
> +    PD_DATA_INT64,    PD_DATA_UINT8,   PD_DATA_INT8,
这里加int8 enum，是为了支持trt的int8推理。

config设置trt的Precision为int8.

2021-06-07 12:01 UTC, jiweibo commented on paddle/fluid/inference/goapi/tensor.go
> +		C.PD_TensorCopyFromCpuInt8(t.c, (*C.int8_t)(unsafe.Pointer(&data[0])))
这里是有定义的，在pd_tensor.h中

2021-06-07 12:02 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_utils.cc
> +      return DataType::INT8;
同上，为支持trt int8推理，需增加的转换。

2021-06-07 12:06 UTC, winter-wang commented on paddle/fluid/inference/goapi/tensor.go
> +		C.PD_TensorCopyFromCpuInt8(t.c, (*C.int8_t)(unsafe.Pointer(&data[0])))
你是不是忘上传pd_tensor.h了？我好想没看到

2021-06-07 12:19 UTC, jiweibo commented on paddle/fluid/inference/goapi/tensor.go
> +		C.PD_TensorCopyFromCpuInt8(t.c, (*C.int8_t)(unsafe.Pointer(&data[0])))
新版capi提供了对应int8的copy_from_cpu和copy_to_cpu的capi 接口。

2021-06-07 12:20 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +  return paddle_infer::CvtVecToOneDimArrayCstr(version);
ok，我改成static的形式

2021-06-07 12:43 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_predictor.cc
> +  return paddle_infer::CvtVecToOneDimArrayCstr(version);
done

2021-06-16 08:21 UTC, Shixiaowei02 approved these changes

2021-06-16 08:35 UTC, winter-wang approved these changes
LGTM

2021-06-16 08:35 UTC, winter-wang commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +  std::vector<std::string> passes = config->pass_builder()->AllPasses();
这个passes直接定义成const&是不是更好一点，少一次拷贝。

2021-06-16 08:38 UTC, jiweibo commented on paddle/fluid/inference/capi_exp/pd_config.cc
> +  std::vector<std::string> passes = config->pass_builder()->AllPasses();
收到，下个pr修改

2021-06-16 11:10 UTC, Superjomn approved these changes
LGTM

2021-06-17 09:52 UTC, raindrops2sea approved these changes

2021-06-17 10:19 UTC, merged