update 2.0 public api in vision
PaddlePaddle/Paddle pull request #33308
Opened 2021-06-02 13:49 UTC by zhiboniu

### PR types

Others
### PR changes

APIs
### Describe

update 2.0 public api in vision
cherry-pick to https://github.com/PaddlePaddle/Paddle/pull/33307

2021-06-04 03:44 UTC, jeff41404 commented on python/paddle/vision/__init__.py
> +    'set_image_backend', 'get_image_backend', 'image_load'
和其它一样分行写？

2021-06-04 11:24 UTC, zhiboniu commented on python/paddle/vision/__init__.py
> +    'set_image_backend', 'get_image_backend', 'image_load'
这里相对还好只有3个，目前这样也还比较清楚。
我看看有没有其他修改一起顺便改了，如果没有其他要改的就下次再改也行吧

2021-06-04 11:33 UTC, XiaoguangHu01 approved these changes, later dismissed
LGTM

2021-06-04 15:00 UTC, LielinJiang commented on python/paddle/vision/__init__.py
> +from .models import LeNet  # noqa: F401
这里为啥单独一个LeNet

2021-06-04 15:47 UTC, zhiboniu commented on python/paddle/vision/__init__.py
> +from .models import LeNet  # noqa: F401
因为很多地方调用了这个，放这里是为了避免出错

2021-06-04 15:55 UTC, LielinJiang approved these changes, later dismissed

2021-06-08 06:45 UTC, raindrops2sea requested changes

2021-06-08 06:45 UTC, raindrops2sea commented on python/paddle/vision/__init__.py
> +from .models import LeNet  # noqa: F401
这个理由表述的并不充分呀。另外，注意到下面all里也没包含。

2021-06-08 07:58 UTC, zhiboniu commented on python/paddle/vision/__init__.py
> +from .models import LeNet  # noqa: F401
https://github.com/search?p=1&q=org%3APaddlePaddle+paddle.vision.LeNet&type=Code
可以参考这里的结果。其实理想情况是跟其他模型api一样在这里不保留比较好。
因为LeNet已经在推荐路径加入__all__了（跟其他模型hapi在一个路径下），所以这里的__all__不加入。

2021-06-08 09:16 UTC, zhiboniu commented on python/paddle/vision/__init__.py
> +from .models import LeNet  # noqa: F401
已经把所有调用paddle.vision.LeNet修改为paddle.vision.models.LeNet，同时删除了这一行

2021-06-10 06:41 UTC, XiaoguangHu01 submitted a review, later dismissed
LGTM

2021-06-10 07:38 UTC, jzhang533 reviewed
python/paddle/hapi/model.py:34:1: F811 redefinition of unused 'in_dygraph_mode' from line 33
python/paddle/hapi/model.py:34:1: F811 redefinition of unused 'Variable' from line 33
python/paddle/hapi/model.py:166:18: F821 undefined name 'unique_name'
python/paddle/hapi/model.py:169:9: F841 local variable 'endpoint_to_index_map' is assigned to but never used
python/paddle/hapi/model.py:1366:97: E502 the backslash is redundant between brackets
python/paddle/hapi/model.py:1504:66: E502 the backslash is redundant between brackets
python/paddle/hapi/model.py:2125:29: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
python/paddle/hapi/model.py:2126:35: E502 the backslash is redundant between brackets
python/paddle/vision/transforms/functional_cv2.py:54:8: E713 test for membership should be 'not in'
python/paddle/vision/transforms/functional_cv2.py:397:26: F523 '...'.format(...) has unused arguments at position(s): 0
python/paddle/vision/transforms/functional_pil.py:62:8: E713 test for membership should be 'not in'
python/paddle/vision/transforms/functional_pil.py:383:26: F523 '...'.format(...) has unused arguments at position(s): 0

2021-06-11 02:19 UTC, raindrops2sea approved these changes
LGTM

2021-06-11 02:21 UTC, zhiboniu commented
> python/paddle/hapi/model.py:34:1: F811 redefinition of unused 'in_dygraph_mode' from line 33
> python/paddle/hapi/model.py:34:1: F811 redefinition of unused 'Variable' from line 33
> python/paddle/hapi/model.py:166:18: F821 undefined name 'unique_name'
> python/paddle/hapi/model.py:169:9: F841 local variable 'endpoint_to_index_map' is assigned to but never used
> python/paddle/hapi/model.py:1366:97: E502 the backslash is redundant between brackets
> python/paddle/hapi/model.py:1504:66: E502 the backslash is redundant between brackets
> python/paddle/hapi/model.py:2125:29: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
> python/paddle/hapi/model.py:2126:35: E502 the backslash is redundant between brackets
> python/paddle/vision/transforms/functional_cv2.py:54:8: E713 test for membership should be 'not in'
> python/paddle/vision/transforms/functional_cv2.py:397:26: F523 '...'.format(...) has unused arguments at position(s): 0
> python/paddle/vision/transforms/functional_pil.py:62:8: E713 test for membership should be 'not in'
> python/paddle/vision/transforms/functional_pil.py:383:26: F523 '...'.format(...) has unused arguments at position(s): 0

done

2021-06-11 03:19 UTC, jzhang533 approved these changes
lgtm

2021-06-11 06:28 UTC, XiaoguangHu01 approved these changes
LGTM

2021-06-11 06:44 UTC, merged