update 2.0 public api in all left files
PaddlePaddle/Paddle pull request #33313
Opened 2021-06-03 05:21 UTC by zhiboniu

### PR types

Others
### PR changes

APIs
### Describe

update 2.0 public api in all left files

2021-06-04 03:41 UTC, jeff41404 commented on python/paddle/incubate/__init__.py
> +    'LookAhead', 'ModelAverage', 'auto_checkpoint'
和其它一样分行写？

2021-06-04 03:43 UTC, jeff41404 commented on python/paddle/__init__.py
> -from .framework import set_grad_enabled  #DEFINE_ALIAS
这里是否要改成 from .framework import set_grad_enabled # noqa: F401
或者说set_grad_enabled 如果不公开了，那下面的__all__列表中也要删除set_grad_enabled

2021-06-04 03:48 UTC, zhiboniu commented on python/paddle/incubate/__init__.py
> +    'LookAhead', 'ModelAverage', 'auto_checkpoint'
这里的set_grad_enabled是重复导入，跟242行重复了。

2021-06-04 03:49 UTC, zhiboniu commented on python/paddle/__init__.py
> -from .framework import set_grad_enabled  #DEFINE_ALIAS
这里的set_grad_enabled是重复导入，跟242行重复了。

2021-06-04 11:21 UTC, XiaoguangHu01 approved these changes, later dismissed
LGTM

2021-06-04 11:24 UTC, zhiboniu commented on python/paddle/incubate/__init__.py
> +    'LookAhead', 'ModelAverage', 'auto_checkpoint'
这里相对还好只有3个，目前这样也还比较清楚。
我看看有没有其他修改一起顺便改了，如果没有其他要改的就下次再改也行吧

2021-06-08 07:20 UTC, raindrops2sea requested changes

2021-06-08 07:20 UTC, raindrops2sea commented on python/paddle/device.py
> -    'is_compiled_with_xpu',
注意后面Examples:        .. code-block:: python里的写法要和最终推荐路径都保持一致，现在比较杂乱，比如有：support_xpu = paddle.device.is_compiled_with_xpu()

2021-06-08 07:49 UTC, zhiboniu commented on python/paddle/device.py
> -    'is_compiled_with_xpu',
done，已经进行修改

2021-06-10 06:42 UTC, XiaoguangHu01 commented on python/paddle/device.py
> +            support_xpu = paddle.is_compiled_with_xpu()
这几个API，考虑到接下来还会增加device相关的api，我建议保留paddle.device层级更好些。
如果全都移到根目录下的话，当前还好，未来这类api会比较分散。
兼容性考虑，根目录下的api需要保留别名，但不用加到all列表。

2021-06-10 07:24 UTC, jzhang533 reviewed
python/paddle/__init__.py:25:9: F821 undefined name 'batch'
python/paddle/__init__.py:138:1: F811 redefinition of unused 'transpose' from line 93
python/paddle/__init__.py:194:1: F811 redefinition of unused 'atan' from line 151
python/paddle/__init__.py:283:17: E262 inline comment should start with '# '
python/paddle/batch.py:63:22: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
python/paddle/compat.py:22:17: F821 undefined name 'long'
python/paddle/device.py:117:52: E502 the backslash is redundant between brackets
python/paddle/device.py:123:52: E502 the backslash is redundant between brackets
python/paddle/device.py:138:75: E502 the backslash is redundant between brackets
python/paddle/device.py:147:75: E502 the backslash is redundant between brackets
python/paddle/distributed/parallel.py:153:9: F841 local variable 'ep_rank' is assigned to but never used
python/paddle/incubate/optimizer/lookahead.py:285:9: F841 local variable 'parameter_list' is assigned to but never used
python/paddle/incubate/optimizer/modelaverage.py:418:17: F841 local variable 'num_updates' is assigned to but never used
python/paddle/incubate/optimizer/modelaverage.py:509:9: F841 local variable 'num_updates' is assigned to but never used
python/paddle/incubate/optimizer/modelaverage.py:517:51: E711 comparison to None should be 'if cond is None:'
python/paddle/incubate/optimizer/modelaverage.py:519:51: E711 comparison to None should be 'if cond is None:'
python/paddle/tensor/__init__.py:28:1: F811 redefinition of unused 'eye' from line 21
python/paddle/tensor/__init__.py:85:1: F811 redefinition of unused 'transpose' from line 39
python/paddle/tensor/__init__.py:146:1: F811 redefinition of unused 'atan' from line 97

2021-06-11 02:11 UTC, zhiboniu commented on python/paddle/device.py
> +            support_xpu = paddle.is_compiled_with_xpu()
done

2021-06-11 02:11 UTC, zhiboniu commented
> python/paddle/**init**.py:25:9: F821 undefined name 'batch'
> python/paddle/**init**.py:138:1: F811 redefinition of unused 'transpose' from line 93
> python/paddle/**init**.py:194:1: F811 redefinition of unused 'atan' from line 151
> python/paddle/**init**.py:283:17: E262 inline comment should start with '# '
> python/paddle/batch.py:63:22: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
> python/paddle/compat.py:22:17: F821 undefined name 'long'
> python/paddle/device.py:117:52: E502 the backslash is redundant between brackets
> python/paddle/device.py:123:52: E502 the backslash is redundant between brackets
> python/paddle/device.py:138:75: E502 the backslash is redundant between brackets
> python/paddle/device.py:147:75: E502 the backslash is redundant between brackets
> python/paddle/distributed/parallel.py:153:9: F841 local variable 'ep_rank' is assigned to but never used
> python/paddle/incubate/optimizer/lookahead.py:285:9: F841 local variable 'parameter_list' is assigned to but never used
> python/paddle/incubate/optimizer/modelaverage.py:418:17: F841 local variable 'num_updates' is assigned to but never used
> python/paddle/incubate/optimizer/modelaverage.py:509:9: F841 local variable 'num_updates' is assigned to but never used
> python/paddle/incubate/optimizer/modelaverage.py:517:51: E711 comparison to None should be 'if cond is None:'
> python/paddle/incubate/optimizer/modelaverage.py:519:51: E711 comparison to None should be 'if cond is None:'
> python/paddle/tensor/**init**.py:28:1: F811 redefinition of unused 'eye' from line 21
> python/paddle/tensor/**init**.py:85:1: F811 redefinition of unused 'transpose' from line 39
> python/paddle/tensor/**init**.py:146:1: F811 redefinition of unused 'atan' from line 97

2021-06-11 02:20 UTC, raindrops2sea approved these changes
LGTM

2021-06-11 03:15 UTC, jzhang533 approved these changes
lgtm

2021-06-11 06:29 UTC, XiaoguangHu01 approved these changes
LGTM

2021-06-11 06:44 UTC, merged