add squeeze2 and unsqueeze2 pbtxt
PaddlePaddle/Paddle pull request #33343
Opened 2021-06-04 05:47 UTC by cuicheng01

2021-06-04 05:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=33343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=33343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=33343) it.</sub>

2021-06-04 06:40 UTC, winter-wang requested changes

2021-06-04 06:40 UTC, winter-wang commented on paddle/fluid/operators/compat/squeeze2.pbtxt
> +  attrs {
从op_role开始的5个属性麻烦找op负责人再确认一下

2021-06-04 06:59 UTC, winter-wang approved these changes
LGTM

2021-06-08 07:48 UTC, Shixiaowei02 approved these changes

2021-06-08 07:49 UTC, merged