ELASTIC 1 : fault tolerance
PaddlePaddle/Paddle pull request #33369
Opened 2021-06-07 03:01 UTC by kuizhiqing

### PR types

New features

### PR changes

Others

### Describe

Adding fault tolerance feature in distributed mode ( collective mode here),
* ElasticManager in elastic module handle life cycle of training process, be notified of node failure;
* define LauncherInterface wrap the real task workflow which is the same as before;

This pr is compatible upgrade which means it will keep silence and change nothing if it is not enabled.

2021-06-08 03:08 UTC, xymyeah requested changes

2021-06-08 03:08 UTC, xymyeah commented on python/paddle/distributed/fleet/launch.py
> +    elastic = ElasticManager(args)
下面的部分，是否可以封装到ElasticManager里边？

2021-06-08 03:08 UTC, xymyeah commented on python/paddle/distributed/fleet/elastic.py
> +    def __init__(self, args):
加上注释，对参数进行解释说明

2021-06-08 03:08 UTC, xymyeah commented on python/paddle/distributed/fleet/elastic.py
> +        scale = args.scale or int(os.getenv('PADDLE_SCALE', 0))
环境变量统一一下规范，例如都是PADDLE_ELASTIC开头

2021-06-08 03:08 UTC, xymyeah commented on python/paddle/distributed/fleet/elastic.py
> +class LauncherInterface(object):
如果是通用的接口，可以考虑放到launch.py里

2021-06-08 03:11 UTC, xymyeah requested changes

2021-06-08 03:11 UTC, xymyeah commented on python/paddle/distributed/fleet/elastic.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
补充单测

2021-06-08 03:11 UTC, xymyeah commented on python/paddle/distributed/fleet/launch.py
> +        elastic.wait()
目前有很多使用 python -m paddle.distributed.launch train.py来启动分布式任务的用法，注意兼容该用法

2021-06-17 02:43 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +    elastic = ElasticManager(args)
返回状态的控制交给 launch 做相比更合理一些，launch 设计上是 控制 elasticmanager 的外层。

2021-06-17 02:45 UTC, kuizhiqing commented on python/paddle/distributed/fleet/elastic.py
> +    def __init__(self, args):
args 的注释加到了 help 信息里面，和这里是对应的

2021-06-17 02:45 UTC, kuizhiqing commented on python/paddle/distributed/fleet/elastic.py
> +        scale = args.scale or int(os.getenv('PADDLE_SCALE', 0))
已修复

2021-06-17 02:46 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +        elastic.wait()
已兼容

2021-06-17 03:05 UTC, xymyeah requested changes

2021-06-17 03:05 UTC, xymyeah commented on python/paddle/distributed/fleet/launch.py
> +    elastic = ElasticManager(args)
现在的处理逻辑应该是无论是否开启elastic，都会有走这部分的逻辑，这部分的逻辑跟elastic相关，如果不开启elastic，应该不需要该部分的逻辑

2021-06-18 03:18 UTC, danleifeng commented on python/paddle/distributed/fleet/launch.py
> +        "--force", type=bool, default=False, help="update np force")
最好参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_fleet_launch_cloud.sh 补充下弹性模型的单测

2021-06-18 12:13 UTC, Baibaifan commented on python/paddle/distributed/fleet/elastic.py
> +    def signal_handler(self, sigint, frame):
frame 这个没使用吧

2021-06-18 12:13 UTC, Baibaifan commented on python/paddle/distributed/fleet/launch.py
> +        self._terminate_procs()
这个应该增加下stop的状态吧，50次还没关闭，这边也没有逻辑报错

2021-06-18 12:13 UTC, Baibaifan commented on python/paddle/distributed/fleet/launch.py
> +        pod = None
这两个None 可以删除哈

2021-06-21 03:37 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +        "--force", type=bool, default=False, help="update np force")
单测放 ce

2021-06-21 03:37 UTC, kuizhiqing commented on python/paddle/distributed/fleet/elastic.py
> +    def signal_handler(self, sigint, frame):
signal 固定写法

2021-06-21 03:38 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +        pod = None
历史保留

2021-06-21 03:38 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +        self._terminate_procs()
后面增加 logger

2021-06-21 03:44 UTC, Baibaifan commented
lgtm for ascend launch

2021-06-21 03:47 UTC, Baibaifan approved these changes
LGTM for ascend launch

2021-06-21 05:41 UTC, xymyeah approved these changes
LGTM

2021-06-21 06:05 UTC, danleifeng approved these changes
LGTM

2021-06-21 06:06 UTC, merged