Add seqconv pass enhance
PaddlePaddle/Paddle pull request #33455
Opened 2021-06-09 08:21 UTC by tink2123

### PR types

New features
### PR changes

Others
### Describe

Add Seqconv_eltadd_relu_fuse pass enhance

2021-06-10 05:37 UTC, winter-wang requested changes
确认一下 pbtxt文件，有问题的话改一下一起提交。 还有调试一下ci

2021-06-10 05:37 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +#include "paddle/fluid/framework/op_proto_maker.h"
这个头文件不需要

2021-06-10 05:37 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +  AddOpCompat(OpCompat("sequence_conv"))
这个算子名为sequence_conv,需要对应 sequence_conv.pbtxt文件，请确认一下pbtxt文件是没有合入还是文件名写错了，

2021-06-17 09:19 UTC, winter-wang requested changes

2021-06-17 09:19 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextLength")
contexLength添加约束条件IsNumGT(0)

2021-06-17 09:19 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextStride")
contexStride的约束条件改为更严格的IsNumEQ(1)

2021-06-17 09:19 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextStart")
在 AddAttr("contextStart")后面补充注释 // the contextStart attribute can be negative, unconstrained

2021-06-17 09:19 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("axis")
axis补充约束条件  IsIntIn({0, -1})

2021-06-17 09:25 UTC, tink2123 commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextStride")
done, thx

2021-06-17 09:25 UTC, tink2123 commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextLength")
done, thx

2021-06-17 09:25 UTC, tink2123 commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("contextStart")
done, thx

2021-06-17 09:25 UTC, tink2123 commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("axis")
done, thx

2021-06-17 10:41 UTC, winter-wang commented on paddle/fluid/framework/ir/seqconv_eltadd_relu_fuse_pass.cc
> +      .AddAttr("axis")
不好意思，刚刚看了一下ci报错，确认了一下， axis的约束条件应该是  IsNumGT(0)

2021-06-18 05:47 UTC, winter-wang approved these changes
LGTM

2021-06-18 06:09 UTC, Shixiaowei02 approved these changes

2021-06-18 06:10 UTC, merged