fc_elementwise_layer_fuse_pass
PaddlePaddle/Paddle pull request #33467
Opened 2021-06-09 11:32 UTC by fengxiaoshuai

### PR types
others

### PR changes
others

### Describe
fc_elementwise_layernorm_pass

2021-06-10 05:41 UTC, winter-wang requested changes

2021-06-10 05:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .AddAttr("activation_type")
需要补充 activation_type的判定条件

2021-06-10 05:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .End();
缺了axis属性

2021-06-10 05:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +  AddOpCompat(OpCompat("fused_fc_elementwise_layernorm"))
不在@op_name@.pbtxt中的算子不需要进行兼容性检测

2021-06-11 03:15 UTC, winter-wang reviewed
确认一下 element_wise的axis的约束条件

2021-06-11 03:15 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .AddAttr("axis")
请在确认一下axis的判断条件

2021-06-11 09:04 UTC, winter-wang approved these changes
LGTM

2021-06-11 09:35 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .AddAttr("axis")
axis确认是-1，已经修改

2021-06-11 09:35 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +  AddOpCompat(OpCompat("fused_fc_elementwise_layernorm"))
已经删除

2021-06-11 09:36 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .End();
已经添加

2021-06-11 09:36 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/fc_elementwise_layernorm_fuse_pass.cc
> +      .AddAttr("activation_type")
属性限定为relu或者为空

2021-06-11 09:54 UTC, Shixiaowei02 approved these changes

2021-06-11 09:54 UTC, merged