add pass enhance for map_matmul_to_mul_pass and flatten2_matmul_fuse_…
PaddlePaddle/Paddle pull request #33463
Opened 2021-06-09 11:02 UTC by MissPenguin

### PR types

New features
### PR changes

Others
### Describe

add pass enhance for map_matmul_to_mul_pass and flatten2_matmul_fuse_pass

2021-06-10 05:29 UTC, winter-wang requested changes

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
缺条件

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
同上，matmul转mul的话，transpose_X得是false吧

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .AddAttr("transpose_Y")
同上

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumGE(1)
y_num_c ol_dims应该强等于1，而不是大于等于1

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
同上，缺条件。后面的都一样，缺乏条件

2021-06-10 05:29 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +
79行需要补充对mul op的兼容性判断

2021-06-18 07:47 UTC, MissPenguin commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
done, thanks

2021-06-18 07:48 UTC, MissPenguin commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
done, thanks

2021-06-18 07:48 UTC, MissPenguin commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End()
done, thanks

2021-06-18 07:48 UTC, MissPenguin commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +
done, thanks

2021-06-25 11:12 UTC, winter-wang approved these changes
LGTM

2021-06-25 11:12 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumGE(1)
x_num_col_dims的约束应为  IsIntIn({1,2})

2021-06-25 11:15 UTC, Shixiaowei02 approved these changes

2021-06-25 11:15 UTC, merged