Add_pass_enhance: conv_bn_fuse, conv_eltwiseadd_bn_fuse
PaddlePaddle/Paddle pull request #33512
Opened 2021-06-10 12:53 UTC by Wangzheee

### PR types

Others
### PR changes

Others
### Describe

conv_bn_fuse_pass, conv_eltwiseadd_bn_fuse_pass

2021-06-15 13:24 UTC, winter-wang requested changes

2021-06-15 13:24 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("groups")
groups需要有约束条件。

2021-06-15 13:24 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +  AddOpCompat(OpCompat("conv2d"))
缺了对data_format的属性检查

2021-06-15 13:24 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("epsilon")
epsilon缺乏判断条件

2021-06-16 12:26 UTC, winter-wang requested changes

2021-06-16 12:26 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
padding_alporithm缺条件

2021-06-16 12:26 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
缺条件

2021-06-16 12:26 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
同上

2021-06-17 03:50 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
搞 padding_alporithm加个 IsOptional吧

2021-06-17 07:34 UTC, Wangzheee commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
好的

2021-06-17 10:19 UTC, Shixiaowei02 approved these changes, later dismissed

2021-06-18 06:48 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +      .AddAttr("padding_algorithm")
"padding_algorithm"除了一个 IsOptional约束条件，还需要再加一个IsStringIn的约束条件。其它几处"padding_algorithm"同样

2021-06-18 06:51 UTC, winter-wang requested changes
padding_algoroithm除了IsOptional约束条件之外，还需要一个类似IsStringIn的约束条件。

2021-06-18 11:00 UTC, winter-wang approved these changes
LGTM

2021-06-18 11:17 UTC, closed without merging