fix Transpose opdef name
PaddlePaddle/Paddle pull request #33555
Opened 2021-06-15 03:26 UTC by LDOUBLEV

### PR types

Bug fixes 
### PR changes

Others
### Describe

fix wrong name

2021-06-16 08:45 UTC, winter-wang requested changes

2021-06-16 08:45 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .End();
reshape算子有这么多属性吗？请再确认一下

2021-06-16 08:45 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumGT(1)
我没理解错的话，这儿的 y_num_col_dims应该是等于1的，所以应该用IsNumEQ(1)?请在确认一哈

2021-06-16 15:12 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumGT(1)
Done

2021-06-16 15:12 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .End();
fixed, THX

2021-06-17 02:39 UTC, winter-wang requested changes

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("pooling_type")
pooling_type缺乏属性约束

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("exclusive")
exclusive缺乏属性约束

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("ceil_mode")
ceil_mode缺乏属性约束

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("padding_algorithm")
padding_algorithm缺乏属性约束

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("data_format")
data_format缺乏属性约束

2021-06-17 02:39 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .AddInput("X")
reshape2.pbtxt之前写的有点问题，请参考  https://github.com/PaddlePaddle/Paddle/pull/33614 更新reshape2的属性

2021-06-22 03:12 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("pooling_type")
加了属性约束.IsStringIn({"max", "avg"})

2021-06-22 03:16 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("exclusive")
global pooling的时候exclusive 不起作用了，增加了isOptional 约束

2021-06-22 03:18 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("ceil_mode")
global pooling的时候ceil_mode不起作用了，增加了isOptional 约束

2021-06-22 03:18 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("padding_algorithm")
增加了.IsStringIn({"max", "avg"})约束

2021-06-22 03:18 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("data_format")
增加了.IsStringIn({"NHWC", "NCHW"})约束

2021-06-22 03:18 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .AddInput("X")
Thx，已修改

2021-06-22 09:02 UTC, winter-wang requested changes

2021-06-22 09:02 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .End()
Out缺乏IsTensor()约束

2021-06-22 09:02 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("padding_algorithm")
padding_algoritm需要补充一个IsStringIn()的约束

2021-06-22 09:35 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .End()
Done, Thx

2021-06-23 01:53 UTC, LDOUBLEV commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("padding_algorithm")
Done

2021-06-23 06:20 UTC, winter-wang requested changes
我们在兼容性判断中新添加了 IsType<@Type@>()的类型约束，在此之后的pass的attribute的约束条件，除非已经有了 IsStringIn之类的已经约束了类型的前置条件，否则都需要添加 类型约束。

2021-06-23 06:20 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("ksize")
ksize需要添加IsType<std::vector<int>>()约束

2021-06-23 06:20 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .IsOptional()
paddings需要添加 IsType<std::vector<int>> （）的约束

2021-06-23 06:20 UTC, winter-wang commented on paddle/fluid/framework/ir/adaptive_pool2d_convert_global_pass.cc
> +      .AddAttr("ceil_mode")
ceil_mode需要条件IsType<bool>()约束

2021-06-23 06:20 UTC, winter-wang commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .End();
shape需要添加类型约束

2021-06-28 11:33 UTC, winter-wang approved these changes
LGTM

2021-06-28 11:42 UTC, kolinwei approved these changes

2021-06-28 11:53 UTC, merged