enhance Conv elementwise add2 act fuse pass
PaddlePaddle/Paddle pull request #33564
Opened 2021-06-15 06:39 UTC by fengxiaoshuai

### PR types
 Others

### PR changes
Others 

### Describe
enhance conv_elementwise_add2_act_fuse_pass

2021-06-16 09:23 UTC, winter-wang requested changes
90行 framework::OpDesc new_op_desc(new_op_proto, nullptr);
这个也需要兼容性检测

2021-06-16 09:23 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("data_format")
缺属性约束

2021-06-16 09:23 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("groups")
groups缺属性约束。

2021-06-16 09:23 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("axis")
axis缺属性约束

2021-06-18 07:16 UTC, winter-wang requested changes

2021-06-18 07:16 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .IsOptional()
padding_algorithm缺属性约束

2021-06-18 07:16 UTC, winter-wang commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .IsIntIn({1, -1})
IsIntIn({1,-1})后面补个注释吧，说明一下何时为1，何时为-1

2021-06-18 07:16 UTC, winter-wang commented on paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
> +      .AddAttr("use_mkldnn")
extra中的属性不需要注册约束条件

2021-06-18 07:18 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .IsOptional()
这个要把所有的算法都列出来吗？

2021-06-18 07:24 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
> +      .AddAttr("use_mkldnn")
好的

2021-06-18 07:29 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("data_format")
已经添加

2021-06-18 07:30 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("groups")
已经添加

2021-06-18 07:30 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .AddAttr("axis")
已经添加

2021-06-18 08:39 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/conv_elementwise_add2_act_fuse_pass.cc
> +      .IsIntIn({1, -1})
已经添加

2021-06-18 09:12 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/mkldnn/batch_norm_act_fuse_pass.cc
> +      .AddAttr("use_mkldnn")
batch_norm_act_fuse移到其他pr中了，该pr不在考虑

2021-06-18 12:35 UTC, winter-wang approved these changes
LGTM

2021-06-23 11:20 UTC, Shixiaowei02 approved these changes

2021-06-23 11:20 UTC, merged