Add the op def for elementwise_mul and enhance layer_norm_fuse_pass
PaddlePaddle/Paddle pull request #33560
Opened 2021-06-15 05:37 UTC by dyning

### PR types
Others

### PR changes
Others

### Describe
Add the op def for elementwise_mul and enhance pass for layer_norm_fuse_pass

2021-06-15 06:06 UTC, Shixiaowei02 commented on paddle/fluid/operators/compat/elementwise_mul.pbtxt
> +    name: "x_data_format"
请确认 x_data_format 和 y_data_format 是否应为 def 参数

2021-06-15 06:08 UTC, dyning commented on paddle/fluid/operators/compat/elementwise_mul.pbtxt
> +    name: "x_data_format"
我看之前写的都没有在def里面，输入也没有指定

2021-06-15 06:30 UTC, winter-wang commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +LayerNormFusePass::LayerNormFusePass() {
这里是不是缺了对layer_norm算子的检测

2021-06-15 06:34 UTC, winter-wang commented on paddle/fluid/operators/compat/elementwise_mul.pbtxt
> +    name: "x_data_format"
我看opmarker里面的注释，x_data_format 和 y_data_format这两个属性好像已经不再使用了。

2021-07-01 06:43 UTC, winter-wang requested changes

2021-07-01 06:43 UTC, winter-wang commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +      .IsOptional()
Mean输出需要补充IsTensor约束条件

2021-07-01 06:43 UTC, winter-wang commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +      .IsOptional()
Variance需要补充IsTensor约束条件

2021-07-01 06:43 UTC, winter-wang commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +      .AddAttr("dim")
dim需要补充约束 IsType<std::vector<int>>()

2021-07-01 06:43 UTC, winter-wang commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +      .AddAttr("keep_dim")
keep_dim需要补充约束条件

2021-07-02 01:54 UTC, dyning commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +      .AddAttr("keep_dim")
已添加

2021-07-02 01:55 UTC, dyning commented on paddle/fluid/framework/ir/layer_norm_fuse_pass.cc
> +LayerNormFusePass::LayerNormFusePass() {
已添加

2021-07-03 11:03 UTC, winter-wang approved these changes
LGTM

2021-07-08 13:20 UTC, jiweibo approved these changes
LGTM

2021-07-08 13:20 UTC, merged