Add squared_mat_sub_fuse_pass , elementwise_mul.pbtxt and square.pbtxt
PaddlePaddle/Paddle pull request #33597
Opened 2021-06-16 06:59 UTC by fengxiaoshuai

### PR types
Others

### PR changes
Others

### Describe
Add squared_mat_sub_fuse_pass , elementwise_mul.pbtxt and square.pbtxt

2021-06-18 07:20 UTC, winter-wang requested changes

2021-06-18 07:20 UTC, winter-wang commented on paddle/fluid/operators/compat/square.pbtxt
> +}
文件的最后面留一个空行

2021-06-18 07:20 UTC, winter-wang commented on paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
> +      .AddAttr("dtype")
确认一下dtype的取值范围，应该还有一个最大值的

2021-06-18 07:20 UTC, winter-wang commented on paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
> +      .End();
value没有约束条件的话。补充个注释说明一下

2021-06-18 12:47 UTC, fengxiaoshuai commented on paddle/fluid/operators/compat/square.pbtxt
> +}
已经修改

2021-06-18 12:47 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
> +      .AddAttr("dtype")
已经修改

2021-06-18 12:55 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/squared_mat_sub_fuse_pass.cc
> +      .End();
注释已经修改

2021-06-18 12:59 UTC, winter-wang submitted a review, later dismissed
LGTM

2021-06-22 02:46 UTC, winter-wang approved these changes
LGTM

2021-06-22 03:00 UTC, Shixiaowei02 approved these changes

2021-06-22 03:00 UTC, merged