Conv relu mkldnn fuse pass
PaddlePaddle/Paddle pull request #33664
Opened 2021-06-18 13:37 UTC by fengxiaoshuai

### PR types
 Others 

### PR changes
Others

### Describe
enhance conv_relu_mkldnn_pass

2021-06-28 09:17 UTC, winter-wang requested changes

2021-06-28 09:17 UTC, winter-wang commented on paddle/fluid/operators/compat/conv2d.pbtxt
>    attrs {
只是调整一下name的位置？

2021-06-28 09:17 UTC, winter-wang commented on paddle/fluid/operators/compat/relu.pbtxt
> +  }
属性重复添加

2021-06-28 09:17 UTC, winter-wang commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +          << "conv_activation_mkldnn_fuse_pass in out fc op compat failed.";
这个log是不是写的有问题？这儿是fc op 吗

2021-06-28 09:17 UTC, winter-wang commented on paddle/fluid/operators/compat/relu6.pbtxt
>      name: "threshold"
请确认一下 threshold是不是应该属于def?

2021-06-28 09:17 UTC, winter-wang commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +      .IsOptional()
添加IsType<float>() 约束条件，后面类似

2021-06-28 11:35 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +          << "conv_activation_mkldnn_fuse_pass in out fc op compat failed.";
已修改

2021-06-28 11:38 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +      .IsOptional()
全部添加

2021-06-28 11:40 UTC, fengxiaoshuai commented on paddle/fluid/operators/compat/conv2d.pbtxt
>    attrs {
调试导致

2021-06-28 12:01 UTC, fengxiaoshuai commented on paddle/fluid/operators/compat/relu.pbtxt
> +  }
已经删除

2021-06-28 12:23 UTC, fengxiaoshuai commented on paddle/fluid/operators/compat/relu6.pbtxt
>      name: "threshold"
已经修改

2021-06-29 07:21 UTC, winter-wang requested changes

2021-06-29 07:21 UTC, winter-wang commented on paddle/fluid/operators/compat/conv2d.pbtxt
>    attrs {
这个改动我理解没有任何意义，，，没有意义的改动还是不要留着吧

2021-06-29 08:21 UTC, fengxiaoshuai commented on paddle/fluid/operators/compat/conv2d.pbtxt
>    attrs {
好的，已修改

2021-06-30 10:03 UTC, winter-wang requested changes

2021-06-30 10:03 UTC, winter-wang commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +    if (!IsCompat(*desc)) {
这一部分删了吧，不用检测。如果这儿检测失败提前返回的话，graph属于改了一部分的状态，就完蛋了

2021-06-30 12:39 UTC, fengxiaoshuai commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +    if (!IsCompat(*desc)) {
好的，已经删除

2021-07-01 02:27 UTC, winter-wang approved these changes
LGTM

2021-07-01 02:31 UTC, Shixiaowei02 approved these changes

2021-07-01 02:31 UTC, merged