[ pass_enhance ]quant_conv2d_dequant_fuse_pass
PaddlePaddle/Paddle pull request #33737
Opened 2021-06-23 05:52 UTC by Wangzheee

### PR types

Others
### PR changes

Others
### Describe

pass增强：quant_conv2d_dequant_fuse_pass

2021-06-23 06:11 UTC, winter-wang requested changes
除非属性的约束条件可以看出是哪个类型，比如 IsStringIn之类的，，，除此之外都应加上IsType<...>（）的前置条件，来严格规范它的类型

2021-06-23 06:11 UTC, winter-wang commented on paddle/fluid/operators/compat/fake_channel_wise_dequantize_max_abs.pbtxt
> +}
文件最后留一个空行

2021-06-23 06:11 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .End()
quant_bits加约束 IsType<std::vector<int>>()

2021-06-23 06:11 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .IsNumGT(0)
max_range加约束 IsType<float>()或者 IsType<int>()

2021-06-23 06:11 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +  .AddAttr("bit_length").IsIntIn({8, 16}).End();
请问这个 .AddAttr("bit_length")是如何编译过去的尼？

2021-06-23 06:12 UTC, Wangzheee commented on paddle/fluid/operators/compat/fake_channel_wise_dequantize_max_abs.pbtxt
> +}
done

2021-06-23 06:12 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .End()
done

2021-06-23 06:12 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +  .AddAttr("bit_length").IsIntIn({8, 16}).End();
已修改

2021-06-23 08:37 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .IsNumGT(0)
done

2021-06-23 08:39 UTC, winter-wang approved these changes, later dismissed
LGTM

2021-06-25 05:31 UTC, winter-wang requested changes
补充一下部分属性的类型约束

2021-06-25 05:31 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("strides")
添加类型约束

2021-06-25 05:31 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("paddings")
添加类型约束

2021-06-25 05:31 UTC, winter-wang commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("dilations")
类型约束

2021-06-25 05:47 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("strides")
done

2021-06-25 05:48 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("paddings")
done

2021-06-25 05:48 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> +      .AddAttr("dilations")
done

2021-06-25 08:26 UTC, winter-wang approved these changes
LGTM

2021-06-25 08:27 UTC, Shixiaowei02 approved these changes

2021-06-25 08:27 UTC, merged