[ pass_enhance ]transpose_flatten_concat_fuse_pass
PaddlePaddle/Paddle pull request #33744
Opened 2021-06-23 11:34 UTC by Wangzheee

### PR types

Others
### PR changes

Others
### Describe

pass增强: transpose_flatten_concat_fuse_pass

2021-06-25 02:23 UTC, Shixiaowei02 submitted a review, later dismissed

2021-06-25 02:33 UTC, winter-wang requested changes
我们在   https://github.com/PaddlePaddle/Paddle/pull/33770    中，将transpose2的data_format属性由def移到了extra中，因此对transpose2的data_format属性不再需要兼容性检测。请在pr 33770 合入之后，移除data_format属性的兼容性检测，再合入。

2021-06-25 08:52 UTC, winter-wang requested changes

2021-06-25 08:52 UTC, winter-wang commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsIntIn({0, 1, 2, 3})
请确认一下axis这个约束是否正确?

2021-06-25 08:52 UTC, winter-wang commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsIntIn({0, 1, 2, 3})
再确认一下这个axis的范围

2021-06-25 09:25 UTC, Wangzheee commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsIntIn({0, 1, 2, 3})
应该是0，1，2，3，4，5

2021-06-25 09:25 UTC, Wangzheee commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsIntIn({0, 1, 2, 3})
应该是0，1

2021-06-28 11:48 UTC, winter-wang requested changes

2021-06-28 11:48 UTC, winter-wang commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsOptional()
需要一个IsTensor()

2021-06-28 11:48 UTC, winter-wang commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .AddAttr("axis")
这个axis，我理解应该只需要大于等于0就可以，请确认一下

2021-06-28 12:15 UTC, Wangzheee commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .AddAttr("axis")
在fuse的实现中必须要求是0或1，因为flatten之后为2D

2021-06-28 12:15 UTC, Wangzheee commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +      .IsOptional()
done

2021-06-29 03:40 UTC, winter-wang approved these changes
LGTM

2021-06-29 05:57 UTC, Shixiaowei02 approved these changes

2021-06-29 05:57 UTC, merged