[pass_enhance] mul_gru_fuse_pass; fc_gru_fuse_pass
PaddlePaddle/Paddle pull request #33793
Opened 2021-06-27 14:44 UTC by Wangzheee

### PR types

Others
### PR changes

Others
### Describe

PASS增强: mul_gru_fuse_pass; fc_gru_fuse_pass

2021-06-28 11:31 UTC, winter-wang requested changes

2021-06-28 11:31 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
> +      .IsType<std::string>()
IsStringIn

2021-06-28 11:31 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
> +      .End()
IsStringIn

2021-06-28 11:31 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
> +      .IsNumGE(1)
请确认一下约束条件

2021-06-28 11:31 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_gru_fuse_pass.cc
> +      .AddAttr("y_num_col_dims")
请确认一下约束条件

2021-06-30 09:07 UTC, winter-wang approved these changes
LGTM

2021-06-30 09:15 UTC, Shixiaowei02 approved these changes

2021-06-30 09:16 UTC, merged