[pass_enhance] fc_lstm_fuse_pass; mul_lstm_fuse_pass
PaddlePaddle/Paddle pull request #33811
Opened 2021-06-28 08:06 UTC by Wangzheee

### PR types

Others
### PR changes

Others
### Describe

PASS增强: fc_lstm_fuse_pass; mul_lstm_fuse_pass

2021-06-28 11:41 UTC, winter-wang requested changes

2021-06-28 11:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .IsNumGE(1)
请确认一下约束条件

2021-06-28 11:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .IsNumGE(1)
请确认一下约束条件

2021-06-28 11:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .AddAttr("x_num_col_dims")
请确认约束条件

2021-06-28 11:41 UTC, winter-wang commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .IsNumGE(1)
请确认约束条件

2021-06-30 09:10 UTC, Wangzheee commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .IsNumGE(1)
done

2021-06-30 09:10 UTC, Wangzheee commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .AddAttr("x_num_col_dims")
done

2021-06-30 09:10 UTC, Wangzheee commented on paddle/fluid/framework/ir/fc_lstm_fuse_pass.cc
> +      .IsNumGE(1)
done

2021-06-30 09:14 UTC, winter-wang approved these changes
LGTM

2021-06-30 09:16 UTC, Shixiaowei02 approved these changes

2021-06-30 09:16 UTC, merged