[xpu] add dropout & amp ops in xpu place
PaddlePaddle/Paddle pull request #33891
Opened 2021-07-01 06:07 UTC by taixiurong

### PR types
Others

### PR changes
OPs

### Describe
1. add new xpu api of dropout 2. add xpu amp ops 3. fix elewise_add crash when dy is null in xpu place
test=kunlun

2021-07-02 03:07 UTC, QingshuChen requested changes

2021-07-02 03:07 UTC, QingshuChen commented on paddle/fluid/operators/amp/check_finite_and_unscale_op_xpu.cc
> +                                              "XPU API(isfinite) return wrong "
logical_not

2021-07-02 03:07 UTC, QingshuChen commented on paddle/fluid/operators/amp/check_finite_and_unscale_op_xpu.cc
> +                                              "XPU API(any) return wrong "
logical_or

2021-07-02 03:07 UTC, QingshuChen commented on paddle/fluid/operators/amp/check_finite_and_unscale_op_xpu.cc
> +                                              r, XPUAPIErrorMsg[r]));
加xpu_wait

2021-07-02 03:07 UTC, QingshuChen commented on paddle/fluid/operators/amp/update_loss_scaling_op_xpu.cc
> +                          platform::errors::External(
这个错误提示改下，参考check_finite_and_unscale_op_xpu.cc

2021-07-02 03:07 UTC, QingshuChen commented on paddle/fluid/operators/dropout_op_xpu.cc
> +              "XPU dropout return wrong value[%d], please check whether "
错误提示改一下

2021-07-05 02:37 UTC, QingshuChen approved these changes
LGTM

2021-07-07 03:03 UTC, jiweibo approved these changes
LGTM for xpu.cmake

2021-07-07 03:03 UTC, merged