add squeeze_op_npu and test
PaddlePaddle/Paddle pull request #34077
Opened 2021-07-11 06:31 UTC by ronny1996

### PR types

Others 
### PR changes

OPs 
### Describe

add squeeze_op_npu and test

2021-07-11 12:02 UTC, qili93 requested changes

2021-07-11 12:02 UTC, qili93 commented on paddle/fluid/operators/squeeze_op_npu.cc
> +    squeeze_grad, ops::SqueezeGradKernel<plat::NPUDeviceContext, float>,
这里可以直接用CANN的OP Squeeze 和 Unsqueeze 实现？如果要用tensorcopy, 需要在 tensorcopy 之后添加 ctx.template device_context<paddle::platform::NPUDeviceContext>().Wait(); 参考 https://github.com/PaddlePaddle/Paddle/pull/34005 这个宇琪的PR。

2021-07-12 09:34 UTC, qili93 requested changes

2021-07-12 09:34 UTC, qili93 commented on paddle/fluid/operators/squeeze_op_npu.cc
>  #include <string>
这两个头文件是不是可以删掉，后面代码没有用到？

2021-07-12 09:34 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_squeeze_op_npu.py
> +#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
2021？

2021-07-12 09:34 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_squeeze_op_npu.py
> +
如果可以的话，参考test_squeeze_op.py，把TestSqueezeOpError, API_TestSqueeze, API_TestStaticSqueeze_, API_TestDygraphSqueeze, API_TestDygraphSqueezeInplace 改一下NPUPlace上的单测都加上。如果哪个单测case无法支持的话，就注释说明一下原因。

2021-07-12 10:27 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/npu/test_squeeze_op_npu.py
> +#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
已更新

2021-07-12 10:27 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/npu/test_squeeze_op_npu.py
> +
已添加

2021-07-13 03:13 UTC, qili93 approved these changes
LGTM

2021-07-13 03:19 UTC, wanghuancoder approved these changes

2021-07-13 05:58 UTC, merged