[NPU] Add greater_than, not_equal, less_equal ops
PaddlePaddle/Paddle pull request #34098
Opened 2021-07-12 08:27 UTC by Ray2020BD

### PR types

New features
### PR changes

OPs
### Describe

Add following ops for npu:
  greater_than
  not_equal
  less_equal
![image](https://user-images.githubusercontent.com/70498791/125255504-17122d00-e32e-11eb-8275-2fb2364f0ad0.png)

2021-07-15 06:53 UTC, qili93 requested changes

2021-07-15 06:53 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +
这里的单测覆盖度不够，参考test_compare_op.py添加单测用例，特别是boardcast的单测用例，你的C++ OP应该无法支持boardcast的情况，可能还需要修改。

2021-07-15 11:21 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +
现有C++op可以支持broadcast，暂时不需另外修改。单测中已经为这三个op新增了broadcast场景

2021-07-16 03:34 UTC, qili93 requested changes

2021-07-16 03:34 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +
这里的单测设计建议直接复制 test_compare_op.py，修改里面的place等信息支持NPU，然后确保单测通过。test_compare_op.py中通过create_paddle_case来创建多个单测，以减少单测代码长度，否则每个class前还得添加skip it not compiled with npu的代码，整体代码太长了。

2021-07-16 09:12 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +
目前已经参考test_compare_op.py中的方法修改了单测，现在可以使用create函数创造多个单测，未来新增npu算子也可以很好的控制代码长度

2021-07-16 09:20 UTC, qili93 requested changes

2021-07-16 09:20 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +    class PaddleCls(OpTest):
这里还是可以写成@unittest.skipIf(not paddle.is_compiled_with_npu(),
                 "core is not compiled with NPU")的形式

2021-07-16 09:20 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +
没有找到test_compare_op.py里面test_broadcast_api_2之类的单测？尽量参考test_compare_op.py把里面所有单测的case补齐，不支持的就写一下注释说明无法支持的原因，方便后续维护。你可以把其他compare_op的单测也一起改掉。

2021-07-16 12:41 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +    class PaddleCls(OpTest):
已修改

2021-09-29 06:57 UTC, closed without merging