support class center sample of PartialFC
PaddlePaddle/Paddle pull request #34106
Opened 2021-07-12 11:08 UTC by GuoxiaWang

### PR types
New features

### PR changes
APIs

### Describe

class center sample of PartialFC

* support CPU
* support single GPU
* support multi GPU

2021-07-12 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34106) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34106) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34106) it.</sub>

2021-07-16 12:31 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cc
> +REGISTER_OP_WITHOUT_GRADIENT(class_center_sample, ops::ClassCenterSampleOp,
该OP为什么没有反向？

2021-07-18 12:58 UTC, sandyhouse requested changes

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cc
> +REGISTER_OP_WITHOUT_GRADIENT(class_center_sample, ops::ClassCenterSampleOp,
该OP为什么没有反向

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.h
> +    PADDLE_ENFORCE_GT(num_sample, 0,
使用num_samples更符合规范

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +  int64_t sta = 0;
may be start is much easier to understand

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/layers/nn.py
> +    the sampled class centers. Note that if the number of the positive class centers greater than the input
is greater than

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/layers/nn.py
> +    num_sample, it keep all the positive class centers and the shape of sampled_class_center will be
it keeps

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/layers/nn.py
> +    	label: label list, each label in [0, num_classes)
规范格式，比如 label (list):

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/layers/nn.py
> +            'Expected num_sample less equal than {}, got num_sample {}'.format(
be less than or equal to, or just <=

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/tests/unittests/parallel_class_center_sample.py
> +            "mp_degree": self.model_parallel_size,
why use model parallel?

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +namespace ops = paddle::operators;
为什么没有反向实现？

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +                          "The value 'num_sample' for Op(class_center_sample) "
num_samples?

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +                          "must be less than %d, "
<=? or use PADDLE_ENFORCE_LT

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +#endif
What happens when PADDLE_WITH_NCCL or PADDLE_WITH_RCCL is not defined?

2021-07-18 12:58 UTC, sandyhouse commented on paddle/fluid/operators/class_center_sample_op.cu
> +    // step 2: Determine temporary device storage requirements
You'd better to give an illustration on how the algorithm works in the pr description.

2021-07-18 12:58 UTC, sandyhouse commented on python/paddle/fluid/layers/nn.py
> +    	num_classes: A positive integer to specify the number of classes at local rank.
num_classes指得是每个卡自己的类别数？这样是不是和语义有些冲突。更合理的建议是设置全局类别数，通过内部计算得到每张卡的类别数。

2021-07-18 13:39 UTC, GuoxiaWang commented on paddle/fluid/operators/class_center_sample_op.cc
> +REGISTER_OP_WITHOUT_GRADIENT(class_center_sample, ops::ClassCenterSampleOp,
这个Op不需要反向，它的作用只是采样出类别中心，有了类别中心索引，结合 gather 就可以把相应的列取出来，参数在反向网络更新时 gather 会有反向更新参数的操作。

2021-07-18 13:39 UTC, GuoxiaWang commented on paddle/fluid/operators/class_center_sample_op.h
> +    PADDLE_ENFORCE_GT(num_sample, 0,
> 使用num_samples更符合规范

好的

2021-07-18 13:53 UTC, GuoxiaWang commented on paddle/fluid/operators/class_center_sample_op.cu
> +                          "must be less than %d, "
是 <=， 输出忘记没改过来。这里最开始设定是 < 的，但是为了后续测试，<= 可以等价为 sample_ratio = 1.0

2021-07-18 13:54 UTC, GuoxiaWang commented on paddle/fluid/operators/class_center_sample_op.cu
> +#endif
没有的话，就是单机单卡，既然都没有编译分布式，那么必然不能初始化 fleet，所以不存在多卡通信

2021-07-18 13:58 UTC, GuoxiaWang commented on python/paddle/fluid/layers/nn.py
> +    	num_classes: A positive integer to specify the number of classes at local rank.
局部 rank 的类别数更合理，局部的，在算子里通信就可以得到全局的，同时局部类别数可以不一致，天然支持不均等切分。如果是全局的，想在内部算出每张卡被别数，基本可以认为需要均分切分类别数，最多最后一张卡类别数可以和其他卡不一样。

2021-08-10 02:30 UTC, sandyhouse approved these changes, later dismissed
LGTM

2021-08-11 05:35 UTC, sandyhouse submitted a review, later dismissed
LGTM

2021-08-12 07:04 UTC, TCChenlong submitted a review, later dismissed

2021-08-12 07:06 UTC, sandyhouse submitted a review, later dismissed
LGTM

2021-08-12 12:01 UTC, XiaoguangHu01 requested changes

2021-08-12 12:01 UTC, XiaoguangHu01 commented on python/paddle/fluid/layers/nn.py
> +def class_center_sample(label, num_classes, num_samples, group=None, seed=None):
这些代码需要放到python/paddle/nn/functionl目录下，
fluid在paddle2.0不推荐用户使用，原则上不在python/paddle/fluid目录增加新的代码

2021-08-12 12:01 UTC, XiaoguangHu01 commented on python/paddle/fluid/layers/nn.py
> +        np_label = np.random.randint(0, num_classes, (batch_size,), dtype=np.int64)
这里推荐使用paddle.randint，避免引入numpy

2021-08-12 12:01 UTC, XiaoguangHu01 commented on python/paddle/fluid/layers/nn.py
> +        num_classes = np.sum(num_classes_list)
优先使用paddle的原生API paddle.sum或 paddle.randint

2021-08-13 09:42 UTC, sandyhouse approved these changes, later dismissed
LGTM

2021-08-13 09:43 UTC, TCChenlong submitted a review, later dismissed

2021-08-13 09:43 UTC, XiaoguangHu01 approved these changes, later dismissed
LG API

2021-08-15 15:23 UTC, raindrops2sea submitted a review, later dismissed

2021-08-16 03:40 UTC, XieYunshen submitted a review, later dismissed
LGTM

2021-08-16 04:19 UTC, cryoco approved these changes, later dismissed

2021-08-16 05:05 UTC, gongweibao approved these changes, later dismissed
LGTM

2021-08-16 10:45 UTC, XieYunshen approved these changes

2021-08-16 10:47 UTC, TCChenlong approved these changes

2021-08-16 10:47 UTC, cryoco approved these changes

2021-08-16 10:49 UTC, sandyhouse approved these changes
LGTM

2021-08-16 12:58 UTC, raindrops2sea approved these changes

2021-08-17 11:11 UTC, XiaoguangHu01 approved these changes
LG API

2021-08-17 13:30 UTC, gongweibao approved these changes
LGTM

2021-08-18 02:28 UTC, merged