[NPU] Add leaky_relu, exp ops
PaddlePaddle/Paddle pull request #34150
Opened 2021-07-14 06:53 UTC by Ray2020BD

### PR types

New features
### PR changes

OPs
### Describe

Add following ops for npu:
leaky_relu
exp
![image](https://user-images.githubusercontent.com/70498791/125576640-b98d290b-4655-4b14-9e31-9adb951d89bc.png)
![image](https://user-images.githubusercontent.com/70498791/125576817-a5d58445-e780-472f-9561-96842d0d81f6.png)

2021-07-15 06:47 UTC, qili93 requested changes

2021-07-15 06:47 UTC, qili93 commented on paddle/fluid/operators/activation_op_npu.cc
> +                                     {{"negative_slope", alpha}});
这个实现不对，可以参考一下  https://gitee.com/ascend/pytorch 中对应的LeakyReluGrad实现代码，输入1是dout，输入2时x, 输出是dx. 

  cmd.Name("LeakyReluGrad")
      .Input(grad_output)
      .Input(self)
      .Output(result)
      .Attr("negative_slope", negval)
      .Run();

2021-07-15 06:47 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +        return
这里改成pass

2021-07-15 06:47 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +    def calc_leaky_relu(self, x, alpha):
这个可以直接from test_activaiton_op import ref_leaky_relu, 不需要重新实现一遍

2021-07-15 06:47 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +        self.check_output_with_place(self.place, check_dygraph=False)
check_dygraph=False 删掉，因为NPU已经可以支持动态图，后面代码也一样

2021-07-15 06:47 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +        return
这里直接在TestLeadyRelu里面的test_check_grad加一行判断当dtype为fp16则return，后面的子类就不需要重写test_check_grad函数了

2021-07-15 06:47 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +        self.check_output_with_place(self.place, check_dygraph=False)
check_dygraph=False，删掉，NPU已经可以支持动态图了

2021-07-15 12:28 UTC, Ray2020BD commented on paddle/fluid/operators/activation_op_npu.cc
> +                                     {{"negative_slope", alpha}});
已修改

2021-07-15 12:29 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +        return
这里删除了fp16测试类中的test_check_grad，统一在基类的test_check_grad中先判断类型是否是fp16再进行反向测试

2021-07-15 12:29 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +    def calc_leaky_relu(self, x, alpha):
已修改

2021-07-15 12:29 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +        self.check_output_with_place(self.place, check_dygraph=False)
已删除

2021-07-15 12:29 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_leaky_relu_op_npu.py
> +        return
已修改

2021-07-15 12:29 UTC, Ray2020BD commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +        self.check_output_with_place(self.place, check_dygraph=False)
已删除

2021-07-16 03:30 UTC, qili93 submitted a review, later dismissed
LGTM

2021-07-16 09:16 UTC, wanghuancoder submitted a review, later dismissed
LGTM for @unittest.skipIf

2021-09-29 06:57 UTC, closed without merging