support margin loss (arcface, cosface, sphereface) for single GPU and cross GPUs
PaddlePaddle/Paddle pull request #34247
Opened 2021-07-19 12:59 UTC by GuoxiaWang

### PR types
 New features

### PR changes
APIs

### Describe
margin loss, it is a unified loss, which includes arcface, cosface, sphereface

![1](http://latex.codecogs.com/svg.latex?L=-\\frac{1}{N}\\sum^N_{i=1}\\log\\frac{e^{s(cos(m_{1}\\theta_{y_i}+m_{2})-m_{3})}}{e^{s(cos(m_{1}\\theta_{y_i}+m_{2})-m_{3})}+\\sum^n_{j=1,j\\neq%20y_i}e^{scos\\theta_{y_i}}})

The details of margin loss could be referred to https://arxiv.org/abs/1801.07698.

Note that the APIs support model parallel and single GPU. And Logits.shape[-1] can be different each rank.

2021-08-10 02:24 UTC, wadefelix requested changes
code-block指令后应有一个空行

2021-08-10 02:24 UTC, wadefelix commented on python/paddle/nn/functional/loss.py
> +    .. code-block:: python
此行后，应有一个空行。

2021-08-10 02:25 UTC, GuoxiaWang commented on python/paddle/nn/functional/loss.py
> +    .. code-block:: python
> 此行后，应有一个空行。

好的，谢谢

2021-08-10 08:17 UTC, sandyhouse submitted a review, later dismissed
LGTM

2021-08-11 05:35 UTC, sandyhouse submitted a review, later dismissed
LGTM

2021-08-12 06:57 UTC, TCChenlong approved these changes, later dismissed
LGTM

2021-08-12 07:05 UTC, sandyhouse approved these changes, later dismissed
LGTM

2021-08-12 11:53 UTC, XiaoguangHu01 submitted a review, later dismissed
LG API

2021-08-13 09:42 UTC, sandyhouse approved these changes
LGTM

2021-08-13 09:43 UTC, XiaoguangHu01 approved these changes
LG API

2021-08-13 09:43 UTC, TCChenlong approved these changes

2021-08-15 15:23 UTC, raindrops2sea approved these changes

2021-08-16 03:48 UTC, kolinwei approved these changes

2021-08-16 03:49 UTC, chenwhql approved these changes
LGTM for PADDLE_ENFORCE

2021-08-16 03:55 UTC, zhiqiu approved these changes
LGTM for ShareDataWith

2021-08-16 04:54 UTC, XieYunshen approved these changes
LGTM

2021-08-16 05:56 UTC, merged