add one_hot_op and tests
PaddlePaddle/Paddle pull request #34258
Opened 2021-07-20 03:17 UTC by ronny1996

### PR types

Others
### PR changes

OPs
### Describe

add one_hot_op and tests
![image](https://user-images.githubusercontent.com/25691046/126256502-e53b5ab0-2b9d-4d9e-9658-45ef5e06549f.png)

ascend的one-hot算子支持out of range，类似cuda kernel实现

2021-07-20 06:57 UTC, qili93 requested changes

2021-07-20 06:57 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_one_hot_op_npu.py
> +                 "core is not compiled with NPU")
秋良在这个PR https://github.com/PaddlePaddle/Paddle/pull/34240 里面修改了，如果这个PR在秋良的PR之后合入的话，可以把这里的skipIf代码去掉。后面所有的class代码都一样可以去掉。

2021-07-20 06:57 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_one_hot_op_npu.py
> +        self.check_output_with_place(paddle.NPUPlace(0), check_dygraph=False)
check_dygraph=False 删掉，后面的也是

2021-07-20 07:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/npu/test_one_hot_op_npu.py
> +                 "core is not compiled with NPU")
已更新

2021-07-20 07:26 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/npu/test_one_hot_op_npu.py
> +        self.check_output_with_place(paddle.NPUPlace(0), check_dygraph=False)
参考test_one_hot_op.py，删掉check_dygraph=False 会报错

2021-07-23 07:23 UTC, qili93 approved these changes, later dismissed
LGTM

2021-07-23 07:23 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_one_hot_op_npu.py
> +        self.check_output_with_place(paddle.NPUPlace(0), check_dygraph=False)
好的

2021-07-26 08:11 UTC, zhiqiu commented on paddle/fluid/operators/one_hot_op_npu.cc
> +          .AddInput(on_value)
To make code clear, maybe `on_value` and `off_value` can write like `depth`

2021-08-09 03:36 UTC, zhiqiu approved these changes
LGTM

2021-08-09 03:44 UTC, phlrain approved these changes

2021-08-09 05:43 UTC, merged