enable eccl for ascend
PaddlePaddle/Paddle pull request #34358
Opened 2021-07-23 12:56 UTC by lw921014

### PR types

New features
### PR changes

OPs
### Describe

1、enable eccl for ascend
2、add a swtich to for hccl and eccl, and set hccl as default
![image](https://user-images.githubusercontent.com/19748572/126784676-f124514f-1df7-429d-82f5-0a6938fe3fcc.png)

2021-07-27 08:53 UTC, wangxicoding commented on cmake/configure.cmake
> +    if(WITH_ECCL STREQUAL WITH_HCCL)
两个都是OFF直接报错了吧

2021-07-27 08:53 UTC, wangxicoding commented on paddle/fluid/operators/collective/CMakeLists.txt
> +    op_library(c_gen_eccl_id_op DEPS ${COLLECTIVE_DEPS})
gen_eccl_id_op少了？

2021-07-27 08:53 UTC, wangxicoding commented on paddle/fluid/operators/collective/c_allgather_op_npu.cc
> +        reinterpret_cast<void *>(stream), AUTO));
这个AUTO是啥

2021-07-27 08:53 UTC, wangxicoding commented on paddle/fluid/operators/collective/c_gen_eccl_id_op.cc
> +               const platform::Place& dev_place) const override {}
是不是得报错

2021-07-27 08:53 UTC, wangxicoding commented on paddle/fluid/operators/collective/c_gen_eccl_id_op.cc
> +    VLOG(3) << "ele";
删掉？

2021-07-27 08:53 UTC, wangxicoding commented on paddle/fluid/platform/enforce.h
> +#define PADDLE_ENFORCE_ECCL_SUCCESS(COND)                      \
这个不用加吧，PADDLE_ENFORCE_NPU_SUCCESS里面包括了

2021-07-27 11:13 UTC, lw921014 commented on cmake/configure.cmake
> +    if(WITH_ECCL STREQUAL WITH_HCCL)
是的，两个都是ON也报错了，所以合并到一起了，就是这两个是一样的情况，就都要报错~

2021-07-27 11:13 UTC, lw921014 commented on paddle/fluid/operators/collective/CMakeLists.txt
> +    op_library(c_gen_eccl_id_op DEPS ${COLLECTIVE_DEPS})
是不是只要留下c_gen_eccl_id_op就可以了？

2021-07-27 11:13 UTC, lw921014 commented on paddle/fluid/operators/collective/c_allgather_op_npu.cc
> +        reinterpret_cast<void *>(stream), AUTO));
这个是eccl算法选择的一个接口，后续会接入不同的算法

2021-07-27 11:13 UTC, lw921014 commented on paddle/fluid/operators/collective/c_gen_eccl_id_op.cc
> +    VLOG(3) << "ele";
好的，马上删除~

2021-07-27 11:28 UTC, lw921014 commented on paddle/fluid/operators/collective/c_gen_eccl_id_op.cc
> +               const platform::Place& dev_place) const override {}
是的，马上加上了~

2021-07-28 13:02 UTC, wangxicoding commented on cmake/configure.cmake
> +    if(WITH_ECCL STREQUAL WITH_HCCL)
这个不太行吧，如果编译Inference包之类的，不需要通信的op，那这个就会报错了

2021-07-28 13:55 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_comm_init_eccl_op.cc
> +
缺少HCCL建连传假数据的过程，参考下paddle更改后的c_comm_init_eccl_op.cc的代码。

2021-07-29 02:23 UTC, lw921014 commented on paddle/fluid/operators/collective/c_comm_init_eccl_op.cc
> +
这一块会放在库里面实现~就在libeccl.so中实现，不会暴露出来，保证接口语义的完整性~

2021-07-29 02:24 UTC, lw921014 commented on paddle/fluid/operators/collective/c_comm_init_eccl_op.cc
> +
这一块会放在库里面实现~就在libeccl.so中实现，不会暴露出来，保证接口语义的完整性~

2021-07-30 04:26 UTC, gongweibao requested changes

2021-07-30 04:26 UTC, gongweibao commented on CMakeLists.txt
> +option(WITH_HCCL        "Compile PaddlePaddle with HCCL in ASCEND platform"       ON)
HCCL为何默认ON？ ${WITH_ASCEND}

2021-07-30 04:26 UTC, gongweibao commented on CMakeLists.txt
> +option(WITH_ECCL        "Compile PaddlePaddle with ECCL in ASCEND platform"       OFF)
ECCL=(NCCL+HCCL+others)
应该把这个开关关系捋清楚？

2021-07-30 04:26 UTC, gongweibao commented on paddle/fluid/operators/collective/c_allgather_op_npu.cc
> +    PADDLE_ENFORCE_ECCL_SUCCESS(platform::dynload::eccl_all_gather(
除了eccl_all_gather 名字换了，前边的逻辑跟hccl的实现有区别吗？
用一个#if #else就可以搞定？

2021-07-30 04:26 UTC, gongweibao commented on paddle/fluid/operators/collective/c_allgather_op_npu.cc
> +        reinterpret_cast<void *>(stream), AUTO));
https://google.github.io/styleguide/cppguide.html#Default_Arguments

2021-07-30 04:26 UTC, gongweibao commented on paddle/fluid/operators/collective/c_allreduce_op.h
> +    PADDLE_ENFORCE_ECCL_SUCCESS(platform::dynload::eccl_all_reduce(
同前边！

2021-07-30 04:28 UTC, gongweibao requested changes
partial_send/recv op没有合并进来？
我觉得是否是把hccl的原生调用做一个adapter封装一下，然后在adapter内部做一下#if #else的判断走不同的逻辑（hccl，eccl）就不用该这么多文件了？

2021-07-30 07:32 UTC, lw921014 commented on cmake/configure.cmake
> +    if(WITH_ECCL STREQUAL WITH_HCCL)
当编译inference的时候with_ascend_cl设置为ON还是OFF？理论上目前这个接入只和with_ascend_cl相关，并且和之前的功能保持一致的~
我看之前那的ascend的接口都没有考虑推理中的通信op如何设置，是不是要后续再考虑？

2021-07-30 07:48 UTC, lw921014 commented on CMakeLists.txt
> +option(WITH_ECCL        "Compile PaddlePaddle with ECCL in ASCEND platform"       OFF)
是的，这个开关的设计逻辑是，尽可能保持原来HCCL的接口和代码不变的情况下引入eccl，这也就是为何每个op都一个eccl的实现类而不是在原来代码上加if else的原因，避免污染之前hccl的代码，影响现在的调试。这个开关工作的原理，我理解是这样的：
当WITH_ASCEND_CL=ON的时候，WITH_HCCL和WITH_ECCL至少有一个为0N才是正确的，如果这两个都是ON 或者 都是OFF，cmake的时候都会报错；默认的情况下，WITH_HCCL=ON，cmake 的选项不需要做任何修改，此时使用的就是之前的hccl的接口，代码也和之前的保持一致，不会引入新的代码，影响现在调试；如果想使用ECCL，需要在cmake的时候加上 -DWITH_HCCL=OFF，-D WITH_ECCL=ON。
当WITH_ASCEND_CL = OFF的时候，会在config.cmake中回强制把WITH_HCCL=OFF，WITH_ECCL=OFF，此时不会输出ascend上的通信op。
这样的逻辑不知道是否合理？当然有点冗余，主要考虑到大部分情况下还是使用原来的hccl，所以不想污染之前的代码，影响调试。当然目前引入的eccl 1.0是一个中间态产品，只支持在ascend上的hccl，作为hccl的备用技术，至于nccl，目前还是通过paddle的WITH_NCLL接口引入，和eccl无关。后续，ECCL2.0接入的时候，才会接管nccl，bkl，rccl等其他通信接口。

2021-07-30 09:14 UTC, lw921014 commented on paddle/fluid/operators/collective/c_allgather_op_npu.cc
> +    PADDLE_ENFORCE_ECCL_SUCCESS(platform::dynload::eccl_all_gather(
有区别，commcotext有差别，总归是要修改挺多的~

2021-07-30 09:19 UTC, lw921014 commented on paddle/fluid/operators/collective/c_allreduce_op.h
> +    PADDLE_ENFORCE_ECCL_SUCCESS(platform::dynload::eccl_all_reduce(
我理解接入是关键，后续可能hccl这个分支会删除，保留eccl的

2021-08-01 04:11 UTC, gongweibao requested changes
重复代码太多，这样不行。
HCCL分支的代码并未完全成熟，如果发现问题，就要两个分支都改，出错的概率太高。

2021-08-01 04:11 UTC, gongweibao commented on paddle/fluid/pybind/CMakeLists.txt
> +  set(OP_FUNCTION_GENERETOR_DEPS pybind proto_desc executor layer tracer engine imperative_profiler imperative_flag)
这个文件其实不用改。后边可能会又更多的diff出来。

2021-08-01 04:11 UTC, gongweibao commented on paddle/fluid/platform/enforce.h
> +#define PADDLE_ENFORCE_ECCL_SUCCESS(COND)                      \
即便加了，也不能拷贝过来，而是直接转到NPU_SUCCESS上

2021-08-01 04:11 UTC, gongweibao commented on cmake/external/ascend.cmake
> +    set(ascend_ccl_lib ${ASCEND_CL_DIR}/libeccl.so)
加上版本，更加的容易控制迭代。

2021-08-02 05:59 UTC, lw921014 commented on CMakeLists.txt
> +option(WITH_HCCL        "Compile PaddlePaddle with HCCL in ASCEND platform"       ON)
ok，已经修改为${WITH_ASCEND_CL}

2021-08-02 08:25 UTC, lw921014 commented on cmake/external/ascend.cmake
> +    set(ascend_ccl_lib ${ASCEND_CL_DIR}/libeccl.so)
目前通过安装的时候，使用软链来管理

2021-08-03 03:48 UTC, lw921014 commented on paddle/fluid/pybind/CMakeLists.txt
> +  set(OP_FUNCTION_GENERETOR_DEPS pybind proto_desc executor layer tracer engine imperative_profiler imperative_flag)
已经复原~

2022-08-26 08:55 UTC, closed without merging