Identity OP
PaddlePaddle/Paddle pull request #34420
Opened 2021-07-27 08:18 UTC by shiyutang

### PR types

New features

### PR changes

OPs

### Describe
Add Identity op as torch.Identity, if we define the "m" as the identity layer, it creates following results
![Ineut-tensor - poddle to-tensorCmrpy rondon rondnC1z, 20))](https://user-images.githubusercontent.com/34859558/127119995-97dfc730-c6fb-494a-aa3c-2244084649fe.png)

2021-07-27 08:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34420) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34420) it.</sub>

2021-07-28 03:59 UTC, ZHUI requested changes

2021-07-28 03:59 UTC, ZHUI commented on python/paddle/fluid/tests/unittests/test_identity_op.py
> +class TestDiagonalAPI(unittest.TestCase):
TestDiagonalAPI?

2021-07-28 03:59 UTC, ZHUI commented on python/paddle/nn/layer/common.py
> +         input_tensor = paddle.to_tensor(numpy.random.randn(128, 20))
Use paddle.randn, you can delete numpy

2021-07-28 03:59 UTC, ZHUI commented on python/paddle/nn/layer/common.py
> +         print('input_tensor.grad', input_tensor.grad)
Please show the usage of Identity layer.

2021-07-28 04:48 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_identity_op.py
> +class TestDiagonalAPI(unittest.TestCase):
changed to TestIdentityAPI

2021-07-28 09:50 UTC, ZHUI requested changes

2021-07-28 09:50 UTC, ZHUI commented on python/paddle/nn/layer/common.py
> +          input_tensor = paddle.to_tensor(paddle.randn(shape=[3, 2]))
No need for `paddle.to_tensor`

2021-07-28 09:50 UTC, ZHUI commented on python/paddle/nn/layer/common.py
> +          layer = paddle.nn.Identity(54)
what's the means of `54`?

2021-07-28 09:50 UTC, ZHUI commented on python/paddle/nn/layer/common.py
> +          out = m(input_tensor)
`out = m(input_tensor)` -> `out = layer(input_tensor)`
You can delete the calculation of gradient in the example.

2021-07-28 09:53 UTC, shiyutang commented on python/paddle/nn/layer/common.py
> +          input_tensor = paddle.to_tensor(paddle.randn(shape=[3, 2]))
ok

2021-07-28 09:55 UTC, shiyutang commented on python/paddle/nn/layer/common.py
> +          layer = paddle.nn.Identity(54)
means any parameters, I will delete it

2021-07-28 12:22 UTC, michaelowenliu approved these changes, later dismissed
LGTM

2021-07-29 02:20 UTC, michaelowenliu approved these changes

2021-07-29 02:26 UTC, ZHUI approved these changes
LGTM

2021-08-02 03:54 UTC, jzhang533 commented on python/paddle/nn/layer/common.py
> +    A placeholder identity operator that is argument-insensitive. For each input :math:`X` ,
只支持一个输入，一个输出吧。
这里用`for each`，感觉是支持多个输入的。

2021-08-02 06:52 UTC, merged