[NPU] fix npu pipeline comm init
PaddlePaddle/Paddle pull request #34466
Opened 2021-07-28 12:26 UTC by wangxicoding

### PR types

Others
### PR changes

Others
### Describe

Fix npu hccl pipeline comm init failed.

2021-07-30 03:40 UTC, Baibaifan submitted a review, later dismissed
LGTM for NPU

2021-07-30 03:41 UTC, gongweibao commented on python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
> +            def init_pair_comm(pair, ring_id):
NPU和其他的分支（GPU）的分开吧。不然后来人很难理解这段代码。

2021-07-30 04:01 UTC, gongweibao requested changes

2021-07-30 04:01 UTC, gongweibao commented on python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
> +                print("pair0(even->odd): pp pair:{}, ring_id: {}".format(
同上

2021-07-30 04:01 UTC, gongweibao commented on python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
> +                    print("pp pair:{}, ring_id: {}".format(pair, ring_id))
这个日志能否用输入参数控制？用户默认不需要关心这些日志输出。

2021-07-30 04:01 UTC, gongweibao commented on python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
> +                print("pair1(even<-odd): pp pair:{}, ring_id: {}".format(
同上

2021-07-30 04:01 UTC, gongweibao commented on python/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py
> +                # FIXME(wangxi): some bug with hccl, must set pp_degree be even number
这段代码太长，单独封装个函数？

2021-08-01 14:43 UTC, kolinwei approved these changes

2021-08-01 16:11 UTC, gongweibao approved these changes
LGTM

2021-08-01 16:11 UTC, merged