add api fill_diagonal_inplace
PaddlePaddle/Paddle pull request #34460
Opened 2021-07-28 10:06 UTC by zhiboniu

### PR types

Others
### PR changes

APIs
### Describe

add api fill_diagonal_inplace

2021-08-02 13:08 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_inplace_op.cc
> +                  "bottom-left corner")
说明改一下？

2021-08-02 13:11 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_inplace_op.cc
> +              "Tensor, the clipped tensor, with the same shape and data type "
“the clipped tensor”的说明在这里有什么特殊意义不，是否去掉？

2021-08-05 03:21 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_inplace_op.cc
> +                  "bottom-left corner")
done

2021-08-05 03:21 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_inplace_op.cc
> +              "Tensor, the clipped tensor, with the same shape and data type "
done，已修改

2021-08-06 03:42 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    T *out_data = out->mutable_data<T>(ctx.GetPlace());
常规做法是先 out->mutable_data 分配内存后再使用 TensorCopy，这里反过来是否有特殊考虑

2021-08-06 03:50 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_op.cu
> +    T* out_data = out->mutable_data<T>(ctx.GetPlace());
常规做法是先 out->mutable_data 分配内存后再使用 TensorCopy，这里反过来是否有特殊考虑

2021-08-06 04:03 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_op.cc
> +          data[i] = static_cast<T>(doutdata[i]);
反向的逻辑中是否也可以使用TensorCopy 批量实现数据cp

2021-08-06 04:03 UTC, jeff41404 commented on paddle/fluid/operators/fill_diagonal_op.cu
> +      dst_data[idx] = const_cast<T&>(src_data[idx]);
反向的逻辑中是否也可以使用TensorCopy 批量实现数据cp

2021-08-06 09:13 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    T *out_data = out->mutable_data<T>(ctx.GetPlace());
done, TensorCopy中也有out->mutable_data，所以其实都可以。不过也已经修改。

2021-08-06 09:13 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cu
> +    T* out_data = out->mutable_data<T>(ctx.GetPlace());
done，同上已修改。

2021-08-06 09:13 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cc
> +          data[i] = static_cast<T>(doutdata[i]);
done，已修改。

2021-08-06 09:14 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cu
> +      dst_data[idx] = const_cast<T&>(src_data[idx]);
done，已修改。

2021-08-09 09:02 UTC, jiangjiajun requested changes

2021-08-09 09:02 UTC, jiangjiajun commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    AddAttr<float>(
value只能是float吗

2021-08-09 09:02 UTC, jiangjiajun commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    // retv->SetInput("Out", this->Output("Out"));
注释的代码如无需要就直接删除吧

2021-08-09 09:02 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/test_tensor_fill_diagonal_.py
> +        typelist = ['float32', 'float64', 'int32', 'int64']
Kernel注册了Bool类型，也加上bool类型的测试

2021-08-12 12:42 UTC, zhiboniu commented on python/paddle/fluid/tests/unittests/test_tensor_fill_diagonal_.py
> +        typelist = ['float32', 'float64', 'int32', 'int64']
done

2021-08-12 12:42 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    // retv->SetInput("Out", this->Output("Out"));
done

2021-08-13 02:52 UTC, zhiboniu commented on paddle/fluid/operators/fill_diagonal_op.cc
> +    AddAttr<float>(
以float类型读取python数值，然后填入时转化为实际类型填入。

2021-08-13 06:45 UTC, jiangjiajun submitted a review, later dismissed
LGTM

2021-08-13 06:58 UTC, jzhang533 submitted a review, later dismissed
LGTM

2021-08-13 09:21 UTC, XiaoguangHu01 approved these changes, later dismissed
LG API

2021-08-13 09:21 UTC, XiaoguangHu01 commented on python/paddle/tensor/manipulation.py
> +        name(str,optional): Name for the operation (optional, default is None)
wrap参数缺少说明

2021-08-13 09:33 UTC, zhiboniu commented on python/paddle/tensor/manipulation.py
> +        name(str,optional): Name for the operation (optional, default is None)
done, 已添加

2021-08-16 04:37 UTC, XiaoguangHu01 approved these changes
LG API

2021-08-16 08:03 UTC, jzhang533 approved these changes
LGTM

2021-08-17 03:20 UTC, jeff41404 approved these changes
LGTM

2021-08-17 03:22 UTC, merged