Allreduce optim
PaddlePaddle/Paddle pull request #34509
Opened 2021-07-30 08:05 UTC by FeixLiu

### PR types
Performance optimization

### PR changes
Others

### Describe
Increase the overlap of the calc stream and comm stream after fusing the allreduce vars

2021-08-02 12:25 UTC, wangxicoding requested changes

2021-08-02 12:25 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        if not segment:
if self.calc_comm_same_stream?

2021-08-02 12:25 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    "copy_data": True,
理论上这个copy_data可以优化掉

2021-08-02 12:25 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    inputs={'X': segment[0]},
理论上这个同步可以放到更后面，allreduce和optimize也可以overlap一些

2021-08-02 12:44 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        if not segment:
agree, will update

2021-08-03 01:05 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    inputs={'X': segment[0]},
will update in later op

2021-08-03 01:06 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    "copy_data": True,
will discuss this offline

2021-08-04 03:46 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        param_segments = []
感觉可以搞到一起param_grad_segments，然后插入用tuple (param, grad)好看点

2021-08-04 03:46 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        for i in range(len(grad_segments) - 1, -1, -1):
-1, -1, -1，逻辑有点绕，最好搞个好看懂的逻辑或者加点注释，比如len=4，则4->3->2->1->0

2021-08-04 03:46 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                # find the offset of the sync op and allreduce op
注释写详细点，把这么做的原因写出来，op可能有多个[param, grad]对，若当前segment最后一个grad和下一个segment第一个梯度在同一个op上，则下一个segment在这个op前面插入过了`coalesce_tensor_op`，所以需要+1

2021-08-04 03:46 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                before_idx,
这个地方可能有风险(不是很确定)，梯度可能在before_idx之前就生成了，before_idx只不过是最后一次生成的地方（可以调研下有没有inplace操作有这样的情况）。
可以遍历一下op，记录一下grad_to_generate_op_idx，再找到segment中梯度最开始生成的位置

2021-08-04 03:46 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                persistable=True,
如果coalesce_tensor_op在main_program里，不用设置persistable

2021-08-04 05:59 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                persistable=True,
updated

2021-08-04 05:59 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                # find the offset of the sync op and allreduce op
will do

2021-08-04 06:00 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        for i in range(len(grad_segments) - 1, -1, -1):
👌

2021-08-04 06:01 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        param_segments = []
👍

2021-08-04 06:39 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                before_idx,
updatead

2021-08-04 11:20 UTC, wangxicoding requested changes

2021-08-04 11:20 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    first_backward_idx = idx
`OP_ROLE_VAR_KEY in op.attr_names`，这个应该叫作first_op_role_var_idx了吧

2021-08-04 11:39 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            for idx in range(first_backward_idx, len(block.ops)):
复杂度有点高，O(n2)，搞成O(n)的

2021-08-04 11:40 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                if after_idx == grads_to_idx[grad_param_segments[j][0][0]]:
逻辑又有新的问题了

2021-08-05 01:31 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                    first_backward_idx = idx
update

2021-08-05 01:31 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            for idx in range(first_backward_idx, len(block.ops)):
空间换时间的话，可以o(n)

2021-08-05 01:32 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                if after_idx == grads_to_idx[grad_param_segments[j][0][0]]:
是有点，grads_to_idx应该分开存最前和最后idx了

2021-08-05 08:17 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        # which is used to indicate teh position to  insert sync and allreduce op
teh->the，注释的标点加一加

2021-08-05 08:17 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                if after_idx == outputs_name_to_idx[grad_param_segments[j][0][
假如最后一组sgements的coalesce_tensor插入到最前面，那么遍历后续的segments时，offset都得+1

2021-08-06 03:18 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +        # which is used to indicate teh position to  insert sync and allreduce op
🥵 ok

2021-08-10 02:25 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +                if after_idx == outputs_name_to_idx[grad_param_segments[j][0][
updated, 先插入sync allreduce，然后更新outputs_name_to_idx再插入coalesce

2021-08-11 02:37 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            before_idx = outputs_name_to_idx[grad_segment[0]][0]
for grad_segment 然后找到最小的那个idx；for i 部分组成(idx, i)；排序；
再插入

2021-08-11 02:37 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            before_idx = outputs_name_to_idx[grad_segment[0]][0]
grad_segment找到最小的。然后按照(idx, i)排序，插入

2021-08-11 02:37 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            pos_for_coalesce.items(), key=lambda x: x[1], reverse=True)
key=lambda kv: (kv[1], kv[0])
可能出现value相同的情况，加上key作稳定排序

2021-08-11 02:46 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            pos_for_coalesce.items(), key=lambda x: x[1], reverse=True)
soted是stable的，在上面是逆序idx插入的，譬如{9: 200, 8: 190, 7: 180, 6: 100, 5: 100, 4: 170, 3: 90, 2: 90, 1: 90}的sorted之后的结果一定是[(9, 200), (8, 190), (7, 180), (4, 170), (6, 100), (5, 100), (3, 90), (2, 90), (1, 90)]这样的，6和5，3、2和1的顺序是一定不变的。https://docs.python.org/3/library/functions.html#sorted

2021-08-11 02:53 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/raw_program_optimizer.py
> +            pos_for_coalesce.items(), key=lambda x: x[1], reverse=True)
已更新，可能存在dict乱序的情况（python3.6之前）

2021-08-11 03:03 UTC, wangxicoding approved these changes
LGTM

2021-08-11 05:26 UTC, merged