[NPU] Support npu op reciprocal and reciprocal grad
PaddlePaddle/Paddle pull request #34531
Opened 2021-08-02 05:22 UTC by limin2021

### PR types
New features

### PR changes
OPs

### Describe
[NPU] Support npu op reciprocal and reciprocal grad

说明：
1) 数据类型支持：
   CANN库中的reciprocal api支持的数据类型有float, float16, double, int32, int64, complex64, complex128。
   本PR添加的数据类型有：float, float16, double, int32, int64。
2) 为避免重复，单测测试用例只测试了fp32和fp16的情形。

#### 运行结果

- 单测运行结果
![test-res](https://user-images.githubusercontent.com/11663212/127807641-7ceeff3a-2af6-4b2a-b842-5277c8690abf.png)

- 调用 reciprocal npu kernel 和 reciprocal grad npu kernel
![log](https://user-images.githubusercontent.com/11663212/127808044-d602230c-d660-4f84-8a9a-67e317807dcc.png)

2021-08-02 06:36 UTC, zhangting2020 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +paddle.enable_static()
- 如果不是用API组网，静态图执行的方式写单测，这个enable_static应该是没有必要的
- 上面的import，看看没有必要的也可以删掉了

2021-08-02 06:36 UTC, zhangting2020 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +
FP16类型不用check_grad吗？这个NPU算子开发要求里有没有明确提到

2021-08-02 06:36 UTC, zhangting2020 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +        pass
init_kernel_type这个方法在哪里用到了吗？

2021-08-02 06:36 UTC, zhangting2020 commented on paddle/fluid/operators/activation_op_npu.cc
> +    const auto& runner = NpuOpRunner("Reciprocal", {*x}, {*out}, {});
上面每一行之间的空行建议删除，下同

2021-08-02 06:36 UTC, zhangting2020 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +        self.__class__.no_need_check_grad = True
如果fp16类型确定不需要梯度检查，需要使用skip_check_grad_ci装饰器，并描述原因（可以在源码里搜索下参考下别的单测）

2021-08-02 06:36 UTC, zhangting2020 commented on paddle/fluid/operators/activation_op_npu.cc
> +                                 paddle::platform::float16>);
看PR描述里提到 complex64, complex12是可以支持的，但这里没有注册，需要确认下开发要求

2021-08-02 06:54 UTC, limin2021 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +
参见[NPU开发算子文档](http://agroup.baidu.com/yoki/md/article/4161053#2%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B-cann-op-%E7%9A%84%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3)：check_grad_with_place检查反向梯度时，不支持对float16数据类型的检查，不用写相关单测。

2021-08-02 06:55 UTC, limin2021 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +        pass
Remove.

2021-08-02 06:55 UTC, limin2021 commented on paddle/fluid/operators/activation_op_npu.cc
> +    const auto& runner = NpuOpRunner("Reciprocal", {*x}, {*out}, {});
Done.

2021-08-02 06:55 UTC, limin2021 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +paddle.enable_static()
Done.

2021-08-02 07:04 UTC, limin2021 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +        self.__class__.no_need_check_grad = True
Done.

2021-08-02 07:06 UTC, limin2021 commented on paddle/fluid/operators/activation_op_npu.cc
> +                                 paddle::platform::float16>);
已确定开发需求（@彭宇琪）：npu上支持的数据类型与cpu上保持一致即可。故最终调整支持的数据类型为float, double和float16.

2021-08-03 03:18 UTC, qili93 requested changes

2021-08-03 03:18 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +
建议增加对double数据类型的单测，C++算子支持的数据类型要尽量在单测中覆盖

2021-08-03 04:15 UTC, limin2021 commented on python/paddle/fluid/tests/unittests/npu/test_reciprocal_op_npu.py
> +
Done. 
测试fp64类型时，报了如下错误：
`ExternalError: ACL error, the error code is : 500002. (at /workspace/limin-workspace/npu-paddle/Paddle/paddle/fluid/operators/npu_op_runner.cc:380) 1226: [operator < mean > error]。`
原因：reciprocal的单测（反向）会自动添加mean op，但是mean的前向ReduceMeanD不支持double和int，注册mean kernel时却支持了fp64和int类型。
解决：将mean_op_npu.cc中对double和int类型的支持去掉。

2021-08-03 04:19 UTC, qili93 approved these changes
LGTM

2021-08-03 04:23 UTC, zhangting2020 approved these changes
LGTM

2021-08-03 08:12 UTC, merged