Add EmptyGradOpMaker CI Approval
PaddlePaddle/Paddle pull request #34552
Opened 2021-08-02 09:59 UTC by LaJiOJ

### PR types

Others

### PR changes

Others

### Describe

CI pipeline will support checking illegal usage of `EmptyGradOpMaker` class or `REGISTER_OP_WITHOUT_GRADIENT` macro after this PR. It would be helpful to enhance the robustness of codes.

To be more specific, before using
```c++
REGISTER_OP_WITHOUT_GRADIENT(...);
```
and
```c++
REGISTER_OPERATOR(
  ...
  paddle::framework::EmptyGradOpMaker<paddle::framework::OpDesc>,
  paddle::framework::EmptyGradOpMaker<paddle::imperative::OpBase>);
```
, one should ask for approval from at least one RD (phlrain, JiabinYang or XiaoguangHu01).

2021-08-03 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34552) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: LaJiOJ<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34552) it.</sub>

2021-08-11 07:37 UTC, JiabinYang approved these changes
LGTM

2021-08-11 07:40 UTC, JiabinYang requested changes
Add Weike into reviewer of `Empty Grad`

2021-08-11 08:31 UTC, LaJiOJ commented
Something went wrong with this branch on my laptop. I reopened a new pull request at [PR34807](https://github.com/PaddlePaddle/Paddle/pull/34807). Thus, this pull request will be closed from now on.

2021-08-11 08:46 UTC, closed without merging