add not_equal NPU op
PaddlePaddle/Paddle pull request #34560
Opened 2021-08-02 12:50 UTC by baoachun

### PR types
New features

### PR changes
OPs

### Describe
add not_equal NPU op
![图片](https://user-images.githubusercontent.com/22114318/127864555-12eb9905-2aff-4d08-a4ab-d122295cf1b6.png)
![图片](https://user-images.githubusercontent.com/22114318/127864694-121b4a48-25d4-436a-ac55-cfac13b55ac9.png)

2021-08-02 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34560) it.</sub>

2021-08-02 13:01 UTC, jiweibo commented on paddle/fluid/operators/controlflow/compare_op_npu.cc
> +    // ops::LessEqualNPUKernel<plat::NPUDeviceContext, uint16_t>,
需要支持数据类型的问题请 @qili93 关注下

2021-08-03 02:53 UTC, qili93 requested changes

2021-08-03 02:53 UTC, qili93 commented on paddle/fluid/operators/controlflow/compare_op_npu.cc
> +    // ops::LessEqualNPUKernel<plat::NPUDeviceContext, uint16_t>,
这里的数据类型对应CANN的以下数据类型，都可以支持
  static TensorType RealNumberType() {
    return TensorType{DT_DOUBLE, DT_FLOAT,  DT_FLOAT16, DT_INT16,  DT_INT32, DT_INT64,
                      DT_INT8,   DT_UINT16, DT_UINT32,  DT_UINT64, DT_UINT8, DT_BF16};
  }

2021-08-03 02:53 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +for _type_name in {'float16', 'float32', 'int32', 'int64'}:
在C++算子中支持的所有数据类型都需要在单测里面跑一下验证一下

2021-08-03 03:18 UTC, baoachun commented on paddle/fluid/operators/controlflow/compare_op_npu.cc
> +    // ops::LessEqualNPUKernel<plat::NPUDeviceContext, uint16_t>,
已注释的数据类型paddle不支持，取消注释编译会报错

2021-08-03 06:22 UTC, baoachun commented on python/paddle/fluid/tests/unittests/npu/test_compare_op_npu.py
> +for _type_name in {'float16', 'float32', 'int32', 'int64'}:
单测这边只支持bool、float32、float64、int32、int64，因此只添加了equal算子支持的bool类型

2021-08-05 03:09 UTC, qili93 requested changes

2021-08-05 03:09 UTC, qili93 commented on paddle/fluid/operators/controlflow/compare_op_npu.cc
> +    // ops::LessEqualNPUKernel<plat::NPUDeviceContext, uint16_t>,
注释掉的数据类型都从代码里面删除一下，Paddle尽量不包含冗余代码，如果需要有需要说明的地方可以卸载注释里面

2021-08-05 03:16 UTC, baoachun commented on paddle/fluid/operators/controlflow/compare_op_npu.cc
> +    // ops::LessEqualNPUKernel<plat::NPUDeviceContext, uint16_t>,
done

2021-08-05 04:54 UTC, qili93 approved these changes
LGTM

2021-08-05 04:54 UTC, merged