[NPU] Support npu kernel for assign_value op
PaddlePaddle/Paddle pull request #34568
Opened 2021-08-03 02:43 UTC by betterpig

### PR types
New features

### PR changes
OPs && Others

### Describe
1. add assign_value_op_npu.cc, it simply register npu kernel, and call compute function in assign_value_op.h to finish job.
2. add code for npu condition in **paddle/fluid/framework/tensor_util.h: TensorFromArray**. The reason is as follows:
When inputs' dtype is bool, there is no corresponding TensorFromVector template function for vector<bool>, so only  TensorFromArray can be used, but it didn't consider npu condition before.

ctest result and op running environment
![Pasted Graphic 6](https://user-images.githubusercontent.com/51314274/127948856-857908e1-1c3a-4107-b115-972f6457d745.png)

2021-08-03 02:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34568) it.</sub>

2021-08-03 09:42 UTC, zhouwei25 submitted a review, later dismissed
LGTM

2021-08-03 09:49 UTC, zhouwei25 commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +sys.path.append("..")
这个是必须的吗

2021-08-03 11:04 UTC, qili93 requested changes

2021-08-03 11:04 UTC, qili93 commented on paddle/fluid/operators/assign_value_op_npu.cc
> +//   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
日期改一下2021

2021-08-03 11:04 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
时间同样改成2021

2021-08-03 11:04 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +
建议参考test_assign_value_op.py把里面4个TestAssignApi相关的单测也加上，相应的修改NPUPlace。

2021-08-03 11:14 UTC, betterpig commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +sys.path.append("..")
你好，感谢review。都是必须的。unittests：需要调用unittests.main()执行单测；numpy：用来生成随机数据；最后两行若未加上，会报“module op_test not found"的错误。

2021-08-03 11:18 UTC, betterpig commented on paddle/fluid/operators/assign_value_op_npu.cc
> +//   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
你好，感谢review。已改正。

2021-08-03 11:18 UTC, betterpig commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
你好，感谢review。已改正。

2021-08-03 12:26 UTC, betterpig commented on python/paddle/fluid/tests/unittests/npu/test_assign_value_op_npu.py
> +
你好，感谢review。已将相应的TestAssignApi类加上并改成NPUPlace，单测结果如下图。
![Pasted Graphic 7](https://user-images.githubusercontent.com/51314274/128015057-fb5b6ce1-4774-4e6c-a96b-b2b770f80355.png)

2021-08-04 03:50 UTC, qili93 approved these changes
LGTM

2021-08-04 03:52 UTC, merged