[NPU] Support npu kernel for StridedSlice op without grad
PaddlePaddle/Paddle pull request #34601
Opened 2021-08-04 07:36 UTC by bliu3650

### PR types
New features

### PR changes
OPs

### Describe
Develop the npu kernel (forward only) for StridedSlice op and reuse the Python unit test for CPU to test this new op.

<img width="512" alt="截屏2021-08-04 下午3 28 17" src="https://user-images.githubusercontent.com/21085266/128140748-683f7005-db9e-43c0-b0ae-cd572cf14c5b.png">
<img width="572" alt="截屏2021-08-04 下午3 27 14" src="https://user-images.githubusercontent.com/21085266/128140760-35406286-e5d3-44b2-9b74-763715ce1df7.png">

2021-08-04 07:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34601) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34601) it.</sub>

2021-08-20 04:54 UTC, gongweibao commented on paddle/fluid/operators/strided_slice_op_npu.cc
> +    switch (rank) {
其他的rank不支持是吗？需要assert？

2021-08-20 05:06 UTC, gongweibao requested changes
需要反向算子不？

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad(self):
cleanup?

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
还有用吗？

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +        with paddle.fluid.dygraph.guard():
cuda?

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
同上

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
同上

2021-08-20 05:06 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    def initTestCase(self):
这些都不用判断输出是吗？

2021-08-20 05:56 UTC, bliu3650 commented on paddle/fluid/operators/strided_slice_op_npu.cc
> +    switch (rank) {
这个 switch 分支是重用 CPU 版的算子实现

2021-08-20 05:58 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +        with paddle.fluid.dygraph.guard():
这个测试是保留下来的，其实在 NPU 环境下，也没用；可以删除

2021-08-20 06:00 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad(self):
没有开发反向，暂时不测

2021-08-20 06:00 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
没有开发反向，暂时不测

2021-08-20 06:01 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
没有开发反向，暂时不测

2021-08-20 06:01 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    #def test_check_grad_normal(self):
没有开发反向，暂时不测；以上不测反向的代码都可以删除

2021-08-20 06:03 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    def initTestCase(self):
这些只有 initTestCase 的单测，是重用了父类的测试代码，因此只改了输入

2021-08-20 06:09 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/npu/test_strided_slice_op_npu.py
> +    def initTestCase(self):
这个只有 initTestCase 的单测，其实是重用了父类的测试过程和判断，只是新增了输入组合。

2021-08-20 07:57 UTC, hbwx24 commented on paddle/fluid/operators/strided_slice_op_npu.cc
> +    int rank = ctx.Input<framework::Tensor>("Input")->dims().size();
这里是默认不支持 TensorArray类型的吧，这里是否需要加一个类型判断？

2021-08-23 06:15 UTC, bliu3650 commented on paddle/fluid/operators/strided_slice_op_npu.cc
> +    int rank = ctx.Input<framework::Tensor>("Input")->dims().size();
已加判断，如果是 TensorArray 类型，将报错：

const Variable* input_var = ctx.InputVar("Input");
bool is_tensor_array = input_var->IsType<LoDTensorArray>();
PADDLE_ENFORCE_EQ(is_tensor_array, false,
                                         paddle::platform::error::UNAVAILABLE(
                                                 "Tensor array as input is not supported."));

2021-08-23 09:25 UTC, bliu3650 commented
> 需要反向算子不？

这个算子是合作开发的，该提交只涉及前向，暂时不需要；等反向算子开发同学完成开发后，需要同步合一下代码和测试。

2021-08-26 03:41 UTC, hbwx24 reviewed
LGTM

2021-08-26 04:22 UTC, zhangting2020 approved these changes
LGTM for skip_check_grad_ci

2021-08-26 08:02 UTC, gongweibao approved these changes
LGTM

2021-08-26 08:02 UTC, merged