Support npu kernel for tile op
PaddlePaddle/Paddle pull request #34606
Opened 2021-08-04 08:22 UTC by rainyfly

### PR types

New features
### PR changes

OPs
### Describe

Support npu kernel for tile op
<img width="415" alt="image" src="https://user-images.githubusercontent.com/22424850/128147534-f43d0aa5-35ea-47cd-a1dd-cda3880e4d24.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/22424850/128147547-b805e03d-defb-43c0-8790-7c3292d66a8f.png">

2021-08-04 08:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34606) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34606) before we can accept your contribution.<br/><hr/>**chenjian26** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34606) it.</sub>

2021-08-05 11:36 UTC, nepeplwu commented
LGTM

2021-08-05 11:54 UTC, qili93 commented on paddle/fluid/operators/tile_op_npu.cc
> +inline std::vector<int> get_repeat_times_npu(
这个函数不需要重写，修改一下tile_op.h的判断，改为就可以了
if (platform::is_gpu_place(repeat_tensor->place()) || platform::is_npu_place(repeat_tensor->place())) {

2021-08-05 11:54 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        self.check_grad(['X'], 'Out')
同上

2021-08-05 11:54 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        self.check_grad(['X'], 'Out')
没有实现tile_grad的话，把这个函数改成 pass就好了

2021-08-05 11:54 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        self.check_grad(['X'], 'Out')
同上

2021-08-05 11:54 UTC, qili93 commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        with fluid.dygraph.guard():
可以改成 fluid.dygraph.guard(paddle.NPUPlace(0)): 后面 to_tensor就不需要加NPUPlace了

2021-08-05 11:57 UTC, rainyfly commented on paddle/fluid/operators/tile_op_npu.cc
> +inline std::vector<int> get_repeat_times_npu(
收到，我之前以为不能改已有的代码呢

2021-08-06 01:54 UTC, rainyfly commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        with fluid.dygraph.guard():
已改

2021-08-06 01:54 UTC, rainyfly commented on python/paddle/fluid/tests/unittests/npu/test_tile_op_npu.py
> +        self.check_grad(['X'], 'Out')
已改

2021-08-06 04:03 UTC, qili93 approved these changes
LGTM

2021-08-06 08:33 UTC, qili93 requested changes

2021-08-06 08:33 UTC, qili93 commented on paddle/fluid/operators/tile_op_npu.cc
> +    switch (rank) { REP_TILE_TEMPLATE(MAX_RANK_SUPPORTED) }
这个在NPU下有编译错误，需要根据最新develop分支的代码修改一下

2021-08-10 02:26 UTC, qili93 approved these changes
LGTM

2021-08-10 02:26 UTC, merged