[NPU] Add exp and exp_grad npu op
PaddlePaddle/Paddle pull request #34612
Opened 2021-08-04 11:34 UTC by 0x45f

### PR types

New features
### PR changes

OPs
### Describe

Add exp and exp_grad npu op

2021-08-06 06:25 UTC, Aurelius84 commented on paddle/fluid/operators/exp_op_npu.cc
> +
Remove this empty line

2021-08-06 06:25 UTC, Aurelius84 commented on paddle/fluid/operators/exp_op_npu.cc
> +
Remove this empty line

2021-08-06 06:25 UTC, Aurelius84 commented on paddle/fluid/operators/exp_op_npu.cc
> +
Why forward kernel dones't register int/int64

2021-08-06 06:25 UTC, Aurelius84 commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +class TestExpNPUOPFloat64(TestExpNPUOP):
why not add unittest of `int / int64`?

2021-08-06 06:34 UTC, 0x45f commented on paddle/fluid/operators/exp_op_npu.cc
> +
前向调用了CANN中实现的exp算子，该算子支持的类型如下，不支持int/int64
![exp](https://user-images.githubusercontent.com/23097963/128466615-03424ec8-1bd2-4b85-93e0-824b575102ca.png)

2021-08-06 06:57 UTC, 0x45f commented on paddle/fluid/operators/exp_op_npu.cc
> +
done

2021-08-06 06:58 UTC, 0x45f commented on python/paddle/fluid/tests/unittests/npu/test_exp_op_npu.py
> +class TestExpNPUOPFloat64(TestExpNPUOP):
移除了反向中的int/int64 kernel的注册，与前向类型保持一致

2021-08-10 02:32 UTC, qili93 requested changes

2021-08-10 02:32 UTC, qili93 commented on paddle/fluid/operators/exp_op.cc
> +*/
activation相关的算子都写在activation_op_npu.cc文件里面，这个exp_op.cc和exp_op_npu.cc都不需要

2021-08-10 02:32 UTC, qili93 commented on paddle/fluid/operators/exp_op_npu.cc
> +    }
参考activation_op.cc中的ExpOpMaker, Paddle的EXP算子没有以上三个attribute，请根据Paddle算子的输入和运算逻辑进行实现。

2021-08-10 11:02 UTC, 0x45f commented on paddle/fluid/operators/exp_op.cc
> +*/
> activation相关的算子都写在activation_op_npu.cc文件里面，这个exp_op.cc和exp_op_npu.cc都不需要
已经将实现代码放入activation_op_npu.cc文件中，删除了exp_op.cc和exp_op_npu.cc文件

2021-08-10 11:03 UTC, 0x45f commented on paddle/fluid/operators/exp_op_npu.cc
> +    }
删除了代码中的三个attribute

2021-08-11 06:42 UTC, qili93 approved these changes
LGTM

2021-08-11 06:42 UTC, merged