[CPU] Enable barrier op upon gloo
PaddlePaddle/Paddle pull request #34671
Opened 2021-08-06 07:52 UTC by bliu3650

### PR types
Others

### PR changes
APIs

### Describe
Compile Paddle with GLOO on;
Reuse previous barrier op implemented for CPU;
Create parallel environment specifically for gloo;
Test on single machine using test_collective_barrier_api.py

<img width="505" alt="截屏2021-08-06 下午3 51 18" src="https://user-images.githubusercontent.com/21085266/128476380-6dd4d480-7436-411d-bb46-45b973bf9ab1.png">

2021-08-14 00:03 UTC, gongweibao approved these changes
Coverage没过

2021-08-14 00:03 UTC, gongweibao commented on python/paddle/distributed/parallel_with_gloo.py
> +        warnings.warn(
assert?

2021-08-14 00:03 UTC, gongweibao commented on python/paddle/distributed/parallel_with_gloo.py
> +    else:
65行已经return了，这个地方就不用 else了？

2021-08-14 00:03 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_collective_cpu_barrier_with_gloo.py
> +    paddle.distributed.gloo_barrier()
barrier就好了，42行已经是说明是gloo了。

2021-08-14 00:03 UTC, gongweibao requested changes
Coverage Failed

2021-08-14 02:33 UTC, bliu3650 commented on python/paddle/distributed/parallel_with_gloo.py
> +    else:
上面用了 assert，这个 else 分支也就不用了

2021-08-14 02:33 UTC, bliu3650 commented on python/paddle/distributed/parallel_with_gloo.py
> +        warnings.warn(
ok

2021-08-14 02:39 UTC, bliu3650 commented on python/paddle/fluid/tests/unittests/test_collective_cpu_barrier_with_gloo.py
> +    paddle.distributed.gloo_barrier()
在 __init__.py 文件里有个同名 barrier 函数，来自 collective.py （通过 append op 组网调用 barrier，也支持其他通信库）；这里写的 gloo_barrier 只针对 CPU，是不是需要区分一下？

2021-08-14 07:19 UTC, gongweibao submitted a review, later dismissed
LGTM

2021-08-17 07:37 UTC, PangHua approved these changes

2021-08-18 01:57 UTC, PangHua approved these changes, later dismissed

2021-08-18 02:01 UTC, lanxianghit commented on python/paddle/distributed/parallel_with_gloo.py
> +def init_gloo_parallel_env(rank_id, rank_num, server_endpoint, with_gloo=True):
缺少文档预览

2021-08-18 02:05 UTC, bliu3650 commented on python/paddle/distributed/parallel_with_gloo.py
> +def init_gloo_parallel_env(rank_id, rank_num, server_endpoint, with_gloo=True):
是这个新增文件的整体预览，是吗？

2021-08-18 10:30 UTC, bliu3650 commented
新增APIs的文档预览：
![init_gloo_parallel_env](https://user-images.githubusercontent.com/21085266/129883097-9ac93553-ae78-44a0-b7fc-c6c564ed8f2e.png)
![barrier_func](https://user-images.githubusercontent.com/21085266/129883150-76bbe415-3b3b-4bed-a732-c84542508860.png)
![release_gloo](https://user-images.githubusercontent.com/21085266/129883184-b77a352f-b9a0-4463-94ce-f1fcec6ee546.png)

2021-08-19 02:31 UTC, lanxianghit submitted a review, later dismissed

2021-08-19 02:49 UTC, XieYunshen approved these changes, later dismissed

2021-08-19 02:59 UTC, PangHua submitted a review, later dismissed

2021-08-20 04:53 UTC, gongweibao approved these changes, later dismissed
LGTM

2021-08-20 05:46 UTC, bliu3650 commented
新增 APIs （修改名称后）文档预览：
![10 136 157 23_8090_documentation_docs_zh_api_paddle_distributed_gloo_init_parallel_env_cn html](https://user-images.githubusercontent.com/21085266/130185124-ef88d74b-1c09-41b4-b081-3efe94ccf412.png)
![10 136 157 23_8090_documentation_docs_zh_api_paddle_distributed_gloo_barrier_cn html](https://user-images.githubusercontent.com/21085266/130185140-d144c144-2102-4054-87dd-921d3908ed9b.png)
![10 136 157 23_8090_documentation_docs_zh_api_paddle_distributed_gloo_release_cn html](https://user-images.githubusercontent.com/21085266/130185651-21aebdf3-0076-451f-8856-be86a4a76f21.png)

2021-08-20 06:35 UTC, PangHua submitted a review, later dismissed

2021-08-20 07:06 UTC, XieYunshen approved these changes
LGTM

2021-08-20 09:58 UTC, PangHua approved these changes

2021-08-23 07:35 UTC, gongweibao requested changes
LGTM

2021-08-23 07:52 UTC, lanxianghit approved these changes

2021-08-23 09:33 UTC, zhiqiu approved these changes
LGTM for init.py

2021-08-23 14:00 UTC, gongweibao approved these changes
LGTM

2021-08-23 14:00 UTC, merged