Adamw skip update for npu
PaddlePaddle/Paddle pull request #34897
Opened 2021-08-13 19:31 UTC by sljlp

### PR types

New features
### PR changes

OPs
### Describe

Adamw skip update for npu

2021-08-13 19:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34897) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=34897) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=34897) it.</sub>

2021-08-14 00:10 UTC, gongweibao requested changes
Data contains Nan or Inf should be tested in CI.

2021-08-14 03:10 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/adam_op.cc
> +    AddAttr<float>("coeff",
除了coeff之外，是否还应该加一个with_decay属性，表示是否对该参数应用weight_decay。原因是：adamw api会使用apply_decay_param_fun函数过滤掉一部分参数。参见：https://github.com/PaddlePaddle/Paddle/pull/34891/files

2021-08-14 03:38 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/adam_op.cc
>  REGISTER_OP_CPU_KERNEL(
adamw后续会注册cpu和gpu kernel吗？如果没有对应kernel的话，就仍需要在python端实现，对用户来讲，逻辑有些费解。

2021-08-14 03:40 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/adam_op.cc
>  REGISTER_OP_CPU_KERNEL(
还需要增加cpu和gpu kernel

2021-08-14 03:54 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/adam_op_npu.cc
> +  void Compute(const framework::ExecutionContext& ctx) const override {
没有更新参数的操作？直接拷贝adam部分的代码就可以？

2021-08-14 06:30 UTC, sljlp commented on paddle/fluid/operators/optimizers/adam_op.cc
> +    AddAttr<float>("coeff",
好的

2021-08-14 06:30 UTC, sljlp commented on paddle/fluid/operators/optimizers/adam_op.cc
>  REGISTER_OP_CPU_KERNEL(
好的

2021-08-15 13:39 UTC, gongweibao commented on python/paddle/optimizer/adamw.py
> +        if core.is_compiled_with_npu(): self.type = "adamw"
这个设置是为了什么？

2021-08-15 14:20 UTC, sljlp commented on python/paddle/optimizer/adamw.py
> +        if core.is_compiled_with_npu(): self.type = "adamw"
之前不支持cpu和cuda， 现在需要再修改下，现在已经支持cpu和npu

2021-08-16 01:28 UTC, ZHUI commented on paddle/fluid/operators/optimizers/adam_op.cc
> +    AddAttr<float>("coeff",
可以默认设置`weight_decay=0`，减少`with_decay`属性。Python层API，对于不需要`decay`的参数，默认设置 `weight_decay=0`即可。

2021-08-16 08:32 UTC, sljlp commented on paddle/fluid/operators/optimizers/adam_op.cc
> +    AddAttr<float>("coeff",
OK，下版这样改下

2021-08-17 05:23 UTC, zhiqiu approved these changes
const_cast can be replaced by ShareDataWith in the next PR

2021-08-17 05:31 UTC, dingjiaweiww approved these changes
Skip TPM approve

2021-08-17 06:33 UTC, gongweibao approved these changes
LGTM

2021-08-17 07:03 UTC, PangHua approved these changes

2021-08-17 07:25 UTC, wangxicoding approved these changes
LGTM. But some problems need to be fixed in the next PR.

2021-08-17 07:25 UTC, wangxicoding commented on paddle/fluid/operators/optimizers/adam_op.cc
> +    AddAttr<float>("coeff",
`with_decay`属性可以不用吧，weight_decay=0就代表不需要做weight_decay了，`coeff`这个属性名之后换成`weight_decay_coeff`好些

2021-08-17 07:25 UTC, wangxicoding commented on paddle/fluid/operators/optimizers/adam_op_npu.cc
> +                        {*const_cast<framework::LoDTensor*>(param)}, {});
训练时，理论上直接拿param_out应该是可以的

2021-08-17 07:25 UTC, wangxicoding commented on python/paddle/optimizer/adamw.py
> +_C_ops = core.ops
from paddle import _C_ops

2021-08-17 07:25 UTC, wangxicoding commented on python/paddle/optimizer/adamw.py
> +            _, _, _, _, _ = _C_ops.adam(
adamw

2021-08-17 07:54 UTC, lanxianghit approved these changes

2021-08-17 08:03 UTC, sljlp commented on python/paddle/optimizer/adamw.py
> +_C_ops = core.ops
下个PR改下

2021-08-17 08:03 UTC, sljlp commented on python/paddle/optimizer/adamw.py
> +            _, _, _, _, _ = _C_ops.adam(
下个PR修

2021-08-17 12:42 UTC, merged