Add paddle.divide_ api, test=develop
PaddlePaddle/Paddle pull request #34928
Opened 2021-08-16 07:54 UTC by Liu-xiandong

### PR types

New features
### PR changes

APIs
### Describe

增加了divide_ API功能，对应着divide API的inplace版本。

### Example to use Inplace APIs
```
import paddle

x = paddle.to_tensor([2, 3, 4], dtype='float64')
y = paddle.to_tensor([1, 5, 2], dtype='float64')
x.divide_(y)
print(x)  # [2., 0.6, 2.]
```

2021-08-17 01:25 UTC, xingfeng01 commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivInplaceBroadcastError(unittest.TestCase):
测试是否覆盖了 double 和 float16 呢 ？

2021-08-17 02:17 UTC, Liu-xiandong commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivInplaceBroadcastError(unittest.TestCase):
我调整一下，把这个加上

2021-08-18 07:13 UTC, Liu-xiandong commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivInplaceBroadcastError(unittest.TestCase):
现在加上了double，但目前是不支持float16的

2021-08-18 07:18 UTC, xingfeng01 commented
LGTM

2021-08-18 07:19 UTC, lanxianghit commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivInplaceBroadcastError(unittest.TestCase):
为什么不支持float16呢？

2021-08-18 07:35 UTC, lanxianghit commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +        with fluid.program_guard(fluid.Program()):
单测中也不要使用fluid api了，需要使用2.0正式api，  下同

2021-08-18 07:35 UTC, lanxianghit commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivApi(unittest.TestCase):
这个的目的是什么，补充divide op的单测吗？

2021-08-18 07:47 UTC, Liu-xiandong commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +        with fluid.program_guard(fluid.Program()):
嗯嗯，好的，明白了

2021-08-18 07:47 UTC, Liu-xiandong commented on python/paddle/fluid/tests/unittests/test_elementwise_div_op.py
> +class TestDivApi(unittest.TestCase):
这个地方本来只写divide_就行，但是写代码方便就复用了几行div的代码，直接改_executed_api就行。

2021-08-19 02:28 UTC, lanxianghit approved these changes

2021-08-19 03:03 UTC, xingfeng01 approved these changes

2021-08-30 07:02 UTC, pangyoki requested changes
对动态图inplace策略，很重要的一点是检测反向梯度计算结果的正确性。因为inplace改变前向的值后，可能导致梯度计算错误。
请参考`test_inplace.py`单测中的测试样例，为`divide_`添加反向检查的单测样例。
（同时，`test_inplace.py`单测中也会对inplace之后的inplace version进行检查。）

2022-03-14 12:04 UTC, closed without merging