sparse_momentum_op is used to save w@GRAD memory for gather_op
PaddlePaddle/Paddle pull request #34942
Opened 2021-08-16 11:59 UTC by GuoxiaWang

### PR types

New features

### PR changes

OPs

### Describe

sparse_momentum_op is used to save w@GRAD memory for gather_op when gather from a large parameter, e.g.

```
# for paddle.optimizer.Momentum
weight = paddle.static.create_parameter(
    shape=[512, 10000000],
    dtype='float32',
    name='large_fc_w',
    is_bias=False)
weight = paddle.gather(weight, index, axis=1)
```

2021-08-17 05:15 UTC, sandyhouse requested changes

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(ctx->HasInput("Grad"), true,
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +    PADDLE_ENFORCE_EQ(
Use OP_INOUT_CHECK.

2021-08-17 05:15 UTC, sandyhouse commented on paddle/fluid/operators/optimizers/sparse_momentum_op.h
> +                          framework::product(lr_dims)));
The above two statements can be combined into one statement.

2021-08-17 05:30 UTC, TCChenlong submitted a review, later dismissed

2021-08-17 11:17 UTC, sandyhouse approved these changes, later dismissed
LGTM

2021-08-27 03:03 UTC, sandyhouse approved these changes
LGTM

2021-08-27 03:21 UTC, TCChenlong approved these changes

2021-08-27 03:44 UTC, XiaoguangHu01 approved these changes
LGTM

2021-08-27 07:43 UTC, zhiqiu approved these changes
LGTM for op_function_generator.cc

2021-08-27 10:04 UTC, merged