[Inference] Support NNAdapter and ascend310
PaddlePaddle/Paddle pull request #35226
Opened 2021-08-27 12:26 UTC by JZZ-NOTE

### PR types

Others
### PR changes

Others
### Describe

1、子图支持NNAdapter使用ascend310预测
2、DEMO pr: https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/162

ARM+Ascend310编译方法：
```
cmake .. -DWITH_PYTHON=ON \
         -DPYTHON_EXECUTABLE=`which python` \
         -DCMAKE_BUILD_TYPE=Release \
         -DON_INFER=ON \
         -DWITH_MKL=OFF \
         -DWITH_LITE=ON \
         -DLITE_WITH_NNADAPTER=ON \
         -DNNADAPTER_WITH_HUAWEI_ASCEND_NPU=ON \
         -DLITE_GIT_TAG=develop \
         -DNPU_SDK_ROOT=/usr/local/Ascend/ascend-toolkit/latest \
         -DWITH_ARM=ON
```

相关接口改动及影响：
增加了config.NNAdapter()的接口，来使用lite ascend310进行预测，对其它方向均没有侵入

2021-08-27 12:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=35226) <br/>All committers have signed the CLA.

2021-08-27 12:47 UTC, jiweibo commented on cmake/external/lite.cmake
> +      BUILD_ALWAYS         1
调试信息删掉

2021-08-27 12:47 UTC, jiweibo commented on paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.cc
> +  // NPU Related
NNAdapter

2021-08-27 12:48 UTC, jiweibo commented on paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.cc
> +  // NPU Related
NNAdapter

2021-08-27 12:48 UTC, jiweibo commented on paddle/fluid/inference/lite/engine.cc
> +#include <iostream>
这个是否可以去掉

2021-08-27 13:04 UTC, jiweibo requested changes
后续需提供python侧接口

2021-09-01 15:46 UTC, hong19860320 commented on paddle/fluid/inference/analysis/ir_pass_manager.cc
> +      pass->Set("nnadapter_model_cache_buffer",
是否可以类似model_cache_dir一样去掉nnadapter前缀？或者，要么都加前缀。

2021-09-01 15:46 UTC, hong19860320 commented on paddle/fluid/inference/analysis/ir_passes/lite_subgraph_pass.cc
> +  auto nnadapter_model_cache_buffer =
同上

2021-09-01 15:46 UTC, hong19860320 commented on cmake/external/lite.cmake
> +  if (NNADAPTER_WITH_NPU)
是否可以改成NNADAPTER_WITH_HUAWEI_ASCEND_NPU

2021-09-16 05:17 UTC, jiweibo commented on cmake/external/lite.cmake
> +  if (NNADAPTER_WITH_NPU)
代码改完后，也请改下pr上和文档上的cmake编译的指令吧

2021-09-22 02:17 UTC, jiweibo approved these changes
LGTM

2021-09-22 02:41 UTC, hong19860320 approved these changes
LGTM

2021-09-22 02:41 UTC, hong19860320 commented on cmake/external/lite.cmake
> +    set(LITE_NNADAPTER_NPU_LIB ${LITE_BINARY_DIR}/${LITE_OUTPUT_BIN_DIR}/cxx/lib/libnnadapter_driver_huawei_ascend_npu.so)
这个在release/v2.10统一改成了libhuawei_ascend_npu.so了
_release/v2.10业务分支仍然使用libnnadapter_driver_huawei_ascend_npu.so

2021-09-22 02:41 UTC, hong19860320 commented on python/setup.py.in
> +            package_data['paddle.libs']+=['libnnadapter_driver_huawei_ascend_npu' + ext_name]
同上

2021-09-22 02:41 UTC, jiweibo commented on cmake/external/lite.cmake
> +    set(LITE_NNADAPTER_NPU_LIB ${LITE_BINARY_DIR}/${LITE_OUTPUT_BIN_DIR}/cxx/lib/libnnadapter_driver_huawei_ascend_npu.so)
收到，后续develop上改为release/v2.10分之后修改

2021-09-22 03:02 UTC, shentanyue commented
LGTM

2021-09-22 03:04 UTC, zhupengyang approved these changes
LGTM

2021-09-22 03:08 UTC, lanxianghit approved these changes
LGTM for API change.

2021-09-22 07:04 UTC, CheQiXiao approved these changes

2021-09-22 07:22 UTC, merged