solve the bug divide by zero in softmax_with_cross_entropy_op, test=d…
PaddlePaddle/Paddle pull request #35220
Opened 2021-08-27 09:50 UTC by XYZ916829

### PR types

 Bug fixes 
### PR changes

OPs 
### Describe

solve the bug divide by zero in softmax_with_cross_entropy_op, test = develop

2021-08-30 02:26 UTC, chajchaj requested changes

2021-08-30 02:26 UTC, chajchaj commented on paddle/fluid/operators/softmax_with_cross_entropy_op.h
> +                  "The size of axis should be larger than 0, but received "
这里的注释最好写n的含义，以及n是怎么计算得来的，怎么造成的n=0，让用户根据提示信息可以有效修改。

2021-08-30 02:26 UTC, chajchaj commented on paddle/fluid/operators/softmax_with_cross_entropy_op.h
> +                  "axis size is %d.",
这里的注释最好写n的含义，以及n是怎么计算得来的，怎么造成的n=0，让用户根据提示信息可以有效修改。

2021-09-07 06:40 UTC, winter-wang approved these changes, later dismissed
LGTM

2021-09-07 06:40 UTC, winter-wang commented on paddle/fluid/operators/softmax_with_cross_entropy_op.h
> +
这两行空行感觉是手误吧？

2021-09-07 06:50 UTC, XYZ916829 commented on paddle/fluid/operators/softmax_with_cross_entropy_op.h
> +
是的，已修改

2021-09-14 11:40 UTC, chajchaj approved these changes

2021-09-14 11:40 UTC, merged