add_loss_scaling_test
PaddlePaddle/Paddle pull request #35270
Opened 2021-08-30 09:18 UTC by Baibaifan

### PR types

New features
### PR changes

OPs
### Describe

add npu LossScaling test

2021-08-31 03:52 UTC, gongweibao requested changes

2021-08-31 03:52 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/npu/test_update_loss_scaling_min_op_npu.py
> +            'PrevLossScaling': self.prev_loss_scaling,
这些值要显式的赋值一下。

2021-08-31 06:03 UTC, Baibaifan commented on python/paddle/fluid/tests/unittests/npu/test_update_loss_scaling_min_op_npu.py
> +            'PrevLossScaling': self.prev_loss_scaling,
Done

2021-08-31 08:21 UTC, gongweibao submitted a review, later dismissed
LGTM
修改一下PR的标题，cherrypick到ascendrelease分支!

2021-09-01 13:04 UTC, zhiqiu approved these changes
LGTM

2021-09-01 13:53 UTC, phlrain approved these changes

2021-09-02 02:36 UTC, merged