Add op define extra for norm and frobenius norm op.
PaddlePaddle/Paddle pull request #35329
Opened 2021-08-31 13:02 UTC by ZHUI

### PR types

Others
### PR changes

OPs
### Describe

Add op define extra for norm and frobenius norm op.

2021-09-07 07:54 UTC, winter-wang requested changes

2021-09-07 07:54 UTC, winter-wang commented on paddle/fluid/operators/norm_op.cc
> +        .AsExtra();
这个is_test不能被标记，不然导出时裁了，再次导入通过exe.run（）执行时会出问题

2021-09-07 08:24 UTC, ZHUI commented on paddle/fluid/operators/norm_op.cc
> +        .AsExtra();
deleted

2021-09-08 02:25 UTC, winter-wang approved these changes
LGTM

2021-09-08 02:29 UTC, zhangting2020 approved these changes
LGTM for skip_check_grad_ci

2021-09-08 02:37 UTC, merged