[NPU]add depthwise_conv_npu_grad op
PaddlePaddle/Paddle pull request #35374
Opened 2021-09-01 14:23 UTC by heliqi

### PR types
New features

### PR changes
Ops

### Describe
![6e35b0ff5dcb5b159554e74ff4db4d0c](https://user-images.githubusercontent.com/34152981/131688093-0f4df15a-340e-4592-bfe3-6425a6365d1a.png)

2021-09-01 14:27 UTC, jiangjiajun requested changes

2021-09-01 14:27 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/npu/test_conv2d_op_depthwise_conv_npu.py
> +            #print("Epoch {} | Prediction[0]: {}, Loss: {}".format(
注释代码删除

2021-09-01 14:27 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/npu/test_conv2d_op_depthwise_conv_npu.py
> +            #print("Epoch {} | Prediction[0]: {}, Loss: {}".format(
其它没问题了

2021-09-01 14:30 UTC, heliqi commented on python/paddle/fluid/tests/unittests/npu/test_conv2d_op_depthwise_conv_npu.py
> +            #print("Epoch {} | Prediction[0]: {}, Loss: {}".format(
deno

2021-09-02 10:22 UTC, qili93 submitted a review, later dismissed
LGTM

2021-09-03 06:26 UTC, zhhsplendid approved these changes
LGTM

2021-09-03 06:34 UTC, lanxianghit approved these changes

2021-09-03 06:40 UTC, qili93 approved these changes

2021-09-06 03:17 UTC, merged