Add cpu npu cembedding
PaddlePaddle/Paddle pull request #35467
Opened 2021-09-04 14:33 UTC by Baibaifan

### PR types

New features
### PR changes

OPs
### Describe

Add a c_embedding op to unify NPU\GPU split embedding.
NPU c_embedding op support FP32 and FP16 for table, INT32 for ids.
Method:
A. Inner function shard_index to handle out ids in collective.
B. Auto add last dim for table to choose out ids.
C. Split auto add dim in backward.
![image](https://user-images.githubusercontent.com/39549453/132087775-09a0292c-0ca6-4b1f-bc98-f91060f37b71.png)

Test result
Seed=2021 
![image](https://user-images.githubusercontent.com/39549453/132089484-08e6e767-7350-4a75-8ab6-be8c1e3319e7.png)

2021-09-06 02:44 UTC, FeixLiu commented on paddle/fluid/operators/collective/c_allreduce_op.h
> +    // runner_mean.Run(stream);
already updated by #35438

2021-09-06 02:44 UTC, FeixLiu commented on paddle/fluid/platform/flags.cc
> +DEFINE_bool(hccl_check_nan, true,
already been updated by #35438

2021-09-06 03:05 UTC, FeixLiu commented on paddle/fluid/operators/collective/c_embedding_op.h
> +
cpu不需要前向补0么？

2021-09-06 06:04 UTC, Baibaifan reviewed
Done resolve

2021-09-06 06:04 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_embedding_op.h
> +
不需要哈，需要提前在输出置0

2021-09-06 13:25 UTC, gongweibao commented on paddle/fluid/operators/collective/c_embedding_op.h
> +    }
else

2021-09-06 13:25 UTC, gongweibao requested changes
把其他人的comment修一下？

2021-09-07 03:15 UTC, gongweibao requested changes
有些地方还可以优化，可以分步骤来。

2021-09-07 03:15 UTC, gongweibao commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +                        "NPU only accept the second dim must align by 64"));
去掉NPU

2021-09-07 03:15 UTC, gongweibao commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +  shard_index<TIds>(*table_t, *ids_t, start_idx, ids_t_local, context);
下个PR把正向的输出保留下来而不是重新算？

2021-09-07 03:21 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +                        "NPU only accept the second dim must align by 64"));
NPU算子内的报错，没必要取消

2021-09-07 04:00 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +  shard_index<TIds>(*table_t, *ids_t, start_idx, ids_t_local, context);
好的 下个pr优化

2021-09-07 08:58 UTC, gongweibao commented on paddle/fluid/operators/collective/c_embedding_op.cc
> +                          "CPU only accept the dims of table_t == 2"));
CPU是什么意思？

2021-09-08 12:04 UTC, Baibaifan reviewed
> 有些地方还可以优化，可以分步骤来。

好

2021-09-08 12:04 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_embedding_op.h
> +    }
Done

2021-09-10 02:51 UTC, FeixLiu requested changes

2021-09-10 02:51 UTC, FeixLiu commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +  const size_t mem_size = table_grad_t->memory_size();
memory_size()的调用与coalesce存在冲突的。造成fuse_grad_merge功能在c_embedding加入后loss对不齐的情况。

假设当fuse_grad_size_in_MB比较大的时候，多个grad会被fuse在一起，fuse grad var的顺序为：
`| grad word embedding | padding | grad var1 | padding | grad var2 | padding | grad var3 | padding |`
指针table_grad_t就是grad word embedding的地址，但同时，该地址也是fused grad var的起始地址。

那么在调用table_grad_t->memory_size();的时候，返回的值并不是grad word embedding的memory size，而是整个fused grad var的memory size。这样的话，在[Memcpy](https://github.com/PaddlePaddle/Paddle/pull/35467/files#diff-b32949391d17d29b060d8e33814785bb862dbf2702d6d35289d6a65adefa25d1R212)的时候，会将grad var1，grad var2，grad var3的值全部覆盖掉。

此外，如果fuse_grad_size_in_MB比较小的时候，fuse grad var只有`| grad word embedding | padding |`，调用table_grad_t->memory_size();的时候，返回的值也不是单纯的grad word embedding的memory size，而是word embedding + padding部分的整体的memory size。虽然现在表现是正常的，但是可能引入其他内存相关的问题。

建议更改为使用numel()与SizeOfType()的方式：
`const size_t mem_size = table_grad_t->numel() * framework::SizeOfType(table_grad_t->type());`

此外，对于其余调用memory_size的函数，如果是针对外部变量的调用，也建议更改为使用numel()与SizeOfType()的方式。如果未来我们进行parameter的fuse，调用memory_size也会造成同样的问题。

2021-09-10 10:00 UTC, Baibaifan commented on paddle/fluid/operators/collective/c_embedding_op_npu.cc
> +  const size_t mem_size = table_grad_t->memory_size();
Had fixed

2021-09-11 02:09 UTC, Baibaifan commented
> 有些地方还可以优化，可以分步骤来。

好的

2021-09-11 02:15 UTC, gongweibao approved these changes
LGTM

2021-09-11 02:16 UTC, merged