Remove autograd/grad api
PaddlePaddle/Paddle pull request #35579
Opened 2021-09-08 07:40 UTC by MingMingShangTian

### PR types

Others
### PR changes

APIs
### Describe

Remove the grad API in paddle/autograd/__init__.py

2021-09-08 07:41 UTC, TCChenlong approved these changes, later dismissed

2021-09-09 03:15 UTC, zhiboniu requested changes

2021-09-09 03:15 UTC, zhiboniu commented on python/paddle/autograd/__init__.py
> +__all__ = ['backward', 'PyLayer', 'PyLayerContext']
1、兼容性影响较小，从__all__列表中删除只影响import *，相对使用很少。对于autograd.grad这类使用不受影响。
2、建议paddle.grad 修改从fluid import 改为从autograd import，fluid是非标准路径是计划会废弃的
3、包括no_grad、set_grad_enabled也建议从autograd import，这部分代码有计划从fluid迁移到autograd

2021-09-09 10:19 UTC, MingMingShangTian commented on python/paddle/autograd/__init__.py
> +__all__ = ['backward', 'PyLayer', 'PyLayerContext']
Done

2021-09-16 02:20 UTC, zhiboniu reviewed
LGTM

2021-09-16 07:03 UTC, jeff41404 approved these changes
lgtm

2021-09-16 07:07 UTC, lanxianghit approved these changes

2021-09-16 07:09 UTC, TCChenlong approved these changes

2021-09-16 08:22 UTC, merged