register the with_quant_attr attribute for all operattor.
PaddlePaddle/Paddle pull request #35591
Opened 2021-09-08 12:18 UTC by winter-wang

### PR types

Others
### PR changes

Others
### Describe

给op proto的基类中注册了 with_quant_attr的bool属性。当一个算子被量化时，该属性会被设置为True。

2021-09-08 12:25 UTC, wanghaoshuang approved these changes

2021-09-08 12:25 UTC, wanghaoshuang commented on paddle/fluid/framework/op_proto_maker.cc
> +                "Operator has necessary quantization attribute. It will be set "
"Whether the operator has attributes used by quantization. "
只需要这一句解释就行了。有量化属性的OP不一定是quantized op。

2021-09-08 12:27 UTC, wanghaoshuang requested changes
需要修改下对with_quant_attr的解释。

2021-09-09 02:16 UTC, winter-wang commented on paddle/fluid/framework/op_proto_maker.cc
> +                "Operator has necessary quantization attribute. It will be set "
好的

2021-09-10 10:07 UTC, jzhang533 approved these changes, later dismissed
lgtm

2021-09-10 11:11 UTC, wanghaoshuang approved these changes

2021-09-10 11:20 UTC, jzhang533 approved these changes
lgtm

2021-09-10 11:36 UTC, zhiqiu approved these changes
LGTM

2021-09-11 03:13 UTC, merged