add paddle.linalg.igvalsh API
PaddlePaddle/Paddle pull request #35615
Opened 2021-09-09 07:44 UTC by huangjun12

### PR types
New features

### PR changes
OPs

### Describe
add paddle.linalg.eigvalsh

2021-10-20 08:22 UTC, chajchaj submitted a review, later dismissed
LGTM

2021-10-21 08:41 UTC, cryoco submitted a review, later dismissed
LGTM for no_check_set

2021-10-22 02:52 UTC, jiangjiajun requested changes
其它没问题，改好后即可Approve

2021-10-22 02:52 UTC, jiangjiajun commented on python/paddle/tensor/linalg.py
> +def eigvalsh(x, UPLO='L', name=None):
英文注释首字母大写

2021-10-22 02:52 UTC, jiangjiajun commented on paddle/fluid/operators/eigvalsh_op.h
> +    // comput elementwise multiply of output_v and output_w_grad
注释comput -> compute

2021-10-22 02:52 UTC, jiangjiajun commented on python/paddle/tensor/linalg.py
> +def eigvalsh(x, UPLO='L', name=None):
另外参考其它API，都是`Computes xxxx`，这里英文对齐下吧

2021-10-22 03:18 UTC, dingjiaweiww submitted a review, later dismissed

2021-10-22 03:28 UTC, huangjun12 commented on python/paddle/tensor/linalg.py
> +def eigvalsh(x, UPLO='L', name=None):
Done

2021-10-22 03:28 UTC, huangjun12 commented on paddle/fluid/operators/eigvalsh_op.h
> +    // comput elementwise multiply of output_v and output_w_grad
Done

2021-10-22 06:09 UTC, jiangjiajun approved these changes

2021-10-22 08:04 UTC, cryoco approved these changes

2021-10-23 23:28 UTC, XiaoguangHu01 approved these changes
LG API

2021-10-25 03:30 UTC, dingjiaweiww approved these changes

2021-10-27 03:03 UTC, merged