[hybrid performance] Optimize Pipeline Scheduler
PaddlePaddle/Paddle pull request #35680
Opened 2021-09-13 06:55 UTC by FeixLiu

### PR types
Performance optimization

### PR changes
Others

### Describe
Update the pipeline scheduler, move the forward/backward/optimize op decision logic to init function of SectionWorker.

Loss compare on GPU with Ernie3.0

2021-09-13 08:31 UTC, wangxicoding requested changes

2021-09-13 08:31 UTC, wangxicoding commented on paddle/fluid/framework/section_worker.cc
> +  for (auto &op : ops_) {
注意第35行有个 `if (schedule_mode_ != 1) return;`
那么这段逻辑在在FthenB里不会被执行

2021-09-13 08:31 UTC, wangxicoding commented on paddle/fluid/framework/device_worker.h
> +  std::vector<OperatorBase*> forward_first_ops_;
改成forward_and_lr_ops_吧

2021-09-13 08:31 UTC, wangxicoding commented on paddle/fluid/framework/device_worker.h
> +  std::vector<OperatorBase*> forward_other_ops_;
forward_ops_

2021-09-13 08:34 UTC, wangxicoding commented on paddle/fluid/framework/section_worker.cc
> +    int op_role = op->Attr<int>("op_role");
这里面再判断一下，有没有op_role不在以下情况里面的op，如果有，报个错

2021-09-13 08:36 UTC, FeixLiu commented on paddle/fluid/framework/device_worker.h
> +  std::vector<OperatorBase*> forward_first_ops_;
好的

2021-09-13 08:36 UTC, FeixLiu commented on paddle/fluid/framework/device_worker.h
> +  std::vector<OperatorBase*> forward_other_ops_;
👌

2021-09-13 08:36 UTC, FeixLiu commented on paddle/fluid/framework/section_worker.cc
> +    int op_role = op->Attr<int>("op_role");
好的

2021-09-13 08:36 UTC, FeixLiu commented on paddle/fluid/framework/section_worker.cc
> +  for (auto &op : ops_) {
updated

2021-09-13 09:22 UTC, wangxicoding submitted a review, later dismissed
LGTM

2021-09-14 03:17 UTC, wangxicoding approved these changes
LGTM

2021-09-14 05:29 UTC, sandyhouse reviewed
从该pr描述部分看，该pr的loss曲线在末端会高于基线。该pr应该不改变调度逻辑，为什么会引起loss曲线的变化？

2021-09-14 05:54 UTC, FeixLiu commented
> 从该pr描述部分看，该pr的loss曲线在末端会高于基线。该pr应该不改变调度逻辑，为什么会引起loss曲线的变化？

随机初始化带来的吧
<img width="200" alt="Screen Shot 2021-09-14 at 1 52 54 PM" src="https://user-images.githubusercontent.com/25279174/133202472-ee25b34a-83cb-49e9-ac0d-103eae8d3189.png">
用了一个另一次跑的baseline做的新对比图

2021-09-14 05:57 UTC, sandyhouse approved these changes
LGTM

2021-09-14 05:59 UTC, merged