Fix mp multi gradient clip prob
PaddlePaddle/Paddle pull request #35713
Opened 2021-09-14 04:03 UTC by FeixLiu

### PR types
Bug fixes

### PR changes
Others

### Describe
mp下，有些var并不是分布式的，譬如scale、bias等等。这些var如果在GradientClipByGlobalNorm时候在各路mp均进行累加，那么最后的global norm会略大一些。
修改后，对于is_distributed为False的grad，只在mp_rank为0的节点进行累加计算Norm，后续通过c_allreduce_sum来计算GlobalNorm
**修改前mp_rank=1 program:**
![image](https://user-images.githubusercontent.com/25279174/133192977-218ad3ba-63c1-46bf-af99-9975b4388db4.png)

![image](https://user-images.githubusercontent.com/25279174/133192942-17f4891a-fd09-4dff-bbd3-24711ff2632b.png)

**修改后mp_rank=1 program:**
![image](https://user-images.githubusercontent.com/25279174/133192817-1b9e54ec-41b4-4954-8398-48c2e0336e76.png)

2021-09-14 08:13 UTC, wangxicoding requested changes

2021-09-14 08:13 UTC, wangxicoding commented on python/paddle/fluid/optimizer.py
> +                    dest_var.is_distributed = source_var.is_distributed
这段copy逻辑整成一个clone函数吧。除了is_distributed这个属性，还有parameter，parameter之后再修复，涉及了参数广播

2021-09-14 08:13 UTC, wangxicoding commented on python/paddle/fluid/optimizer.py
> +                merged_grad_var.is_distributed = real_param.is_distributed
这个是在_accumulate_gradients_with_fuse里的，没有fuse的呢

2021-09-14 08:13 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +        for idx, op in list(enumerate(block.ops)):
这里面逻辑有问题
1. 首先需要判断是否是GradientClipByGlobalNorm才能裁剪，正常的gradientclip是单个单个的，目前的方案会把正常gradientclip的也给裁剪掉。
2. 有的参数是没有is_distributed属性的，那么默认这些参数在每个mp上都是复制的。

2021-09-14 08:38 UTC, FeixLiu commented on python/paddle/fluid/optimizer.py
> +                merged_grad_var.is_distributed = real_param.is_distributed
没有fuse就是上面那个create_var的逻辑

2021-09-14 08:39 UTC, FeixLiu commented on python/paddle/fluid/optimizer.py
> +                    dest_var.is_distributed = source_var.is_distributed
好的

2021-09-14 08:45 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +        for idx, op in list(enumerate(block.ops)):
好的

2021-09-14 12:49 UTC, wangxicoding requested changes

2021-09-14 12:49 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                                     input_var.is_distributed):
没有开mp，也即mp_degree<=1时，self.mp_rank是等于-1的，需要加上是否开启mp的判断。
not input_var.is_distributed
or的两个操作数加上括号，严格优先级
另外这段逻辑加上注释，说明没有is_distributed属性及is_distributed属性为False时在MP的group内，参数是duplicate的，MP进行c_allreduce_sum时会给多加了

2021-09-14 12:49 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                continue
这个continue删了

2021-09-14 12:49 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                block._remove_op(idx, sync=False)
没用的var也需要删一下

2021-09-14 12:49 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                op.desc.set_input("X", reserved_vars)
加个break. 或者这个for循环可以和上面的合到一起

2021-09-14 12:49 UTC, wangxicoding commented on python/paddle/fluid/optimizer.py
> +                self._clone_var_attr(dest_var, source_var)
clone_var吧，把前面的那一段逻辑也包括进来

2021-09-14 12:49 UTC, wangxicoding reviewed
加上开MP和不开MP时，混合并行精度的对比

2021-09-15 01:25 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                continue
done

2021-09-15 01:29 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                op.desc.set_input("X", reserved_vars)
done

2021-09-15 01:53 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                block._remove_op(idx, sync=False)
done

2021-09-15 01:56 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                                     input_var.is_distributed):
done

2021-09-15 06:24 UTC, FeixLiu commented
<img width="300" alt="Screen Shot 2021-09-15 at 2 23 36 PM" src="https://user-images.githubusercontent.com/25279174/133381342-7ff21f32-36e0-4e24-9a36-ac03ce23b8f2.png">
gradient clip 数值改为1e-6后，dev分支，pr分支在w/ mp与w/o mp下loss基本对齐

2021-09-15 07:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +            if idx in removed_op_idx:
removed_op_idx 类型改成set，减少查询时间

2021-09-15 07:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                    removed_op_idx.append(idx)
其实当前这种删法是不严谨的，按照之前global_clip的square、sum op实现会出问题。不过目前改成了squarel2norm实现，不会出问题就是了。

2021-09-15 07:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +            if op.type == 'sum' and mp_rank != 0:
建议这个!= 0和前面的 >0都改成>=1，语义更明了一些

2021-09-15 07:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +                op.desc.set_input("X", reserved_vars)
如果reserved_vars还是[]怎么办，虽然在开启mp时理论不会发生，不过你可以先自己想想办法。然后在我optimzier_sharding的PR里面有解决方案

2021-09-15 07:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +    def sync_global_norm(self, block, ring_ids, mp_rank):
sharding使用的前一个函数prune_gradient_clip也有同样的bug，可以下个PR再修一下。

2021-09-15 07:46 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +            if op.type == 'sum' and mp_rank != 0:
done

2021-09-15 07:55 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +            if idx in removed_op_idx:
ok

2021-09-15 07:55 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +    def sync_global_norm(self, block, ring_ids, mp_rank):
是的，可以下一个pr修

2021-09-16 06:44 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +        for idx, op in reversed(list(enumerate(block.ops))):
建议这个for循环的代码和上面那个for循环的代码合并起来，if op.type == 'sum之后处理逻辑一样。然后还是reversed遍历

2021-09-16 07:00 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +        for idx, op in reversed(list(enumerate(block.ops))):
ok

2021-09-16 10:17 UTC, wangxicoding approved these changes
LGTM

2021-09-16 10:17 UTC, wangxicoding commented on python/paddle/fluid/tests/unittests/test_fleet_sharding_meta_optimizer.py
> +            'update_loss_scaling', 'fill_constant', 'c_allreduce_sum',
👻

2021-09-16 10:17 UTC, wangxicoding commented on python/paddle/distributed/fleet/meta_optimizers/sharding/gradient_clip_helper.py
> +        for idx, op in list(enumerate(block.ops)):
其实反向遍历更好点点

2021-09-16 13:09 UTC, sandyhouse approved these changes
LGTM

2021-09-16 14:14 UTC, merged