User specified backend
PaddlePaddle/Paddle pull request #35745
Opened 2021-09-15 03:10 UTC by 2742195759

### PR types

New features
### PR changes

APIs
### Describe

user can specifize which backend to use when parallel training.

2021-09-15 08:26 UTC, Aurelius84 submitted a review, later dismissed
LGTM

2021-09-15 12:52 UTC, ZHUI commented on python/paddle/distributed/fleet/launch.py
> +    base_group.add_argument(
选项有文档暴露给用户吗？最近，我看guoxia这边有个lanch的文档pr，https://github.com/PaddlePaddle/Paddle/pull/35634

2021-09-15 13:03 UTC, 2742195759 commented on python/paddle/distributed/fleet/launch.py
> +    base_group.add_argument(
> 选项有文档暴露给用户吗？最近，我看guoxia这边有个lanch的文档pr，#35634

我们打算这个功能合入之后单独提一个PR修改文档。

2021-09-15 13:16 UTC, ZHUI commented on python/paddle/distributed/fleet/launch.py
> +    base_group.add_argument(
Get 👍🏻

2021-09-16 03:09 UTC, XieYunshen approved these changes, later dismissed
LGTM for 
bash_test_modules(test_cpuonly_launch START_BASH test_cpuonly_launch.sh SERIAL LABELS "RUN_TYPE=EXCLUSIVE" ENVS "PADDLE_DIST_UT_PORT=${dist_ut_port}" PADDLE_BINARY_DIR=${PADDLE_BINARY_DIR}

2021-09-16 03:19 UTC, Aurelius84 approved these changes, later dismissed
LGTM

2021-09-16 04:02 UTC, TCChenlong approved these changes, later dismissed

2021-09-16 06:29 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +    global_envs["PADDLE_DISTRI_BACKEND"] = args.backend
should we use PADDLE_DIST_BACKEND or PADDLE_DISTRIBUTED_BACKEND ?

2021-09-16 06:34 UTC, Baibaifan commented on python/paddle/distributed/fleet/launch.py
> +        args.backend = 'unknown'
npu 为什么是unknow，线上策略已经支持npu了吖

2021-09-16 06:34 UTC, Baibaifan commented on python/paddle/distributed/fleet/launch_utils.py
>      if fluid.core.is_compiled_with_npu() and \
这个npu应该加入npu mode

2021-09-16 06:34 UTC, Baibaifan commented on python/paddle/distributed/spawn.py
> +def _get_default_backend():
需要增加npu相关backend

2021-09-16 06:54 UTC, 2742195759 commented on python/paddle/distributed/fleet/launch.py
> +    global_envs["PADDLE_DISTRI_BACKEND"] = args.backend
> should we use PADDLE_DIST_BACKEND or PADDLE_DISTRIBUTED_BACKEND ?

那我们就定为 PADDLE_DIST_BACKEND 吧。我回头修改一下名字即可。

2021-09-16 06:58 UTC, 2742195759 commented on python/paddle/distributed/spawn.py
> +def _get_default_backend():
我们在parallel.py 中没有看到任何与NPU硬件相关联的支持。

2021-09-16 06:58 UTC, 2742195759 commented on python/paddle/distributed/fleet/launch_utils.py
>      if fluid.core.is_compiled_with_npu() and \
请问NPU在当前模块上前后端是否打通了？

2021-09-16 06:59 UTC, 2742195759 commented on python/paddle/distributed/fleet/launch.py
> +    global_envs["PADDLE_DISTRI_BACKEND"] = args.backend
我们准备下一个PR修改这个名字。

2021-09-16 07:03 UTC, sandyhouse commented on python/paddle/distributed/fleet/launch.py
> +    )
这样的话，backend只能选一种了吧。如果想要选择多个backend怎么支持，比如nccl和gloo同时需要。

2021-09-16 07:55 UTC, lanxianghit approved these changes, later dismissed

2021-09-16 08:09 UTC, gongweibao requested changes
需要讨论下。

2021-09-16 08:41 UTC, Aurelius84 commented on python/paddle/distributed/fleet/launch.py
> +    )
NCCL和GLOO都会默认初始化，不冲突

2021-10-19 09:43 UTC, Aurelius84 approved these changes

2021-10-20 08:37 UTC, XieYunshen approved these changes
LGTM for `    set_tests_properties(test_parallel_dygraph_unused_variables_gloo PROPERTIES TIMEOUT 120)
    set_tests_properties(test_parallel_dygraph_sparse_embedding_gloo PROPERTIES TIMEOUT 120)
    set_tests_properties(test_parallel_dygraph_sparse_embedding_over_height_gloo PROPERTIES TIMEOUT 120)`

2021-10-20 11:20 UTC, ForFishes approved these changes
LGTM

2021-10-20 11:28 UTC, sandyhouse approved these changes
LGTM

2021-10-21 02:24 UTC, lanxianghit approved these changes

2021-10-21 02:45 UTC, TCChenlong approved these changes

2021-10-21 02:56 UTC, kuizhiqing commented on python/paddle/distributed/fleet/launch.py
> +    global_envs["PADDLE_DISTRI_BACKEND"] = args.backend
为什么不在这个 pr 修改？

2021-10-21 03:18 UTC, Xreki approved these changes
LGTM for const_cast

2021-10-21 03:18 UTC, raindrops2sea approved these changes

2021-10-21 03:50 UTC, XiaoguangHu01 approved these changes
LGTM

2021-10-21 06:06 UTC, gongweibao approved these changes

2021-10-21 06:06 UTC, gongweibao commented on paddle/fluid/framework/fleet/gloo_wrapper.h
> +    LOG(WARNING) << "AllGather does nothing when WITH_GLOO=OFF";
这个地方是 Throw Exception?

2021-10-21 06:07 UTC, merged

2021-10-21 06:27 UTC, Aurelius84 commented on paddle/fluid/framework/fleet/gloo_wrapper.h
> +    LOG(WARNING) << "AllGather does nothing when WITH_GLOO=OFF";
这个保持了gloo_wrapper的其他接口的处理范式，参见line 221行

2021-11-03 15:06 UTC, wduo commented
@2742195759 您好！源码编译最新的develop分支后，用python -m paddle.distributed.launch --nproc_per_node=4 --backend=gloo train.py训练，运行到dist.init_parallel_env()这句时报错如下：
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'GLOOParallelContext'
请问您这个是因为什么呢？是需要把develop分支代码回退到您提交时的版本吗？

2021-11-03 15:25 UTC, wduo commented
> @2742195759 您好！源码编译最新的develop分支后，用python -m paddle.distributed.launch --nproc_per_node=4 --backend=gloo train.py训练，运行到dist.init_parallel_env()这句时报错如下： AttributeError: module 'paddle.fluid.core_avx' has no attribute 'GLOOParallelContext' 请问您这个是因为什么呢？是需要把develop分支代码回退到您提交时的版本吗？

我用docker环境编译的CPU版的：

```
cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON

```

2021-11-03 16:27 UTC, 2742195759 commented
> > @2742195759 您好！源码编译最新的develop分支后，用python -m paddle.distributed.launch --nproc_per_node=4 --backend=gloo train.py训练，运行到dist.init_parallel_env()这句时报错如下： AttributeError: module 'paddle.fluid.core_avx' has no attribute 'GLOOParallelContext' 请问您这个是因为什么呢？是需要把develop分支代码回退到您提交时的版本吗？
> 
> 我用docker环境编译的CPU版的：
> 
> ```
> cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON
> ```

你得添加 –DWITH_GLOO=ON 才能开启cpu并行。

2021-11-04 02:43 UTC, wduo commented
> > > @2742195759 您好！源码编译最新的develop分支后，用python -m paddle.distributed.launch --nproc_per_node=4 --backend=gloo train.py训练，运行到dist.init_parallel_env()这句时报错如下： AttributeError: module 'paddle.fluid.core_avx' has no attribute 'GLOOParallelContext' 请问您这个是因为什么呢？是需要把develop分支代码回退到您提交时的版本吗？
> > 
> > 
> > 我用docker环境编译的CPU版的：
> > ```
> > cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON
> > ```
> 
> 你得添加 –DWITH_GLOO=ON 才能开启cpu并行。

您好，已经添加 ` –DWITH_GLOO=ON `并且不再报上述错误，但是报了一个新的错误如下：
```
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'
```
请问您这个是因为什么呢？是否是某些第三方库下载不完整的原因呢？

2021-11-04 02:51 UTC, wduo commented
@2742195759 完成的报错信息如下：
```
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 78, in main
    model = paddle.DataParallel(model)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 582, in __init__
    sync_params_buffers(self._layers)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 230, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 377, in sync_params_buffers
    coalesced_var, src=src_rank, group=comm_group, use_calc_stream=True)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/collective.py", line 394, in broadcast
    return _C_ops.c_broadcast(tensor, tensor, 'root', gsrc,
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'
```

2021-11-04 03:03 UTC, 2742195759 commented
> @2742195759 完成的报错信息如下：
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 125, in <module>
>     main(config, device, logger, vdl_writer)
>   File "tools/train.py", line 78, in main
>     model = paddle.DataParallel(model)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 582, in __init__
>     sync_params_buffers(self._layers)
>   File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 230, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 377, in sync_params_buffers
>     coalesced_var, src=src_rank, group=comm_group, use_calc_stream=True)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/collective.py", line 394, in broadcast
>     return _C_ops.c_broadcast(tensor, tensor, 'root', gsrc,
> AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'
> ```

看样子还是有某些cmake的选项没有开启，导致没有编译到这个c broadcast 属性。我晚上帮你看下。你可以先试试 –DWITH_DISTRIBUTED 这个属性是否有用。

2021-11-04 03:45 UTC, wduo commented
我刚才运行`cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GLOO=ON -DWITH_DISTRIBUTE=ON` ，在最后几行看到了一个`MESSAGE`信息：
```
...
ccache version                      3.7
cache directory                     /root/.ccache
primary config                      /root/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/ccache-3.7.9/etc/ccache.conf
stats updated                       Thu Nov  4 02:24:53 2021
cache hit (direct)                  1061
cache hit (preprocessed)             937
cache miss                           962
cache hit rate                     67.50 %
called for link                     4990
cleanups performed                     0
files in cache                      2801
cache size                         560.3 MB
max cache size                       5.0 GB

-- Paddle version is 0.0.0
-- Enable Intel OpenMP with /paddle/build/third_party/install/mklml/lib/libiomp5.so
CMake Warning at CMakeLists.txt:403 (message):
  On inference mode, will take place some specific optimization.  Turn on the
  ON_INFER flag when building inference_lib only.


-- generating brpc sendrecv.proto
-- commit: e512aa9a4b
-- branch: develop
WITH_DLNNE:
-- MESSAGE: This is just a message for publishing release.
      You are building AVX version without NOAVX core.
      So the wheel package may fail on NOAVX machine.
      You can add -DNOAVX_CORE_FILE=/path/to/your/core_noavx.* in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local machine.
-- Configuring done
-- Generating done
-- Build files have been written to: /paddle/build
```

您看是否是因为这个的原因呢？

2021-11-04 03:48 UTC, wduo commented
我这会儿正在尝试再添加一个` -WITH_AVX=OFF` 试下；
或者是否是需要使用`-DNOAVX_CORE_FILE=/path/to/your/core_noavx.*`呢？请问您这个文件`core_noavx.*`应该在哪里找到呢？

2021-11-04 11:29 UTC, wduo commented
@2742195759 您好！上述问题已解决，均为第三方库下载时的网络问题，使相应包安装不完整。感谢您的答复！

2021-11-04 15:29 UTC, 2742195759 commented
> @2742195759 您好！上述问题已解决，均为第三方库下载时的网络问题，使相应包安装不完整。感谢您的答复！

好的~