Add functional autograd API: jacobian
PaddlePaddle/Paddle pull request #35917
Opened 2021-09-22 09:11 UTC by levi131

### PR types
<!--  New features

### PR changes
<!--  APIs

### Describe
Add functional autograd API: jacobian

2021-09-24 10:12 UTC, JiabinYang approved these changes
LGTM

2021-09-26 02:53 UTC, phlrain commented on python/paddle/autograd/functional.py
> +        **This API is ONLY available in Dygraph mode.**
imperative mode

2021-09-26 03:28 UTC, JiabinYang requested changes
Fix bugs first

2021-09-26 03:28 UTC, levi131 commented on python/paddle/autograd/functional.py
> +        **This API is ONLY available in Dygraph mode.**
done

2021-09-26 04:05 UTC, XieYunshen approved these changes, later dismissed
LGTM for set_tests_properties(test_jacobian PROPERTIES TIMEOUT 20)

2021-09-26 08:08 UTC, TCChenlong approved these changes, later dismissed

2021-09-26 08:08 UTC, TCChenlong commented on python/paddle/autograd/functional.py
> +    '''
缺少示例代码

2021-09-26 08:09 UTC, levi131 commented on python/paddle/autograd/functional.py
> +    '''
已经补充

2021-09-26 09:52 UTC, phlrain approved these changes

2021-09-26 10:27 UTC, CheQiXiao approved these changes

2021-09-26 10:34 UTC, XieYunshen approved these changes

2021-09-26 10:44 UTC, PangHua approved these changes

2021-09-26 11:09 UTC, JiabinYang submitted a review, later dismissed
LGTM

2021-09-26 11:29 UTC, TCChenlong approved these changes

2021-09-27 06:04 UTC, merged