Polish multi-thread schedule strategy and Keep one task in current thread
PaddlePaddle/Paddle pull request #35928
Opened 2021-09-22 13:03 UTC by Aurelius84

### PR types

Others
### PR changes

Others
### Describe

Polish multi-thread schedule strategy and Keep one task in current thread

2021-09-24 09:01 UTC, liutiexing requested changes

2021-09-24 09:01 UTC, liutiexing commented on paddle/fluid/framework/new_executor/interpretercore.cc
> +        async_work_queue_.AddTask(
先ADD，再run留下的，尽早add其他thread尽早执行

2021-09-24 10:22 UTC, Aurelius84 commented on paddle/fluid/framework/new_executor/interpretercore.cc
> +        async_work_queue_.AddTask(
Thanks, done

2021-09-26 03:30 UTC, wanghuancoder approved these changes
LGTM

2021-09-26 04:49 UTC, liutiexing approved these changes

2021-09-27 05:02 UTC, merged