Add celu use c++
PaddlePaddle/Paddle pull request #36088
Opened 2021-09-26 03:53 UTC by JunnYu

### PR types

New features
### PR changes

OPs
### Describe

debug

2021-09-28 08:23 UTC, JunnYu commented
- PR-CI-Coverage中python覆盖100%，c++代码覆盖有点低，好多`REGISTER_OP`都没覆盖到，不清楚为什么- -。
- PR-CI-CPU-Py2 没有approve。

2021-10-08 03:19 UTC, zhiboniu requested changes

2021-10-08 03:19 UTC, zhiboniu commented on paddle/fluid/operators/activation_op.h
> +class CELUDoubleGradKernel
如果代码实现与ELU相同，是否有必要重复代码，是否可以直接沿用ELU的代码？

2021-10-08 03:19 UTC, zhiboniu commented on python/paddle/nn/functional/activation.py
> +        elu(x) = max(0, x) + min(0, \alpha * (e^{x/\alpha}-1))
elu -> celu

2021-10-08 07:10 UTC, JunnYu commented on python/paddle/nn/functional/activation.py
> +        elu(x) = max(0, x) + min(0, \alpha * (e^{x/\alpha}-1))
done

2021-10-08 07:15 UTC, JunnYu commented on paddle/fluid/operators/activation_op.h
> +class CELUDoubleGradKernel
代码实现大致与ELU相同，但是存在些许不同：
（1）前向计算多了个alpha
（2）反向传播计算梯度时候，由于多了alpha因此，计算的梯度方式有些许不同之处。
```bash
   CELU的
    // dx = dout , if alpha > 0 and x > 0
    // dx = dout * (x/alpha).exp(), if alpha > 0 and x <= 0
    // dx = dout , if alpha < 0 and x > 0
    // dx = dout * (x/alpha).exp(), if alpha < 0 and x <=0

   ELU的
   // dx = dout, if alpha > 0 and x > 0
   // dx = dout * alpha * x.exp(), if alpha > 0 and x <= 0
   // dx = dout * (1 + alpha * x.exp()), if alpha <= 0 and x > 0
   // dx = 0, if alpha <= 0 and x <=0
```

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/__init__.py
> +from .layer.activation import CELU  # noqa: F401
`CELU` 也需要加到下面的 \_\_all\_\_ 中

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/layer/activation.py
> +    Parameters:
Parameters: 前需要加一个空行

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/layer/activation.py
> +    .. math::
.. math:: 前需要加一个空行

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/layer/activation.py
> +    Shape:
Shape: 前 需要加一个空行

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/layer/activation.py
> +    Examples:
Examples: 前需要加一个空行

2021-10-11 03:15 UTC, TCChenlong commented on python/paddle/nn/layer/activation.py
> +            import paddle
import paddle 前需要加一个空行

2021-10-11 11:54 UTC, JunnYu commented
@zhiboniu 同样的，这个我之前也想过使用纯Python实现，然后发现paddle的有些算子不支持float16，如paddle.where，于是我才想到用c++的来实现这个算子。https://github.com/PaddlePaddle/Paddle/pull/36076/

2021-10-13 02:32 UTC, zhiboniu approved these changes
lgtm

2021-10-13 02:41 UTC, TCChenlong commented
还需要在 [docs](https://github.com/PaddlePaddle/docs) 中补充对应的中文文档~

2021-10-13 07:43 UTC, XiaoguangHu01 approved these changes
LGTM

2021-10-13 07:47 UTC, TCChenlong approved these changes
LGTM

2021-10-13 10:43 UTC, merged