[IPU] ipu backend
PaddlePaddle/Paddle pull request #36322
Opened 2021-10-11 02:32 UTC by jianghaicheng

### PR types

New features

### PR changes

Others

### Describe

This  PR contains the code of  CMake, ipu compile, and compute method.

2021-10-11 02:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=36322) <br/>All committers have signed the CLA.

2021-10-11 03:13 UTC, qili93 requested changes

2021-10-11 03:13 UTC, qili93 commented on cmake/external/poplar.cmake
> +    message(FATAL_ERROR "You must provide a path to a Poplar install using -DPOPLAR_DIR=/path/to/popart/build/install")
Please use ENV variable to set the POPLAR_DIR, for example "if(NOT DEFINED ENV{ROCM_PATH})" in hip.cmake and "if(DEFINED ENV{ASCEND_CUSTOM_PATH})" in ascend.cmake.

2021-10-11 03:13 UTC, qili93 commented on cmake/external/protobuf.cmake
> +        SET(PROTOBUF_TAG         d750fbf648256c7c631f51ffdbf67d7c18b0114e)
Which protobuf version here used for IPU?

2021-10-11 03:13 UTC, qili93 commented on cmake/external/protobuf.cmake
> +    SET(PROTOBUF_VERSION d750fbf648256c7c631f51ffdbf67d7c18b0114e)
If this commit is mapping to specific protobuf version or tag, please replace the commit id with version number.

2021-10-11 03:13 UTC, qili93 commented on cmake/generic.cmake
> +    add_dependencies(${TARGET_NAME} ${cc_test_DEPS} paddle_gtest_main lod_tensor memory gtest gflags glog proto_desc)
please add if (WITH_IPU) for this modification to avoid impact to other platform.

2021-10-11 03:18 UTC, qili93 requested changes

2021-10-11 03:18 UTC, qili93 commented on paddle/fluid/framework/ipu/ipu_strategy.cc
> +//
remove this line?

2021-10-11 03:18 UTC, qili93 commented on paddle/fluid/framework/ipu/ipu_utils.h
> +#include <memory>
<memory> is redundant, try to remove?

2021-10-11 03:18 UTC, qili93 commented on paddle/fluid/framework/ipu/ipu_utils.h
> +  }
Please use PADDLE_ENFORCE_EQ here, i.e.

PADDLE_ENFORCE_EQ(lod_tensor.lod().size(), 0UL, ....)
return Tensor2IArray<T>(lod_tensor);

Then no if else needed.

2021-10-11 03:18 UTC, qili93 commented on paddle/fluid/framework/ipu/supported_ops_custom.h
> +#pragma once
This file is reserved? If not, please remove this, and only .cc file is also able to generate an C++ object.

2021-10-11 03:18 UTC, qili93 commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_custom.h"
This file is reserved? If not, please remove this, and only .cc file is also able to generate an C++ object.

2021-10-11 05:46 UTC, jianghaicheng commented on cmake/external/poplar.cmake
> +    message(FATAL_ERROR "You must provide a path to a Poplar install using -DPOPLAR_DIR=/path/to/popart/build/install")
OK, I will use WITH_IPU

2021-10-11 05:59 UTC, jianghaicheng commented on cmake/external/protobuf.cmake
> +    SET(PROTOBUF_VERSION d750fbf648256c7c631f51ffdbf67d7c18b0114e)
OK changed to v3.6.1

2021-10-11 06:06 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/ipu_strategy.cc
> +//
removed

2021-10-11 06:09 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/ipu_utils.h
> +#include <memory>
std::unique_ptr in ipu_utils.cc used it.

2021-10-11 06:13 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/ipu_utils.h
> +  }
Applied

2021-10-11 06:19 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops_custom.h
> +#pragma once
This file is deleted because it is empty.

2021-10-11 06:36 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_custom.h"
This file is reserved due to future functions expansion.

2021-10-11 08:35 UTC, gglin001 commented on cmake/external/protobuf.cmake
> +        SET(PROTOBUF_TAG         d750fbf648256c7c631f51ffdbf67d7c18b0114e)
here we need to keep the same version as popart used(which is a commit id)

2021-10-11 08:54 UTC, jianghaicheng commented on cmake/generic.cmake
> +    add_dependencies(${TARGET_NAME} ${cc_test_DEPS} paddle_gtest_main lod_tensor memory gtest gflags glog proto_desc)
applied

2021-10-11 11:10 UTC, jianghaicheng commented on cmake/external/protobuf.cmake
> +        SET(PROTOBUF_TAG         d750fbf648256c7c631f51ffdbf67d7c18b0114e)
3.6.1 就行

2021-10-12 03:47 UTC, qili93 requested changes

2021-10-12 03:47 UTC, qili93 commented on cmake/external/poplar.cmake
> +    message(FATAL_ERROR "You must provide a path to a Popart build using -DPOPART_DIR=/path/to/popart/build")
这条comment的意思是，我们一般很少通过cmake -D的方式来说输入超长路径，建议改成通过环境变量的方式，就是用户在环境变量里面输出`export POPART_DIR=/path/to/popart/build`，然后这里的cmake通过 `$ENV{POPART_DIR}`的方式获取，如果用户未定义就抛出一个ERROR或者给个PopART的默认安装路径。这样编译的时候的cmake相对会比较简洁。

2021-10-12 03:47 UTC, qili93 commented on paddle/fluid/framework/ipu/ipu_utils.h
> +#include <memory>
#include <memory> is also included in "paddle/fluid/framework/lod_tensor.h", so needless to include again here.

2021-10-12 03:47 UTC, qili93 commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_autogen.h"
If this file is reserved, please add some comment here for the usage.

2021-10-12 03:47 UTC, qili93 commented on paddle/fluid/framework/ipu/supported_ops_autogen.h
> +OP_DECL(popart_transpose, aiOnnxOpset.transpose, ARG(INT_VEC,perm) ) // NOLINT
Able to sort all the ops by alphabetic index? Or maybe categorize them as activations, math_ops, elementwise ops, etc. ?

2021-10-12 04:02 UTC, qili93 requested changes

2021-10-12 04:02 UTC, qili93 commented on paddle/fluid/framework/ipu/device.h
> +
与设备管理相关的代码最好都能放到 platform 文件夹下面，不要放到 framework 下面，因为Paddle这里framework是定义paddle自身相关代码的。还有这个类的功能应该类似于 npu_info.h / xpu_info.h / gpu_info.h，建议参考其他硬件接入的代码写成 GetIPUDeivceID() 这样的格式。方便以后对所有硬件做统一封装。

2021-10-12 05:41 UTC, jianghaicheng commented on cmake/external/poplar.cmake
> +    message(FATAL_ERROR "You must provide a path to a Popart build using -DPOPART_DIR=/path/to/popart/build")
Get

2021-10-12 06:02 UTC, gglin001 commented on paddle/fluid/framework/ipu/supported_ops_autogen.h
> +OP_DECL(popart_transpose, aiOnnxOpset.transpose, ARG(INT_VEC,perm) ) // NOLINT
这里是按照不同的 opset 支持来分类的, 每一部分的opset内部是按照 alphabetic 排序的(开始的 AiGraphcoreOpset1 除外), 考虑到后面popart的变化, 这样的排序应该是 make sense 的

2021-10-12 06:02 UTC, gglin001 commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_autogen.h"
可以去掉这个文件, ipu_compiler.cc 那里直接 include  `supported_ops_autogen.h` @jianghaicheng

2021-10-12 06:19 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops_autogen.h
> +OP_DECL(popart_transpose, aiOnnxOpset.transpose, ARG(INT_VEC,perm) ) // NOLINT
They are sorted by onnx opset

2021-10-12 06:19 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_autogen.h"
OK

2021-10-12 06:52 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/device.h
> +
我们在微信群里讨论了这个问题，如果需要的话可以进一步讨论。

2021-10-13 03:07 UTC, qili93 requested changes

2021-10-13 03:07 UTC, qili93 commented on paddle/fluid/framework/ipu/ipu_executor.cc
> +    auto tensor = const_cast<Tensor *>(outputs[i]);
Please avoid using const_cast in code, try to edit he code as 

framework::Tensor tensor;
tensor.ShareDataWith(*outputs[i]);

2021-10-13 03:09 UTC, qili93 commented on paddle/fluid/framework/ipu/supported_ops_autogen.h
> +OP_DECL(popart_transpose, aiOnnxOpset.transpose, ARG(INT_VEC,perm) ) // NOLINT
那可以给不同的 opset 分类前后加一些comments之类的标注一下不？方便查看

2021-10-13 05:20 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops.h
> +#include "paddle/fluid/framework/ipu/supported_ops_custom.h"
removed

2021-10-13 05:21 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/ipu_executor.cc
> +    auto tensor = const_cast<Tensor *>(outputs[i]);
Applied

2021-10-13 05:24 UTC, jianghaicheng commented on paddle/fluid/framework/ipu/supported_ops_autogen.h
> +OP_DECL(popart_transpose, aiOnnxOpset.transpose, ARG(INT_VEC,perm) ) // NOLINT
加入了opset 分类注释：
// Ops from AiGraphcoreOpset1
// Ops from AiOnnxOpset9
// Ops from AiOnnxOpset8
// Ops from AiOnnxOpset7

2021-11-16 11:38 UTC, ronny1996 requested changes

2021-11-16 11:40 UTC, ronny1996 commented on paddle/fluid/operators/ipu_runtime_op.cc
> +REGISTER_OP_CPU_KERNEL(ipu_runtime, ops::IpuRuntimeKernel<float>,
这里为什么需要注册两个kernel？

2021-11-16 11:49 UTC, ronny1996 commented
请将ipu底层api封装的代码文件放到paddle/fluid/platform/device/ipu目录下，如paddle/fluid/platform/ipu_info.h放到paddle/fluid/platform/device/ipu/ipu_info.h

2021-11-17 08:19 UTC, jianghaicheng commented on paddle/fluid/operators/ipu_runtime_op.cc
> +REGISTER_OP_CPU_KERNEL(ipu_runtime, ops::IpuRuntimeKernel<float>,
已经修改

2021-11-18 03:09 UTC, jianghaicheng commented on paddle/fluid/operators/ipu_runtime_op.cc
> +REGISTER_OP_CPU_KERNEL(ipu_runtime, ops::IpuRuntimeKernel<float>,
这个文件移动到https://github.com/PaddlePaddle/Paddle/pull/36941 里了，不然变编译会有问题

2021-11-18 09:45 UTC, ronny1996 commented
LGTM

2021-12-02 06:02 UTC, qili93 approved these changes, later dismissed
LGTM

2021-12-03 09:34 UTC, qili93 approved these changes
LGTM

2021-12-03 09:38 UTC, luotao1 approved these changes
LGTM for CMakeLists.txt

2021-12-03 09:58 UTC, raindrops2sea approved these changes

2021-12-03 10:07 UTC, merged