[NPU] Add sync_batch_norm and sync_batch_norm_grad NPU Kernel
PaddlePaddle/Paddle pull request #36320
Opened 2021-10-10 13:28 UTC by windstamp

### PR types

New features
### PR changes

OPs
### Describe

[NPU] Add sync_batch_norm and sync_batch_norm_grad NPU Kernel

<img width="1260" alt="50d5f5970df1a8e8813d39943c6d534f" src="https://user-images.githubusercontent.com/34057289/136703736-1d89678b-7a52-464d-81f4-4b0b70596ff3.png">

<img width="783" alt="1c2a412ce222cd58927c6c4a6122631c" src="https://user-images.githubusercontent.com/34057289/136703760-2f6b553d-aa73-4859-94a0-f987ae57cb62.png">

<img width="741" alt="dff24f0ca5e66900b9743b81a7e00ea3" src="https://user-images.githubusercontent.com/34057289/136703778-4812ac5b-c8de-4f66-80ea-598164a0761a.png">

2021-10-11 03:34 UTC, qili93 requested changes

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/batch_norm_op_npu.cc
> +      saved_variance->mutable_data<float>(ctx.GetPlace());
why change the datatype to float, the template datatype T should also equal to float16?

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/batch_norm_op_npu.cc
> +      d_bias->mutable_data<float>(ctx.GetPlace());
same question as above.

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/conv_op_npu.cc
> +
remove the above lines.

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/conv_op_npu.cc
> +
remove these LOG(WARNING) lines.

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +#endif
why #if defined(PADDLE_WITH_ASCEND_CL) here? this npu.cc file will not be compiled if WITH_ASCEND OFF.

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +
remove debug functions of outputVector and PrintTensor here

2021-10-11 03:34 UTC, qili93 commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +    LOG(WARNING) << "common_mean_tile_1: ";
remove all LOG(WARNING) messages.

2021-10-12 10:50 UTC, windstamp commented on paddle/fluid/operators/batch_norm_op_npu.cc
> +      saved_variance->mutable_data<float>(ctx.GetPlace());
thanks.

1. 参考 batch_norm_op.cu，参数 X 和 Y 为 float16 时，其它参数（mean, variance, scale, bias 等）仍然是 float32。
2. 背后的原因可能是，对于模型训练（比如 AMP - float16 训练），只是会将参数 X 和 Y 转换为 float16，其它的参数仍然是 float32，所以 batch_norm_op.cu 是目前的实现。
3. 类似于第 2 点，单元测试构建的模型，参数 mean, variance, scale, bias 等即使对于 float16 测试 case，仍然是 float32。
4. Ascend BNTrainingUpdate 的文档，对于上述参数类型的描述是类似的。

![c0fdd206418021cab49c777799536a7d](https://user-images.githubusercontent.com/34057289/136942391-3b49331e-6447-419a-bbee-e7e879054270.png)

2021-10-12 10:51 UTC, windstamp commented on paddle/fluid/operators/batch_norm_op_npu.cc
> +      d_bias->mutable_data<float>(ctx.GetPlace());
thanks.

解释如上。

2021-10-12 10:51 UTC, windstamp commented on paddle/fluid/operators/conv_op_npu.cc
> +
done, thanks.

2021-10-12 10:51 UTC, windstamp commented on paddle/fluid/operators/conv_op_npu.cc
> +
done, thanks.

2021-10-12 10:52 UTC, windstamp commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +#endif
Deleted, thanks.

2021-10-12 10:52 UTC, windstamp commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +
done, thanks.

2021-10-12 10:52 UTC, windstamp commented on paddle/fluid/operators/sync_batch_norm_op_npu.cc
> +    LOG(WARNING) << "common_mean_tile_1: ";
done, thanks.

2021-10-21 06:27 UTC, qili93 approved these changes
LGTM

2021-10-21 07:38 UTC, zhiqiu approved these changes
LGTM

2021-10-21 10:30 UTC, raindrops2sea approved these changes

2021-10-21 10:31 UTC, raindrops2sea approved these changes

2021-10-21 10:42 UTC, merged