[NPU] Add iou_similarity op
PaddlePaddle/Paddle pull request #36412
Opened 2021-10-13 10:45 UTC by Ray2020BD

### PR types

New features
### PR changes

OPs 
### Describe

[NPU] Add iou_similarity op
![image](https://user-images.githubusercontent.com/70498791/137118703-2a0b09d9-ba83-483b-80cd-7e8f4fe713f7.png)
![image](https://user-images.githubusercontent.com/70498791/137118719-26d1c1d8-5690-4276-865e-dacc95b89d6c.png)

2021-10-18 12:18 UTC, qili93 requested changes

2021-10-18 12:18 UTC, qili93 commented on paddle/fluid/operators/detection/CMakeLists.txt
>  else()
这里可以改成

if (WITH_XPU)
...
elseif(WITH_ASCEND_CL)
...
else()
...
endif()

2021-10-19 00:04 UTC, Ray2020BD commented on paddle/fluid/operators/detection/CMakeLists.txt
>  else()
done

2021-10-19 11:32 UTC, qili93 approved these changes
LGTM

2021-10-19 11:32 UTC, merged