Add lazy distributed launch with rank mapping
PaddlePaddle/Paddle pull request #36570
Opened 2021-10-20 05:42 UTC by bliu3650

### PR types
New features

### PR changes
Others

### Describe
Lazy launch for starting un-balanced subprocesses on each node. This feature is required for auto parallel scenario which will split the user task automatically and dispatch sub-task to distributed nodes/ranks. Partial ranks of some nodes will be chosen to execute the related sub-tasks. The rank mapping is a json file with format:
`{ 
  "ip_ranks": [
    {
      "ip": "127.0.0.1",
      "ranks": [0,1]
    },
    {
      "ip": "127.0.0.2",
      "ranks": [2,3,4]
    }
  ]
}`

2021-10-20 05:48 UTC, bliu3650 commented
This new PR is the same as https://github.com/PaddlePaddle/Paddle/pull/35793, but only change the email address of author for passing the CLA check.

2021-10-21 09:21 UTC, gongweibao requested changes

2021-10-21 09:21 UTC, gongweibao commented on python/paddle/distributed/fleet/launch.py
> +    elif args.enable_auto_mapping == True:
device_mode和这个args是ifelse的关系吗？

2021-10-21 09:21 UTC, gongweibao commented on python/paddle/distributed/fleet/launch.py
> +    elif args.enable_auto_mapping == True:
这个ifelse策略需要梳理？

2021-10-21 09:24 UTC, gongweibao reviewed
lazy launch代表什么含义？

2021-10-21 10:29 UTC, bliu3650 commented on python/paddle/distributed/fleet/launch.py
> +    elif args.enable_auto_mapping == True:
这里的一组 if-elseif 是区分 local、cloud 场景的；其中 device_mode 在修改前也是单独作为一个分支（因为其特殊性，只在 cloud 环境下使用 acend 硬件）；本次修改加入的 lazy_launch 在 local 和 cloud 场景下共用一个解析逻辑（rank_mapping 有依赖自动并行的分析结果，暂不支持，就没有做区分，统一提供 json 文件作为输入）。

2021-10-21 10:33 UTC, bliu3650 commented
> lazy launch代表什么含义？

是相对于 launch 的默认对称启动而言的；因自适应需要先对训练任务进行资源使用分析，基于分析结果再做启动动作（也就是这里的延迟启动）。这种启动方式需要接收 rank-mapping 输入信息，按需启动不同节点上的不同数量的训练进程（卡数）。

2021-10-22 03:59 UTC, bliu3650 commented on python/paddle/distributed/fleet/launch.py
> +    elif args.enable_auto_mapping == True:
> 这个ifelse策略需要梳理？

之前实现过一个分支顺序：
1. 不改变原有的分支结构 if use_paddlecloud（branch 1）; elseif device_mode（branch 2）; else（branch 3）
2. 分别在 branch 1 和 3 中增加对 enable_auto_mapping 的支持

效果如下：
<img width="357" alt="截屏2021-10-22 上午11 55 07" src="https://user-images.githubusercontent.com/21085266/138391122-789998a1-17a6-4adc-bba3-dc1631a4a37f.png">

如果可以接受，我就按这个分支顺序改一下？ @gongweibao @aoyulong

2021-10-26 10:00 UTC, bliu3650 commented on python/paddle/distributed/fleet/launch.py
> +    elif args.enable_auto_mapping == True:
将 enable_auto_mapping 分支上升到最外层，区分其它分支结构。

2021-10-26 12:23 UTC, gongweibao commented on python/paddle/distributed/fleet/launch.py
>      elif device_mode == DeviceMode.ASCEND_NPU:
```
else:
       if device_mode == DeviceMode.ASCEND_NPU:
```

2021-10-27 01:35 UTC, bliu3650 commented on python/paddle/distributed/fleet/launch.py
>      elif device_mode == DeviceMode.ASCEND_NPU:
Done.

2021-10-27 03:00 UTC, gongweibao approved these changes
LGTM

2021-10-28 03:03 UTC, merged