[Cherry-pick] Enable CTC grad compute on GPU
PaddlePaddle/Paddle pull request #36780
Opened 2021-10-27 07:36 UTC by zh794390558

### PR types

Bug fixes
### PR changes

APIs
### Describe

cherry pick to 2.2
same to :
https://github.com/PaddlePaddle/Paddle/pull/36756

* Reverts ctc grad scale same with espnet #34729，之前的grad norm计算方式完全没有必要。espnet是把reduce相关的op放到ctc中实现的，我们是分开实现的，所以ctc grad计算保持原样即可。回退之前的PR。
* ctc grad compute on gpu。之前的PR包含将GRAD计算放到GPU上，所以保留此部分修改。
* 2.2-rc引入 ctc grad scale same with espnet #34729 修改，2.2 revert op api的修改。
* warpctc 2.2-rc之前无 OP_VERSION
* warpctc 整个 Op 都不会用到预测模型里

2021-10-27 07:38 UTC, XiaoguangHu01 approved these changes
LG API

2021-10-27 07:39 UTC, TCChenlong approved these changes

2021-10-27 07:42 UTC, zhangting2020 approved these changes
LGTM for skip_check_grad_ci

2021-10-27 07:43 UTC, ZeyuChen approved these changes
LGTM

2021-10-27 12:30 UTC, Superjomn requested changes

2021-10-27 12:30 UTC, Superjomn commented on paddle/fluid/operators/warpctc_op.cc
> -
怎么连 OpVersion 都删了？ 
这是推理监测 Op 升级用的

如果只有训练用到，那可以备注下只用于训练，不影响预测。

如果这个是推理会用的，应该是有问题的，看起来这个 Op 是改了定义是吧？ 那应该破坏推理向前兼容了，可以参考下 Op 开发规范，里面应该是不能直接删除已有的 attribute 的

2021-10-27 12:52 UTC, zh794390558 commented on paddle/fluid/operators/warpctc_op.cc
> -
2.2-rc引入了参数，这次修改需要revert之前的修改。只将grad放到GPU上计算，不涉及op接口变动。

2021-10-28 06:15 UTC, Superjomn approved these changes
了解 wrapctc 不会用到推理模型中，LGTM

2021-10-28 06:24 UTC, ZeyuChen approved these changes
LGTM

2021-10-28 06:42 UTC, merged