add ipu device
PaddlePaddle/Paddle pull request #36941
Opened 2021-11-02 10:46 UTC by jianghaicheng

### PR types

New features

### PR changes

Others

### Describe

This PR contains the code corresponding to hardware.

2021-11-16 11:46 UTC, ronny1996 commented
请将ipu底层api封装的代码文件放到paddle/fluid/platform/device/ipu目录下，如paddle/fluid/platform/ipu_info.h

2021-11-16 11:56 UTC, ronny1996 commented on paddle/fluid/framework/tensor_util.cc
> +  }
这里修改是否多余

2021-11-16 11:56 UTC, ronny1996 commented on python/paddle/fluid/__init__.py
> +        read_env_flags += [
这里为什么添加一段npu代码

2021-11-17 07:09 UTC, jianghaicheng commented on paddle/fluid/framework/tensor_util.cc
> +  }
这里修改是因为pre-commit 过不了，NOLINT貌似没有起作用。这个文件还有其他相似的地方

2021-11-17 08:11 UTC, jianghaicheng commented on python/paddle/fluid/__init__.py
> +        read_env_flags += [
这块儿应该是解冲突的时候的问题。我修一下

2021-11-18 09:45 UTC, ronny1996 commented
LGTM

2021-11-18 11:36 UTC, qili93 requested changes

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/framework/tensor_util.cc
> +  }
和其他硬件平台的实现相比，这里为什么只有 cpu -> ipu的TensorCopy，没有 ipu -> cpu 和 ipu -> ipu 的内存拷贝？

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/framework/tensor_util.cc
> +#endif
同上，和其他硬件平台相比，少了 ipu -> ipu 的 TensorCopySync的实现？

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/framework/tensor_util.cc
> +    // return GetResultHelper(out, ipu);
这行注释代码删掉？

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/platform/CMakeLists.txt
> +ENDIF(WITH_IPU)
把这段代码往上挪？放到和 XPU_CTX_DEPS ASCEND_DEPS 附近

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/pybind/pybind.cc
> +
这里的 API 增加需要相应的在 https://github.com/PaddlePaddle/docs 这个repo中增加中文API的说明文档，可以参考其他硬件的中文API实现。

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/pybind/pybind.cc
> +  m.def("is_compiled_with_ipu", IsCompiledWithIPU);
为什么这里有2个重复的 IsCompiledWithIPU?

2021-11-18 11:36 UTC, qili93 commented on paddle/fluid/pybind/tensor_py.h
> +    }
参考其他硬件，这里需要有 #else 和 PADDLE_THROW

2021-11-18 11:36 UTC, qili93 commented on python/paddle/device/__init__.py
> +
同上，API中文文档增加

2021-11-19 02:15 UTC, jianghaicheng commented on paddle/fluid/framework/tensor_util.cc
> +  }
其实是没有用到，我把它添上吧

2021-11-19 02:16 UTC, jianghaicheng commented on paddle/fluid/framework/tensor_util.cc
> +#endif
同上

2021-11-19 02:17 UTC, jianghaicheng commented on paddle/fluid/framework/tensor_util.cc
> +    // return GetResultHelper(out, ipu);
Ok

2021-11-19 02:28 UTC, jianghaicheng commented on paddle/fluid/platform/CMakeLists.txt
> +ENDIF(WITH_IPU)
OK

2021-11-19 02:29 UTC, jianghaicheng commented on paddle/fluid/pybind/pybind.cc
> +  m.def("is_compiled_with_ipu", IsCompiledWithIPU);
已经删除

2021-11-19 02:39 UTC, jianghaicheng commented on paddle/fluid/pybind/tensor_py.h
> +    }
Ok

2021-11-19 08:45 UTC, jianghaicheng commented on python/paddle/device/__init__.py
> +
已经添加在pr: https://github.com/PaddlePaddle/docs/pull/4113/files

2021-11-19 08:45 UTC, jianghaicheng commented on paddle/fluid/pybind/pybind.cc
> +
已经添加在pr: https://github.com/PaddlePaddle/docs/pull/4113/files

2021-11-19 11:25 UTC, jianghaicheng commented
re-run

2021-12-14 06:37 UTC, jianghaicheng commented
pr已经拆分，本pr关闭

2021-12-14 06:37 UTC, closed without merging