【PaddlePaddle Hackathon】31. 为 Paddle Inference 添加新的前端语言
PaddlePaddle/Paddle pull request #37162
Opened 2021-11-12 14:41 UTC by chenyanlann

### PR types
New features

### PR changes
为 Paddle Inference 添加 Java Apis

### Describe

Task: #35977

#### Paddle Inference java API

Paddle Inference java API 基于 [capi](../capi_exp) 和 jni 实现，需要您提前准备好C预测库。

#### 安装(Linux)

##### 1.下载C预测库

您可以选择直接下载[paddle_inference_c](https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/user_guides/download_lib.md)预测库，或通过源码编译的方式安装，源码编译方式参考官网文档，注意这里cmake编译时打开`-DON_INFER=ON`,在编译目录下得到`paddle_inference_c_install_dir`。

##### 2.准备预测部署模型

下载 [resnet50](https://paddle-inference-dist.bj.bcebos.com/Paddle-Inference-Demo/resnet50.tgz) 模型后解压，得到 Paddle Combined 形式的模型。

```
wget https://paddle-inference-dist.bj.bcebos.com/Paddle-Inference-Demo/resnet50.tgz
tar zxf resnet50.tgz

#### 获得 resnet50 目录结构如下
resnet50/
├── inference.pdmodel
├── inference.pdiparams
└── inference.pdiparams.info
```

##### 3.准备预测执行目录

```
git clone github.com/paddlepaddle/paddle/paddle/fluid/inference/javaapi
```

##### 3. 编译动态链接库和jar包

```bash
在javaapi目录下执行

./build_gpu.sh {c预测库目录} {jni头文件目录} {jni系统头文件目录}

以笔者的目录结构为例
./build_gpu.sh /root/paddle_c/paddle_inference_c /usr/lib/jvm/java-8-openjdk-amd64/include /usr/lib/jvm/java-8-openjdk-amd64/include/linux

执行完成后，会在当前目录下生成JavaInference.jar和libpaddle_inference.so
```

##### 5.运行单测，验证

```
在javaapi目录下执行

./test.sh {c预测库目录} {.pdmodel文件目录} {.pdiparams文件目录}

以笔者的目录结构为例
./test.sh "/root/paddle_c/paddle_inference_c_2.2/paddle_inference_c"  "/root/paddle_c/resnet50/inference.pdmodel" "/root/paddle_c/resnet50/inference.pdiparams"
```

#### 在Java中使用Paddle预测

首先创建预测配置

```java
Config config = new Config();
config.setCppModel(model_file, params_file);
```

创建predictor

```java
Predictor predictor = Predictor.createPaddlePredictor(config);
```

获取输入Tensor

```java
String inNames = predictor.getInputNameById(0);
Tensor inHandle = predictor.getInputHandle(inNames);
```

设置输入数据(假设只有一个输入)

```java
inHandle.Reshape(4, new int[]{1, 3, 224, 224});
float[] inData = new float[1*3*224*224];
inHandle.CopyFromCpu(inData);
```

运行预测

```java
predictor.Run();
```

获取输出Tensor

```java
String outNames = predictor.getOutputNameById(0);
Tensor outHandle = predictor.getOutputHandle(outNames);
float[] outData = new float[outHandle.GetSize()];
outHandle.CopyToCpu(outData);
```

2021-11-21 15:29 UTC, chenyanlann commented
@TCChenlong

2021-11-23 01:07 UTC, TCChenlong commented
还在review中哈~

2021-11-23 02:46 UTC, DannyIsFunny commented
编译过程的中间产物需要从PR中删除： `JavaInference.jar`、`libpaddle_inference.so `、`Config.class` 等等

2021-11-23 02:49 UTC, DannyIsFunny commented
PaddlePaddle 编译体系基于CMake工具构建、建议将`build.sh`中的 gcc 的编译流程修改为`CMakeLists.txt`
eg.
``` shell
# CMakeLists.txt
add_library(paddle_inference SHARED com_baidu_paddle_inference_Predictor.cpp com_baidu_paddle_inference_Config.cpp com_baidu_paddle_inference_Tensor.cpp)
target_link_libraries(paddle_inference paddle_inference_c)
```

2021-11-23 02:51 UTC, DannyIsFunny commented
JAVA API 请 @winter-wang  review一下

2021-11-23 02:51 UTC, DannyIsFunny commented
当前产出的java api动态库仍然需要动态依赖 C API的动态库、能否直接产出独立的JAVA API动态库

2021-11-23 02:55 UTC, winter-wang reviewed
我在所有java涉及到的接口中没有看见对 PD_TensorDestroy函数和PD_PredictorDestroy函数的调用。请问在java接口使用过程中，底层的Tensor对象和Predictor对象如何回收尼？

2021-11-23 03:27 UTC, winter-wang requested changes

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  free(const_cast<char*>(params_file));
此处不能显式free。 params_file指向的内存是底层std::string对应的内存。

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  const char* params_file = PD_ConfigGetProgFile(
C接口函数调用错误。此处应该调用 PD_ConfigGetParamsFile函数。

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  free(const_cast<char*>(prog_file));
此处不能显式free.  prog_file对应的内存是底层std::string的内存。

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  free(const_cast<char*>(model_dir));
此处不能显式free. model_dir对应的内存是底层std::string的内存

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  free(const_cast<char*>(prog_file));
这种GetStringUTFChars得到的内存不能用free函数是释放吧？

2021-11-23 03:27 UTC, winter-wang commented on paddle/fluid/inference/javaapi/native/com_baidu_paddle_inference_Config.cpp
> +  free(const_cast<char*>(prog_file));
其它地方也类似。

2021-11-26 09:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=37162) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=37162) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: chenyanlann<br/>:x: zeuswuwuwuwu<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=37162) it.</sub>

2021-11-29 01:52 UTC, chenyanlann commented
@winter-wang 感谢，已修复

2021-11-29 01:53 UTC, chenyanlann commented
@DannyIsFunny 感谢，已删除中间产物，添加CMakeLists.txt

2021-12-10 03:13 UTC, winter-wang approved these changes, later dismissed
LGTM

2021-12-13 06:32 UTC, Shixiaowei02 commented
感谢您为飞桨贡献代码！

请参考已有的 [C++ 部分](https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B) 贡献文档和示例，并将相关代码移入 `experimental` 名称空间或目录中。

用户接口是框架最重要的代码，我们将发起评审并正式合入。谢谢！

2022-01-21 01:38 UTC, Superjomn approved these changes
LGTM

2022-01-21 03:03 UTC, winter-wang approved these changes
LGTM

2022-01-21 13:43 UTC, Shixiaowei02 approved these changes

2022-01-27 07:18 UTC, raindrops2sea approved these changes
LGTM

2022-02-10 08:55 UTC, merged