[Eager] publish python c api for eager
PaddlePaddle/Paddle pull request #37550
Opened 2021-11-25 08:07 UTC by wanghuancoder

### PR types

New features
### PR changes

Others 
### Describe

提交python c api相关代码

2021-11-30 12:14 UTC, wanghuancoder commented on paddle/fluid/pybind/eager_properties.cc
> +#pragma GCC diagnostic ignored "-Wwrite-strings"
这里是因为CI编译会报编译错误：
eager_properties.cc:143:50: error: ISO C++ forbids converting a string constant to 'char*' [-Werror=write-strings]

2021-11-30 12:56 UTC, JiabinYang commented on cmake/flags.cmake
> +    -Wno-error=missing-field-initializers
Why this, remove it if not necessary.

2021-11-30 12:56 UTC, JiabinYang commented on paddle/fluid/pybind/eager.cc
> +namespace pybind {
How about change these to a new namespace, since we will have serval api as same as imperative.

2021-11-30 12:56 UTC, JiabinYang commented on paddle/fluid/pybind/eager.h
> +namespace pybind {
same namespace issue.

2021-11-30 12:56 UTC, JiabinYang commented on paddle/fluid/pybind/eager_functions.cc
> +static inline PyObject* eager_api_numpy_to_tensor(
why inline here

2021-11-30 12:56 UTC, JiabinYang commented on paddle/fluid/pybind/eager_functions.cc
> +class EagerNumpyAllocation : public paddle::memory::allocation::Allocation {
Plz rearrange all helper class and function to above and list all api implements below

2021-11-30 12:56 UTC, JiabinYang commented on python/paddle/fluid/eager/eager_tensor_patch_methods.py
> +    # for method_name, method in (("__str__", __str__), ("__name__", "Tensor")):
remove comment

2021-11-30 12:56 UTC, JiabinYang commented on python/paddle/fluid/tests/unittests/test_egr_python_api.py
> +class EagerTensorPropertiesTestCase(unittest.TestCase):
add test for Grad

2021-12-01 01:23 UTC, wanghuancoder commented on cmake/flags.cmake
> +    -Wno-error=missing-field-initializers
done, thx!

2021-12-01 01:25 UTC, wanghuancoder commented on paddle/fluid/pybind/eager.cc
> +namespace pybind {
我觉得还是这个namespace更合理，所有向python暴露的代码都放在pybind文件夹下，所有代码均用pybind namespace。

2021-12-01 01:25 UTC, wanghuancoder commented on paddle/fluid/pybind/eager.h
> +namespace pybind {
同上

2021-12-01 01:25 UTC, wanghuancoder commented on paddle/fluid/pybind/eager_functions.cc
> +static inline PyObject* eager_api_numpy_to_tensor(
已删除

2021-12-01 01:27 UTC, wanghuancoder commented on python/paddle/fluid/eager/eager_tensor_patch_methods.py
> +    # for method_name, method in (("__str__", __str__), ("__name__", "Tensor")):
done, thx!

2021-12-01 03:27 UTC, wanghuancoder commented on paddle/fluid/pybind/eager_functions.cc
> +class EagerNumpyAllocation : public paddle::memory::allocation::Allocation {
done, thx!

2021-12-01 03:27 UTC, wanghuancoder commented on python/paddle/fluid/tests/unittests/test_egr_python_api.py
> +class EagerTensorPropertiesTestCase(unittest.TestCase):
done, thx!

2021-12-01 11:42 UTC, JiabinYang requested changes
LGTM

2021-12-01 11:43 UTC, JiabinYang approved these changes
LGTM

2021-12-02 01:52 UTC, TCChenlong approved these changes
LGTM

2021-12-02 01:56 UTC, XiaoguangHu01 approved these changes
LGTM

2021-12-02 02:10 UTC, lanxianghit approved these changes

2021-12-02 15:46 UTC, raindrops2sea commented
> ### PR types
> New features
> 
> ### PR changes
> Others
> 
> ### Describe
> 提交python c api相关代码

翔实地描述一下。

2021-12-03 02:13 UTC, raindrops2sea approved these changes

2021-12-03 02:14 UTC, merged