[ut] Update skip concept to ignore.
PaddlePaddle/Paddle pull request #37635
Opened 2021-11-27 06:35 UTC by jiweibo

### PR types

Others
### PR changes

Others
### Describe

skip概念易混淆，改为ignore

2021-11-28 01:54 UTC, jiangjiajun requested changes

2021-11-28 01:54 UTC, jiangjiajun commented on paddle/fluid/inference/analysis/helper.h
> +static void MakeDirIfNotExists(const std::string path) {
建议改为const std::string&，提升代码效率

2021-11-28 01:54 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_emb_eltwise_layernorm_fuse_pass.py
> +        yield config, ['tensorrt_engine'], (1e-5, 1e-5)
这里应该还得改回`fused_embedding_eltwise_layernorm`， 在auto_scan_test.py中，将create_trt_inference_config中，删除插入的默认pass即可。 
不然对于TRT Engine我们只能判断最终所有子图是否load到trt，而无法判断是否fuse成功了

2021-11-28 02:53 UTC, jiangjiajun requested changes

2021-11-28 02:53 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_emb_eltwise_layernorm_fuse_pass.py
> +                    'embedding_eltwise_layernorm_fuse_pass')
为什么需要在ignore_case中添加delete_pass呢

2021-11-28 04:58 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_emb_eltwise_layernorm_fuse_pass.py
> +                    'embedding_eltwise_layernorm_fuse_pass')
目前这个pass的问题还没修复，不加delte_pass的话，输出会有精度diff的提示，该部分内容通过grep SKIP信息可以查到，不需要保留错误。

2021-11-28 05:03 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_emb_eltwise_layernorm_fuse_pass.py
> +        yield config, ['tensorrt_engine'], (1e-5, 1e-5)
对于trt来说，如果不跑tensorrt_subgraph_fuse的话，最后是无法跑到trt上，所以对于trt的pass，感觉不应该删pass

2021-11-28 05:05 UTC, jiweibo commented on paddle/fluid/inference/analysis/helper.h
> +static void MakeDirIfNotExists(const std::string path) {
收到

2021-11-28 11:57 UTC, jiangjiajun approved these changes

2021-11-29 02:29 UTC, FrostML approved these changes

2021-11-29 02:30 UTC, merged