Add unittest for  flatten2_matmul squeeze2_matmul reshape2_matmul pass
PaddlePaddle/Paddle pull request #37644
Opened 2021-11-28 06:54 UTC by heliqi

Add unittest for flatten2_matmul_fuse_pass squeeze2_matmul_fuse_pass reshape2_matmul_fuse_pass
### PR types
bug fixes
### PR changes
Others

### Describe

1.   Add a test code for squeeze2_matmul_fuse_pass , fix "squeeze2" name error in OpCompat input.
2.  Add a test code for flatten2_matmul_fuse_pass ,     remove the false attribute "Y" on the op "flatten2" and fix "axis" attribute  error limits.
3.  Add a test code for reshape2_matmul_fuse_pass,  and fix squeeze2's name of OpCompat input

2021-12-09 02:39 UTC, jiangjiajun commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumEQ(1)
为什么需要限制为1，在PR描述中说明下原因

2021-12-09 06:26 UTC, heliqi commented on paddle/fluid/framework/ir/map_matmul_to_mul_pass.cc
> +      .IsNumEQ(1)
否则输出形状对不上， 已在PR中加上

2021-12-09 06:44 UTC, jiangjiajun approved these changes, later dismissed
LGTM

2021-12-15 07:24 UTC, XieYunshen submitted a review, later dismissed
LGTM for 
`  set_tests_properties(test_flatten2_matmul_fuse_pass PROPERTIES TIMEOUT 240)
  set_tests_properties(test_squeeze2_matmul_fuse_pass PROPERTIES TIMEOUT 240)
  set_tests_properties(test_reshape2_matmul_fuse_pass PROPERTIES TIMEOUT 240)`

2021-12-22 03:39 UTC, XieYunshen approved these changes, later dismissed

2021-12-22 13:10 UTC, jiangjiajun requested changes

2021-12-22 13:10 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_flatten2_matmul_fuse_pass.py
> +                # "Y": ["flatten2_y"]
删除

2021-12-22 13:10 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_flatten2_matmul_fuse_pass.py
> +                    # "flatten2_y": TensorConfig(shape=x_shape),
删除

2021-12-22 13:13 UTC, jiangjiajun approved these changes

2021-12-23 03:42 UTC, XieYunshen approved these changes

2021-12-23 05:03 UTC, jiangjiajun approved these changes

2021-12-23 05:03 UTC, merged