add transpose_flatten_concat_fuse_pass test case
PaddlePaddle/Paddle pull request #37675
Opened 2021-11-29 11:37 UTC by heliqi

### PR types
Bug fixes

### PR changes
Others

### Describe
Add unittest for transpose_flatten_concat_fuse_pass and fix some bugs:
1. Add the check: all input shapes should be the same
2. Add the check: All axis of transpose should be the same

2021-12-08 02:28 UTC, jiangjiajun requested changes

2021-12-08 02:28 UTC, jiangjiajun commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +            ->GetAttr("axis"));
trans_axis, flatten_axis应该相同； in_shape是否一定要相同，还是只要transpose+flattten后的shape相同即可

2021-12-08 06:21 UTC, heliqi commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +            ->GetAttr("axis"));
trans_axis 和 flatten_axis 固定成一样，transpose+flattten后的shape相同 不就等于in_shape相同？

2021-12-08 14:16 UTC, jiangjiajun requested changes

2021-12-08 14:16 UTC, jiangjiajun commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +            subgraph.at(pattern.GetPDNode("transpose" + std::to_string(i)))
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/ir/embedding_fc_lstm_fuse_pass.cc#L188 这里改成使用这个宏吧，看起来相比自己写在出错提示上更友好

2021-12-09 03:36 UTC, heliqi commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +            subgraph.at(pattern.GetPDNode("transpose" + std::to_string(i)))
那整个前面的代码 + pattern定义的地方都要改才行。这里边由于是for循环遍历获取node，所以之前都没用宏

2021-12-09 03:36 UTC, heliqi commented on paddle/fluid/framework/ir/transpose_flatten_concat_fuse_pass.cc
> +            ->GetAttr("axis"));
已经修复

2021-12-09 03:48 UTC, jiangjiajun submitted a review, later dismissed
LGTM

2021-12-09 10:06 UTC, jiangjiajun approved these changes

2021-12-09 10:06 UTC, merged