Add 3 conv eltwiseadd fuse pass tests
PaddlePaddle/Paddle pull request #37751
Opened 2021-12-01 06:58 UTC by zhenlin-work

### PR types
Bug fixes

### PR changes
Others

### Describe
新增conv_affine_channel_fuse_pass单测
新增conv_eltwiseadd_affine_channel_fuse_pass单测
新增conv_elementwise_add_fuse_pass单测

2021-12-02 05:33 UTC, XieYunshen submitted a review, later dismissed
LGTM

2021-12-02 11:47 UTC, XieYunshen approved these changes, later dismissed
LGTM for `set_tests_properties(test_conv_eltwiseadd_affine_channel_fuse_pass PROPERTIES TIMEOUT 100)`

2021-12-03 05:49 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +            return False
看起来该Pass不支持NHWC的输入，可以在Pass的compat检查中把这个加上，NHWC的时候不走Pass，保证正确性

2021-12-03 05:50 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +        ops_config = [
可以参考fc_fuse_pass的最新写法，直接写OpConfig

2021-12-03 05:51 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add_fuse_pass.py
> +            return False
同上

2021-12-03 05:52 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_elementwise_add_fuse_pass.py
> +        ops = self.generate_op_config(ops_config)
同上，不调用这个函数了，自己组OpConfig就行

2021-12-03 05:53 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +        groups = draw(st.sampled_from([1]))
该Pass中conv对groups的取值只支持1吗？

2021-12-03 05:54 UTC, jiangjiajun requested changes

2021-12-03 05:54 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +            return False
为什么需要将NHWC的program设为invalid？是否是当前fuse对于NHWC的program进行fuse时存在问题？

2021-12-03 05:54 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +            if program_config.ops[0].attrs['data_format'] == "NHWC":
需区分ignore和valid两个函数的作用

2021-12-03 05:54 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +        batch_size = draw(st.integers(min_value=1, max_value=4))
groups只测了为1的情况，建议增加其它groups的测试用例

2021-12-03 05:54 UTC, jiweibo commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_eltwiseadd_affine_channel_fuse_pass.py
> +        # mkldnn Output has diff with bias!!
这里是指mkldnn下输出有diff吗

2021-12-04 05:36 UTC, zhenlin-work commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_eltwiseadd_affine_channel_fuse_pass.py
> +        # mkldnn Output has diff with bias!!
mkldnn下conv2d带bias带情况会报出diff

2021-12-07 02:49 UTC, XieYunshen approved these changes
LGTM for `set_tests_properties(test_conv_eltwiseadd_affine_channel_fuse_pass PROPERTIES TIMEOUT 100)`

2021-12-07 06:23 UTC, jiangjiajun requested changes

2021-12-07 06:23 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +                # "conv2d_bias": TensorConfig(shape=bias_shape)
conv2d应该是包括bias的情况？考虑到前面的pass可能fuse出一个带bias的conv2d。

如若是此fuse有限制不能fuse带bias的conv2d，那可以直接移除掉注释代码

2021-12-07 06:23 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +        # mkldnn Output has diff with bias!!!
上面注释的bias就是因为mkldnn的问题么

如若是此问题，那无需注释，仍然加在ignore_pass_case中，当predictor_config为mkldnn config时跳过即可过单测

2021-12-07 06:23 UTC, jiangjiajun commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_eltwiseadd_affine_channel_fuse_pass.py
> +        # mkldnn Output has diff with bias!!!
同上

2021-12-07 07:03 UTC, zhenlin-work commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_affine_channel_fuse_pass.py
> +        # mkldnn Output has diff with bias!!!
是的，有diff

2022-11-21 03:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=37751) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=37751) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=37751) it.</sub>

2023-01-11 11:41 UTC, closed without merging