add matmul_scale_fuse_pass
PaddlePaddle/Paddle pull request #37962
Opened 2021-12-08 08:48 UTC by heliqi

### PR types

Performance optimization

### PR changes

Others 

### Describe

新增matmul_scale_fuse_pass和matmul_v2_scale_fuse_pass用于融合matmul 和 scale， 能提升rec_vit模型在mkldnn下5%的性能

2021-12-08 09:37 UTC, jiangjiajun requested changes

2021-12-08 09:37 UTC, jiangjiajun commented on paddle/fluid/framework/ir/matmul_scale_fuse_pass.cc
> +    if (std::abs(bias - 0.0) > 1e-5) return;
这里是否可以简写成 std::abs(bias) > 1e-05

2021-12-08 09:37 UTC, jiangjiajun commented on paddle/fluid/framework/ir/matmul_scale_fuse_pass.cc
> +      auto* sacle_tensor = scale_var->GetMutable<LoDTensor>();
sacle_tensor -> scale_tensor

2021-12-08 11:21 UTC, heliqi commented on paddle/fluid/framework/ir/matmul_scale_fuse_pass.cc
> +      auto* sacle_tensor = scale_var->GetMutable<LoDTensor>();
已改

2021-12-08 11:22 UTC, heliqi commented on paddle/fluid/framework/ir/matmul_scale_fuse_pass.cc
> +    if (std::abs(bias - 0.0) > 1e-5) return;
已改

2021-12-09 05:12 UTC, jiangjiajun commented on paddle/fluid/inference/api/paddle_pass_builder.cc
> +             "fc_mkldnn_pass", "fc_act_mkldnn_fuse_pass",
这里不是默认关闭么

2021-12-09 06:18 UTC, heliqi commented on paddle/fluid/inference/api/paddle_pass_builder.cc
> +             "fc_mkldnn_pass", "fc_act_mkldnn_fuse_pass",
误提交了， 已关闭

2021-12-09 07:26 UTC, jiangjiajun approved these changes, later dismissed
LGTM

2021-12-17 12:30 UTC, wanghuancoder approved these changes

2021-12-17 12:53 UTC, chalsliu approved these changes

2021-12-18 09:34 UTC, jiangjiajun approved these changes

2021-12-20 06:27 UTC, baoachun commented
后续可能需要考虑下是否对量化场景有影响

2021-12-20 06:27 UTC, baoachun commented
LGTM

2021-12-20 07:38 UTC, merged