[Unify Tensors PR #3] Replaced pten::Allocation with shared_ptr<memory::Allocation> for Storage
PaddlePaddle/Paddle pull request #38301
Opened 2021-12-21 02:23 UTC by jim19930609

### PR types
New features

### PR changes
Others
### Describe
Replaced pten::Allocation with shared_ptr<memory::Allocation> for Storage

2021-12-23 06:02 UTC, chenwhql submitted a review, later dismissed
LGTM

2021-12-23 06:03 UTC, Shixiaowei02 commented on paddle/pten/core/allocator.h
不建议改这个文件，Tensor 可将接收的 Allocator 从 `pten::Allocator` 改为 `memory::Allocator`。

2021-12-23 06:04 UTC, Shixiaowei02 requested changes
除了 `paddle/pten/core/allocator.h`，其它我没问题

2021-12-24 03:03 UTC, jim19930609 commented on paddle/pten/core/allocator.h
Per offline discussion, replaced AllocateShared() interface with a virtual place() method.

2021-12-24 03:50 UTC, Shixiaowei02 commented on paddle/pten/core/allocator.h
> +#include "paddle/fluid/memory/memory.h"
这个头文件交易删除下

2021-12-24 04:05 UTC, Shixiaowei02 approved these changes

2021-12-24 05:37 UTC, chenwhql approved these changes

2021-12-24 09:05 UTC, zhiqiu approved these changes
LGTM

2021-12-24 09:22 UTC, merged