Add trace data internal presentation format
PaddlePaddle/Paddle pull request #38645
Opened 2021-12-31 09:04 UTC by rainyfly

### PR types

New features
### PR changes

Others
### Describe

该PR当前只作为草稿同步开发使用。

2022-01-04 05:43 UTC, liutiexing requested changes

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +    std::vector<CudaRuntimeRecordNode*> GetRuntimeRecordNode();
GetRuntimeRecordNodes?复数

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +    CudaRuntimeRecordNode(std::string name, TracerEventType type,
TracerEventType type只能是CudaRuntime，构造函数不需要传参数了吧？

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +    HostRecordNode(std::string name, TracerEventType type,
TracerEventType type只能是UserDefine，构造函数不需要传参数了吧？

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +    HostRecordNode(std::string name, TracerEventType type,
std::string name一般是const std::string &name，引用传递

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +                     KernelDetails& kernel_info):
写错了？应该是memcpy_info？

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +      static_assert(type_ == TracerEventType::Memset,
static_assert是编译时判断？这里应该用assert或者PADDLE_ENFORCE_EQ

2022-01-04 05:43 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +    void BuildTree();
这个咋用？没参数也没有返回值

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +    std::vector<CudaRuntimeRecordNode*> GetRuntimeRecordNode();
已改

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +    CudaRuntimeRecordNode(std::string name, TracerEventType type,
已改

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +    HostRecordNode(std::string name, TracerEventType type,
这个需要

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +    HostRecordNode(std::string name, TracerEventType type,
已改

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +                     KernelDetails& kernel_info):
已改

2022-01-04 09:55 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +      static_assert(type_ == TracerEventType::Memset,
已改

2022-01-04 09:56 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +    void BuildTree();
已根据讨论修改

2022-01-07 08:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38645) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38645) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: liutiexing<br/>:white_check_mark: rainyfly<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=38645) it.</sub>

2022-01-10 12:55 UTC, closed without merging