[IPU] update ipu releated passes
PaddlePaddle/Paddle pull request #38846
Opened 2022-01-10 12:15 UTC by gglin001

### PR types

Others
### PR changes

Others
### Describe

ipu releated updates

2022-01-11 09:21 UTC, qili93 commented on paddle/fluid/framework/ir/ipu/ipu_pass_base.cc
> +// pass
ipu_pass_base.cc / ipu_pass_base.h都是空文件，建议删掉

2022-01-11 09:21 UTC, qili93 commented on paddle/fluid/framework/ir/ipu/transfer_cast_op_pass.cc
> +// Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
时间改为2022，下面其他新增文件页检查一下时间

2022-01-12 09:53 UTC, gglin001 commented on paddle/fluid/framework/ir/ipu/ipu_pass_base.cc
> +// pass
fixed

2022-01-12 09:53 UTC, gglin001 commented on paddle/fluid/framework/ir/ipu/transfer_cast_op_pass.cc
> +// Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
fixed

2022-01-13 05:48 UTC, qili93 approved these changes
LGTM

2022-01-13 05:50 UTC, qili93 requested changes

2022-01-13 05:50 UTC, qili93 commented on paddle/fluid/framework/ir/ipu/optimizer_extract_pass.cc
> +    PADDLE_THROW(platform::errors::NotFound("No optimizer found"));
根据CI提示，这里的error message不符合要求，参考以下文档进行修改

 https://github.com/PaddlePaddle/Paddle/wiki/Paddle-Error-Message-Writing-Specification

2022-01-17 04:30 UTC, qili93 approved these changes
LGTM

2022-01-17 04:40 UTC, merged