Add trace data internal presentation
PaddlePaddle/Paddle pull request #38851
Opened 2022-01-10 12:35 UTC by rainyfly

### PR types
New features 

### PR changes
Others

### Describe
Profiler工具内部数据表示

2022-01-10 12:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38851) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38851) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: liutiexing<br/>:white_check_mark: rainyfly<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=38851) it.</sub>

2022-01-10 13:54 UTC, liutiexing requested changes

2022-01-10 13:54 UTC, liutiexing commented on paddle/fluid/platform/profiler/trace_event_collector.h
> +  void AddDeviceRecord(DeviceEvent&& event) { device_events_.push_back(event); }
AddDeviceEvent?

2022-01-10 13:54 UTC, liutiexing commented on paddle/fluid/platform/profiler/trace_event_collector.h
> +  void AddHostRecord(HostEvent&& event) { host_events_.push_back(event); }
AddHostEvent?

2022-01-10 13:54 UTC, liutiexing commented on paddle/fluid/platform/profiler/trace_event_collector.h
> -struct HostRecord {
#inculde "event_record.h"

2022-01-10 13:54 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_record.h
> +  HostEvent(const std::string& name, TracerEventType type, uint64_t start_ns,
增加HostEvent() = defalut;
否则定义HostEvent有参数构造会导致默认构造函数消失。

2022-01-10 13:56 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_record.h
> +  HostEvent(const std::string& name, TracerEventType type, uint64_t start_ns,
对于字段特别多的struct，最好是Struct.field = field来set;因为通过有参数构造函数会导致很容易对不齐。

2022-01-11 02:28 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_record.h
> +  HostEvent(const std::string& name, TracerEventType type, uint64_t start_ns,
已修改

2022-01-11 02:28 UTC, rainyfly commented on paddle/fluid/platform/profiler/trace_event_collector.h
> -struct HostRecord {
已修改

2022-01-11 02:29 UTC, rainyfly commented on paddle/fluid/platform/profiler/trace_event_collector.h
> +  void AddHostRecord(HostEvent&& event) { host_events_.push_back(event); }
已修改

2022-01-11 02:29 UTC, rainyfly commented on paddle/fluid/platform/profiler/trace_event_collector.h
> +  void AddDeviceRecord(DeviceEvent&& event) { device_events_.push_back(event); }
已修改

2022-01-14 08:34 UTC, closed without merging