add trace event data structure
PaddlePaddle/Paddle pull request #38952
Opened 2022-01-14 08:33 UTC by rainyfly

### PR types

New Features
### PR changes

Profiler tool
### Describe

用于表示Profiler性能数据的数据结构定义。
1. event_record.h
   性能数据的Event定义
2. event_node.h
  采用Node对Event进行封装，根据时间关系组织成树的结构。
3. event_python.h
  用于导出结果到暴露到Python层的数据结构。

2022-01-14 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38952) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=38952) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=38952) it.</sub>

2022-01-14 12:19 UTC, liutiexing requested changes

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_record.h
> +namespace platform {
文件名改成trace_event.h把，因为里面的类都叫做XXXTraceEvent，表意更好

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +  void LogMe(BaseLogger* logger) { logger->LogDeviceTraceEventNode(*this); }
这个删掉？等于啥也没干，还增加了TraceEventNode类型对logger的依赖。

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +  std::vector<HostTraceEventNode*> host_event_nodes_;
这三个nodes_只在buildtree中使用，没必要做成数据成员，临时构建传参给buildtree就可以。
只有所有node都在vector分配然后TraceEventNode自身析构不负责delete时，弄三个node数据管理数据才有意义。
现在既然new node，走传统路线，就不需要维护三个nodes 的class data members

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/output_logger.h
> +class BaseLogger {
还有其他Logger吗？有得话这个得拆出来

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_python.cc
> +HostPythonNode* ProfilerResult::_copyTree(HostTraceEventNode* node) {
c++不这么命名，不要下划线开头，private函数和public命名规则一样，这是private函数放private:下面

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.cc
> +      HostTraceEvent(std::string("root node"), TracerEventType::Operator,
UserDefineType？

2022-01-14 12:19 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.cc
> +      HostTraceEvent(std::string("root node"), TracerEventType::Operator,
root node做成const常量，后面可以用于判断一个node是不是root。

2022-01-19 03:04 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_record.h
> +namespace platform {
已改

2022-01-19 03:08 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +  void LogMe(BaseLogger* logger) { logger->LogDeviceTraceEventNode(*this); }
感觉该接口设计对于记录不同的Node比较方便，第三方调用的时候不用知道Node和Logger之间的关系，只需要Node和Logger之间互知。

2022-01-19 03:08 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +  std::vector<HostTraceEventNode*> host_event_nodes_;
已改。

2022-01-19 03:08 UTC, rainyfly commented on paddle/fluid/platform/profiler/output_logger.h
> +class BaseLogger {
已改

2022-01-19 03:08 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_python.cc
> +HostPythonNode* ProfilerResult::_copyTree(HostTraceEventNode* node) {
已改

2022-01-19 03:08 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.cc
> +      HostTraceEvent(std::string("root node"), TracerEventType::Operator,
已改

2022-01-24 03:51 UTC, closed without merging