Support allocate_from in Tensor and allocate_data in Context
PaddlePaddle/Paddle pull request #39022
Opened 2022-01-18 09:09 UTC by Aurelius84

### PR types

Others
### PR changes

Others
### Describe

Support allocate_from in Tensor and allocate_data in Context

2022-01-20 03:13 UTC, chenwhql commented on paddle/fluid/platform/device_context.h
> +  void* allocate_data(pten::TensorBase* tensor) const {
非模板的方法，按现状来看，可能需要添加一个dtype的参数

2022-01-20 03:13 UTC, chenwhql commented on paddle/pten/core/dense_tensor.cc
> +void* DenseTensor::allocate_from(Allocator* allocator, size_t requested_size) {
或许需要添加一个dtype参数

2022-01-20 05:39 UTC, Shixiaowei02 commented on paddle/pten/core/dense_tensor.cc
> +    storage_.reset(static_cast<Storage*>(new TensorStorage(allocator, bytes)));
这里建议绕开 Storage/TensorStorage，直接用 `ResetHolder` 的类似接口，对后续的去除影响小一些

2022-01-20 05:44 UTC, jiweibo commented on paddle/fluid/platform/device_context.h
> +  void set_device_allocator(
接口名都要用小写吗？
SetDeviceAllocator or set_device_allocator

2022-01-20 05:45 UTC, jiweibo commented on paddle/fluid/platform/device_context.h
> +  void* allocate_data(pten::TensorBase* tensor,
ctx->allocate_data(...)

or

ctx->Alloc(...)

2022-01-20 05:45 UTC, jiweibo commented on paddle/fluid/platform/device_context.h
> +  void* allocate_host_data(pten::TensorBase* tensor,
ctx->allocate_host_data(...)

or

ctx->HostAlloc(...)

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/fluid/platform/device_context.h
> +  void* allocate_data(pten::TensorBase* tensor) const {
Thanks，Done

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/pten/core/dense_tensor.cc
> +void* DenseTensor::allocate_from(Allocator* allocator, size_t requested_size) {
Thanks，Done

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/pten/core/dense_tensor.cc
> +    storage_.reset(static_cast<Storage*>(new TensorStorage(allocator, bytes)));
Thanks，Done

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/fluid/platform/device_context.h
> +  void set_device_allocator(
Thanks，Done

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/fluid/platform/device_context.h
> +  void* allocate_data(pten::TensorBase* tensor,
Thanks，Done

2022-01-20 12:24 UTC, Aurelius84 commented on paddle/fluid/platform/device_context.h
> +  void* allocate_host_data(pten::TensorBase* tensor,
Thanks，Done

2022-01-26 06:43 UTC, Shixiaowei02 commented on paddle/pten/core/tensor_base.h
> +  /// \brief Allocate memory with requested size from allocator.
此接口不放 DataType 参数

2022-01-26 06:44 UTC, Shixiaowei02 commented on paddle/pten/core/dense_tensor.h
> +                     DataType dtype,
此接口不放 `DataType` 参数

2022-01-26 06:49 UTC, jiweibo commented on paddle/pten/tests/kernels/test_cast_dev_api.cc
> +  dev_ctx.SetDeviceAllocator(
单测中是否可以fake一个Allocator来使用，不需include allocator_facade.h 头文件，下同。

2022-01-26 06:51 UTC, Aurelius84 commented on paddle/pten/tests/kernels/test_cast_dev_api.cc
> +  dev_ctx.SetDeviceAllocator(
这个只是单测文件，不影响。

2022-01-26 06:54 UTC, Aurelius84 commented on paddle/pten/core/dense_tensor.h
> +                     DataType dtype,
那需要接口调用者就需要确保首先设置好 dtype。从目前修改的Pten目录的Kernel来看，一些调用mutable_data的地方有类似场景。

2022-01-26 06:55 UTC, jiweibo commented on paddle/pten/core/device_context.h
> +class DeviceContextImpl {
Impl的定义及实现均放到.cc文件中，对用户不可见

2022-01-26 06:56 UTC, Aurelius84 commented on paddle/pten/core/tensor_base.h
> +  /// \brief Allocate memory with requested size from allocator.
可以，我在下个小PR统一调整过来。

2022-01-26 06:56 UTC, jiweibo commented on paddle/pten/core/device_context.h
> +  void SetZeroAllocator(const Allocator* allocator);
请问为什么需要保留ZeroAllocator呢？

2022-01-26 06:57 UTC, Aurelius84 commented on paddle/pten/core/device_context.h
> +class DeviceContextImpl {
DeviceContextImpl 有模板成员函数。

2022-01-26 06:57 UTC, Aurelius84 commented on paddle/pten/core/device_context.h
> +  void SetZeroAllocator(const Allocator* allocator);
因为有些Op如 bicount_op ，出现input和output 的tensor是 0 memory_size 的场景。

2022-01-26 07:07 UTC, Shixiaowei02 commented on paddle/pten/core/dense_tensor.h
> +                     DataType dtype,
好的，DenseTensor 这个接口需要删除 DataType

2022-01-26 08:00 UTC, Shixiaowei02 commented on paddle/pten/core/tensor_base.h
> +  /// \brief Allocate memory with requested size from allocator.
`TensorBase` 不加 `AllocateFrom` 接口，或者加一个不带 `DataType` 的接口。除了这个地方，其它地方都可以走中间态。

2022-01-26 08:02 UTC, Shixiaowei02 requested changes
`TensorBase` 本身的 `AllocateFrom` 不带 `DataType` 参数，其它都可以走中间态。

2022-01-26 08:23 UTC, Superjomn requested changes
请保留 Pimpl，另外避免修改 TensorBase 基类接口。
有实现难度或者有变化可以提前约相关作者讨论，避免直接开发完反向驱动合入。

谢谢

2022-01-26 08:23 UTC, Superjomn commented on paddle/pten/core/device_context.h
> +class DeviceContextImpl {
为啥要删 PImpl ? 

原有的这个困难可以提前跟卫波讨论解决哈

2022-01-26 10:01 UTC, Aurelius84 commented
> 请保留 Pimpl，另外避免修改 TensorBase 基类接口。 有实现难度或者有变化可以提前约相关作者讨论，避免直接开发完反向驱动合入。
> 
> 谢谢

已把 Pimpl 迁移回来~~

2022-01-26 10:49 UTC, Aurelius84 commented on paddle/pten/core/device_context.h
> +class DeviceContextImpl {
已加回 Pimpl~~

2022-01-26 11:28 UTC, jiweibo commented on paddle/pten/core/device_context.h
> +  virtual void SetZeroAllocator(const Allocator*);
ZeroAllocator的问题背景，如果是kernel的问题，bug修复后，pten中未来能否将该接口去除

2022-01-26 11:33 UTC, Aurelius84 commented on paddle/pten/core/device_context.h
> +  virtual void SetZeroAllocator(const Allocator*);
这个不是Kernel的问题，是因为底层Alloctor对于memory_size为0 和非0 是分开处理的。

2022-01-26 11:53 UTC, Shixiaowei02 commented on paddle/pten/core/device_context.cc
> +        tensor->numel() == 0 ? zero_allocator_ : device_allocator_;
根据会上的讨论，kernel 中 `Alloc` 能满足各种情况，请问这里添加 `HostAlloc`，并且调用 `device_allocator` 的作用是什么

2022-01-26 11:59 UTC, chenwhql commented on paddle/pten/core/device_context.cc
> +        tensor->numel() == 0 ? zero_allocator_ : device_allocator_;
会上没有说alloc能满足各种情况，这个应该是客观需要的，比如在gpu kernel里面，可能需要申请一个cpu 的tensor，这个之前在DeviceContext的决策表记录里也是这样的
![image](https://user-images.githubusercontent.com/22561442/151159296-790beac3-d199-4a3e-be37-3415c13e6e87.png)

2022-01-26 12:02 UTC, Aurelius84 commented on paddle/pten/core/device_context.cc
> +        tensor->numel() == 0 ? zero_allocator_ : device_allocator_;
这里应该是host_allocator_，已fix

2022-01-26 12:24 UTC, jiweibo commented on paddle/pten/core/device_context.h
> +  void* Alloc(TensorBase*,
DeviceAlloc?

2022-01-26 13:50 UTC, Shixiaowei02 approved these changes

2022-01-27 01:14 UTC, jiweibo approved these changes
LGTM  

Todo(wilber)后续把Alloc函数签名改为DeviceAlloc

2022-01-27 02:03 UTC, Superjomn approved these changes
LGTM

2022-01-27 02:30 UTC, phlrain approved these changes

2022-01-27 02:46 UTC, chenwhql approved these changes

2022-01-27 03:36 UTC, XiaoguangHu01 approved these changes
LGTM

2022-01-27 08:22 UTC, ZzSean commented
LGTM for ci op benchmark

2022-01-27 08:22 UTC, ZzSean approved these changes
LGTM for ci op benchmark

2022-01-27 08:42 UTC, merged