[pten] add full xpu kernel
PaddlePaddle/Paddle pull request #39172
Opened 2022-01-24 08:46 UTC by MingMingShangTian

### PR types

Others
### PR changes

Others
### Describe

Add full kernel of XPU place

2022-01-25 03:53 UTC, YuanRisheng approved these changes, later dismissed

2022-01-25 03:53 UTC, YuanRisheng commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  paddle::memory::Copy(place,
建议使用fluid下的copy

2022-01-25 05:03 UTC, chenwhql requested changes
1. 这里full的xpu和其他设备是公用的，full_like不是，是不是把full和full_like的kernel实现拆开比较好，full_kernel直接在根目录下了
2. 没有对原xpu的实现进行替换，是不是又是两份代码？

2022-01-25 05:03 UTC, chenwhql commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  out->ResizeAndAllocate(pten::framework::make_ddim(shape.GetData()));
这个接口好像不能再使用了

2022-01-25 05:03 UTC, chenwhql commented on paddle/pten/kernels/xpu/full_kernel.cc
> +void FullLikeKernel(const Context& dev_ctx,
为什么原XPU没有改动

2022-01-25 05:03 UTC, chenwhql commented on paddle/pten/kernels/xpu/full_kernel.cc
> +PT_REGISTER_KERNEL(full,
为什么只注册了full

2022-01-25 06:28 UTC, zhiqiu commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  FullValueXPU<T>(dev_ctx, out, value);
what about fill nan and inf?

2022-01-25 06:59 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  paddle::memory::Copy(place,
这里的是用的底层的copy，pten 下copy 不能用

2022-01-25 06:59 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  out->ResizeAndAllocate(pten::framework::make_ddim(shape.GetData()));
现在还可以用

2022-01-25 06:59 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +void FullLikeKernel(const Context& dev_ctx,
原XPU 已经修改了

2022-01-25 07:00 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +PT_REGISTER_KERNEL(full,
full_like的已经添加

2022-01-25 07:06 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  FullValueXPU<T>(dev_ctx, out, value);
added nan and inf check.

2022-01-26 08:02 UTC, zyfncg commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  PD_VISIT_ALL_TYPES(tensor->dtype(), "FullValueXPU", ([&] {
这里的`tensor->dtype()`和`T`会不一样吗？

2022-01-26 09:29 UTC, MingMingShangTian commented on paddle/pten/kernels/xpu/full_kernel.cc
> +  PD_VISIT_ALL_TYPES(tensor->dtype(), "FullValueXPU", ([&] {
FullValueXPU 函数定义上是支持不一样的类型的

2022-01-27 06:32 UTC, YuanRisheng approved these changes

2022-01-27 06:40 UTC, chenwhql approved these changes

2022-01-27 06:44 UTC, merged