Add profiler node tree implementation
PaddlePaddle/Paddle pull request #39316
Opened 2022-01-28 10:18 UTC by rainyfly

### PR types

New features
### PR changes

Others
### Describe

1. 性能数据数据结构化组织成树
2. 导出为Chrome Tracing的格式

2022-01-28 12:32 UTC, liutiexing requested changes

2022-01-28 12:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/profiler.h
>  #include "paddle/fluid/platform/profiler/trace_event_collector.h"
那这个依赖就挪到cc吧

2022-01-28 12:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/test_event_node.cc
> +  host_events.push_back(HostTraceEvent(
op间启止时间不能重叠

2022-01-28 12:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/output_logger.h
> +/* Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
我研究了一下visitor模式
我的理解是：BaseLogger访问各种node的method应该都叫LogNode，但是接受不同的类型（C++支持重载）。
现在这样的问题是：各种node里调用了传入的logger的特定名字的方法了。
void LogMe(BaseLogger* logger) { logger->LogDeviceTraceEventNode(*this); }
这样是不是好点
void LogMe(BaseLogger* logger) { logger->LogNode(*this); }

2022-02-07 09:23 UTC, liutiexing requested changes

2022-02-07 09:23 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.h
> +/* Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
这里之前没注意到，method按照命名规则是驼峰，不知道presubmit为啥没有拦截。
start_ns()应该是StartNs()

2022-02-07 10:21 UTC, liutiexing requested changes

2022-02-07 10:21 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.cc
> +  for (auto it = thread2host_event_nodes.begin();
这里有问题，如果没有HostEvent而只有RuntimeEvent，这里就不对了，RuntimeEvent应该挂到RootNode

2022-02-08 09:00 UTC, liutiexing requested changes

2022-02-08 09:00 UTC, liutiexing commented on paddle/fluid/platform/profiler/profiler.h
> +  NodeTrees* Stop();
返回NodeTrees对象（NodeTree支持拷贝构造），或者返回unique_ptr<NodeTree>。
函数内new一个对象返回指针，使用者不看代码不知道对象的ownership是自己还是谁

2022-02-09 02:20 UTC, rainyfly commented on paddle/fluid/platform/profiler/test_event_node.cc
> +  host_events.push_back(HostTraceEvent(
这个只是为了测试，测试包含关系能work。

2022-02-09 02:29 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +/* Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
因为是属性的getter，我就用了和属性名一样的名字做方法名

2022-02-09 04:39 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.cc
> +  for (auto it = thread2host_event_nodes.begin();
已修改

2022-02-09 05:17 UTC, rainyfly commented on paddle/fluid/platform/profiler/profiler.h
> +  NodeTrees* Stop();
已修改

2022-02-09 05:18 UTC, rainyfly commented on paddle/fluid/platform/profiler/profiler.h
>  #include "paddle/fluid/platform/profiler/trace_event_collector.h"
已修改

2022-02-09 07:38 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_node.h
> +/* Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
已修改

2022-02-09 09:00 UTC, liutiexing requested changes

2022-02-09 09:00 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_node.cc
> +                     LLONG_MAX, 0, 0));
ULLONG_MAX

2022-02-09 10:48 UTC, liutiexing submitted a review, later dismissed

2022-02-10 06:12 UTC, liutiexing approved these changes

2022-02-10 06:27 UTC, liutiexing approved these changes

2022-02-11 02:30 UTC, wanghuancoder approved these changes

2022-02-11 02:31 UTC, merged