Add profiler tree serialization
PaddlePaddle/Paddle pull request #39463
Opened 2022-02-10 12:49 UTC by rainyfly

### PR types

New features
### PR changes

Others
### Describe

1. 增加profiler数据构成的内存树的protobuf格式的导出以及导入。

2022-02-11 05:32 UTC, liutiexing requested changes

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +std::string string_format(const std::string& format, Args... args) {
如果这个函数多次使用，就抽离出来吧。

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +static std::string GetStringFormatLocalTime() {
同样的，公用的抽离出来

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +  if (!output_file_stream_) {
如果ostream失败，就退出吧？dump不了的话转成proto也没用啊

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +    VLOG(2) << "Unable to open file for writing profiling data." << std::endl;
LOG(WARNING)

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +  } else {
LOG(INFO)

2022-02-11 05:32 UTC, liutiexing commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +    int64_t index = 0;
bfs返回的vector，天然有idx，直接用就行吧，这里重新遍历效果上和用vector idx一样吧？

2022-02-14 02:17 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +    VLOG(2) << "Unable to open file for writing profiling data." << std::endl;
已修改

2022-02-14 02:17 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +  } else {
已修改

2022-02-14 02:18 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +  if (!output_file_stream_) {
和chrometracing一样，判断有没有ostream, 没有就return。

2022-02-14 02:18 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +static std::string GetStringFormatLocalTime() {
已抽离

2022-02-14 02:18 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +std::string string_format(const std::string& format, Args... args) {
已抽离

2022-02-14 02:18 UTC, rainyfly commented on paddle/fluid/platform/profiler/dump/serialization_logger.cc
> +    int64_t index = 0;
一样的

2022-02-18 09:32 UTC, closed without merging