new way of unit test , *test=kunlun
PaddlePaddle/Paddle pull request #39650
Opened 2022-02-16 15:16 UTC by helen88

### PR types

Others
### PR changes

Others
### Describe

reconstruc unit test of ops , including adam, concat, fill_constant

2022-02-17 01:58 UTC, zhangting2020 approved these changes, later dismissed
LGTM for skip_check_grad_ci

2022-02-17 02:18 UTC, ykkk2333 approved these changes, later dismissed
LGTM

2022-02-17 02:25 UTC, XiaociZhang requested changes

2022-02-17 02:25 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +        def set_attrs(self):
hyper param和attrs分开吧

2022-02-17 02:37 UTC, helen88 commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +        def set_attrs(self):
这里没有把set_data里的数据分的那么细，为了方便扩展后续case，直接set这些data

2022-02-17 02:55 UTC, XiaociZhang requested changes

2022-02-17 02:55 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +    class TestAdamOp2(XPUOpTest):
继承写错了，下同

2022-02-17 02:55 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +            self.attrs = {'epsilon': epsilon, 'beta1': beta1, 'beta2': beta2}
beta1,beta2加self，下同

2022-02-17 02:56 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +        def set_attrs(self):
还是建议改掉哈，因为下面同样的set_attrs代码重复了很多次

2022-02-17 07:32 UTC, helen88 commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +        def set_attrs(self):
fixed

2022-02-17 07:32 UTC, helen88 commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +    class TestAdamOp2(XPUOpTest):
fixed

2022-02-17 07:32 UTC, helen88 commented on python/paddle/fluid/tests/unittests/xpu/test_adam_op_xpu.py
> +            self.attrs = {'epsilon': epsilon, 'beta1': beta1, 'beta2': beta2}
fixed

2022-02-17 10:37 UTC, helen88 commented
> Details

fixed

2022-02-18 02:12 UTC, ykkk2333 approved these changes
LGTM

2022-02-18 02:39 UTC, QingshuChen approved these changes

2022-02-18 02:41 UTC, zhangting2020 approved these changes

2022-02-18 03:20 UTC, XiaociZhang approved these changes
LGTM

2022-02-18 03:31 UTC, QingshuChen approved these changes

2022-02-18 03:31 UTC, merged