update unittests for activation ops on xpu. test=kunlun
PaddlePaddle/Paddle pull request #39677
Opened 2022-02-17 10:16 UTC by houj04

### PR types
Others

### PR changes
Others

### Describe
按照新的单测标准，重写一系列激活函数的xpu单测。

2022-02-18 03:32 UTC, XiaociZhang requested changes

2022-02-18 03:32 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
> +        self.check_output_with_place(self.place)
这里为什么移除了compiled_with_xpu的检查，以及atol参数为什么要去掉？

2022-02-18 03:32 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
> +            x = np.random.uniform(0.1, 1, [11, 17]).astype(self.dtype)
取值范围为啥从0.1开始？

2022-02-18 03:32 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
> +            x = np.random.uniform(0.1, 1, [11, 17]).astype(self.dtype)
包括其它激活函数，除了log和sqrt，其它的似乎没理由从0.1开始取值。之前这么写是有啥讲究吗？

2022-02-18 05:06 UTC, houj04 commented on python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
> +        self.check_output_with_place(self.place)
1、问了一下知毅，说“现在非xpu的提交也不会跑到xpu 算子的单测”。
2、python/paddle/fluid/tests/unittests/op_test_xpu.py里面的check_output_with_place默认就是0.001，所以不需要特地指定。并且根据paddle的规范，也不建议在单独的单测里面修改阈值。
https://github.com/paddlepaddle/paddle/wiki/op-test-accuracy-requirements

2022-02-18 05:18 UTC, houj04 commented on python/paddle/fluid/tests/unittests/xpu/test_activation_op_xpu.py
> +            x = np.random.uniform(0.1, 1, [11, 17]).astype(self.dtype)
看了一下gpu上的单测，exp、square、tanh这三个，范围也是0.1开始的，原因未知。
我适当放大一下。

2022-02-21 02:13 UTC, XiaociZhang approved these changes
LGTM

2022-02-21 02:36 UTC, helen88 commented
LGTM

2022-02-21 03:03 UTC, helen88 approved these changes

2022-02-21 04:46 UTC, QingshuChen approved these changes

2022-02-21 04:46 UTC, merged