update unittest for reduce_prod op on xpu. test=kunlun
PaddlePaddle/Paddle pull request #39671
Opened 2022-02-17 08:36 UTC by houj04

### PR types
Others

### PR changes
Others

### Describe
按照新的单测标准，重写reduce_prod的xpu单测。

2022-02-18 03:22 UTC, XiaociZhang requested changes

2022-02-18 03:22 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_reduce_prod_op_xpu.py
> +            self.inputs = {'X': np.random.random(self.shape).astype("float32")}
没有用self.dtype?

2022-02-18 03:37 UTC, houj04 commented on python/paddle/fluid/tests/unittests/xpu/test_reduce_prod_op_xpu.py
> +            self.inputs = {'X': np.random.random(self.shape).astype("float32")}
多谢指出，已修复。

2022-02-21 02:28 UTC, helen88 commented
LGTM

2022-02-21 03:02 UTC, helen88 approved these changes

2022-02-21 04:24 UTC, XiaociZhang approved these changes
LGTM

2022-02-21 04:29 UTC, QingshuChen approved these changes

2022-02-21 04:29 UTC, merged