fix RecordEvent interface
PaddlePaddle/Paddle pull request #39675
Opened 2022-02-17 09:22 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

往RecordEvent中多加入一个参数，服务于新的Profiler使用。

2022-02-17 09:46 UTC, liutiexing requested changes

2022-02-17 09:46 UTC, liutiexing commented on paddle/fluid/platform/profiler.cc
> +                         uint32_t level, const EventRole role) {
default level低一点

2022-02-17 10:20 UTC, rainyfly commented on paddle/fluid/platform/profiler.cc
> +                         uint32_t level, const EventRole role) {
已改

2022-02-17 10:21 UTC, liutiexing approved these changes

2022-02-17 11:25 UTC, liutiexing requested changes

2022-02-17 11:25 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_tracing.h
> +      uint32_t level = 4, const EventRole role = EventRole::kOrdinary);
把默认level 4定义一个const常量，这样用户需要设置后面的默认参数而不想改level时可以用这个

2022-02-17 11:26 UTC, liutiexing requested changes

2022-02-17 11:26 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_tracing.h
> +  explicit RecordEvent(
修改接口会导致部分使用EventRole的case无法编译，需要修改这些

2022-02-17 13:45 UTC, rainyfly commented on paddle/fluid/platform/profiler/event_tracing.h
> +      uint32_t level = 4, const EventRole role = EventRole::kOrdinary);
已改

2022-02-18 03:28 UTC, liutiexing requested changes

2022-02-18 03:28 UTC, liutiexing commented on paddle/fluid/framework/operator.cc
> +          Type(), platform::TracerEventType::Operator, 1);
const std::string& Type() const { return type_; }
写成Type().c_str()
否则性能会差

2022-02-18 03:28 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_tracing.h
> +                                             TracerEventType::UserDefined,
换行有点怪，换成type单独一行吧

2022-02-18 03:28 UTC, liutiexing commented on paddle/fluid/framework/operator.cc
> +          Type(), platform::TracerEventType::Operator, 1);
string类型会导致memcpy，尽量用const char*

2022-02-18 06:46 UTC, rainyfly commented on paddle/fluid/framework/operator.cc
> +          Type(), platform::TracerEventType::Operator, 1);
已改

2022-02-18 06:56 UTC, liutiexing approved these changes

2022-02-18 06:56 UTC, liutiexing commented on paddle/fluid/imperative/prepared_operator.cc
> +    platform::RecordEvent record_event(op.Type() + "::compute",
这种尽量避免，新执行器只需要记录compute，无需op name，老执行器可以保持和原来一致

2022-02-19 04:08 UTC, wawltor approved these changes
LGTM

2022-02-19 04:08 UTC, merged