Update record interface using part3
PaddlePaddle/Paddle pull request #39695
Opened 2022-02-17 14:28 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

更新框架已有打点位置的代码到最新接口。

2022-02-19 08:56 UTC, liutiexing submitted a review, later dismissed

2022-02-21 05:04 UTC, liutiexing requested changes

2022-02-21 05:04 UTC, liutiexing commented on paddle/fluid/operators/reader/read_op.cc
> +        Type(), platform::TracerEventType::UserDefined, 1);
这里可以写成Type().c_str()

2022-02-21 05:11 UTC, rainyfly commented on paddle/fluid/operators/reader/read_op.cc
> +        Type(), platform::TracerEventType::UserDefined, 1);
已修改

2022-02-21 05:37 UTC, liutiexing submitted a review, later dismissed

2022-02-22 07:52 UTC, liutiexing approved these changes

2022-02-23 02:01 UTC, wanghuancoder approved these changes
LGTM

2022-02-23 02:01 UTC, merged