[MLU]support launch process on mlu
PaddlePaddle/Paddle pull request #39839
Opened 2022-02-23 03:54 UTC by kangna-qi

### PR types
New features

### PR changes
Others

### Describe
support launch processes on MLU

2022-02-23 04:09 UTC, kangna-qi commented
测试命令
```
bash test_launch_async_mlu.sh
bash test_launch_cloud_mlu.sh
bash test_launch_nproc_mlu.sh
```

测试日志
![1](https://user-images.githubusercontent.com/96479180/155260270-20d30184-89f4-4f83-b370-29d21421f931.png)
![2](https://user-images.githubusercontent.
![4](https://user-images.githubusercontent.com/96479180/155260288-ec24245e-3046-49ab-85e8-f71b8b1be99e.png)
com/96479180/155260272-a66405f2-9763-44d5-87f6-31c9d2173cec.png)
![5](https://user-images.githubusercontent.com/96479180/155260301-f56eb449-1a09-4e48-bad8-b1a09e76bfdc.png)

2022-02-23 09:43 UTC, qili93 approved these changes
LGTM

2022-02-23 09:59 UTC, qili93 requested changes

2022-02-23 09:59 UTC, qili93 commented on python/paddle/distributed/fleet/launch_utils.py
> +                    "your mlus %s in MLU_VISIBLE_DEVICES[%s]."\
需要确认下，寒武纪的硬件是支持使用“MLU_VISIBLE_DEVICES”这样的变量对不？功能类似CUDA_VISIBLE_DEVICES可以指定可见的设备ID对吗？

2022-02-23 09:59 UTC, qili93 commented on python/paddle/fluid/tests/unittests/multi_process.py
> +        selected_devices = os.getenv("FLAGS_selected_gpus")
这里建议避免直接修改unittests目录下的文件，建议在mlu目录下单独拷贝一份代码命名为multi_process_mlu.py，后续Paddle会对所有的单测针对不同硬件做统一封装，目前暂时通过不通目录来区分硬件类型。下面的文件做相同处理，谢谢！

2022-02-23 10:06 UTC, kangna-qi commented on python/paddle/distributed/fleet/launch_utils.py
> +                    "your mlus %s in MLU_VISIBLE_DEVICES[%s]."\
对的，功能类似于CUDA_VISIBLE_DEVICES

2022-02-23 10:28 UTC, kangna-qi commented on python/paddle/fluid/tests/unittests/multi_process.py
> +        selected_devices = os.getenv("FLAGS_selected_gpus")
已修改

2022-02-23 11:39 UTC, xymyeah submitted a review, later dismissed
LGTM

2022-02-24 12:51 UTC, qili93 approved these changes
LGTM

2022-02-24 12:53 UTC, xymyeah approved these changes

2022-02-25 03:13 UTC, PangHua approved these changes

2022-02-25 03:29 UTC, fuyinno4 approved these changes

2022-02-25 03:37 UTC, XieYunshen approved these changes
LGTM for 
`        set_tests_properties(test_collective_broadcast PROPERTIES TIMEOUT 120)
	set_tests_properties(test_collective_allreduce PROPERTIES TIMEOUT 120)`

2022-02-25 05:28 UTC, merged