Add components for profiler
PaddlePaddle/Paddle pull request #39838
Opened 2022-02-23 03:43 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

给Paddle profiler加入CPU利用率、额外信息补充机制、以及sm占用率的调用接口。

2022-02-24 07:37 UTC, liutiexing requested changes

2022-02-24 07:37 UTC, liutiexing commented on paddle/fluid/platform/profiler/utils.h
> +#ifdef PADDLE_WITH_CUPTI
前面加一个空行

2022-02-24 07:37 UTC, liutiexing commented on paddle/fluid/platform/profiler/cpu_utilization.h
> +#ifdef _MSC_VER
private data members

2022-02-24 07:37 UTC, liutiexing commented on paddle/fluid/platform/profiler/cpu_utilization.cc
> +  float idle_time = (idle_end_ - idle_start_);
previdle = previdle + previowait
idle = idle + iowait
prevnoidle = prevuser + prevnice + prevsystem + previrq + prevsoftirq + prevsteal
noidle = user + nice + system + irq + softirq + steal
prevtotal = previdle + prevnonidle
total = idle + nonidle
total_delta = total - prevtotal
idle_delta = idle - previdle
CPU_usage = (total_delta - idle_delta)/total_delta

2022-02-24 07:37 UTC, liutiexing commented on paddle/fluid/platform/profiler/cpu_utilization.cc
> +  float idle_time = (idle_end_ - idle_start_);
可以观察一下现在公式的效果，上述公式可能更好。

2022-02-24 10:29 UTC, rainyfly commented on paddle/fluid/platform/profiler/utils.h
> +#ifdef PADDLE_WITH_CUPTI
已改

2022-02-24 10:30 UTC, rainyfly commented on paddle/fluid/platform/profiler/cpu_utilization.h
> +#ifdef _MSC_VER
已改

2022-02-24 10:30 UTC, rainyfly commented on paddle/fluid/platform/profiler/cpu_utilization.cc
> +  float idle_time = (idle_end_ - idle_start_);
已改

2022-02-25 07:59 UTC, liutiexing approved these changes, later dismissed

2022-02-25 10:55 UTC, liutiexing approved these changes

2022-02-28 02:02 UTC, closed without merging