Inference add ONNXRuntime  back-end
PaddlePaddle/Paddle pull request #39988
Opened 2022-02-28 07:23 UTC by heliqi

### PR types
New features

### PR changes
Others

### Describe

paddle inference增加paddle2onnx、onnxruntime集成
1. 当前只支持了python、c++，其他语言后续提PR合入
2. 新的onnx推理维支持旧的run接口(不会报错，调用返回false并提示)，只实现了新的ZeroCopyRun接口

2022-02-28 08:33 UTC, liyancas commented on cmake/external/onnxruntime.cmake
> +  message(SEND_ERROR "onnxruntime no support GPU")
"onnxruntime no support GPU" -> "The current onnxruntime backend doesn't support GPU", 本身onnxruntime是支持的，只是咱们集成中只考虑了CPU，下面“With Arm” 类似

2022-02-28 08:41 UTC, liyancas commented on paddle/fluid/inference/api/analysis_config.cc
> +  LOG(ERROR) << "Please compile with onnxruntime to EnableONNXRuntime()";
"Please compile with onnxruntime to EnableONNXRuntime()"-> “The onnxruntime backend isn't enabled, and please re-compile Paddle with WITH_ONNXRUNTIME option”

2022-03-01 08:33 UTC, heliqi commented on cmake/external/onnxruntime.cmake
> +  message(SEND_ERROR "onnxruntime no support GPU")
已改，同时去掉了开启GPU时的编译拦截

2022-03-01 08:33 UTC, heliqi commented on paddle/fluid/inference/api/analysis_config.cc
> +  LOG(ERROR) << "Please compile with onnxruntime to EnableONNXRuntime()";
已改

2022-03-02 02:39 UTC, Shixiaowei02 submitted a review, later dismissed

2022-03-02 02:53 UTC, jiweibo reviewed
缺失单测和CI，是否能修改PR-CI-Inference流水线，ort默认打开

2022-03-02 06:31 UTC, liyancas commented on paddle/fluid/pybind/inference_api.cc
> +      .def("onnxruntime_enable", &AnalysisConfig::use_onnxruntime)
onnxruntime_enable 和 enable_onnxruntime这两个很奇怪

2022-03-02 07:09 UTC, heliqi commented on paddle/fluid/pybind/inference_api.cc
> +      .def("onnxruntime_enable", &AnalysisConfig::use_onnxruntime)
这个是参照下面TRT的，比如: enable_tensorrt_oss 、tensorrt_dla_enabled
gpu、npu的接口是 enable_use_gpu 和 use_gpu,   enable_npu 和 use_npu 感觉更奇怪，就用了上面的

2022-03-02 08:37 UTC, liyancas commented on paddle/fluid/pybind/inference_api.cc
> +      .def("onnxruntime_enable", &AnalysisConfig::use_onnxruntime)
这个函数应该是查询设置的状态，那这个改成这样稍微清晰点：onnxruntime_enable -> onnxruntime_enabled

2022-03-02 08:38 UTC, liyancas commented on cmake/external/onnxruntime.cmake
> +  SET(ONNXRUNTIME_LIB "${ONNXRUNTIME_INSTALL_DIR}/lib/onnxruntime.lib" CACHE FILEPATH "ONNXRUNTIME static library." FORCE)
share -> shared 其他类似问题更改下

2022-03-02 08:41 UTC, liyancas commented on paddle/fluid/inference/api/analysis_predictor.cc
> +                      "using Paddle Inference.";
"The current ONNXRuntime backend doesn't support GPU， and it falls back to use Paddle Inference." 类似注释问题也改一下

2022-03-02 08:42 UTC, liyancas commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // Turn optimization off first, and then turn it on when it's stabl
stabl -> stable

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +/*
没用的删掉？

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // session_options.SetInterOpNumThreads(config_.cpu_math_library_num_threads());
删？

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // session_ = {env_, config_.prog_file().c_str(), session_options};
删？

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#ifdef PADDLE_WITH_ONNXRUNTIME
是不是不打开编译选项这个头文件不会被include，也不会release到发布包，同时onnxruntime_predictor.cc也不会编译，这个头文件内部还需要用宏判断么？

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#ifdef PADDLE_WITH_ONNXRUNTIME
同上

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#ifdef PADDLE_WITH_ONNXRUNTIME
同

2022-03-02 08:59 UTC, shangzhizhou commented on paddle/fluid/pybind/inference_api.cc
> +#include "paddle/fluid/inference/api/onnxruntime_predictor.h"
此处加宏控制

2022-03-03 02:32 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#ifdef PADDLE_WITH_ONNXRUNTIME
已经把把宏删掉。 不打开选项不会编译.cc文件，也不会include头文件。这个.h文件不是对外暴露的接口，不会放到发不包里

2022-03-03 02:32 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // session_ = {env_, config_.prog_file().c_str(), session_options};
已删

2022-03-03 02:33 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // session_options.SetInterOpNumThreads(config_.cpu_math_library_num_threads());
属于优化开启要设置的，移动到上面了

2022-03-03 02:33 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#ifdef PADDLE_WITH_ONNXRUNTIME
已删

2022-03-03 02:33 UTC, heliqi commented on paddle/fluid/pybind/inference_api.cc
> +#include "paddle/fluid/inference/api/onnxruntime_predictor.h"
已加

2022-03-03 02:33 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +/*
已删

2022-03-03 02:34 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.cc
> +  // Turn optimization off first, and then turn it on when it's stabl
已改

2022-03-03 02:34 UTC, heliqi commented on paddle/fluid/inference/api/analysis_predictor.cc
> +                      "using Paddle Inference.";
已改

2022-03-03 02:34 UTC, heliqi commented on cmake/external/onnxruntime.cmake
> +  SET(ONNXRUNTIME_LIB "${ONNXRUNTIME_INSTALL_DIR}/lib/onnxruntime.lib" CACHE FILEPATH "ONNXRUNTIME static library." FORCE)
已全部替换

2022-03-03 02:34 UTC, heliqi commented on paddle/fluid/pybind/inference_api.cc
> +      .def("onnxruntime_enable", &AnalysisConfig::use_onnxruntime)
已改

2022-03-09 12:27 UTC, qili93 approved these changes
LGTM for CMakeLists.txt

2022-03-10 02:16 UTC, leiqing1 requested changes
麻烦更新下对应API文档。

2022-03-10 02:52 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +  std::shared_ptr<framework::Scope> scope_;
请问这个是public的么？

2022-03-10 02:53 UTC, heliqi commented
> 麻烦更新下对应API文档。
API文档我等下提一个PR到对应的另一个repo

2022-03-10 02:53 UTC, Shixiaowei02 commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#if PADDLE_WITH_TESTING
请问这里的宏定义用法有参考吗

2022-03-10 02:54 UTC, Shixiaowei02 approved these changes

2022-03-10 02:59 UTC, heliqi commented on paddle/fluid/inference/api/onnxruntime_predictor.h
> +#if PADDLE_WITH_TESTING
参考的analysis_predictor.h : https://github.com/PaddlePaddle/Paddle/blob/9262a93c2ef51db2f0b80e6539c5b3e54f2fc6f4/paddle/fluid/inference/api/analysis_predictor.h#L388

2022-03-10 02:59 UTC, Shixiaowei02 commented
approve for CMakeLists.txt

2022-03-10 03:00 UTC, winter-wang approved these changes
LGTM

2022-03-10 03:21 UTC, Superjomn approved these changes
API 名称修改，可以下个PR改下

2022-03-10 05:35 UTC, XiaoguangHu01 approved these changes
LGTM

2022-03-10 08:21 UTC, heliqi commented
> > 麻烦更新下对应API文档。
> > API文档我等下提一个PR到对应的另一个repo
已提文档PR: https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/222

2022-03-10 09:24 UTC, leiqing1 approved these changes

2022-03-10 12:50 UTC, merged

2022-03-10 12:55 UTC, jiangjiajun commented
数据拷贝上仍然有优化的空间，下个PR解决 @heliqi

2022-03-15 06:57 UTC, heliqi commented
> 

@jiangjiajun   优化PR:  https://github.com/PaddlePaddle/Paddle/pull/40561