Upgrade new profiler
PaddlePaddle/Paddle pull request #39984
Opened 2022-02-28 06:11 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

1. 优化了Chrometracing导出的timeline展示效果
2. 加入了Extra info
3. 加入暴露到python层的数据结构
4. 根据所加入内容修改profiler.cc

2022-02-28 08:17 UTC, liutiexing requested changes

2022-02-28 08:17 UTC, liutiexing commented on paddle/fluid/platform/profiler/profiler.cc
>    HostTracerOptions host_tracer_options;
HostTracerOptions host_tracer_options;挪到if (trace_switch.test(kProfileCPUOptionBit)里

2022-02-28 08:17 UTC, liutiexing commented on paddle/fluid/platform/profiler/profiler.cc
> +#include "paddle/fluid/platform/profiler/cpu_utilization.h"
这个。h里include一次了

2022-02-28 08:25 UTC, liutiexing requested changes

2022-02-28 08:25 UTC, liutiexing commented on paddle/fluid/platform/profiler/event_python.cc
> +    : tree_(std::move(tree)), extra_info_(extra_info) {
tree_ is a memory leak？

2022-02-28 10:31 UTC, rainyfly commented on paddle/fluid/platform/profiler/profiler.cc
>    HostTracerOptions host_tracer_options;
已改

2022-02-28 10:31 UTC, rainyfly commented on paddle/fluid/platform/profiler/profiler.cc
> +#include "paddle/fluid/platform/profiler/cpu_utilization.h"
已改

2022-02-28 11:34 UTC, liutiexing approved these changes, later dismissed

2022-03-01 03:33 UTC, liutiexing approved these changes, later dismissed

2022-03-01 07:16 UTC, liutiexing approved these changes

2022-03-01 07:51 UTC, liutiexing requested changes
ChromeTracing has some bug

2022-03-01 10:53 UTC, liutiexing submitted a review, later dismissed

2022-03-01 14:00 UTC, liutiexing approved these changes, later dismissed

2022-03-02 07:30 UTC, wanghuancoder approved these changes
LGTM

2022-03-02 07:30 UTC, merged