add python profiler package
PaddlePaddle/Paddle pull request #40065
Opened 2022-03-02 08:03 UTC by rainyfly

### PR types

New features
### PR changes

APIS
### Describe

1. pybind绑定C++ Profiler有关接口到python层
2. Python层新增profiler package

2022-03-02 08:28 UTC, liutiexing requested changes

2022-03-02 08:28 UTC, liutiexing commented on paddle/fluid/pybind/pybind.cc
> +      .def_readwrite("trace_level",
这个level暴漏吗？

2022-03-02 08:28 UTC, liutiexing commented on paddle/fluid/pybind/pybind.cc
> +      .def("Stop", &paddle::platform::Profiler::Stop,
stop时disable HostEventRecorder

2022-03-02 08:48 UTC, rainyfly commented on paddle/fluid/pybind/pybind.cc
> +      .def_readwrite("trace_level",
已改

2022-03-02 08:48 UTC, rainyfly commented on paddle/fluid/pybind/pybind.cc
> +      .def("Stop", &paddle::platform::Profiler::Stop,
已添加

2022-03-02 08:58 UTC, liutiexing reviewed
LGTM

2022-03-04 08:24 UTC, wawltor commented on paddle/fluid/pybind/pybind.cc
> +  py::class_<paddle::platform::Profiler>(m, "_Profiler")
这块的Profiler相关调用函数首字母大写，这块是有调研过竞品，都是大写？

2022-03-04 08:24 UTC, wawltor commented on paddle/fluid/pybind/pybind.cc
> +        return std::unique_ptr<platform::RecordEvent>(new platform::RecordEvent(
这里使用make_unique的性能是不是更好一点？

2022-03-04 08:24 UTC, wawltor commented on python/paddle/profiler/profiler.py
> +                            scheduler = (3, 10),
这里有个疑问，虽然在构建scheduler的时候可以多种方式，但是给用户的感觉就是构建方法不够清晰，这里是不是考虑把接口统一一下

2022-03-04 08:24 UTC, wawltor commented on python/paddle/profiler/profiler.py
> +    def start(self):
start和stop的文档补齐一下

2022-03-04 10:42 UTC, rainyfly commented on paddle/fluid/pybind/pybind.cc
> +  py::class_<paddle::platform::Profiler>(m, "_Profiler")
已修改为小写

2022-03-04 10:42 UTC, rainyfly commented on paddle/fluid/pybind/pybind.cc
> +        return std::unique_ptr<platform::RecordEvent>(new platform::RecordEvent(
已修改

2022-03-04 10:43 UTC, rainyfly commented on python/paddle/profiler/profiler.py
> +    def start(self):
已补充

2022-03-08 01:55 UTC, wawltor approved these changes
LGTM

2022-03-08 01:55 UTC, merged