modify sequence_conv_xpu op test. test=kunlun
PaddlePaddle/Paddle pull request #40347
Opened 2022-03-09 04:01 UTC by tiancaitzp

### PR types

Others 

### PR changes

Others 

### Describe

根据内部规范修改xpu op test

2022-03-15 06:13 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +                                   self.input_size[1]]).astype('float32')
用self.dtype

2022-03-15 06:13 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +            ]).astype('float32')
同上

2022-03-15 06:13 UTC, XiaociZhang requested changes

2022-03-15 06:13 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +                0, 0, [total_pad, self.input_size[1]]).astype('float32')
同上

2022-03-16 03:43 UTC, tiancaitzp commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +                0, 0, [total_pad, self.input_size[1]]).astype('float32')
done

2022-03-16 03:44 UTC, tiancaitzp commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +            ]).astype('float32')
done

2022-03-16 03:44 UTC, tiancaitzp commented on python/paddle/fluid/tests/unittests/xpu/test_sequence_conv_op_xpu.py
> +                                   self.input_size[1]]).astype('float32')
done

2022-03-17 04:37 UTC, XiaociZhang approved these changes
LGTM

2022-03-17 09:22 UTC, QingshuChen approved these changes

2022-03-17 09:22 UTC, merged