【Hachathon No.30】
PaddlePaddle/Paddle pull request #40545
Opened 2022-03-14 17:00 UTC by yangguohao

### PR types
New features
### PR changes
API

### Describe
add triplet margin with distance loss

2022-03-14 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=40545) <br/>All committers have signed the CLA.

2022-03-15 01:54 UTC, dingjiaweiww commented
你的 PR 提交成功，感谢你对于开源项目的贡献

2022-03-15 01:55 UTC, dingjiaweiww commented
PR 格式检查通过，你的PR 将接受Paddle 专家以及开源社区的review，请及时关注PR 动态

2022-03-15 14:04 UTC, shiyutang commented
根据[流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)，方案设计通过之后才能开始代码review，请仔细查看对应方案设计文档PR的修改意见，修改之后对应进行代码部分修改，当文档合入之后方可进行代码 PR 的review。

2022-03-28 11:34 UTC, shiyutang commented
根据 CI 报错信息来看，你需要将paddle dev merge到当前 yangguohao:triplet_margin_distance_loss 分支来通过CI
![image](https://user-images.githubusercontent.com/34859558/160389392-d8072db7-43ba-4426-94ee-c787192db77d.png)

2022-03-29 08:19 UTC, shiyutang requested changes
需要重新拉区develop的代码，通过所有CI（除PR-CI-Static-Check）之后才能进行进一步review

2022-03-31 03:40 UTC, dingjiaweiww commented
请先通过CI噢~

2022-03-31 03:41 UTC, dingjiaweiww commented
请先通过CI噢~

2022-03-31 07:28 UTC, shiyutang commented
1. 需要增加设计文档链接，如图所示：
![06b8a2904adf5ec3c229031619c25f57](https://user-images.githubusercontent.com/34859558/160998313-50c97afe-418c-4921-915a-2f76a14e6f41.png)

2. 需要替换 in_dygraph_mode 如下图所示：
![4ac43d3d67cdea50a08659a006f90a19](https://user-images.githubusercontent.com/34859558/160998692-d627b147-90f0-42bd-b207-9134f8bb1d73.jpg)

2022-04-06 06:55 UTC, shiyutang commented
根据最新说明，_non_static_mode的调用路径需要更改为paddle.framework._non_static_mode，不再和fluid耦合

2022-04-07 12:56 UTC, shiyutang commented
CI 中显示代码中存在错误：
<img width="822" alt="image" src="https://user-images.githubusercontent.com/34859558/162203701-0d41e9c0-49a1-403d-a0f1-5821b70600aa.png">

2022-04-08 02:29 UTC, shiyutang commented
请注意代码PR中还需要和中文文档关联才可合入，可以参考这个PR：https://github.com/PaddlePaddle/Paddle/pull/40472
<img width="853" alt="image" src="https://user-images.githubusercontent.com/34859558/162351098-6b621a09-62c1-43fd-852f-9d483763e7c3.png">

书写规范请参考：https://github.com/PaddlePaddle/docs/wiki/%E9%A3%9E%E6%A1%A8API%E6%96%87%E6%A1%A3%E4%B9%A6%E5%86%99%E8%A7%84%E8%8C%83

2022-04-24 03:05 UTC, shiyutang requested changes
大部分完善点和 https://github.com/PaddlePaddle/Paddle/pull/40487#pullrequestreview-951140425 相同，请参照修改。

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +
空行删除

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2022

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/nn/layer/loss.py
> +
注释需要根据自己理解重写，里面维度说明、positive、negative的数值说明也存在一定问题

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/nn/functional/loss.py
> +            `Learning shallow convolutional feature descriptors with triplet losses` by
注释需要根据自己理解重写，里面维度说明、positive、negative的数值说明也存在一定问题

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +            return paddle.max(paddle.abs(x1-x2), axis=1)
测试当距离函数不满足非负性是是否会报错？

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        negative = np.random.randint(0, 2, size=(20, 30)).astype(np.float64)
随机浮点数

2022-04-24 03:05 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +
增加margin<0, swap=True的测试。

2022-04-25 13:59 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +            return paddle.max(paddle.abs(x1-x2), axis=1)
添加了一个对求得距离的判断不能小于0

2022-04-27 07:04 UTC, shiyutang approved these changes
LGTM

2022-04-27 07:10 UTC, shiyutang requested changes

2022-04-27 07:10 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss()
调用接口存在问题：
<img width="231" alt="image" src="https://user-images.githubusercontent.com/34859558/165461455-2e508586-6ca2-4f68-a796-d8cc691afc21.png">

2022-04-27 07:10 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +    triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss(distance_function=distance_function,
接口存在问题：
<img width="231" alt="image" src="https://user-images.githubusercontent.com/34859558/165461524-5f81c5da-4850-4493-8d18-2c30f6629ace.png">

2022-04-27 07:44 UTC, DDDivano requested changes

2022-04-27 07:44 UTC, DDDivano commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        positive = paddle.fluid.data(
尽量避免使用fluid包下函数

2022-04-27 07:44 UTC, DDDivano commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        place = fluid.CPUPlace()
使用paddle.CPUPlace()替代

2022-04-27 14:22 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss()
我不太清楚这是什么原因导致的。

2022-04-28 02:23 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +        triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss()
最好使用paddle.nn.TripletMarginWithDistanceLoss

2022-04-28 02:24 UTC, shiyutang commented
coverage test fail 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/34859558/165663979-7a28a82e-0dbf-4edf-a6d8-60f00c528956.png">

2022-05-06 12:37 UTC, shiyutang commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +    triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss(distance_function=distance_function,
这里没有修改

2022-05-07 05:43 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_triplet_margin_with_distance_loss.py
> +    triplet_margin_with_distance_loss = paddle.nn.loss.TripletMarginWithDistanceLoss(distance_function=distance_function,
已修改

2022-05-07 15:38 UTC, yangguohao commented
已修改相关内容，麻烦再review下

2022-05-09 09:00 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +
中英文文档需要保持一致，缺少论文部分

2022-05-09 09:00 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +        input:Input tensor, the data type is float32 or float64.
- 参数需要在括号里增加数据类型和是否可选
- 源码参数若有name则文档中也需要有，顺序与数量需要和源码保持一致

2022-05-09 09:00 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
> +    Creates a criterion that measures the triplet loss given an input
参考triplet_margin_with_distance_loss进行修改

2022-05-10 07:59 UTC, yangguohao commented on python/paddle/nn/functional/loss.py
> +
已修改

2022-05-10 07:59 UTC, yangguohao commented on python/paddle/nn/functional/loss.py
> +        input:Input tensor, the data type is float32 or float64.
已修改

2022-05-10 07:59 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    Creates a criterion that measures the triplet loss given an input
已修改

2022-05-13 06:15 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
> +    Creates a criterion that measures the triplet loss given an input
嗯？介绍部分还是不太一样呀？
<img width="962" alt="image" src="https://user-images.githubusercontent.com/39876205/168221459-92a14a15-667d-4744-a342-45c2f3d642bb.png">
<img width="878" alt="image" src="https://user-images.githubusercontent.com/39876205/168221491-8f928e51-0806-48b4-a413-d5038adc4325.png">

2022-05-13 06:15 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
> +    Call Parameters:
- 这是？对应中文文档的shape吗？怎么没有output？
- 英文标点符号后最好加一个空格

2022-05-13 06:15 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +
改了吗？
<img width="913" alt="image" src="https://user-images.githubusercontent.com/39876205/168222123-e20b2972-78fb-4da3-a515-dab487591b86.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/39876205/168222158-5d0777bc-0619-4cf4-b368-1bf0dbe37843.png">

2022-05-13 09:19 UTC, shiyutang reviewed
LGTM

2022-05-16 08:20 UTC, DDDivano submitted a review, later dismissed

2022-05-17 04:05 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    Call Parameters:
将 Call Parameters 改为 Shapes， 添加 output

2022-05-17 04:06 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    Creates a criterion that measures the triplet loss given an input
添加英文部分 distance_function, margin, swap 的内容

2022-05-17 04:06 UTC, yangguohao commented on python/paddle/nn/functional/loss.py
> +
添加英文部分 distance_function, margin, swap 的内容

2022-05-18 08:21 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
> +    Creates a criterion that measures the triplet loss given an input
<img width="848" alt="image" src="https://user-images.githubusercontent.com/39876205/168991659-263f4864-9be7-42a8-ace7-072a95cc2ebe.png">

这里好像还没有加上~

2022-05-18 08:21 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +
同 TripletMarginWithDistanceLoss，API介绍部分中英文意思还是不太一样

2022-05-20 03:02 UTC, Ligoml approved these changes, later dismissed
LGTM for docs

2022-05-20 08:54 UTC, jeff41404 commented on python/paddle/nn/layer/loss.py
> +    def __init__(self, distance_function=None, margin=1.0, swap=False, reduction: str = 'mean', name=None):
the order of parameters here must same with [RFC](https://github.com/PaddlePaddle/community/pull/34), here suggest to modify RFC `distance_function` before `margin`

2022-05-20 08:59 UTC, jeff41404 commented on python/paddle/nn/functional/loss.py
> +				      margin=1.0,
the order of parameters here must same with [RFC](https://github.com/PaddlePaddle/community/pull/34), here suggest to modify postion of `margin` before `swap`

2022-05-20 09:23 UTC, yangguohao commented on python/paddle/nn/functional/loss.py
> +				      margin=1.0,
已修改

2022-05-20 09:24 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    def __init__(self, distance_function=None, margin=1.0, swap=False, reduction: str = 'mean', name=None):
![image](https://user-images.githubusercontent.com/70266361/169498061-e96ec89a-76e7-4323-897f-c88d6ec4122e.png)

我这里显示的类名称和参数位置是正确的

2022-05-23 04:45 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    def __init__(self, distance_function=None, margin=1.0, swap=False, reduction: str = 'mean', name=None):
已修改RFC

2022-05-24 11:53 UTC, shiyutang submitted a review, later dismissed
LGTM，确认和RFC一致。

2022-05-31 06:10 UTC, Ligoml submitted a review, later dismissed

2022-06-01 02:42 UTC, jeff41404 submitted a review, later dismissed
LGTM

2022-06-01 07:59 UTC, XiaoguangHu01 approved these changes, later dismissed
LGTM

2022-06-02 02:30 UTC, Ligoml approved these changes, later dismissed

2022-06-08 10:17 UTC, Ligoml approved these changes, later dismissed

2022-06-10 02:56 UTC, Ligoml approved these changes

2022-06-10 09:34 UTC, XiaoguangHu01 approved these changes
LGTM

2022-06-13 02:58 UTC, merged