fleetrun launch in legacy mode
PaddlePaddle/Paddle pull request #40568
Opened 2022-03-15 08:04 UTC by kuizhiqing

### PR types

New features

### PR changes

Others

### Describe

New launch module with legacy mode

2022-03-17 03:19 UTC, xymyeah requested changes

2022-03-17 03:19 UTC, xymyeah commented on python/paddle/distributed/launch/plugins/__init__.py
>      if 'DISTRIBUTED_TRAINER_ENDPOINTS' in ctx.envs:
考虑一下兼容pdc的ip：port方式，防止出现端口冲突（pdc用全局端口）

2022-03-17 03:19 UTC, xymyeah commented on python/paddle/distributed/launch/__init__.py
> +# python -m paddle.distributed.launch --devices=0,1,2,3 train.py
如果是在平台上通过环境变量配置的，是对应新版本的逻辑还是对应老版本的逻辑，可以在check一下是否有兼容的问题

2022-03-17 03:19 UTC, xymyeah commented on python/paddle/distributed/launch/plugins/__init__.py
> +        eps = ctx.envs['DISTRIBUTED_TRAINER_ENDPOINTS'].split(',')
除了兼容之外，在新版本中DISTRIBUTED_TRAINER_ENDPOINTS这个环境变量是否还在使用？

2022-03-17 07:23 UTC, kuizhiqing commented on python/paddle/distributed/launch/__init__.py
> +# python -m paddle.distributed.launch --devices=0,1,2,3 train.py
新版本统一 --devices, 否则使用老版本

2022-03-17 07:23 UTC, kuizhiqing commented on python/paddle/distributed/launch/plugins/__init__.py
>      if 'DISTRIBUTED_TRAINER_ENDPOINTS' in ctx.envs:
已启用兼容模式

2022-03-17 07:23 UTC, kuizhiqing commented on python/paddle/distributed/launch/plugins/__init__.py
> +        eps = ctx.envs['DISTRIBUTED_TRAINER_ENDPOINTS'].split(',')
DISTRIBUTED_TRAINER_ENDPOINTS 为 pdc 专用，目前已启用兼容模式

2022-03-18 09:02 UTC, aoyulong approved these changes
LGTM.

2022-03-18 09:03 UTC, xymyeah approved these changes

2022-03-18 09:03 UTC, xymyeah commented on python/paddle/distributed/launch/context/args_envs.py
> +    base_group.add_argument(
新增的参数legacy建议在增加一些解释

2022-03-18 09:04 UTC, xymyeah approved these changes
LGTM

2022-03-18 09:53 UTC, kuizhiqing commented on python/paddle/distributed/launch/context/args_envs.py
> +    base_group.add_argument(
好的

2022-03-21 02:23 UTC, sandyhouse approved these changes
LGTM

2022-03-21 02:25 UTC, fuyinno4 approved these changes

2022-03-21 06:27 UTC, XiaoguangHu01 approved these changes
请更新一下API使用文档和示例

2022-03-21 06:27 UTC, XiaoguangHu01 commented on python/paddle/distributed/launch/context/args_envs.py
> +    base_group.add_argument(
这里可以说明一下legacy只用于内部调试，外部开发者不需要关心这两种模式的差别。

2022-03-21 06:35 UTC, XieYunshen approved these changes
LGTM for `set_tests_properties(test_run PROPERTIES TIMEOUT 120)`

2022-03-21 07:14 UTC, merged