fix paddle.vision.transforms.Resize en docs
PaddlePaddle/Paddle pull request #40719
Opened 2022-03-18 15:09 UTC by Liyulingyue

### PR types

Others 
### PR changes

Docs 
### Describe

任务需求见https://github.com/PaddlePaddle/docs/issues/4239
修改代码示例与中文文档保持一致

2022-03-18 16:02 UTC, SigureMo requested changes

2022-03-18 16:02 UTC, SigureMo commented on python/paddle/vision/transforms/transforms.py
> +            # (150, 200)
示例代码个人感觉完全对齐中文文档比较好吧（就是直接 copy，两面完全一致），而且目前英文文档的示例输出应当是 `(268, 224)`

另外不太建议对同一个 `fake_img` 连续 transform 两次，这样第二个用例可能会依赖第一个用例，建议 transform 后换一个变量名～感觉参考 [paddle.vision.transform.resize](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/vision/transforms/resize_cn.html#daimashili) 的中英文文档那样就可以～

看样子 paddle.vision.transform.resize 中英文文档也有相似问题呀，可以一起解决下下～～～

2022-03-18 23:27 UTC, Liyulingyue commented on python/paddle/vision/transforms/transforms.py
> +            # (150, 200)
已修改，因为我的电脑抽取英文文档报错，所以没有对英文的api解释说明修改

具体修改内容如下：
1. 给resize增加输出示例
2. 由于Resize的develop中文文档和resize保持一致，所以对英文的Resize的注释部分的代码没有完全和中文保持一致，仅修改示例使得输出一致。

2022-03-19 14:42 UTC, Liyulingyue commented
@TCChenlong

2022-03-19 15:10 UTC, SigureMo commented
> @TCChenlong

可以等下周一哈～周末龙哥应该还在休息，可以先检查下 CI～我刚刚发现仅涉及文档的修改可以在 commit message （应该是最新一次 commit）里加上 `test=document_fix` 使其仅执行 static check～

> 参考 [Paddle CI 手册](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/paddle_ci_manual_cn.html#zhengtijieshao)

2022-03-19 15:12 UTC, SigureMo commented
或者手动重新触发下 PR-CI-iScan-Python 应该也可以～现在 CI 也支持手动 rerun 其中某一个了～

2022-03-23 05:31 UTC, TCChenlong approved these changes

2022-03-25 03:21 UTC, merged