pool2d support fp16 on xpu and update pool2d unittest, test=kunlun
PaddlePaddle/Paddle pull request #40841
Opened 2022-03-23 03:39 UTC by zhangyk0314

### PR types
New features

### PR changes
OPs 

### Describe
pool2d support fp16 on xpu and update pool2d unittest, test=kunlun

2022-03-28 03:06 UTC, houj04 requested changes

2022-03-28 03:06 UTC, houj04 commented on python/paddle/fluid/tests/unittests/xpu/test_pool2d_op_xpu.py
> +            return core.is_compiled_with_xpu()
刚和zhiyi确认了，新的单测里面不需要这个了。

2022-03-28 03:08 UTC, houj04 commented on python/paddle/fluid/tests/unittests/xpu/test_pool2d_op_xpu.py
> +    class TestCase5_AsyPadding((TestCase5)):
双层括号？

2022-03-28 06:55 UTC, zhangyk0314 commented on python/paddle/fluid/tests/unittests/xpu/test_pool2d_op_xpu.py
> +    class TestCase5_AsyPadding((TestCase5)):
已修改。

2022-03-28 06:55 UTC, zhangyk0314 commented on python/paddle/fluid/tests/unittests/xpu/test_pool2d_op_xpu.py
> +            return core.is_compiled_with_xpu()
已修改。

2022-03-29 02:45 UTC, houj04 approved these changes

2022-03-29 02:46 UTC, QingshuChen approved these changes

2022-03-29 02:46 UTC, merged