Add time range duration display
PaddlePaddle/Paddle pull request #41029
Opened 2022-03-28 09:18 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

1.  给Chrometracing的时间段名字上面加入了时间的显示，方便查看时间
2. 修复了一下不足1us即1000ns以内的事件在timeline显示为线条非线段的问题
3. 控制颜色为3种，防止杂乱过多的问题

2022-03-28 09:39 UTC, liutiexing requested changes

2022-03-28 09:39 UTC, liutiexing commented on paddle/fluid/platform/profiler/chrometracing_logger.cc
> +    "name": "%s[%.3f ms]", "pid": %lld, "tid": "%lld(Python)",
如沟通，时间短，us，时间长（大于1ms），用ms

2022-03-28 10:53 UTC, rainyfly commented on paddle/fluid/platform/profiler/chrometracing_logger.cc
> +    "name": "%s[%.3f ms]", "pid": %lld, "tid": "%lld(Python)",
已修改

2022-03-28 11:03 UTC, liutiexing submitted a review, later dismissed

2022-03-28 11:39 UTC, TCChenlong approved these changes, later dismissed

2022-03-29 05:59 UTC, TCChenlong submitted a review, later dismissed
LGTM for API docs

2022-03-29 07:26 UTC, liutiexing approved these changes, later dismissed

2022-03-30 02:52 UTC, TCChenlong submitted a review, later dismissed

2022-03-30 11:17 UTC, liutiexing approved these changes

2022-03-30 12:06 UTC, TCChenlong approved these changes

2022-03-31 03:36 UTC, merged