[PaddleHackathon No.14]
PaddlePaddle/Paddle pull request #41183
Opened 2022-03-30 16:58 UTC by yangguohao

### PR types
New features
### PR changes
APIs
### Describe
add multi label margin loss

2022-03-30 16:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=41183) <br/>All committers have signed the CLA.

2022-03-31 03:38 UTC, dingjiaweiww commented
在PR被review前请先通过CI噢~

2022-04-19 07:38 UTC, betterpig requested changes
主要问题：
1. 两个单测文件要去掉，如果没修改的话。
2. 尽量将paddle.fluid改为paddle.static

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_frac_api.py
> -#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
这个文件有改动/需要改动吗，没有的话不应该出现在这里。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_quantile_and_nanquantile.py
> -#   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
这个文件有改动/需要改动吗，没有的话不应该出现在这里。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/nn/functional/loss.py
> +    r"""
需要补充英文文档。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/nn/functional/loss.py
> +            'The input and label should have some dimension'
1. 单词拼写错了 some->same
2. 加上 `'but received {} != {}'.format(input.shape, label.shape)`

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +import paddle.fluid as fluid
后续fluid将删除，因此尽量不使用fluid下的API，需要替换为paddle.static.xx，可在[__init__.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/__init__.py)中查看static对应的API。若无法替代的，请不要显式使用fluid API，即在开始引入API名称，后面不加路径地调用该API。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +        input = paddle.fluid.data(
paddle.fluid.data --> paddle.static.data，下同

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +    unittest.main()
最后需要空一行。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +            for reduction in reductions:
前面已经测过place和reduction了，这里可以不用再测了，降低单测执行时间。

2022-04-19 07:38 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +            places.append(fluid.CUDAPlace(0))
看能否改为 `paddle.static.cpu_places()` 和 `paddle.static.cuda_places(0)`

2022-04-24 08:29 UTC, betterpig requested changes
大部分问题已解决，还需要看下两个无关单测怎么从PR中去除，以及单测中动态图测试函数里并没有用到place。

2022-04-24 08:29 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +def test_dygraph(place,
place在动态图测试中似乎没有体现。

2022-04-24 08:29 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_frac_api.py
> -#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
这个文件改动吗，能删除吗，请答复一下。

2022-04-24 08:29 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_quantile_and_nanquantile.py
> -#   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
这个文件改动吗，能删除吗，请答复一下。

2022-04-25 12:08 UTC, yangguohao commented
那两个无关文件我不知道怎么删除，我并没有改动他们，也都是一样的，不知道为什么判定修改了。

2022-04-25 12:08 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +def test_dygraph(place,
我修改一下

2022-04-25 12:13 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +def test_dygraph(place,
这一部分我参考已有的损失函数的test文件，发现place在动态图中都没有体现。

2022-04-25 12:16 UTC, yangguohao commented on python/paddle/fluid/tests/unittests/test_frac_api.py
> -#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
我用原文件覆盖也判定为修改了，不知道什么原因。

> 这个文件改动吗，能删除吗，请答复一下。

2022-04-26 09:13 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_multilabel_margin_loss.py
> +def test_dygraph(place,
可能是考虑到在静态图中已经测试了place，那就不用加了。

2022-04-26 09:17 UTC, betterpig commented on python/paddle/fluid/tests/unittests/test_frac_api.py
> -#   Copyright (c) 2018 PaddlePaddle Authors. All Rights Reserved.
先保留要更改的文件，然后把分支reset成最新的develop分支，再加上修改。

2022-04-29 07:24 UTC, betterpig submitted a review, later dismissed
LGTM

2022-04-29 11:01 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +        Parameters:
Parameters、Call parameters、Shape、Returns、Examples 等和前面空一行

2022-04-29 11:01 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +                import paddle
import paddle 前要空一行

2022-04-29 11:01 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +                import paddle.nn as nn
示例代码也要注意空行

2022-04-29 11:01 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +        .. math::
公式这里有格式问题，前面要空一行

2022-05-05 07:24 UTC, luotao1 commented
PR_CI_Coverage的历史记录看：https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/builds/6512?module=github/PaddlePaddle/Paddle&pipeline=PR-CI-Coverage&branch=pull/41183(develop) 失败了3次，都是单测超时，可以考虑缩小下单测输入数据大小来减少运行时间

2022-05-05 08:20 UTC, yangguohao commented
> PR_CI_Coverage的历史记录看：https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/builds/6512?module=github/PaddlePaddle/Paddle&pipeline=PR-CI-Coverage&branch=pull/41183(develop) 失败了3次，都是单测超时，可以考虑缩小下单测输入数据大小来减少运行时间

ok

2022-05-06 06:15 UTC, TCChenlong commented on python/paddle/nn/functional/loss.py
> +def multi_label_soft_margin_loss(
这里的英文文档，同下面的API，也需要在相关的位置空行~

2022-05-06 06:18 UTC, TCChenlong submitted a review, later dismissed

2022-05-06 06:32 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +            reduction=self.reduction,
这里建议严谨一点， weight 在前，reduction 在后吧

2022-05-06 06:32 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +        Parameters:
这里少了 weight 的参数说明

2022-05-06 06:32 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +    r"""Creates a criterion that optimizes a multi-class multi-classification
英文的这段说明，较中文少了一部分内容，建议语义内容上，与中文保持一致

2022-05-06 06:32 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +        Call parameters:
这个在中文文档中没有体现

2022-05-06 06:32 UTC, TCChenlong commented on python/paddle/nn/layer/loss.py
> +        Returns:
这个返回不是 Tensor吧，可以不写返回，写shape就好

2022-05-09 08:19 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +            reduction=self.reduction,
已修改

2022-05-09 08:19 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +        Parameters:
已添加

2022-05-09 08:32 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +        Returns:
修改为 A callable object of MultiLabelSoftMarginLoss.

2022-05-09 08:48 UTC, yangguohao commented on python/paddle/nn/functional/loss.py
> +def multi_label_soft_margin_loss(
1

2022-05-10 07:58 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +        Call parameters:
已作修改

2022-05-10 07:59 UTC, yangguohao commented on python/paddle/nn/layer/loss.py
> +    r"""Creates a criterion that optimizes a multi-class multi-classification
我看了好像是中文内容少了一些，补充了中文内容

2022-05-12 02:36 UTC, DDDivano approved these changes, later dismissed

2022-05-30 02:30 UTC, TCChenlong submitted a review, later dismissed
LGTM

2022-06-06 07:01 UTC, TCChenlong commented
@yangguohao 请解决一下 Code Style 问题

2022-06-17 06:20 UTC, TCChenlong approved these changes
LGTM

2022-06-17 07:03 UTC, XiaoguangHu01 approved these changes
LGTM

2022-06-17 08:05 UTC, jeff41404 commented
code is fine, but in [RFC](https://github.com/PaddlePaddle/community/pull/53) the description of parameters of `paddle.nn.MultiLabelSoftMarginLoss` is not correct which do not have  input and target

2022-06-17 08:35 UTC, jeff41404 approved these changes

2022-06-17 08:35 UTC, merged