add ParallelMode docs
PaddlePaddle/Paddle pull request #41326
Opened 2022-04-02 07:22 UTC by Yanxing-Shi

### PR types

Others

### PR changes

Docs

### Describe

add ParallelMode docs

2022-04-07 12:43 UTC, xymyeah requested changes

2022-04-07 12:43 UTC, xymyeah commented on python/paddle/distributed/fleet/base/topology.py
> +    - DATA_PARALLEL: Distribute input data to different devices.
表述上比较直接，我们自己能看懂这个解释，看看怎样用更通俗的表述，让用户可以理解的真正的意思

2022-04-07 12:43 UTC, xymyeah commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
这里好像没有单独的定义SHARDING_PARALLEL

2022-04-08 08:25 UTC, aoyulong reviewed
LGTM.

2022-04-11 04:07 UTC, chenwhql approved these changes
LGTM  for init

2022-04-11 07:45 UTC, TCChenlong approved these changes

2022-04-12 02:35 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
> 这里好像没有单独的定义SHARDING_PARALLEL



> 这里好像没有单独的定义SHARDING_PARALLEL
这里有单独的SHARDING_PARALLEL

2022-04-12 02:35 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
> 这里好像没有单独的定义SHARDING_PARALLEL



> 这里好像没有单独的定义SHARDING_PARALLEL
这里有单独的SHARDING_PARALLEL

2022-04-12 02:36 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
这里有单独的SHARDING_PARALLEL=3

2022-04-12 02:36 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
这里有单独的SHARDING_PARALLEL=3

2022-04-12 02:37 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - SHARDING_PARALLEL: Segment The model parameters, parameter gradients and optimizer states
> 这里好像没有单独的定义SHARDING_PARALLEL

这里有单独的定义SHARDING_PARALLEL=3

2022-04-12 02:40 UTC, Yanxing-Shi commented on python/paddle/distributed/fleet/base/topology.py
> +    - DATA_PARALLEL: Distribute input data to different devices.
> 表述上比较直接，我们自己能看懂这个解释，看看怎样用更通俗的表述，让用户可以理解的真正的意思

已经用直接的表述各种并行模式，并且对竞品文档进行了对比。

2022-04-12 02:43 UTC, lanxianghit approved these changes

2022-04-12 06:30 UTC, merged