【Hackathon 33】Modified the case where Tensor cannot be used on DCU
PaddlePaddle/Paddle pull request #41695
Opened 2022-04-12 07:47 UTC by ImNoBadBoy

### PR types
【Hackathon 33 曙光算子修复】PR提交
https://github.com/PaddlePaddle/Paddle/issues/40300

### PR changes
 修改了四个文件
- test_trunc_op.py
- test_where_op.py
- test_yolo_box_op.py
- test_zeros_like_op.py

### Describe
- test_trunc_op.py
```python
vim /public/home/acv2h3zdq0/Paddle/build/python/paddle/fluid/tests/unittests/test_trunc_op.py
42         self.check_output()
45         self.check_grad(['X'], 'Out', numeric_grad_delta=1e-5)
```
- test_where_op.py
```python
vim /public/home/acv2h3zdq0/Paddle/build/python/paddle/fluid/tests/unittests/test_where_op.py
251             assert np.array_equal(out.cpu().numpy(), np.where(cond_i, x_i, y_i)) 
269             result = result.cpu().numpy()
270             expect = np.where(cond.cpu(), a.cpu(), b.cpu())
```
- test_yolo_box_op.py
```python

没有修改直接测试通过

```
- test_zeros_like_op.py
```python
 vim /public/home/acv2h3zdq0/Paddle/build/python/paddle/fluid/tests/unittests/test_zeros_like_op.py

73             if core.is_compiled_with_cuda():
 74                 self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(),True)
 75             else:
 76                 self.assertEqual((out.numpy() == np.zeros(shape, dtype)).all(),True)
 

78         if core.is_compiled_with_cuda():
 79             self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(), True)
 80         else:
 81             self.assertEqual((out.numpy() == np.zeros(shape, dtype)).all(), True)

83         if core.is_compiled_with_cuda():
 84             self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(), True)
 85         else:
 86             self.assertEqual((out.numpy() == np.zeros(shape, dtype)).all(), True)
 87         paddle.enable_static()

```

2022-04-12 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=41695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=41695) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=41695) it.</sub>

2022-04-18 03:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_trunc_op.py
> +#   Copyright (c) 021 PaddlePaddle Authors. All Rights Reserved.
这里不需要修改

2022-04-18 03:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_trunc_op.py
> +m __future__ import print_function
请检查一下这里多出的重复代码

2022-04-18 03:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_trunc_op.py
> +import unittest
请检查这里多出的代码，另外请使用pre-commit工具在提交PR前检查一下

2022-04-18 03:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_where_op.py
> +            assert np.array_equal(out.cpu().numpy(), np.where(cond_i, x_i, y_i))
这里直接.numpy()不行吗？

2022-04-18 03:25 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_zeros_like_op.py
> +                self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(),True)
这里直接.numpy()不行吗？

2022-04-24 12:33 UTC, wangjincheng123456 commented on python/paddle/fluid/tests/unittests/test_zeros_like_op.py
> +                self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(),True)
cuda上的数据不能直接使用.numpy()获取数据值

2022-04-25 01:59 UTC, TCChenlong commented
@ImNoBadBoy 可以根据 review 意见修改下~

2022-04-25 13:11 UTC, ImNoBadBoy reviewed
对代码进行了修改，把重复代码进行了删除

2022-04-25 13:13 UTC, ImNoBadBoy reviewed
您好已经按照您的要求进行了修改

2022-04-25 13:13 UTC, ImNoBadBoy commented on python/paddle/fluid/tests/unittests/test_where_op.py
> +            assert np.array_equal(out.cpu().numpy(), np.where(cond_i, x_i, y_i))
cuda上的数据不能直接使用.numpy()获取数据值

2022-04-25 13:17 UTC, ImNoBadBoy commented on python/paddle/fluid/tests/unittests/test_trunc_op.py
> +import unittest
已经删除了

2022-04-26 07:57 UTC, ronny1996 requested changes
cuda上的

2022-04-26 07:57 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_zeros_like_op.py
> +                self.assertEqual((out.cpu().numpy() == np.zeros(shape, dtype)).all(),True)
cuda上的数据应该能拷贝到cpu再转成numpy，这个测试过吗？如果不可以，我再确认下

2022-04-26 07:57 UTC, ronny1996 commented on python/paddle/fluid/tests/unittests/test_where_op.py
> +            assert np.array_equal(out.cpu().numpy(), np.where(cond_i, x_i, y_i))
cuda上的数据应该能拷贝到cpu再转成numpy，这个测试过吗？如果不可以，我再确认下

2022-04-29 09:13 UTC, ImNoBadBoy commented on python/paddle/fluid/tests/unittests/test_where_op.py
> +            assert np.array_equal(out.cpu().numpy(), np.where(cond_i, x_i, y_i))
对的，我们单测通过了

2023-08-29 06:35 UTC, closed without merging