adds the conv bn fusion, test=develop
PaddlePaddle/Paddle pull request #41711
Opened 2022-04-12 11:13 UTC by Shixiaowei02

### PR types

New features
### PR changes

Others
### Describe

adds the conv bn fusion, test=develop

2022-04-12 12:22 UTC, winter-wang requested changes

2022-04-12 12:22 UTC, winter-wang commented on paddle/infrt/dialect/phi/ir/infrt_phi_tensor.cc
> +#include <iostream>
会用到 iostream标准库吗？

2022-04-12 12:22 UTC, winter-wang commented on paddle/infrt/dialect/phi/pass/phi_op_fuse.td
> +include "paddle/infrt/dialect/pd/ir/pd_ops.td"
我觉得这个fuse放到 dialect/pd/pass路径下面更合适吧。因为是paddle dialect的op融合。

2022-04-12 12:27 UTC, Shixiaowei02 commented on paddle/infrt/dialect/phi/pass/phi_op_fuse.td
> +include "paddle/infrt/dialect/pd/ir/pd_ops.td"
有道理👌

2022-04-12 12:27 UTC, Shixiaowei02 commented on paddle/infrt/dialect/phi/ir/infrt_phi_tensor.cc
> +#include <iostream>
调试遗留的代码，我删一下

2022-04-13 08:35 UTC, winter-wang approved these changes, later dismissed
感觉 conv2d_bn_fuse_pass.h和conv2d_bn_fuse_pass.cc的名字是不是稍微修改一下比较好。这两个文件更多的是conv2d_bn_fuse_pass的工具函数。而且感觉相对于pass,  说conv2d_bn_fuse是一个pattern rewriter感觉更合适。 重命名为 conv2d_bn_fuse_utils 怎么样?

2022-04-13 09:10 UTC, Shixiaowei02 commented
> 感觉 conv2d_bn_fuse_pass.h和conv2d_bn_fuse_pass.cc的名字是不是稍微修改一下比较好。这两个文件更多的是conv2d_bn_fuse_pass的工具函数。而且感觉相对于pass, 说conv2d_bn_fuse是一个pattern rewriter感觉更合适。 重命名为 conv2d_bn_fuse_utils 怎么样?

2022-04-13 10:19 UTC, Shixiaowei02 commented
> 感觉 conv2d_bn_fuse_pass.h和conv2d_bn_fuse_pass.cc的名字是不是稍微修改一下比较好。这两个文件更多的是conv2d_bn_fuse_pass的工具函数。而且感觉相对于pass, 说conv2d_bn_fuse是一个pattern rewriter感觉更合适。 重命名为 conv2d_bn_fuse_utils 怎么样?

done

2022-04-13 10:25 UTC, winter-wang approved these changes, later dismissed
LGTM

2022-04-13 13:08 UTC, winter-wang commented on paddle/infrt/dialect/pd/pass/pd_op_fuse.td
>  #endif // INFRT_REWRITE
建议顺手将这个保护符从 INFRT_REWRITE改为PD_OP_FUSE，更顺畅一点。

2022-04-14 02:26 UTC, Shixiaowei02 commented on paddle/infrt/dialect/pd/pass/pd_op_fuse.td
>  #endif // INFRT_REWRITE
可以

2022-04-14 02:51 UTC, winter-wang approved these changes
LGTM

2023-04-14 02:29 UTC, closed without merging