[WIP] exit code 139 (interrupted by signal 11: SIGSEGV) when add sparse op
PaddlePaddle/Paddle pull request #41857
Opened 2022-04-15 10:19 UTC by gsq7474741

### PR types

New features
### PR changes

OPs
### Describe

#41827

2022-04-18 05:43 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    PADDLE_ENFORCE_EQ(x.dims(), y.dims());                                     \
需要给出校验的提示信息。

2022-04-18 05:44 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    const auto& n_col = x.dims()[1];                                           \
当前的SparseCsrTensor支持2-D和3-D的矩阵，所以这里还需要考虑下3-D的输入。

2022-04-18 05:59 UTC, zkh2016 commented on python/paddle/sparse/math.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2020 -> 2022

2022-04-18 07:42 UTC, zkh2016 commented on python/paddle/sparse/math.py
> +            _x = x.to_sparse_csr()
1. 因为当前不支持csr的反向，所以不能够在python层进行转换，可以提供一个coo的api，在c++端进行转换。
2. 另外这里直接转成csr会有问题，SparseCsrTensor只支持2-D和3-D的矩阵，但是SparseCooTensor支持多维的Tensor，非零元素可以是Tensor。这里考虑到确实是csr比较好实现，可以考虑自定以一个转换方法，把这种非零元素是Tensor的coo转换成csr，然后再进行计算。

2022-04-18 07:44 UTC, zkh2016 reviewed
另外建议可以再写下GPU实现。

2022-04-18 08:54 UTC, gsq7474741 commented
> 另外建议可以再写下GPU实现。

好的，GPU的我黑客松之后再提个pr

2022-04-21 02:27 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +#define DEFINE_CSR_ELEMENTWISE_KERNEL(name)                                    \
这里的作用看上去就是替换函数名字合functor的名字，可以试着把计算逻辑单独放一个函数，这个宏里面调用该函数，也可以把functor单参数传递进来。

2022-04-21 02:29 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    const auto* x_crows_data = x.non_zero_crows().data<int64_t>();             \
这里的crows，cols需要支持模板，kernel内可以用二次分发来获取坐标/索引的dtype，可以参考其他计算类kernel的实现。

2022-04-21 06:05 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    const auto* x_crows_data = x.non_zero_crows().data<int64_t>();             \
```
  const auto& csr_crows = x.non_zero_crows();
  const auto& csr_cols = x.non_zero_cols();
  const auto& csr_values = x.non_zero_elements();
  const int64_t* csr_crows_data = csr_crows.data<int64_t>();
  const int64_t* csr_cols_data = csr_cols.data<int64_t>();
```
是指这个写法嘛

2022-04-21 06:11 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    const auto* x_crows_data = x.non_zero_crows().data<int64_t>();             \
[  PD_VISIT_INTEGRAL_TYPES二次分发](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/sparse/cpu/sparse_mask_kernel.cc#L82)

[获取索引信息]https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/sparse/cpu/sparse_mask_kernel.cc#L56

2022-04-21 06:17 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    const auto* x_crows_data = x.non_zero_crows().data<int64_t>();             \
好滴 我看看

2022-04-21 09:05 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    for (int b = 0; b < n_batch; b++) {                                        \
这里的计算逻辑可以加点注释。

2022-04-21 09:07 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  for (int b = 0; b < n_batch; b++) {
这部分看着不少相似代码，可以试着提取出来作为一个函数调用。

2022-04-22 08:25 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    for (int b = 0; b < n_batch; b++) {                                        \
这里的方式是把输入当作无序的？我们当前的SparseCooTensor构造的时候会进行排序和合并重复项，参考[PR#41784](https://github.com/PaddlePaddle/Paddle/pull/41784)，所以这里建议思考下考换种算法实现。

2022-04-26 10:20 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +    for (int b = 0; b < n_batch; b++) {                                        \
已更新

2022-04-26 11:19 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +          if (result != 0) {
这个代码块重复的太多了，可以提取出来。

2022-04-26 11:26 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  for (int i = 0; i < std::max(nnz_x, nnz_y); ++i) {
这里merge的整体逻辑和csr merge一行的逻辑是一样的，可以考虑下把merge的逻辑写成通用的函数。

2022-04-26 11:27 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  if (nnz == 0) {
输出为空的情况？可以试试*out = SparseCoTensor()

2022-04-26 11:33 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +DEFINE_CSR_ELEMENTWISE_KERNEL(Divide)
除法需要把零值考虑进去，这个kernrl貌似并不太适用，可以把merge逻辑扩展下，适配下除法的情况。

2022-04-28 05:14 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  for (int i = 0; i < std::max(nnz_x, nnz_y); ++i) {
已更新

2022-04-28 09:12 UTC, zkh2016 commented on paddle/phi/kernels/funcs/elementwise_functor.h
> +                                              const T* b,
这些functor计算模式都一样，可以考虑只实现一个函数，然后把计算的functor传进来，函数内循环调用functor(a[i], b[i])。
看这里返回vector的目的是后面判断是否为0，可以考虑只返回一个bool is_zero，循环里把functor的计算结果是否为0于is_zero进行或运算，也就是只要有一个不为0就返回的is_zero=false，否则返回的is_zero=true。

2022-04-28 09:12 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  PADDLE_ENFORCE_EQ(x.dims(),
注释和错误信息里说明下，当前只支持相同shape的计算，不支持broadcast的计算

2022-04-28 09:12 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  for (auto j = 1; j < x.non_zero_elements().dims().size(); ++j) {
如果x的shape是[2,3,4,5], 前两维是坐标呢？

2022-04-28 09:12 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  out_indexs.reserve(max_len);
这里的max_len最大等于x.nnz() + y.nnz()吧？

2022-04-28 09:12 UTC, zkh2016 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +        memcpy(
考虑到c_values的空间已经按最大需要分配好，建议直接把c传到merge函数进去直接把计算结果写入到c_values，这里只根据is_zero控制是否++nnz就可以了

2022-04-28 09:53 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +        memcpy(
这里全为0则不写入c

2022-04-28 09:55 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +  out_indexs.reserve(max_len);
这里已修改为在除法时才为max_len

2022-04-28 12:14 UTC, gsq7474741 commented
本PR主体功能已完善，拆解为
- PR 1：#42374 
- PR 2：#42375

进行merge

2022-04-29 03:03 UTC, zkh2016 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +                coo_y = dense_y.to_sparse_coo(2)
非0元素是标量和tensor的都分别测下，另外coo需要测试反向。

2022-04-29 07:31 UTC, zkh2016 submitted a review, later dismissed

2022-04-29 08:21 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +                coo_y = dense_y.to_sparse_coo(2)
好的

2022-04-29 11:14 UTC, TCChenlong commented
请在 Describe 中添加 RFC & 中文文档的链接

2022-04-29 11:17 UTC, TCChenlong commented on python/paddle/sparse/math.py
> +    Add two sparse tensors element-wise. The equation is:
这里的描述和中文保持一致吧，那里的信息比较全
其他几个也是

2022-04-29 11:20 UTC, gsq7474741 commented
> 请在 Describe 中添加 RFC & 中文文档的链接

已贴链接

2022-04-29 13:54 UTC, gsq7474741 commented on python/paddle/sparse/math.py
> +    Add two sparse tensors element-wise. The equation is:
done

2022-04-30 03:15 UTC, zkh2016 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +from operator import __add__, __sub__, __mul__, __truediv__
div的命名为什么和其他的不一样？

2022-04-30 05:28 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +from operator import __add__, __sub__, __mul__, __truediv__
导入这个只是为了能够在计算dense的参照结果时复用op(x, y)这句话而已

![6433a7e91033e5fa1c8ea84bb69cf7c8](https://user-images.githubusercontent.com/38883252/166092634-8e5ff076-c6c1-4233-a108-d42a4e5d9e82.png)

2022-05-05 02:32 UTC, zkh2016 submitted a review, later dismissed

2022-05-05 05:57 UTC, TCChenlong submitted a review, later dismissed
LGTM

2022-05-06 02:59 UTC, DDDivano requested changes

2022-05-06 02:59 UTC, DDDivano commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +        if paddle.device.get_device() == "cpu":
如果只实现了CPU的版本，需要补充一个异常的Case，在GPU下调用该方法需要有一个友好的异常提示说明当前API不支持GPU硬件调用。

2022-05-06 06:17 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +        if paddle.device.get_device() == "cpu":
已更新

2022-05-06 06:18 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +        if paddle.device.get_device() == "cpu":
加在函数本身里面了，后期如果增加GPU版本只需要在测试文件和math.py里删除两个判断即可

2022-05-06 07:56 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sparse_elementwise_op.py
> +        if paddle.device.get_device() == "cpu":
@DDDivano

2022-05-09 01:45 UTC, zkh2016 submitted a review, later dismissed

2022-05-09 01:59 UTC, gsq7474741 commented
已更新 @DDDivano

2022-05-09 07:10 UTC, TCChenlong submitted a review, later dismissed

2022-05-09 07:16 UTC, DDDivano submitted a review, later dismissed

2022-05-10 02:17 UTC, zkh2016 commented on python/paddle/sparse/math.py
> +        x (Tensor): the input tensor, it's data type should be float32, float64.
这里只支持float32和float64？`paddle.add`是支持float32、float64、int32、int64，我看kernel注册的地方是都支持的，这边补充下，另外单测也可以补充下。

2022-05-10 02:17 UTC, gsq7474741 commented on python/paddle/sparse/math.py
> +        x (Tensor): the input tensor, it's data type should be float32, float64.
ok 我改下

2022-05-11 13:32 UTC, gsq7474741 commented on python/paddle/sparse/math.py
> +        x (Tensor): the input tensor, it's data type should be float32, float64.
done

2022-05-13 06:00 UTC, zkh2016 submitted a review, later dismissed

2022-05-13 07:54 UTC, TCChenlong approved these changes, later dismissed

2022-05-18 01:42 UTC, zkh2016 submitted a review, later dismissed

2022-05-18 01:45 UTC, TCChenlong approved these changes, later dismissed

2022-05-18 02:38 UTC, DDDivano approved these changes, later dismissed

2022-05-27 06:10 UTC, zkh2016 submitted a review, later dismissed

2022-05-30 06:33 UTC, TCChenlong submitted a review, later dismissed
LGTM

2022-05-30 09:12 UTC, DDDivano approved these changes, later dismissed

2022-05-30 09:24 UTC, lanxianghit submitted a review, later dismissed

2022-06-14 06:02 UTC, zkh2016 approved these changes

2022-06-14 06:06 UTC, zkh2016 approved these changes, later dismissed

2022-06-14 06:06 UTC, zkh2016 commented on python/setup.py.in
> +          'paddle.incubate.sparse',
这个已经加过了，后面再提个PR去掉下

2022-06-14 06:50 UTC, TCChenlong approved these changes, later dismissed
LGTM

2022-06-14 06:54 UTC, gsq7474741 commented on python/setup.py.in
> +          'paddle.incubate.sparse',
ok

2022-06-14 06:55 UTC, lanxianghit submitted a review, later dismissed

2022-06-14 08:32 UTC, XiaoguangHu01 commented on paddle/phi/kernels/cpu/activation_kernel.cc
> +PD_REGISTER_KERNEL(opposite,
这里是取负号操作吗？这个名字是否是业界普遍的叫法？是否应该叫negative呢

2022-06-14 08:32 UTC, XiaoguangHu01 commented on python/paddle/incubate/sparse/math.py
> +        from paddle.fluid.framework import _test_eager_guard
这里为什么需要调用内部的api呢？默认是imperative模式，这里只在eager模式下才能生效吗？

2022-06-14 08:32 UTC, XiaoguangHu01 commented on python/paddle/utils/code_gen/sparse_bw_api.yaml
> +    func : sparse_elementwise_div_grad_csr{sparse_csr, sparse_csr, sparse_csr -> sparse_csr, sparse_csr}
div_grad -> sub_grad
为什么单测没有发现这个错误呢？请补充一下单测

2022-06-14 08:32 UTC, XiaoguangHu01 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_grad_kernel.cc
> +PD_REGISTER_KERNEL(sparse_elementwise_add_grad_csr,
kenerl的名字命名方式，对齐其他算子sparse_csr_add_grad

2022-06-14 08:32 UTC, XiaoguangHu01 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +PD_REGISTER_KERNEL(sparse_elementwise_sub_coo,
sub 用全称，跟python api的命名一致

2022-06-14 08:42 UTC, zhouwei25 commented
yaml形式规范可以参考下这个PR：https://github.com/PaddlePaddle/Paddle/pull/42935/files#diff-bfad6f19739eb95b60bd46fc6a77adbf3ccb4a5ebac465b7aba845ae15470f11

![infoflow 2022-06-14 16-42-07](https://user-images.githubusercontent.com/52485244/173534197-ba32ffca-6928-4fb5-9480-0b428bb1d253.png)

2022-06-14 08:45 UTC, zkh2016 commented on python/paddle/incubate/sparse/math.py
> +        from paddle.fluid.framework import _test_eager_guard
嗯，当前Sparse只在eager模式下生效。

2022-06-17 08:27 UTC, gsq7474741 commented on paddle/phi/kernels/cpu/activation_kernel.cc
> +PD_REGISTER_KERNEL(opposite,
已修改

2022-06-17 08:28 UTC, gsq7474741 commented on python/paddle/utils/code_gen/sparse_bw_api.yaml
> +    func : sparse_elementwise_div_grad_csr{sparse_csr, sparse_csr, sparse_csr -> sparse_csr, sparse_csr}
刚开始csr不支持反向，所以没测，现已修改

2022-06-17 08:29 UTC, gsq7474741 commented on paddle/phi/kernels/sparse/cpu/sparse_elementwise_kernel.cc
> +PD_REGISTER_KERNEL(sparse_elementwise_sub_coo,
已修改，均已对齐，sub div mul -> subtract divide multiply，感谢指正

2022-06-17 08:31 UTC, gsq7474741 commented
> 你好，yaml形式规范可以参考下这个PR，合并到一起在设计上更好：https://github.com/PaddlePaddle/Paddle/pull/42935/files#diff-bfad6f19739eb95b60bd46fc6a77adbf3ccb4a5ebac465b7aba845ae15470f11
> 
> ![infoflow 2022-06-14 16-42-07](https://user-images.githubusercontent.com/52485244/173534197-ba32ffca-6928-4fb5-9480-0b428bb1d253.png)

好的，已参考该设计修改

2022-06-17 10:17 UTC, zhouwei25 commented
你好，经过内部讨论，目前达成以下一些开发规范要求：

1.【yaml规则】：写到同一个yaml api，不要写多个，yaml需支持调度
2.【kernel名规则】：[计算名] + 异构后缀，matmul、matmul_csr_dense、softmax、softmax_csr
3.【文件名规则】：sparse/xx_kernel.cc，sparse/xx_kernel.cu，以目录区分，文件名与dense一致

辛苦对kenrel注册名、与文件名进行一些修改

2022-06-17 11:17 UTC, gsq7474741 commented
> 你好，经过内部讨论，目前达成以下一些sparse开发规范要求：
> 
> 1.【yaml规则】：写到同一个yaml api，不要写多个，yaml需支持调度 2.【kernel名规则】：[计算名] + 异构后缀，matmul、matmul_csr_dense、softmax、softmax_csr 3.【文件名规则】：sparse/xx_kernel.cc，sparse/xx_kernel.cu，以目录区分，文件名与dense一致
> 
> 辛苦对kenrel注册名、与文件名进行修改

加减乘除要写成四个文件么

2022-06-17 11:42 UTC, zhouwei25 commented
> > 你好，经过内部讨论，目前达成以下一些sparse开发规范要求：
> > 1.【yaml规则】：写到同一个yaml api，不要写多个，yaml需支持调度 2.【kernel名规则】：[计算名] + 异构后缀，matmul、matmul_csr_dense、softmax、softmax_csr 3.【文件名规则】：sparse/xx_kernel.cc，sparse/xx_kernel.cu，以目录区分，文件名与dense一致
> > 辛苦对kenrel注册名、与文件名进行修改
> 
> 加减乘除要写成四个文件么

这里如果复用比较多的话，就合到elementwise_kernel.h/cc/cu，不用sparse前缀

2022-06-17 13:50 UTC, gsq7474741 commented
> > > 你好，经过内部讨论，目前达成以下一些sparse开发规范要求：
> 
> > > 1.【yaml规则】：写到同一个yaml api，不要写多个，yaml需支持调度 2.【kernel名规则】：[计算名] + 异构后缀，matmul、matmul_csr_dense、softmax、softmax_csr 3.【文件名规则】：sparse/xx_kernel.cc，sparse/xx_kernel.cu，以目录区分，文件名与dense一致
> 
> > > 辛苦对kenrel注册名、与文件名进行修改
> 
> > 
> 
> > 加减乘除要写成四个文件么
> 
> 
> 
> 这里复用比较多，就合到elementwise_kernel.h/cc/cu吧，不用sparse前缀

指的是dense的这个文件么

2022-06-17 14:37 UTC, zhwesky2010 commented
就写到sparse/elementwise_kernel.h/cc/cu里吧，文件不用sparse前缀，使用目录区分

2022-06-21 04:43 UTC, zhouwei25 commented on python/paddle/utils/code_gen/sparse_api.yaml
> +    func : add_coo{sparse_coo -> sparse_coo},
这里二元的kernel名是 add_coo_coo，因为后面我们还会补充add_coo_dense的情形

2022-06-21 04:43 UTC, zhouwei25 commented on python/paddle/utils/code_gen/sparse_bw_api.yaml
> +    func : add_grad_coo{sparse_coo, sparse_coo, sparse_coo -> sparse_coo, sparse_coo},
反向kernel名 add_coo_coo_grad

2022-06-21 07:23 UTC, gsq7474741 commented on python/paddle/utils/code_gen/sparse_api.yaml
> +    func : add_coo{sparse_coo -> sparse_coo},
好的

2022-06-23 03:28 UTC, zhouwei25 approved these changes

2022-06-23 08:09 UTC, zkh2016 approved these changes
LGTM

2022-06-23 08:11 UTC, TCChenlong approved these changes
LGTM

2022-06-23 09:15 UTC, chenwhql approved these changes

2022-06-23 09:20 UTC, XiaoguangHu01 approved these changes
LGTM

2022-06-23 10:11 UTC, merged

2022-10-24 08:21 UTC, zhouwei25 commented
@gsq7474741 你好，这个kernel在`FLAGS_use_system_allocator=0`时单测是正确的，在`FLAGS_use_system_allocator=1`时会发生错误，kernel可能有地址访问bug需要修复。

![2fdac3d7babb941612da7827f697cdf3](https://user-images.githubusercontent.com/52485244/197480789-67b10c21-449c-4985-ae99-e29d70ee597b.png)

![586980951007279ae290208c1332e0f2](https://user-images.githubusercontent.com/52485244/197480802-538e11db-2c79-4fe9-8639-896f466de58a.png)