Refine platform::Transform function and fix prelu_op testing.
PaddlePaddle/Paddle pull request #4201
Opened 2017-09-19 15:47 UTC by qingqing01

2017-09-19 16:18 UTC, hedaoyuan approved these changes

2017-09-19 21:26 UTC, jacquesqiao commented on paddle/platform/transform.h
> +template <>
为什么这样改一下就不会有问题了呢

2017-09-19 22:41 UTC, reyoung requested changes
I think this #4209 is much simpler.

2017-09-20 02:13 UTC, qingqing01 commented on paddle/platform/transform.h
> +template <>
@jacquesqiao 改了之后，带了模板参数，对于CPUPlace 、 GPUPlace编译出来是两个不同的符号。

原先那样，在.cu文件里**链接**时，用的是第一次g++/gcc编译同出来的同名符号，就出现问题。

2017-09-20 02:41 UTC, hedaoyuan commented
Such as the [comment in the pr 4209](https://github.com/PaddlePaddle/Paddle/pull/4209/files#r139862597), this code is more efficient after compile.

2017-09-20 05:07 UTC, reyoung approved these changes

2017-09-20 05:37 UTC, merged