Add bool type for attribute and use it in dropout_op.
PaddlePaddle/Paddle pull request #4216
Opened 2017-09-20 05:06 UTC by qingqing01

Fix #4215

2017-09-20 10:18 UTC, lcy-seso commented
这里 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/cross_entropy_op.cc#L39 也需要改掉。不过可以提新的PR。

2017-09-20 17:42 UTC, reyoung requested changes
I do not think bool is needed because it could be simulated by `int`.

2017-09-20 17:43 UTC, reyoung commented on paddle/operators/dropout_op.cc
> -    if (ctx.Attr<int>("is_training") == 1) {
Actually, zero is false, and non-zero is true.

2017-09-20 17:43 UTC, reyoung commented on paddle/operators/dropout_op.cc
> -    AddAttr<int>("is_training", "Whether in training phase.").SetDefault(1);
SetDefault(true)

2017-09-20 18:17 UTC, reyoung commented
Please reference #4239

2017-09-21 04:50 UTC, reyoung submitted a review, later dismissed

2017-09-22 06:11 UTC, lcy-seso approved these changes
LGTM, thank you.

2017-09-22 06:35 UTC, merged