add reader example and update faq
PaddlePaddle/Paddle pull request #4222
Opened 2017-09-20 07:50 UTC by peterzhang2029

resolve #2076

2017-09-20 09:26 UTC, lcy-seso reviewed
Thanks for the work, but please refine the doc.

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +其中，train_reader函数会返回一个reader函数，reader函数是实现训练数据输入的主函数，在这个函数中，实现了打开文本文件，从文本文件中读取每一行，并将每行转换成训练配置文件中需要的格式，然后返回给PaddlePaddle进程。需要注意的是，返回的顺序需要和训练配置中定义的顺序一致。
必须要一致。不一致时通过feeding字典来告诉trainer与data layer的对应关系。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +同时，返回数据在PaddlePaddle中是仅仅返回一条完整的训练样本。 通过使用关键词 yield ， 可以为一个数据文件返回多条训练样本(就像这个样例一样)，只需要在reader函数调用多次 yield 即可。 yield 是Python的一个关键词，相关的概念是 generator 。使用这个关键词，可以在一个函数里，多次返回变量。
- 这一段太口语了，重写。
- 按照reader的设计原理和思想来解释，数据读取接口是一个python的generator，只需要用户实现读取一条数据的逻辑。
- 不要“返回数据在PaddlePaddle中是仅仅返回一条完整的训练样本” 直接就给一个结论，让人分不清楚是这是paddle的限制，还是一种设计，还是可选的。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +对应的数据层可以定义如下：
对应的数据层定义如下：
- 不是可以定义如下，而是就应该这样定义，所以尽量避免不必要的情态动词。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +这里的type表示输入数据的具体格式，详细信息可以查看 `基本实用概念 <../concepts/use_concepts_cn.html>`_ 中的数据类型进行了解。
这里的type表示输入数据的在PaddlePaddle中的类型。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +在训练配置里，可以很方便的设置训练引用这个reader。这个设置为：
- 请修改这句话，尽量不要使用技术不精确的描述，不是“方便地设置训练引用这个reader”，直接描述：reader是train接口的一个参数即可。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +这里feeding是一个字典，定义了数据传入的顺序信息，其中key对应传入数据层的名称，value表示train_reader函数返回的迭代器中的一条样本各部分对应到数据层的位置映射信息。
1. 请解释一下什么时候需要feeding，什么时候不需要。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +----------------------
序列数据的读取

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +这里举例的数据是英文情感分类的数据。数据是给一段英文文本，分类成正面情绪和负面情绪两类(用0和1表示)。样例数据为：
- 整段都太口语化了。
- 这里以英文情感分类数据为例。在情感分类任务中，给定一段输入的文本和文本反映出的情感标签，在这个例子中我们只考虑正面情绪和负面情绪两类，分别用0和1编号。下面是×条示例数据。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +
多余的空行去掉。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +对应的数据读取函数为：
对应的数据读取接口为：

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +和上述的MNIST数据处理有所不同，序列数据需要一个词典来将每个输入的每个token映射为词典的索引。因此，这里的输入特征是词id的序列。对应的数据层的配置如下：
- 不是因为序列数据需要一个词典来做token映射，而是因为输入数据类型变了，不要这样写。

2017-09-20 09:26 UTC, lcy-seso commented on doc/getstarted/data_reader/data_reader.rst
> +最终传入这个变量的方式为：
这个变量是什么？请务必保证在当前上下文语境下指代清晰。

2017-09-21 11:27 UTC, lcy-seso requested changes

2017-09-21 11:27 UTC, lcy-seso commented on doc/faq/index_cn.rst
> +此外还可以通过设置 :code:`flatten_result=False` 之后会去掉“拼接”这个步骤，返回的结果是一个list：
- 当多个层的输出矩阵的高度不一致时（这种情况常常发生在同时输出序列层和非序列层，或是多个输出层处理多个不同长度的序列时），可以在调用infer接口时通过设置  :code:`flatten_result=False`  跳过“拼接”步骤，来解决上面的问题。这时，`infer`接口的返回值是一个python list，

2017-09-21 12:47 UTC, peterzhang2029 commented on doc/faq/index_cn.rst
> +此外还可以通过设置 :code:`flatten_result=False` 之后会去掉“拼接”这个步骤，返回的结果是一个list：
Done

2019-02-01 04:53 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:53 UTC, closed without merging