add federated learning parameter server(fl-ps) mode
PaddlePaddle/Paddle pull request #42682
Opened 2022-05-11 07:09 UTC by ziyoujiyi

### PR types
New features
### PR changes
Others
### Describe
1. add federated learning model 
2. add fl-ps train.py
3. add fl-ps split program pass
4. add fl-ps unittest
5. support N cpus + N cpus
6. test ok

2022-05-23 03:00 UTC, fuyinno4 approved these changes, later dismissed

2022-05-30 02:36 UTC, fuyinno4 approved these changes

2022-05-30 02:41 UTC, fuyinno4 requested changes

2022-05-30 02:41 UTC, fuyinno4 commented on paddle/fluid/framework/data_feed.cc
> +      /*
remove

2022-05-30 02:41 UTC, fuyinno4 commented on python/paddle/distributed/ps/the_one_ps.py
> +            fleet.util.barrier()
check this with guanqun?

2022-05-30 02:41 UTC, fuyinno4 commented on python/paddle/distributed/ps/utils/ps_program_builder.py
> -        logger.info("start building geo-ps program")
check with caibei ?

2022-05-30 03:25 UTC, ziyoujiyi commented on paddle/fluid/framework/data_feed.cc
> +      /*
deleted

2022-05-31 23:53 UTC, zmxdream approved these changes

2022-06-01 02:05 UTC, zmxdream commented on python/paddle/fluid/executor.py
> -                             debug=False,
这块找xinxuan确认下

2022-06-01 02:07 UTC, zmxdream commented on paddle/fluid/framework/heter_pipeline_trainer.cc
> +}  // namespace paddle
不应该去掉

2022-06-01 02:29 UTC, ziyoujiyi commented on python/paddle/fluid/executor.py
> -                             debug=False,
done

2022-06-01 02:29 UTC, ziyoujiyi commented on paddle/fluid/framework/heter_pipeline_trainer.cc
> +}  // namespace paddle
done

2022-06-01 06:16 UTC, fuyinno4 approved these changes

2022-06-01 06:16 UTC, fuyinno4 commented on python/paddle/fluid/executor.py
> +        trainer._set_infer(False)
hardcode？

2022-06-01 06:43 UTC, zhaocaibei123 commented on python/paddle/distributed/ps/the_one_ps.py
> -            self._pull_all_dense(scopes, send_ctx, dense_map)
if xx mode:
    push dense param
    barrier
    pull dense
elif xx1 mode:
    push dense param1
    barrier
    pull dense1
else ...

2022-06-01 07:30 UTC, ziyoujiyi commented on python/paddle/distributed/ps/utils/ps_program_builder.py
> -        logger.info("start building geo-ps program")
done

2022-06-01 07:58 UTC, Ligoml approved these changes

2022-06-01 07:58 UTC, Ligoml commented on python/paddle/fluid/tests/unittests/ps/dataset_generator_A.py
> +#   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Copyright (c) 2022

2022-06-01 07:58 UTC, Ligoml commented on python/paddle/fluid/tests/unittests/ps/dataset_generator_B.py
> +#   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Copyright (c) 2022

2022-06-01 07:58 UTC, Ligoml commented on python/paddle/fluid/tests/unittests/ps/test_fl_ps.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
Copyright (c) 2022

2022-06-02 00:51 UTC, XiaoguangHu01 approved these changes
LGTM

2022-06-02 04:46 UTC, merged