Add ECCL in Paddle
PaddlePaddle/Paddle pull request #42831
Opened 2022-05-18 01:18 UTC by kanghui0204

### PR types

### PR changes

### Describe

2022-05-18 01:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=42831) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=42831) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=42831) it.</sub>

2022-05-18 06:48 UTC, sandyhouse requested changes
Please refer to init_parallel_env and _new_process_group_impl python functions to add your backend to enable eccl.

2022-05-19 05:59 UTC, kanghui0204 commented
> 

i have add in python api ，please check it！

2022-05-19 06:02 UTC, sandyhouse approved these changes, later dismissed
LGTM

2024-09-03 06:33 UTC, closed without merging