[XPUPS] modify BKCL comm op register
PaddlePaddle/Paddle pull request #43028
Opened 2022-05-26 13:16 UTC by WorgenZhang

### PR types
Bug fixes

### PR changes
OPs

### Describe
1. modify BKCL comm op register
   a. c_sync_calc_stream_op
   b. c_sync_comm_stream_op
   c. c_allreduce_sum_op

2. adapt BKCL initialization
  a. c_commit_all_op add bkcl_init_rank with pthread and then AssignBKCLComm for each device
  b. cancel insert any comm ops when device number is 1

2022-05-30 02:26 UTC, zhhsplendid commented on paddle/fluid/operators/collective/c_sync_calc_stream_op.h
> +/* Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
2019 -> 2022

2022-05-30 02:26 UTC, zhhsplendid commented on paddle/fluid/operators/collective/c_sync_comm_stream_op.h
> +/* Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
2019 -> 2022

2022-05-30 12:28 UTC, tiancaitzp requested changes

2022-05-30 12:28 UTC, tiancaitzp commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +      GM2LM(local_src[i] + k * hidden, local_slot_grads,
178-179行之间要加mfence

2022-05-30 12:28 UTC, tiancaitzp commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +      LM2GM(local_dest_vals, local_dest[i] + k * hidden,
mfence

2022-05-30 12:28 UTC, tiancaitzp commented on paddle/fluid/framework/fleet/heter_ps/heter_comm_kernel.kps
> +#include "xpu/kernel/debug.h"  // NOLINT
这个头文件可以去掉

2022-05-30 12:28 UTC, tiancaitzp commented on paddle/fluid/framework/fleet/heter_ps/heter_comm_kernel.kps
>    // to be optimized: call LM2GM too frequently
112，113行的mfence

2022-05-30 12:28 UTC, tiancaitzp commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +  GM2LM(keys, local_keys,
local_keys既然是__global_ptr__ 这里又拿它当GM2LM的dest，这里会不会有问题？

2022-05-31 05:52 UTC, WorgenZhang commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +  GM2LM(keys, local_keys,
> local_keys既然是__global_ptr__ 这里又拿它当GM2LM的dest，这里会不会有问题？

这块比较绕，就相当于在LM上通过索引方式拿到第n个slot的地址，再通过GM2LM把实际的keys的拷贝到LM上

2022-06-02 03:37 UTC, WorgenZhang commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +      GM2LM(local_src[i] + k * hidden, local_slot_grads,
> 178-179行之间要加mfence

done, mfence相关添加在另一个PR

2022-06-02 03:37 UTC, WorgenZhang commented on paddle/fluid/framework/fleet/ps_gpu_wrapper.kps
> +      LM2GM(local_dest_vals, local_dest[i] + k * hidden,
> mfence

done, mfence相关添加在另一个PR

2022-06-02 03:38 UTC, WorgenZhang commented on paddle/fluid/framework/fleet/heter_ps/heter_comm_kernel.kps
> +#include "xpu/kernel/debug.h"  // NOLINT
> 这个头文件可以去掉

暂不去掉，可支持printf打印

2022-06-02 03:38 UTC, WorgenZhang commented on paddle/fluid/framework/fleet/heter_ps/heter_comm_kernel.kps
>    // to be optimized: call LM2GM too frequently
> 112，113行的mfence

done, mfence相关添加在另一个PR

2022-06-02 03:39 UTC, WorgenZhang commented on paddle/fluid/operators/collective/c_sync_comm_stream_op.h
> +/* Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
done

2022-06-02 03:40 UTC, WorgenZhang commented on paddle/fluid/operators/collective/c_sync_calc_stream_op.h
> +/* Copyright (c) 2019 PaddlePaddle Authors. All Rights Reserved.
> 2019 -> 2022

暂时保留2019，因为改成2022后需要手动解决conflict冲突，重新commit后会强制merge最新develop分支，目前xpups合入develop分支后无法运行

2022-06-02 03:41 UTC, Thunderbrook approved these changes

2022-06-02 07:03 UTC, zhhsplendid approved these changes
经沟通，BKCL通信同步op，只是做了Wait操作，跟数据类型无关，可以注册double相关kernel，LGTM for CI数据类型检查。

2022-06-02 07:54 UTC, Thunderbrook approved these changes

2022-06-02 07:54 UTC, merged