[MLU]add mlu kernel for clip
PaddlePaddle/Paddle pull request #43229
Opened 2022-06-06 08:05 UTC by Ashelly1

### PR types

New features 

### PR changes

OPs

### Describe

add mlu kernel for clip

2022-06-07 07:30 UTC, Ashelly1 commented
clip:
![image](https://user-images.githubusercontent.com/22099158/172321842-555a9670-2789-4135-8050-f23901cf3729.png)

2022-06-09 03:16 UTC, ShawnNew requested changes

2022-06-09 03:16 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_clip_op_mlu.py
> +
需要覆盖一下已经注册的half和int32的kernel测试

2022-06-09 06:25 UTC, Ashelly1 commented on python/paddle/fluid/tests/unittests/mlu/test_clip_op_mlu.py
> +
已增加half的kernel测试

2022-06-10 05:47 UTC, ShawnNew approved these changes
👍

2022-06-10 06:16 UTC, Ivorfeng commented
👍

2022-06-10 11:04 UTC, qili93 approved these changes
LGTM

2022-06-10 11:05 UTC, merged