[MLU]add mlu kernel for scatter op
PaddlePaddle/Paddle pull request #43292
Opened 2022-06-07 12:36 UTC by fuyou765

### PR types
New features

### PR changes
OPs 

### Describe
添加 scatter 算子的mlu kernel及对应pytest

2022-06-08 06:33 UTC, fuyou765 commented
scatter:
<img width="787" alt="scatter" src="https://user-images.githubusercontent.com/64373205/172547954-e25a495b-af45-4ab2-b6b3-a0aea6494643.png">

2022-06-08 07:25 UTC, ShawnNew requested changes

2022-06-08 07:25 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +        self.places = [fluid.CPUPlace()]
这个量后面有影响吗？

2022-06-08 07:25 UTC, ShawnNew commented on paddle/fluid/operators/scatter_op_mlu.cc
> +                       ops::ScatterMLUKernel<int64_t>,
这个模板参数不太对，检查下cnnl文档

2022-06-09 02:45 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +        self.places = [fluid.CPUPlace()]
已修改为paddle.device.MLUPlace(0)

2022-06-09 02:45 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +        self.places = [fluid.CPUPlace()]
已修改为paddle.device.MLUPlace(0)

2022-06-09 02:45 UTC, fuyou765 commented on paddle/fluid/operators/scatter_op_mlu.cc
> +                       ops::ScatterMLUKernel<int64_t>,
已修改

2022-06-09 02:45 UTC, fuyou765 commented on paddle/fluid/operators/scatter_op_mlu.cc
> +                       ops::ScatterMLUKernel<int64_t>,
已修改

2022-06-09 02:52 UTC, ShawnNew requested changes

2022-06-09 02:52 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +            input = fluid.data(name="input", shape=[3, 2], dtype="float64")
这个数据类型好像不ok吧？

2022-06-09 02:52 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                gpu_out = paddle.scatter(paddle.to_tensor(x),
gpu -> mlu

2022-06-09 02:52 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                return gpu_out.numpy()
same

2022-06-09 02:52 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                gpu_exe = paddle.static.Executor(paddle.device.MLUPlace(0))
same

2022-06-09 02:52 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                return gpu_value
same

2022-06-09 03:37 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +            input = fluid.data(name="input", shape=[3, 2], dtype="float64")
已修改

2022-06-09 03:37 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                gpu_out = paddle.scatter(paddle.to_tensor(x),
已修改

2022-06-09 03:37 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                return gpu_out.numpy()
已修改

2022-06-10 05:37 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                gpu_exe = paddle.static.Executor(paddle.device.MLUPlace(0))
已修改

2022-06-10 05:37 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_scatter_op_mlu.py
> +                return gpu_value
已修改

2022-06-10 08:19 UTC, ShawnNew approved these changes
👍

2022-06-10 11:05 UTC, qili93 approved these changes
LGTM

2022-06-10 11:05 UTC, merged