[MLU]: add shape kernel
PaddlePaddle/Paddle pull request #43347
Opened 2022-06-09 06:12 UTC by zhaoying9105

### PR types

New features 
### PR changes

OPs 
### Describe

add MLU shape kernel

2022-06-09 06:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=43347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=43347) before we can accept your contribution.<br/><hr/>**zhaoying** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=43347) it.</sub>

2022-06-09 06:39 UTC, zhaoying9105 commented
测试报告
![图片](https://user-images.githubusercontent.com/15980746/172781099-6bb4c0dd-27ff-4c44-a967-21f853cc9ae0.png)
![shape](https://user-images.githubusercontent.com/15980746/172781130-efd6e62a-b09c-4eb3-86ae-206c67d5f619.png)

2022-06-13 05:58 UTC, ShawnNew requested changes

2022-06-13 05:58 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
npu -> mlu

2022-06-13 05:58 UTC, ShawnNew commented on paddle/fluid/operators/shape_op_mlu.cc
> +    auto out_data = out_t->mutable_data<int32_t>(platform::CPUPlace());
这里默认都是cpu吗？

2022-06-13 06:06 UTC, Ivorfeng commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
set_npu改为set_mlu比较合适

2022-06-13 06:06 UTC, Ivorfeng commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
set_npu改为set_mlu比较合适

2022-06-13 10:31 UTC, zhaoying9105 commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
已修改

2022-06-13 10:31 UTC, zhaoying9105 commented on paddle/fluid/operators/shape_op_mlu.cc
> +    auto out_data = out_t->mutable_data<int32_t>(platform::CPUPlace());
copy到MLU上了

2022-06-13 10:31 UTC, zhaoying9105 commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
已修改

2022-06-13 10:31 UTC, zhaoying9105 commented on python/paddle/fluid/tests/unittests/mlu/test_shape_op_mlu.py
> +        self.set_npu()
已修改

2022-06-14 06:39 UTC, ShawnNew approved these changes
👍

2022-06-14 11:50 UTC, qili93 approved these changes
LGTM

2022-06-17 09:45 UTC, merged