[MLU]add mlu kernal for expand_v2 op
PaddlePaddle/Paddle pull request #43353
Opened 2022-06-09 06:42 UTC by fuyou765

### PR types
 New features 

### PR changes
OPs

### Describe
添加 expand_v2 算子的mlu kernel及对应pytest

2022-06-09 06:42 UTC, fuyou765 commented
expand_v2:
<img width="749" alt="expand" src="https://user-images.githubusercontent.com/64373205/172781736-e111418c-2528-483b-b00d-a17f67cf045f.png">

2022-06-14 03:31 UTC, ShawnNew requested changes

2022-06-14 03:31 UTC, ShawnNew commented on paddle/fluid/operators/expand_v2_op_mlu.cc
> +    auto* Out = ctx.Output<framework::Tensor>("Out");
参考下其他设备，看看如何获取out的形状

2022-06-14 06:04 UTC, fuyou765 commented on paddle/fluid/operators/expand_v2_op_mlu.cc
> +    auto* Out = ctx.Output<framework::Tensor>("Out");
已参考xpu添加对shape的检查代码

2022-06-14 06:52 UTC, ShawnNew approved these changes, later dismissed
👍

2022-06-17 09:53 UTC, qili93 approved these changes
LGTM

2022-06-17 09:53 UTC, merged