add mlu expand_as_v2 kernel
PaddlePaddle/Paddle pull request #43393
Opened 2022-06-10 05:52 UTC by cifar10

### PR types
New features

### PR changes
OPs

### Describe
add expand_as_v2 kernel forward

2022-06-10 05:59 UTC, cifar10 commented
expand_as_v2

![expand_as_v2](https://user-images.githubusercontent.com/41565156/173000327-73e815f0-ac05-495d-978c-43ac6ffcd530.jpg)

2022-06-13 06:43 UTC, ShawnNew requested changes

2022-06-13 06:43 UTC, ShawnNew commented on paddle/fluid/operators/expand_as_v2_op_mlu.cc
> +    out0->mutable_data<T>(context.GetPlace());
这个模板好像没有传进来？

2022-06-13 07:12 UTC, Ivorfeng commented on paddle/fluid/operators/expand_as_v2_op_mlu.cc
> +REGISTER_OP_MLU_KERNEL(expand_as_v2, ops::ExpandAsV2MLUKernel<float>,
类型注册，增加支持bool

2022-06-13 09:20 UTC, Ivorfeng commented
👍

2022-06-13 09:24 UTC, cifar10 commented on paddle/fluid/operators/expand_as_v2_op_mlu.cc
> +REGISTER_OP_MLU_KERNEL(expand_as_v2, ops::ExpandAsV2MLUKernel<float>,
已修改

2022-06-14 06:57 UTC, ShawnNew approved these changes
👍

2022-06-14 11:51 UTC, qili93 approved these changes
LGTM

2022-06-21 06:58 UTC, merged