add mlu stack kernel
PaddlePaddle/Paddle pull request #43423
Opened 2022-06-11 07:15 UTC by cifar10

### PR types
New features

### PR changes
OPs

### Describe
add stack forward

2022-06-11 07:17 UTC, cifar10 commented
![stack](https://user-images.githubusercontent.com/41565156/173177796-9c75682c-3bc2-432e-a433-02aa0904389b.jpg)

2022-06-15 06:35 UTC, ShawnNew requested changes

2022-06-15 06:35 UTC, ShawnNew commented on paddle/fluid/operators/stack_op_mlu.cc
> +      if (x[i]->dims().size() != 0) {
感觉这块逻辑只需要把所有input的dims组成vector就好？

2022-06-15 09:10 UTC, ShawnNew approved these changes
👍

2022-06-16 01:52 UTC, Ivorfeng commented
👍

2022-06-21 06:57 UTC, qili93 approved these changes
LGTM

2022-06-21 06:58 UTC, merged