[MLU]add mlu kernal for where op
PaddlePaddle/Paddle pull request #43441
Opened 2022-06-13 07:20 UTC by fuyou765

### PR types
New features

### PR changes
OPs 

### Describe
添加 where 算子的mlu kernel及对应pytest

2022-06-13 07:20 UTC, fuyou765 commented
where:
<img width="785" alt="where" src="https://user-images.githubusercontent.com/64373205/173300507-d984030a-fb93-4a55-8dd6-b8ff454c4128.png">

2022-06-15 07:03 UTC, Ivorfeng commented on paddle/fluid/operators/where_op_mlu.cc
> +    ops::WhereMLUKernel<paddle::platform::MLUDeviceContext, int>,
注册函数结尾少了);

2022-06-15 07:03 UTC, Ivorfeng commented on python/paddle/fluid/tests/unittests/mlu/test_where_op_mlu.py
> +        self.x = np.random.uniform((-3), 5, (20, 2, 4)).astype('float64')
目前不支持double 类型，可以把对应测例删掉，下同

2022-06-15 08:03 UTC, fuyou765 commented on paddle/fluid/operators/where_op_mlu.cc
> +    ops::WhereMLUKernel<paddle::platform::MLUDeviceContext, int>,
已修改

2022-06-15 08:03 UTC, fuyou765 commented on python/paddle/fluid/tests/unittests/mlu/test_where_op_mlu.py
> +        self.x = np.random.uniform((-3), 5, (20, 2, 4)).astype('float64')
已改为float32

2022-06-15 09:23 UTC, ShawnNew requested changes

2022-06-15 09:23 UTC, ShawnNew commented on paddle/fluid/operators/where_op_mlu.cc
> +    ops::WhereMLUKernel<paddle::platform::MLUDeviceContext, int>)
syntax

2022-06-16 03:10 UTC, fuyou765 commented on paddle/fluid/operators/where_op_mlu.cc
> +    ops::WhereMLUKernel<paddle::platform::MLUDeviceContext, int>)
已修改

2022-06-16 03:14 UTC, fuyou765 commented on paddle/fluid/operators/where_op_mlu.cc
> +    ops::WhereMLUKernel<paddle::platform::MLUDeviceContext, int>)
已修改

2022-06-17 09:53 UTC, qili93 approved these changes
LGTM

2022-06-17 09:53 UTC, merged