Re-write the unit tests for compare xpu op
PaddlePaddle/Paddle pull request #43460
Opened 2022-06-13 09:59 UTC by runzhech

### PR types
Others

### PR changes
Others

### Describe
Re-write the unit tests for XPU's compare ops like less_than, greater_equal.

2022-06-30 09:09 UTC, XiaociZhang requested changes
测试用例太少，建议增加到5个以上

2022-06-30 09:11 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
> +            # np.random.rand
注释去掉

2022-06-30 09:12 UTC, XiaociZhang commented on python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
> +            self.inputs = {'X': input_x, 'Y': input_y}
self.inputs和self.outputs的定义写到基类里

2022-07-01 02:13 UTC, ykkk2333 approved these changes
LGTM

2022-07-01 02:13 UTC, ykkk2333 commented on python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
> +            self.op_type = 'less_than'
optype是不是可以写进init里

2022-07-01 02:26 UTC, runzhech commented on python/paddle/fluid/tests/unittests/xpu/test_compare_op_xpu.py
> +            self.op_type = 'less_than'
试了一下好像不行，XXXOpTestCase作为内部类没有继承外部类的成员，把op_type写到init里面之后，生成测试用例时获取不到op_type这个成员

2022-07-01 02:28 UTC, XiaociZhang reviewed
lgtm

2022-07-01 02:29 UTC, XiaociZhang approved these changes
lgtm

2022-07-01 04:07 UTC, QingshuChen approved these changes

2022-07-01 04:16 UTC, merged