record memory and op supplement info
PaddlePaddle/Paddle pull request #43550
Opened 2022-06-15 10:03 UTC by rainyfly

### PR types

Others
### PR changes

Others
### Describe

1. 采集memory的分配信息。
2. 采集静态图下input shape , input types 和callstack的信息。

2022-06-16 06:25 UTC, liutiexing requested changes

2022-06-16 06:25 UTC, liutiexing commented on paddle/fluid/platform/profiler/host_event_recorder.h
> +#include <stack>
删掉吧

2022-06-16 10:56 UTC, liutiexing submitted a review, later dismissed

2022-06-21 06:33 UTC, From00 commented on paddle/fluid/memory/allocation/pinned_allocator.cc
> +  platform::RecordMemEvent(allocation->ptr(), allocation->place(),
Should pass _CPUPlace_ here? Better to handle _GPUPinnedPlace_ in the implement of _RecordMemEvent_.

2022-06-21 06:33 UTC, From00 commented on paddle/fluid/memory/allocation/stat_allocator.h
> +    platform::RecordMemEvent(allocation->ptr(), allocation->place(),
The same problem as above to handle _GPUPinnedPlace_

2022-06-21 06:33 UTC, From00 commented on paddle/fluid/platform/profiler.cc
> +  if (g_state == ProfilerState::kDisabled &&
Better to keep consistent of the curly braces  requirement in _if_ statement. Since elsewhere you add a curly brace for _if_ even though the statement is brief, better to add here.

2022-06-21 06:57 UTC, rainyfly commented on paddle/fluid/memory/allocation/pinned_allocator.cc
> +  platform::RecordMemEvent(allocation->ptr(), allocation->place(),
Done

2022-06-21 06:57 UTC, rainyfly commented on paddle/fluid/memory/allocation/stat_allocator.h
> +    platform::RecordMemEvent(allocation->ptr(), allocation->place(),
Done

2022-06-21 06:57 UTC, rainyfly commented on paddle/fluid/platform/profiler.cc
> +  if (g_state == ProfilerState::kDisabled &&
Done

2022-06-23 09:43 UTC, From00 approved these changes
LGTM

2022-06-23 12:42 UTC, zhiqiu approved these changes
LGTM

2022-06-23 13:44 UTC, lanxianghit approved these changes

2022-06-24 02:18 UTC, XiaoguangHu01 approved these changes
LGTM

2022-06-24 02:35 UTC, merged