[MLU]add mlu kernel for where_index op
PaddlePaddle/Paddle pull request #43720
Opened 2022-06-21 09:18 UTC by fuyou765

### PR types
 New features 

### PR changes
 OPs

### Describe
添加 where_index 算子的mlu kernel及对应pytest

2022-06-21 09:27 UTC, fuyou765 commented
where_index:
<img width="780" alt="where_index" src="https://user-images.githubusercontent.com/64373205/174766445-c38d1f26-a50c-4904-9969-be5bb27f2405.png">

2022-06-21 09:45 UTC, ShawnNew requested changes

2022-06-21 09:45 UTC, ShawnNew commented on paddle/fluid/operators/where_index_op_mlu.cc
> +    out->mutable_data<int>(context.GetPlace());
out的dtype在算子定义的时候是int64，得处理一下

2022-06-22 03:22 UTC, fuyou765 commented on paddle/fluid/operators/where_index_op_mlu.cc
> +    out->mutable_data<int>(context.GetPlace());
cnnl 只支持int32

2022-06-22 03:27 UTC, Ivorfeng commented on paddle/fluid/operators/where_index_op_mlu.cc
> +    out->mutable_data<int>(context.GetPlace());
cnnl执行的按int32 ，执行完再cast回int64

2022-06-22 03:30 UTC, ShawnNew commented on paddle/fluid/operators/where_index_op_mlu.cc
> +    out->mutable_data<int>(context.GetPlace());
参考一下德明的算子，[arg_max](https://github.com/PaddlePaddle/Paddle/pull/43624/files#diff-80898311dac0de3dc494fac1fcc649c158fab78463157d9fa17852fd162b02dcR95)，注意一下paddle op定义的类型哈。

2022-06-23 13:06 UTC, fuyou765 commented on paddle/fluid/operators/where_index_op_mlu.cc
> +    out->mutable_data<int>(context.GetPlace());
已修改

2022-06-28 03:35 UTC, qili93 approved these changes
LGTM

2022-06-28 08:39 UTC, merged