[MLU] add mlu kernel for masked_select
PaddlePaddle/Paddle pull request #43816
Opened 2022-06-24 05:57 UTC by Ashelly1

### PR types

New features 
### PR changes

OPs
### Describe

add mlu kernel for masked_select

2022-06-24 06:59 UTC, Ashelly1 reviewed
fix confilct

2022-06-27 02:24 UTC, Ashelly1 commented
maked_select op:
![image](https://user-images.githubusercontent.com/22099158/175846417-e4eef1e4-beae-4659-ac94-c480c6daf840.png)
masked_select_grad op:
![image](https://user-images.githubusercontent.com/22099158/175848343-5ac2e1e6-5d72-423b-9142-d016ab608fb5.png)

2022-06-28 02:14 UTC, Ivorfeng commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +                       ops::MaskedSelectedMLUKernel<plat::float16>);
类型加上int32

2022-06-28 02:14 UTC, Ivorfeng commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +    y_grad_tmp.ShareDataWith(*y_grad);
y_grad_tmp 看下是否可以删除，直接用y_grad

2022-06-28 02:14 UTC, Ivorfeng commented on python/paddle/fluid/tests/unittests/mlu/test_masked_select_op_mlu.py
> +class TestMaskedSelectOp2(TestMaskedSelectOp):
添加fp16&int32 类型测例

2022-06-28 08:05 UTC, Ashelly1 commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +                       ops::MaskedSelectedMLUKernel<plat::float16>);
已添加

2022-06-28 08:06 UTC, Ashelly1 commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +    y_grad_tmp.ShareDataWith(*y_grad);
已删除y_grad_tmp，并直接用y_grad

2022-06-28 08:07 UTC, Ashelly1 commented on python/paddle/fluid/tests/unittests/mlu/test_masked_select_op_mlu.py
> +class TestMaskedSelectOp2(TestMaskedSelectOp):
已添加fp16&int32 类型测例

2022-06-28 09:55 UTC, ShawnNew requested changes

2022-06-28 09:55 UTC, ShawnNew commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +/* static */ void MLUCnnl::MaskSelected(
建议直接取名Mask，因为select是mask的一个模式，mask应该是一个更广泛的概念。

2022-06-28 09:55 UTC, ShawnNew commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +                          static_cast<uint32_t*>(number_ptr));
nullptr应该就ok

2022-06-28 11:38 UTC, Ashelly1 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +/* static */ void MLUCnnl::MaskSelected(
已更改为Mask

2022-06-28 11:42 UTC, Ashelly1 commented on paddle/fluid/operators/masked_select_op_mlu.cc
> +                          static_cast<uint32_t*>(number_ptr));
这里的Mask为select模式，输出number 不能为空，且需为mlu地址

2022-06-29 02:34 UTC, ShawnNew submitted a review, later dismissed
👍

2022-06-30 09:44 UTC, qili93 approved these changes
LGTM

2022-06-30 10:40 UTC, merged