【Fix en docs】 Fix document formatting
PaddlePaddle/Paddle pull request #43996
Opened 2022-07-01 02:50 UTC by ReganYue

### PR types

Others
### PR changes

Docs
### Describe

【Fix en docs】 Fix document formatting
· Returns
· Return Type

2022-07-22 11:42 UTC, SigureMo commented
emmmm，CI 里有不少 fluid API 的示例代码挂掉了，这些 fluid API 是修复任务里的吗？

2022-07-23 02:07 UTC, ReganYue commented
> emmmm，CI 里有不少 fluid API 的示例代码挂掉了，这些 fluid API 是修复任务里的吗？

是我全量搜索然后进行修改的，是的，示例代码挂掉了 ^ ^

2022-07-23 05:24 UTC, SigureMo commented
我看了下，有 20 个示例代码错误，全是 fluid 的，fluid 的 API 还有必要修复吗 @Ligoml

2022-07-23 05:35 UTC, SigureMo commented
@ReganYue 梦柳刚刚说「fluid下的API不用管」，要不辛苦恢复一下？

2022-07-23 07:03 UTC, SigureMo requested changes

2022-07-23 07:03 UTC, SigureMo commented on python/paddle/nn/functional/common.py
> +        Tensor，padded with 0 according to pad and data type is same as input.
```suggestion
        Tensor, padded with 0 according to pad and data type is same as input.
```

这里是个全角逗号 :joy:

2022-07-23 07:03 UTC, SigureMo commented on python/paddle/nn/functional/loss.py
> +        Tensor, if :attr:`reduction` is ``'mean'`` or ``'sum'``, the out shape is :math:`[1]`, otherwise the shape is the same as `input` .The same dtype as input tensor.
emmm，这行有点长，最好折断下。

还有上面那个参数 `reduction` 那行，也太长了，非常影响阅读体验……可以参考其他几个函数折断下（目测都是一样的，可以直接 copy）

2022-07-24 13:59 UTC, ReganYue commented on python/paddle/nn/functional/common.py
> +        Tensor，padded with 0 according to pad and data type is same as input.
收到

2022-07-24 13:59 UTC, ReganYue commented on python/paddle/nn/functional/loss.py
> +        Tensor, if :attr:`reduction` is ``'mean'`` or ``'sum'``, the out shape is :math:`[1]`, otherwise the shape is the same as `input` .The same dtype as input tensor.
嗯嗯嗯

2022-07-24 14:08 UTC, SigureMo commented
<img width="670" alt="image" src="https://user-images.githubusercontent.com/38436475/180650831-b691d811-5a5e-49f3-92d1-4b10b0377084.png">

看来偏离主线太久了，需要重新 merge 下主线了

2022-07-24 15:09 UTC, ReganYue commented
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/38436475/180650831-b691d811-5a5e-49f3-92d1-4b10b0377084.png">
> 
> 看来偏离主线太久了，需要重新 merge 下主线了

merge了

2022-07-26 09:10 UTC, momozi1996 approved these changes, later dismissed
LGTM

2022-07-29 06:59 UTC, Ligoml commented on python/paddle/fluid/io.py
> +    Return Type:
文档中不需要写Return Type的哈，英文文档的Return Type是从Returns:中解析出来的，建议改成

```
Returns:
    list: The fetch variables' name list.
```

2022-07-29 06:59 UTC, Ligoml commented on python/paddle/fluid/io.py
> +    Return Type:
另外 Raises: 删掉

2022-07-29 08:02 UTC, Ligoml commented
> @ReganYue 梦柳刚刚说「fluid下的API不用管」（微信上回复我的 😂），要不辛苦恢复一下？

我指的是paddle.fluid目录下的API哈，不是说放在fluid文件下的，比如 save_inference_model 调用路径是 paddle.static.save_inference_model，那这个API就是需要修改的~

2022-07-29 10:04 UTC, Ligoml commented on python/paddle/fluid/io.py
> +        list, The fetch variables' name list
注意句尾标点符号

2022-07-29 10:04 UTC, Ligoml commented on python/paddle/fluid/layers/nn.py
>      Raises:
Raises全部删掉

2022-08-01 06:00 UTC, Ligoml commented on python/paddle/fluid/io.py
>                                        Default: False.
<img width="881" alt="image" src="https://user-images.githubusercontent.com/39876205/182079878-29e30936-0058-4836-a1f8-c4e4a866a26e.png">
这里的参数描述显示有问题

2022-08-01 06:00 UTC, Ligoml commented on python/paddle/fluid/io.py
>                                        Default: False.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/39876205/182079957-b45ea0d7-1530-4537-9dce-584b4acb4874.png">
另外中文和英文不太一致？

2022-08-01 06:00 UTC, Ligoml commented on python/paddle/fluid/layers/nn.py
>              None by default.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/39876205/182080191-dec23eb3-415a-4389-80ac-4cd2e4ee2910.png">
shape应该是可选参数吧？另外paddle.crop的中文文档可能也有点问题？

2022-08-01 06:00 UTC, Ligoml commented on python/paddle/fluid/layers/sequence_lod.py
>              to :ref:`api_guide_Name`. Usually name is no need to set and \
参考API文档页面，有些部分需要修正：https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/sequence_expand_en.html

例如这里可以写成一个notes
<img width="480" alt="image" src="https://user-images.githubusercontent.com/39876205/182081366-5b2865c1-9615-49e7-bd9e-16e05c527a6c.png">

这里的return type记得删掉
<img width="902" alt="image" src="https://user-images.githubusercontent.com/39876205/182081466-17995700-a6c9-4d6e-8716-970208f65343.png">

这个删掉
<img width="143" alt="image" src="https://user-images.githubusercontent.com/39876205/182082010-55440982-4f90-4422-8250-b9cb8b41233c.png">

2022-08-01 06:00 UTC, Ligoml commented on python/paddle/fluid/layers/sequence_lod.py
>              to :ref:`api_guide_Name`. Usually name is no need to set and \
sequence_expand_as 同 sequence_expand

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/fluid/layers/sequence_lod.py
> -    Return Type: Tensor
LGTM for paddle.nn.functional.sequence_mask

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/common.py
> +        Tensor, The tensor corresponding to the sliding local blocks.
把api描述中的this op去掉吧，中英文一起去掉

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/common.py
> -    Returns: a Tensor padded according to pad and mode and data type is same as input.
paddle.nn.functional.pad 需要增加参数是否可选的描述，删掉该OP的描述（both 中英文文档）

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/common.py
> +        Tensor, padded with 0 according to pad and data type is same as input.
paddle.nn.functional.zeropad2d 需要增加参数是否可选的描述，删掉该OP的描述（中文文档）

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/common.py
> +        Tensor, a Tensor representing cosine similarity between x1 and x2 along axis.
paddle.nn.functional.cosine_similarity 需要增加参数是否可选的描述，删掉该OP的描述（中文文档）
示例代码需要修改，不需要引入numpy

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/extension.py
> +            Tensor, The output sequence mask. Tensor with shape [d_1, d_2, ..., d_n, maxlen] \
LGTM for paddle.nn.functional.sequence_mask

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +        Tensor, The tensor storing the element-wise squared error \
<img width="494" alt="image" src="https://user-images.githubusercontent.com/39876205/182113934-3c8781ab-e884-41db-ab0c-0a45d7dc84bd.png">
还是不太对？
另外删掉 this op（both 中英文）

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/extension.py
> +            Tensor, The output sequence mask. Tensor with shape [d_1, d_2, ..., d_n, maxlen] \
<img width="712" alt="image" src="https://user-images.githubusercontent.com/39876205/182114260-f9974f78-24d9-47e4-aa48-a3590570bc78.png">
同square_error_cost，可能格式还需要调一下

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +        Tensor, The tensor variable storing the smooth_l1_loss of input and label.
paddle.nn.functional.smooth_l1_loss 需要删掉 this operator（both 中英文）

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
<img width="853" alt="image" src="https://user-images.githubusercontent.com/39876205/182115363-ffbd7200-aea1-4513-b834-8017ff5a0098.png">

中文部分需要改下哦
顺便需要删掉 this op（both 中英文）

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
> +        Tensor, The tensor tensor storing the mean square error difference of input and label.
paddle.nn.functional.mse_loss 中文少两个参数，描述部分去掉 该op

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
>      Returns:
中文参数需要修改，去掉该OP
英文部分需要改下这里
<img width="782" alt="image" src="https://user-images.githubusercontent.com/39876205/182116014-41721933-8bfc-4634-9393-2701cfec55fc.png">

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/tensor/creation.py
> +        Tensor, A Tensor copied from ``input``.
LGTM for paddle.clone

2022-08-01 09:20 UTC, Ligoml commented on python/paddle/utils/cpp_extension/cpp_extension.py
> +        None
LGTM for paddle.utils.cpp_extension.setup

2022-08-03 12:17 UTC, Ligoml commented on python/paddle/fluid/layers/nn.py
>              None by default.
done

2022-08-03 12:17 UTC, Ligoml commented on python/paddle/fluid/layers/nn.py
>      Raises:
done

2022-08-03 12:29 UTC, Ligoml submitted a review, later dismissed
good job! LGTM

2022-08-03 12:30 UTC, ReganYue commented
> good job! LGTM

梦柳姐辛苦啦~

2022-08-03 13:33 UTC, Ligoml approved these changes

2022-08-04 02:32 UTC, Ligoml submitted a review, later dismissed

2022-08-04 03:51 UTC, zhiqiu approved these changes, later dismissed
LGTM

2022-08-04 11:06 UTC, Ligoml submitted a review, later dismissed

2022-08-05 07:53 UTC, JiabinYang approved these changes
LGTM

2022-08-05 07:54 UTC, Ligoml approved these changes

2022-08-08 05:29 UTC, merged