【PaddlePaddle Hackathon 3 No.17】为 Paddle 新增 sgn
PaddlePaddle/Paddle pull request #44568
Opened 2022-07-23 10:51 UTC by peachlcy

### PR types

New features
### PR changes

APIs
### Describe

solve this https://github.com/PaddlePaddle/Paddle/issues/44073#task23

2022-07-23 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=44568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=44568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=44568) it.</sub>

2022-07-23 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=44568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=44568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=44568) it.</sub>

2022-07-26 03:40 UTC, luotao1 commented
请先修复下多条失败CI的问题

2022-07-27 02:58 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        zero_mask = paddle.all(exp_zero, axis=-1)
zero_mask后面没有用到？

2022-07-27 02:58 UTC, luotao1 commented on python/paddle/tensor/math.py
> +    This API returns sign of every element in `x`: 1 for positive, -1 for negative and 0 for zero.
注释不够准确，没有体现复数

2022-07-27 02:58 UTC, luotao1 commented on python/paddle/tensor/math.py
> +            print(paddle.sgn(x))
- example中需要有复数的例子
- 不要用rand输入，用确切的输入，然后把输出作为注释写出来

2022-07-27 02:58 UTC, luotao1 commented on python/paddle/fluid/tests/unittests/test_sgn.py
> +        if paddle.device.get_device() == 'cpu':
没有GPU的？

2022-07-30 18:29 UTC, gsq7474741 commented on python/paddle/fluid/tests/unittests/test_sgn.py
> +        if paddle.device.get_device() == 'cpu':
逻辑是：默认是GPU，如果是cpu则去掉fp16

2022-08-01 07:36 UTC, peachlcy commented on python/paddle/fluid/tests/unittests/test_sgn.py
> +        if paddle.device.get_device() == 'cpu':
这里CPU没有fp16，所以单列了一个情况，默认是gpu

2022-08-01 09:15 UTC, luotao1 commented on python/paddle/fluid/tests/unittests/test_sgn.py
> +                [[3 + 4j, 7 - 24j, 0, 1 + 2j], [3 + 4j, 7 - 24j, 0, 1 + 2j]],
[3 + 4j, 7 - 24j, 0, 1 + 2j]重复出现了，因此可以换一个来增加测试的丰富度

2022-08-01 09:15 UTC, luotao1 commented on python/paddle/tensor/math.py
> +    For other dtype tensor,
other float dtype tensor

2022-08-01 09:15 UTC, luotao1 commented on python/paddle/tensor/math.py
> +            print(paddle.sgn(x))
[3 + 4j, 7 - 24j, 0, 1 + 2j]重复出现了，因此可以换一个来增加示例的丰富度

2022-08-01 09:15 UTC, luotao1 commented on python/paddle/tensor/math.py
> +            "The data type of input must be one of ['float32', 'float64', 'complex64', 'complex128'], but got {}"
类型并不匹配，4586行中有float16，但下面的typeError处没有。
包括上面的注释和单测中，需要统一对float16的处理

2022-08-02 09:35 UTC, peachlcy commented on python/paddle/tensor/math.py
> +            "The data type of input must be one of ['float32', 'float64', 'complex64', 'complex128'], but got {}"
已更新

2022-08-03 03:43 UTC, luotao1 commented
@peachlcy PR-CI-Codestyle-Check流水线没有过，请修改下格式

2022-08-04 06:02 UTC, Ligoml commented
需要补充中文API文档到 [docs ](https://github.com/PaddlePaddle/docs)

2022-08-04 15:47 UTC, peachlcy commented
> 需要补充中文API文档到 [docs](https://github.com/PaddlePaddle/docs)

已添加
- https://github.com/PaddlePaddle/docs/pull/5107

2022-08-04 16:30 UTC, SigureMo requested changes

2022-08-04 16:30 UTC, SigureMo commented on python/paddle/tensor/__init__.py
> -from .search import bucketize  # noqa: F401
这里是解决冲突时候误操作咩？(｡･ω･｡) 

也导致 bucketize 的示例代码挂掉了～

2022-08-04 16:30 UTC, SigureMo commented on python/paddle/tensor/__init__.py
> -    'bucketize',
同上～

2022-08-05 06:26 UTC, peachlcy commented on python/paddle/tensor/__init__.py
> -    'bucketize',
done

2022-08-05 08:19 UTC, Ligoml commented on python/paddle/tensor/math.py
> +            x = paddle.to_tensor(np_x)
这里可以直接使用 to_tensor 创建输入的哈，不需要引入numpy，可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/conj_cn.html#conj

2022-08-06 13:24 UTC, peachlcy commented on python/paddle/tensor/math.py
> +            x = paddle.to_tensor(np_x)
done

2022-08-08 06:50 UTC, Ligoml commented
中文文档的pr也辛苦改一下~

2022-08-09 12:37 UTC, peachlcy commented
> 中文文档的pr也辛苦改一下~

中文文档用的是COPY-FROM: paddle.sgn

2022-08-09 12:40 UTC, SigureMo commented
> 中文文档用的是COPY-FROM: paddle.sgn

应该是说那边的一些其他问题，看起来都还没有改

2022-08-09 13:24 UTC, peachlcy commented
> > 中文文档用的是COPY-FROM: paddle.sgn
> 
> 应该是说中文文档那边的一些其他问题，看起来都还没有改

已修改

2022-08-11 03:59 UTC, Ligoml approved these changes
LGTM for docs

2022-08-11 06:50 UTC, jeff41404 commented
[rfc](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220705_api_design_for_sgn.md) should be included in PR Describe above.

2022-08-11 06:51 UTC, jeff41404 approved these changes
LGTM

2022-08-11 08:11 UTC, luotao1 commented
> [rfc](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220705_api_design_for_sgn.md) should be included in PR Describe above.

rfc已经添加到PR描述中。

2022-08-11 08:11 UTC, merged