【PaddlePaddle Hackathon 3 No.16】为 Paddle 新增 API paddle.take
PaddlePaddle/Paddle pull request #44741
Opened 2022-07-29 13:06 UTC by S-HuaBomb

### PR types

New features

### PR changes

APIs

### Describe

完成飞桨黑客松第三期第16项目开发任务: https://github.com/PaddlePaddle/Paddle/issues/44073#task16

增加 API `paddle.take`，对于输入的 Tensor，将输入 Tensor 视为一维 Tensor，实现根据索引返回指定索引上的元素集合组成的新 Tensor。返回结果与索引的形状相同。

RFC 设计文档: https://github.com/PaddlePaddle/community/pull/186

2022-08-04 04:08 UTC, luotao1 commented on python/paddle/fluid/tests/unittests/test_take.py
> +    """Test take Error"""
缺少index索引越界的报错

2022-08-04 04:08 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        input (Tensor): An N-D Tensor, which data type should be int32, int64, float32, float64.
which data type-》its data type

2022-08-04 04:08 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        check_variable_and_dtype(index, 'index', ['int32', 'int64'], 'take')
index索引越界时需要报错

2022-08-04 04:08 UTC, luotao1 commented on python/paddle/tensor/math.py
> +            #         [7, 8, 9]])
示例可增加一个negative index和float类型的input

2022-08-04 12:42 UTC, S-HuaBomb commented on python/paddle/fluid/tests/unittests/test_take.py
> +    """Test take Error"""
我直接通过 `paddle.index_select` 来报错。
Done

2022-08-04 12:42 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        input (Tensor): An N-D Tensor, which data type should be int32, int64, float32, float64.
Done

2022-08-04 12:42 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        check_variable_and_dtype(index, 'index', ['int32', 'int64'], 'take')
Done

2022-08-04 12:42 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +            #         [7, 8, 9]])
Done

2022-08-05 03:45 UTC, luotao1 reviewed
LGTM

2022-08-05 08:06 UTC, Ligoml commented on python/paddle/tensor/math.py
> +            x_float = paddle.to_tensor(n, dtype='float64')
可以使用paddle API直接生成输入的情况下，尽量避免引入第三方库哈~

2022-08-05 08:30 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +            x_float = paddle.to_tensor(n, dtype='float64')
Done

2022-08-05 08:34 UTC, Ligoml approved these changes, later dismissed
LGTM for docs

2022-08-05 08:42 UTC, Ligoml commented on python/paddle/tensor/math.py
> +            x_float = paddle.to_tensor(n, dtype='float64')
docs 的 pr 也需要改一下

2022-08-09 02:52 UTC, luotao1 commented
@S-HuaBomb 和 @jeff41404 讨论后，需要根据 https://github.com/PaddlePaddle/community/pull/186#pullrequestreview-1066022085 重新修改下RFC和PR

2022-08-23 00:49 UTC, S-HuaBomb commented
> @S-HuaBomb 和 @jeff41404 讨论后，需要根据 [PaddlePaddle/community#186 (review)](https://github.com/PaddlePaddle/community/pull/186#pullrequestreview-1066022085) 重新修改下RFC和PR

> 由于 numpy 在指定轴索引后得到的结果不能保证与 index 的 shape 一致，会破坏 take 方法的输出结果形状与 index 一致的特性。因此我们决定新增的 `paddle.take` 的功能与 `torch.take` 和 `numpy.take` 的默认形式保持一致，即，不增加 axis 参数指定索引轴；在 `torch.take` 的基础上增加 mode 参数提供三种 index 索引越界的处理方式。尽可能保持 take 索引方法简洁、易理解的特性。

见修改后的 RFC：https://github.com/PaddlePaddle/community/pull/217

2022-08-23 06:19 UTC, SigureMo requested changes

2022-08-23 06:19 UTC, SigureMo commented on python/paddle/fluid/tests/unittests/test_take.py
> +                    np.take(self.input_np, self.index_np, mode=self.mode)))
<img width="866" alt="image" src="https://user-images.githubusercontent.com/38436475/186084306-914d676b-70fd-46f8-8683-02e36b860e5c.png">

建议使用 `np.testing.assert_allclose(...)` 替代现有的 `self.assertTrue(np.allclose(...))`，下同，如果默认值无法通过可调整 rtol 和 atol，因为两个 API 的默认值是不一样的

这是前两天刚引入的一个检测，修改后应可通过 PR-CI-APPROVAL

2022-08-23 07:11 UTC, S-HuaBomb commented on python/paddle/fluid/tests/unittests/test_take.py
> +                    np.take(self.input_np, self.index_np, mode=self.mode)))
Thx, done.

2022-08-23 08:05 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        # This processing enables 'take' to handle negative indexes within the correct range.
可以补充下注释，negative indexes可以enable，但越界的索引会在下面的index_select报错

2022-08-23 09:12 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        # This processing enables 'take' to handle negative indexes within the correct range.
THX，Done

2022-08-23 09:41 UTC, SigureMo commented on python/paddle/tensor/math.py
> +    Returns a new tensor with the elements of tnput tensor x at the given index.
`tnput`？是个 typo 嘛？

2022-08-23 09:58 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +    Returns a new tensor with the elements of tnput tensor x at the given index.
是的，fixed，done

2022-08-23 11:55 UTC, luotao1 reviewed
LGTM 请 @Ligoml review下文档部分

2022-08-23 12:44 UTC, SigureMo requested changes

2022-08-23 12:44 UTC, SigureMo commented on python/paddle/tensor/math.py
> +        Tensor: Tensor with the same shape as index, the data type is the same with input.
Tensor 后使用 `,`，以避免解析出 `Return Type`

2022-08-23 12:44 UTC, SigureMo commented on python/paddle/tensor/math.py
> +                the candicates are ``'raise'`` | ``'wrap'`` | ``'clip'``.
这里用 `,` 分隔即可，下面的内容按照中文文档那边的意见统一改成列表吧～

2022-08-24 07:27 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +                the candicates are ``'raise'`` | ``'wrap'`` | ``'clip'``.
Thx, done.

2022-08-24 07:33 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        Tensor: Tensor with the same shape as index, the data type is the same with input.
Thx, done.

2022-08-25 09:22 UTC, Ligoml commented on python/paddle/tensor/math.py
> +            the index that addresses the last element. Note that this disables indexing with negative numbers.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/39876205/186627339-22152c9a-87ee-4d16-9f63-289a8ccceb87.png">

啊哦，这里报了一个warning，需要在这一行和参数详解之间增加一个空行来解决

2022-08-25 09:24 UTC, Ligoml commented
另外解决一下冲突~

2022-08-25 12:45 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +            the index that addresses the last element. Note that this disables indexing with negative numbers.
Done.

2022-08-25 12:46 UTC, S-HuaBomb commented
> 另外解决一下冲突~

Done.

2022-08-26 02:16 UTC, luotao1 approved these changes, later dismissed

2022-08-26 02:48 UTC, Ligoml submitted a review, later dismissed
LGTM for docs

2022-08-26 04:06 UTC, jeff41404 commented on python/paddle/tensor/math.py
> +def take(x, index, mode='raise', name=None):
the name of parameter needs to be consistent with [rfc](https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220714_api_design_for_take.md), `input` in rfc while `x` here, and `mode` is not in rfc.

2022-08-26 04:10 UTC, luotao1 commented on python/paddle/tensor/math.py
> +def take(x, index, mode='raise', name=None):
@jeff41404 根据之前的修改意见 https://github.com/PaddlePaddle/community/pull/186#pullrequestreview-1066022085 更新过RFC：https://github.com/PaddlePaddle/community/pull/217
参数的名字按照新的RFC内容进行修改的。

@S-HuaBomb 请先修改完RFC的评审意见吧。

2022-08-26 04:14 UTC, jeff41404 commented on python/paddle/tensor/math.py
> +def take(x, index, mode='raise', name=None):
rfc is still old now, should update and merge rfc first

2022-08-27 05:05 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +def take(x, index, mode='raise', name=None):
This is the modified RFC https://github.com/PaddlePaddle/community/pull/217 with instructions added

2022-08-29 02:26 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        index_1d = paddle.where(index_1d < 0, index_1d + max_index, index_1d)
@S-HuaBomb 这个修改是哪个case会出bug呢？

2022-08-29 02:42 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        index_1d = paddle.where(index_1d < 0, index_1d + max_index, index_1d)
这里本来就应该是  `+` 号，这样确保负值索引是在合理范围内的，我只需要  `+` 号把它转成对应的负值索引。如果使用取余 `%`，那么超出范围的负值索引也会被约束到合理范围，那样是不对的。

2022-08-29 02:51 UTC, luotao1 commented on python/paddle/tensor/math.py
> +        index_1d = paddle.where(index_1d < 0, index_1d + max_index, index_1d)
> 那么超出范围的负值索引也会被约束到合理范围，那样是不对的。

Got it. 可以针对这个case补充一个报错的单测么？

2022-08-29 03:14 UTC, S-HuaBomb commented on python/paddle/tensor/math.py
> +        index_1d = paddle.where(index_1d < 0, index_1d + max_index, index_1d)
已加，done.

2022-08-29 06:18 UTC, luotao1 commented
LGTM 
@jeff41404 https://github.com/PaddlePaddle/community/pull/217 修改后的RFC文档已经合入，请再次审核～

2022-08-29 06:18 UTC, luotao1 approved these changes

2022-08-30 07:40 UTC, jeff41404 approved these changes
LGTM

2022-08-30 07:45 UTC, merged