【PaddlePaddle Hackathon 3 No.20】为 Paddle 新增 vsplit API
PaddlePaddle/Paddle pull request #44853
Opened 2022-08-03 08:22 UTC by Asthestarsfalll

### PR types

**New features**
### PR changes

APIs
### Describe

rfc链接：https://github.com/PaddlePaddle/community/pull/166

vsplit将输入按照给定的sections或num数量在垂直轴上（行上）划分，等效于将`split`API的axis固定为0.

2022-08-03 08:28 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +]
这里使用test_list来储存需要测试的API，可以便于后续添加类似的API如dsplit、hsplit

2022-08-03 08:28 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +    return func(x, indices_or_sections)
由于paddle.split的中分块的逻辑与numpy中不同，因此需要做一下转换

2022-08-05 02:25 UTC, Asthestarsfalll commented
@tizhou86 
你好，CI已全部通过，可以开始review了吗？

2022-08-05 02:58 UTC, tizhou86 commented
> @tizhou86 你好，CI已全部通过，可以开始review了吗？

OK，我这儿尽快review

2022-08-12 03:25 UTC, tizhou86 reviewed
整体OK，劳烦添加注释明确测试对应case。

2022-08-12 03:25 UTC, tizhou86 commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +    return func(x, indices_or_sections)
这儿可以添加函数注释说明，明确这个函数的用途

2022-08-12 03:25 UTC, tizhou86 commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +]
这儿也可以注释说明一下可扩展能力，也可以加一个TODO项来说明后续可以在该位置添加其他算子

2022-08-12 03:25 UTC, tizhou86 commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +
这儿需要为测试case添加对应注释说明，覆盖了哪些测试项

2022-08-12 03:25 UTC, tizhou86 commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +
这儿也缺少对应注释哈

2022-08-15 07:05 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +
已添加

2022-08-15 07:05 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +
已添加

2022-08-17 08:43 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +]
已添加

2022-08-17 08:43 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +    return func(x, indices_or_sections)
已添加

2022-08-19 03:04 UTC, tizhou86 reviewed
需要在init.py中添加新增函数，可以参考该实现：https://github.com/PaddlePaddle/Paddle/pull/44568/files，添加完成后，需要重新跑一下ci。

2022-08-22 06:52 UTC, Asthestarsfalll commented
@tizhou86 已更新

2022-08-22 07:53 UTC, tizhou86 submitted a review, later dismissed
LGTM

2022-08-22 07:55 UTC, Ligoml commented
请补充中文API文档哈

2022-08-27 09:34 UTC, Asthestarsfalll commented
[已添加](https://github.com/PaddlePaddle/docs/pull/5213)

2022-08-29 18:32 UTC, SigureMo requested changes

2022-08-29 18:32 UTC, SigureMo commented on python/paddle/tensor/manipulation.py
> +        list(Tensor): The list of segmented Tensors.
`list[Tensor]`

2022-08-29 18:32 UTC, SigureMo commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +                self.assertTrue(np.allclose(n, p))
<img width="865" alt="image" src="https://user-images.githubusercontent.com/38436475/187272822-98cfb383-50cb-47ef-9432-f69ad50cef8d.png">

使用 `np.testing` 模块下的断言函数代替 `self.assertTrue(np.allclose(...))`

```suggestion
                np.testing.assert_allclose(n, p)
```

如果由于精度问题导致测试无法通过可适当调整 atol 和 rtol，66 行同

修改后应可通过 PR-CI-APPROVAL

2022-08-30 12:25 UTC, Asthestarsfalll commented on python/paddle/tensor/manipulation.py
> +        list(Tensor): The list of segmented Tensors.
[此处](https://github.com/PaddlePaddle/Paddle/blob/release/2.3/python/paddle/tensor/manipulation.py#L923)为`list(Tensor)`

2022-08-30 12:38 UTC, SigureMo requested changes

2022-08-30 12:38 UTC, SigureMo commented on python/paddle/tensor/manipulation.py
> +        list(Tensor): The list of segmented Tensors.
统一修改成 `list[Tensor]` 吧，`list[Tensor]` 才是正确的类型注解

以及后面的 `:` 修改成 `,`，以免解析出 Return Type 的内容

2022-08-30 12:40 UTC, SigureMo commented on python/paddle/tensor/manipulation.py
> +        list(Tensor): The list of segmented Tensors.
统一修改成 `list[Tensor]` 吧，`list[Tensor]` 才是正确的类型注解。

另外后面的 `:` 修改为 `,` 吧，以免解析出不必要的 Return Type 字段

2022-08-30 12:42 UTC, Asthestarsfalll commented on python/paddle/tensor/manipulation.py
> +        list(Tensor): The list of segmented Tensors.
了解！

2022-08-30 13:03 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +                self.assertTrue(np.allclose(n, p))
down

2022-08-30 19:07 UTC, SigureMo commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +        self.atol = 1e-8
<img width="851" alt="image" src="https://user-images.githubusercontent.com/38436475/187521187-b0b5ffe1-4dd8-4123-98a3-d6b91bccf9b3.png">

这样的话下面继承 `TestSplitsAPI` 并重载了 `setUp` 的几个单测访问不到它们，因为这些值只会写一次，所以以字面量形式直接写在 `np.testing.assert_allclose` 调用处吧～

2022-09-02 08:26 UTC, Asthestarsfalll commented on python/paddle/fluid/tests/unittests/test_splits_api.py
> +        self.atol = 1e-8
done

2022-09-02 08:59 UTC, SigureMo approved these changes
LGTM for docs~~~

2022-09-02 09:37 UTC, Ligoml commented
预览工具无法正常构建出文档，目前还在排查原因，需要等一段时间

2022-09-02 09:49 UTC, SigureMo requested changes

2022-09-02 09:49 UTC, SigureMo commented on python/paddle/tensor/manipulation.py
> +            out0, out1, out2 = paddle.vplit(x, num_or_sections=[2, 3, -1])
> 预览工具无法正常构建出文档，目前还在排查原因，需要等一段时间

应该是因为某种原因 docstring 没被解析出来，中文文档那面的 COPY-FROM 也是失败的，而且这里 `vplit` 明显是个 typo，CI 通过了的话说明这个示例并没有跑

2022-09-07 06:03 UTC, Ligoml commented on python/paddle/tensor/manipulation.py
> +            out0, out1, out2 = paddle.vplit(x, num_or_sections=[2, 3, -1])
是的，我反馈给官网研发了，他们说近期会协助排查一下

2022-09-08 07:32 UTC, Ligoml commented on python/paddle/tensor/manipulation.py
> +            out0, out1, out2 = paddle.vplit(x, num_or_sections=[2, 3, -1])
重新编译后正常，我这边没有问题了

2022-09-08 07:33 UTC, Ligoml approved these changes
LGTM for docs

2022-09-09 08:11 UTC, jeff41404 approved these changes
LGTM

2022-09-09 08:50 UTC, merged