update loss.py in nn.functional and nn.layer module
PaddlePaddle/Paddle pull request #45068
Opened 2022-08-11 08:05 UTC by liyongchao911

### PR types
Others

### PR changes
Docs

### Describe
1. fix some typo and markdown issue
2. add optional note in the nn.Pad1D/2D/3D class parameter, for both CN and EN docs
3. replace np.prod with paddle.prod in some code example

2022-08-11 08:57 UTC, SigureMo requested changes

2022-08-11 08:57 UTC, SigureMo commented on python/paddle/nn/layer/common.py
>      Code Examples:
这里改成 `Examples:` 吧～

2022-08-11 08:57 UTC, SigureMo commented
最好中英互相链起来呀～

2022-08-11 13:31 UTC, liyongchao911 commented on python/paddle/nn/layer/common.py
>      Code Examples:
Done！

2022-08-15 15:20 UTC, SigureMo requested changes

2022-08-15 15:20 UTC, SigureMo commented on python/paddle/nn/functional/common.py
> +        value (float, optional): The value to fill the padded areas in 'constant' mode . Default is 0.0
这里和中文对齐吧，同样用

```
:math:`0.0`
```

最后也需要加英文句号 `.`

2022-08-15 15:20 UTC, SigureMo commented on python/paddle/nn/functional/common.py
>              Default is 'constant'
这里默认值和英文调整成一样的吧，都放到上面去，此外同样空一下行以免渲染问题吧

2022-08-15 15:20 UTC, SigureMo commented on python/paddle/nn/functional/loss.py
>           ignore_index (int64, optional): Specifies a target value that is ignored
这里 `int64` 改为 `int`

2022-08-19 09:45 UTC, Ligoml approved these changes, later dismissed

2022-08-19 09:45 UTC, Ligoml commented on python/paddle/nn/functional/loss.py
>           ignore_index (int64, optional): Specifies a target value that is ignored
这里好像还是没改？

2022-08-19 09:45 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
>          input (Tensor): Input tensor, the shape is :math:`[N, C]`, `C` is the number of classes.
<img width="706" alt="image" src="https://user-images.githubusercontent.com/39876205/185592144-282cdc9c-548b-4a42-bbbd-edef837c0f94.png">
这里需要增加空行，保证前端正确展示

2022-08-19 09:45 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
>              Default is ``'mean'``.
<img width="384" alt="image" src="https://user-images.githubusercontent.com/39876205/185592343-b211bd77-f95f-4cf4-8976-15495767793f.png">
对应的中文文档似乎增加了多余的符号

2022-08-23 03:58 UTC, Ligoml commented on python/paddle/nn/layer/loss.py
>          input (Tensor): Input tensor, the shape is :math:`[N, C]`, `C` is the number of classes.
抱歉我记错了，这里是需要在前面加`-`，我直接改了

2022-08-23 04:24 UTC, SigureMo approved these changes
LGTM~~~

2022-08-23 05:05 UTC, Ligoml approved these changes
LGTM

2022-08-23 06:05 UTC, merged