[inference]predictor add GetInputType interface
PaddlePaddle/Paddle pull request #45143
Opened 2022-08-15 08:12 UTC by heliqi

### PR types
Others

### PR changes
Others

### Describe
predictor add GetInputType interface

2022-08-16 06:38 UTC, jiangjiajun requested changes

2022-08-16 06:38 UTC, jiangjiajun commented on paddle/fluid/inference/api/paddle_inference_api.h
> +  std::map<std::string, DataType> GetInputType();
这里获取的所有的dtype，就改名为`GetInputTypes()`吧，与`GetInputNames()`对应

2022-08-16 06:38 UTC, jiangjiajun commented on paddle/fluid/inference/api/analysis_predictor.cc
> +  for (auto name : names) {
`auto& name : names`

2022-08-16 06:45 UTC, heliqi commented on paddle/fluid/inference/api/analysis_predictor.cc
> +  for (auto name : names) {
对于只读的vector遍历不需要加& ，要修改里边内容才需要引用

2022-08-16 06:45 UTC, heliqi commented on paddle/fluid/inference/api/paddle_inference_api.h
> +  std::map<std::string, DataType> GetInputType();
Done

2022-08-16 06:58 UTC, jiangjiajun commented on paddle/fluid/inference/api/paddle_inference_api.h
> +  std::map<std::string, DataType> GetInputType();
`auto x : std::vector<std::string>`
相对比
`auto& x : std::vector<std::string>` 是否会多出来复制的操作，或者是否是`const auto& x : std::vector<std::string>`

2022-08-16 06:58 UTC, jiangjiajun commented on paddle/fluid/inference/api/analysis_predictor.cc
> +  for (auto name : names) {
`auto x : std::vector<std::string>`
相对比
`auto& x : std::vector<std::string>` 是否会多出来复制的操作，或者是否是`const auto& x : std::vector<std::string>`

2022-08-16 08:08 UTC, heliqi commented on paddle/fluid/inference/api/analysis_predictor.cc
> +  for (auto name : names) {
已改成 const auto&

2022-08-16 10:04 UTC, jiangjiajun approved these changes, later dismissed

2022-08-18 13:48 UTC, jiangjiajun approved these changes

2022-08-18 13:49 UTC, merged