move collective tests into a collective directory
PaddlePaddle/Paddle pull request #45223
Opened 2022-08-17 12:27 UTC by sljlp

### PR types

Others
### PR changes

Others
### Describe

Move all collective unit tests into a collective directory.

2022-08-19 03:19 UTC, gongweibao requested changes
Rename not copy.

2022-08-19 03:19 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/CMakeLists.txt
> +          SRCS "collective/test_collective_allreduce_api.py")
Should it be moved?

2022-08-19 03:19 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/CMakeLists.txt
> +    set_tests_properties(test_pipeline_parallel PROPERTIES LABELS
Should it be moved?

2022-08-19 08:13 UTC, XieYunshen submitted a review, later dismissed
LGTM 单测迁移

2022-08-20 03:44 UTC, gongweibao requested changes
1. This tool should manage `dist_port` and the user need only to consider the ports they would use.
2. Remove the commented lines in the CMakeLists.txt
3. Add a key `device_num`?

2022-08-25 02:58 UTC, XieYunshen approved these changes, later dismissed
LGTM

2022-08-25 08:53 UTC, gongweibao approved these changes, later dismissed
LGTM

2022-08-25 09:14 UTC, wanghuancoder approved these changes, later dismissed
LGTM

2022-08-26 07:03 UTC, XiaoguangHu01 submitted a review, later dismissed
LGTM

2022-08-26 07:23 UTC, XiaoguangHu01 approved these changes
LGTM

2022-08-26 07:24 UTC, XieYunshen approved these changes

2022-08-26 07:25 UTC, wanghuancoder approved these changes
LGTM

2022-08-26 08:17 UTC, gongweibao approved these changes
LGTM

2022-08-26 11:24 UTC, merged