Solve the random state serialization
PaddlePaddle/Paddle pull request #45327
Opened 2022-08-23 03:11 UTC by ForFishes

### PR types

New features
### PR changes

Others
### Describe

Solve the random state serialization

2022-08-23 08:34 UTC, zhiqiu submitted a review, later dismissed
;GTM

2022-08-24 03:08 UTC, gongweibao requested changes
Explain why we do this? Like what issue or problem to solve under what condition?

2022-08-24 03:08 UTC, gongweibao commented on paddle/fluid/pybind/generator_py.cc
> +              throw std::runtime_error("Invalid Random state!");
`Invalid Random state. Please check the format(device, current_seed, thread_offset)`.

2022-08-24 03:08 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
> +        if core.is_compiled_with_cuda():
Can we use `paddle.set_cuda_rng_state`  while not  `is_compiled_with_cuda`?

2022-08-24 03:08 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
> +            np.testing.assert_allclose(x1_np, x2_np, rtol=1e-05)
1e-06 or higher?

2022-08-24 04:03 UTC, ForFishes commented on paddle/fluid/pybind/generator_py.cc
> +              throw std::runtime_error("Invalid Random state!");
done

2022-08-24 04:03 UTC, ForFishes commented on python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
> +        if core.is_compiled_with_cuda():
no, when not ``is_compiled_with_cuda ``,  ``paddle.set_cuda_rng_state`` is invalid.

2022-08-24 07:35 UTC, ForFishes commented on python/paddle/fluid/tests/unittests/test_cuda_random_seed.py
> +            np.testing.assert_allclose(x1_np, x2_np, rtol=1e-05)
done

2022-08-24 08:19 UTC, gongweibao approved these changes
LGTM

2022-08-24 12:18 UTC, merged