update PixelShuffle and PRelu api in vision.py and activation.py；test=document_fix
PaddlePaddle/Paddle pull request #45423
Opened 2022-08-25 11:01 UTC by liyongchao911

### PR types
 Others 

### PR changes
Docs 

### Describe
1. using paddle.randn and paddle.to_tensor to replace the numpy in some api
2. fix some format issue

2022-08-26 05:36 UTC, SigureMo requested changes
其余按照中文那边改一下吧～

另外中英文最好互链一下，方便跳转

2022-08-26 05:36 UTC, SigureMo commented on python/paddle/nn/functional/activation.py
> +            out
`print(out)` 吧

2022-08-26 08:42 UTC, Ligoml approved these changes, later dismissed
LGTM

2022-08-29 02:41 UTC, luotao1 commented
```
2022-08-26 15:25:22 1 sample codes ran failed
2022-08-26 15:25:22 samplecode_temp/paddle.nn.RReLU_example.py
2022-08-26 15:25:22 Mistakes found in sample codes. Please recheck the sample codes.
```

2022-08-29 09:17 UTC, Ligoml approved these changes

2022-08-29 10:31 UTC, merged