[Do not Merge][JitLayer]Using predictor in JitLayer an apply pass
PaddlePaddle/Paddle pull request #45428
Opened 2022-08-25 13:00 UTC by 0x45f

### PR types

Others
### PR changes

Others
### Describe

Using predictor in JitLayer an apply pass

2022-08-25 13:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=45428) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=45428) before we can accept your contribution.<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=45428) it.</sub>

2022-09-27 12:41 UTC, Aurelius84 commented on paddle/fluid/inference/api/analysis_predictor.cc
> +  // PADDLE_ENFORCE_NOT_NULL(
可以考虑在PaddleTensorToLoDTensor函数加一个bool allow_empty_tensor参数，默认false，实现对zero shape tensor的支持。

if(allow_empty_tensor) return true; 直接跳过下面的检查和data copy

2022-09-27 12:41 UTC, Aurelius84 commented on paddle/fluid/inference/api/analysis_predictor.cc
> +    OptimizeInferenceProgram();
这是个public的接口，我们可以放到PredictorEngine的构造函数里单独调用

2022-09-27 12:41 UTC, Aurelius84 commented on paddle/fluid/inference/api/analysis_predictor.cc
> +    // std::string dir = inference::analysis::GetDirRoot(config_.prog_file());
我们可以考虑给config_新增一个配置项，表示program是从内存加载进来的，此时可以允许config_.prog_file()为空

2022-10-24 03:46 UTC, yeliang2258 requested changes

2022-10-24 03:46 UTC, yeliang2258 commented on paddle/fluid/inference/io.cc
> +  // LoadPersistables(executor,
这里可以传一个参数控制是否需要加载params

2022-10-24 03:50 UTC, yeliang2258 commented on paddle/fluid/jit/engine/predictor_engine.h
> +    config.SwitchIrOptim(true);
增加以下配置：
config.EnableMKLDNN();
config.EnableMkldnnInt8();
config.SetMkldnnCacheCapacity(0);

2022-11-01 06:27 UTC, closed without merging