fix memcpy_h2d bug related to cuda stream setting when allocate memory
PaddlePaddle/Paddle pull request #45450
Opened 2022-08-26 07:23 UTC by kangguangli

### PR types

Bug fixes
### PR changes

OPs
### Describe

[Transfer memcpy_h2d](related: #44932)
This commit did not correctly set the stream of the tensor when allocating, so may cause crash. 

Known problem includes cudaError(700) while training model (PaddleRec/models/rank/bst) using:
`python -u ../../../tools/static_trainer.py -m config.yaml -o runner.use_gpu=True`

2022-08-26 09:37 UTC, From00 requested changes

2022-08-26 09:37 UTC, From00 commented on paddle/phi/core/tensor_utils.cc
> -  dst->mutable_data(dst_place);
phi::copy函数并不假定所有调用者都对拷贝的目的地址提前分配了显存，此处不应删除mutable_data。mutable_data不会对已分配内存的Tensor做重复分配。

2022-08-26 09:37 UTC, From00 commented on paddle/phi/kernels/memcpy_kernel.cc
> +void MemcpyH2DKernel(const GPUContext& dev_ctx,
特化GPUContext增加了代码复杂度，更建议直接在kernel中通过is_gpu_place(dev_ctx.GetPlace())判断需要在分配时传入stream的情况

2022-08-26 09:37 UTC, From00 commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(CPUPlace());
此处代码没有必要

2022-08-26 09:37 UTC, From00 commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(GPUPinnedPlace());
同上

2022-08-26 11:12 UTC, kangguangli commented on paddle/phi/core/tensor_utils.cc
> -  dst->mutable_data(dst_place);
这里是之前迁移memcpy_d2h(#45150)时为了给size为0的向量分配正确的place引入的，迁移前phi::copy是没有这一句的，而言mutable_data也不是推荐写法，因此把这一句放到MemcyD2HKernel里了

2022-08-26 11:14 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +void MemcpyH2DKernel(const GPUContext& dev_ctx,
嗯，这里我也觉得后续会有维护问题，后续修改，再想想有没有其他解决方案

2022-08-26 11:14 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(CPUPlace());
有必要，参见前面对phi::copy修改的说明

2022-08-26 11:14 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(GPUPinnedPlace());
有必要，参见前面对phi::copy修改的说明

2022-08-26 11:20 UTC, From00 commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(CPUPlace());
嗯，处理特殊逻辑建议在代码中加NOTE

2022-08-29 12:04 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(CPUPlace());
Done

2022-08-29 12:06 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +void MemcpyH2DKernel(const GPUContext& dev_ctx,
应该只能这样实现，如果不特化的话，虽然使用if判断，但是stream部分依然需要需要编译，这样cpucontext实例化的时候通不过编译

2022-08-29 12:07 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +void MemcpyH2DKernel(const GPUContext& dev_ctx,
当然用宏修饰一下应该也可以，不确定哪个写法差距更好

2022-08-30 02:34 UTC, kangguangli commented on paddle/phi/kernels/memcpy_kernel.cc
> +      out->mutable_data(GPUPinnedPlace());
Done

2022-08-30 02:36 UTC, From00 approved these changes

2022-08-30 02:55 UTC, YuanRisheng approved these changes

2022-08-30 03:01 UTC, merged