fix some doc bug test=document_fix
PaddlePaddle/Paddle pull request #45488
Opened 2022-08-27 05:36 UTC by mrcangye

### PR types

Bug fixes
### PR changes

Docs
### Describe

Issue：https://github.com/PaddlePaddle/docs/issues/5212

2022-08-27 07:56 UTC, SigureMo requested changes
部分 activation 的英文文档显示也有问题，但是写在 C++ 代码里的，是否需要修改周一问问梦柳吧

比如 sigmoid 公式就是有问题的

<img width="570" alt="image" src="https://user-images.githubusercontent.com/38436475/187020924-529d2d65-1431-43d0-9410-58b98764a627.png">

英文文档在

https://github.com/PaddlePaddle/Paddle/blob/a635a8a5c4ec914f57058bdcccf854d620ce5f42/paddle/fluid/operators/activation_op.cc#L184-L189

和

https://github.com/PaddlePaddle/Paddle/blob/a635a8a5c4ec914f57058bdcccf854d620ce5f42/python/paddle/tensor/ops.py#L111-L124

2022-08-27 07:56 UTC, SigureMo commented on python/paddle/nn/layer/activation.py
> +        sigmoid(x) = \frac{1}{1 + e^{-x}}
这里删除转义应该不行吧，如果删除的话，在 707 行加个 `r` 自动转义吧

2022-08-27 07:56 UTC, SigureMo commented on python/paddle/nn/layer/activation.py
> +        sigmoid(x) = \frac{1}{1 + e^{-x}}
其他几个如果没有加 `r` 的加上即可

2022-08-27 07:56 UTC, SigureMo commented on python/paddle/nn/functional/loss.py
>              label = paddle.to_tensor(label_data)
这里直接用 paddle 的 API 生成数据吧

2022-08-27 07:56 UTC, SigureMo commented on python/paddle/nn/layer/activation.py
>          x (Tensor): The input Tensor with data type float32, or float64.
没有参数 `x`，这行删掉就好了

2022-08-27 07:56 UTC, SigureMo commented on python/paddle/nn/layer/loss.py
>              loss = paddle.nn.SmoothL1Loss()
同样用 Paddle API 替代 NumPy API 生成数据

2022-09-24 20:29 UTC, SigureMo approved these changes, later dismissed
LGTM~~eow~~ ～

2022-10-06 02:36 UTC, mrcangye commented
> LGTM~eow~ ～


> [mrcangye](/mrcangye) dismissed [SigureMo](/SigureMo)’s [stale review](#pullrequestreview-1119338963) via ` [7ee6825](/PaddlePaddle/Paddle/commit/7ee6825c676d3d158ad2cde56c3884067e2d6643) ` [ 6分钟前](#event-7529846573)

大佬再瞅瞅，这个dismissed [SigureMo](/SigureMo)’s [stale review]没啥影响吧，我一推送就酱紫了

2022-10-06 02:40 UTC, mrcangye commented on python/paddle/nn/layer/activation.py
> +        sigmoid(x) = \frac{1}{1 + e^{-x}}
学到了！

2022-10-06 08:41 UTC, SigureMo reviewed
梦柳在 docs 下回复了好几个引入 numpy 的问题，但好像只改了一个？其余几个是不用改吗？

2022-10-06 08:41 UTC, SigureMo commented on python/paddle/nn/layer/activation.py
>      .. math::
上面加一个空行吧～梦柳说的问题应该是少空行导致的

2022-10-06 08:58 UTC, mrcangye commented on python/paddle/nn/layer/activation.py
>      .. math::
多谢提醒，辛苦大佬再审核看看有没有遗漏

2022-10-06 09:04 UTC, SigureMo approved these changes, later dismissed
应该没啥问题了，等梦柳过两天再预览看看吧～

2022-10-06 09:04 UTC, SigureMo commented on python/paddle/nn/functional/activation.py
> +            x = paddle.to_tensor([-0.4, -0.2, 0.1, 0.3],dtype='float32')
```suggestion
            x = paddle.to_tensor([-0.4, -0.2, 0.1, 0.3], dtype='float32')
```

2022-10-06 09:04 UTC, SigureMo approved these changes, later dismissed

2022-10-06 10:26 UTC, mrcangye commented on python/paddle/nn/functional/activation.py
> +            x = paddle.to_tensor([-0.4, -0.2, 0.1, 0.3],dtype='float32')
感谢大佬

2022-10-06 10:29 UTC, SigureMo commented on python/paddle/nn/layer/activation.py
> +            x = paddle.to_tensor(np.array([-0.4, -0.2, 0.1, 0.3]),dtype='float32')
```suggestion
            x = paddle.to_tensor([-0.4, -0.2, 0.1, 0.3], dtype='float32')
```

2022-10-08 06:15 UTC, Ligoml approved these changes
good job！
LGTM

2022-10-08 06:17 UTC, SigureMo approved these changes
LGTM~~~

2022-10-08 06:35 UTC, merged