[AMP] Support AMP-O2 for bfloat16
PaddlePaddle/Paddle pull request #45541
Opened 2022-08-30 02:58 UTC by zhangbo9674

### PR types
New features

### PR changes
Others

### Describe
AMP-O2支持bfloat16数据类型

2022-09-13 06:59 UTC, lanxianghit submitted a review, later dismissed

2022-09-13 08:07 UTC, zhiqiu commented on python/paddle/fluid/dygraph/amp/auto_cast.py
> +PURE_BF16_WHITE_LIST = {' '}
why use `' '` instead of `''`

2022-09-13 08:42 UTC, zhangbo9674 commented on python/paddle/fluid/dygraph/amp/auto_cast.py
> +PURE_BF16_WHITE_LIST = {' '}
Changed from`' '`to B `''`

2022-09-14 02:50 UTC, zhiqiu requested changes
LGTM

2022-09-14 02:50 UTC, zhiqiu approved these changes

2022-09-14 02:53 UTC, lanxianghit approved these changes

2022-09-14 03:00 UTC, Ligoml approved these changes
LGTM for docs
decorate的API描述部分遗漏了bf16的描述，后续补一个pr吧

2022-09-14 03:17 UTC, merged