Gloo update
PaddlePaddle/Paddle pull request #45584
Opened 2022-08-30 12:24 UTC by ziyoujiyi

### PR types
Others
### PR changes
Others
### Describe
solve gcc 9.3 gloo compile error  
modify: https://github.com/ziyoujiyi/gloo/commit/8b6b61dfa0dca02b226a01262bfcf0484382048f

2022-08-31 08:52 UTC, jzhang533 requested changes
根据线下讨论。
要用upstream gloo，对gloo的改动，在paddle仓库内维护一个patch。

2022-09-02 02:06 UTC, gongweibao requested changes
A comment.

2022-09-02 02:06 UTC, gongweibao commented on cmake/external/gloo.cmake
> +set(GLOO_REPOSITORY ${GIT_URL}/ziyoujiyi/gloo.git)
Why we don't use the original branch of gloo?

2022-09-05 11:29 UTC, fuyinno4 approved these changes

2022-09-06 03:03 UTC, ziyoujiyi commented on cmake/external/gloo.cmake
> +set(GLOO_REPOSITORY ${GIT_URL}/ziyoujiyi/gloo.git)
当前框架使用的gloo版本从 2020.1.9 commit345 拉过来的，然后新增了自定义功能，共 8 个 commit，涉及改动文件数20+，代码行数 1000+，落后官方 repo 53 个 commit，使用官方 repo 工作量估计是一个月，之前讨论的方案是先临时修复

2022-09-06 03:04 UTC, ziyoujiyi commented on cmake/external/gloo.cmake
> +set(GLOO_REPOSITORY ${GIT_URL}/ziyoujiyi/gloo.git)
当前框架使用的gloo版本从 2020.1.9 commit345 拉过来的，然后新增了自定义功能，共 8 个 commit，涉及改动文件数20+，代码行数 1000+，落后官方 repo 53 个 commit，使用官方 repo 工作量估计是一个月，之前讨论的方案是先临时修复

2022-09-06 03:31 UTC, gongweibao approved these changes
LGTM

2022-09-06 03:44 UTC, jzhang533 approved these changes
期待使用upstream gloo

@raindrops2sea @XiaoguangHu01 我们需要对paddle仓库里对第三方依赖的使用做一次治理。
如果看看`./cmake/external`下的文件，不仅存在使用非upstream仓库的问题，甚至存在依赖binary的问题。

2022-09-15 12:45 UTC, merged