[MLU] add mlu kernel for reduce_max_grad
PaddlePaddle/Paddle pull request #45651
Opened 2022-09-01 09:05 UTC by Ashelly1

### PR types

New features
### PR changes

OPs
### Describe

add mlu kernel for reduce_max_grad

2022-09-01 09:24 UTC, ShawnNew requested changes

2022-09-01 09:24 UTC, ShawnNew commented on paddle/fluid/operators/reduce_ops/reduce_max_op_mlu.cc
> +    MLUCnnl::CycleOp(context,
可以尝试使用MLUCnnl::Logic

2022-09-01 11:56 UTC, Ashelly1 commented on paddle/fluid/operators/reduce_ops/reduce_max_op_mlu.cc
> +    MLUCnnl::CycleOp(context,
已修改

2022-09-02 01:07 UTC, ShawnNew submitted a review, later dismissed
👍

2022-09-09 02:24 UTC, ronny1996 approved these changes
LGTM

2022-09-09 03:03 UTC, qili93 approved these changes
LGTM

2022-09-29 03:19 UTC, merged