add paddle audio dataset && backend
PaddlePaddle/Paddle pull request #45939
Opened 2022-09-09 10:22 UTC by SmileGoat

### PR types

New features
### PR changes

Others
### Describe

add paddle audio dataset && backend

2022-09-10 14:36 UTC, zh794390558 submitted a review, later dismissed
LGTM

2022-09-13 03:06 UTC, zh794390558 commented on python/paddle/__init__.py
> +import paddle.audio
noqa: F401

2022-09-13 07:38 UTC, zh794390558 commented on python/paddle/tests/test_audio_backend.py
> +            self.assertTrue(backend in ["wave_backend", "sox_io", "soundfile"])
sox_io先去掉吧

2022-09-19 13:43 UTC, zh794390558 reviewed
paddleaudio的下载在哪儿？

2022-09-20 09:42 UTC, ZeyuChen requested changes
不能默认import，会侵入是破坏别人的使用体验

2022-09-20 09:42 UTC, ZeyuChen commented on python/paddle/audio/utils/download.py
> +def download_and_decompress(archives: List[Dict[str, str]],
这个API不合理，不应该在audio目录里面有utils

2022-09-20 09:42 UTC, ZeyuChen commented on python/paddle/audio/utils/env.py
> +        home_path = os.environ['PPAUDIO_DATA']
也不适合，建议和VISION公用数据集托管目录

2022-09-20 09:42 UTC, ZeyuChen commented on python/paddle/audio/utils/env.py
> +    return os.path.join(_get_user_home(), '.paddle_audiodata')
不能叉开，需要框架整体统一高阶API数据集托管目录

2022-09-20 09:42 UTC, ZeyuChen commented on python/paddle/tests/test_audio_datasets.py
> +                'https://bj.bcebos.com/paddleaudio/datasets/TESS_Toronto_emotional_speech_set_lite.zip',
需要检查数据集license这里是否有二次分发的风险

2022-09-20 09:42 UTC, ZeyuChen commented on python/paddle/audio/backends/init_backend.py
> +    package = "paddleaudio"
不能让所有paddle用户一import就触发这个警告，要在函数级别调用时触发warning

2022-09-21 07:31 UTC, SmileGoat commented on python/paddle/tests/test_audio_datasets.py
> +                'https://bj.bcebos.com/paddleaudio/datasets/TESS_Toronto_emotional_speech_set_lite.zip',
查了一下license：Creative Commons license Attribution-NonCommercial-NoDerivatives 4.0 International
可以分发，下载等。kaggle上面也有分享链接，但是我们的reference  链接打不开，所以又添加了 多伦多大学数据分享链接（主要下载源之一）。
但是不可以再编辑和转换后分发，不可以商用。

2022-09-22 14:05 UTC, ZeyuChen reviewed
AudioClassificationDataset数据类加验证

2022-09-22 14:05 UTC, ZeyuChen commented on python/paddle/audio/backends/wave_backend.py
> +        #dtype = "int16"
sharp后面要有带空格

2022-10-17 06:28 UTC, momozi1996 commented on python/paddle/audio/backends/backend.py
> +    Args:
报错了：
![image](https://user-images.githubusercontent.com/79295425/196104308-6bfc85e4-3bf9-427b-ba2c-4fa02a8bc5d0.png)

2022-10-17 06:29 UTC, momozi1996 commented on python/paddle/audio/backends/backend.py
> +    Example:
示例代码没显示出来，Example: 这里看看有没有，格式问题
![image](https://user-images.githubusercontent.com/79295425/196104493-40e7d8a1-aa50-41e2-882f-d57197fe7e29.png)

2022-10-17 06:30 UTC, momozi1996 commented on python/paddle/audio/backends/backend.py
> +    Examples:
Examples 没显示出来，示例代码不见了

![Uploading image.png…]()

2022-10-17 06:33 UTC, momozi1996 commented on python/paddle/audio/backends/init_backend.py
> +        "wave_backend" is the default.
这里错了：

![image](https://user-images.githubusercontent.com/79295425/196105171-28172a20-d641-4e1d-9a9f-153483ba1c00.png)

2022-10-17 06:40 UTC, momozi1996 reviewed
一些意见，请回复一下

2022-10-20 02:37 UTC, momozi1996 approved these changes
LGTM

2022-10-20 03:10 UTC, zh794390558 submitted a review, later dismissed
LGTM

2022-10-20 04:32 UTC, XiaoguangHu01 commented on python/paddle/audio/backends/__init__.py
> +__all__ = [
有几个疑问
1.  这几个函数名称信息有冗余，比如，audio和beckend都出现了两次
paddle.audio.backends.get_current_audio_backend()
是否可以考虑简洁的方式，比如
paddle.audio.get_current_beckend()
paddle.audio.list_available_beckends()
paddle.audio.set_backend()
2. paddle.audio.backends.save&load&info，backends的save接口表示什么含义呢？
表示save的对象是一个backend吗？
backend是通过set_backend()全局设置的一个状态
如果是表示保存文件的话，是不是paddle.audio.save就可以了？

2022-10-20 04:47 UTC, momozi1996 submitted a review, later dismissed
LGTM

2022-10-20 10:14 UTC, momozi1996 approved these changes
LGTM

2022-10-20 10:55 UTC, XiaoguangHu01 approved these changes
LGTM

2022-10-20 11:03 UTC, ZeyuChen approved these changes

2022-10-20 12:19 UTC, zh794390558 approved these changes
LGTM

2022-10-20 12:21 UTC, merged