Fix the En docs (delete some expression like 'This OP')
PaddlePaddle/Paddle pull request #46165
Opened 2022-09-17 17:06 UTC by Liyulingyue

### PR types

Others 
### PR changes

Docs 
### Describe

1. Delete some expression like 'This Op'
2. remove import numpy as np

2022-09-18 17:34 UTC, SigureMo commented
<img width="606" alt="image" src="https://user-images.githubusercontent.com/38436475/190920691-d0a3fbe3-53e8-4571-bf5b-4c46c794360e.png">

分布式和 fluid 先回撤吧

2022-09-18 17:58 UTC, SigureMo requested changes

2022-09-18 17:58 UTC, SigureMo commented on python/paddle/nn/functional/norm.py
> +          x = paddle.rand((2, 2, 3))
数据 shape 改错了，InstanceNorm2D 和 3D 也改错了

2022-09-18 17:58 UTC, SigureMo commented on python/paddle/nn/layer/norm.py
>            layer_norm = paddle.nn.LayerNorm(x_data.shape[1:])
```
2022-09-18 18:09:42 /usr/local/python3.7.0/lib/python3.7/site-packages/requests/__init__.py:43: DeprecationWarning: 'urllib3[secure]' extra is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
2022-09-18 18:09:42   import urllib3
2022-09-18 18:09:42 Traceback (most recent call last):
2022-09-18 18:09:42   File "samplecode_temp/paddle.nn.LayerNorm_example.py", line 6, in <module>
2022-09-18 18:09:42     layer_norm = paddle.nn.LayerNorm(x_data.shape[1:])
2022-09-18 18:09:42 NameError: name 'x_data' is not defined
```

这里也要改成 `x`

2022-09-18 17:58 UTC, SigureMo commented on python/paddle/nn/functional/loss.py
>              pred_loss = F.kl_div(paddle.to_tensor(input),
```
2022-09-18 18:11:24 print("paddle.nn.functional.kl_div's sample code (name:None, id:1) is executed successfully!")
2022-09-18 18:11:24 -----------------------
2022-09-18 18:11:24 subprocess return code: 1
2022-09-18 18:11:24 Error Raised from Sample Code:
2022-09-18 18:11:24 stderr: W0918 10:11:22.134946  2804 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 11.2
2022-09-18 18:11:24 W0918 10:11:22.141083  2804 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
2022-09-18 18:11:24 /usr/local/python3.7.0/lib/python3.7/site-packages/requests/__init__.py:43: DeprecationWarning: 'urllib3[secure]' extra is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
2022-09-18 18:11:24   import urllib3
2022-09-18 18:11:24 Traceback (most recent call last):
2022-09-18 18:11:24   File "samplecode_temp/paddle.nn.functional.kl_div_example.py", line 10, in <module>
2022-09-18 18:11:24     pred_loss = F.kl_div(paddle.to_tensor(input),
2022-09-18 18:11:24   File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/tensor/creation.py", line 469, in to_tensor
2022-09-18 18:11:24     return _to_tensor_non_static(data, dtype, place, stop_gradient)
2022-09-18 18:11:24   File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/tensor/creation.py", line 319, in _to_tensor_non_static
2022-09-18 18:11:24     .format(type(data)))
2022-09-18 18:11:24 TypeError: Can't constructs a 'paddle.Tensor' with data type <class 'builtin_function_or_method'>, data type must be scalar|list|tuple|np.ndarray|paddle.Tensor
2022-09-18 18:11:24 
```

看到这 log 我还愣了会，后来才反应过来是 built-in 的 input 函数被传进 `to_tensor` 了 :joy:

```suggestion
            pred_loss = F.kl_div(x,
```

下同

2022-09-18 17:58 UTC, SigureMo commented on python/paddle/nn/functional/norm.py
> +          x = paddle.rand((2, 2, 2, 3)))
```suggestion
          x = paddle.rand((2, 2, 2, 3))
```

（╯‵□′）╯︵┴─┴

2022-09-18 22:35 UTC, Liyulingyue commented
> <img alt="image" width="606" src="https://user-images.githubusercontent.com/38436475/190920691-d0a3fbe3-53e8-4571-bf5b-4c46c794360e.png">
> 
> 分布式和 fluid 先回撤吧

尴尬在于我没找到单独文件的撤回按钮哈哈哈哈哈哈，先把其他改了再跑一版看看哈哈哈

2022-09-19 04:40 UTC, SigureMo commented
> 尴尬在于我没找到单独文件的撤回按钮哈哈哈哈哈哈，先把其他改了再跑一版看看哈哈哈

```bash
git checkout <git_hash> -- <file_path1> <file_path2> <file_path3> ...
```

这个可以将 file_path1、2、3 回撤到 git_hash 时的状态

比如

```bash
# 将 python/paddle/distributed/collective.py 回撤到 develop
git checkout develop -- python/paddle/distributed/collective.py

# 将 fluid 目录全部回撤到 develop
git checkout develop -- 'python/paddle/fluid/*'
```

2022-09-19 16:55 UTC, SigureMo submitted a review, later dismissed
LGT喵喵喵 for docs

2022-09-21 12:16 UTC, Ligoml approved these changes, later dismissed
good job！LGTM

2022-09-22 07:43 UTC, Ligoml approved these changes

2022-09-22 10:39 UTC, XiaoguangHu01 approved these changes
LGTM

2022-09-22 10:51 UTC, merged