[MLU] add barrier_op kernel.
PaddlePaddle/Paddle pull request #46417
Opened 2022-09-22 12:21 UTC by ShawnNew

### PR types

New features

### PR changes

OPs

### Describe

add mlu barrier use cnclAllReduce sum.

2022-09-22 12:34 UTC, ronny1996 requested changes

2022-09-22 12:34 UTC, ronny1996 commented on paddle/fluid/operators/collective/barrier_op_mlu.cc
> +/* Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2020 -> 2022

2022-09-22 12:43 UTC, ShawnNew commented on paddle/fluid/operators/collective/barrier_op_mlu.cc
> +/* Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
Done

2022-09-23 02:49 UTC, chenwhql approved these changes

2022-09-23 03:22 UTC, ronny1996 approved these changes
LGTM

2022-09-23 04:46 UTC, merged