[MLU] fluid: add mluop
PaddlePaddle/Paddle pull request #46429
Opened 2022-09-23 02:44 UTC by cifar10

[[MLU] fluid: add mluOp](https://github.com/PaddlePaddle/Paddle/pull/46397)
### PR types
New features

### PR changes
OPs

### Describe
add pre modified: https://github.com/PaddlePaddle/Paddle/pull/45967/commits/d6f8a522cfdf4f0a2366e5cd25ed06e152f9d01b

add fluid  mluop

2022-09-23 08:57 UTC, ShawnNew approved these changes, later dismissed
👍

2022-09-23 08:57 UTC, ShawnNew commented on paddle/fluid/operators/mlu/mlu_baseop.h
> +  static void OpAbs(const ExecutionContext& ctx,
delete

2022-09-26 03:06 UTC, ronny1996 requested changes

2022-09-26 03:06 UTC, ronny1996 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +//     const ExecutionContext& ctx,
不需要的代码可以删掉

2022-09-26 03:53 UTC, cifar10 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +//     const ExecutionContext& ctx,
已修改

2022-09-26 06:03 UTC, cifar10 commented on paddle/fluid/operators/mlu/mlu_baseop.h
> +  static void OpAbs(const ExecutionContext& ctx,
已修改

2022-09-26 07:24 UTC, qili93 approved these changes
LGTM

2022-09-26 07:41 UTC, ronny1996 approved these changes

2022-09-26 07:41 UTC, merged