[MLU] add huber_loss kernel.
PaddlePaddle/Paddle pull request #46455
Opened 2022-09-23 10:18 UTC by ShawnNew

### PR types

New features

### PR changes

OPs

### Describe

add huber loss for mlu, depends on [PR46426](https://github.com/PaddlePaddle/Paddle/pull/46429)

2022-09-26 08:17 UTC, ronny1996 requested changes

2022-09-26 08:17 UTC, ronny1996 commented on paddle/fluid/operators/huber_loss_op_mlu.cc
> +/* Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
2022

2022-09-26 08:20 UTC, ShawnNew commented on paddle/fluid/operators/huber_loss_op_mlu.cc
> +/* Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Done

2022-09-26 13:17 UTC, qili93 submitted a review, later dismissed
LGTM

2022-09-27 02:35 UTC, chenwhql commented on paddle/fluid/operators/huber_loss_op_mlu.cc
> +using Tensor = framework::Tensor;
麻烦直接using Tensor = phi::DenseTensor; 或者只用使用 phi::DenseTensor，这里有历史遗留问题，正在全局删除

https://github.com/PaddlePaddle/Paddle/pull/46432

2022-09-27 07:32 UTC, ShawnNew commented on paddle/fluid/operators/huber_loss_op_mlu.cc
> +using Tensor = framework::Tensor;
Done

2022-09-27 12:13 UTC, qili93 approved these changes
LGTM

2022-09-27 12:13 UTC, ronny1996 approved these changes

2022-09-27 12:25 UTC, chenwhql approved these changes

2022-09-27 12:34 UTC, merged