[MLU] add_fluid_mluop_yolo_box
PaddlePaddle/Paddle pull request #46573
Opened 2022-09-27 13:29 UTC by Ashelly1

### PR types

New features 
### PR changes

 OPs
### Describe

add mluop yolo_box kernel

2022-09-28 06:51 UTC, ShawnNew requested changes

2022-09-28 06:51 UTC, ShawnNew commented on paddle/fluid/operators/detection/CMakeLists.txt
> -detection_library(yolo_box_op SRCS yolo_box_op.cc)
这里不要修改别人的代码

2022-09-28 06:51 UTC, ShawnNew commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    MLUOpTensorDesc tmp_boxes_desc(
boxes_trans_desc_mluops
boxes_trans_desc_cnnl
scores_trans_desc_mluops
scores_trans_desc_cnnl

2022-09-28 06:51 UTC, ShawnNew commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    MLUCnnlTensorDesc boxes_out_desc(
boxes_desc_cnnl
scores_desc_cnnl

2022-09-28 06:51 UTC, ShawnNew commented on python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
> +    # def test_eager(self):
delete

2022-09-28 07:49 UTC, Ashelly1 commented on paddle/fluid/operators/detection/CMakeLists.txt
> -detection_library(yolo_box_op SRCS yolo_box_op.cc)
已修改，至else

2022-09-28 07:49 UTC, Ashelly1 commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    MLUOpTensorDesc tmp_boxes_desc(
已修改

2022-09-28 07:49 UTC, Ashelly1 commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    MLUCnnlTensorDesc boxes_out_desc(
已修改

2022-09-28 07:49 UTC, Ashelly1 commented on python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
> +    # def test_eager(self):
这里无法delete

2022-09-28 08:27 UTC, Ashelly1 commented on python/paddle/fluid/tests/unittests/mlu/test_yolo_box_op_mlu.py
> +    # def test_eager(self):
已修改

2022-09-28 09:39 UTC, ronny1996 approved these changes

2022-09-28 09:41 UTC, ronny1996 requested changes

2022-09-28 09:41 UTC, ronny1996 commented on paddle/fluid/operators/detection/CMakeLists.txt
> +  detection_library(yolo_box_op SRCS yolo_box_op.cc)
这里需要添加吗？

2022-09-28 09:54 UTC, Ashelly1 commented on paddle/fluid/operators/detection/CMakeLists.txt
> +  detection_library(yolo_box_op SRCS yolo_box_op.cc)
需要添加，原本非mlu条件下，也是有detection_library(yolo_box_op SRCS yolo_box_op.cc)的

2022-09-28 10:17 UTC, ronny1996 submitted a review, later dismissed

2022-09-29 07:52 UTC, chenwhql approved these changes, later dismissed

2022-09-29 07:52 UTC, chenwhql commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    auto* img_size = ctx.Input<framework::LoDTensor>("ImgSize");
这个后续也请不要再使用了，请直接使用phi::DenseTensor，背景见：https://github.com/PaddlePaddle/Paddle/pull/46432

2022-09-29 08:55 UTC, qili93 submitted a review, later dismissed
LGTM

2022-09-30 02:25 UTC, Ashelly1 commented on paddle/fluid/operators/detection/yolo_box_op_mlu.cc
> +    auto* img_size = ctx.Input<framework::LoDTensor>("ImgSize");
framework::LoDTensor已修改为phi::DenseTensor

2022-09-30 06:34 UTC, ronny1996 approved these changes

2022-09-30 06:41 UTC, chenwhql approved these changes

2022-09-30 07:00 UTC, qili93 approved these changes
LGTM

2022-09-30 07:29 UTC, merged