[MLU] add mluops prior_box kernel
PaddlePaddle/Paddle pull request #46585
Opened 2022-09-28 07:00 UTC by cifar10

### PR types
New features

### PR changes
OPs

### Describe
add mluops prior_box kernel

2022-09-28 07:03 UTC, ShawnNew approved these changes, later dismissed
等 [46573](https://github.com/PaddlePaddle/Paddle/pull/46573) 合入之后，你rebase一下。再合入哈

2022-09-30 09:38 UTC, cifar10 commented
> 等 [46573](https://github.com/PaddlePaddle/Paddle/pull/46573) 合入之后，你rebase一下。再合入哈

已rebase

2022-09-30 09:43 UTC, ShawnNew approved these changes
👍

2022-10-08 03:16 UTC, ronny1996 requested changes

2022-10-08 03:16 UTC, ronny1996 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +    const int im_height,
不使用的代码可以删除

2022-10-08 03:23 UTC, cifar10 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +    const int im_height,
需要在prior_box_op_mlu.cc中使用该函数以及参数

2022-10-08 03:31 UTC, ronny1996 approved these changes

2022-10-08 08:43 UTC, chenwhql approved these changes

2022-10-08 08:47 UTC, merged