add function FindInputNameByVarName
PaddlePaddle/Paddle pull request #46759
Opened 2022-10-05 17:15 UTC by sfraczek

### PR types
Function optimization

### PR changes
OPs

### Describe
Add functions for a functionality that is repeated multiple times throughout files.

2022-10-07 10:03 UTC, tsocha requested changes

2022-10-07 10:03 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +
`FindInputNameByVarName` is duplicated in two files already.
Please move it to common place to avoid code duplication.

2022-10-07 10:03 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/scale_matmul_fuse_pass.cc
> +
Already defined above.

2022-10-07 10:10 UTC, jakpiase commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +  for (auto name : op->InputNames())
What do you think about using `const & auto here and below?

2022-10-09 13:11 UTC, sfraczek commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +  for (auto name : op->InputNames())
ok

2022-10-09 13:11 UTC, sfraczek commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +
ok but it will cost extra code and extra lines and extra include files which I wanted to avoid.

2022-10-09 18:38 UTC, sfraczek commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +
ok

2022-10-10 06:52 UTC, tsocha approved these changes

2022-10-10 08:08 UTC, jczaja approved these changes
LGTM

2022-10-10 08:08 UTC, merged