[MLU]add mlu kernel for warpctcloss and warpctcloss_grad op
PaddlePaddle/Paddle pull request #46989
Opened 2022-10-13 08:46 UTC by fuyou765

### PR types
New features

### PR changes
OPs

### Describe
添加 warpctcloss 和 warpctcloss_grad 算子的mlu kernel及对应pytest

2022-10-13 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=46989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=46989) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=46989) it.</sub>

2022-10-13 08:58 UTC, fuyou765 commented
warpctcloss,warpctcloss_grad
<img width="786" alt="warpctc" src="https://user-images.githubusercontent.com/64373205/195551856-7188a162-6168-42f4-a511-43b20c278484.png">

2022-10-18 07:41 UTC, ShawnNew requested changes

2022-10-18 07:41 UTC, ShawnNew commented on paddle/fluid/operators/warpctc_op.cc
> +#ifdef PADDLE_WITH_MLU
这里尽量不要修改原本op的定义

2022-10-18 07:41 UTC, ShawnNew commented on paddle/fluid/operators/warpctc_op.cc
> +#ifndef PADDLE_WITH_MLU
尽量保证op.cc不要修改

2022-10-18 07:41 UTC, ShawnNew commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +MLUCnnlCTCLossDesc::MLUCnnlCTCLossDesc(
CTCLossDesc可以直接在实现时定义，不用单独封装哈

2022-10-18 07:41 UTC, ShawnNew commented on paddle/fluid/operators/mlu/mlu_baseop.h
> +  static void CTCLoss(const ExecutionContext& ctx,
空行保留

2022-10-18 08:18 UTC, fuyou765 commented on paddle/fluid/operators/warpctc_op.cc
> +#ifdef PADDLE_WITH_MLU
这是适配ctcloss算子必须增加的定义

2022-10-18 08:18 UTC, fuyou765 commented on paddle/fluid/operators/warpctc_op.cc
> +#ifndef PADDLE_WITH_MLU
这是适配ctcloss算子必须增加的定义

2022-10-18 08:26 UTC, fuyou765 commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +MLUCnnlCTCLossDesc::MLUCnnlCTCLossDesc(
不太清楚什么意思，之前的代码不都是统一这样封装的吗？

2022-10-18 08:31 UTC, fuyou765 commented on paddle/fluid/operators/mlu/mlu_baseop.h
> +  static void CTCLoss(const ExecutionContext& ctx,
已修改

2022-10-19 12:05 UTC, ShawnNew commented on paddle/fluid/operators/mlu/mlu_baseop.cc
> +MLUCnnlCTCLossDesc::MLUCnnlCTCLossDesc(
这里desc直接使用就好，不用包一层，意义不大

2022-10-19 12:06 UTC, ShawnNew commented on paddle/fluid/operators/warpctc_op.cc
> +#ifndef PADDLE_WITH_MLU
npu有做相关算子定义修改吗？

2022-10-28 08:32 UTC, ShawnNew submitted a review, later dismissed
👍

2024-09-03 06:33 UTC, closed without merging