Add Op Embeddingbag
PaddlePaddle/Paddle pull request #47018
Opened 2022-10-14 08:10 UTC by JianmingGuo

### PR types
New features

### PR changes
OPs

### Describe
Add operator Embeddingbag. This is a project supported by GLCC and guided by Yujun.(https://www.gitlink.org.cn/glcc/subjects/detail/29)
I used AI Studio to develop the module. Thanks for the support!

2022-10-14 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=47018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=47018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=47018) it.</sub>

2022-10-19 05:52 UTC, JunnYu commented
@JianmingGuo 哈喽，
- 请先签一下CLA assistant check，然后CI才能进行下面的测试。
- 代码中删除一些无用的注释信息，注释信息请用英文适当注释。

2022-10-20 02:28 UTC, JunnYu commented on paddle/fluid/operators/embeddingbag_op.cc
> +        //     .SetDefault(std::vector<int64_t>({}));
一些无用的注释需要清理。

2022-10-20 02:29 UTC, JunnYu commented on paddle/fluid/operators/embeddingbag_op.cc
> +// 定义OperatorWithKernel & InferShape()
建议这些都使用英文注释一下

2022-10-20 02:31 UTC, JianmingGuo commented on paddle/fluid/operators/embeddingbag_op.cc
> +// 定义OperatorWithKernel & InferShape()
Got！稍后修改。

2022-11-07 00:26 UTC, JunnYu reviewed
中文注释都可以去掉

2022-11-07 00:27 UTC, JunnYu requested changes
改成2022年

2022-11-08 01:47 UTC, JunnYu commented on python/paddle/nn/functional/input.py
> -# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已有文件的 年份 应该不需要修改，你新建的文件需要2022

2022-11-08 13:38 UTC, JunnYu approved these changes, later dismissed
LGTM

2022-12-05 02:52 UTC, luotao1 commented
1. 可以重新从develop checkout 一个分支b，在分支上加上你的代码: git checkout embeddingbag xxx.cc 
2. 将原分支重命名为任意的，将新分支b重命名为embeddingbag，git push -f 上来

2022-12-05 15:40 UTC, closed without merging