slice op supports uint8_t
PaddlePaddle/Paddle pull request #47067
Opened 2022-10-17 09:35 UTC by will-jl944

### PR types
New features

### PR changes
APIs

### Describe
`slice` op supports uint8_t.

2022-10-18 06:33 UTC, chenwhql approved these changes

2022-10-18 06:34 UTC, chenwhql requested changes

2022-10-18 06:34 UTC, chenwhql commented on paddle/fluid/operators/slice_op.cc
> +    ops::SliceKernel<phi::CPUContext, uint8_t>,
这里好像错用了前向

2022-10-18 06:34 UTC, chenwhql commented on paddle/fluid/operators/slice_op.cc
> +    ops::SliceKernel<phi::CPUContext, uint8_t>,
同上，CI查不到的话建议加个单测

2022-10-18 06:40 UTC, will-jl944 commented on paddle/fluid/operators/slice_op.cc
> +    ops::SliceKernel<phi::CPUContext, uint8_t>,
已修改，感谢

2022-10-18 06:40 UTC, will-jl944 commented on paddle/fluid/operators/slice_op.cc
> +    ops::SliceKernel<phi::CPUContext, uint8_t>,
已修改，感谢

2022-10-19 03:03 UTC, chenwhql approved these changes

2022-10-19 03:07 UTC, merged