[Auto Parallel] Add matmul flops
PaddlePaddle/Paddle pull request #47816
Opened 2022-11-09 12:54 UTC by CjhHa1

### PR types

 New features
### PR changes

Others
### Describe

This PR adds matmul and matmul_v2 flops computation func.

2022-11-09 12:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=47816) <br/>All committers have signed the CLA.

2022-11-09 12:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=47816) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=47816) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=47816) it.</sub>

2022-11-15 06:34 UTC, kuizhiqing requested changes

2022-11-15 06:34 UTC, kuizhiqing commented on python/paddle/utils/flops.py
> +    input_x = input_shapes[0]
some index check would be better.

2022-11-15 09:56 UTC, kuizhiqing requested changes

2022-11-15 09:56 UTC, kuizhiqing commented on python/paddle/fluid/tests/unittests/test_profiler.py
> +        )
add unitest for dict input shape

2022-11-15 09:56 UTC, kuizhiqing commented on python/paddle/utils/flops.py
> +    try:
maybe move try catch to the api function `flops`, no need do it in all funcs.

2022-11-15 10:01 UTC, CjhHa1 commented
Get,thx

From: Zhiqing Kui ***@***.***>
Date: Tuesday, November 15, 2022 at 17:57
To: PaddlePaddle/Paddle ***@***.***>
Cc: Jianghai ***@***.***>, Author ***@***.***>
Subject: Re: [PaddlePaddle/Paddle] [Auto Parallel] Add matmul flops (PR #47816)

@kuizhiqing requested changes on this pull request.

________________________________

In python/paddle/fluid/tests/unittests/test_profiler.py<https://github.com/PaddlePaddle/Paddle/pull/47816#discussion_r1022578125>:

> +            flops('elementwise_add', ([12, 12, 12], [2, 2, 12])) == 12 * 12 * 12

+        )

+        self.assertTrue(

+            flops('elementwise_mul', ([12, 12, 12], [2, 2, 12])) == 12 * 12 * 12

+        )

+        self.assertTrue(

+            flops('elementwise_div', ([12, 12, 12], [2, 2, 12])) == 12 * 12 * 12

+        )

+        self.assertTrue(

+            flops(

+                'layer_norm',

+                ([12, 12, 12], [12, 12, 12], [12, 12, 12]),

+                **{'epsilon': 0.01}

+            )

+            == 12 * 12 * 12 * 8

+        )

add unitest for dict input shape

________________________________

In python/paddle/utils/flops.py<https://github.com/PaddlePaddle/Paddle/pull/47816#discussion_r1022579053>:

> @@ -55,6 +55,147 @@ def _dropout_flops(input_shapes, **attrs):

     return 0





+def _elementwise_flops_compute(input_shapes, **attrs):

+    try:

maybe move try catch to the api function flops, no need do it in all funcs.

—
Reply to this email directly, view it on GitHub<https://github.com/PaddlePaddle/Paddle/pull/47816#pullrequestreview-1180563469>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARJ2PHS4W5QMCQIXHXHJX7LWINM7PANCNFSM6AAAAAAR3M264I>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-23 06:38 UTC, aoyulong commented on python/paddle/utils/flops.py
> +    flops computation for elementwise_add op
Please write the comment in a standard way.

2022-11-23 06:38 UTC, aoyulong commented on python/paddle/utils/flops.py
> +def _soft_max_flops(input_shapes, attrs):
Please rename `_soft_max` to `softmax`.

2022-11-24 01:32 UTC, kuizhiqing requested changes
/hold /do-not-merge

2022-11-28 02:23 UTC, aoyulong approved these changes
LGTM

2022-11-28 02:35 UTC, JZ-LIANG approved these changes
LGTM

2022-11-28 02:36 UTC, merged