Recompute upgrade
PaddlePaddle/Paddle pull request #47985
Opened 2022-11-15 03:19 UTC by wuhuachaocoding

### PR types

New features
### PR changes

Others
### Describe

Recompute upgrade:
in the past, there is just one PyLayer implementation of recompute, here , this PR adds other hook implementation of recompute.

2022-11-23 02:14 UTC, gongweibao requested changes
Modify docs and put the link to comments.

2022-11-23 02:14 UTC, gongweibao commented on python/paddle/distributed/fleet/recompute/recompute.py
> +    if preserve_rng_state:
User can't use CPU or other XXPU?

2022-11-23 02:14 UTC, gongweibao commented on python/paddle/distributed/fleet/recompute/recompute.py
> +        amp_dtype = 'bfloat16'
float32->bfloat16?

2022-11-23 02:14 UTC, gongweibao commented on python/paddle/distributed/fleet/recompute/recompute.py
> +    tracer = framework._dygraph_tracer()
Are these functions all internal functions with _?

2022-11-23 02:14 UTC, gongweibao commented on python/paddle/distributed/fleet/recompute/recompute.py
>  from paddle.fluid import core
Don't use fluid

2022-11-25 09:39 UTC, ForFishes submitted a review, later dismissed
LGTM

2022-12-19 08:59 UTC, sljlp commented on python/paddle/distributed/fleet/recompute/recompute.py
OK

2022-12-19 09:02 UTC, wuhuachaocoding commented on python/paddle/distributed/fleet/recompute/recompute.py
> +    if preserve_rng_state:
only support GPU to preserve rng state now.

2022-12-19 09:02 UTC, wuhuachaocoding commented on python/paddle/distributed/fleet/recompute/recompute.py
> +    tracer = framework._dygraph_tracer()
yes, and only use this way to get tracer from python, the name of _dygraph_tracer is defined by framewark.

2022-12-19 09:02 UTC, wuhuachaocoding commented on python/paddle/distributed/fleet/recompute/recompute.py
> +        amp_dtype = 'bfloat16'
auto_cast supports two dtypes: float16 and bfloat16.
![image](https://user-images.githubusercontent.com/77733235/203488688-5600c26b-2ba4-4f9b-b063-d946f30990ee.png)

2022-12-19 09:02 UTC, wuhuachaocoding commented on python/paddle/distributed/fleet/recompute/recompute.py
>  from paddle.fluid import core
DONE

2022-12-19 09:02 UTC, wuhuachaocoding commented on python/paddle/distributed/fleet/recompute/recompute.py
ok

2022-12-20 08:37 UTC, gongweibao approved these changes
LGTM

2022-12-20 08:37 UTC, merged