Rewrite conv activation mkldnn fuse pass tester
PaddlePaddle/Paddle pull request #49278
Opened 2022-12-22 13:41 UTC by HulekJakub

### PR types
Others

### PR changes
Others

### Describe
Deleted old C++ conv activation mkldnn fuse pass test and updated python one

Currently in PaddlePaddle there are 3 unit-test frameworks - one written in C++ and 2 in Python.
Old fuse pass tests (C++) fuse_pass_tester.cc are checking only if graph has correct number of / type of vertices after fusion. It doesn't check data. So these tests pass even if accuracy drops.
New python framework is superior because it checks both graph fusion and accuracy after fusion.

2023-01-03 11:17 UTC, Silv3S requested changes

2023-01-03 11:17 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_onednn_fuse_pass.py
>          conv2d
I'd remove this mini-graph

2023-01-03 11:17 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_onednn_fuse_pass.py
>          # MKLDNN
```suggestion
```

2023-01-03 11:17 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_conv_act_onednn_fuse_pass.py
> +                    'hard_swish',
This list is not complete. Please add all activations from _onednn_reuse.h_ `GetSupportedActivations()` 
```suggestion
                    'abs',
                    'clip',
                    'gelu',
                    'hard_sigmoid',
                    'hard_swish',
                    'leaky_relu',
                    'mish',
                    'relu',
                    'relu6',
                    'sigmoid',
                    'sqrt',
                    'swish',
                    'tanh'
```

2023-01-30 13:27 UTC, Silv3S commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +                  act_types.end());
Please remove OpCompat related to `sqrt`
- AddOpCompat(OpCompat("sqrt"))
- .EQ("sqrt", 0)

2023-02-01 11:24 UTC, Silv3S approved these changes, later dismissed

2023-02-03 10:50 UTC, Silv3S approved these changes, later dismissed

2023-02-13 10:26 UTC, Silv3S approved these changes

2023-02-13 10:28 UTC, HulekJakub commented
@XieYunshen please approve changes to unit tests

2023-02-13 11:23 UTC, XieYunshen approved these changes
LGTM for test rewrite

2023-02-15 08:59 UTC, jczaja approved these changes
LGTM

2023-02-15 08:59 UTC, merged