add bool type for paddle_infer::Tensor
PaddlePaddle/Paddle pull request #49388
Opened 2022-12-28 04:32 UTC by yuanlehome

### PR types

Others
### PR changes

Others
### Describe

add bool type for paddle_infer::Tensor

2022-12-29 03:39 UTC, jiweibo requested changes
python的相关接口处理还需要支持下bool

2023-01-03 03:03 UTC, jiweibo approved these changes
LGTM

2023-01-03 03:12 UTC, From00 approved these changes
LGTM for `mutable_data`

2023-01-03 03:44 UTC, leiqing1 approved these changes

2023-01-03 11:26 UTC, merged