[OpAttr]Fix Ignore AttriteTensor in IndicateDataType bug in grad_op
PaddlePaddle/Paddle pull request #49472
Opened 2022-12-30 09:12 UTC by Aurelius84

### PR types

Bug fixes
### PR changes

Others
### Describe

[OpAttr]Fix Ignore AttriteTensor in IndicateDataType bug in grad_op

2022-12-30 09:21 UTC, iclementine requested changes

2022-12-30 09:21 UTC, iclementine commented on paddle/fluid/framework/operator.cc
> +  size_t pos = Type().find("_grad");
这么做不够安全。有的反向算子的名字，并不是截去第一个 "_grad" 以及后续的部分得到的就是它的正向算子的名字。比如说，abs_double_grad。

代码依赖这种 naming convention 来运作感觉不太好。

2023-01-03 02:33 UTC, Aurelius84 commented on paddle/fluid/framework/operator.cc
> +  size_t pos = Type().find("_grad");
改为了GetExpectedKernelType函数

2023-01-03 06:22 UTC, iclementine approved these changes
LGTM

2023-01-03 06:33 UTC, merged