[Custom Device] update get_device to custom
PaddlePaddle/Paddle pull request #49721
Opened 2023-01-11 03:15 UTC by YanhuiDua

### PR types
Others 

### PR changes
Others

### Describe
1. Add CustomPlace in `_current_expected_place()`. 
2. Expose `get_custom_device_count(const std::string &device_type)` API for _current_expected_place()

2023-01-11 07:04 UTC, qili93 commented on paddle/fluid/pybind/pybind.cc
> +    device_count = phi::DeviceManager::GetDeviceCount(device_type);
当前 PR可以，后续考虑优化方向如下：

1. 之前设计的时候为了满足多个硬件同事注册的需求，DeviceManager 支撑一个编译包注册多个硬件类型，所以需要通过输入 device_type 来判断当前注册的实际的 device impl 的对象
2. 但是实际的用户场景下，90%以上都是除了 CPU 外只有一个单独硬件注册的场景，比如要么昇腾、要么寒武纪，基低的概率才会出现一个安装包里面同时存在2款硬件的情况

所以后续可以考虑这里修改 DeviceManager 里面逻辑，当判断 DeviceManager 里面 device_impl_map_ 的注册数量为1的时候，device_type 输入可以为空。就是通过调用 `phi::DeviceManager::GetDeviceCount()` 直接返回唯一被注册的硬件。

这个可以后续对 DeviceManager 进行统一优化。

2023-01-11 07:04 UTC, qili93 commented on python/paddle/fluid/framework.py
> +                    device_count = core.get_custom_device_count("npu")
同上，当前 PR 是可以的，后续优化方向如下：

1. 增加 core.is_compiled_with_custom_device() 接口替换 649 行
2. 修改 DeviceManager 之后，652行可以直接返回 device_count = core.get_custom_device_count()
3. 同时新增逻辑判断 DeviceManger 中已经注册的硬件数量，如果 > 1，则这里需要增加 if else 分支判断；并返回多个 expected places 而不是一个

2023-01-11 07:04 UTC, qili93 commented on python/paddle/fluid/framework.py
> +        device_ids = range(core.get_custom_device_count("npu"))
这里建议新增接口为 _device_ids(device_type)，代码返回 device_ids = range(core.get_custom_device_count(device_type))

因为这里的 _npu_ids 是原有的 builtin NPU 的代码接口在其他地方会被调用到，后续可以考虑统一清理。

2023-01-11 07:04 UTC, qili93 commented on python/paddle/fluid/framework.py
> +                    )
这里可以直接返回 _global_expected_place_ = core.CustomPlace("npu") 不带 id 也是支持的

2023-01-12 02:45 UTC, qili93 approved these changes
LGTM

2023-01-12 02:48 UTC, qili93 commented on python/paddle/__init__.py
> +from .device import is_compiled_with_custom_device  # noqa: F401
确认下这个 is_compiled_with_custom_device 对外暴露吗？需要的话，要把它加到 __init__.py 的 __all__里面，然后再 doc repo 里面新增对应的中文 API说明文档

2023-01-12 02:51 UTC, qili93 requested changes

2023-01-12 02:51 UTC, qili93 commented on python/paddle/fluid/framework.py
> +            support_npu = fluid.is_compiled_with_custom_device("npu")
这里的 is_compiled_with_custom_device 重复定义了？

2023-01-12 13:44 UTC, qili93 approved these changes
LGTM

2023-01-13 02:47 UTC, YanhuiDua commented
docs related PR : https://github.com/PaddlePaddle/docs/pull/5585

2023-01-13 06:20 UTC, qingqing01 approved these changes
LGTM for API

2023-01-13 06:36 UTC, Ligoml approved these changes
LGTM for docs

2023-01-13 08:55 UTC, merged