[Paddle Inference]Support PaddlePaddle Backend on Triton
PaddlePaddle/Paddle pull request #49758
Opened 2023-01-11 16:28 UTC by heliqi

### PR types
Others

### PR changes
Others

### Describe
1. CPP 增加获取输出shape、dtype信息接口，用于服务化部署
2. C API增加SetExecStream、EnableMkldnnInt8等C++已有接口，用于服务化部署
3. 修复C API参数跟CPP API参数不对齐接口(缺一些默认参数)

2023-01-11 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=49758) <br/>All committers have signed the CLA.

2023-01-17 07:15 UTC, jiangjiajun requested changes

2023-01-17 07:15 UTC, jiangjiajun commented on paddle/fluid/inference/capi_exp/pd_config.h
> +    PD_PrecisionType precision_mode);
这里看起来是不兼容升级，是否之前用了这个API的代码会出错？

2023-01-17 07:36 UTC, heliqi commented on paddle/fluid/inference/capi_exp/pd_config.h
> +    PD_PrecisionType precision_mode);
Done

2023-01-17 07:42 UTC, jiangjiajun submitted a review, later dismissed
LGTM

2023-01-18 10:00 UTC, qingqing01 approved these changes

2023-01-19 03:35 UTC, merged