Fix Python IndexError of Case14: paddle.nn.functional.glu
PaddlePaddle/Paddle pull request #50016
Opened 2023-01-23 01:02 UTC by longranger2

### PR types
Bug fixes 

### PR changes
APIs 

### Describe
- https://github.com/PaddlePaddle/Paddle/issues/49923
- https://github.com/PaddlePaddle/Paddle/issues/49927

### Solution
为split增加取值范围维度的判断

2023-01-30 07:39 UTC, wanghuancoder reviewed
为这个case加个单测吧

2023-01-30 07:39 UTC, wanghuancoder commented on python/paddle/tensor/manipulation.py
> +        assert dim < len(input.shape), "axis must < (rank(x)"
(rank(x)是不是应该改成rank(x)

2023-01-30 07:39 UTC, wanghuancoder commented on python/paddle/tensor/manipulation.py
> +            assert dim < len(input.shape), "axis must < (rank(x)"
同上

2023-01-30 07:52 UTC, longranger2 commented on python/paddle/tensor/manipulation.py
> +        assert dim < len(input.shape), "axis must < (rank(x)"
对的，我的疏忽

2023-01-30 07:53 UTC, longranger2 commented
单侧我今天搞定

2023-02-05 15:08 UTC, longranger2 commented
> 为这个case加个单测吧

单侧添加好了

2023-02-06 06:27 UTC, wanghuancoder approved these changes, later dismissed
LGTM

2023-02-06 07:03 UTC, iclementine requested changes

2023-02-06 07:03 UTC, iclementine commented on python/paddle/nn/functional/activation.py
> +    assert axis < len(x.shape), "axis must < rank(x)"
I think it's better to check `-R <= axis < R` because this is more precise.
Also, to report the expected behavior and what actually happened is more informative.

For example
```python
rank = x.shape
if not (-rank <= axis < axis):
    raise ValueError("Expected value range of `axis` is [{}, {}), but received axis: {}".format(-rank, rank, axis))
```

2023-02-06 08:03 UTC, longranger2 commented on python/paddle/nn/functional/activation.py
> +    assert axis < len(x.shape), "axis must < rank(x)"
Thank you for your advice. I will fix it later

2023-02-07 09:21 UTC, iclementine approved these changes
LGTM

2023-02-10 06:20 UTC, merged