Rewrite mkldnn conv bn fuse pass tester
PaddlePaddle/Paddle pull request #50034
Opened 2023-01-27 12:11 UTC by HulekJakub

PR types
Others

PR changes
Others

Describe
Deleted old C++ conv activation mkldnn fuse pass test and updated python one

Currently in PaddlePaddle there are 3 unit-test frameworks - one written in C++ and 2 in Python.
Old fuse pass tests (C++) fuse_pass_tester.cc are checking only if graph has correct number of / type of vertices after fusion. It doesn't check data. So these tests pass even if accuracy drops.
New python framework is superior because it checks both graph fusion and accuracy after fusion.

This change adds dedicated test for onednn conv_bn_fuse_pass 
It also fixes issue when model is using mkldnn and convolution has bias

2023-01-30 08:37 UTC, Silv3S requested changes

2023-01-30 08:37 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_bn_fuse_pass.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
```suggestion
# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
```

2023-01-30 08:37 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_bn_fuse_pass.py
> +            return np.random.random(var_shape).astype(np.float32)
maybe create one method with shape passed as argument

2023-01-30 08:37 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_bn_fuse_pass.py
> +        print(program_config.weights)
```suggestion
        print(conv2d_op.inputs)
        print(program_config.weights)
```

2023-01-30 08:37 UTC, Silv3S commented on python/paddle/fluid/tests/unittests/ir/inference/test_onednn_conv_bn_fuse_pass.py
> +        return True
```suggestion
    def is_program_valid(self, program_config: ProgramConfig) -> bool:
        return True
```
No need to overload this

2023-01-30 08:37 UTC, Silv3S commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +            platform::errors::InvalidArgument("Find input var Bias error."));
```suggestion
            phi::errors::InvalidArgument("Find input var Bias error."));
```

2023-01-30 08:37 UTC, Silv3S commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +                          platform::errors::InvalidArgument(
```suggestion
                          phi::errors::InvalidArgument(
```

2023-01-30 13:34 UTC, Silv3S approved these changes, later dismissed

2023-02-02 11:54 UTC, Silv3S submitted a review, later dismissed
LGTM

2023-02-02 11:59 UTC, HulekJakub commented
@XieYunshen could you approve? I deleted obsolete test and fixed fuse pass.
 '::mutable_data()' was there already and I just moved it. I don't have access to DeviceContext in this class so I can not refactor it. Thank you

2023-02-02 12:17 UTC, XieYunshen submitted a review, later dismissed
LGTM

2023-02-02 13:25 UTC, HulekJakub commented
@YuanRisheng could you approve?
`::mutable_data()` was there already and I just moved it. I don't have access to DeviceContext in this class so I can not refactor it. Thank you

2023-02-03 02:26 UTC, YuanRisheng approved these changes, later dismissed

2023-02-03 10:31 UTC, HulekJakub commented
@Silv3S @YuanRisheng @XieYunshen I had to resolve conflicts, could you approve once again?

2023-02-03 10:50 UTC, Silv3S approved these changes, later dismissed

2023-02-13 10:27 UTC, Silv3S approved these changes

2023-02-13 10:52 UTC, HulekJakub commented
@YuanRisheng @XieYunshen I had to resolve conflicts, could you approve once again?

2023-02-13 11:14 UTC, YuanRisheng approved these changes

2023-02-15 09:30 UTC, HulekJakub commented
@XieYunshen please approve changes in tests

2023-02-15 09:31 UTC, XieYunshen approved these changes

2023-02-16 09:42 UTC, jczaja approved these changes
LGTM

2023-02-16 09:42 UTC, merged