Add rpc ops to fetch data from remote service
PaddlePaddle/Paddle pull request #50220
Opened 2023-02-05 07:56 UTC by HermitSun

### PR types

New features
### PR changes

OPs
### Describe

新增 RPC op

2023-02-13 03:25 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.cc
> +      channel.Init(url.c_str(), /*load_balancer*/ "", &options),
channel.Init的开销有多大，能用长链接吗？

2023-02-13 03:28 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* normalizer = icu::Normalizer2::getNFDInstance(err);
初始化一次

2023-02-13 03:38 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.h
> +    std::lock_guard<std::mutex> lock(mutex_);
可以更改为原子变量减小开销

2023-02-13 04:45 UTC, HermitSun commented on paddle/fluid/platform/rpc_utils.cc
> +      channel.Init(url.c_str(), /*load_balancer*/ "", &options),
1. 文档上说：『这类Init连接的服务器往往有固定的ip地址，不需要命名服务和负载均衡，创建起来相对轻量。』如果需要的话感觉也可以针对每个 op 创建一个单例（如果最后 server 是固定的）。
2. 支持长连接，但感觉需要 server 配合?

2023-02-13 04:45 UTC, HermitSun commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* normalizer = icu::Normalizer2::getNFDInstance(err);
放在全局吗

2023-02-13 08:47 UTC, HermitSun commented on paddle/fluid/platform/rpc_utils.h
> +    std::lock_guard<std::mutex> lock(mutex_);
done

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_call_op.cc
> +    AddInput("X", "(Tensor) Src words' ids.");
少了一个use_src_ids?

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_result_op.h
> +    if (ok) {
这里暂时改为如果非OK就报错吧，同时把错误码打印出来

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_call_op.cc
> +    AddInput("X", "(Tensor) Src words' ids.");
这里也少了use_src_ids?

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_call_op.h
> +    VLOG(3) << "Request id " << request_id << " failed: access url error.";
这里失败的话直接抛出出异常吧

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_result_op.cc
> +    AddComment(R"DOC(
少了一个res_type,或者去掉这个选项，只让他返回src id

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_result_op.h
> +      const std::string res_type = ctx.Attr<std::string>("res_type");
这一行也可以删掉

2023-02-13 09:08 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_result_op.h
> +                          const std::string& res_type,
这一个res_type在这里应该就不需要了

2023-02-13 10:57 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* ctrl = new brpc::Controller();
这个不释放的话应该会对性能有较大影响

2023-02-13 10:58 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.cc
> +      channel.Init(url.c_str(), /*load_balancer*/ "", &options),
嗯，是的，感觉后面要从server端一起优化

2023-02-13 10:58 UTC, SylarTiaNII commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* normalizer = icu::Normalizer2::getNFDInstance(err);
别放在全局，担心里面的buffer不安全，可以把他放到BasicTokenizer类里

2023-02-13 11:09 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_call_op.cc
> +    AddInput("X", "(Tensor) Src words' ids.");
加回来了

2023-02-13 11:09 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_result_op.h
> +    if (ok) {
done

2023-02-13 11:10 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_call_op.cc
> +    AddInput("X", "(Tensor) Src words' ids.");
加回来了

2023-02-13 11:10 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_result_op.cc
> +    AddComment(R"DOC(
去掉了，只返回 src_ids

2023-02-13 11:11 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_result_op.h
> +      const std::string res_type = ctx.Attr<std::string>("res_type");
done

2023-02-13 11:11 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_result_op.h
> +                          const std::string& res_type,
done

2023-02-13 11:11 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_call_op.h
> +    VLOG(3) << "Request id " << request_id << " failed: access url error.";
done

2023-02-13 11:36 UTC, HermitSun commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* ctrl = new brpc::Controller();
异步请求的controller得在堆上，否则获取不到数据
由调用者确保在回调中进行释放：
https://github.com/PaddlePaddle/Paddle/blob/de52cae96a0d6eb40abc85b58963d0ae35ff04c8/paddle/fluid/operators/collective/rpc_call_op.h#L67-L72

2023-02-13 11:44 UTC, HermitSun commented on paddle/fluid/platform/rpc_utils.cc
> +  auto* normalizer = icu::Normalizer2::getNFDInstance(err);
文档里说这个已经是单例了
```cpp
/**
 * Returns a Normalizer2 instance for Unicode NFD normalization.
 * Same as getInstance(NULL, "nfc", UNORM2_DECOMPOSE, errorCode).
 * Returns an unmodifiable singleton instance. Do not delete it.
 */
static const Normalizer2 *
getNFDInstance(UErrorCode &errorCode);
```

2023-02-13 12:01 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_call_op.h
> +    std::vector<int> src_ids_vec;
这种vector<int> 改成vector<T>的形式会不会更好，src id you的是int64类型

2023-02-13 12:01 UTC, sljlp commented on paddle/fluid/operators/collective/rpc_token_call_op.h
> +    std::vector<int> src_ids_vec;
同上

2023-02-13 12:06 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_call_op.h
> +    std::vector<int> src_ids_vec;
done

2023-02-13 12:06 UTC, HermitSun commented on paddle/fluid/operators/collective/rpc_token_call_op.h
> +    std::vector<int> src_ids_vec;
done

2023-02-16 08:39 UTC, gongweibao requested changes

2023-02-16 08:39 UTC, gongweibao commented on python/paddle/tensor/stat.py
> +    n = paddle.cast(paddle.numel(x), dtype) / paddle.cast(
这个的原因是？

2023-02-16 08:39 UTC, gongweibao commented on python/paddle/static/nn/rpc_utils.py
> +    if url_id is None:
url_id是什么？

2023-02-16 08:39 UTC, gongweibao commented on paddle/fluid/platform/rpc_utils.h
> +      int timeout_ms = 10000,
超时是10s？

2023-02-16 08:39 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +req_ids = paddle.static.nn.rpc_call(
url_id是不需要的。

2023-02-16 08:39 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +    "/code_lp/ernie-bot/post-train/ernie_3.0_100b_no_distill/config/ernie3.0_vocab_multi_prompt_v9.txt",
EB模型

2023-02-16 08:39 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +out_data, out_succeed = paddle.static.nn.rpc_result(req_ids, RES_TYPE, 1)
outlen不应该由用户传入。
超时参数要涉及。

2023-02-16 14:14 UTC, sljlp commented on python/paddle/tensor/stat.py
> +    n = paddle.cast(paddle.numel(x), dtype) / paddle.cast(
FP16 反向报错

2023-02-16 14:15 UTC, sljlp commented on python/paddle/static/nn/rpc_utils.py
> +    if url_id is None:
已经去掉

2023-02-16 14:15 UTC, sljlp commented on paddle/fluid/platform/rpc_utils.h
> +      int timeout_ms = 10000,
已经修改

2023-02-16 14:16 UTC, sljlp commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +out_data, out_succeed = paddle.static.nn.rpc_result(req_ids, RES_TYPE, 1)
done

2023-02-16 14:16 UTC, sljlp commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +    "/code_lp/ernie-bot/post-train/ernie_3.0_100b_no_distill/config/ernie3.0_vocab_multi_prompt_v9.txt",
已修改

2023-02-16 14:17 UTC, sljlp commented on python/paddle/fluid/tests/unittests/collective/test_rpc_call_result.py
> +req_ids = paddle.static.nn.rpc_call(
已删除

2023-02-17 10:03 UTC, gongweibao approved these changes
LGTM

2023-02-17 10:04 UTC, merged