Expand mixed_precision to all backend
PaddlePaddle/Paddle pull request #50378
Opened 2023-02-09 08:38 UTC by YanhuiDua

### PR types
Others

### PR changes
APIs

### Describe
Expand ConvertToMixedPrecision to all backend and change the input arg `backend`from `phi::PlaceType` to `const char*` to support custom device.

2023-02-09 11:09 UTC, qili93 commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> +bool AllKernelSupportPrecision(
建议函数名称改成 KernelSupportPrecision 就可以

2023-02-09 11:32 UTC, qili93 requested changes
整体建议：针对 ConvertToMixedPrecision 这个接口增加 Custom Device 的适配就可以，暂时不要修改对所有 Backend 都支持，可能会影响其他后端的功能。
同时参考 enable_gpu_mixed_ 的代码（GPU 在EnableUseGpu中通过判断 precision mode来决定是否打开 enable_gpu_mixed_）修改 EnableCustomDevice 支持通过判断数据类型来打开 FP16 的自动转化。

2023-02-09 11:32 UTC, qili93 commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> +  skip_pass_ = false;
这是需要通过 analysis config 对象的配置 enable_gpu_mixed，来决定是否要走这个 pass，这里的修改是把这个配置去掉了，默认这个配置一致打开，而且用户无法通过 enable_gpu_mixed 来决定是否开关；这里会 Broken 原有 GPU 推理功能接口 SetEnableGPUMixed，需要修复下。

2023-02-09 11:32 UTC, qili93 commented on paddle/fluid/inference/analysis/passes/convert_to_mixed_precision.h
> +      const std::string& backend,
建议这里通过对 phi/common/backend.h 的修改添加 Custom Device 的 backend 类型，这里不建议将 phi::Backend 的数据结构改成 std::string，下面做相应的修改。

2023-02-09 11:32 UTC, qili93 commented on python/paddle/fluid/tests/unittests/ir/test_convert_to_mixed_precision.py
> +        place_options = ["GPU", "CPU"]
这里建议在  custom cpu 下增加一个类似的单测 case，place 类型为 Custom CPU

2023-02-09 11:32 UTC, qili93 commented on python/paddle/inference/wrapper.py
> +    backend: str,
同上，这里的接口改动，会 broken 之前通过这个接口开发的 Paddle Inference的 GPU代码，接口参数尽量避免修改

2023-02-09 11:38 UTC, YanhuiDua commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> +  skip_pass_ = false;
收到，谢谢

2023-02-09 11:38 UTC, YanhuiDua commented on python/paddle/fluid/tests/unittests/ir/test_convert_to_mixed_precision.py
> +        place_options = ["GPU", "CPU"]
收到谢谢

2023-02-10 06:16 UTC, YanhuiDua commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> +#endif
下面需要获取all_custom_device_types，需要导入该头文件

2023-02-13 07:05 UTC, qili93 approved these changes, later dismissed
LGTM，单测需要修复下，代码没有问题啦

2023-02-13 07:50 UTC, yuanlehome commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> -      PADDLE_THROW(paddle::platform::errors::InvalidArgument(
保留一下这个PADDLE_THROW吧，这个接口其他地方会调用到

2023-02-13 07:50 UTC, yuanlehome commented on paddle/fluid/framework/ir/auto_mixed_precision_pass.cc
> +  if (enable_custom_device_mixed) {
enable_gpu_mixed和enable_custom_device_mixed是二选一的关系吧，这里可以：
```cpp
if (enable_gpu_mixed) {
  //
} else if(enable_custom_device_mixed) {
  //
}
```

2023-02-14 11:22 UTC, qili93 approved these changes
LGTM

2023-02-14 11:34 UTC, merged

2023-02-23 07:08 UTC, engineer1109 commented
谢谢大神贡献代码，但是好像Inference接口没写，我加个接口试试