Fused ops converter
PaddlePaddle/Paddle pull request #50751
Opened 2023-02-21 17:57 UTC by Silv3S

### PR types
Others

### PR changes
OPs

### Describe
- add method converting base op to fused op during fuse pass,
- change hardcoded op types with list, which is stored in one place.

2023-02-22 14:21 UTC, jczaja submitted a review, later dismissed
LGTM

2023-02-22 16:18 UTC, sfraczek submitted a review, later dismissed
LGTM :)

2023-02-22 16:22 UTC, Silv3S commented
@jczaja please merge

2023-02-23 08:11 UTC, tsocha requested changes

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/mkldnn_pass_util.h
> +static void ConvertToFusedOp(OpDesc* op) {
Why did you declare this function as static?
```suggestion
inline void ConvertToFusedOp(OpDesc* op) {
```
It should be inline IMHO.
https://stackoverflow.com/questions/8406800/when-should-i-write-the-keyword-static-before-a-non-member-function/8406986#8406986

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
> +      ConvertToFusedOp(operator_op->Op());
This check will be done in `ConvertToFusedOp` function.
```suggestion
    ConvertToFusedOp(operator_op->Op());
```

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/int8_scale_calculation_mkldnn_pass.cc
> +      ConvertToFusedOp(conv_op->Op());
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_squash_pass.cc
> +        ConvertToFusedOp(any_op->Op());
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/cpu_quantize_pass.cc
> +      ConvertToFusedOp(conv_op->Op());
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/conv_elementwise_add_mkldnn_fuse_pass.cc
> +      ConvertToFusedOp(conv_op->Op());
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +        ConvertToFusedOp(conv_op);
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/mkldnn/conv_activation_mkldnn_fuse_pass.cc
> +      ConvertToFusedOp(conv_op);
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:11 UTC, tsocha commented on paddle/fluid/framework/ir/conv_bn_fuse_pass.cc
> +        ConvertToFusedOp(conv->Op());
You can remove `if` statement because this check will be done in `ConvertToFusedOp` function.

2023-02-23 08:56 UTC, Silv3S commented on paddle/fluid/framework/ir/mkldnn/operator_scale_onednn_fuse_pass.cc
> +      ConvertToFusedOp(operator_op->Op());
I left these checks in fuse passes which affect ops, that don't have fused op implemented yet. For example in _operator_scale_onednn_fuse_pass_ only 2 of 7 ops (matmuls) can be converted to fused op. There is no reason to call this function for `fc` or `elementwise` ops until `fused_fc` and `fused_elementwise` are implemented.

But I agree that later these extra checks should be deleted in all cases you've mentioned in code review.

2023-02-23 09:03 UTC, tsocha approved these changes

2023-02-23 10:03 UTC, jczaja approved these changes
LGTM

2023-02-23 16:52 UTC, Silv3S commented
@jczaja please merge

2023-02-24 08:34 UTC, merged