Add gru qat int8 test
PaddlePaddle/Paddle pull request #50846
Opened 2023-02-23 14:43 UTC by wozna

### PR types

Others
### PR changes

Others 
### Describe

This PR adds:
- option to run lexical analysis test with new quantization process. 
- test for GRU QAT int8 model

2023-02-24 15:44 UTC, Silv3S approved these changes, later dismissed
LGTM

2023-02-24 15:44 UTC, Silv3S commented on paddle/fluid/inference/tests/api/CMakeLists.txt
> +      "
```suggestion
    --model_name="Resnet50"
```

2023-02-25 23:12 UTC, Silv3S approved these changes, later dismissed

2023-02-27 10:13 UTC, wozna commented on paddle/fluid/inference/tests/api/CMakeLists.txt
> +    --enable_int8=${enable_int8}
Correct flag names to make them clearer

2023-02-27 11:06 UTC, tsocha requested changes

2023-02-27 11:06 UTC, tsocha commented on paddle/fluid/inference/tests/api/CMakeLists.txt
> +    false)
I'm not a fan of naked bool flags, could you place it in the documenting variable?
You could also use a comment for it.

2023-02-27 11:06 UTC, tsocha commented on paddle/fluid/inference/tests/api/CMakeLists.txt
> +    true)
as above

2023-02-27 11:06 UTC, tsocha commented on paddle/fluid/inference/tests/api/CMakeLists.txt
> +    false)
as above

2023-02-27 18:59 UTC, sfraczek commented on paddle/fluid/inference/tests/api/tester_helper.h
>          "CompareAccuracy: output_slots vector is empty.");
This if could use some explanation. It seems counter intuitive that we check ((fp32 && non_fp32) &&  some output_slots vector).

2023-02-27 19:21 UTC, sfraczek approved these changes
LGTM

2023-02-27 20:18 UTC, Silv3S approved these changes

2023-02-28 09:41 UTC, tsocha approved these changes

2023-02-28 13:27 UTC, jczaja approved these changes
LGTM

2023-02-28 13:27 UTC, merged