[fp16] support fp16 on AvgPool3D
PaddlePaddle/Paddle pull request #50920
Opened 2023-02-25 23:41 UTC by Liyulingyue

### PR types

Others 
### PR changes

APIs 
### Describe

- https://github.com/PaddlePaddle/Paddle/issues/50832 case22

2023-02-26 07:16 UTC, zhangting2020 approved these changes
LGTM

2023-02-26 07:31 UTC, zhangting2020 requested changes

2023-02-26 07:31 UTC, zhangting2020 commented on python/paddle/nn/functional/pooling.py
> +            x, 'x', ['float16', 'float32', 'float64'], 'max_pool3d'
这里应该是当时的开发人员写错， max_pool3d->avg_pool3d

2023-02-26 07:34 UTC, Liyulingyue commented on python/paddle/nn/functional/pooling.py
> +            x, 'x', ['float16', 'float32', 'float64'], 'max_pool3d'
```suggestion
            x, 'x', ['float16', 'float32', 'float64'], 'avg_pool3d'
```

2023-02-27 02:25 UTC, zhangting2020 approved these changes

2023-02-27 02:32 UTC, zhangting2020 commented
TODO：遗漏了AvgPool3D 文档修复，看这个PR一起改或者另提一个PR修都可以。

2023-02-27 07:51 UTC, merged