stack & unstack fp16 bf16 support
PaddlePaddle/Paddle pull request #50999
Opened 2023-02-28 05:12 UTC by piDack

### PR types
New features

### PR changes
Others

### Describe
add fp16/bf16 support 4 stack & unstack ops

2023-02-28 07:41 UTC, ZzSean commented on paddle/phi/kernels/cpu/unstack_grad_kernel.cc
> +                   int64_t,
本次修改暂不修改CPU，只针对CPU

2023-02-28 08:00 UTC, ZzSean commented on paddle/phi/kernels/cpu/unstack_kernel.cc
> +                   phi::dtype::float16,
同上

2023-02-28 08:00 UTC, ZzSean commented on python/paddle/fluid/tests/unittests/test_unstack_op.py
> +    def test_check_grad(self):
这里为什么没有直接使用原来的test_check_grad

2023-02-28 08:00 UTC, ZzSean commented on python/paddle/fluid/tests/unittests/test_unstack_op.py
> +        self.x = np.random.random(size=self.input_dim).astype(float)
`astype(float)`需要改成`astype(np.float32)`，否则在python中直接使用float的话会是64bits的

2023-02-28 08:00 UTC, ZzSean commented on python/paddle/fluid/tests/unittests/test_unstack_op.py
> +        with fluid.dygraph.guard():
这里反向的写法最好还是跟TestUnStackOpBase保持一致吧

2023-03-02 11:19 UTC, ZzSean commented on python/paddle/fluid/tests/unittests/test_unstack_op.py
> +def unstack_grad_fp16(dout):
需删除

2023-04-11 03:47 UTC, ZzSean requested changes
LGTM

2023-04-11 03:47 UTC, ZzSean approved these changes
LGTM

2023-04-11 05:16 UTC, qili93 approved these changes
LGTM

2023-04-11 05:19 UTC, merged