To support cuda12, pybind need to upgrade to v2.10.0
PaddlePaddle/Paddle pull request #51350
Opened 2023-03-08 06:24 UTC by zhengqiwen1997

### PR types

New features
### PR changes

Others
### Describe

To support cuda12, pybind need to upgrade to v2.10.0.

2023-03-20 03:50 UTC, phlrain requested changes

2023-03-20 03:50 UTC, phlrain commented on paddle/fluid/inference/tensorrt/convert/CMakeLists.txt
> +  DEPS python paddle_framework tensorrt_converter op_meta_info custom_operator)
这个会不会导致，c++部署的时候，依然需要python环境

2023-03-23 02:52 UTC, pangyoki approved these changes
LGTM

2023-03-23 03:04 UTC, phlrain approved these changes

2023-03-23 03:15 UTC, merged