mp sync params & grads & opt states.
PaddlePaddle/Paddle pull request #51428
Opened 2023-03-09 10:03 UTC by wuhuachaocoding

### PR types

Others
### PR changes

Others
### Describe

mp sync params & grads & opt states.
see: https://github.com/PaddlePaddle/Paddle/pull/50676

2023-03-28 12:16 UTC, gongweibao submitted a review, later dismissed
LGTM

2023-04-04 11:31 UTC, gongweibao requested changes

2023-04-04 11:31 UTC, gongweibao commented on python/paddle/fluid/tests/unittests/collective/fleet/hybrid_parallel_mp_model.py
> +            "sync_grad": False,
sync_grad和sync_moment是指？

2023-04-10 06:56 UTC, ForFishes approved these changes
LGTM

2023-04-10 06:57 UTC, wuhuachaocoding commented on python/paddle/fluid/tests/unittests/collective/fleet/hybrid_parallel_mp_model.py
> +            "sync_grad": False,
一个标志：代表是否同步grad, 是否同步moment. 和静态图对齐。

2023-04-11 04:11 UTC, gongweibao approved these changes
LGTM

2023-04-11 04:11 UTC, merged