fix paddle_infer::Tensor::data lack custom place
PaddlePaddle/Paddle pull request #51710
Opened 2023-03-15 11:00 UTC by engineer1109

### PR types

Bug fixes
### PR changes

Others
### Describe

[paddle/fluid/inference/api/details/zero_copy_tensor.cc](https://github.com/PaddlePaddle/Paddle/compare/develop...engineer1109:fix-data?expand=1#diff-012247f22ceecf153a7a84e7523f0ef43b48cfb52b5701ddc4860a662d266b03)
```cpp
template <typename T>
T *Tensor::data(PlaceType *place, int *size) const
```
这个函数缺乏CustomDevice Place的处理过程，导致CustomDevice无法使用paddle_infer::Tensor::data
例如
```
auto input_t = m_predictor->GetInputHandle(input_names[0]);
auto inputPtr = input_t->mutable_data<float>(paddle_infer::PlaceType::kCUSTOM);
```
会直接报出如下错误
```
Only CPU / CUDA / XPU / NPU places is supported.
```
这里加入Custom Place的处理代码。
支持place_ >= PlaceType::kCUSTOM

2023-03-16 09:54 UTC, engineer1109 commented
[paddle/fluid/platform/init.cc](https://github.com/PaddlePaddle/Paddle/pull/51710/files#diff-488d70e6ba3cc8671f445966edf52383f3d70023d6e910400a018dbe4f0f012a) 这个改动是为了支持单元测试对FakeCPU CustomDevice的注册。

[paddle/testing/paddle_gtest_main.cc](https://github.com/PaddlePaddle/Paddle/pull/51710/files#diff-5279b182b01072afdd0bc8a052ec10d84f03c5b75ecaebc6acc2307cba8b9a5a) 允许在单元测试中使用CustomDevice

2023-03-16 13:10 UTC, engineer1109 commented
https://github.com/PaddlePaddle/Paddle/issues/51766
[paddle/testing/paddle_gtest_main.cc](https://github.com/PaddlePaddle/Paddle/pull/51710/files#diff-5279b182b01072afdd0bc8a052ec10d84f03c5b75ecaebc6acc2307cba8b9a5a)
paddle 通用gtest函数里没有custom device的初始化。
Custom Device的PR很难通过coverage覆盖率检测。


这个PR加入了对Custom Device的处理，允许在paddle::framework::InitDevices加载FakeCPU的Custom Device。

FakeCPU是Paddle自带的Custom Device模拟，使用phi::LoadCustomRuntimeLib手动接入函数。
不使用CUSTOM_DEVICE_ROOT。
这个PR在允许没有CUSTOM_DEVICE_ROOT的情况下，检查phi::LoadCustomRuntimeLib挂载的CustomDevice
允许在gtest中接入FakeCPU。

2023-03-17 02:30 UTC, engineer1109 commented
@luotao1 CI已经全绿，还请安排一下

2023-03-17 09:04 UTC, jzhang533 commented
cc: @ZeyuChen

2023-03-17 09:41 UTC, qili93 requested changes

2023-03-17 09:41 UTC, qili93 commented on paddle/fluid/platform/init.cc
> +  }
Custom Device 的 PR 很难通过 coverage 覆盖率检测是已知问题，不建议直接在 CUSTOM_DEVICE_ROOT 为空的情况下也对飞桨框架 Custom Device进行初始化。目前 PR-CI-Coverage 流水线只能支持 CUDA 的代码覆盖率，对于其他硬件暂不支持 ，如果后续存在 Custom Device PR 的覆盖率问题，请直接联系本人 @qili93 申请覆盖率流水线的豁免即可。

2023-03-17 09:41 UTC, qili93 commented on paddle/testing/paddle_gtest_main.cc
> +#endif
同上，请删除因为流水线覆盖率导致的对  Custom Device功能的修改。

2023-03-17 09:41 UTC, qili93 commented on paddle/fluid/platform/init_test.cc
> +#endif
同上，请删除因为流水线覆盖率导致的对  Custom Device功能的修改。

2023-03-17 09:41 UTC, qili93 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +    *place = PlaceType::kCUSTOM;
170行建议修改为  } else if (paddle::platform::is_custom_place(tensor->place())) {

2023-03-17 09:41 UTC, qili93 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +      }
这里建议修改代码如下

![image](https://user-images.githubusercontent.com/16605440/225868745-c2166824-cbd2-41fd-a75b-d1185c7a839a.png)

2023-03-17 09:43 UTC, qili93 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +      }
以上代码修改仅是建议，辛苦试下以上代码是否可以支持同样的 mutable_data的接口需求 ，如果无法支持，请反馈给我们，我们来对其进行修复，感谢您的贡献！

2023-03-17 09:56 UTC, engineer1109 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +      }
@qili93 使用mutable这个字，会触发Approval的阻止，这个是可以豁免？

2023-03-17 10:24 UTC, engineer1109 commented on paddle/fluid/platform/init.cc
> +  }
已经删除

2023-03-17 11:13 UTC, engineer1109 commented
@qili93 您说的修改可以使用。
但是需要做一个修改
```
input_t->SetPlace(paddle_infer::PlaceType::kCUSTOM, 0, "OpenCL");
```
现在Tensor的Place的"OpenCL"需要手动指定。
```
  void SetPlace(PlaceType place,
                int device = -1,
                const std::string device_type = "");
```
这个函数需要移动到public，可访问。其他和您说的修改一样不变

2023-03-17 11:14 UTC, engineer1109 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +      }
```
void SetPlace(PlaceType place,
                int device = -1,
                const std::string device_type = "");
```
需要改为public，其他不变

2023-03-17 11:14 UTC, engineer1109 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +    *place = PlaceType::kCUSTOM;
OK

2023-03-20 03:49 UTC, qili93 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +      }
> @qili93 使用mutable这个字，会触发Approval的阻止，这个是可以豁免？

是的，这个可以豁免

2023-03-20 03:59 UTC, qili93 requested changes

2023-03-20 03:59 UTC, qili93 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +void Tensor::SetPlace(PlaceType place, int device, std::string device_type) {
这里的参数建议和头文件保持一致，加上 const 修饰

2023-03-20 03:59 UTC, qili93 commented on paddle/fluid/inference/api/paddle_tensor.h
> +
请问这里把 SetPlace 放到 protected 里面是编译会报什么错误吗？这个是对类本身的参数进行设置，还是继续放 protected 里面就可以。

2023-03-20 04:15 UTC, engineer1109 commented on paddle/fluid/inference/api/paddle_tensor.h
> +
@qili93 
```
input_t->SetPlace(paddle_infer::PlaceType::kCUSTOM, 0, "OpenCL");
```
没有这步操作，
PaddleInference里拿出来的Tensor是没有device_type的。
mutable报错 device_type为空

2023-03-20 04:18 UTC, qili93 commented on paddle/fluid/inference/api/paddle_tensor.h
> +
@engineer1109 可以尝试下在这里修改如下代码应该就不需要显示调用 `input_t->SetPlace(paddle_infer::PlaceType::kCUSTOM, 0, "OpenCL");`了，辛苦试下这个方法是否可行，多谢 :) 

![image](https://user-images.githubusercontent.com/16605440/226245911-ab199e91-3fa4-4298-be4b-fae76d938b48.png)

如果上述方法可行，就可以把 SetPlace 放回到 protected 下面去。

2023-03-20 05:15 UTC, engineer1109 commented on paddle/fluid/inference/api/details/zero_copy_tensor.cc
> +void Tensor::SetPlace(PlaceType place, int device, std::string device_type) {
已经修改

2023-03-20 05:16 UTC, engineer1109 commented on paddle/fluid/inference/api/paddle_tensor.h
> +
需要修改两处 GetInputTensor GetOutputTensor
[paddle/fluid/inference/api/analysis_predictor.cc](https://github.com/PaddlePaddle/Paddle/pull/51710/files#diff-f6feda974e038d722114830a39bea985fd814e28bd86bcd33248aece3c3181a4)
SetPlace可以还原为protected

2023-03-20 08:44 UTC, qili93 commented on paddle/fluid/inference/api/paddle_tensor.h
> +
太好了，感谢您的贡献！

2023-03-20 08:50 UTC, qili93 approved these changes
LGTM

2023-03-20 09:56 UTC, YuanRisheng approved these changes

2023-03-21 01:33 UTC, engineer1109 commented
@qili93 
PR-CI-Coverage 需要豁免
CINN download出错

2023-03-21 07:22 UTC, merged