Fix the config_parse.py if user does not set padding for Pool in the old config.
PaddlePaddle/Paddle pull request #521
Opened 2016-11-18 06:50 UTC by qingqing01

2016-11-18 07:05 UTC, luotao1 approved these changes

2016-11-18 09:53 UTC, reyoung requested changes
protobuf里面的默认值需要使用protobuf的default value。这样可以减小序列化文件的长度。

2016-11-18 11:16 UTC, reyoung approved these changes
lgtm

2016-11-22 11:35 UTC, luotao1 commented
pre-commit 格式化一下

2016-11-23 03:47 UTC, merged