[Paddle-Trt] Replace fc mul matmul matmul_v2 with matrix_multiply
PaddlePaddle/Paddle pull request #52222
Opened 2023-03-28 05:21 UTC by Wangzheee

### PR types

### PR changes

### Describe

Replace fc mul matmul matmul_v2 with matrix_multiply

2023-03-30 07:39 UTC, XieYunshen submitted a review, later dismissed
LGTM 
单测删除

2023-04-06 09:19 UTC, fengxiaoshuai submitted a review, later dismissed
LGTM

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/multihead_matmul_roformer_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/multihead_matmul_roformer_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/multihead_matmul_roformer_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul_v2"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul_v2"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/quant_conv2d_dequant_fuse_pass.cc
> -  AddOpCompat(OpCompat("fc"))
已经没有fc这个op，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_cross_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_cross_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_cross_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul_v2"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_delete_weight_dequant_linear_op_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_flash_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_flash_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("mul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_multihead_matmul_fuse_pass.cc
> -  AddOpCompat(OpCompat("matmul"))
mul、matmul、matmul_v2已经通过前置pass转换成 matrix_multiply，去除这里的pass兼容性 op属性的检测

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/multihead_matmul_op.cc
> -    auto tranpose_weight = [](const float* src, float* dst, int m, int n) {
matrix_multiply layer 相比于 FullyConnected layer、Convolution layer，权重不需要转置

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/op_converter.h
> -        if (op_desc.Type() == "mul") {
删除 mul 和 fc convert 逻辑

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/engine.cc
> +#if IS_TRT_VERSION_GE(8500)
提升 matrix_multiply 、ele_add、等layer触发 myelin融合的dynamic shape下的性能

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/op_teller.cc
> -    if (op_type == "matmul_v2") {
去除多个converter_op: matmul、matmul_v2、mul、fc

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/op_teller.cc
> -    if (op_type == "matmul") {
去除多个converter_op: matmul、matmul_v2、mul、fc

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/op_teller.cc
> -    if (op_type == "fc") {
去除多个converter_op: matmul、matmul_v2、mul、fc

2023-04-07 03:24 UTC, Wangzheee commented on python/paddle/fluid/tests/unittests/ir/inference/CMakeLists.txt
> -    set_tests_properties(test_trt_squeeze2_matmul_fuse_pass PROPERTIES TIMEOUT
去除融合：squeeze2_matmul_fuse

2023-04-07 03:24 UTC, Wangzheee commented on paddle/fluid/inference/api/paddle_pass_builder.cc
> -      "trt_squeeze2_matmul_fuse_pass",     //
去除融合：squeeze2_matmul_fuse、squeeze2_matmul_fuse、flatten2_matmul_fuse、fc_fuse

2023-04-10 03:05 UTC, zhangjun commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +Licensed under the Apache License, Version 2.0 (the "License");
改成2023

2023-04-10 03:05 UTC, zhangjun commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +}  // namespace paddle
无用代码去掉

2023-04-10 03:05 UTC, zhangjun commented on paddle/fluid/inference/tensorrt/engine.cc
> +                   "FP16 speed up, use FP32 instead. ";
多加了空格

2023-04-10 03:05 UTC, zhangjun commented on paddle/fluid/inference/tensorrt/engine.cc
> +#else
这里这么改动是不是有点问题？
The default value for this flag is on.

[Deprecated:](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/deprecated.html#_deprecated000047)
Turning it off is deprecated in TensorRT 8.6. The flag kFASTER_DYNAMIC_SHAPES_0805 will be removed in 9.0.

2023-04-10 03:37 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +}  // namespace paddle
都有用的

2023-04-10 03:38 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +Licensed under the Apache License, Version 2.0 (the "License");
收到

2023-04-10 03:38 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/engine.cc
> +                   "FP16 speed up, use FP32 instead. ";
收到

2023-04-10 03:38 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/engine.cc
> +#else
没问题的～ 官方用法

2023-04-10 03:38 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +}  // namespace paddle
都是有用代码

2023-04-10 03:39 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +Licensed under the Apache License, Version 2.0 (the "License");
收到

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/framework/ir/graph_pattern_detector.h
> +struct MulMatmulMatmulV2 : public PatternBase {
这个命名让人很困惑。命名可以精确一些，注释些详细一些。

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/framework/ir/constant_folding_pass.cc
> +  std::vector<std::string> blacklist{"feed", "matrix_multiply"};
说明下为啥这里去掉？

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/framework/ir/remove_padding_recover_padding_pass.cc
> +          ->assert_is_op_input("matrix_multiply", "X");
matrix_multiply没有看到显示的Op定义， 输入、输出、属性命名有在哪里清晰的定义吗？

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/framework/ir/remove_padding_recover_padding_pass.cc
> +  elementwise();
相比改动前增加了 elementwise pattern检测，说明下原因吧

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/framework/ir/trt_map_ops_to_matrix_multiply_pass.cc
> +                 "please reconfig. ";
注释需要注意  语法正确， 并明确告诉用户如何配置。

2023-04-10 04:00 UTC, qingqing01 commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +               "ElementWiseOperation::kPROD layer.";
tensorrt -> TensorRT

convert a matrix_multiply op to TensorRT layers by MatrixMultiply + ElementWiseOperation(KPROD)  ?

2023-04-10 04:00 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.12)
说明下改动阈值的原因

2023-04-10 04:00 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.11)
同上，说明下改动阈值的原因

2023-04-10 04:01 UTC, qingqing01 reviewed
在PR commits里描述下 正确性是如何测试的

2023-04-10 06:01 UTC, zhangjun commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +}  // namespace paddle
> 都是有用代码

可以直接去掉

2023-04-10 08:15 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +}  // namespace paddle
收到～

2023-04-10 08:19 UTC, Wangzheee commented on paddle/fluid/framework/ir/graph_pattern_detector.h
> +struct MulMatmulMatmulV2 : public PatternBase {
好的

2023-04-10 08:22 UTC, Wangzheee commented on paddle/fluid/framework/ir/constant_folding_pass.cc
> +  std::vector<std::string> blacklist{"feed", "matrix_multiply"};
常量折叠的bug，这里顺便修了。可能在某些case，找不到输入输出的node，康康给的方案是加到黑名单里

2023-04-10 08:23 UTC, Wangzheee commented on paddle/fluid/framework/ir/remove_padding_recover_padding_pass.cc
> +          ->assert_is_op_input("matrix_multiply", "X");
收到，在convert op里加上

2023-04-10 08:26 UTC, Wangzheee commented on paddle/fluid/framework/ir/remove_padding_recover_padding_pass.cc
> +  elementwise();
收到，已加注释，去除 fc elementwise_add融合后， elementwise_add会单独出现在模型中

2023-04-10 08:37 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/convert/matrix_multiply_op.cc
> +               "ElementWiseOperation::kPROD layer.";
已修改

2023-04-10 09:18 UTC, Wangzheee commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.12)
测试发现这个单测在未训练权重，输入全0的情况下，原生前向和Paddle-TRT的计算结果数值区别有些大。在单独OP(mul, matmul, matmul_v2)的单测和模型单测上误差都小于阈值

2023-04-10 09:18 UTC, Wangzheee commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.11)
测试发现这个单测在未训练权重，输入全0的情况下，原生前向和Paddle-TRT的计算结果数值区别有些大。在单独OP(mul, matmul, matmul_v2)的单测和模型单测上误差都小于阈值

2023-04-10 09:32 UTC, Wangzheee commented
> 

已加上～

2023-04-11 02:25 UTC, wwbitejotunn approved these changes, later dismissed

2023-04-11 03:09 UTC, qingqing01 requested changes

2023-04-11 03:09 UTC, qingqing01 commented on paddle/fluid/framework/ir/constant_folding_pass.cc
> +  std::vector<std::string> blacklist{"feed", "matrix_multiply"};
请继续确认是否修复常量折叠Pass或怎么修复

2023-04-11 03:09 UTC, qingqing01 commented on paddle/fluid/inference/tensorrt/engine.cc
> +#else
现在TensorRT8.6已经发布，deprecated之后还需要升级？这里是必须的吗？

2023-04-11 03:09 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_fc_fuse_pass.py
> +            self.check_output_with_option(use_gpu[i], atol=1e-4, rtol=1e-3)
更改之前默认阈值是多少？

2023-04-11 03:09 UTC, qingqing01 commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.11)
那误差的本质原因是什么？

2023-04-12 07:54 UTC, Wangzheee commented on paddle/fluid/framework/ir/constant_folding_pass.cc
> +  std::vector<std::string> blacklist{"feed", "matrix_multiply"};
matrix_multiply只有Paddle-TRT的实现，对于cpu上没有注册的OP，通过黑名单的方式不运行常量折叠。另外所有进TensorRT的OP不需要进行常量折叠，TensorRT会在分析阶段自己进行常量折叠

2023-04-12 07:55 UTC, Wangzheee commented on paddle/fluid/inference/tensorrt/engine.cc
> +#else
这个config在TensorRT8.5和8.6上是默认关闭，TensorRT8.7可能会默认开启，可以提升myelin shape动态变化情况下的性能

2023-04-12 07:56 UTC, Wangzheee commented on paddle/fluid/framework/ir/trt_map_ops_to_matrix_multiply_pass.cc
> +                 "please reconfig. ";
done

2023-04-12 07:57 UTC, Wangzheee commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.12)
已整体修改单测，另外发现half 精度下 Windows比Linux的误差会大5～10倍

2023-04-12 07:57 UTC, Wangzheee commented on python/paddle/fluid/tests/unittests/ir/inference/test_trt_convert_multihead_matmul.py
> +        yield self.create_inference_config(), (1, 3), (1e-5, 0.11)
已整体修改单测：组网的权重和输入输出

2023-04-12 07:58 UTC, Wangzheee commented
> 在PR commits里描述下 正确性是如何测试的

已在pr里描述

2023-04-13 02:38 UTC, XieYunshen approved these changes
LGTM
单测删除

2023-04-13 03:38 UTC, qingqing01 approved these changes

2023-04-13 12:16 UTC, XiaoguangHu01 approved these changes
LGTM

2023-04-13 14:15 UTC, merged