rem is_compiled_with_npu
PaddlePaddle/Paddle pull request #52385
Opened 2023-03-30 16:36 UTC by KimBioInfoStudio

### PR types

Others
### PR changes

Others
### Describe

#52319
昇腾和寒武纪相关代码退场
任务编号 | 任务内容                                                  | 认领人              | PR链接|
------- | --------------------------------------------------------- | -------------------| ------|
8       | 清理 is_compiled_with_npu 相关代码                         |  @KimBioInfoStudio | #52385|

2023-04-02 17:14 UTC, engineer1109 commented on python/paddle/amp/grad_scaler.py
> +        if core.is_compiled_with_custom_device('npu'):
float status对CustomDevice的 NPU会有效吗？
我记得Custom Device里没有Pin Memory和Float Status的相关内容。
从代码来看，华为的浮点数0或inf的判断好像有问题。

2023-04-03 01:52 UTC, ronny1996 requested changes

2023-04-03 01:52 UTC, ronny1996 commented on python/paddle/amp/grad_scaler.py
> +        if core.is_compiled_with_custom_device('npu'):
不再需要这个判断了，下面这两个amp也是npu特有的，我们在插件里解决了

2023-04-03 10:47 UTC, engineer1109 commented on python/paddle/amp/grad_scaler.py
> +        if core.is_compiled_with_custom_device('npu'):
is_compiled_with_custom_device('npu') 是不是都不需要了吗？

2023-04-06 03:30 UTC, ronny1996 approved these changes
LGTM

2023-04-06 03:35 UTC, merged