【昇腾和寒武纪相关代码退场】No.9 清理 PADDLE_WITH_ASCEND 相关代码
PaddlePaddle/Paddle pull request #52403
Opened 2023-03-31 06:55 UTC by mrcangye

### PR types

Others
### PR changes

Others
### Describe

昇腾和寒武纪相关代码退场 Tracking Issue  #52319

2023-03-31 12:06 UTC, KimBioInfoStudio requested changes

2023-03-31 12:06 UTC, KimBioInfoStudio commented on paddle/fluid/operators/ascend_trigger_op.h
>  #endif
endif tag should also rem?

2023-03-31 12:08 UTC, KimBioInfoStudio requested changes

2023-03-31 12:08 UTC, KimBioInfoStudio commented on paddle/fluid/operators/ascend_trigger_op.h
>  #endif
```suggestion
```
`#endif` close tag also need remove here?

2023-03-31 12:29 UTC, KimBioInfoStudio commented
你是不是把错误的分支merge到 source 分支了， 为啥 changes 一下变得这么多， 能 clean 下吗

2023-03-31 12:30 UTC, mrcangye commented
> 你是不是把错误的分支merge到 source 分支了， 为啥 changes 一下变得这么多， 能 clean 下吗

我去，我回退下，囧

2023-04-05 11:34 UTC, mrcangye commented
@KimBioInfoStudio 小哥辛苦再看看，要是没问题我就艾特涛姐合一下

2023-04-06 00:36 UTC, KimBioInfoStudio approved these changes
LGTM

2023-04-06 03:28 UTC, ronny1996 approved these changes
LGTM

2023-04-06 03:28 UTC, ronny1996 commented on paddle/fluid/operators/ascend_trigger_op.h
>  #include "paddle/fluid/framework/op_registry.h"
这个文件可以删除

2023-04-06 03:28 UTC, ronny1996 commented on paddle/fluid/pybind/ascend_wrapper_py.cc
>  };
同上

2023-04-06 03:52 UTC, merged

2023-04-06 03:56 UTC, luotao1 commented
@mrcangye 请在下一个PR中删除 [paddle/fluid/operators/ascend_trigger_op.h] 和 [paddle/fluid/pybind/ascend_wrapper_py.cc] 两个文件

2023-04-06 05:12 UTC, mrcangye commented
> 

收到！会在下个PR删除相关的文件

> @mrcangye 请在下一个PR中删除 [paddle/fluid/operators/ascend_trigger_op.h] 和 [paddle/fluid/pybind/ascend_wrapper_py.cc] 两个文件