[PHI kernels] Bind XPU kernels
PaddlePaddle/Paddle pull request #53336
Opened 2023-04-25 10:54 UTC by RuohengMa

### PR types
Others

### PR changes
OPs

### Description
Bind sparse_coo_tensor, reduce_max/max_int32, range/arange_int32, equal_bool

2023-04-27 02:28 UTC, taixiurong commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +    xpu::VectorParam<int> indices{
这里为啥要把const去掉？

2023-05-04 02:26 UTC, luotao1 approved these changes, later dismissed
LGTM for const_cast

2023-05-04 03:06 UTC, XiaociZhang requested changes

2023-05-04 03:06 UTC, XiaociZhang commented on paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
> +#if !defined(PADDLE_WITH_XPU)
为什么要加这行判断

2023-05-04 03:06 UTC, XiaociZhang commented on paddle/phi/backends/xpu/xpu2_op_list.cc
> +      {"reduce_max",
单测需要改

2023-05-04 03:06 UTC, XiaociZhang commented on paddle/phi/backends/xpu/xpu2_op_list.cc
> +      {"sparse_coo_tensor",
没有单测？

2023-05-04 04:46 UTC, ZibinGuo commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +    xpu::VectorParam<int> indices{nullptr, index_size, index_data};
这里根据api文档要求，在VectorParam结构体里，cpu数据是必须要有的(第一个参数不能为nullptr)，xpu数据则是可选的

2023-05-06 02:54 UTC, RuohengMa commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +    xpu::VectorParam<int> indices{
因为xdnn里的VectorParam里的xpu数据需要非const的指针~

2023-05-06 02:54 UTC, RuohengMa commented on paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
> +#if !defined(PADDLE_WITH_XPU)
因为sparse下面，cpu和xpu的sparse_coo_tensor都是绑定的同一个SparseCooTensorKernel，如果同时编译的话会产生重复绑定报错。另外因为这个kernel可以根据输入Backend产生一个包含了两个dense_tensors的coo_tensor，所以cpu和xpu可以共用一个kernel~

2023-05-06 02:54 UTC, RuohengMa commented on paddle/phi/backends/xpu/xpu2_op_list.cc
> +      {"reduce_max",
ok

2023-05-06 02:54 UTC, RuohengMa commented on paddle/phi/backends/xpu/xpu2_op_list.cc
> +      {"sparse_coo_tensor",
这个sparse_coo_tensor是根据Backend产生不同的coo_tensor，但不会对数据进行处理，这样的话还需要单测吗？

2023-05-06 02:54 UTC, RuohengMa commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +    xpu::VectorParam<int> indices{nullptr, index_size, index_data};
这个之前和@taixiurong讨论过，文档已经过时了，那个VectorParam可以不提供cpu只提供xpu指针~ 然后因为indices本身就是xpu的，可以直接装到VectorParam里然后api算子会直接拿这个xpu的指针来读数据~

2023-05-06 02:58 UTC, XiaociZhang commented on paddle/phi/backends/xpu/xpu2_op_list.cc
> +      {"sparse_coo_tensor",
python/paddle/fluid/tests/unittests/test_sparse_utils_op.py
cpu/gpu的，可以参考

2023-05-06 02:59 UTC, XiaociZhang commented on paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc
> +#if !defined(PADDLE_WITH_XPU)
> cpu和xpu的sparse_coo_tensor都是绑定的同一个SparseCooTensorKernel，如果同时编译的话会产生重复绑定报错

感觉不太合理啊，别的kernel之前好像没有类似问题？

2023-05-06 05:38 UTC, ZibinGuo commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +    xpu::VectorParam<int> indices{nullptr, index_size, index_data};
OK

2023-05-06 05:38 UTC, ZibinGuo submitted a review, later dismissed
LGTM

2023-05-08 07:37 UTC, ykkk2333 approved these changes
LGTM

2023-05-08 07:37 UTC, ykkk2333 commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +#include "glog/logging.h"
kernel中不需要加过log吧？这个头文件是不是没有用到

2023-05-08 07:44 UTC, RuohengMa commented on paddle/phi/kernels/xpu/scatter_grad_kernel.cc
> +#include "glog/logging.h"
了解，下个commit把多余的头文件删掉~

2023-05-08 07:44 UTC, luotao1 approved these changes
LGTM for const_cast

2023-05-09 09:21 UTC, houj04 approved these changes

2023-05-09 09:21 UTC, merged