rem npu in test
PaddlePaddle/Paddle pull request #53469
Opened 2023-04-28 14:43 UTC by KimBioInfoStudio

### PR types

Others
### PR changes

Others
### Description

https://github.com/PaddlePaddle/Paddle/issues/52319

2023-05-05 05:39 UTC, KimBioInfoStudio commented
@ronny1996  @luotao1  pls help review

2023-05-05 08:15 UTC, ronny1996 requested changes

2023-05-05 08:15 UTC, ronny1996 commented on test/cpp/inference/api/analysis_predictor_tester.cc
> -TEST(AnalysisPredictor, lite_nn_adapter_npu) {
这里需要保留，其他没问题

2023-05-06 02:12 UTC, ronny1996 approved these changes
LGTM

2023-05-06 02:12 UTC, merged