昇腾和寒武纪相关代码退场 npu相关代码退场
PaddlePaddle/Paddle pull request #53568
Opened 2023-05-06 20:54 UTC by Liyulingyue

### PR types

Others 
### PR changes

Others 
### Description

Others

2023-05-08 06:55 UTC, ronny1996 requested changes

2023-05-08 06:55 UTC, ronny1996 commented on paddle/fluid/operators/memcpy_op.cc
> +                 "4: dst is on NPUPinnerPlace. "
NPUPinnedPlace也可以删了

2023-05-08 06:55 UTC, ronny1996 commented on paddle/fluid/platform/place.h
>      case phi::AllocationType::NPUPINNED: {
同上

2023-05-08 06:55 UTC, ronny1996 commented on paddle/phi/common/place.h
>  class NPUPinnedPlace : public Place {
同上

2023-05-08 06:55 UTC, ronny1996 commented on python/paddle/fluid/dygraph/tensor_patch_methods.py
> -                _global_flags()['FLAGS_npu_storage_format']
这里先不删除

2023-05-08 06:55 UTC, ronny1996 commented on python/paddle/nn/functional/conv.py
> -    is_compiled_with_custom_device,
get_all_custom_device_type, is_compiled_with_custom_device 不需要删除

2023-05-08 06:55 UTC, ronny1996 commented on python/paddle/nn/functional/conv.py
> -            # TODO(qili93): temporary for ascned npu performance to be removed along with npu_identity op
这里先不删除

2023-05-08 06:55 UTC, ronny1996 commented on python/paddle/nn/functional/conv.py
> -                    and 'npu' in get_all_custom_device_type()
同上

2023-05-08 06:55 UTC, ronny1996 commented on python/paddle/nn/layer/norm.py
> -        # TODO(qili93): temporary for ascned npu performance to be removed along with npu_identity op
同上

2023-05-09 03:20 UTC, luotao1 commented
辛苦清理下commit，引入了很多其他同学的commit信息

2023-05-11 02:55 UTC, ronny1996 approved these changes
LGTM

2023-05-11 02:57 UTC, merged