[CustomDevice] suport device_guard for npu
PaddlePaddle/Paddle pull request #53808
Opened 2023-05-15 07:34 UTC by YanhuiDua

### PR types
Others 

### PR changes
Others

### Description
suport device_guard for npu

2023-05-15 07:39 UTC, ronny1996 requested changes

2023-05-15 07:39 UTC, ronny1996 commented on paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
> +    } else if (op_device.find("npu") != std::string::npos &&
尽量不要使用硬编码的 "npu"

2023-05-15 09:09 UTC, YanhuiDua commented on python/paddle/fluid/framework.py
> +        '',
这里是否先添加了所有的custom device

2023-05-15 09:12 UTC, ronny1996 requested changes

2023-05-15 09:12 UTC, ronny1996 commented on python/paddle/fluid/framework.py
> +        '',
这里也不用用硬编码，paddle.device.get_all_custom_device_type() 可以获取所有已注册的custom device设备类型

2023-05-15 09:12 UTC, YanhuiDua commented on python/paddle/fluid/framework.py
> +        '',
好的

2023-05-15 09:12 UTC, YanhuiDua commented on paddle/fluid/framework/new_executor/interpreter/interpreter_util.cc
> +    } else if (op_device.find("npu") != std::string::npos &&
done

2023-05-15 09:25 UTC, ronny1996 approved these changes, later dismissed
LGTM

2023-05-17 12:00 UTC, qili93 approved these changes
LGTM

2023-05-17 13:03 UTC, merged