support sharding parallel
PaddlePaddle/Paddle pull request #54634
Opened 2023-06-14 03:26 UTC by pangengzheng

### PR types

Others
### PR changes

Others
### Description

Others
cherry-pick from https://github.com/PaddlePaddle/Paddle/pull/54069
card-72028

2023-06-26 06:17 UTC, pangengzheng commented
cherry-pick from https://github.com/PaddlePaddle/Paddle/pull/54069

2023-06-26 07:19 UTC, FeixLiu requested changes

2023-06-26 07:19 UTC, FeixLiu commented on python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
> +                    # TODO(pangengzheng): change to reduce operation when there is no diff in calculating global norm values in HybridParallelClipGrad compared to dp.
There is a logic conflict between sharding stage 1 and sharding_pp_overlap which can be addressed in one of this two ways:
1. If use `all_reduce`, this part https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/fleet/meta_parallel/pp_utils/utils.py#L249 should also be updated, you can ref this pr https://github.com/PaddlePaddle/Paddle/pull/54872
2. If use `reduce`, then nothing else this comm method should be updated.

2023-06-26 07:30 UTC, pangengzheng commented on python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
> +                    # TODO(pangengzheng): change to reduce operation when there is no diff in calculating global norm values in HybridParallelClipGrad compared to dp.
ok

2023-06-26 07:31 UTC, FeixLiu submitted a review, later dismissed
LGTM for the change in pp_utils

2023-07-11 10:02 UTC, dingjiaweiww approved these changes

2023-07-11 10:09 UTC, sneaxiy approved these changes

2023-07-11 11:55 UTC, qingqing01 approved these changes

2023-07-11 12:24 UTC, merged