[Custom Dice]add run_check support for custom device
PaddlePaddle/Paddle pull request #56318
Opened 2023-08-15 09:59 UTC by USTCKAY

### PR types

New features
### PR changes

Others
### Description

为Custom Device增加run_check支持。目前仅支持单一种类的Custom Device（如只安装了昇腾NPU）。
测试结果如下：
`I0816 00:21:36.809013 46151 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:21:36.809063 46151 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:21:45.779037 46151 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:21:45.785408 46151 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:21:45.785624 46151 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:21:45.785661 46151 init.cc:245] CustomDevice: npu, visible devices count: 8
Running verify PaddlePaddle program ... 
I0816 00:21:46.421669 46151 program_interpreter.cc:173] New Executor is Running.
I0816 00:21:56.070345 46151 interpreter_util.cc:602] Standalone Executor is Used.
PaddlePaddle works well on 1 npu.
I0816 00:22:03.654654 47214 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.654700 47214 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.654707 47218 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.654744 47218 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.679235 47224 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.679277 47224 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.679328 47222 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.679370 47222 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.733134 47226 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.733175 47226 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.745720 47216 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.745798 47216 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.774627 47228 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.774673 47228 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:22:03.844810 47220 init.cc:239] ENV [CUSTOM_DEVICE_ROOT]=/opt/py37env/lib/python3.7/site-packages/paddle_custom_device
I0816 00:22:03.844862 47220 init.cc:145] Try loading custom device libs from: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.845295 47224 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.845419 47214 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.845582 47216 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.845983 47218 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.845981 47226 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.846091 47222 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.846371 47220 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.847659 47228 custom_device.cc:1112] Successed in loading custom runtime in lib: /opt/py37env/lib/python3.7/site-packages/paddle_custom_device/libpaddle-custom-npu.so
I0816 00:23:01.853188 47222 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.853382 47222 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.853421 47222 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.855057 47216 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.855264 47216 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.855311 47216 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.856283 47214 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.856554 47214 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.856628 47214 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.856930 47224 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.857210 47224 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.857270 47224 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.861477 47228 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.861799 47228 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.861892 47228 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.869469 47218 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.871120 47218 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.871223 47218 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.871992 47226 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.872675 47226 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.872776 47226 init.cc:245] CustomDevice: npu, visible devices count: 8
I0816 00:23:01.876528 47220 custom_kernel.cc:76] Successed in loading 325 custom kernel(s) from loaded lib(s), will be used like native ones.
I0816 00:23:01.877274 47220 init.cc:157] Finished in LoadCustomDevice with libs_path: [/opt/py37env/lib/python3.7/site-packages/paddle_custom_device]
I0816 00:23:01.877414 47220 init.cc:245] CustomDevice: npu, visible devices count: 8
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_allocator_strategy', current_value='naive_best_fit', default_value='auto_growth [...]

2023-08-15 10:05 UTC, USTCKAY commented on python/paddle/utils/install_check.py
> +                os.environ['PADDLE_DISTRI_BACKEND'] = "xccl"
分布式通过读取环境变量`PADDLE_DISTRI_BACKEND`设置backend，默认值为auto。这里检出使用custom device后手动设置backend为xccl，避免设置错误的backend。

2023-08-16 01:51 UTC, qili93 requested changes

2023-08-16 01:51 UTC, qili93 commented on python/paddle/distributed/spawn.py
> +        return core.get_custom_device_count('mlu')
这里改成适用所有custom device的方式，不要用字符串进行判断，只能支持 npu 和  mlu 两种硬件类型。

2023-08-16 01:51 UTC, qili93 commented on python/paddle/distributed/spawn.py
> +        return 'xccl'
同上，这里修改为支持所有通过custom device注册的硬件类型，不要用过字符串判断。

2023-08-16 03:26 UTC, USTCKAY commented on python/paddle/distributed/spawn.py
> +        return core.get_custom_device_count('mlu')
done

2023-08-16 03:26 UTC, USTCKAY commented on python/paddle/distributed/spawn.py
> +        return 'xccl'
done

2023-08-16 05:25 UTC, qili93 requested changes

2023-08-16 05:25 UTC, qili93 commented on python/paddle/utils/install_check.py
> +        use_custom = _is_custom_device_available()
这里259行的判断逻辑应该是 >0, 存在注册多个custom device的情况，另外 _is_custom_device_available 里面实现的逻辑和 259 行 elif的逻辑是同一个，判断条件重复，可以去掉一个。

2023-08-16 07:09 UTC, USTCKAY commented on python/paddle/utils/install_check.py
> +        use_custom = _is_custom_device_available()
done

2023-08-16 07:54 UTC, qili93 requested changes

2023-08-16 07:54 UTC, qili93 commented on python/paddle/utils/install_check.py
> +        )
这里默认只跑 device[0]，判断一下如果有多个device注册，这里加点warning message提示下只对你device[0]进行检测

2023-08-16 08:16 UTC, USTCKAY commented on python/paddle/utils/install_check.py
> +        )
done

2023-08-16 08:28 UTC, qili93 approved these changes
LGTM

2023-08-17 02:51 UTC, merged