[Doctest]fix No.163,164,166, test=docs_preview
PaddlePaddle/Paddle pull request #56527
Opened 2023-08-22 03:42 UTC by liyongchao911

### PR types
Others

### PR changes
Others

### Description
修改如下文件的示例代码，使其通过 `xdoctest` 检查：
- python/paddle/vision/models/squeezenet.py
- python/paddle/vision/models/vgg.py
- python/paddle/vision/transforms/functional.py

### Related links

-  #55629
-  #55295

@sunzhongkai588 @SigureMo @megemini

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            >>> print(flpped_img.size)
flpped_img -> flipped_img

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            >>> print(flpped_img.size)
flpped_img -> flipped_img

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            >>> # doctest: -SKIP
用 seed，不需要 skip ～

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            >>> print(gray_img.size)
输出～

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            (300, 256)
输出不对～

2023-08-22 10:25 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            [ 0.56948012, -0.96200180,  0.53355658,  3.20450878]]])
用 seed ～ 另外，最好把方括号对齐一下 ～

2023-08-27 02:22 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            >>> print(flpped_img.size)
done!

2023-08-27 02:23 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            >>> print(flpped_img.size)
done!

2023-08-27 02:55 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            [ 0.56948012, -0.96200180,  0.53355658,  3.20450878]]])
done！

2023-08-27 11:21 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            >>> # doctest: -SKIP
done

2023-08-27 11:21 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            >>> print(gray_img.size)
done

2023-08-27 11:21 UTC, liyongchao911 commented on python/paddle/vision/transforms/functional.py
> +            (300, 256)
done

2023-08-27 11:31 UTC, SigureMo approved these changes
自行看下 log 吧，还有很多对不上的

2023-08-27 11:31 UTC, SigureMo commented on python/paddle/vision/transforms/functional.py
> +            (0.99215686 -1.0)
<img width="528" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/38436475/e5c3ee6c-7507-413f-a829-afe645bf0d35">

2023-08-27 11:32 UTC, SigureMo requested changes
点错了，不应该 approve 的

2023-08-28 05:16 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +             >>> print(fake_img.size)
多了一个空格 ～

2023-08-28 05:16 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            [-1.85003340, -0.23008066,  0.65083790,  0.75387722]]])
输出不要空行 ～ 另外，可以对齐一下方括号 ～

``` python
Tensor(shape=[3, 2, 4], dtype=float32, place=Place(cpu), stop_gradient=True,
[[[ 0.06132207,  1.11349595,  0.41906244, -0.24858207],
  [-1.85169315, -1.50370061,  1.73954511,  0.13331604]],
 [[ 1.66359663, -0.55764782, -0.59911072, -0.57773495],
  [-1.03176904, -0.33741450, -0.29695082, -1.50258386]],
 [[ 0.67233968, -1.07747352,  0.80170447, -0.06695852],
  [-1.85003340, -0.23008066,  0.65083790,  0.75387722]]])
```

2023-08-28 05:16 UTC, megemini commented on python/paddle/vision/transforms/functional.py
> +            [-1.85003340, -0.23008066,  0.65083790,  0.75387722]]])
同上

2023-08-29 11:04 UTC, megemini reviewed
有个地方写了很多空行，清理一下吧 ～ 其他的我这边没啥问题了 ～

2023-08-29 11:04 UTC, megemini commented on python/paddle/vision/transforms/functional.py
这里好多空行 ～ 是不是要整体修改一下 Codestyle ~

2023-09-01 01:30 UTC, SigureMo approved these changes
LGTMeow 🐾

2023-09-01 03:17 UTC, merged