[PIR] Unify dyn_cast interface with pir::cast
PaddlePaddle/Paddle pull request #57463
Opened 2023-09-18 10:53 UTC by zhangboSJTU

### PR types

Others
### PR changes

Others
### Description

+ 规范接口中的命名方式
+ 统一接口中 dyn_cast 的风格和命名
### Other
Pcard-67164

2023-09-18 12:08 UTC, winter-wang commented on paddle/pir/core/builtin_type_interfaces.h
>      return detail::any_of(vectorize(dSizes),
这个detail::any_of的实现只有一行，是不是可以直接调用它的实现，然后把detai::any_of删了。

2023-09-18 12:14 UTC, winter-wang commented on paddle/pir/core/builtin_type_interfaces.h
> +  explicit ShapedTypeInterface(Type type = Type())
这两个构造函数是必须的吗？

2023-09-18 12:37 UTC, winter-wang commented on paddle/fluid/pir/dialect/operator/interface/infermeta.h
> +  InferMetaInterface(std::nullptr_t)  // NOLINT
这两个构造函数的增加感觉不是必要的，而且会给IR库的扩展着造成额外的负担。

2023-09-18 12:40 UTC, zhangboSJTU commented on paddle/fluid/pir/dialect/operator/interface/infermeta.h
> +  InferMetaInterface(std::nullptr_t)  // NOLINT
OK，这里是想把 interface 抽出来，做一个 interfaceBase 的，在没有做 interfaceBase 前先和 op 的保持一致

2023-09-18 12:41 UTC, winter-wang requested changes
interface新增的两个构造函数不是必须的。会给Interface的开发者造成额外的负担，不建议增加。

2023-09-26 10:51 UTC, winter-wang approved these changes
LGTM

2023-09-27 02:42 UTC, merged