[complex] add complex support for softplus
PaddlePaddle/Paddle pull request #57540
Opened 2023-09-20 08:30 UTC by xiaoyewww

### PR types

Others 
### PR changes

APIs 

### Description

add complex support for softplus
https://github.com/PaddlePaddle/Paddle/issues/56689

2023-09-22 09:41 UTC, luotao1 commented
@ScottWong98 可以review一下

2023-09-24 05:54 UTC, ScottWong98 requested changes

2023-09-24 05:54 UTC, ScottWong98 commented on test/legacy_test/=1.6,
> +Defaulting to user installation because normal site-packages is not writeable
这个文件的作用是？

2023-09-25 06:16 UTC, GGBond8488 commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', max_relative_error=0.06)
complex64 和complex128的误差都是这样吗

2023-10-12 02:33 UTC, xiaoyewww commented
@GGBond8488 @ScottWong98 上述意见已修改，麻烦再review一下，谢谢

2023-10-12 03:43 UTC, GGBond8488 approved these changes
LGTM

2023-10-12 06:32 UTC, luotao1 commented
@xiaoyewww 请补充下对应的中文文档

2023-10-12 13:21 UTC, xiaoyewww commented
> @xiaoyewww 请补充下对应的中文文档

@luotao1 请问一下中文文档是指哪部分？我看其他pr里面都没有补充

2023-10-13 02:18 UTC, luotao1 commented
可以参考下这个
- https://github.com/PaddlePaddle/docs/pull/6202

2023-10-13 02:39 UTC, ZzSean approved these changes
LGTM for CI-OP-Benchmark

2023-10-13 02:40 UTC, merged