[xdoctest][task 325] reformat example code with google style in paddle/fluid/pybind/place.cc
PaddlePaddle/Paddle pull request #57610
Opened 2023-09-21 12:16 UTC by sunzhongkai588

### PR types

Others 
### PR changes

Others 
### Description

修改如下文件的示例代码，使其通过 `xdoctest` 检查：

- `paddle/fluid/pybind/place.cc`

@megemini @SigureMo 

### Related links
- #55629

2023-09-21 15:29 UTC, SigureMo approved these changes
PR-CI-Codestyle-Check 挂了哦，需要跑一下 pre-commit

2023-09-21 15:29 UTC, SigureMo commented on paddle/fluid/pybind/place.cc
> +            >>> import paddle
required:ipu 要改成 doctest directive

2023-09-21 15:30 UTC, SigureMo requested changes
点错了，不小心 approve 了

2023-09-22 04:50 UTC, megemini commented on paddle/fluid/pybind/place.cc
> +            >>> fake_cpu_place = paddle.CustomPlace("FakeCPU", 0)
需要加个 `>>> # doctest: +REQUIRES(env:CUSTOM_DEVICE)` ，不然直接报错跳出来了 ～

2023-09-22 04:50 UTC, megemini commented on paddle/fluid/pybind/place.cc
> +            >>> xpu_place = base.XPUPlace(0)
同上，需要加个 `>>> # doctest: +REQUIRES(env:XPU)`

2023-09-26 11:01 UTC, megemini approved these changes
LSTM ～ 🤗

2023-09-27 04:59 UTC, SigureMo approved these changes
LGTMeow 🐾

2023-09-27 08:37 UTC, merged