Faster
PaddlePaddle/Paddle pull request #57883
Opened 2023-10-07 01:46 UTC by niuliling123

### PR types

Others
### PR changes

Others
### Description

Others

2023-10-25 07:46 UTC, sneaxiy commented on paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.h
>  } OpType;
这些改动是为什么？现在这个分支没有这些代码也是可编译的。

2023-10-25 07:46 UTC, sneaxiy commented on paddle/phi/kernels/flash_attn_kernel.h
> +#pragma once
删除之。

2023-10-25 07:46 UTC, sneaxiy commented on python/paddle/nn/functional/flash_attention.py
> +            (result_attention, result_softmax,) = _C_ops.flash_attn(
为什么删掉这个？

2023-10-25 07:46 UTC, sneaxiy commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +                                 int64_t numel,
这个代码有什么用？

2023-10-25 07:46 UTC, sneaxiy commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +    const Context& ctx, int64_t numel, float scale, const T* input, T* output) {
这个代码有什么用？

2023-10-25 07:49 UTC, niuliling123 commented on paddle/phi/kernels/fusion/cutlass/conv2d/conv2d_util.h
>  } OpType;
当时编译出现这个报错就直接添加了，后面删除

2023-10-25 07:56 UTC, niuliling123 commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +                                 int64_t numel,
<img width="398" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/51102941/871ada87-2473-402d-895b-7b48783b25ce">
反向计算q_grad

2023-10-25 11:14 UTC, niuliling123 commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +    const Context& ctx, int64_t numel, float scale, const T* input, T* output) {
反向计算q_grad

2023-10-25 11:14 UTC, niuliling123 commented on python/paddle/nn/functional/flash_attention.py
> +            (result_attention, result_softmax,) = _C_ops.flash_attn(
v2 只返回2个参数， result 和 softmax

2023-10-25 13:57 UTC, sneaxiy commented on python/paddle/nn/functional/flash_attention.py
> +            (result_attention, result_softmax,) = _C_ops.flash_attn(
这个取决于怎么设计，后2个参数是主动返回的，有特殊用途，这里建议不要修改。

2023-10-25 16:51 UTC, sneaxiy commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +    const Context& ctx, int64_t numel, float scale, const T* input, T* output) {
但是这个函数没被调用？

2023-10-25 16:51 UTC, sneaxiy commented on python/paddle/nn/functional/flash_attention.py
> +            (result_attention, result_softmax,) = _C_ops.flash_attn(
而且ops.yaml里返回4个参数，为什么这里返回2个参数，不会报错？

2023-10-26 06:14 UTC, niuliling123 commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +    const Context& ctx, int64_t numel, float scale, const T* input, T* output) {
调用了， 你全文搜一下就能看到

2023-10-26 07:26 UTC, sneaxiy commented on paddle/phi/api/yaml/ops.yaml
> +  intermediate : softmax_lse, seed_offset
这两个输出是有特殊用途的，必须改回去。同时，Python代码也得改回去。

2023-10-26 13:25 UTC, AnnaTrainingG commented on paddle/phi/api/yaml/ops.yaml
> +  intermediate : softmax_lse, seed_offset
已经删除

2023-10-26 13:40 UTC, niuliling123 commented on paddle/phi/kernels/flash_attn_kernel.h
> +#pragma once
done

2023-10-26 13:40 UTC, niuliling123 commented on python/paddle/nn/functional/flash_attention.py
> +            (result_attention, result_softmax,) = _C_ops.flash_attn(
dong

2023-10-26 13:40 UTC, niuliling123 commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +                                 int64_t numel,
done

2023-10-26 13:40 UTC, AnnaTrainingG commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +    const Context& ctx, int64_t numel, float scale, const T* input, T* output) {
done

2023-10-26 13:59 UTC, sneaxiy approved these changes

2023-10-26 16:50 UTC, sneaxiy requested changes
经测试，有明显降速现象，需要进一步定位问题。

2023-10-27 15:16 UTC, sneaxiy submitted a review, later dismissed

2023-11-08 13:15 UTC, sneaxiy approved these changes

2023-11-08 13:15 UTC, merged