Fix_batchnorm的optional语义
PaddlePaddle/Paddle pull request #58226
Opened 2023-10-19 06:23 UTC by xuxinyi389

### PR types
Bug fixes
### PR changes
APIs 
### Description
Pcard-73263
修复batchnorm的ParamAttr语义，支持为optional

2023-10-19 13:18 UTC, zhwesky2010 commented on test/legacy_test/test_batch_norm_op_v2.py
> +            def compute_v3_1(x, is_test, trainable_statistics):
这几个case调用一下反向，目前看还没有跑到反向里。

另外是不是ONEDNN kernel没有适配，这个合入后像这样创建一个issue通知intel适配吧 https://github.com/PaddlePaddle/Paddle/issues/51364

2023-10-23 08:33 UTC, zhwesky2010 approved these changes
LGTM

2023-10-23 09:34 UTC, yuanlehome requested changes
需按照如流沟通的，验证下对推理代码的影响。在这个单测 test/ir/inference/test_trt_convert_batch_norm.py 下添加 optional 的组网，并跑通

2023-10-23 11:09 UTC, yuanlehome approved these changes
风险：用户使用新版paddle训练并保存的模型，推理时会挂掉。

2023-10-23 12:09 UTC, xuxinyi389 commented
> 风险：用户使用新版paddle训练并保存的模型，推理时会挂掉。

2023-10-23 12:14 UTC, xuxinyi389 commented
> 风险：用户使用新版paddle训练并保存的模型，推理时会挂掉。

目前，pytorch的batchnormAPI均支持optional语意，但paddle部分api对optional的支持是缺失的，目前这个pr（https://github.com/PaddlePaddle/Paddle/pull/58226）的工作就是要修复这个问题，并作为示例PR推动外部开发者帮助修复剩下的InstanceNorm、GroupNorm、SyncBatchNorm修复。这一部分代码的改动是兼容升级，对当前所支持的运行方式是完整支持的。至于新用法存在的风险的解决方法是，对Intel方面的提了一个issue（https://github.com/PaddlePaddle/Paddle/issues/58326）推动同步，对于给推理带来的风险，目前的建议是推理侧整理下任务需求，后面一同放到快乐开源修改。

2023-10-24 02:32 UTC, chenwhql approved these changes
LGTM for PADDLE_ENFORCE

2023-10-24 02:44 UTC, cyber-pioneer commented
Todo：组合机制batch_norm前向拆解受影响，逻辑需要适配，以及缺少相关单侧覆盖

2023-10-24 02:45 UTC, cyber-pioneer approved these changes
LGTM for prim backward

2023-10-24 02:59 UTC, wanghuancoder approved these changes

2023-10-24 03:08 UTC, sunzhongkai588 approved these changes
LGTM，中文文档同步

2023-10-24 03:08 UTC, sunzhongkai588 commented on python/paddle/nn/functional/norm.py
> +        bias(Tensor, optional): The bias tensor of batch_norm.
该部分参数描述更新，也在中文文档同步吧

2023-10-24 06:13 UTC, merged