【PIR API adaptor No.221】 Migrate tanhshrink/thresholded_relu/Selu/RRelu into pir
PaddlePaddle/Paddle pull request #58429
Opened 2023-10-26 13:08 UTC by DrRyanHuang

### PR types

Others

### PR changes

APIs 

### Description

No.221 与 leaky_relu
PIR API 推全升级

将 paddle.nn.Swish 迁移升级至 pir，并更新单测 单测覆盖率：3/4
将 paddle.nn.LeakyReLU 迁移升级至 pir，并更新单测 单测覆盖率：3/4

存在问题:

2023-10-30 11:06 UTC, 0x45f commented on test/legacy_test/test_activation_op.py
> +    @test_with_pir_api
test_errors这类测试raise error的单测可以先不打开，在pr描述中标记一下就可以

2023-10-30 11:06 UTC, 0x45f commented on test/legacy_test/test_activation_op.py
> +    @test_with_pir_api
同上

2023-10-30 11:06 UTC, 0x45f commented on test/legacy_test/test_maxout_op.py
> +    @test_with_pir_api
同上

2023-10-30 11:06 UTC, 0x45f commented on test/legacy_test/test_rrelu_op.py
> +    @test_with_pir_api
同上

2023-10-30 11:06 UTC, 0x45f commented on test/legacy_test/test_selu_op.py
> +    @test_with_pir_api
同上

2023-11-01 10:57 UTC, MarioLulab requested changes
nice work~ 但是有一些单测缺失，需要补上

2023-11-01 10:57 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
`TestTanhshrink` 会继承 TestActivation 的 `test_check_output` 方法，但是 TestActivation::test_check_output 方法没有开启 check_pir，可以继承并重写:

```python
def test_check_output(self):
    self.check_output(check_pir=True)
```

2023-11-01 10:57 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
还有 test_activation_op.py 文件下面的 `create_test_act_fp16_class(TestTanhshrink)` 与 `create_test_act_bf16_class(TestTanhshrink)` 也都需要打开 `check_pir=True`

2023-11-01 10:57 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +    @test_with_pir_api
`TestThresholdedRelu` 同样需要打开 check_pir 开关

2023-11-01 10:57 UTC, MarioLulab commented on test/legacy_test/test_rrelu_op.py
`TestFunctionalRReluAPI` 还没有打开 check_pir 开关

2023-11-09 05:44 UTC, MarioLulab requested changes

2023-11-09 05:44 UTC, MarioLulab commented on test/legacy_test/test_rrelu_op.py
> +            for place in self.places:
for-loop 可以放在 `with paddle.static.program_guard(main, startup):` 管理的建图上下文的外面。否则在 pir 模式下对同一个 main 和 startup 多次建图可能会导致错误，类似的问题已经记录在了：https://github.com/PaddlePaddle/Paddle/issues/58259#issuecomment-1788867715

2023-11-09 05:44 UTC, MarioLulab commented on test/legacy_test/test_rrelu_op.py
> +            for place in self.places:
同上

2023-11-09 05:44 UTC, MarioLulab commented on test/legacy_test/test_rrelu_op.py
> +        with paddle.static.program_guard(main, startup):
问题类似，在 pir 模式下对同一个 program 两次 exe.run，导致第二次 exe.run 时 出现错误

2023-11-09 05:44 UTC, MarioLulab commented on test/legacy_test/test_rrelu_op.py
> +    @test_with_pir_api
这个单测取消掉 pir 模式下吧，当前还不支持，ci 也报错了~

2023-11-10 10:31 UTC, 0x45f commented on test/legacy_test/test_rrelu_op.py
> +            with paddle.static.program_guard(main, startup):
这里需要用新的main_program和startup_program~下面也一样，一个函数内每个with program_guard都用新的program试试呢

2023-11-13 07:38 UTC, MarioLulab approved these changes
LGTM

2023-11-13 08:04 UTC, 0x45f approved these changes

2023-11-13 08:04 UTC, merged