【PIR API adaptor No.41、138、153】 Migrate paddle.complex, paddle.logspace, paddle.meshgrid into pir
PaddlePaddle/Paddle pull request #58491
Opened 2023-10-30 08:48 UTC by enkilee

### PR types

Others
### PR changes

APIs
### Description

PIR API 推全升级

* https://github.com/PaddlePaddle/Paddle/issues/58067

No.41 将 `paddle.complex` 迁移升级至 pir，并更新单测 单测覆盖率：5/5
No.138 将 `paddle.logspace ` 迁移升级至 pir，并更新单测 单测覆盖率：8/8
No.153 将 `paddle.complex` 迁移升级至 pir，并更新单测 单测覆盖率：8/8

2023-10-30 09:46 UTC, MarioLulab requested changes
可以在 PR 描述里说明一下：`test/legacy_test/test_logspace.py` 中的 TestLogspaceAPI.test_name 和 TestLogspaceOpError 尚不支持

2023-10-31 07:12 UTC, 0x45f commented
logspace的单测为什么全都没有打开呢？

2023-10-31 07:19 UTC, 0x45f commented
logspace的适配有点问题，在调用_C_ops.logspace之前有一些检查的逻辑没有适配。可以参考creation.py文件arange API 1378行附近的代码，适配之后可以尝试在打开logspace的相关单测~

2023-10-31 07:31 UTC, 0x45f commented
meshgrid单测3个继承自TestCase单测报错是因为在新IR下program用到了老的program，以TestMeshgridOp3为例，可以尝试做类似如下的修改
![image](https://github.com/PaddlePaddle/Paddle/assets/23097963/bba801bf-03ad-4070-9f0f-d9a0367c7ef0)

2023-11-01 03:48 UTC, enkilee commented
already done.

2023-11-01 10:34 UTC, MarioLulab approved these changes
LGTM

2023-11-01 11:18 UTC, 0x45f approved these changes
LGTM

2023-11-01 11:18 UTC, merged