【PIR API adaptor No.50、57、67】fix for 58466
PaddlePaddle/Paddle pull request #58541
Opened 2023-10-31 12:55 UTC by longranger2

### PR types
Others

### PR changes
APIs

### Description
将cumprod和digamma的单测都打开

- https://github.com/PaddlePaddle/Paddle/issues/58067

2023-11-02 02:58 UTC, MarioLulab requested changes

2023-11-02 02:58 UTC, MarioLulab commented on test/legacy_test/test_cumprod_op.py
> +    @test_with_pir_api
@test_with_pir_api 装饰器应该**直接**修饰静态图单测。比如:
```python
class TestCumprodAPI(unittest.TestCase):
   ...
   @test_with_pir_api
   def test_static_api(self):
         paddle.enable_static()
```

2023-11-02 02:58 UTC, MarioLulab commented on test/legacy_test/test_digamma_op.py
> +    @test_with_pir_api
同上，@test_with_pir_api 装饰器应该直接修饰静态图单测

2023-11-02 06:47 UTC, longranger2 commented
done

2023-11-02 09:33 UTC, MarioLulab commented
从 `PR-CI-Py3`  的报错信息来看：ci 挂在了 test/legacy_test/test_digamma_op.py。目前场景下，在 pir 模式中，应该不支持直接使用 OpResult.name，可以作如下修改试试：

```python
    @test_with_pir_api
    def test_in_static_mode(self):
        def init_input_output(dtype):
            input = np.random.random(self._shape).astype(dtype)
            return {'x': input}, psi(input)
        for dtype in self.dtypes:
            input_dict, sc_res = init_input_output(dtype)
            for place in self.places:
                with static.program_guard(static.Program()):
                    x = static.data(name="x", shape=self._shape, dtype=dtype)
                    out = paddle.digamma(x)
                    exe = static.Executor(place)
                    # out_value = exe.run(feed=input_dict, fetch_list=[out.name])     # <--------- 报错的地方
                    # 改成试试：
                    out_value = exe.run(feed=input_dict, fetch_list=[out]) 
                    np.testing.assert_allclose(out_value[0], sc_res, rtol=1e-05)
```

2023-11-03 02:37 UTC, MarioLulab approved these changes
LGTM

2023-11-03 02:41 UTC, 0x45f approved these changes

2023-11-03 03:26 UTC, merged