Custom op support auto parallel
PaddlePaddle/Paddle pull request #58553
Opened 2023-11-01 04:39 UTC by wanghuancoder

### PR types

### PR changes

### Description

2023-11-03 09:11 UTC, GhostScreaming commented on paddle/phi/api/lib/op_meta_info.cc
> +  } else {
这里需要考虑`SelectedRows`这些其他的Tensor类型吗

2023-11-03 09:14 UTC, GhostScreaming approved these changes, later dismissed
LGTM

2023-11-03 09:15 UTC, jiahy0825 requested changes

2023-11-03 09:15 UTC, jiahy0825 commented on test/auto_parallel/semi_auto_parallel_simple_net_custom_relu.py
> +        'dist_custom_relu_op.cu',
这几个 kernel 文件和原来的实现有区别吗？是不是可以复用原来的 kernel 代码，应该可以通过相对路径找到

2023-11-03 09:15 UTC, jiahy0825 commented on paddle/phi/api/ext/op_meta_info.h
> +  const std::vector<std::pair<size_t, size_t>>& OutputRange() const;
感谢欢哥对这里的 const 保障

2023-11-03 09:15 UTC, jiahy0825 commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +#ifdef PADDLE_WITH_DISTRIBUTE
最好把 `#ifdef PADDLE_WITH_DISTRIBUTE` 里的代码独立出来一个函数

2023-11-03 09:15 UTC, jiahy0825 commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +                        paddle::CustomOpKernelContext& ctx) {  // NOLINT
对于写入的变量，在自定义算子的体系里，要改成指针。
paddle::CustomOpKernelContext* ctx
paddle::OpMetaInfo op_info 也做了写入吧？也要改成指针形式

2023-11-06 01:47 UTC, wanghuancoder commented on test/auto_parallel/semi_auto_parallel_simple_net_custom_relu.py
> +        'dist_custom_relu_op.cu',
好的，我试试~感谢！

2023-11-06 01:47 UTC, wanghuancoder commented on paddle/phi/api/ext/op_meta_info.h
> +  const std::vector<std::pair<size_t, size_t>>& OutputRange() const;
客气啦~

2023-11-06 01:47 UTC, wanghuancoder commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +#ifdef PADDLE_WITH_DISTRIBUTE
啊，这个是为了和PHI api.cc里的格式保持一致~

2023-11-06 01:49 UTC, wanghuancoder commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +                        paddle::CustomOpKernelContext& ctx) {  // NOLINT
我把paddle::OpMetaInfo op_info改成const paddle::OpMetaInfo& op_info吧~
ctx在run_custom_op_impl还要做修改，但指针我觉得大量使用不方便。所以加了NOLINT。

2023-11-06 02:14 UTC, wanghuancoder commented on test/auto_parallel/semi_auto_parallel_simple_net_custom_relu.py
> +        'dist_custom_relu_op.cu',
我试了，可以。感谢！！

2023-11-06 05:14 UTC, jiahy0825 commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +                current_process_mesh, out_dim[0], out_dtype[0]);
这里下标是不是有问题，应该修改为 j ?

2023-11-06 05:14 UTC, jiahy0825 commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +#ifdef PADDLE_WITH_DISTRIBUTE
感觉还是有必要独立出来，此处分布式和自定义算子的耦合太重了，如果后续需要调试，预计这里的维护成本会很高

2023-11-06 07:01 UTC, wanghuancoder commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +                current_process_mesh, out_dim[0], out_dtype[0]);
感谢感谢！不然是个大坑！

2023-11-06 07:20 UTC, jiahy0825 submitted a review, later dismissed
LGTM~ Great work!

2023-11-07 02:34 UTC, XieYunshen approved these changes
LGTM

2023-11-07 02:45 UTC, GhostScreaming approved these changes
LGTM

2023-11-07 03:22 UTC, chenwhql approved these changes

2023-11-07 03:22 UTC, chenwhql commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +            ? paddle::get<0>(spmd_info.first[0]).process_mesh()
paddle::get直接使用需要加try catch，或者直接使用PADDLE_GET系列宏，不然一旦报错就很难分析，后面建议再完善一下

2023-11-07 05:08 UTC, XiaoguangHu01 approved these changes
LGTM

2023-11-07 05:48 UTC, merged

2023-11-09 09:09 UTC, RichardWooSJTU commented on paddle/fluid/eager/custom_operator/custom_operator_utils.cc
> +        PADDLE_ENFORCE_EQ(
我这边一个带可选input自定义算子的执行会出现问题，定位到这里应该是input.impl().get()出来了一个空指针，请问这里有考虑自定义算子的可选Input吗