[PIR API adaptor NO.97-100, 209-211] Migrate softplus/softsign/hardshrink/hardtanh/hardsigmoid/hardswish into pir
PaddlePaddle/Paddle pull request #58593
Opened 2023-11-01 16:14 UTC by BeingGod

### PR types

Others
### PR changes

Others
### Description

1. softplus 单测覆盖率：6/8
2. softshrink 单测覆盖率：3/5
3. softsign 单测覆盖率：3/5
4. hardshrink 单测覆盖率：3/5
5. hardtanh 单测覆盖率：3/4
6. hardsigmoid 单测覆盖率：6/8
7. hardswish 单测覆盖率：6/8

https://github.com/PaddlePaddle/Paddle/issues/58067

2023-11-02 09:24 UTC, MarioLulab requested changes
nice work ~ 但遗漏了部分 fp16 和 bf16 的单测，麻烦大佬添加一下吧 😃 
可以顺便在 pr 描述里填写：test_error 单测未支持

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> -        self.check_grad(['X'], 'Out')
hard_shrink 在本文件 (test/legacy_test/test_activation_op.py) 的下面有两个分别被 `create_test_act_fp16_class` 和 `create_test_act_bf16_class` 创建的 fp16 和 bf16 单测，直接在文件里搜索 `TestHardShrink` 就能看到，这两个单测的 check_pir 开关也需要打开。
麻烦添加一下吧~

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +
softshrink 同上，需要添加 bf16, fp16 单测

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
>              return
hardtanh 同上，需要添加 bf16, fp16 单测

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> -            else False
hardswish 同上，需要添加 fp16 和 bf16 的单测

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
softplus 同上，需要添加 fp16 和 bf16 的单测

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
softsign 同理，需要添加 fp16 和 bf16 单测

2023-11-02 09:24 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +    def test_check_grad(self):
hardsigmoid 同理，需要添加 fp16 和 bf16 单测

2023-11-03 02:26 UTC, MarioLulab requested changes
还有一些问题🔧~

2023-11-03 02:26 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +create_test_act_fp16_class(TestTanhshrink, check_pir=True)
貌似本 pr 未做 tanhshrink 的迁移？所以这个 check_pir 应该关闭
```suggestion
create_test_act_fp16_class(TestTanhshrink)
```

2023-11-03 02:26 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
>  create_test_act_bf16_class(TestHardSwish, check_prim=True)
这里忘记打开 check_pir 了
```suggestion
create_test_act_bf16_class(TestHardSwish, check_prim=True, check_pir=True)
```

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> -        self.check_grad(['X'], 'Out')
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> +
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
>              return
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> -            else False
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> +    def test_check_grad(self):
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
> +create_test_act_fp16_class(TestTanhshrink, check_pir=True)
done

2023-11-03 02:41 UTC, BeingGod commented on test/legacy_test/test_activation_op.py
>  create_test_act_bf16_class(TestHardSwish, check_prim=True)
done

2023-11-06 01:30 UTC, MarioLulab approved these changes
LGTM

2023-11-06 02:46 UTC, Aurelius84 approved these changes
LGTM

2023-11-06 02:55 UTC, 0x45f approved these changes

2023-11-06 03:15 UTC, merged