【PIR API adaptor No.105】 Migrate paddle.sin into pir
PaddlePaddle/Paddle pull request #58603
Opened 2023-11-02 05:36 UTC by PommesPeter

### PR types
Others

### PR changes
APIs

### Description

PIR API 推全升级
将 `paddle.sin` 迁移升级至 pir，并更新单测

单测覆盖率：8/8

TODO：目前缺少适配 `test/legacy_test/test_activation_nn_grad.py` 内
 `TestSinDoubleGradCheck` 和 `TestSinTripleGradCheck` 的单测。
原因是当前不支持 `gradient_checker.double_grad_check` 和 `gradient_checker.triple_grad_check` 在 pir 体系下运行，
具体的适配问题包括但不限于：目前缺少从 python 端获取 OpResult.name 的支持

后续做自动微分推全工作的时候，可以进行支持

2023-11-03 02:10 UTC, MarioLulab requested changes
nice work，只有一个地方有问题，麻烦修改一下吧 😄

2023-11-03 02:10 UTC, MarioLulab commented on python/paddle/tensor/math.py
> +    if in_dynamic_or_pir_mode():
i0_ 函数被装饰器 `@inplace_apis_in_dygraph_only` 修饰，只能运行在动态图模式下；而我们的 pir 属于静态图，所以这里不需要改动，复原一下吧~
```suggestion
    if in_dynamic_mode():
```

2023-11-03 14:15 UTC, PommesPeter commented on python/paddle/tensor/math.py
> +    if in_dynamic_or_pir_mode():
好的，done

2023-11-03 14:15 UTC, PommesPeter commented on python/paddle/tensor/math.py
> +    if in_dynamic_or_pir_mode():
好的，done

2023-11-04 09:45 UTC, PommesPeter commented
`PR-CI-Codestyle-Check` CI 本地可以通过但是线上 CI 无法通过

2023-11-06 03:30 UTC, 0x45f commented
> `PR-CI-Codestyle-Check` CI 本地可以通过但是线上 CI 无法通过

rerun了下这条流水线，还是会失败。建议在本地随便修改下test_i0_op.py这个文件（加个空格或者空行），然后git add一下，然后再pre-commit一下看是否能修复~

2023-11-06 07:01 UTC, PommesPeter commented
> > `PR-CI-Codestyle-Check` CI 本地可以通过但是线上 CI 无法通过
> 
> rerun了下这条流水线，还是会失败。建议在本地随便修改下test_i0_op.py这个文件（加个空格或者空行），然后git add一下，然后再pre-commit一下看是否能修复~

还是无法解决，本地没有提示有修改内容

2023-11-06 08:50 UTC, PommesPeter commented
> > `PR-CI-Codestyle-Check` CI 本地可以通过但是线上 CI 无法通过
> 
> rerun了下这条流水线，还是会失败。建议在本地随便修改下test_i0_op.py这个文件（加个空格或者空行），然后git add一下，然后再pre-commit一下看是否能修复~

解决了，正在 rerun

2023-11-07 02:41 UTC, YuanRisheng approved these changes

2023-11-07 02:41 UTC, merged