【PIR API adaptor No.166】 Migrate paddle.polygamma into pir
PaddlePaddle/Paddle pull request #58605
Opened 2023-11-02 05:51 UTC by PommesPeter

### PR types
Others

### PR changes
APIs

### Description

PIR API 推全升级
将 `paddle.polygamma` 迁移升级至 pir，并更新单测

单测覆盖率：0/8

2023-11-03 02:14 UTC, MarioLulab requested changes

2023-11-03 02:14 UTC, MarioLulab commented on python/paddle/tensor/math.py
> +        if in_dynamic_or_pir_mode():
polygamma_ 函数被装饰器 @inplace_apis_in_dygraph_only 修饰，只能运行在动态图模式下；而我们的 pir 属于静态图，所以这里不需要改动，复原一下吧~
```suggestion
        if in_dynamic_mode():
```

2023-11-03 02:14 UTC, MarioLulab commented on test/legacy_test/test_i0e_op.py
>              ['x'],
本 pr 应该是只迁移 `paddle.polygamma` ，所以 `paddle.i0e` 的单测应该不用做修改。复原一下吧

2023-11-03 14:16 UTC, PommesPeter commented on python/paddle/tensor/math.py
> +        if in_dynamic_or_pir_mode():
好的 done

2023-11-03 14:17 UTC, PommesPeter commented on test/legacy_test/test_i0e_op.py
>              ['x'],
抱歉，修改的时候忘记切换分支了

2023-11-06 01:51 UTC, MarioLulab approved these changes
LGTM

2023-11-06 02:43 UTC, 0x45f approved these changes

2023-11-06 02:45 UTC, merged