【PIR API adaptor No.54-56】Migrate some ops into pir
PaddlePaddle/Paddle pull request #58627
Opened 2023-11-02 13:24 UTC by longranger2

### PR types
Others

### PR changes
APIs

### Description

PIR API 推全升级
将如下算子迁移升级至 pir，并更新单测
- diagflat（1/2）：总计 2 个单测，打开1个单测，1个单测用来测试error的
- diag_embed（3/3）
- diagonal（9/9）

- https://github.com/PaddlePaddle/Paddle/issues/58067

2023-11-03 03:13 UTC, MarioLulab commented
现在 ci 挂在了 PR-CI-Py3，我看了一下挂的具体位置：TestDiagEmbedAPICase 的 test_case1 . 具体解决办法可以参考 https://github.com/PaddlePaddle/Paddle/issues/58259#issuecomment-1776870397
可能需要修改一下现在的单测~

2023-11-03 03:32 UTC, longranger2 commented
> 现在 ci 挂在了 PR-CI-Py3，我看了一下挂的具体位置：TestDiagEmbedAPICase 的 test_case1 . 具体解决办法可以参考 [#58259 (comment)](https://github.com/PaddlePaddle/Paddle/issues/58259#issuecomment-1776870397) 可能需要修改一下现在的单测~

对的，这个我看到了，晚点修复下~

2023-11-06 02:02 UTC, MarioLulab commented
现在 ci 挂在了 PR-CI-windows，具体位置是 test/legacy_test/test_diagflat.py 的 TestDiagFlatAPI::run_static。可能的解决思路是：这个函数里的静态图构建采用 static.program_guard 来管理，如下：
```
main = paddle.static.Program()
startup = paddle.static.Program()
with paddle.static.program_guard(main, startup):
    ....
```

2023-11-07 08:36 UTC, MarioLulab commented on test/legacy_test/test_diagflat.py
> +        with paddle.static.program_guard(main, startup):
目前挂在了 ci 阶段：PR-CI-Py3。原因应该是没有运行 startup program. 可以做如下修改：
```python
  with paddle.static.program_guard(main, startup):
      exe = paddle.static.Executor(place)
      exe.run(startup)            # <----------------- 运行 startup program
      res0, res3 = exe.run(
          main,
          feed={"input": self.input_np, 'input2': self.input_np2},
          fetch_list=[result0, result3],
      )
```

2023-11-08 09:32 UTC, MarioLulab requested changes
ci 好像又挂了 🐶

2023-11-08 09:32 UTC, MarioLulab commented on test/legacy_test/test_diagflat.py
> +        with paddle.static.program_guard(main, startup):
我重新分析了一下 ci 挂的原因
```python
x = paddle.static.data(name='input', shape=[10, 10], dtype='float64')
x2 = paddle.static.data(name='input2', shape=[20], dtype='float64')
result0 = paddle.diagflat(x)
result3 = paddle.diagflat(x2)
```
应该放在 `with paddle.static.program_guard(main, startup):` 下，比如：
```python
main = paddle.static.Program()
startup = paddle.static.Program()
with paddle.static.program_guard(main, startup):
    x = paddle.static.data(name='input', shape=[10, 10], dtype='float64')
    x2 = paddle.static.data(name='input2', shape=[20], dtype='float64')
    result0 = paddle.diagflat(x)
    result3 = paddle.diagflat(x2)
    ...
```
这样 x, x2 等变量才会被构建在指定的 program ( main, startup ) 之中

2023-11-09 05:54 UTC, MarioLulab reviewed
great work ~ 
但还有一些小问题，辛苦修改一下吧。btw，这个 pr 描述貌似有误，erfinv 应该改为 diagonal?

2023-11-09 05:54 UTC, MarioLulab commented on test/legacy_test/test_diagflat.py
这个文件下还遗漏了 test_fp16_with_gpu 这个静态图单测，麻烦大佬修改一下吧 ~ 😃

2023-11-09 06:08 UTC, longranger2 commented
> great work ~ 但还有一些小问题，辛苦修改一下吧。btw，这个 pr 描述貌似有误，erfinv 应该改为 diagonal?

done

2023-11-10 01:24 UTC, MarioLulab approved these changes
LGTM

2023-11-10 02:40 UTC, YuanRisheng approved these changes

2023-11-10 02:40 UTC, merged