【PIR API adaptor No.131】 Migrate paddle.Tensor.log2 into pir
PaddlePaddle/Paddle pull request #58634
Opened 2023-11-02 16:23 UTC by xiaoyewww

### PR types

Others

### PR changes

APIs

### Description

PIR API 推全升级
将 paddle.Tensor.log2 迁移升级至 pir，并更新单测

单测覆盖率：3/3
https://github.com/PaddlePaddle/Paddle/issues/58067

2023-11-03 02:03 UTC, MarioLulab requested changes
nice work ~ 但有一些单测遗漏，需要修改一下 😃

2023-11-03 02:03 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +    @test_with_pir_api
这个单测并没有运行在静态图下，所以不需要 `@test_with_pir_api` 修饰

2023-11-03 02:03 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
>      def test_api(self):
此文件（test/legacy_test/test_activation_op.py） 的下面还有 被 create_test_act_fp16_class 与 create_test_act_bf16_class 创建的 fp16 与 bf16 单测，即 create_test_act_fp16_class(TestLog2) 和 create_test_act_bf16_class(TestLog2)。这些单测貌似没有打开 check_pir 开关，麻烦打开一下吧~

2023-11-03 02:03 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
btw, 在 `test/legacy_test/test_op_name_conflict.py` 文件的TestOpNameConflict，有一个运行在静态图下的单测，也使用 `@test_with_pir_api` 修饰一下吧

2023-11-03 08:06 UTC, xiaoyewww commented
@MarioLulab 已按照要求修改，麻烦重新review，多谢~

2023-11-06 02:03 UTC, MarioLulab approved these changes
LGTM

2023-11-06 02:39 UTC, 0x45f approved these changes

2023-11-06 02:40 UTC, merged