【PIR API adaptor No.17、33、72、101、121、125】Migrate paddle.atan2，paddle.deg2rad，paddle.floor_divide，paddle.heaviside，paddle.kron，paddle.lerp into pir
PaddlePaddle/Paddle pull request #58718
Opened 2023-11-06 09:22 UTC by enkilee

### PR types

Others
### PR changes

APIs
### Description

* https://github.com/PaddlePaddle/Paddle/issues/58067

PIR API 推全升级
No.17、33、72、101、121、125
将 `paddle.atan2` 迁移升级至 pir，并更新单测
将 `paddle.deg2rad` 迁移升级至 pir，并更新单测
将 `paddle.floor_divide` 迁移升级至 pir，并更新单测
将 `paddle.heaviside` 迁移升级至 pir，并更新单测
将 `paddle.kron` 迁移升级至 pir，并更新单测
将 `paddle.lerp` 迁移升级至 pir，并更新单测

2023-11-08 09:16 UTC, MarioLulab requested changes
nice work~ 
但还有些小问题需要修改 🚀

2023-11-08 09:16 UTC, MarioLulab commented on test/legacy_test/test_elementwise_floordiv_op.py
> +        paddle.enable_static()
目前 test_name 相关的单测还不支持。所以这个单测应该没法切换到 pir 模式下。所以这个单测跳过

2023-11-08 09:16 UTC, MarioLulab commented on test/legacy_test/test_kron_op.py
>          place = base.CPUPlace()
这里将普通变量变成是成员变量的原因是？这里应该不需要更改吧 🤔

2023-11-09 06:03 UTC, MarioLulab approved these changes
LGTM

2023-11-09 06:47 UTC, 0x45f approved these changes

2023-11-09 09:34 UTC, merged