【PIR API adaptor No.224】 Migrate paddle.tan
PaddlePaddle/Paddle pull request #58737
Opened 2023-11-06 15:55 UTC by xiaoyewww

### PR types

Others

### PR changes

APIs

### Description

PIR API 推全升级
将 paddle.Tensor.log2 迁移升级至 pir，并更新单测

https://github.com/PaddlePaddle/Paddle/issues/58067

单测覆盖率：3/3

2023-11-07 09:22 UTC, MarioLulab requested changes
nice work ~ 但还有某些单测有所遗漏，需要添加上去

2023-11-07 09:22 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
TestTan 继承自 TestActivation. TestActivation 有一个 test_check_output 需要继承重写并打开 check_pir 开关。麻烦添加一下吧~

2023-11-07 09:22 UTC, MarioLulab commented on test/legacy_test/test_activation_op.py
> +create_test_act_fp16_class(TestTan, check_pir=True)
类似于 `create_test_act_fp16_class`, 在该文件内还有一个 create_test_act_bf16_class(TestTan) 创建了 bf16 的单测，麻烦也打开一下吧~

2023-11-08 03:58 UTC, MarioLulab approved these changes
LGTM

2023-11-08 03:59 UTC, xiaoyewww commented on test/legacy_test/test_activation_op.py
> +create_test_act_fp16_class(TestTan, check_pir=True)
Done.

2023-11-08 03:59 UTC, xiaoyewww commented on test/legacy_test/test_activation_op.py
> +        self.check_grad(['X'], 'Out', check_pir=True)
Done.

2023-11-08 05:54 UTC, YuanRisheng approved these changes

2023-11-08 05:54 UTC, merged