【PIR API adaptor No.175】 Migrate paddle.vision.ops.read_file into pir
PaddlePaddle/Paddle pull request #58955
Opened 2023-11-13 09:48 UTC by enkilee

### PR types

Others
### PR changes

APIs
### Description

* https://github.com/PaddlePaddle/Paddle/issues/58067
No.175 paddle.vision.ops.read_file

PIR API 推全升级
将 `paddle.vision.ops.read_file` 迁移升级至 pir，并更新单测 单测覆盖率：1/1

2023-11-21 06:18 UTC, MarioLulab commented
read_file op 需要迁移到 PHI 体系下，内部已经记录。这个 pr 可以先搁置

2023-11-21 07:09 UTC, enkilee commented
收到

2023-12-18 13:39 UTC, MarioLulab commented
`read_file` op 已迁移至 phi 体系下。可以关注这个 pr: https://github.com/PaddlePaddle/Paddle/pull/60126 该 pr 添加 read_file op 的配置文件，以生成 read_file op 的 pir 组网 api，待这个 pr 合入后，当前 pr 就可以继续推进了~
还有我看到 read_file op 和 decode_jpeg op 的单测貌似是关联的，敏师傅可以顺便认领一下 51 号子任务（decode_jpeg 的 pir 适配），然后顺便在当前 pr 一起做掉吧 😄 🚀

2023-12-19 06:00 UTC, MarioLulab commented on python/paddle/vision/ops.py
可以统一起来，写成：
```python
if in_dynamic_or_pir_mode():
    return _C_ops.read_file(filename)
```

2023-12-19 06:30 UTC, enkilee commented on python/paddle/vision/ops.py
收到

2023-12-20 03:14 UTC, 0x45f commented on test/legacy_test/test_read_file.py
>      def read_file_decode_jpeg(self):
这个函数改成test_开头吧，不然单测不会执行，也就导致覆盖率的ci没有过~

2023-12-20 03:14 UTC, 0x45f commented on test/legacy_test/test_read_file.py
> +    def read_file_decode_jpeg(self):
同上

2023-12-20 04:51 UTC, enkilee commented on test/legacy_test/test_read_file.py
>      def read_file_decode_jpeg(self):
收到

2023-12-20 04:51 UTC, enkilee commented on test/legacy_test/test_read_file.py
> +    def read_file_decode_jpeg(self):
收到

2023-12-20 14:01 UTC, MarioLulab commented on python/paddle/vision/ops.py
> +        return _C_ops.read_file(filename)
从 ci 报错来看，这里应该还不能统一起来写，还是分开吧~
```suggestion
    if in_dygraph_mode():
        return _legacy_C_ops.read_file('filename', filename)
    elif in_pir_mode():
        return _C_ops.read_file(filename)
```

2023-12-21 00:58 UTC, enkilee commented on python/paddle/vision/ops.py
> +        return _C_ops.read_file(filename)
收到

2023-12-21 15:43 UTC, MarioLulab requested changes
关于 read_file api，还需要修改 read_file op 的 infermeta 函数及 read_file api 的 pir 分支，具体可以参考：https://github.com/PaddlePaddle/Paddle/pull/60242 .
https://github.com/PaddlePaddle/Paddle/pull/60242 应该没法合入因为覆盖率会不通过。敏师傅在当前 pr 做修改吧

2023-12-21 15:43 UTC, MarioLulab commented on test/legacy_test/test_read_file.py
> +class TestReadFileWithStatic(unittest.TestLoader):
```suggestion
class TestReadFileWithStatic(unittest.TestCase):
```

设置错了的话单测不会运行，导致 ci-coverage 不通过

2023-12-22 02:14 UTC, enkilee commented on test/legacy_test/test_read_file.py
> +class TestReadFileWithStatic(unittest.TestLoader):
收到

2023-12-22 07:14 UTC, MarioLulab commented
目前 pr https://github.com/PaddlePaddle/Paddle/pull/60242 还存在问题。此 pr 需等 https://github.com/PaddlePaddle/Paddle/pull/60242 合入后再合入~

2023-12-25 00:46 UTC, enkilee commented
> 当前 pr 可以按照 #60242 修改一下 read_file python api 和 nullary.cc。这个 pr 直接在 read_file op 的 infermeta 里设置 output tensor 的 dtype 为 uint8，这样能保持 pir 与旧 ir 的组网行为一致 我本地测过了没问题，辛苦修改一下吧~ @enkilee

收到，谢谢

2023-12-25 03:39 UTC, MarioLulab approved these changes
LGTM

2023-12-25 06:30 UTC, 0x45f approved these changes

2023-12-26 03:04 UTC, merged