[Dy2St] enable_to_static_guard 推全 40-45
PaddlePaddle/Paddle pull request #59694
Opened 2023-12-05 07:59 UTC by ooooo-create

### PR types

Others 
### PR changes

Others 
### Description

#59684

2023-12-06 02:08 UTC, DrRyanHuang approved these changes
LGTM🔍

2023-12-10 17:57 UTC, DrRyanHuang requested changes

2023-12-10 17:57 UTC, DrRyanHuang commented on test/dygraph_to_static/test_tensor_methods.py
> +
```suggestion
        with enable_to_static_guard(False):
            dygraph_res = self._run()
```

2023-12-10 18:00 UTC, DrRyanHuang commented on test/dygraph_to_static/test_tensor_methods.py
>      def test_ture_div(self):
```suggestion
    def test_true_div(self):
```

2023-12-12 12:26 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20220203/u1f498/u1f498_u1f43e.png" 
width="14px"/>

2023-12-13 01:04 UTC, merged