[Dy2St] enable_to_static_guard 推全 31-39
PaddlePaddle/Paddle pull request #59703
Opened 2023-12-05 08:55 UTC by ooooo-create

### PR types

Others 
### PR changes

Others 
### Description

乱改ing
#59684 
@DrRyanHuang @SigureMo

2023-12-06 01:51 UTC, DrRyanHuang approved these changes

2023-12-06 02:13 UTC, SigureMo commented on test/dygraph_to_static/test_save_inference_model.py
> +        with enable_to_static_guard(True):
True 的情况要不直接删掉？

2023-12-10 18:04 UTC, DrRyanHuang commented on test/dygraph_to_static/test_simnet_v2.py
> +
```suggestion
        with enable_to_static_guard(False):
            dygraph_loss = train(conf_dict)

```

2023-12-10 18:18 UTC, DrRyanHuang requested changes
这里还是传入一下 `to_static` ?

```
from paddle.jit.api import to_static
```

2023-12-10 18:18 UTC, DrRyanHuang commented on test/dygraph_to_static/test_se_resnet.py
> +    def train(self, train_reader):
这里还是传入一下 `to_static` ?

455行的 if 分支
```
                    if step_idx == STEP_NUM:
                        if to_static:
                            paddle.jit.save(
```
用的是这个 `to_static` 的函数来当条件
```
from paddle.jit.api import to_static
```

2023-12-10 18:23 UTC, SigureMo commented on test/dygraph_to_static/test_se_resnet.py
> +    def train(self, train_reader):
就不要 `import to_static` 了，使用动转静时候直接 `paddle.jit.to_static`，不然很容易混淆

2023-12-12 12:09 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20230127/u1f31f/u1f31f_u1f43e.png" 
width="14px"/>

2023-12-13 01:03 UTC, merged