[Dy2St][tests][23-29] `paddle.jit.enable_to_static`->`enable_to_static_guard`
PaddlePaddle/Paddle pull request #59729
Opened 2023-12-05 16:07 UTC by gouzil

### PR types

Others
### PR changes

Others
### Description

相关链接：

*  https://github.com/PaddlePaddle/Paddle/issues/59684

2023-12-07 02:08 UTC, DrRyanHuang approved these changes
nice work! 🍢🍢YYDS! LGTM

2023-12-10 18:24 UTC, DrRyanHuang requested changes

2023-12-10 18:24 UTC, DrRyanHuang commented on test/dygraph_to_static/test_resnet_amp.py
> +            return train(to_static)
```suggestion
        with enable_to_static_guard(to_static):
            return train()
```

2023-12-13 02:23 UTC, SigureMo commented on test/dygraph_to_static/test_pylayer.py
> +                )
双重保护？这样写就没必要用 `enable_to_static_guard` 了，直接删掉就行

2023-12-13 02:23 UTC, SigureMo commented on test/dygraph_to_static/test_resnet_amp.py
> +        dygraph_loss = train(to_static=False)
这里直接用 train，然后上面的 train 删掉了 `to_static`，这能跑？

2023-12-13 13:04 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20230418/u1f5ef-ufe0f/u1f5ef-ufe0f_u1f43e.png" width="14px"/>

2023-12-13 13:05 UTC, merged