Enable the case N != ldc in EigenBlasGemm.
PaddlePaddle/Paddle pull request #5976
Opened 2017-11-28 06:11 UTC by Xreki

2017-11-28 11:42 UTC, hedaoyuan requested changes

2017-11-28 11:42 UTC, hedaoyuan commented on paddle/math/Allocator.h
> +#ifdef PADDLE_WITH_CUDA
`WITH_GPU=OFF`下编译的时候会`include hl_cuda_stub.h`；下面这些代码中的宏应该是不需要加也能正确编译的？

2017-11-28 11:42 UTC, hedaoyuan commented on paddle/function/EigenGemm.cpp
> +    if (N != ldc) {
这样的fix方式，会给以后带来，性能风险（而且，不熟悉这段代码的人也不容易知道这里有性能问题）。可以，看一下Eigen有没有别的表达方式，可以直接支持stride参数的。

2017-11-28 11:53 UTC, Xreki commented on paddle/function/EigenGemm.cpp
> +    if (N != ldc) {
我查过了，Eigen的stride方式不适合这种情况。

2017-11-28 11:53 UTC, Xreki commented on paddle/math/Allocator.h
> +#ifdef PADDLE_WITH_CUDA
加这个是因为，`EigenGemm.cpp`中引入了`#include "paddle/math/MemoryHandle.h"`，从而会间接地引入`#include "hl_base.h"`，这个头文件中定义了`using real float`，会导致Eigen的编译问题。

2017-11-29 06:53 UTC, Xreki commented on paddle/function/EigenGemm.cpp
> +    if (N != ldc) {
Done.

2017-11-29 11:45 UTC, hedaoyuan commented on paddle/function/EigenGemm.cpp
> +      c.slice(offsetC, extentC).device(device) = a.contract(b, dims);
考虑两种情况：
1. `ldc_1 > N` and use the operation  `c.slice(offsetC, extentC).device(device) = a.contract(b, dims);` 
2. `ldc_2 == N` and use the operation `c.device(device) = a.contract(b, dims);`
1和2中的MNK是一样的，但是1中的ldc > N，2中的ldc == N，这两种情况下分别采用这两个不同的计算方式表现出来的性能（gflops）是一样的吗？

2017-11-30 12:18 UTC, Xreki commented on paddle/function/EigenGemm.cpp
> +      c.slice(offsetC, extentC).device(device) = a.contract(b, dims);
Done. 这样代码显得有点长（重复）了。后面来测下耗时。

2017-11-30 12:24 UTC, hedaoyuan approved these changes

2017-12-01 05:04 UTC, merged