[Cleanup][C-7]Replace Program.random_seed
PaddlePaddle/Paddle pull request #61519
Opened 2024-02-03 04:52 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Description

https://github.com/PaddlePaddle/Paddle/issues/61385

2024-02-03 14:27 UTC, gouzil approved these changes
LGTM

2024-02-03 14:31 UTC, gouzil approved these changes
`test_fused_attention_pass` 过不去就 RollBACK , 我们会在后续统一处理

2024-02-03 14:33 UTC, gouzil requested changes
啊，不小心手滑又点了 Approve

2024-02-03 14:33 UTC, gouzil commented on test/legacy_test/test_fused_attention_pass.py
> +        paddle.seed(1234)
这个文件

2024-02-04 00:23 UTC, co63oc commented on test/legacy_test/test_fused_attention_pass.py
> +        paddle.seed(1234)
已修改

2024-02-04 02:08 UTC, SigureMo commented on test/xpu/test_fused_attention_op_xpu.py
这个文件也恢复下吧，看起来也有问题

2024-02-04 02:53 UTC, co63oc commented on test/xpu/test_fused_attention_op_xpu.py
已修改

2024-02-04 14:25 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20230418/u1f5ef-ufe0f/u1f5ef-ufe0f_u1f43e.png" width="14px"/>

2024-02-04 14:49 UTC, gouzil approved these changes

2024-02-04 14:50 UTC, merged