feat(custom device): enable memory event and stat record for custom device.
PaddlePaddle/Paddle pull request #61668
Opened 2024-02-06 10:29 UTC by zhaohaixu

### PR types

New features
### PR changes

Others
### Description

feat(custom device): enable memory event and stat record for custom device.

2024-02-19 06:06 UTC, qili93 commented
感谢您的贡献，请帮忙补充下这个PR修改的原因和背景，请问此PR的分类是属于 1. 功能增强；2. 性能提升；3. BUG修复？ 

请描述此修改会在硬件适配中导致的具体问题，以及次修复之后得到的结果。如果方便请详细描述并提供相关的sample或代码说明。

再次感谢您的贡献 :)

2024-02-19 06:20 UTC, zhaohaixu commented
> 感谢您的贡献，请帮忙补充下这个PR修改的原因和背景，请问此PR的分类是属于 1. 功能增强；2. 性能提升；3. BUG修复？
> 
> 请描述此修改会在硬件适配中导致的具体问题，以及次修复之后得到的结果。如果方便请详细描述并提供相关的sample或代码说明。
> 
> 再次感谢您的贡献 :)

该PR可以使custom device记录reserved及allocated memory到Profiler中，进而在开启Profiler后在memory summary中输出详细信息，以及能够在VisualDL中看到device memory曲线。
![pf0wyuga](https://github.com/PaddlePaddle/Paddle/assets/49297029/5c7367f3-776f-4e24-91e0-35808306056e)

2024-02-23 07:29 UTC, qili93 commented
了解，建议添加一个flags控制一下这个的功能开关，避免对其他硬件的影响，添加flag的方法comment在代码review中，非常感谢！

2024-02-23 07:35 UTC, qili93 requested changes

2024-02-23 07:35 UTC, qili93 commented on paddle/fluid/memory/allocation/custom_allocator.cc
文件头部先声明一个flags 

```
PD_DEFINE_bool(  // NOLINT
    custom_device_mem_record,
    false,
    "Enable mem record event on custom device");
```

2024-02-23 07:35 UTC, qili93 commented on paddle/fluid/memory/allocation/custom_allocator.cc
> +                           platform::TracerMemEventType::ReservedFree);
这里 38-43行代码前后用 `if (FLAGS_custom_device_mem_record)` 包一下，默认不打开，如果需要记录的时候可以通过设置环境变量 export FLAGS_custom_device_mem_record=1 来启用这个功能。

下面其他的代码修改也都用 if 条件判断包一下

2024-11-08 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=61668) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=61668) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=61668) it.</sub>

2025-11-25 06:38 UTC, closed without merging