Implement the composition of some differential operators
PaddlePaddle/Paddle pull request #62067
Opened 2024-02-26 06:16 UTC by YibinLiu666

### PR types

### PR changes

### Description
部分算子的组合实现还没注册，后续会补上

2024-02-27 12:23 UTC, HydrogenSulfate requested changes
辛苦

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +    auto dx_res = y_value * elementwise_pow<T>(x, y_minus1_tensor) * out_grad;
TOOD：这里应该可以用pow代替elementwise_pow

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +
删除多余空行

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      auto x_grad_tmp = 0 * x;
0*x是否可以用full代替？scale op Tensor 的操作应该是会调用scale算子，会产生不必要的计算

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      auto x_grad_tmp = 0 * x;
同上

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(grad_out_grad_tmp, grad_out_grad);
同上

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(x_grad_tmp, x_grad);
同上

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                         const Tensor& grad_y_grad,
函数为多输入时，xxx_grad有可能是optional的

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(ddout_res, grad_out_grad);
这个是否可以用1-x_tmp？对于相等的输入应该也不太影响吧

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    auto y_tmp = cast<T>(less_equal<T>(x, y), grad_y_grad.dtype());
同上

2024-02-27 12:23 UTC, HydrogenSulfate commented on paddle/phi/api/yaml/backward.yaml
> +  #   func : GatherInferMeta
这里可能需要写个新的，或者找个类似的，具有相同输入、输出个数&&形状的算子，用该算子的infer_meta

2024-02-27 12:37 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +    auto dx_res = y_value * elementwise_pow<T>(x, y_minus1_tensor) * out_grad;
Done

2024-02-27 12:37 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(grad_out_grad_tmp, grad_out_grad);
Done

2024-02-27 12:38 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(x_grad_tmp, x_grad);
Done

2024-02-27 12:38 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                         const Tensor& grad_y_grad,
Done

2024-02-27 12:39 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(ddout_res, grad_out_grad);
这里因为grad_x_grad和grad_y_grad都是optional的，所以我现在是分情况计算的了

2024-02-28 02:44 UTC, YibinLiu666 commented
结果正确性的测试代码为
```python
import paddle
import numpy as np
import shutil
import os

def test_abs_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.tanh(paddle.abs(x))
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("abs_grad")
    y_composite_res = paddle.tanh(paddle.abs(x))
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

def test_sin_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.sin(x)
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("sin_grad")
    y_composite_res = paddle.sin(x)
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

def test_cos_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.cos(x)
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("cos_grad")
    y_composite_res = paddle.cos(x)
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

def test_pow_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.pow(x, 2.7)
    dx_fused_res = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    y_composite_res = paddle.pow(x, 2.7)
    dx_composite_res = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    np.testing.assert_allclose(dx_fused_res.numpy(), dx_composite_res.numpy(), 1e-6, 1e-6)

def test_pow_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.pow(x, 2.7)
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("pow_grad")
    y_composite_res = paddle.pow(x, 2.7)
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

def test_minimum_double_grad():
    x = paddle.to_tensor(np.load("./tmp/x.npy"), dtype="float32", stop_gradient=False)
    y = paddle.to_tensor(np.load("./tmp/y.npy"), dtype="float32", stop_gradient=False)
    ddx = np.load("./tmp/ddx_minimum.npy")
    ddy = np.load("./tmp/ddy_minimum.npy")
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("minimum_grad")
    z_composite_res = paddle.tanh(paddle.minimum(x, y))
    g = paddle.grad(z_composite_res, [x, y], create_graph=True, retain_graph=False)
    ddx_composite_res, ddy_composite_res = paddle.grad(g, [x,y], create_graph=False, retain_graph=False)
    np.testing.assert_allclose(ddx, ddx_composite_res.numpy(), 1e-6, 1e-6)
    np.testing.assert_allclose(ddy, ddy_composite_res.numpy(), 1e-6, 1e-6)

def test_maximum_double_grad():
    x = paddle.to_tensor(np.load("./tmp/x.npy"), dtype="float32", stop_gradient=False)
    y = paddle.to_tensor(np.load("./tmp/y.npy"), dtype="float32", stop_gradient=False)
    ddx = np.load("./tmp/ddx_maximum.npy")
    ddy = np.load("./tmp/ddy_maximum.npy")
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("maximum_grad")
    z_composite_res = paddle.tanh(paddle.maximum(x, y))
    g = paddle.grad(z_composite_res, [x, y], create_graph=True, retain_graph=False)
    ddx_composite_res, ddy_composite_res = paddle.grad(g, [x,y], create_graph=False, retain_graph=False)
    np.testing.assert_allclose(ddx, ddx_composite_res.numpy(), 1e-6, 1e-6)
    np.testing.assert_allclose(ddy, ddy_composite_res.numpy(), 1e-6, 1e-6)
    if os.path.exists("./tmp"):
        shutil.rmtree("./tmp")
```

2024-02-28 05:54 UTC, HydrogenSulfate requested changes

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +  // cos grad grad : ddout = - sinx * ddx, dx = -dy * cosx * ddx
`- sinx` -> `-sinx`

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    }
1. grad_out应该是一定存在的（其它算子也是如此），至少会是全1矩阵，应该不用optional，因此下面的
2. dx计算时可复用前向输出`y`替换`cos<T>(x)`

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
同上，一般grad_out不需要optional

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    }
同上，删除else分支，并复用前向输出y

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +  auto y_value = y.to<float>();
这里应该不用转成float,直接用y即可，有`pow(const Tensor&, const Scalar&)`这个重载版本
![image](https://github.com/PaddlePaddle/Paddle/assets/23737287/6c1e215c-aebf-4a1b-9bee-99db535ed6d9)

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +}
同上，直接用y即可

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    auto x_grad_tmp = y_value * (y_value - 1.0) * x.pow(y_value - 2.0) *
用1和2代替1.0和2.0吧

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                         const Tensor& y,
添加out参数，复用out.dims

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(ddout_tmp, grad_out_grad);
参考以下代码，改为4个分支，否则会多调用一些基础算子导致性能变差
![image](https://github.com/PaddlePaddle/Paddle/assets/23737287/353c1628-4966-4557-9700-8a092eddcf9c)

2024-02-28 05:54 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +}
问题同minimum_double_grad

2024-02-28 06:31 UTC, HydrogenSulfate requested changes

2024-02-28 06:31 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      auto y_tmp = cast<T>(greater_equal<T>(x, y), grad_y_grad.get().dtype());
1. x_tmp和y_tmp建议改为x_mask和y_mask，符合变量语义，少用tmp类的名字
2. 根据MinimumGradKernel，x_mask为x < y，y_mask 为 x>=y，因此可以改成4个分支，在 grad_x_grad && grad_y_grad 分支里，y_mask=1-x_mask即可

2024-02-28 06:31 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      ddout_tmp = ddout_tmp + grad_y_grad.get() * y_tmp;
_tmp和变量复用问题同minimum_double_grad

2024-02-28 11:44 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +  // cos grad grad : ddout = - sinx * ddx, dx = -dy * cosx * ddx
Done

2024-02-28 11:45 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    }
大算子是optional的，此外，大算子没有将y作为二阶微分的输入，这里与大算子对齐

2024-02-28 11:45 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
同上

2024-02-28 11:45 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    }
同上

2024-02-28 11:45 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +  auto y_value = y.to<float>();
Done

2024-02-28 11:46 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +}
目前paddle没有重载scalar - int的加法等类似的运算，因此还是需要使用y_value

2024-02-28 11:46 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    auto x_grad_tmp = y_value * (y_value - 1.0) * x.pow(y_value - 2.0) *
Done

2024-02-28 11:46 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    set_output<T>(ddout_tmp, grad_out_grad);
Done

2024-02-28 11:46 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +}
Done

2024-02-28 11:47 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      auto y_tmp = cast<T>(greater_equal<T>(x, y), grad_y_grad.get().dtype());
Done

2024-02-28 11:47 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +      ddout_tmp = ddout_tmp + grad_y_grad.get() * y_tmp;
Done

2024-04-16 14:24 UTC, closed without merging