【complex op No.33】abs_coo/abs_csr(sparse)
PaddlePaddle/Paddle pull request #62237
Opened 2024-02-29 09:18 UTC by bapijun

### PR types
New features

### PR changes
OPs | Apis

### Description
add complex support for abs_coo/abs_csr in sparse

https://github.com/PaddlePaddle/Paddle/issues/61975

2024-02-29 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=62237) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=62237) before we can accept your contribution.<br/><hr/>**bapijun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=62237) it.</sub>

2024-03-01 03:14 UTC, luotao1 commented
@zbt78 可以进行 review 了

2024-03-01 10:10 UTC, zbt78 commented
测试的时候建议先不添加新的测试文件，在原测试文件test_sparse_unary_op.py里进行修改。

2024-03-13 03:38 UTC, luotao1 commented
> 测试的时候建议先不添加新的测试文件，在原测试文件test_sparse_unary_op.py里进行修改。

@bapijun 请根据review意见进行修改

2024-03-13 08:13 UTC, bapijun commented
> > 测试的时候建议先不添加新的测试文件，在原测试文件test_sparse_unary_op.py里进行修改。
> 
> @bapijun 请根据review意见进行修改
已经提交了更改

2024-03-14 03:24 UTC, luotao1 commented
@zbt78 可以再review一下，目前Coverage覆盖率没过

2024-03-14 09:08 UTC, zbt78 commented on test/legacy_test/test_sparse_unary_op.py
> +        for device in devices:
这里device的作用是什么呢，看起来没起作用

2024-03-14 16:09 UTC, bapijun commented on test/legacy_test/test_sparse_unary_op.py
> +        for device in devices:
这个代码少了一句,忘记把放到不同设备的哪一句写进来

2024-03-15 01:37 UTC, luotao1 commented on test/legacy_test/test_sparse_unary_op.py
> +        for device in devices:
现在覆盖率就过了👍

2024-03-15 02:01 UTC, zbt78 commented
LGTM

2024-03-15 02:52 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
> +PD_REGISTER_KERNEL(abs_coo_grad,
注册的形式是一样的，这里是不是也写一个带复数注册的宏会更好一点，也更方便后面稀疏方法的注册，

2024-03-15 02:52 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +void AbsCooKernel(const Context& dev_ctx,
这种的是不是也可以写一个宏，毕竟实现方式也是一样的

2024-03-15 02:52 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
这里为什么会需要重新设置一下out的dtype

2024-03-15 06:22 UTC, bapijun commented on paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
> +PD_REGISTER_KERNEL(abs_coo_grad,
可以的，事实上我在后面几个复数的更改里面就用了额外的形式，我等会把代码迁移过来再提交

2024-03-15 06:23 UTC, bapijun commented on paddle/phi/kernels/sparse/gpu/unary_grad_kernel.cu
> +PD_REGISTER_KERNEL(abs_coo_grad,
> 注册的形式是一样的，这里是不是也写一个带复数注册的宏会更好一点，也更方便后面稀疏方法的注册，

事实上我在后面的复数修改就重新写了新的宏，我晚上有时间就去把那边pr的代码移动过来

2024-03-15 06:26 UTC, bapijun commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
> 这里为什么会需要重新设置一下out的dtype
这是因为abs的结果是会是浮点数，比如对于value是complex64的输入，他的abs结果会是一个float32所以这里对于values需要重设他的类型

2024-03-15 06:39 UTC, luotao1 commented
@bapijun 可以考虑参加下 [【HACKATHON 预备营】飞桨启航计划集训营（第二期）](https://github.com/PaddlePaddle/Paddle/issues/62347) 的复数团，简历截止3月18日

2024-03-18 03:03 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
那这里应该是修改一下sparse_ops.yaml 文件里面infermeta的函数，可以先参考一下ops.yaml里面abs的infermeta函数是否可用，如果不行就需要新增一个，kernel 内部非必要不会去增加设置meta信息的逻辑，不利于整体op的维护。

2024-03-18 06:36 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
那这里应该是修改一下sparse_ops.yaml 文件里面infermeta的函数，可以先参考一下ops.yaml里面abs的infermeta函数是否可用，如果不行就需要新增一个，kernel 内部非必要不会去增加设置meta信息的逻辑，不利于整体op的维护。

2024-03-18 13:55 UTC, bapijun commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
> 那这里应该是修改一下sparse_ops.yaml 文件里面infermeta的函数，可以先参考一下ops.yaml里面abs的infermeta函数是否可用，如果不行就需要新增一个，kernel 内部非必要不会去增加设置meta信息的逻辑，不利于整体op的维护。

我回去试了一下,只改infermeta函数是不行的,因为这个Kernel里面有一个EmptyLikeCXXKernel 函数,函数里面会试着把x的属性复制到out里面去,导致导致在infermeta重设过得dtype变回来,我的想法是写一个新的EmptyLikeCXXKernel 处理这个逻辑问题,我看了一下在op.yaml里面除了abs之外,还有另外三个算子也是会出现需要复数的输入,转化为浮点数的结果

2024-03-19 03:27 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
当初sparse 设计的时候没有考虑像复数这种存在C-R 或是R-C导致输入输出meta 信息不一致的场景。所以为了规范sparse_kernel设计，这里需要修改相应逻辑，EmptyLikeCXXKernel实际上承担了两部分的工作，infermeta(坐标、dim、dtype等等)、内存分配。所以现在需要把这个两个功能分开，将infermeta的功能放到infermeta函数中，将分配内存的功能放到kernel内部，这里先修改abs_kernel，主要有两个修改点：
1. 新增一个sparse的 unchangedinfermeta函数去设置坐标、dim、dtype这种
2. abs kernel 内部的EmptyLikeCXXKernel  替换成分配内存的逻辑

2024-03-20 07:21 UTC, bapijun commented on paddle/phi/kernels/sparse/impl/unary_kernel_impl.h
> +    out->set_type(out_values->dtype());
> 1. unchangedinfermeta

好的我回去试试

2024-03-22 06:06 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/empty_kernel.cc
> +void EmptyLikeCooRealComplexKernel(const Context& dev_ctx,
不是这么改，不应该额外增加这个kernel了，这么做其实和之前的做法没有本质的区别，还是将输入输出的meta信息计算和数据计算耦合在一起了，这样是不符合现有的框架设计的，而且目前非必要也不推荐去新增kernel，后续维护容易出现坑。
正确的方式是新增SparseUnchangedInferMeta，作为通用的sparse的infermeta函数，做设置坐标`*(out->mutable_indices()) = x.indices();` ，设置dim `out_values->Resize(x_values.dims());`，还有设置dtype 的工作，只不过针对C-R 这种场景，需要新增一个SparseC2RInferMeta，可以在这个SparseC2RInferMeta里面调用SparseUnchangedInferMeta， 然后设置输出的dtype 是实数。
而`dev_ctx.template Alloc<T>(out_values);` 分配内存的事情就放到kernel内部，所以sparse_abs的kernel 应该是这样的。
```
#define DEFINE_SPARSE_UNARY_KERNEL(prefix)                                 \
  template <typename T, typename Context>                                  \
  void prefix##CooKernel(const Context& dev_ctx,                           \
                         const SparseCooTensor& x,                         \
                         SparseCooTensor* out) {                           \
    dev_ctx.template Alloc<T>(out);                       \
    phi::prefix##Kernel<T, Context>(                                       \
        dev_ctx, x.non_zero_elements(), out->mutable_non_zero_elements()); \
    out->SetIndicesDict(x.GetIndicesDict());                               \
  }                                                                        \
```
这样才更通用，扩展性更强。

2024-03-28 02:57 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/impl/unary_grad_kernel_impl.h
> +  EmptyLikeCooKernel<T, Context>(dev_ctx, x_or_out, dx);
反向的也可以拆分吧

2024-03-28 02:57 UTC, GGBond8488 commented on test/legacy_test/test_sparse_unary_op.py
> +                paddle.set_device(device)
这种全局设置要慎用，很容易在并行测试的时候影响其他的单测，可以https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#tensor 主动用tensor.to 指定输入tensor的设备

2024-03-29 12:54 UTC, bapijun commented on paddle/phi/kernels/sparse/impl/unary_grad_kernel_impl.h
> +  EmptyLikeCooKernel<T, Context>(dev_ctx, x_or_out, dx);
关于这个我回去看了一下,非稀疏的abs,看起来结果下,abs的梯度也就是复数形式的,应该是不需要c to r的写法

2024-04-02 08:14 UTC, bapijun commented
@GGBond8488  
麻烦老师再看一下

2024-04-03 02:40 UTC, GGBond8488 approved these changes
LGTM

2024-04-03 02:42 UTC, luotao1 reviewed
请对应修改中文文档中的数据类型

2024-04-03 06:33 UTC, GGBond8488 requested changes

2024-04-03 06:33 UTC, GGBond8488 commented on paddle/phi/kernels/sparse/gpu/sparse_utils_kernel.cu
>  PD_REGISTER_KERNEL(coo_to_csr,
这些kernel 对应的grad kernel 也注册上复数吧

2024-04-07 09:29 UTC, bapijun commented on paddle/phi/kernels/sparse/gpu/sparse_utils_kernel.cu
>  PD_REGISTER_KERNEL(coo_to_csr,
> 这些kernel 对应的grad kernel 也注册上复数吧

这一次提交里面,在对应的sparse_backward.yaml下面能找到的后向我改掉了,但是对应的to_dense和value的梯度,涉及到
mask_kernel下面的两个kernel
另外还有之前提到的,稀疏格式在backward的时候涉及到的meta丢失的问题,在修改to_dense的梯度的时候也出现了,这一次也改掉了

2024-04-07 09:32 UTC, bapijun commented
> 请对应修改中文文档中的数据类型

指的是这个么?
https://github.com/PaddlePaddle/docs

2024-04-07 10:10 UTC, luotao1 commented
> 指的是这个么?
https://github.com/PaddlePaddle/docs

对的

2024-05-21 02:34 UTC, zhiminzhang0830 commented
LGTM

2024-05-21 03:03 UTC, zhiminzhang0830 approved these changes

2024-05-21 03:13 UTC, wanghuancoder approved these changes
LGTM

2024-05-21 03:15 UTC, phlrain approved these changes

2024-05-21 03:17 UTC, merged

2024-05-21 03:22 UTC, luotao1 commented
hi, @bapijun 
- 非常感谢你对飞桨的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~

2024-05-21 03:29 UTC, bapijun commented
https://github.com/PaddlePaddle/docs/pull/6645
@luotao1 
对应的文档 or也麻烦老师看看