Implement the composition of pow_double_grad
PaddlePaddle/Paddle pull request #62338
Opened 2024-03-03 12:48 UTC by YibinLiu666

### PR types
Others

### PR changes
Others

### Description
实现pow的二阶微分组合，测试代码为：
```python
import paddle
import numpy as np

def test_pow_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.pow(x, 2.7)
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("pow_grad")
    y_composite_res = paddle.pow(x, 2.7)
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

```
@HydrogenSulfate

2024-03-04 11:25 UTC, HydrogenSulfate requested changes
LGTM

麻烦 @cyber-pioneer 卓哥也review一下

2024-03-25 09:18 UTC, HydrogenSulfate approved these changes
LGTM

2024-03-26 03:45 UTC, cyber-pioneer commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +  auto y_value = y.to<float>();
确认一下pow对int类型是否有特殊优化，如果有，建议对int做特判

2024-03-26 04:36 UTC, cyber-pioneer approved these changes

2024-03-26 06:06 UTC, heavyrain-lzy approved these changes
LGTM for yaml

2024-03-26 06:25 UTC, merged