Implement the composition of pow_grad
PaddlePaddle/Paddle pull request #62336
Opened 2024-03-03 11:57 UTC by YibinLiu666

### PR types
Others

### PR changes
Others 

### Description
实现pow的一阶微分组合，测试代码为：
```python
import paddle
import numpy as np

def test_pow_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.pow(x, 2.7)
    dx_fused_res = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    y_composite_res = paddle.pow(x, 2.7)
    dx_composite_res = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    np.testing.assert_allclose(dx_fused_res.numpy(), dx_composite_res.numpy(), 1e-6, 1e-6)
```

2024-03-04 11:17 UTC, HydrogenSulfate approved these changes
LGTM

@cyber-pioneer 麻烦卓哥也review一下

2024-03-05 11:20 UTC, Charles-hit reviewed
因为这个拆解规则是动静统一的，一阶拆解的话加一个静态图测试吧

2024-03-05 12:26 UTC, YibinLiu666 commented
> 因为这个拆解规则是动静统一的，一阶拆解的话加一个静态图测试吧

已添加

2024-03-21 02:49 UTC, HydrogenSulfate requested changes

2024-03-21 02:49 UTC, HydrogenSulfate commented on test/prim/prim/vjp/eager/test_comp_eager_pow_grad.py
> +sys.path.append('../../../../legacy_test/')
这行删除

2024-03-21 06:23 UTC, Charles-hit approved these changes

2024-03-21 07:39 UTC, heavyrain-lzy approved these changes
LGTM for YAML

2024-03-21 07:56 UTC, merged