Implement the composition of minimum_double_grad
PaddlePaddle/Paddle pull request #62342
Opened 2024-03-03 13:44 UTC by YibinLiu666

### PR types
Others

### PR changes
Others

### Description
实现pow的一阶微分组合，测试代码为：
```python
import paddle
import numpy as np
import torch
def test_minimum_double_grad():
    shape = [1024, 512]
    x_np = np.random.randn(*shape)
    y_np = np.random.randn(*shape)
    x = paddle.to_tensor(x_np, dtype="float32")
    x.stop_gradient=False
    y = paddle.to_tensor(y_np, dtype="float32")
    y.stop_gradient=False
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("minimum_grad")
    z_composite_res = paddle.tanh(paddle.minimum(x, y))
    g = paddle.grad(z_composite_res, [x, y], create_graph=True, retain_graph=False)
    ddx_composite_res, ddy_composite_res = paddle.grad(g, [x,y], create_graph=False, retain_graph=False)
    
    x_torch = torch.tensor(x_np, dtype=torch.float32, requires_grad=True)
    y_torch = torch.tensor(y_np, dtype=torch.float32, requires_grad=True)
    z_torch = torch.tanh(torch.minimum(x_torch, y_torch))
    dx_torch, dy_torch = torch.autograd.grad(z_torch.sum(), [x_torch, y_torch], create_graph=True, retain_graph=True)
    ddx, ddy = torch.autograd.grad([dx_torch.sum(), dy_torch.sum()], [x_torch, y_torch], create_graph=False, retain_graph=False)
    np.testing.assert_allclose(ddx, ddx_composite_res.numpy(), 1e-6, 1e-6)
    np.testing.assert_allclose(ddy, ddy_composite_res.numpy(), 1e-6, 1e-6)
```

2024-03-04 11:50 UTC, HydrogenSulfate approved these changes
LGTM

麻烦 @cyber-pioneer 卓哥也review一下

2024-03-15 02:48 UTC, HydrogenSulfate requested changes
加一下二阶组合单测

2024-03-15 02:48 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +    }
这里的else分支可以删除，不会出现grad_x_grad和grad_y_grad同时不存在的情况

2024-03-21 06:24 UTC, Charles-hit approved these changes

2024-03-21 07:40 UTC, heavyrain-lzy approved these changes
LGTM for YAML

2024-03-21 07:56 UTC, merged