Implement the composition of sin_double_grad
PaddlePaddle/Paddle pull request #62341
Opened 2024-03-03 13:26 UTC by YibinLiu666

### PR types
Others

### PR changes
Others

### Description
实现sin的二阶微分组合，测试代码为：
```python
import paddle
import numpy as np

def test_sin_double_grad():
    paddle.framework.core.set_prim_eager_enabled(False)
    shape = [1024, 512]
    x = paddle.to_tensor(np.random.randn(*shape), dtype="float32")
    x.stop_gradient=False
    y_fused_res = paddle.sin(x)
    dx = paddle.grad(y_fused_res, x, create_graph=True, retain_graph=False)[0]
    ddx_fused_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    paddle.framework.core.set_prim_eager_enabled(True)
    paddle.framework.core._set_prim_backward_blacklist("sin_grad")
    y_composite_res = paddle.sin(x)
    dx = paddle.grad(y_composite_res, x, create_graph=True, retain_graph=False)[0]
    ddx_composite_res = paddle.grad(dx, x, create_graph=False, retain_graph=False)[0]
    np.testing.assert_allclose(ddx_fused_res.numpy(), ddx_composite_res.numpy(), 1e-6, 1e-6)

```

2024-03-04 11:38 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
同cos_double_grad，这里的grad_out应该不需要是optional，而是一定会存在

2024-03-04 13:35 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
同cos_double_grad，大算子实现是使用的optional

2024-03-04 14:12 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
> 同cos_double_grad，大算子实现是使用的optional

可以尝试同步修改一下大算子的实现、声明以及yaml配置，这里确认了下是不需要optional的

2024-03-12 05:30 UTC, HydrogenSulfate requested changes

2024-03-12 05:30 UTC, HydrogenSulfate commented on test/prim/prim/vjp/eager/test_comp_eager_sin_double_grad.py
> +        core.set_prim_eager_enabled(False)
1. 测试二阶组合
2. 黑名单应该加入`sin_grad`

2024-03-12 05:33 UTC, HydrogenSulfate commented on test/prim/prim/vjp/eager/test_comp_eager_sin_double_grad.py
> +sys.path.append('../../../../legacy_test/')
这行应该可以删除掉，因为其他文件都不需要这个

2024-03-12 12:53 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_double_backward_api.h
> +                     const paddle::optional<Tensor>& grad_out,
Done

2024-03-12 12:53 UTC, YibinLiu666 commented on test/prim/prim/vjp/eager/test_comp_eager_sin_double_grad.py
> +        core.set_prim_eager_enabled(False)
Done

2024-03-12 12:54 UTC, YibinLiu666 commented on test/prim/prim/vjp/eager/test_comp_eager_sin_double_grad.py
> +sys.path.append('../../../../legacy_test/')
Done

2024-03-13 09:38 UTC, Charles-hit approved these changes

2024-03-13 11:12 UTC, heavyrain-lzy approved these changes
LGTM

2024-03-13 11:24 UTC, merged