[HACKATHON 6th][CMake Optimization] Fix clang compatibility
PaddlePaddle/Paddle pull request #62565
Opened 2024-03-08 10:55 UTC by silverling

### PR types

Bug fixes
### PR changes

Others 
### Description

由于 Paddle 开启了 `-Wall -Werror` 编译选项，将所有的 Warning 视为错误，而 Clang 的编译检查较为严格，相比 GCC 会有更多的 Warning 需要解决。

本次 PR 包含一系列 commits 来修复用 Clang/LLVM 来编译 Paddle 的一些问题，使得目前可以通过 Clang 完整编译 Paddle。

本次 PR 修复的问题包含多种，同一类的问题都在相同的 commit 中，每一种问题的具体描述如下：

1. **变量类型不一致**：[fix variable type inconsistent](https://github.com/PaddlePaddle/Paddle/commit/15a5834fd41383553e4d659786a9ae5bb8466fd2)
    
    编译器可以隐式转化绝大部分基本类型的变量，其中一些可能产生错误的转化，则会提示 Warning。如将 `unsigned int` 转为 `signed int` ，`int` 转为 `float` 等。

2. **使用未初始化的变量**：[fix uninitialized but used variable](https://github.com/PaddlePaddle/Paddle/commit/3d07f95e31119d8f15415fec63770e6b3b8b7e79)
    
    有时候，变量的初始化是通过传递指针或地址交给一个函数来赋值，然而这种情况编译器不能正常判断，所以报错。不过，为了良好的编程习惯，还是建议将变量手动初始化。

3. **子类声明无效的默认构造函数**：[add flags "-Wno-defaulted-function-deleted" to avoid warning in GLOO](https://github.com/PaddlePaddle/Paddle/commit/e5b09eca21f210d13e808b81f4fd104ccae80570)
    
    例如在第三方依赖 GLOO 中的 https://github.com/ziyoujiyi/gloo/blob/8b6b61dfa0dca02b226a01262bfcf0484382048f/gloo/common/error.h#L25 
```
// A base class for all gloo runtime errors
struct Exception : public std::runtime_error {
  Exception() = default;
  explicit Exception(const std::string& msg) : std::runtime_error(msg) {}
};
```
  由于父类 `std::runtime_error` 没有默认的构造函数，所以 `Exception() = default;` 实际上是无效的，所以编译器会报错。由于 GLOO 是第三方依赖，无法直接修改其实现，所以在 `flags.cmake` 添加了 `-Wno-defaulted-function-deleted`

4. **Copy elision 编译优化**：[fix copy elision](https://github.com/PaddlePaddle/Paddle/commit/db64b5974f989586bfac01010d33baedf0a3fe7c)

  现代编译器会默认启用 RVO 和 NRVO，在 C++17 标准之后，RVO 被要求必须实现，NRVO 则鼓励实现。现代编译器均会实现这两种优化。具体内容可搜索关键字了解，篇幅有限，简而言之，如果一个函数中实例化了一个对象，然后将其作为返回值，编译器会在调用该函数的地方直接实例化对象，而不是在函数中实例化，避免对象的拷贝。而 `std::move` 会阻止这种行为，可能造成额外的程序开销。

5. **struct 和 class 不匹配**：[fix struct and class tag mismatch](https://github.com/PaddlePaddle/Paddle/commit/9ee47527f4ec10844f4bffe432c38c280b678c0f)
  
  我们知道，`struct` 和 `class` 唯一的区别是默认的访问权限不同，`struct` 默认为 `public`，`class` 为 `private`。在几乎所有情况下，我们可以混用这两个名字。而 Clang 编译器的 Warning 为：“class was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI”，意思是，由于 C++ 的 mangling 机制，MSVC 可能会区别 `struct` 和 `class`，导致链接时可能出现异常。为了统一起见，均修改为 `class`。

6. **缺失拷贝构造函数或拷贝赋值构造函数**：[add copy or copy assignment constructor (three/five/zero rule)](https://github.com/PaddlePaddle/Paddle/commit/e4ec35be1079cee816c23c4f1dba875e2b4a7058)
  
  C++ 中有个约定叫 [three/five/zero rule](https://en.cppreference.com/w/cpp/language/rule_of_three)，意思是：当定义一个 Class 时，要么不明确声明任何构造函数，由编译器默认生成；要么声明普通构造函数、拷贝构造函数和拷贝赋值构造函数这三个；要么再加上移动构造函数和移动赋值构造函数。如果一个类定义了拷贝构造函数，则也应该定义普通构造函数和拷贝赋值构造函数，避免在代码中尝试不一致的行为。

7. **重载右加运算符**：[fix operator+ infinite recursion](https://github.com/PaddlePaddle/Paddle/commit/6c5375205f90e399d242b1934088249d23ded282)

8. **删除无用的 lambda 捕获**：[remove unused lambda captures](https://github.com/PaddlePaddle/Paddle/commit/a94437a4985affc59899b264195b9d870d64d4b5)

9. **运算符短路判断**：[fix overlapping comparisons](https://github.com/PaddlePaddle/Paddle/commit/7fa668c6d909430b109c24fcefb8ee3cf29a08d8)

10. **子类 final 关键字**： [add final keyword for final subclass](https://github.com/PaddlePaddle/Paddle/commit/35cd66db866c3b79faa65d6dfba9b7568d82825a)
  
  如果一个子类中一些成员函数标记为 `final`，则该子类也应标记为 `final`

11. **注释函数中未使用的局部变量**：[comment out unused local variable in functions](https://github.com/PaddlePaddle/Paddle/commit/b86ad32ea15fc2dcd8e67fc0581515e0fe74530e)
  
  在 Paddle 的许多函数中存在一些声明、赋值，但并未使用的局部变量，可能是历史遗留原因。本次 PR 先将其全部注释。

12. **不兼容的 C ABI 暴露**：[fix C-compatible declaration for C linkage](https://github.com/PaddlePaddle/Paddle/commit/9ef4946f5b717108400208fa57f0e6acebb11752)

13. **子类 override 关键字**：[add override keyword](https://github.com/PaddlePaddle/Paddle/commit/0ca877299f211d6c5aef3d20d15d380b7024bafc)

14. **添加宏判断**：[add macro check for custom device](https://github.com/PaddlePaddle/Paddle/commit/d0bd6cd7d55f6834dee045d3f16d995f4fbb66bd)

15. **调整 rocksdb 编译选项**：[fix rocksdb compatibility with clang](https://github.com/PaddlePaddle/Paddle/commit/f6984dff8dabdd8de88bde853e77048d4aaf27bc)

  调整了编译选项，避免 Clang 将不能识别的选项报错

16. **使用 C++17 参数展开语法**：[use C++17 pack arguments expansion](https://github.com/PaddlePaddle/Paddle/commit/732178f409ec5d2329cf04b7254672cf24b5c509)

17. **添加额外的编译选项来抑制错误**：[suppress several warning](https://github.com/PaddlePaddle/Paddle/commit/dc0c3315b0a8e9bfc352d755423119663a35635e)

  Paddle 以及第三方依赖中存在大量以下问题，包括：
  - 定义但未使用的成员私有变量
  - 定义但未使用的常量
  - 重载虚函数时没有添加 override 关键字（大部分在 `paddle/fluid/distributed` 模块下）
  - 重载虚函数时函数签名不一致（同上）

  这些问题部分来自于历史遗留，部分源于模块还在实现，其最终的修改还需对应模块的研发人员来确定，目前先通过在 `flags.cmake` 中添加警告抑制选项来完成编译。

后续的开发，可以通过移除某类警告的抑制选项，然后由相关人员根据编译器报错进行排查处理。

**本次 PR 的本地测试环境有限，不能覆盖所有编译场景与配置，还需后续继续完善，以及对应的 Clang 编译 CI 支持。**

附加信息：
- 测试环境：Debian 12
- Clang 版本：Debian clang version 14.0.6
- CUDA 版本：12.0
- Python 版本：3.8

备注：
- 在编译 CUDA 程序时，nvcc 会调用系统默认编译器来编译其中的 C++ Host 程序，可能会绕过 Clang，可以添加编译选项 `--compiler-bindir=<path/to/clang>` 来指定。本次 PR 没有指定，也即依旧使用 GCC 编译 Host 程序。后续可以改进。
- 本次 PR 的 cmake 构建命令如下：
```
CC="clang" CXX="clang++" cmake <paddle-source-dir> -B build -G "Ninja" \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_GPU=ON \
  -DWITH_CUDNN_DSO=OFF \
  -DWITH_SHARED_PHI=ON \
  -DWITH_TENSORRT=ON \
  -DTENSORRT_ROOT="$TENSORRT_ROOT" \
  -DWITH_ROCM=OFF \
  -DWITH_RCCL=OFF \
  -DWITH_CINN=OFF \
  -DWITH_DISTRIBUTE=ON \
  -DWITH_MKL=ON \
  -DWITH_AVX=ON \
  -DCUDA_ARCH_NAME=Manual \
  -DNEW_RELEASE_PYPI=OFF \
  -DNEW_RELEASE_ALL=OFF \
  -DNEW_RELEASE_JIT=OFF \
  -DWITH_PYTHON=ON \
  -DCUDNN_ROOT=/usr/ \
  -DWITH_TESTING=OFF \
  -DWITH_COVERAGE=OFF \
  -DWITH_INCREMENTAL_COVERAGE=OFF \
  -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DWITH_INFERENCE_API_TEST=OFF \
  -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo \
  -DPY_VERSION=3.8 \
  -DCMAKE_INSTALL_PREFIX=/paddle/build \
  -DWITH_PSCORE=ON \
  -DWITH_PSLIB=OFF \
  -DWITH_GLOO=ON \
  -DLITE_GIT_TAG=release/v2.10 \
  -DWITH_XPU=OFF \
  -DWITH_IPU=OFF \
  -DXPU_SDK_ROOT= \
  -DWITH_LITE=OFF \
  -DWITH_XPU_BKCL=OFF \
  -DWITH_ARM=OFF \
  -DWITH_STRIP=ON \
  -DON_INFER=OFF \
  -DWITH_HETERPS=OFF \
  -DWITH_GPU_GRAPH=OFF \
  -DCUDA_ARCH_BIN="70" \
  -DWITH_RECORD_BUILDTIME=OFF \
  -DWITH_UNITY_BUILD=OFF \
  -DWITH_ONNXRUNTIME=OFF \
  -DWITH_CUDNN_FRONTEND=OFF \
  -DNCCL_ROOT="/root/.conda/envs/cuda120"
```
编译命令如下：
```
ninja
```

2024-03-08 11:55 UTC, risemeup1 requested changes

2024-03-08 11:55 UTC, risemeup1 commented on paddle/phi/kernels/cpu/send_uv_kernel.cc
>    ctx.template Alloc<T>(out);
这里的memeset_size是因为后边没用到所以删了吗？还有注释的代码也可以删掉，这里如果删了的话，out_dims也没有被使用，编译器会报错应该

2024-03-08 11:55 UTC, risemeup1 commented on paddle/phi/kernels/funcs/selected_rows_functor.cc
>        merged_row_set.insert(input->rows().begin(), input->rows().end());
同理，删除这些注释

2024-03-08 12:02 UTC, silverling commented on paddle/phi/kernels/cpu/send_uv_kernel.cc
>    ctx.template Alloc<T>(out);
对，`memset_size` 是由于后面没有使用到，所以注释掉了。在这个 commit  中均为类似原因：[[HACKATHON 6th][CMake Optimization] comment out unused local variable in functions](https://github.com/PaddlePaddle/Paddle/pull/62565/commits/b86ad32ea15fc2dcd8e67fc0581515e0fe74530e) 均采用了注释而不是删除。

如果确认删除的话，我可以再次 commit.

2024-03-08 12:40 UTC, risemeup1 commented on paddle/phi/infermeta/unary.h
why？这里用struct有问题吗？

2024-03-08 12:40 UTC, risemeup1 commented on paddle/phi/infermeta/unary.cc
>      // set dims of HW -1
common::vectorize(x_dims)这样的右值都不在需使用std::move来转换吗？

2024-03-08 12:40 UTC, risemeup1 commented on paddle/phi/core/distributed/nccl_comm_task.h
>    void ClearRecord() override;
覆盖基类中的虚函数，不加overide为啥gcc没有监控到啊，按道理gcc也能监控到啊

2024-03-08 12:40 UTC, risemeup1 commented on paddle/phi/core/distributed/nccl_comm_task.cc
>    auto global_ranks =
同理删除注释，有很多这种注释的都删了吧

2024-03-08 12:40 UTC, risemeup1 commented on paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
> +    else if (phi::CustomContext::classof(&dev_ctx)) {  // NOLINT
如果不加宏判断会报错吗？

2024-03-08 12:40 UTC, risemeup1 commented on cmake/flags.cmake
> +        -Wno-defaulted-function-deleted # Warning in GLOO
no-defaulted-function-deleted建议加载gloo.cmake，不要放在flags.cmake里面，同理，如果有一些第三方库报了很多warning，可以加在第三方库对应的.cmake文件里，flags.cmake不建议放这些，之前删了很多这里的flags

2024-03-08 12:45 UTC, risemeup1 commented on cmake/flags.cmake
>        ${fsanitize})
上边加的几个编译器选项gcc和clang都有这个问题吗？是不是也加一些判断比较好？如果是clang编译器再加？然后如果是第三方库的问题，放在第三方库的.CMAKE里

2024-03-08 12:52 UTC, silverling commented on paddle/phi/infermeta/unary.cc
>      // set dims of HW -1
通过编译器的 NRVO 优化，在 `common::vectorize()` 函数中的 `result` 变量会直接在 `output_shape = ...` 这里实例化。

2024-03-08 12:54 UTC, silverling commented on paddle/phi/infermeta/unary.h
见上面的第 5 条：
> 5\. **struct 和 class 不匹配**：[fix struct and class tag mismatch](https://github.com/PaddlePaddle/Paddle/commit/9ee47527f4ec10844f4bffe432c38c280b678c0f)
> 
> 我们知道，`struct` 和 `class` 唯一的区别是默认的访问权限不同，`struct` 默认为 `public`，`class` 为 `private`。在几乎所有情况下，我们可以混用这两个名字。而 Clang 编译器的 Warning 为：“class was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI”，意思是，由于 C++ 的 mangling 机制，MSVC 可能会区别 `struct` 和 `class`，导致链接时可能出现异常。为了统一起见，均修改为 `class`。

一般来说，混用 class 和 struct 几乎不会有影响，但编译器会警告，从而报错

2024-03-08 12:59 UTC, silverling commented on paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
> +    else if (phi::CustomContext::classof(&dev_ctx)) {  // NOLINT
不会报错，这个 commit 主要是添加宏判断来避免不必要的头文件引入

2024-03-10 08:53 UTC, silverling commented on cmake/flags.cmake
>        ${fsanitize})
Done

2024-03-14 08:56 UTC, silverling commented on paddle/phi/kernels/cpu/send_uv_kernel.cc
>    ctx.template Alloc<T>(out);
Done

2024-03-14 08:56 UTC, silverling commented on paddle/phi/kernels/funcs/selected_rows_functor.cc
>        merged_row_set.insert(input->rows().begin(), input->rows().end());
Done

2024-03-14 08:56 UTC, silverling commented on paddle/phi/core/distributed/nccl_comm_task.cc
>    auto global_ranks =
Done

2024-03-14 08:56 UTC, silverling commented on paddle/phi/core/distributed/auto_parallel/reshard/reshard_utils.cc
> +    else if (phi::CustomContext::classof(&dev_ctx)) {  // NOLINT
Reverted

2024-03-14 09:05 UTC, silverling commented on cmake/flags.cmake
> +        -Wno-defaulted-function-deleted # Warning in GLOO
Done

2024-03-15 02:22 UTC, zyfncg approved these changes

2024-03-15 02:22 UTC, risemeup1 approved these changes
great work

2024-03-15 02:22 UTC, risemeup1 commented on paddle/fluid/framework/details/all_reduce_op_handle.cc
>          auto dst_ptr = var->GetMutable<phi::DenseTensor>()->data();
这里为啥要这应改啊

2024-03-15 02:22 UTC, zhiqiu approved these changes
LGTM for const_cast

2024-03-15 02:23 UTC, jiahy0825 approved these changes
LGTM for PADDLE_API

2024-03-15 02:26 UTC, luotao1 approved these changes

2024-03-15 02:33 UTC, Galaxy1458 approved these changes

2024-03-15 02:48 UTC, zhangbo9674 approved these changes

2024-03-15 02:49 UTC, merged