[CustomDevice] Support stride[Part 2]
PaddlePaddle/Paddle pull request #62697
Opened 2024-03-13 12:24 UTC by Tongkaio

### PR types

Others
### PR changes

Others
### Description

续 #62532 。给customdevice支持剩余的stride kernel。

2024-03-14 10:49 UTC, wanghuancoder submitted a review, later dismissed
LGTM

2024-03-20 02:14 UTC, wanghuancoder approved these changes, later dismissed
LGTM

2024-03-20 02:34 UTC, risemeup1 approved these changes, later dismissed

2024-03-20 04:40 UTC, qili93 requested changes
需要有更好的抽象来解决这个算子对custom device的注册

2024-03-20 11:41 UTC, YanhuiDua approved these changes

2024-03-20 11:45 UTC, qili93 approved these changes
LGTM

2024-03-21 02:18 UTC, risemeup1 approved these changes

2024-03-21 02:27 UTC, Galaxy1458 approved these changes

2024-03-21 02:44 UTC, raindrops2sea approved these changes
LGTM

2024-03-21 05:58 UTC, merged