【Hackathon 6th No.33】支持动态图流水并行设定多个损失函数，并返回多个 loss
PaddlePaddle/Paddle pull request #63167
Opened 2024-04-01 14:10 UTC by DanGuge

### PR Category

* New features

### PR Types

### Description

1. 在构建 PipelineLayer 时，对用户传入的 loss_fn 进行判断
  * 如果 loss_fn 不是 list，则将 loss_fn 用 [] 包裹
  * 如果 loss_fn 是 list，则直接设置
2. 在计算 loss 时，将计算和通信逻辑都调整为 list loss_fn 的逻辑
3. 在返回 loss 时，根据 len(losses) 的长度，判断用户需要返回 1 个 loss 结果或者多个 loss 结果

2024-04-03 06:46 UTC, DanGuge commented
@MarioLulab 辛苦review一下～

2024-04-07 02:46 UTC, MarioLulab reviewed
Nice Work~ 但还有一些问题，辛苦看下

2024-04-07 02:46 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    assert isinstance(
在 len(_loss_fn) > 1 时，`output_tensor` 会被下一次循环覆盖掉，是否可以改成：

```python
loss_tensor = loss_fn(output_tensor, labels)
```

2024-04-07 02:46 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    assert isinstance(
当前的 `_forward_step` 不符合赛题的要求：「用户可以指定针对哪一个 loss 做 backward。默认下，只对返回的第 0 个 loss 做 backward」。照目前的写法，用户当前情况下没法控制针对哪一个 loss 做 backward。可以尝试在 `train_batch` 函数里新增入参，可让用户指明是对哪个 loss 做 backward

2024-04-07 02:46 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                self.total_loss[idx].detach()
这里的 `idx` 是指？

2024-04-07 03:05 UTC, DanGuge commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    assert isinstance(
> 在 len(_loss_fn) > 1 时，`output_tensor` 会被下一次循环覆盖掉，是否可以改成：
> 
> ```python
> loss_tensor = loss_fn(output_tensor, labels)
> ```

这里的output_tensor只作为一个临时的中间变量，output会被添加到self.total_loss中，此处确实没有考虑到对指定的loss进行backward计算这个问题，目前这样实现是默认用的最后一个loss_fn来做的backward

2024-04-07 03:08 UTC, DanGuge commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                self.total_loss[idx].detach()
这里的idx在866行，如果loss_fn很多的话，total_loss中也会存有对应数量的由不同loss_fn计算得到的loss，此处是对所有loss_fn计算的loss进行聚合，在有多个loss_fn的时候，会返回一个list，存有[loss_0, loss_1, ...]

2024-04-07 06:01 UTC, DanGuge commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                self.total_loss[idx].detach()
这里想问个问题，如果用户指定了loss_fn后，在train_batch/eval_batch中需要返回多个loss还是只返回用户指定的loss_fn对应的loss？
任务中是这么表述的：支持动态图流水线并行组网时指定多个损失函数，并返回多个 loss，用户可以指定针对哪一个 loss 做 backward
我目前的实现是如果只有一个loss_fn，只会返回一个loss，如果有多个loss_fn，会返回一个loss list

2024-04-07 06:35 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    assert isinstance(
output_tensor 确实是作为一个临时的中间变量，但是我们期望达到的效果是不同的 loss_fn 之间是分开对前向得到的 `output_tensor` 与 `label` 求损失函数，而不是当前所写的串行的方式。题目期望效果如下：
<img width="642" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/61354321/9204ac72-ea13-4add-ac20-3b2de8581007">

2024-04-07 06:35 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                self.total_loss[idx].detach()
> 这里想问个问题，如果用户指定了loss_fn后，在train_batch/eval_batch中需要返回多个loss还是只返回用户指定的loss_fn对应的loss？ 任务中是这么表述的：支持动态图流水线并行组网时指定多个损失函数，并返回多个 loss，用户可以指定针对哪一个 loss 做 backward 我目前的实现是如果只有一个loss_fn，只会返回一个loss，如果有多个loss_fn，会返回一个loss list

如果用户指定对特定的 loss_fn 的计算结果进行 backward，在train_batch/eval_batch中也需要返回多个loss，即当 `loss_fn` 是一个 List 时，train_batch/eval_batch 应该返回 List[Tensor] or Tuple[Tensor]；当 `len(loss_fn) == 1`时，只需要返回 Tensor 即可（这样可以和原先的预期行为对齐）

2024-04-07 06:42 UTC, DanGuge commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    assert isinstance(
ok👌，之前实现确实有bug

2024-04-07 07:00 UTC, MarioLulab requested changes
还需要增加一些单测

2024-04-07 07:00 UTC, MarioLulab commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
1. 目前该单测只是测试了2卡的 non-interleaved 模式的 pp。还需要添加 interleaved 模式的 pp 的单测。interleaved 模式的 pp 开启方法是：在派生 `PipelineLayer` 时，指定 `num_virtual_pipeline_stages` 参数，并且需满足 pp_degree > 2

2. 最好再增加一个多卡与单卡的逐位对齐单测，可以参考：https://github.com/PaddlePaddle/Paddle/pull/62563/files#diff-b5f15f3b078428d426f6ddcc1b7c57a67581366ecff2b3b754d9b41bb9484e8fR367-R448
所谓「逐位对齐」的含义是：在每一个 step 中，单卡模型计算得到的 loss 与多卡分布式模型计算得到的 loss 的误差保持在一定阈值内

2024-04-07 11:54 UTC, DanGuge commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
单测添加了，辛苦review～

2024-04-08 02:16 UTC, MarioLulab commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
ci-coverage 里提示代码覆盖率没过，辛苦看下是不是还需要添加一些单测或者单测格式不对导致有些代码没运行？

2024-04-08 02:23 UTC, DanGuge commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
<img width="1045" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/77946882/167c8367-c0f7-4b3d-9e10-69b8f0453846">

<img width="1023" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/77946882/832689c7-1b11-492b-aa76-51c4bd95425f">

这个看起来不是我的单测，错误原因应该是很细微的精度上的问题，这种需要我来添加tolerance吗？

2024-04-08 02:26 UTC, DanGuge commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
还有一个error，我看https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10427910/job/25821459里面也报错了，但是pass了

2024-04-08 02:41 UTC, MarioLulab commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses.py
当前 pr 的 ci-coverage 没过不是因为单测报错，而是因为「代码覆盖率」没过。
![image](https://github.com/PaddlePaddle/Paddle/assets/61354321/bbb0b9f5-8711-494f-bb59-0f8593087d3c)

![image](https://github.com/PaddlePaddle/Paddle/assets/61354321/0de1aaf5-8b9d-47d3-9f39-766d7b2d5d8c)

关于代码覆盖率可以看：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/git_guides/paddle_ci_manual_cn.html#pr-ci-coverage

2024-04-09 09:14 UTC, DanGuge commented
@MarioLulab 辛苦review一下～

2024-04-10 03:04 UTC, MarioLulab reviewed
nice work ～
我提了一些小修改，辛苦看下

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +        self.loss_fn_idx = loss_fn_idx
这里可以再加一个 assert ，断言 self._layers._loss_fn[loss_fn_idx] not None

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +        self.loss_fn_idx = loss_fn_idx
同上

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +                    self._layers._loss_fn[0] is not None
```suggestion
                    self._layers._loss_fn[self.loss_fn_idx] is not None
```

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
>              )
此处对 `is_fp32` broadcast 也要对应处理为 list，因为可能不是 losses 里所有的 loss 都是 fp32 的

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +        self.loss_fn_idx = loss_fn_idx
这里可以再加一个 assert ，断言 self._layers._loss_fn[loss_fn_idx] not None

2024-04-10 03:04 UTC, MarioLulab commented on python/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py
> +        self.loss_fn_idx = loss_fn_idx
同上

2024-04-10 03:04 UTC, MarioLulab commented on test/collective/fleet/hybrid_parallel_pp_multiple_losses_alignment.py
> +            loss_a = model_a(x1, x2, y1)
单卡模型的 loss 数量也要和多卡的对齐，返回 MSE, LossNet(), L1 三种 loss

2024-04-11 07:13 UTC, DanGuge commented
> nice work ～ 我提了一些小修改，辛苦看下

@MarioLulab 修改好了，辛苦review～

2024-04-11 09:17 UTC, MarioLulab approved these changes
LGTM

2024-04-11 12:59 UTC, DanGuge commented
@luotao1 辛苦review一下～

2024-04-12 02:44 UTC, luotao1 commented
辛苦 @ForFishes @GuoxiaWang 审核下

2024-04-15 02:25 UTC, DanGuge commented
@GuoxiaWang @ForFishes 辛苦review一下～

2024-04-16 02:50 UTC, DanGuge commented
@luotao1 辛苦review一下～

2024-04-16 02:57 UTC, ForFishes approved these changes
LGTM

2024-04-16 03:04 UTC, merged