[PIR] reopen `TestReduceAPI.test_static_reduce` UT
PaddlePaddle/Paddle pull request #63185
Opened 2024-04-02 08:45 UTC by gouzil

### PR Category

Others

### PR Types

Others

### Description

重新打开`TestReduceAPI.test_static_reduce`测试

rerun Mac-CI 计数: 0

相关链接：
* #61846
* #62652

2024-04-05 08:19 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20231113/u1f947/u1f947_u1f43e.png" width="14" alt="🐾"/>

2024-04-05 08:21 UTC, SigureMo requested changes
差点忘记 rerun mac CI 了

2024-04-05 08:23 UTC, SigureMo commented
不过 https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10425826/job/25818495 已经 timeout 过了，但自动 rerun 后过了

2024-04-05 13:40 UTC, SigureMo approved these changes

2024-04-05 13:40 UTC, SigureMo commented on python/paddle/autograd/backward_utils.py
> +    block.remove_op(op)
修好了修好了，现在不用 rerun 了～

2024-04-07 03:12 UTC, xiaoguoguo626807 approved these changes

2024-04-07 03:14 UTC, merged