【Hackathon 6th Fundable Projects 3 No.78-80】Remove fluid operators cross_entropy etc
PaddlePaddle/Paddle pull request #63456
Opened 2024-04-12 23:47 UTC by co63oc

### PR Category

Others

### PR Types

Others

### Description

Remove fluid operators cross_entropy etc
cross_entropy
cross_entropy_grad2
cross_entropy2

2024-04-16 06:29 UTC, wanghuancoder approved these changes
LGTM 请 @luotao1 协调预测同学Review，看看删除预测单测是否OK。

2024-04-16 07:52 UTC, vivienfanghuagood approved these changes

2024-04-16 07:56 UTC, vivienfanghuagood reviewed
不建议直接删除单测，可能影响其他功能的测试

2024-04-18 03:05 UTC, luotao1 requested changes
涉及 analzyer，之后统一讨论

2024-04-26 13:47 UTC, closed without merging