add cumprod_grad composite
PaddlePaddle/Paddle pull request #64432
Opened 2024-05-19 08:18 UTC by YibinLiu666

### PR Category
Others

### PR Types
New features

### Description
实现cumprod_grad的组合实现。

2024-05-20 06:04 UTC, HydrogenSulfate requested changes
辛苦提交PR，单测和代码可以再看一下

2024-05-20 06:04 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
1. 加法第二项`zero_mask * ones_tensor`是不是可以化简为`zero_mask`，一个张量乘以全1矩阵`ones_tensor`等于没乘？
2. 如果上面结论成立，可以删除`ones_tensor`

2024-05-20 06:04 UTC, HydrogenSulfate commented on test/prim/prim/vjp/eager/test_comp_eager_cumprod_grad.py
> +)
1. 形状可以添加0D、1D、2D、5D
2. 数据类型添加int64
3. 数据本身添加包含1个0、2个0，全部都是0的case

2024-05-20 06:04 UTC, HydrogenSulfate commented on test/prim/prim/vjp/static/test_comp_cumprod_grad.py
补充更多单测case，同`test/prim/prim/vjp/eager/test_comp_eager_cumprod_grad.py`

2024-05-20 14:33 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
Done

2024-05-20 14:33 UTC, YibinLiu666 commented on test/prim/prim/vjp/eager/test_comp_eager_cumprod_grad.py
> +)
Done

2024-05-20 14:33 UTC, YibinLiu666 commented on test/prim/prim/vjp/static/test_comp_cumprod_grad.py
Done

2024-05-21 03:21 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +    auto zero_mask_cumsum2 = cumsum<T>(zero_mask, dim, false, true, reverse);
变量命名尽量准确符合语义，
zero_mask_cumsum1 --> zero_mask_cumsum_left
zero_mask_cumsum2 --> zero_mask_cumsum_right

2024-05-21 03:23 UTC, HydrogenSulfate commented on paddle/fluid/primitive/rule/vjp/details.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
这里的ones_tensor应该可以删掉吧

2024-05-21 03:28 UTC, HydrogenSulfate commented on paddle/fluid/primitive/rule/vjp/details.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
```suggestion
    auto replace_one = (1 - zero_mask) * x + zero_mask;
```

2024-05-21 03:28 UTC, HydrogenSulfate commented on paddle/fluid/primitive/rule/vjp/details.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
逻辑连续的代码块之间可以加上一些注释，比如此处将0的位置填充成1，可以加上: `# fill the positions of 0 with 1.`

2024-05-21 03:31 UTC, HydrogenSulfate commented on test/prim/prim/vjp/eager/test_comp_eager_cumprod_grad.py
> +    [
加上一个单元素的测试：`np.array(np.rand(), dtype="float32")`

2024-05-21 03:33 UTC, HydrogenSulfate commented on test/prim/prim/vjp/static/test_comp_cumprod_grad.py
> +@param.parameterized_class(
同上，补充以单元素的0-Dcase

2024-05-21 03:35 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
此处的实现跟details.h里的实现好像有一些区别？可以确认一下

2024-05-22 11:39 UTC, HydrogenSulfate commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +        zero_mask_cumsum_inclusive + zero_mask_cumsum_exclusive;
inclusive + exclusive 是否相当于两倍的exclusive + x？两次cumprod应该比一次cumprod + scale + add耗时会更长，是否可以改成后者实现方式？

2024-05-23 04:13 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
> +        zero_mask_cumsum_inclusive + zero_mask_cumsum_exclusive;
Done

2024-05-23 04:13 UTC, YibinLiu666 commented on paddle/fluid/prim/api/composite_backward/composite_backward_api.h
Done

2024-05-23 04:13 UTC, YibinLiu666 commented on test/prim/prim/vjp/static/test_comp_cumprod_grad.py
> +@param.parameterized_class(
Done

2024-05-23 04:13 UTC, YibinLiu666 commented on test/prim/prim/vjp/eager/test_comp_eager_cumprod_grad.py
> +    [
Done

2024-05-23 04:13 UTC, YibinLiu666 commented on paddle/fluid/primitive/rule/vjp/details.h
> +    auto replace_one = (1 - zero_mask) * x + zero_mask * ones_tensor;
Done

2024-05-24 03:11 UTC, zyfncg approved these changes

2024-05-24 03:44 UTC, cyber-pioneer approved these changes
todo: 建议适配optest，当前的这批单侧属于遗留case，未来会被清理

2024-05-24 04:30 UTC, XieYunshen approved these changes

2024-05-24 05:12 UTC, HydrogenSulfate approved these changes

2024-05-24 05:12 UTC, merged