[Typing][A-44] Add type annotations for `paddle/optimizer/lbfgs.py`
PaddlePaddle/Paddle pull request #65308
Opened 2024-06-20 02:56 UTC by enkilee

### PR Category

User Experience

### PR Types

Improvements

### Description

- https://github.com/PaddlePaddle/Paddle/issues/65008
A44

2024-06-22 04:20 UTC, megemini commented on python/paddle/optimizer/lbfgs.py
还有几个 api 别漏了哈 ～ `state_dict` `step` `minimize` ~~~

2024-06-22 04:20 UTC, megemini commented on python/paddle/optimizer/lbfgs.py
还有几个 api 别漏了哈 ～ `state_dict` `step` `minimize` ～～～

咱们这次主要是关注 `公开 api` ，重点关注不以 `_` 开头的那些函数或者方法 ～

另外，ISSUE 里面统计的每个文件中 api 数量可能不准，比如，有的是一个类，只统计了 `1` 次，但是类里面的方法其实都需要修改 ～ 可以参考官网有哪些接口，宁缺勿漏吧 ～ 🤟🤟🤟

2024-06-24 01:11 UTC, enkilee commented on python/paddle/optimizer/lbfgs.py
收到

2024-06-24 01:18 UTC, SigureMo requested changes

2024-06-24 01:18 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    def state_dict(self) -> dict[str, Any]:
用 TypedDict

2024-06-24 01:18 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    def step(self, closure) -> Any:
这个应该是 Tensor？

2024-06-24 01:18 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    ) -> Any:
用 NoReturn

2024-06-24 03:15 UTC, enkilee commented on python/paddle/optimizer/lbfgs.py
> +    ) -> Any:
收到

2024-06-24 04:53 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    ) -> Any:
我这里说的不是 `NoReturn` 吗？

2024-06-24 04:54 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    line_search_fn: NotRequired[str]
再看看？这里不是这样的吧？

2024-06-24 07:11 UTC, SigureMo requested changes

2024-06-24 07:11 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    al: Tensor
会有这些么？

2024-06-24 07:16 UTC, enkilee commented on python/paddle/optimizer/lbfgs.py
> +    al: Tensor
他这个是返回state的值吧？state里面打印出来这些参数

2024-06-24 07:19 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    al: Tensor
这也不是 state 里啊

2024-06-24 07:44 UTC, SigureMo commented on python/paddle/optimizer/lbfgs.py
> +    packed_state: _LbfgsStateDict
<img width="930" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/38436475/77e40463-2943-42cd-8921-8699a33b974e">

啊？为什么会写成这样？我不能理解啊……

2024-06-24 07:53 UTC, enkilee commented on python/paddle/optimizer/lbfgs.py
> +    packed_state: _LbfgsStateDict
啊哈哈，我没看明白，他代码返回的是dict,然后dict里面给了键 state, 和state对应的dict的键的值

2024-06-24 17:02 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20231113/u1f4ae/u1f4ae_u1f43e.png" width="14" alt="🐾"/>

2024-06-25 00:59 UTC, merged