[DCU] New features for LLM
PaddlePaddle/Paddle pull request #65398
Opened 2024-06-24 05:05 UTC by yuguo-Jack

PR Category
Performance Optimization

PR Types
New features

Description
surpport multiclass_nms3 op for DCU（单测通过）
surpport miopen bn for DCU when FLAGS_cudnn_batchnorm_spatial_persistent is 1（test_batch_norm_op/test_batch_norm_op_v2单测通过）
surpport gemm fp16 compute type for DCU when FLAGS_gemm_use_half_precision_compute_type is 1

支持flash attention（mha，gqa前反向，单测通过）
支持a8w8相关算子（单测通过）
支持quant_linear相关算子（单测通过）
支持fused rope相关算子（单测通过）

2024-06-24 09:51 UTC, SylarTiaNII requested changes

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/fluid/operators/matmul_op.cc
> +    ops::MatMulKernel<phi::GPUContext, int8_t>,
量化相关的kernel可以拆分到推理的PR里面。

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/backends/dynload/flashattn.h
>    __macro(flash_attn_bwd_with_bias_and_mask); \
这两个kernel能否也在DCU上实现？这样可以和GPU完全打平，就不用这个分支宏了。

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/common/float16.h
> +#if !(defined(PADDLE_WITH_CUSTOM_KERNEL) && defined(PADDLE_WITH_HIP))
这段逻辑确认只会在DCU相关的逻辑分支中调用吗？

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/infermeta/ternary.cc
> +  PADDLE_ENFORCE_EQ(out_dims.size(),
这里修改原来GPU默认的逻辑原因是什么？

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/infermeta/unary.cc
> +      ((arch == 80) || (arch == 86) || (arch == 70) || (arch == 75)),
需要琦姐帮忙确认一下影响面。

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/funcs/blas/blas_impl.hip.h
> +COMMON_DECLARE_bool(gemm_use_half_precision_compute_type);
这里为什么需要在kernel内部控制算子类型呢？因为会有破坏框架amp（混合精度）逻辑的风险。

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
这里我理解不需要新增编译宏，WITH_HIP和WITH_GPU是同等的，都可以开启WITH_FLASHATTN

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_utils.h
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
同上

2024-06-24 09:51 UTC, SylarTiaNII commented on python/paddle/utils/cpp_extension/cpp_extension.py
> +                    # cflags.append('-D__HIP_NO_HALF_CONVERSIONS__=1')
这里注释的原因是什么？后续还会打开吗？

2024-06-24 10:15 UTC, yuguo-Jack commented on paddle/fluid/operators/matmul_op.cc
> +    ops::MatMulKernel<phi::GPUContext, int8_t>,
这部分代码paddle之后改动很小了，一并提交吧，未合入的推理文件是近期会变动较大的

2024-06-24 10:16 UTC, yuguo-Jack commented on paddle/phi/backends/dynload/flashattn.h
>    __macro(flash_attn_bwd_with_bias_and_mask); \
>

2024-06-24 10:37 UTC, yuguo-Jack commented on paddle/phi/common/float16.h
> +#if !(defined(PADDLE_WITH_CUSTOM_KERNEL) && defined(PADDLE_WITH_HIP))
此段逻辑只会在DCU上编三方算子时跳过，其他场景均不受影响，否则编paddlenlp中的三方算子会报错

2024-06-24 10:39 UTC, yuguo-Jack commented on paddle/phi/infermeta/unary.cc
> +      ((arch == 80) || (arch == 86) || (arch == 70) || (arch == 75)),
这是为了之后DCU上weight only相关代码合入去掉的检查

2024-06-24 10:46 UTC, yuguo-Jack commented on paddle/phi/infermeta/ternary.cc
> +  PADDLE_ENFORCE_EQ(out_dims.size(),
![image](https://github.com/PaddlePaddle/Paddle/assets/29474149/cee436ff-ec6e-4e89-910e-d3df43a6f6bf)
paddle中fa变长接口用的也是FlashAttnInferMeta，在此推导接口内会检查qkv是否是4维，但是变长接口传入的qkv是3维，所以会报错，我还奇怪难道nv上调用变长接口时候这个检查能通过吗

2024-06-24 10:47 UTC, yuguo-Jack commented on paddle/phi/infermeta/ternary.cc
> +                    4,
在这里做的检查

2024-06-24 10:49 UTC, yuguo-Jack commented on python/paddle/utils/cpp_extension/cpp_extension.py
> +                    # cflags.append('-D__HIP_NO_HALF_CONVERSIONS__=1')
在DCU上编三方算子需要注释，否则算子内部无法使用half static_cast，之后不会打开

2024-06-24 10:58 UTC, yuguo-Jack commented on paddle/phi/kernels/funcs/blas/blas_impl.hip.h
> +COMMON_DECLARE_bool(gemm_use_half_precision_compute_type);
这是参考的NV的逻辑blas_iml.cu.h的方式

2024-06-24 11:00 UTC, yuguo-Jack commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
DCU上没有适配fused_gate_attention，也即bias_mask接口，PADDLE_WITH_FLASHATTN会打开这段逻辑，所以没有复用这个宏

2024-06-24 11:13 UTC, yuguo-Jack commented on paddle/phi/infermeta/unary.cc
> +      ((arch == 80) || (arch == 86) || (arch == 70) || (arch == 75)),
这个我修复下，合错了

2024-06-25 06:48 UTC, SylarTiaNII commented on paddle/phi/kernels/gpu/flash_attn_grad_kernel.cu
> +#if defined(PADDLE_WITH_FLASHATTN) || defined(PADDLE_WITH_HIP)
那如果这样的话应该反过来定义比较合理，在with_bias_and_mask接口的位置增加&& !defined(PADDLE_WITH_HIP)

2024-07-03 05:16 UTC, zhangting2020 approved these changes
LGTM for op-benchmark

2024-07-03 06:29 UTC, SylarTiaNII approved these changes
LGTM

2024-07-03 06:43 UTC, zhangbo9674 approved these changes
LGTM for setup

2024-07-03 06:47 UTC, phlrain approved these changes
LGTM for setup.py.in

2024-07-03 09:37 UTC, XiaoguangHu01 approved these changes
LGTM

2024-07-03 12:29 UTC, merged