Update cudnn flash attention
PaddlePaddle/Paddle pull request #65507
Opened 2024-06-27 02:22 UTC by deepllz

### PR Category

 Performance Optimization

### PR Types

Performance

### Description

重构cudnn版本的flash attention API，与scaled_dot_product_attention对齐

2024-07-04 08:54 UTC, Wong4j commented
LGTM

2024-07-05 02:34 UTC, zhiqiu submitted a review, later dismissed
LGTM

2024-07-05 03:51 UTC, sneaxiy approved these changes

2024-07-05 03:51 UTC, sneaxiy commented on python/paddle/incubate/nn/functional/fused_dot_product_attention.py
> +    scaling_factor = head_dim**-0.5
`scaling_factor`可以保留`None`的默认参数，这样以后可以给其他值。在为None的时候，自动变成`head_dim**-0.5`.

2024-07-05 03:57 UTC, Wong4j approved these changes

2024-07-05 03:59 UTC, sneaxiy requested changes
请回退`graph_pattern_detector.cc`的改动，并给`fused_dot_product_attention`补回`scaling_factor`的参数选项。

2024-07-05 04:12 UTC, deepllz commented on python/paddle/incubate/nn/functional/fused_dot_product_attention.py
> +    scaling_factor = head_dim**-0.5
Done

2024-07-05 04:14 UTC, deepllz commented
> 请回退`graph_pattern_detector.cc`的改动，并给`fused_dot_product_attention`补回`scaling_factor`的参数选项。

Done

2024-07-08 09:01 UTC, sneaxiy approved these changes

2024-07-08 09:01 UTC, merged