add deterministic option
PaddlePaddle/Paddle pull request #65696
Opened 2024-07-04 02:29 UTC by Wong4j

### PR Category
Others

### PR Types
New features

### Description
Add deterministic option for cuDNN flash attention.

2024-08-05 03:05 UTC, deepllz approved these changes
LGTM

2024-08-06 02:31 UTC, Wong4j commented
@onecatcn 这个PR给cuDNN FA的API增加了一个deterministic的开关，麻烦帮忙找人review API的修改。
```
0. You must have one RD (inference[ vivienfanghuagood(Recommend), yuanlehome, qingqing01 ] or slim[ wanghaoshuang(Recommend), qingqing01 ] or train[ phlrain ]) approval for the changes of Inputs/Output/Attrs of OPs. The changes of OPs will cause that the new version inference fails to load model trained by the old version. Please modify your code. 
1. You must have one RD (qingqing01(Recommend), heavengate) approval for the changes of  Inputs/Output/Attrs of OPs. 
```

2024-08-08 02:21 UTC, vivienfanghuagood reviewed
What's the effect if user turn on the `deterministic` option?

2024-08-08 02:36 UTC, Wong4j commented
@vivienfanghuagood Flash Attention的forward总是deterministic的，但backward计算默认会用一个non-deterministic的算法，即同样的输入，每次跑的输出会有一些的误差波动。
开启这个option之后，可以让backward采用deterministic的算法，确保结果是稳定的，相同的输入，其输出是bit-wise完全一致的。

2024-08-14 01:18 UTC, Wong4j commented
@vivienfanghuagood @qingqing01 请问还有review意见吗？

2024-08-21 02:38 UTC, vivienfanghuagood approved these changes

2024-08-26 06:26 UTC, Wong4j commented
@qingqing01 麻烦帮忙看一下

2024-09-02 06:03 UTC, qingqing01 submitted a review, later dismissed

2024-09-02 06:08 UTC, qingqing01 commented on paddle/phi/ops/yaml/fused_backward.yaml
> +  forward : fused_dot_product_attention (Tensor q, Tensor k, Tensor v, Tensor bias, Tensor cu_seqlen_q, Tensor cu_seqlen_kv, float scaling_factor, float dropout_probability, bool is_training, str mas
The environment variable  FLAGS_cudnn_deterministic  is also used to set deterministic algorithm in cuDNN.


https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/common/flags.cc#L227

2024-09-03 11:45 UTC, Wong4j commented on paddle/phi/ops/yaml/fused_backward.yaml
> +  forward : fused_dot_product_attention (Tensor q, Tensor k, Tensor v, Tensor bias, Tensor cu_seqlen_q, Tensor cu_seqlen_kv, float scaling_factor, float dropout_probability, bool is_training, str mas
@qingqing01 cudnn frontend 1.5版本之后在c++ API中增加了参数控制deterministic，不再检测环境变量。所以我这里是按照cudnn推荐的写法来改。另外FLAGS_cudnn_deterministic是Paddle的环境变量，目前不能影响到cudnn flash attention。   


如果你们想通过FLAGS_cudnn_deterministic来控制，我也可以在python API中加一行
```python
if os.environ.get("FLAGS_cudnn_deterministic", False):
        deterministic = True
```

2024-09-25 03:42 UTC, GuoxiaWang approved these changes
LGTM

2024-09-25 03:43 UTC, GuoxiaWang requested changes
随机性控制，请用 FLAGS_cudnn_deterministic 来控制，用户可能会是这样写：

```
export FLAGS_cudnn_deterministic=1
or 
export FLAGS_cudnn_deterministic=false
```

```
from distutils.util import strtobool

if strtobool(os.getenv("FLAGS_cudnn_deterministic", 0)): 
    deterministic = True
```

2024-09-26 02:40 UTC, qingqing01 submitted a review, later dismissed

2024-10-10 02:46 UTC, GuoxiaWang commented
建议在 phi 接口上去除 deterministic 入参，在 Kernel 里面使用 FLAGS_cudnn_deterministic 环境变量控制。

2024-11-11 02:19 UTC, Wong4j commented
@GuoxiaWang CI过了，麻烦review一下。
我暂时是把flashattn的编译设置成set(FA_JOB_POOLS_COMPILE 2)，避免内存不够。
如果没问题，我就把这部分revert回去。

2024-12-12 06:18 UTC, GuoxiaWang approved these changes

2024-12-12 06:18 UTC, merged