[Typing][B-20] Add type annotations for `python/paddle/distribution/lognormal.py`
PaddlePaddle/Paddle pull request #65843
Opened 2024-07-09 02:16 UTC by enkilee

### PR Category

User Experience

### PR Types

Improvements

### Description

- https://github.com/PaddlePaddle/Paddle/issues/65008
B20

2024-07-09 04:09 UTC, megemini commented on python/paddle/distribution/lognormal.py
> +    ) -> None:
是不是缺了类属性 `loc scale`？

2024-07-09 04:53 UTC, enkilee commented on python/paddle/distribution/lognormal.py
> +    ) -> None:
抱歉，已加

2024-07-10 06:53 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240206/u2757/u2757_u1f43e.png" width="14" alt="🐾"/>

2024-07-10 06:57 UTC, SigureMo requested changes
等待 https://github.com/PaddlePaddle/Paddle/pull/65849#discussion_r1671718328 确认

2024-07-11 17:10 UTC, SigureMo submitted a review, later dismissed

2024-07-12 06:33 UTC, SigureMo approved these changes

2024-07-12 06:33 UTC, merged