【Fix PIR Unittest No.33 BUAA】Fix some test case in PIR
PaddlePaddle/Paddle pull request #66247
Opened 2024-07-19 04:36 UTC by crazyxiaoxi

### PR Category
others

### PR Types
others

### Description
版本问题，回退一下即可

2024-07-22 03:24 UTC, wanghuancoder approved these changes, later dismissed
set_need_check_feed的修改方法为：
if not paddle.framework.use_pir_api():
    set_need_check_feed

2024-07-23 02:25 UTC, luotao1 requested changes
请按照要求进行修改

2024-07-23 09:21 UTC, wanghuancoder reviewed
修复完以后需要把单测从deprecated里挪出

2024-07-23 10:07 UTC, crazyxiaoxi commented
> 修复完以后需要把单测从deprecated里挪出

这个是下午线下找您的，当时说调试的时候注释掉说精度有问题，把调试的部分提个pr，还是报error，所以没放到deprecated里面

2024-07-24 03:15 UTC, wanghuancoder approved these changes
LGTM

2024-08-20 07:03 UTC, closed without merging