[Typing][B-92] Add type annotations for python/paddle/batch.py
PaddlePaddle/Paddle pull request #66295
Opened 2024-07-20 04:13 UTC by Caogration

### PR Category

User Experience

### PR Types

Improvements

### Description

类型标注：

- python/paddle/batch.py

### Related links
 
- https://github.com/PaddlePaddle/Paddle/issues/65008

@SigureMo @megemini

2024-07-20 09:53 UTC, SigureMo requested changes
这已经是第三次提示了，按照 `PR-CI-Codestyle-Check` 报错提示运行 pre-commit

2024-07-20 09:53 UTC, SigureMo commented on python/paddle/batch.py
> +T = TypeVar('T')
```suggestion
_T = TypeVar('_T')
```

2024-07-20 09:53 UTC, SigureMo commented on python/paddle/batch.py
> +    from types import ModuleType
这是干啥用的？

2024-07-20 09:53 UTC, SigureMo commented on python/paddle/batch.py
> +) -> Generator[List[T], None, None]:
```suggestion
) -> Generator[list[T], None, None]:
```

2024-07-20 10:30 UTC, SigureMo commented
> 这已经是第三次提示了，按照 `PR-CI-Codestyle-Check` 报错提示运行 pre-commit

喔，抱歉看错人了，这是第一次 :joy:

2024-07-21 09:32 UTC, megemini commented on python/paddle/batch.py
> +) -> Generator[List[T], None, None]:
```suggestion
    reader: Callable[[], Generator[_T, None, None]], batch_size: int, drop_last: bool = False
) -> Callable[[], Generator[list[_T], None, None]]:
```

2024-07-22 02:02 UTC, SigureMo reviewed
1. pre-commit 仍然没跑
2. 输入输出类型不对，没有按照 @megemini 的提示修改，可以参考 #66305 定义一个 `TypeAlias`

2024-07-22 02:02 UTC, SigureMo commented on python/paddle/batch.py
> +    reader: Generator[T, None, None], batch_size: int, drop_last: bool = False
上面定义了 `_T`，这里肯定也要改啊

2024-07-22 10:38 UTC, Caogration commented on python/paddle/batch.py
> +    from types import ModuleType
这是没有用的，在新的提交中已经将其删除。

2024-07-22 10:39 UTC, Caogration commented on python/paddle/batch.py
> +) -> Generator[List[T], None, None]:
Done

2024-07-22 10:39 UTC, Caogration commented on python/paddle/batch.py
> +    reader: Generator[T, None, None], batch_size: int, drop_last: bool = False
Done

2024-07-22 18:21 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20220506/u1f52e/u1f52e_u1f43e.png" width="14" alt="🐾"/>

2024-07-23 01:52 UTC, merged