[Typing][C-119] Add type annotations for `python/paddle/quantization/config.py`
PaddlePaddle/Paddle pull request #66684
Opened 2024-07-29 01:48 UTC by enkilee

### PR Category

User Experience

### PR Types

Improvements

### Description

- https://github.com/PaddlePaddle/Paddle/issues/65008
C119

2024-07-29 05:05 UTC, megemini commented on python/paddle/quantization/config.py
> +        layer_type: type | list[type],
```suggestion
        layer_type: type[Layer] | list[type[Layer]],
```

后面的几个也需要 ～～～

2024-07-29 05:05 UTC, megemini commented on python/paddle/quantization/config.py
> +    def customized_leaves(self) -> list:
```suggestion
    def customized_leaves(self) -> list[type[Layer]]:
```

2024-07-29 07:13 UTC, enkilee commented on python/paddle/quantization/config.py
> +        layer_type: type | list[type],
收到

2024-07-29 07:13 UTC, enkilee commented on python/paddle/quantization/config.py
> +    def customized_leaves(self) -> list:
收到

2024-07-29 10:00 UTC, megemini commented on python/paddle/quantization/config.py
> +        self, activation: QuanterFactory, weight: QuanterFactory
```suggestion
        self, activation: QuanterFactory | None, weight: QuanterFactory | None
```

2024-07-29 10:00 UTC, megemini commented on python/paddle/quantization/config.py
>          activation: QuanterFactory = None,
`activation: QuanterFactory | None= None` 另外，刚才发现这个文件中很多地方都没加 `None` ~~~

2024-07-30 00:52 UTC, enkilee commented on python/paddle/quantization/config.py
>          activation: QuanterFactory = None,
收到

2024-07-30 00:52 UTC, enkilee commented on python/paddle/quantization/config.py
> +        self, activation: QuanterFactory, weight: QuanterFactory
收到

2024-07-30 17:36 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240206/u1f9e9/u1f9e9_u1f43e.png" width="14" alt="🐾"/>

2024-07-30 17:40 UTC, SigureMo requested changes

2024-07-30 17:40 UTC, SigureMo commented on python/paddle/quantization/config.py
>          Examples:
```
2024-07-30 09:23:09 paddle.quantization.QuantConfig.add_qat_layer_mapping:1
2024-07-30 09:23:09 <string>:10:40: error: Argument 2 to "add_qat_layer_mapping" of "QuantConfig" has incompatible type "Type[CustomizedQuantedConv2D]"; expected "Type[Layer]"  [arg-type]
2024-07-30 09:23:09 Found 1 error in 1 file (checked 1 source file)
2024-07-30 09:23:09 
2024-07-30 09:23:09 
2024-07-30 09:23:09 >>> Mistakes found in type checking!
2024-07-30 09:23:09 >>> Please recheck the type annotations. Run `tools/type_checking.py` to check the typing issues:
2024-07-30 09:23:09 > python tools/type_checking.py paddle.quantization.QuantConfig.add_qat_layer_mapping
```

这个 `CustomizedQuantedConv2D` 是不是忘了继承 `Layer` 了，奇怪 289 行明明有检查，示例代码运行时检查怎么没挂

2024-07-31 03:44 UTC, megemini commented on python/paddle/quantization/config.py
>          Examples:
好好看看，原来的代码写错了 ... ... 🫠

@enkilee 帮忙把原来代码改一下吧 ～

2024-07-31 05:07 UTC, enkilee commented on python/paddle/quantization/config.py
>          Examples:
收到

2024-07-31 13:02 UTC, SigureMo commented on python/paddle/quantization/config.py
>          Examples:
示例代码没改啊，需要继承下

2024-08-01 05:32 UTC, enkilee commented on python/paddle/quantization/config.py
>          Examples:
收到

2024-08-01 10:33 UTC, SigureMo commented on python/paddle/quantization/config.py
> +                >>> class CustomizedQuantedConv2D(paddle.nn.Layer):
```
2024-08-01 16:54:42 ----------------Check results--------------------
2024-08-01 16:54:42 paddle.quantization.QuantConfig.add_qat_layer_mapping:1
2024-08-01 16:54:42 <string>:6:31: error: Name "paddle" is not defined  [name-defined]
2024-08-01 16:54:42 Found 1 error in 1 file (checked 1 source file)
2024-08-01 16:54:42 
2024-08-01 16:54:42 
2024-08-01 16:54:42 >>> Mistakes found in type checking!
2024-08-01 16:54:42 >>> Please recheck the type annotations. Run `tools/type_checking.py` to check the typing issues:
2024-08-01 16:54:42 > python tools/type_checking.py paddle.quantization.QuantConfig.add_qat_layer_mapping
2024-08-01 16:54:42 ----------------End of the Check--------------------
```

啊……

2024-08-02 00:36 UTC, enkilee commented on python/paddle/quantization/config.py
> +                >>> class CustomizedQuantedConv2D(paddle.nn.Layer):
啊哈哈，昨天没空，现在加了，大佬放宽心。

2024-08-02 01:54 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20231113/u1f4ae/u1f4ae_u1f43e.png" width="14" alt="🐾"/>

2024-08-02 07:41 UTC, merged