【Infer Symbolic Shape BUAA No.73】Add margin_cross_entropy op
PaddlePaddle/Paddle pull request #66730
Opened 2024-07-29 08:30 UTC by crazyxiaoxi

### PR Category
CINN

### PR Types
improvements

### Description
添加margin_cross_entropy算子符号推导接口

2024-08-05 09:16 UTC, crazyxiaoxi commented
test_index_select_strided.py 中已包含OpTest单测，self.check_output() 中 check_dygraph / check_pir 默认关闭，申请approve coverage 流水线

2024-08-06 11:11 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +
这里参考infermeta 加一下 equal constrain 约束

2024-08-09 07:48 UTC, zyfncg commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +      infer_context->AddBroadcastableCstr(logits_dims[i], labels_dims[i]);
这里应该是 Equal 约束吧？

2024-08-09 07:49 UTC, Hongqing-work approved these changes

2024-08-09 08:25 UTC, Hongqing-work requested changes

2024-08-09 08:25 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  }
这里逻辑和infer meta不太符合，和之前的相等约束一并修改后再合并吧

2024-08-09 08:31 UTC, crazyxiaoxi commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  }
已修改

2024-08-09 08:32 UTC, crazyxiaoxi commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +      infer_context->AddBroadcastableCstr(logits_dims[i], labels_dims[i]);
已修改

2024-08-09 10:02 UTC, crazyxiaoxi commented
test_mode_op.py中已包含OpTest单测，self.check_output() 确认使用，申请approve流水线
<img width="943" alt="截屏2024-08-09 10 42 50" src="https://github.com/user-attachments/assets/7442686e-fee2-4752-afc2-f496f4bc82be">

2024-08-12 03:24 UTC, gongshaotian approved these changes
LGTM

2024-08-12 03:26 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    infer_context->AddEqualCstr(labels_dims[axis - 1], one);
infer meta里是检查labels_dims[logits_rank - 1]是否等于1，再确认下是否一致吧

2024-08-12 03:37 UTC, crazyxiaoxi commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    infer_context->AddEqualCstr(labels_dims[axis - 1], one);
上面是infermeta的定义
<img width="370" alt="截屏2024-08-12 11 34 46" src="https://github.com/user-attachments/assets/54acfeb4-13fa-4ea5-82a5-43f1159d91ce">
下面是opinfersymbolicshape
<img width="544" alt="截屏2024-08-12 11 35 36" src="https://github.com/user-attachments/assets/f7aacd3d-d7eb-478d-846c-452285b1bffd">

确实在写的时候不需要 ' -1'

2024-08-12 04:43 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    infer_context->AddEqualCstr(labels_dims[axis - 1], one);
那下一个PR顺带修复一下吧，提的时候把这个PR链接带上

2024-08-12 04:43 UTC, Hongqing-work approved these changes

2024-08-12 04:44 UTC, merged