【Infer Symbolic Shape No.120】[BUAA] affine_grid
PaddlePaddle/Paddle pull request #67364
Opened 2024-08-13 03:37 UTC by BHmingyang

### PR Category
CINN

### PR Types
Others

### Description

add affine_grid op
check_pir已经打开，本地测试通过
<img width="850" alt="截屏2024-08-13 11 36 34" src="https://github.com/user-attachments/assets/452289cf-9691-44bc-b19d-3c3ebf8f0a4d">

2024-08-16 02:06 UTC, Hongqing-work approved these changes

2024-08-16 02:06 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +      static_cast<int64_t>(output_shape_or_data.data().value().size());
output_shape_or_data.shape().size()

2024-08-16 02:06 UTC, Hongqing-work requested changes

2024-08-16 02:06 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +      static_cast<int64_t>(output_shape_or_data.data().value().size());
修改后再重新review吧

2024-08-16 07:00 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +  const auto &output_shape_or_data =
output_shape 是IntArray类型有可能从attribute传过来，加一个逻辑判断

2024-08-16 07:01 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +      static_cast<int64_t>(output_shape_or_data.shape().size());
非必要cast，为啥不直接用int接收

2024-08-16 07:37 UTC, BHmingyang commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +      static_cast<int64_t>(output_shape_or_data.data().value().size());
done

2024-08-16 07:37 UTC, BHmingyang commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +  const auto &output_shape_or_data =
done

2024-08-16 07:37 UTC, BHmingyang commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +      static_cast<int64_t>(output_shape_or_data.shape().size());
done

2024-08-22 12:00 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +  }
D, H, W可以从output_shape中得到，再确认下吧

2024-08-23 00:58 UTC, BHmingyang commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +  }
done

2024-08-23 02:12 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
> +    output_shape_data = output_shape_or_data.shape();
这里应该是取data，可以用details::GetOrCreateExprVecFromData(output_shape_or_data, infer_context)

2024-08-23 06:40 UTC, Hongqing-work approved these changes

2024-08-23 08:53 UTC, merged