[Typing][C-107] Add type annotations for `python/paddle/base/compiler.py`
PaddlePaddle/Paddle pull request #67699
Opened 2024-08-25 12:29 UTC by haoyu2022

### PR Category

User Experience

### PR Types

Improvements

### Description

类型标注：
-python/paddle/base/compiler.py

### Related links
 
- https://github.com/PaddlePaddle/Paddle/issues/65008

@SigureMo @megemini

2024-08-25 12:49 UTC, megemini reviewed
没有全部 review 完，这个文件里面需要标注的是 

- "CompiledProgram",
- "IpuCompiledProgram",
- "IpuStrategy"

这三个类，标注其中类的实例参数、公共方法、魔法方法 ～

目前有很多地方都有标注不全的情况 ～

2024-08-25 12:49 UTC, megemini commented on python/paddle/base/compiler.py
> +    def _with_inference_optimize(self, config) -> Any:
私有方法不用标注 ～ 如果要标注，也漏掉了 `config` ，而且，返回的是 `Self` ～

另外，`__init__` 等魔法方法需要标注，上面漏掉了 ～

2024-08-25 12:49 UTC, megemini commented on python/paddle/base/compiler.py
> +    def patch_program_cache(ipu_strategy) -> None:
上面的 `__init__` 和 `convert_concrete_program` 没有标注

2024-08-25 12:49 UTC, megemini commented on python/paddle/base/compiler.py
> +    _ClassInfo: TypeAlias = Union[type[Any], Tuple["_ClassInfo", ...]]
？

2024-08-25 12:50 UTC, SigureMo requested changes
有不少漏的吧……比如 `register_patch`

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    _ClassInfo: TypeAlias = Union[type[Any], Tuple["_ClassInfo", ...]]
这个是干啥用的？

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def _with_inference_optimize(self, config) -> Any:
你要不会标，这些下划线开头的非公开 API 就不要标了，标个 `Any` 和没标一样

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def _compile(self, scope, place) -> Any:
同上

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def set_optimizer(self, optimizer: Any) -> None:
`optimizer` 怎么会是 `Any`？

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def parse_optimizer(self, optimizer: Any) -> Any:
怎么全是 `Any`？

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
>          micro_batch_size=1,
这个怎么不标？

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def set_options(self, options: dict[str, Any]) -> None:
这个 `options` 用 `TypedDict` 标注下

2024-08-25 12:50 UTC, SigureMo commented on python/paddle/base/compiler.py
> +    def get_option(self, option: str) -> Any:
同样用 `TypedDict`

2024-08-25 13:31 UTC, haoyu2022 commented on python/paddle/base/compiler.py
> +    def _with_inference_optimize(self, config) -> Any:
好的，我再仔细看看🤔

2024-08-25 13:32 UTC, haoyu2022 commented on python/paddle/base/compiler.py
> +    _ClassInfo: TypeAlias = Union[type[Any], Tuple["_ClassInfo", ...]]
这个文件有些地方我还没看太明白，我再仔细看看。

2024-08-28 05:16 UTC, megemini commented
@haoyu2022 由于需要结项，我这里就把这个任务接过来了 https://github.com/PaddlePaddle/Paddle/pull/67767 

不好意思 ～ 🤟

2024-08-28 05:39 UTC, haoyu2022 commented
好的



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 28, 2024 13:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle] [Typing][C-107] Add type annotations for`python/paddle/base/compiler.py` (PR #67699)




 
@haoyu2022 由于需要结项，我这里就把这个任务接过来了 #67767
 
不好意思 ～ 🤟
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-08-28 05:39 UTC, haoyu2022 commented
好的，里面有些地方不太会改，一直不知道该怎么改。



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 28, 2024 13:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle] [Typing][C-107] Add type annotations for`python/paddle/base/compiler.py` (PR #67699)




 
@haoyu2022 由于需要结项，我这里就把这个任务接过来了 #67767
 
不好意思 ～ 🤟
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-08-29 12:27 UTC, closed without merging