【Infer Symbolic Shape No.176】【BUAA】Add unpool op
PaddlePaddle/Paddle pull request #67818
Opened 2024-08-29 06:56 UTC by Caogration

### PR Category
 CINN

### PR Types
 Others

### Description

Add unpool op.

2024-09-02 11:28 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  }
删掉symbol::DimExpr()

2024-09-02 11:28 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    output_size = details::GetVectorAttr<int64_t>(op, "output_size");
在这里转成dimexpr类型吧

2024-09-06 07:50 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  }
Done

2024-09-06 09:14 UTC, Hongqing-work requested changes

2024-09-06 09:14 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    }
1、output_size允许是符号表达式，不需要检查`output_size_i.isa<int64_t>())`
2、`output_size_expr = shape_or_data.shape();`为错误使用，这里和shape无关

2024-09-06 12:49 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +      output_size_expr = shape_or_data.shape();
改为：details::GetOrCreateExprVecFromData(shape_or_data,infer_context);

2024-09-06 12:52 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    }
不需要判断这里可以是符号或者表达式，不需要判断int

2024-09-06 12:54 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  std::vector<int64_t> output_size;
这里直接声明成std::vector<symbol::DimExpr>

2024-09-06 12:55 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    output_size = details::GetVectorAttr<int64_t>(op, "output_size");
取出来后转成DimExpr吧，这样就统一了，下面不需要output_size_expr了

2024-09-13 06:44 UTC, gongshaotian commented
pre-commit 一下，codestyle 挂了

2024-09-14 06:21 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    }
Done

2024-09-14 06:21 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +      output_size_expr = shape_or_data.shape();
Done

2024-09-14 06:22 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    }
Done

2024-09-14 06:22 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +  std::vector<int64_t> output_size;
Done

2024-09-14 06:22 UTC, Caogration commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/binary_infer_sym.cc
> +    output_size = details::GetVectorAttr<int64_t>(op, "output_size");
Done

2024-09-18 02:57 UTC, gongshaotian approved these changes

2024-09-18 03:01 UTC, Hongqing-work approved these changes

2024-09-19 02:32 UTC, merged