【BUAA】【Infer Symbolic Shape】add lstm
PaddlePaddle/Paddle pull request #67859
Opened 2024-08-30 04:59 UTC by uanu2002

### PR Category

CINN

### PR Types

Others

### Description

添加 lstm 算子符号推导接口实现。

2024-08-30 10:46 UTC, uanu2002 commented
lstm有optest单测但check_pir未打开

2024-09-01 16:13 UTC, gongshaotian requested changes

2024-09-01 16:13 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
> +  symbol::ShapeOrDataDimExprs shape_data{
命名不规范

2024-09-01 16:13 UTC, gongshaotian commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/multiary_infer_sym.cc
> +    infer_context->SetShapeOrDataForValue(op->result(2), input_shape_or_data);
这里将input的data区数据也传出去了，一般只传shape区数据

2024-09-04 12:52 UTC, gongshaotian approved these changes
LGTM

2024-10-08 08:42 UTC, closed without merging