[CINN] fix `unsqueeze` op in PaddleTest `test_all_pd_op_unsqueeze_`
PaddlePaddle/Paddle pull request #67916
Opened 2024-09-02 07:29 UTC by tlxd

### PR Category

CINN

### PR Types

Bug fixes

### Description

fix `unsqueeze` op in PaddleTest `test_all_pd_op_unsqueeze_`

2024-09-02 07:32 UTC, tlxd commented
![img2](https://github.com/user-attachments/assets/29334923-c928-4b6b-a276-f6c1208c9219)
测试通过 `PaddleTest/.../test_all_pd_op_unsqueeze_ .py`文件

2024-09-04 03:13 UTC, gongshaotian approved these changes
LGTM

2024-09-04 03:21 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
这里不应该用shape()吧，原来代码就有误，建议直接用details::GetOrCreateExprVecFromData

2024-09-05 07:15 UTC, tlxd commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
> 这里不应该用shape()吧，原来代码就有误，建议直接用details::GetOrCreateExprVecFromData
换成details::GetOrCreateExprVecFromData之后报错信息就变成这个了，请问这样要怎么解决呢
![img2](https://github.com/user-attachments/assets/a5257c6c-fb79-4c3b-a55c-966746e00761)

2024-09-05 08:56 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
CINN处理不了动态rank，报错是正常的

2024-09-05 08:56 UTC, Hongqing-work approved these changes

2024-09-05 09:25 UTC, Hongqing-work requested changes

2024-09-05 09:25 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
这个测试挂了没问题，修改成details::GetOrCreateExprVecFromData

2024-09-05 09:36 UTC, tlxd commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
done

2024-09-09 03:15 UTC, Hongqing-work approved these changes

2024-09-09 03:15 UTC, Hongqing-work commented on paddle/fluid/pir/dialect/operator/interface/infer_symbolic_shape/unary_infer_sym.cc
>    }
`GetOrCreateExprVecFromData`其实已经有`.data().has_value()`的判断了，可以下个PR再修复

2024-09-09 03:37 UTC, gongshaotian approved these changes

2024-09-09 03:38 UTC, merged