c_softmax_with_cross_entropy_op supports multiple label values
PaddlePaddle/Paddle pull request #69041
Opened 2024-10-29 09:25 UTC by tianhaodongbd

### PR Category

Distributed Strategy

### PR Types

New features

### Description

ParallelCrossEntropy 支持多标签分类
c_softmax_with_cross_entropy_op 的label参数支持shape=[B, S, C]，其中1 <= C <= vocab_size
Pcard-87604

2024-10-31 03:14 UTC, GuoxiaWang requested changes

2024-10-31 03:14 UTC, GuoxiaWang commented on paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
> +__global__ void CaculateLogitsGrad(T* logits_grad,
这里`CaculateLogitsGrad` 改成 `CaculateSoftLogitsGrad` 吧

2024-10-31 03:14 UTC, GuoxiaWang commented on paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
> +    phi::DenseTensor is_ignore;
`phi::DenseTensor is_ignore;` 放到下面 `if (C > 1) {` 里面去，把作用缩小。

2024-10-31 03:20 UTC, tianhaodongbd commented on paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
> +__global__ void CaculateLogitsGrad(T* logits_grad,
done

2024-10-31 03:20 UTC, tianhaodongbd commented on paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu
> +    phi::DenseTensor is_ignore;
done

2024-11-01 07:29 UTC, luotao1 approved these changes
LGTM for Paddle_enforce

2024-11-01 07:59 UTC, GuoxiaWang approved these changes

2024-11-01 08:00 UTC, merged