【Paddle Tensor No.2】新增 Tensor.__rfloordiv__	复用已有接口 Tensor.__floordiv__
PaddlePaddle/Paddle pull request #69222
Opened 2024-11-07 06:51 UTC by enkilee

### PR Category

User Experience

### PR Types

New features

### Description

- https://github.com/PaddlePaddle/Paddle/issues/69082
Paddle Tensor 规范化: 新增 Tensor.__rfloordiv__	复用已有接口 Tensor.__floordiv__

2024-11-08 05:25 UTC, HydrogenSulfate requested changes
感谢提交PR，有几点建议

2024-11-08 05:25 UTC, HydrogenSulfate commented on paddle/fluid/pybind/eager_math_op_patch.cc
pybind这一层级应该调的同一个接口吧？复用是不是只需要在python层转发就行了？

2024-11-08 05:25 UTC, HydrogenSulfate commented on test/legacy_test/test_math_op_patch_pir.py
除了这个文件，还需要在`test/legacy_test/test_math_op_patch.py`里添加单测动态图dygraph的单测

2024-11-08 09:15 UTC, enkilee commented on paddle/fluid/pybind/eager_math_op_patch.cc
收到

2024-11-08 09:16 UTC, enkilee commented on test/legacy_test/test_math_op_patch_pir.py
收到

2024-11-11 06:05 UTC, HydrogenSulfate commented on paddle/fluid/pybind/eager_math_op_patch.cc
> rpow这些，都是在c这边，第3步进行的，这里不用改吗？

哦对，这里还是按照已有的规则加到pybind里比较好~

2024-11-11 07:35 UTC, HydrogenSulfate commented
@enkilee Coverage这个CI需要麻烦合并一下最新的上游develop代码

2024-11-11 08:10 UTC, enkilee commented
收到

2024-11-12 02:31 UTC, HydrogenSulfate approved these changes
LGTM

2024-11-12 02:31 UTC, merged