【Paddle Tensor No.3】新增 Tensor.__rmod__，复用已有接口 Tensor.__mod__
PaddlePaddle/Paddle pull request #69231
Opened 2024-11-07 13:43 UTC by PolaKuma

### PR Category
User Experience

### PR Types
New features

### Description
Paddle Tensor 规范化：新增 `Tensor.__rmod__`，复用已有接口 `Tensor.__mod__`

2024-11-08 05:22 UTC, HydrogenSulfate requested changes
感谢提交PR，有几点建议

2024-11-08 05:22 UTC, HydrogenSulfate commented on paddle/fluid/pybind/eager_math_op_patch.cc
这个文件应该不用新增代码吧，因为到pybind这一层仍然调的还是`tensor__rmod__method`，复用`Tensor.__mod__`应该在python层进行转发

2024-11-08 05:22 UTC, HydrogenSulfate commented on test/legacy_test/test_math_op_patch_pir.py
除了这个文件，还需要在`test/legacy_test/test_math_op_patch.py`里添加单测动态图dygraph的单测

2024-11-08 09:04 UTC, PolaKuma commented on paddle/fluid/pybind/eager_math_op_patch.cc
感谢指正！但好像加减乘除的反向运算都是在pybind这一层写`tensor__xxx__method`，想统一所以就在这新增了`tensor__rmod__method`。

2024-11-08 09:06 UTC, HydrogenSulfate commented on paddle/fluid/pybind/eager_math_op_patch.cc
> 感谢指正！但好像加减乘除的反向运算都是在pybind这一层写`tensor__xxx__method`，想统一所以就在这新增了`tensor__rmod__method`。

哦哦那也可以

2024-11-08 09:06 UTC, HydrogenSulfate commented on paddle/fluid/pybind/eager_math_op_patch.cc
> 感谢指正！但好像加减乘除的反向运算都是在pybind这一层写`tensor__xxx__method`，想统一所以就在这新增了`tensor__rmod__method`。

上面的注释也同步更新一下

2024-11-08 11:46 UTC, PolaKuma commented on paddle/fluid/pybind/eager_math_op_patch.cc
OK

2024-11-08 11:46 UTC, PolaKuma commented on test/legacy_test/test_math_op_patch_pir.py
收到

2024-11-11 09:15 UTC, HydrogenSulfate commented
@PolaKuma 麻烦合并一下上游的最新代码，有一个会导致PR-CI-Coverage挂掉的BUG已经修复了

2024-11-12 02:31 UTC, HydrogenSulfate approved these changes
LGTM

2024-11-12 02:31 UTC, merged