【Paddle Tensor No.13】: 新增paddle.positive,新增Tensor.__pos__
PaddlePaddle/Paddle pull request #69256
Opened 2024-11-08 13:50 UTC by MrXnneHang

PR Category
User Experience

PR Types
New features

Description
新增paddle.positive,Tensor.pos,用于对Tensor进行正号操作。

2024-11-09 03:46 UTC, MrXnneHang commented
![Snipaste_2024-11-09_11-39-40](https://github.com/user-attachments/assets/d95a26e0-8f50-4832-ac64-f311a48739fe)

我注意到pytorch的positive似乎是在算子层面上实现的，paddle是否也有必要这么做。

2024-11-11 02:54 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +    return x.clone()
这里return x.clone()的原因是？

2024-11-11 06:13 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +    return x.clone()
竞品torch也是直接返回输入即可，不需要进行clone()，
![image](https://github.com/user-attachments/assets/78ab5803-cd9d-423f-b987-3bcefe32ef75)

2024-11-11 06:14 UTC, HydrogenSulfate requested changes

2024-11-11 06:14 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +    return x.clone()
```suggestion
    # Check if the input tensor is of bool type and raise an error
    if x.dtype == paddle.bool:
        raise ValueError("The `+` operator, on a bool tensor is not supported.")
    return x
```

2024-11-11 06:35 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +    return x.clone()
好的，是我最初对静态图计算的理解有点问题。

2024-11-11 18:10 UTC, SigureMo reviewed
`python/paddle/tensor/tensor.prototype.pyi` `__neg__` 附近也补一个 `__pos__` 吧

2024-11-11 18:10 UTC, SigureMo commented on python/paddle/tensor/logic.py
> +        raise ValueError("The `+` operator, on a bool tensor is not supported.")
```suggestion
        raise TypeError("The `+` operator, on a bool tensor is not supported.")
```

用 `TypeError` 吧？

2024-11-11 18:10 UTC, SigureMo commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
这里没有 kernel，应该没有任何 dtype 限制？

2024-11-12 00:02 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
我单测只加了这些，不过从代码看确实只有Bool不行。

2024-11-12 00:03 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +        raise ValueError("The `+` operator, on a bool tensor is not supported.")
ok

2024-11-12 02:35 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
> Member

这里需要对bool进行限制，这是一个逻辑值，没有正负运算的概念，参考：
![image](https://github.com/user-attachments/assets/8b3fd69b-cd7c-48ef-9f06-660d8abf265b)

2024-11-12 02:52 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
我用raise TypeError是否可以。或者有更好的方法

2024-11-12 02:53 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
> 我用raise TypeError是否可以。或者有更好的方法

可以的，这里就用TypeError好了

2024-11-12 03:00 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +                    float16, float32, float64, int32, or int64.
https://github.com/PaddlePaddle/Paddle/pull/69256/commits/b2a83618fe78db2791e4bac6457b7573dd947bad

2024-11-12 06:02 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240530/u1f3b6/u1f3b6_u1f43e.png" width="14" alt="🐾"/>

2024-11-12 06:28 UTC, XiaoguangHu01 approved these changes
LGTM

2024-11-12 06:40 UTC, HydrogenSulfate approved these changes

2024-11-12 06:40 UTC, merged

2024-11-14 06:37 UTC, HydrogenSulfate commented
新增的接口`paddle.positive`麻烦在中文API文档(<https://github.com/PaddlePaddle/docs>)中也同步添加一下对应的文档信息，感谢~

2024-11-14 07:07 UTC, MrXnneHang commented
好的

2024-11-15 05:54 UTC, HydrogenSulfate commented on python/paddle/tensor/logic.py
> +def positive(x: Tensor) -> Tensor:
这个函数能否移动到`python/paddle/tensor/math.py`里？我觉得放在`logic.py`里不太合适，因为`logic.py`里面都是与布尔逻辑判断相关的，而`math.py`有一个和`positive`对应的`paddle.neg`函数

2024-11-15 06:10 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +def positive(x: Tensor) -> Tensor:
可以，我再提一个PR.

2024-11-15 08:46 UTC, MrXnneHang commented on python/paddle/tensor/logic.py
> +def positive(x: Tensor) -> Tensor:
- #69425