【SCU】【Paddle Tensor No.24】新增 `paddle.matrix_transpose`, `paddle.linalg.matrix_transpose`，复用已有接口 `paddle.transpose`
PaddlePaddle/Paddle pull request #69301
Opened 2024-11-11 14:47 UTC by PolaKuma

### PR Category
User Experience

### PR Types
New features

### Description
Paddle Tensor 规范化：新增 `paddle.matrix_transpose`, `paddle.linalg.matrix_transpose`，复用已有接口 `paddle.transpose`

2024-11-12 06:09 UTC, HydrogenSulfate requested changes
感谢提交PR，docstring可以修改一下

2024-11-12 06:09 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +            >>> print(x_transposed_np.shape)
此处应该展示动态图的样例代码，而不是静态图的吧？

2024-11-12 13:50 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +            (2, 5, 3)
```suggestion
            [2, 5, 3]
```

2024-11-13 05:54 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +    return paddle.transpose(x, perm)
可以复用Tensor.mT接口：
```suggestion
    return x.mT
```

2024-11-14 02:48 UTC, HydrogenSulfate approved these changes
LGTM

2024-11-14 03:00 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20230127/u1f31f/u1f31f_u1f43e.png" width="14" alt="🐾"/>

2024-11-14 06:39 UTC, HydrogenSulfate commented
新增的接口`paddle.linalg.matrix_transpose`麻烦在中文API文档(<https://github.com/PaddlePaddle/docs>)中也同步添加一下对应的文档信息，感谢~

2024-11-14 08:52 UTC, XiaoguangHu01 approved these changes
LGTM

2024-11-14 09:04 UTC, merged

2024-11-14 09:26 UTC, PolaKuma commented
> 新增的接口`paddle.linalg.matrix_transpose`麻烦在中文API文档(https://github.com/PaddlePaddle/docs)中也同步添加一下对应的文档信息，感谢~

好的好的～

2024-11-28 06:14 UTC, HydrogenSulfate commented
@PolaKuma 还麻烦在Paddle/python/paddle/tensor/__init__.py里加一下`matrix_transpose`