【SCU】【Paddle Tensor No.16】新增 paddle.e, 复用math.e
PaddlePaddle/Paddle pull request #69470
Opened 2024-11-18 10:41 UTC by ndyysheep

### PR Category

User Experience

### PR Types

New features
### Description

aaa

2024-11-18 12:51 UTC, HydrogenSulfate commented on test/legacy_test/test_e_op
1. 文件后缀.py呢？
2. 建议文件名叫做: `test_constant.py`

2024-11-18 12:51 UTC, HydrogenSulfate requested changes

2024-11-18 12:51 UTC, HydrogenSulfate commented on python/paddle/__init__.py
> +    'e',
按照字典序排列，e不应该放在开头位置

2024-11-19 05:18 UTC, ndyysheep reviewed
修改了__all__申明中的顺序和文件名称

2024-11-19 06:31 UTC, HydrogenSulfate commented
提交代码之前请安装pre-commit，否则PR-CI-Codestyle-Check无法通过
![image](https://github.com/user-attachments/assets/2cd3784e-5498-4f39-98a7-21bf0982d8f9)

2024-11-19 09:09 UTC, ndyysheep reviewed
aaa

2024-11-19 11:07 UTC, HydrogenSulfate commented
> aaa



> aaa

![image](https://github.com/user-attachments/assets/754fc12f-3f75-414c-b684-14a09b444bf4)
在 Paddle/ 目录下，执行：`pre-commit run --all-files`，否则
![image](https://github.com/user-attachments/assets/af8fc5d0-e0c8-4de0-b9b9-2a5ba1f59b60)
无法通过

2024-11-19 11:16 UTC, closed without merging