【SCU】【Paddle Tensor No.25】新增`paddle.vecdot` , `paddle.linalg.vecdot`，复用函数`paddle.linalg.dot`
PaddlePaddle/Paddle pull request #69477
Opened 2024-11-18 11:56 UTC by PolaKuma

### PR Category
User Experience

### PR Types
New features

### Description
Paddle Tensor 规范化：新增`paddle.vecdot` , `paddle.linalg.vecdot`，复用函数`paddle.linalg.dot`（实现功能一样）

注：paddle.linalg.dot还缺doc文档，以及vecdot文档后续分给另外报名那个同学完成～

2024-11-18 13:02 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +    return dot(x, y)
参考API规范定义，vecdot应该是逐元素乘法后再在axis轴上求和：<https://data-apis.org/array-api/latest/API_specification/generated/array_api.vecdot.html#array_api.vecdot>
所以可以参考如下实现（复用乘法和sum）
<https://github.com/pytorch/pytorch/blob/main/torch/_refs/linalg/__init__.py#L307>

2024-11-18 13:02 UTC, HydrogenSulfate commented on test/legacy_test/test_dot_op.py
1. 这是新增的API，不是OP，参考这几个文件写一下单测
2. 文件名建议改成test_linalg_vecdot.py

2024-11-18 17:29 UTC, PolaKuma commented on python/paddle/tensor/linalg.py
> +    return dot(x, y)
omg sry，已修改，谢谢佬更正！

2024-11-19 05:46 UTC, HydrogenSulfate requested changes

2024-11-19 05:46 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +
再补充几个单测：
1. 类型提升1：f32+fp64-->fp64
2. 类型提升2：fp32/64+c32/64 --> c32/64
3. 复数类型数据（需要在复数上运算才能验证x.conj()这条语句的正确性）
4. 形状广播测试：两个0-D Tensor、两个1-D Tenosr，0-D+N-D、1-D+N-D、N-D+N-D（广播）

2024-11-19 05:46 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +            y_tensor = paddle.to_tensor(self.y, place=place)
```suggestion
            x_tensor = paddle.to_tensor(self.x, dtype=self.dtype, place=place)
            y_tensor = paddle.to_tensor(self.y, dtype=self.dtype, place=place)
```

2024-11-19 05:46 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +    Parameters:
```suggestion
    Args:
```

2024-11-19 05:46 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +        y (Tensor): The second input tensor, which must have the same shape and dtype as tensor `x` except possibly at the specified `axis`.
1. x和y的维数可以是任意的，不一定必须是1-D或2-D，0-D也行
2. 二者形状也不一定要相同，能够进行广播即可

2024-11-19 05:46 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +        name (str|None, optional): An optional name for the operation. Default is None. Useful for debugging.
这个name的描述很奇怪啊，是参考哪里的？建议跟其他API里的name描述保持一致

2024-11-19 06:49 UTC, PolaKuma commented on test/legacy_test/test_linalg_vecdot.py
> +
> 再补充几个单测：
> 
> 1. 类型提升1：f32+fp64-->fp64
> 2. 类型提升2：fp32/64+c32/64 --> c32/64
> 3. 复数类型数据（需要在复数上运算才能验证x.conj()这条语句的正确性）
> 4. 形状广播测试：两个0-D Tensor、两个1-D Tenosr，0-D+N-D、1-D+N-D、N-D+N-D（广播）

加惹

2024-11-20 08:41 UTC, HydrogenSulfate commented
麻烦解决一下conflict

2024-11-20 08:42 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +    )
不用手动broadcast，因为Tensor的运算符是自带广播的

2024-11-20 08:57 UTC, PolaKuma commented on python/paddle/tensor/linalg.py
> +    )
噢噢原来如此，我删掉了，谢谢佬！

2024-11-21 09:24 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +            paddle.vecdot(x, y, axis=-1)
这个单测需要跳过XPU：
``` py
@unittest.skipIf(
    core.is_compiled_with_xpu(),
    "Skip XPU for not support uniform(dtype=int)",
)
```

2024-11-21 09:24 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +class VecDotTestCaseComplex(unittest.TestCase):
这个类跳过XPU：
``` py
@unittest.skipIf(
    core.is_compiled_with_xpu(),
    "Skip XPU for not support complex",
)
```

2024-11-21 09:24 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +class VecDotTestCaseTypePromotion2(unittest.TestCase):
同上，跳过XPU，
``` py
@unittest.skipIf(
    core.is_compiled_with_xpu(),
    "Skip XPU for not support complex",
)
```

2024-11-21 09:58 UTC, PolaKuma commented on test/legacy_test/test_linalg_vecdot.py
> +class VecDotTestCaseTypePromotion2(unittest.TestCase):
已加

2024-11-21 10:59 UTC, HydrogenSulfate commented
建议不要在网页上编辑，还是本地经过pre-commit比较好呢，
![image](https://github.com/user-attachments/assets/ef502cfb-dc77-437c-b80d-c9c66ef79086)

2024-11-21 12:02 UTC, PolaKuma commented
> 建议不要在网页上编辑，还是本地经过pre-commit比较好呢， ![image](https://private-user-images.githubusercontent.com/23737287/388475732-ef502cfb-dc77-437c-b80d-c9c66ef79086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTA3ODksIm5iZiI6MTczMjE5MDQ4OSwicGF0aCI6Ii8yMzczNzI4Ny8zODg0NzU3MzItZWY1MDJjZmItZGM3Ny00MzdjLWI4MGQtYzljNjZlZjc5MDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEyMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNDZlOGE4NWQ1M2JkMzFkMjE3NGM5NWQzNzdjNDczZDAxOWRhZTdlMjYyZDU4YWUxNWYyMTkxY2VhZWYxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JlDJKBgO7ezGHvWzK_ePbyJr_iD3FVkfARx0zchnTw8)

好咧好咧！现在codestyle过了，感谢感谢！

2024-11-22 05:20 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +class VecDotTestCaseTypePromotion2(unittest.TestCase):
> 已加

这里是不是忘记加了？
![image](https://github.com/user-attachments/assets/e7719536-f139-4904-9a10-fdcc59dbdfe0)

2024-11-22 05:22 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +               [14.0, 77.0])
看下样例代码的输出的空格缩进是否与实际输出完全一致：
![image](https://github.com/user-attachments/assets/8fe2d74a-8a56-43a0-a448-bcc5361d6cf3)

2024-11-22 08:56 UTC, PolaKuma commented
@HydrogenSulfate 应该可以了，老师您再看看ww

2024-11-22 10:34 UTC, HydrogenSulfate commented on test/legacy_test/test_linalg_vecdot.py
> +    def test_float64_complex64_promotion(self):
这个也是，所有complex类型的都加上对xpu的skip，否则CI过不了

2024-11-25 12:38 UTC, HydrogenSulfate commented on python/paddle/tensor/linalg.py
> +            [14.0, 77.0])
样例代码的输出部分，缩进修改一下，不然example code检测挂了：
![image](https://github.com/user-attachments/assets/7c5b84da-8801-4758-b0d5-2cf29f1ef6f6)

2024-11-26 03:52 UTC, HydrogenSulfate commented
@PolaKuma 注意文档格式：尤其是缩进空格和末尾的小数点，建议手动运行一下样例代码，然后把终端里的输出粘贴上去
![image](https://github.com/user-attachments/assets/ab0a421c-9a79-48d8-aa0c-65e570220108)

2024-11-26 06:56 UTC, HydrogenSulfate commented
@PolaKuma 缩进空格也要相同

2024-11-26 07:05 UTC, PolaKuma commented
> @PolaKuma 缩进空格也要相同，32的"3"要跟上面的"s"对齐

我换一个例子好了🥲我本地跑都没问题呜呜

2024-11-27 06:19 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240206/u1fa82/u1fa82_u1f43e.png" width="14" alt="🐾"/>

2024-11-27 06:29 UTC, luotao1 approved these changes

2024-11-27 07:08 UTC, XiaoguangHu01 approved these changes
LGTM

2024-11-27 07:45 UTC, HydrogenSulfate approved these changes
LGTM

2024-11-27 07:45 UTC, merged