[CodeStyle][Typos]21,22,24
PaddlePaddle/Paddle pull request #69482
Opened 2024-11-18 16:14 UTC by rich04lin

### PR Category

### PR Types

### Description

2024-11-18 19:00 UTC, SigureMo commented
标题不合规范 or PR 描述不按模板来，一律不予 review

cc @MrXnneHang

2024-11-18 23:04 UTC, MrXnneHang commented
好

2024-11-19 03:07 UTC, MrXnneHang commented
![image](https://github.com/user-attachments/assets/6db2fa40-ba9c-4092-a6aa-ac7afcdd3a5a)

2024-11-19 05:20 UTC, MrXnneHang commented
```txt
[CodeStyle][Typos][A-[21,22,24]]
```

你写成这样吧，我去改一下 FAQ 标题示例，我不太会写正则...

2024-11-19 06:00 UTC, SigureMo commented
> [CodeStyle][Typos][A-[21-30]]

标题就写这？知道自己在干什么么？知道的话在标题里说明下

2024-11-19 06:06 UTC, rich04lin commented
> > [代码样式][错别字][A-[21-30]]
> 
> 标题就写这个？知道自己在么？知道的话在标题里说明下
[CodeStyle][Typos][A-[21,22,24]]
你写成这样吧，我去修改一下常见问题标题示例，我不太会写正则...他让我按这个对吗

2024-11-19 06:15 UTC, SigureMo commented
> 他让我按这个对吗

人家让你把前缀改成这个

2024-11-19 14:50 UTC, SigureMo reviewed
整体上下文理解能力还需要提升啊……

2024-11-19 14:50 UTC, SigureMo commented on _typos.toml
> +anc = 'anc'
下面的空行加回来

2024-11-19 14:50 UTC, SigureMo commented on paddle/cinn/operator_fusion/graph_transformer/search_algorithm.h
> +  auto along = SearchAlgorithm<Kind, GraphMatcher, GraphOperation>(graph);
```suggestion
  auto algo = SearchAlgorithm<Kind, GraphMatcher, GraphOperation>(graph);
```

自己看上下文，这不是 `SearchAlgorithm` 返回一个 `Algorithm` 吗？

2024-11-19 14:50 UTC, SigureMo commented on python/paddle/incubate/asp/supported_layer_list.py
> +    # for computing, Act( (W^T X^T)^T + b). Therefore, we have to prune log k dimension
```suggestion
    # for computing, Act( (W^T X^T)^T + b). Therefore, we have to prune along k dimension
```

从 71 行能看出来是 `along`

2024-11-19 14:50 UTC, SigureMo commented on python/paddle/static/quantization/post_training_quantization.py
> +        # The vars for along = KL or hist
```suggestion
        # The vars for algo = KL or hist
```

算法 KL

2024-11-19 14:50 UTC, SigureMo commented on test/cpp/phi/kernels/test_gpu_timer.cu
> +  Functor along2 = Along<1, 256, 8>;
```suggestion
  Functor algo0 = Algo<4, 256, 1024>;
  Functor algo1 = Algo<1, 256, 1024>;
  Functor algo2 = Algo<1, 256, 8>;
```

算法算法算法，`Along` 是什么鬼？

2024-11-19 14:50 UTC, SigureMo commented on test/dataset/imikolov_test.py
> +            'are banknote berlitz calloway centrust cluett fromstein '
这里不能修改，因为这里本来就不是有效词汇，需要将本文件在配置中 ignore 掉

参考 https://github.com/crate-ci/typos/issues/316#issuecomment-889836924

配置参考 https://github.com/crate-ci/typos/blob/master/docs/reference.md#config-fields 

可用 `files.ignore-files` 配置项

@MrXnneHang 可以在 Q&A 里提及，这种本身就是使用一些 typos 的字面量，整个文件可以 ignore

2024-11-19 14:50 UTC, SigureMo commented
CI 挂了，与修改相关，自己看下 CI 报错

2024-11-19 14:54 UTC, MrXnneHang commented on test/dataset/imikolov_test.py
> +            'are banknote berlitz calloway centrust cluett fromstein '
好。

2024-11-19 17:18 UTC, SigureMo commented on test/dataset/imikolov_test.py
> +            'are banknote berlitz calloway centrust cluett fromstein '
> aer[无效单词]

这个加到配置了吗？

2024-11-19 17:56 UTC, SigureMo requested changes
另外运行 typos 有一堆没修的

2024-11-19 17:56 UTC, SigureMo commented on _typos.toml
> +algo = "algo"
这是在干啥？

2024-11-19 18:07 UTC, rich04lin commented on _typos.toml
> +algo = "algo"
anc 和 algo都是缩写不需要修改

2024-11-19 18:13 UTC, SigureMo commented on _typos.toml
> +algo = "algo"
人家有把 algo 识别成 typo 吗？没有加在这干什么？

2024-11-19 18:20 UTC, SigureMo requested changes

2024-11-19 18:20 UTC, SigureMo commented on .gitignore
> +*aer*
恢复

在 `_typos.toml` 里加

```toml
[files]
extend-exclude = [
    "test/dataset/imikolov_test.py"
]
```

放在最上面

2024-11-20 03:47 UTC, MrXnneHang commented
你先等一等，应该需要等这个合入一下，可以先接其他的任务。
- #69530

2024-11-20 14:45 UTC, SigureMo submitted a review, later dismissed
漏了一大堆，我都改了，你不用动了

2024-11-21 02:30 UTC, luotao1 commented
下次1个PR可以少领几个，更容易快速合入

2024-11-21 06:09 UTC, SigureMo commented
……不是说了不用动了吗？

2024-11-21 06:11 UTC, rich04lin commented
> ……不是说了不用动了吗？

对不起，我把其他单词修改提交到这里了，撤回了

2024-11-21 06:14 UTC, SigureMo commented
仅这个任务，全部修改完需要改动 21 个文件，我之前都改完了，你全都覆盖掉了

2024-11-21 06:17 UTC, rich04lin commented
> 仅这个任务，全部修改完需要改动 21 个文件，我之前都改完了，你全都覆盖掉了

啊对不起，那还能撤回修改吗

2024-11-21 14:29 UTC, SigureMo commented
> 啊对不起，那还能撤回修改吗

不能，因为你 force push 了

自己改回来吧，我不管了

2024-11-22 05:19 UTC, closed without merging

2024-11-22 05:28 UTC, rich04lin commented
> > 啊对不起，那还能撤回修改吗
> 
> 不能，因为你 force push 了
> 
> 自己改回来吧，我不管了

老师可以重新开一个issue吗，我重新写

2024-11-22 05:33 UTC, MrXnneHang commented
你再新建一个分支然后改完push上来再PR即可。
这次少接几个。
不过你的仓库的 develop 分支被污染了，我建议你删掉重新fork。
可以看FAQ。

2024-11-22 05:36 UTC, rich04lin commented
> 你再新建一个分支然后改完push上来再PR即可。 这次少接几个。 不过你的仓库的 develop 分支被污染了，我建议你删掉重新fork。 可以看FAQ。
重新fork了，我重新写，谢谢老师