【SCU】【Paddle Tensor No.17、18】新增 paddle.nan, paddle.inf, 复用math.nan、math.inf
PaddlePaddle/Paddle pull request #69542
Opened 2024-11-20 07:05 UTC by kineast

### PR Category

### PR Types

### Description

2024-11-20 08:46 UTC, HydrogenSulfate commented on python/paddle/__init__.py
> +nan = math.nan
常量写到776行下面

2024-11-20 08:46 UTC, HydrogenSulfate commented on python/paddle/tensor/__init__.py
> +# from math import nan
无用注释删除

2024-11-20 08:47 UTC, HydrogenSulfate commented on python/paddle/__init__.py
>      'inf',
请不要删除已有常量newaxis

2024-11-20 09:26 UTC, luotao1 commented
17题已经合入了，标题请改一下
- https://github.com/PaddlePaddle/Paddle/pull/69464

2024-11-20 09:30 UTC, kineast commented
> 17题已经合入了，标题请改一下
> 
> * [【SCU】【Paddle Tensor No.17、20】新增 paddle.inf, paddle.newaxis, 复用math.inf、None #69464](https://github.com/PaddlePaddle/Paddle/pull/69464)

2024-11-20 11:02 UTC, HydrogenSulfate reviewed
和最新代码合并一下

2024-11-20 11:02 UTC, HydrogenSulfate commented on python/paddle/__init__.py
> +newaxis: None = None
删除newaxis

2024-11-20 11:02 UTC, HydrogenSulfate commented on test/legacy_test/test_constant_nan_inf.py
> +
删除inf的test

2024-11-20 11:03 UTC, HydrogenSulfate requested changes

2024-11-20 11:03 UTC, HydrogenSulfate commented on test/legacy_test/test_constant_nan_inf.py
单测放到`test/legacy_test/test_constant.py`文件下

2024-11-21 09:31 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240206/u1f9e9/u1f9e9_u1f43e.png" width="14" alt="🐾"/>

2024-11-21 10:43 UTC, HydrogenSulfate approved these changes
LGTM

2024-11-21 12:35 UTC, XiaoguangHu01 approved these changes
LGTM

2024-11-21 14:14 UTC, merged