add external memory demo
PaddlePaddle/Paddle pull request #696
Opened 2016-12-02 00:50 UTC by Haichao-Zhang

This PR includes an example implementation of an external memory network and example usage with a simple task.

2016-12-02 22:29 UTC, emailweixu requested changes

2016-12-02 22:29 UTC, emailweixu commented on demo/memnet/external_memory.py
> +                                     act = LinearActivation())
78 and 81 can be combinded as written as: memory_removed = self.external_memory - memory_remove.
See https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/tests/configs/math_ops.py

2016-12-02 22:29 UTC, emailweixu commented on demo/memnet/external_memory.py
> +        out_prod = out_prod_layer(norm_cosine_similarity_write, erase_vec, name="outer")
Creating a constant vector erase_vec for this is very ugly. A nicer way to do this is to enhance "repeat" layer to allow repeat in both directions, similar to "repmat" in matlat.

2016-12-02 22:29 UTC, emailweixu commented on demo/memnet/external_memory.py
> +        memory_output = mixed_layer(input = [identity_projection(input=memory_removed),
Using addto_layer can make this looks simpler.

2016-12-02 22:29 UTC, emailweixu commented on demo/memnet/external_memory.py
> +class ExternalMemory(object):
need to comment for the class, and its member functions.

2016-12-03 00:29 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +class ExternalMemory(object):
Comments have been added to both the class and member functions.

2016-12-03 00:30 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +        self.scale = 5
This has been corrected.

2016-12-03 00:30 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +                                boot_bias= ParamAttr(initial_std=0.01,
This has been updated.

2016-12-03 00:30 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +                                                  name='read_weight')
Similar issues have been addressed.

2016-12-03 00:30 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +                                     act = LinearActivation())
This part of the code has been updated using math_ops

2016-12-03 00:31 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +        memory_output = mixed_layer(input = [identity_projection(input=memory_removed),
Switch to addto_layer

2016-12-03 00:31 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +    def MakeConstantVector(self, vec_size, value, dummy_input):
Changed the function name following the convention.

2016-12-03 00:46 UTC, Haichao-Zhang commented on demo/memnet/external_memory.py
> +        out_prod = out_prod_layer(norm_cosine_similarity_write, erase_vec, name="outer")
Looking into the repeat layer currently.

2019-02-01 04:32 UTC, luotao1 commented
感谢您给PaddlePaddle贡献代码。由于Paddle V1/V2版本已不再维护，相关代码也已从develop分支上删除，因此关闭您的PR，欢迎您向Paddle最新版-Fluid贡献代码。
Thanks for contributing to PaddlePaddle! Since V1/V2 will not be maintained anymore, and related codes have been deleted from develop branch as well, we close this PR. Welcome to contribute to Fluid——the latest version of PaddlePaddle.

2019-02-01 04:32 UTC, closed without merging