[CodeStyle][Typos][A-[1-10]] Fix typo(Acceses、accessable、accesss、accoding、accurary、Accuarcy、actived、acitve、actualy、Actural、actural)
PaddlePaddle/Paddle pull request #69627
Opened 2024-11-22 07:51 UTC by fxy1699

### PR Category

User Experience

### PR Types

Devs

### Description

Fix:
- Acceses
- accessable
- aaccesss
- accoding
- accurary
- actived
- acitve
- actualy
- Actural/actural

Undo:
- Accuarcy 涉及API名称变动

2024-11-22 07:52 UTC, fxy1699 commented
#69575 查了一下没有找到好的解决办法只能重开了

2024-11-22 11:10 UTC, MrXnneHang commented
Accuarcy 是不是漏了

2024-11-22 11:25 UTC, fxy1699 commented
> Accuarcy 是不是漏了 你的`_typos.toml`漏删了一个

这个是没有修改的，涉及到API变动，删了typos不是会报错吗

2024-11-22 12:04 UTC, MrXnneHang commented
你在没有修改的那一行后面加一个注释`#Undo : Accuarcy`看看，让审核人判断保留与否。
如果保留，按照 FAQ 里面把那个文件忽略掉，然后把那个单词删掉。

2024-11-22 16:17 UTC, SigureMo commented
> 你在没有修改的那一行后面加一个注释#Undo : Accuarcy

https://github.com/PaddlePaddle/Paddle/pull/69558#discussion_r1850738775

这种情况不要加注释，直接移到上面

> Accuarcy 涉及API名称变动

不过 `AccuarcyCheckPass` 等均非公开 API，全部应该修改

2024-11-26 05:46 UTC, fxy1699 commented
> 按照下面那个方法改

已修改

2024-11-26 06:06 UTC, SigureMo requested changes

2024-11-26 06:06 UTC, SigureMo commented on _typos.toml
> -Accuarcy = 'Accuarcy'
这个 PR 改的不止这一个吧

2024-11-26 06:27 UTC, fxy1699 commented on _typos.toml
> -Accuarcy = 'Accuarcy'
抱歉merge的时候这部忘记保存了，已修改

2024-11-26 06:29 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20231113/u1f4a5/u1f4a5_u1f43e.png" width="14" alt="🐾"/>

2024-11-26 06:54 UTC, MrXnneHang approved these changes

2024-11-26 17:39 UTC, merged