[CodeStyle][Typos][A-[11-19]] Fix typos (befor, befores, begining,benfit,Betweent,betweeen,bindins)
PaddlePaddle/Paddle pull request #69640
Opened 2024-11-22 11:51 UTC by fangfangssj

**PR Category**

User Experience

**PR Types**

Devs

**Description**
Fix：
- befor
- befores
- begining
- benfit
- Betweent
- betweeen
- bindins

2024-11-23 07:53 UTC, MrXnneHang approved these changes

2024-11-23 08:37 UTC, SigureMo requested changes

2024-11-23 08:37 UTC, SigureMo commented on paddle/fluid/framework/new_executor/interpreter/dependency_builder.cc
>        for (auto behind_op : behinds) {
从语义上来看，这里 `befores` 表示的是复数个 before 的 OP，因此可以将其命名改为 `before_ops`，确保一致性，`behinds` 也改为 `behind_ops`

2024-11-23 09:51 UTC, fangfangssj commented on paddle/fluid/framework/new_executor/interpreter/dependency_builder.cc
>        for (auto behind_op : behinds) {
已修改

2024-11-23 09:53 UTC, SigureMo submitted a review, later dismissed
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240610/u2b50/u2b50_u1f43e.png" width="14" alt="🐾"/>

2024-11-23 14:30 UTC, SigureMo commented
#69650 重排了下配置顺序，麻烦解决下冲突

2024-11-23 15:07 UTC, fangfangssj commented
> #69650 重排了下配置顺序，麻烦解决下冲突

已解决

2024-11-23 15:08 UTC, SigureMo commented
没有解决冲突

2024-11-23 15:25 UTC, fangfangssj commented
> 没有解决冲突

您好，想问一下，我只能改成和最新的分支一样的吗，我想删除我已经修改过的部分，但是会报冲突的错误

2024-11-23 15:31 UTC, SigureMo commented
```bash
git checkout develop
git pull
git checkout fix-typos
git checkout develop -- _typos.toml
git commit -m 'restore `_typos.toml`'
# 重新修改 `_typos.toml`
git add _typos.toml
git commit -m 'update `_typos.toml`'
```

只是建议，自己判断是否应该这样做，出问题别找我，自己搜索解决

2024-11-23 15:45 UTC, SigureMo commented
实在不行你把 https://github.com/PaddlePaddle/Paddle/blob/develop/_typos.toml 的内容粘贴一下啊……

2024-11-23 15:54 UTC, fangfangssj commented
> 实在不行你把 https://github.com/PaddlePaddle/Paddle/blob/develop/_typos.toml 的内容粘贴一下啊……

我把内容换成和develop一样的是不会报冲突的，但我想把我改过的删除掉，一修改就会报错，
使用`git checkout develop -- _typos.toml`也没有作用

2024-11-23 15:58 UTC, SigureMo commented
> 我把内容换成和develop一样的是不会报冲突的，但我想把我改过的删除掉，一修改就会报错，

不懂，冲突解决是基础，自己学习下吧

2024-11-23 16:29 UTC, SigureMo approved these changes

2024-11-25 05:27 UTC, fangfangssj commented
@MrXnneHang 您好，想问一下PR-CI-APPROVAL没通过，需要别人APPROVAL的情况该怎么做呢

2024-11-25 06:18 UTC, MrXnneHang commented
就是字面意思，需要RD批准，耐心等待即可。

2024-11-25 09:30 UTC, merged