[CodeStyle][Typos][A-36] Fix typo(assigend、assined)
PaddlePaddle/Paddle pull request #69655
Opened 2024-11-23 16:37 UTC by mikemikimike

PR Category
User Experience

PR Types
Devs

Description
fit：
assigend
assined

2024-11-23 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=69655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=69655) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=69655) it.</sub>

2024-11-23 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=69655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=69655) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=69655) it.</sub>

2024-11-23 16:41 UTC, SigureMo submitted a review, later dismissed
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240530/u1f973/u1f973_u1f43e.png" width="14" alt="🐾"/>

2024-11-23 16:41 UTC, SigureMo commented
麻烦签署下 CLA

2024-11-23 16:52 UTC, SigureMo commented
PR 模板从哪 copy 的，完全不对，CI 过不了的

2024-11-23 17:31 UTC, mikemikimike commented
> PR 模板从哪 copy 的，完全不对，CI 过不了的

2024-11-23 17:32 UTC, mikemikimike commented
> PR 模板从哪 copy 的，完全不对，CI 过不了的

![image](https://github.com/user-attachments/assets/189d7cb4-d248-4eba-81ee-53e402379afd)
emmm已更正

2024-11-24 05:08 UTC, SigureMo commented
签一下 CLA 就能 merge 了

2024-11-24 11:59 UTC, mikemikimike commented
![Snipaste_2024-11-24_19-58-02](https://github.com/user-attachments/assets/deb04b67-3a61-4884-ab86-51e115b2f340)
![Snipaste_2024-11-24_19-58-20](https://github.com/user-attachments/assets/eda88bec-2e4a-4ea3-947a-ddf96251dc13)
已签署

2024-11-25 09:29 UTC, luotao1 commented
冲突了

2024-11-25 13:14 UTC, mikemikimike commented
已处理，应该是合并顺序导致的

2024-11-25 13:53 UTC, SigureMo commented
<img width="613" alt="image" src="https://github.com/user-attachments/assets/ae85678c-4104-4e3e-a526-6cb4a29c41cd">

这个 commit 是没有签署 CLA 的

可以考虑 rebase 修改之前 commit

2024-11-25 13:53 UTC, SigureMo requested changes

2024-11-25 13:53 UTC, SigureMo commented on _typos.toml
> +annotaion = 'annotaion'
冲突解决的不对

2024-11-26 01:04 UTC, mikemikimike commented
签署了不显示，很奇怪

2024-11-26 02:01 UTC, SigureMo commented
<img width="941" alt="image" src="https://github.com/user-attachments/assets/3389ebbe-4a1c-4479-9ce3-f296beee36c6">

> 签署了不显示，很奇怪

显示了啊，这里说用户 `strayscat` 是没有签署的，https://github.com/PaddlePaddle/Paddle/pull/69655#issuecomment-2498082820 也说解决方案了啊

2024-11-26 19:10 UTC, mikemikimike commented
#69741   之前提交的账户邮箱是虚拟的，请求更换pr

2024-11-26 19:30 UTC, closed without merging