【SCU】【Paddle Tensor No.3】新增 Tensor.__dlpack__
PaddlePaddle/Paddle pull request #69689
Opened 2024-11-25 11:37 UTC by SCUcookie

### PR Category

User Experience

### PR Types

New features

### Description

Paddle Tensor 规范化：新增 Tensor.__dlpack__

2024-11-25 12:33 UTC, HydrogenSulfate commented
提交代码前请安装pre-commit
![image](https://github.com/user-attachments/assets/dba4a36d-83f6-49ac-880f-d38784dfb17e)

2024-11-25 12:35 UTC, HydrogenSulfate commented on paddle/fluid/pybind/tensor.cc
> +          )DOC")
这个复用 paddle.to_dlpack即可，不用写C++代码，可以参考：<https://github.com/pytorch/pytorch/blob/main/torch/_tensor.py#L1565>

2024-11-26 00:42 UTC, SCUcookie commented on paddle/fluid/pybind/tensor.cc
> +          )DOC")
好的谢谢老师

2024-11-26 03:58 UTC, HydrogenSulfate requested changes

2024-11-26 03:58 UTC, HydrogenSulfate commented on python/paddle/__init__.py
> +    '__dlpack__',
__dlpack__是Tensor的方法，不是paddle模块下的函数

2024-11-26 03:58 UTC, HydrogenSulfate commented on python/paddle/tensor/tensor.prototype.pyi
> +    def __dlpack__(self) -> Any: ...
这个返回的是Any吗？应该是CapsuleType，参考`Paddle/python/paddle/utils/dlpack.py`

2024-11-26 03:58 UTC, HydrogenSulfate commented on python/paddle/utils/dlpack.py
不应该改动这个文件

2024-11-26 03:58 UTC, HydrogenSulfate commented on setup.py
> +from paddle.utils.dlpack import enable_dlpack
不应该改动这个文件

2024-11-26 03:58 UTC, HydrogenSulfate commented on third_party/pybind
不需要改pybind

2024-11-26 03:58 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack.py
`__dlpack__`作为Tensor的类方法，参考<https://github.com/PaddlePaddle/Paddle/blob/fa26020ed0d89702e546eeb4fafbf08602d6752d/python/paddle/base/dygraph/tensor_patch_methods.py#L1261>，https://github.com/PaddlePaddle/Paddle/pull/68192

2024-11-26 04:01 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack.py
> +        self.assertIsNotNone(dlpack_capsule)
只判断是不是None是不够的，需要将dlpack_capsule用paddle.from_dlpack重新转回Tensor，检测转换前的两个tensor里的值，以及`.data_ptr()`是不是一样的

2024-11-26 04:16 UTC, SCUcookie commented on test/legacy_test/test_dlpack.py
> +        self.assertIsNotNone(dlpack_capsule)
好的老师

2024-11-26 09:08 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +    @property
删除，`__dlpack__`不是一个属性，而是一个方法(函数)

2024-11-26 09:10 UTC, HydrogenSulfate commented on third_party/pybind
这个submodule不要修改

2024-11-27 09:24 UTC, HydrogenSulfate commented on third_party/pybind
这个文件记得还原回去

2024-11-27 09:24 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack.py
> +        self.assertEqual(tensor.data_ptr(), converted_tensor.data_ptr())
这个单测有两个问题：
1. 设备类型没有测试全，只测了当前默认设备。
2. 没有测试stream这个参数非None的情况

2024-11-28 07:42 UTC, closed without merging