[CodeStyle][Typos][C-[25-31]] Fix typos (cliping,clos,coalesc,coloumn,commericial,commiter,comparision)
PaddlePaddle/Paddle pull request #69695
Opened 2024-11-25 12:17 UTC by rich04lin

### PR Category

User Experience

### PR Types

Devs

### Description

Fix:

- cliping
- coalesc
- coloumn
-commericial
- commiter
- comparision

Undo:

- clos

2024-11-25 14:01 UTC, SigureMo requested changes

2024-11-25 14:01 UTC, SigureMo commented on _typos.toml
> +clos = 'clos'
不改需要说明理由

存量代码大多是 `cols`（`columns` 缩写）的错写，应该修改

2024-11-25 14:01 UTC, SigureMo commented on _typos.toml
> +#cliping = 'cliping'
删掉

2024-11-25 14:01 UTC, SigureMo commented on _typos.toml
> -annotaion = 'annotaion'
学习分支管理，这个 PR 不要包含上个 PR 的改动

2024-11-25 15:06 UTC, rich04lin commented on _typos.toml
> -annotaion = 'annotaion'
好滴

2024-11-25 18:42 UTC, SigureMo approved these changes
这个 PR 可以先这样，之后 PR 不允许出现之前 PR 的改动，不允许使用 develop 分支提 PR

2024-11-26 02:57 UTC, merged

2024-12-01 05:56 UTC, rich04lin commented on _typos.toml
> -annotaion = 'annotaion'
![q](https://github.com/user-attachments/assets/0635aed3-00ab-4e3e-b577-e69449aeaf92)
老师请问这个怎么解决

2024-12-01 06:22 UTC, SigureMo commented on _typos.toml
> -annotaion = 'annotaion'
不要修改 `third_party`，以及不要在之前不相关的 PR 回复问题，会打扰其他人