[XPU] fp16 for multinomial op
PaddlePaddle/Paddle pull request #69767
Opened 2024-11-27 10:25 UTC by houj04

### PR Category
Custom Device

### PR Types
New features

### Description
在PaddleNLP的较早版本中，由于`multinomial`算子不支持XPU下的float16数据类型，临时在组网代码中增加了一个`cast`操作，见：https://github.com/PaddlePaddle/PaddleNLP/pull/8787 。

本PR在主框架中，给`multinomial`算子增加float16数据类型的支持。但由于底层算子库只支持float32数据类型，因此方式是在算子绑定中，垫一个`cast`操作。

2024-11-28 05:41 UTC, houj04 commented on paddle/phi/kernels/xpu/multinomial_kernel.cc
> +  if (!replacement) {
这个if之内的代码全部来源于GPU的实现。单测里面有些case是预期挂掉并且抛出ValueError的，所以不加这段代码会导致单测跑不过，所以我从GPU抄过来了。

2024-11-28 09:18 UTC, gongweibao commented on paddle/phi/kernels/xpu/multinomial_kernel.cc
> +  if (!replacement) {
封个函数？免得两份到处改。

2024-11-28 09:23 UTC, gongweibao requested changes

2024-11-28 09:23 UTC, gongweibao commented on paddle/phi/kernels/xpu/multinomial_kernel.cc
> +  if (!replacement) {
改完了把PaddleNLP也删了吧。

2024-11-29 02:41 UTC, RuohengMa approved these changes
LGTM

2024-12-02 02:04 UTC, gongweibao approved these changes
LGTM

2024-12-02 02:04 UTC, merged