【SCU】【Paddle Tensor No.3】新增 Tensor.__dlpack__
PaddlePaddle/Paddle pull request #69781
Opened 2024-11-28 02:56 UTC by SCUcookie

### PR Category

User Experience

### PR Types

New features

### Description

Paddle Tensor 规范化：新增 `Tensor.__dlpack__`

2024-11-28 03:42 UTC, HydrogenSulfate commented
@SCUcookie 解决一下冲突

2024-11-28 04:11 UTC, SCUcookie commented
> @SCUcookie 解决一下冲突

已解决

2024-11-28 05:42 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +            )
为什么只能支持"gpu"类型？这里应该不用这个判断吧？

2024-11-28 05:42 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +            )
```suggestion
                "Can't get __dlpack__ from a Tensor that requires gradients, "
                "use tensor.detach() if gradients are not required."
            )
```

2024-11-28 05:42 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +            )
```suggestion
            raise AttributeError(
                "Can't get __dlpack__ from sparse tensor. "
                "Use Tensor.to_dense() to convert to a dense tensor first."
            )
```

2024-11-28 05:42 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +                    stream = paddle.device.cuda.default_stream()
```suggestion
                if stream == 1 and not paddle.device.is_compiled_with_rocm():
                    stream = paddle.device.cuda.default_stream()
                elif stream == 0 and paddle.device.is_compiled_with_rocm():
                    stream = paddle.device.cuda.default_stream()
```

2024-11-28 05:42 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +        return paddle.utils.dlpack.to_dlpack(self)
```suggestion
        return paddle.to_dlpack(self)
```

2024-11-28 05:47 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack.py
> +            self.assertTrue(paddle.equal_all(tensor_gpu, converted_tensor_gpu))
不同设备的测试代码可以合并成同一个，他们只有place的区别，参考：
https://github.com/PaddlePaddle/Paddle/blob/9e405f7d04565f7e8ff2dfbcd840716f0f1566bf/test/legacy_test/test_index_select_strided.py#L28-L37

``` py
places = []

for place in places:
    x = paddle.to_tensor(xxx, place=place)
    // write test code below
```

2024-11-28 05:47 UTC, SCUcookie commented on test/legacy_test/test_dlpack.py
> +            self.assertTrue(paddle.equal_all(tensor_gpu, converted_tensor_gpu))
好的

2024-11-28 05:50 UTC, SCUcookie commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +            )
好的

2024-11-28 05:51 UTC, HydrogenSulfate requested changes
感觉单测可以直接使用：`Paddle/test/legacy_test/test_dlpack.py`，把里面的`paddle.to_dlpack`换成`Tensor.__dlpack__()`即可

2024-11-28 06:29 UTC, SCUcookie commented
> 感觉单测可以直接使用：`Paddle/test/legacy_test/test_dlpack.py`，把里面的`paddle.to_dlpack`换成`Tensor.__dlpack__()`即可

test_dlpack里所有的都要改吗

2024-11-28 06:35 UTC, HydrogenSulfate commented
> > 感觉单测可以直接使用：`Paddle/test/legacy_test/test_dlpack.py`，把里面的`paddle.to_dlpack`换成`Tensor.__dlpack__()`即可
> 
> test_dlpack里所有的都要改吗

哦可能我没说清楚，我的意思是不修改test_dlpack.py，而是可以直接复制test_dlpack里的所有单元测试到你这个PR的单测里

2024-11-28 06:40 UTC, SCUcookie commented
> > > 感觉单测可以直接使用：`Paddle/test/legacy_test/test_dlpack.py`，把里面的`paddle.to_dlpack`换成`Tensor.__dlpack__()`即可
> > 
> > 
> > test_dlpack里所有的都要改吗
> 
> 哦可能我没说清楚，我的意思是不修改test_dlpack.py，而是可以直接复制test_dlpack里的所有单元测试到你这个PR的单测里，并且把全部to_dlpack的调用改成__dlpack__调用就行

好的

2024-11-28 07:02 UTC, SCUcookie commented
> > > 感觉单测可以直接使用：`Paddle/test/legacy_test/test_dlpack.py`，把里面的`paddle.to_dlpack`换成`Tensor.__dlpack__()`即可
> > 
> > 
> > test_dlpack里所有的都要改吗
> 
> 哦可能我没说清楚，我的意思是不修改test_dlpack.py，而是可以直接复制test_dlpack里的所有单元测试到你这个PR的单测里，并且把全部to_dlpack的调用改成__dlpack__调用就行

这个所有都提示找不到Tensor

2024-11-28 07:34 UTC, HydrogenSulfate commented
> test_dlpack.py

能看一下具体报错信息吗？test_dlpack.py

2024-11-28 07:38 UTC, SCUcookie commented
> > test_dlpack.py
> 
> 能看一下具体报错信息吗？test_dlpack.py

就是如果把test_dlpack的内容复制到新的test文件里然后改成Tensor.__dlpack__()每一个都会报错：
Traceback (most recent call last):
  File "/root/Paddle/test/legacy_test/test___dlpack__.py", line 255, in test_to_dlpack_strides_consistency
    dlpack_v2 = Tensor.__dlpack__()(x_strided)
NameError: name 'Tensor' is not defined

2024-11-28 07:41 UTC, HydrogenSulfate commented
> > > test_dlpack.py
> > 
> > 
> > 能看一下具体报错信息吗？test_dlpack.py
> 
> 就是如果把test_dlpack的内容复制到新的test文件里然后改成Tensor.**dlpack**()每一个都会报错： Traceback (most recent call last): File "/root/Paddle/test/legacy_test/test___dlpack__.py", line 255, in test_to_dlpack_strides_consistency dlpack_v2 = Tensor.**dlpack**()(x_strided) NameError: name 'Tensor' is not defined

不好意思我没表述清楚，`Tensor`需要改成你实际的tensor名字，而不是把`Tensor`这六个字符也复制过去 😢

2024-11-28 07:43 UTC, SCUcookie commented
> > > > test_dlpack.py
> > > 
> > > 
> > > 能看一下具体报错信息吗？test_dlpack.py
> > 
> > 
> > 就是如果把test_dlpack的内容复制到新的test文件里然后改成Tensor.**dlpack**()每一个都会报错： Traceback (most recent call last): File "/root/Paddle/test/legacy_test/test___dlpack__.py", line 255, in test_to_dlpack_strides_consistency dlpack_v2 = Tensor.**dlpack**()(x_strided) NameError: name 'Tensor' is not defined
> 
> 不好意思我没表述清楚，`Tensor`需要改成你实际的tensor名字，而不是把`Tensor`这六个字符也复制过去 😢

哦哦哦我理解错了

2024-11-28 07:44 UTC, HydrogenSulfate commented
> > > > test_dlpack.py
> > > 
> > > 
> > > 能看一下具体报错信息吗？test_dlpack.py
> > 
> > 
> > 就是如果把test_dlpack的内容复制到新的test文件里然后改成Tensor.**dlpack**()每一个都会报错： Traceback (most recent call last): File "/root/Paddle/test/legacy_test/test___dlpack__.py", line 255, in test_to_dlpack_strides_consistency dlpack_v2 = Tensor.**dlpack**()(x_strided) NameError: name 'Tensor' is not defined
> 
> 不好意思我没表述清楚，`Tensor`需要改成你实际的tensor名字，而不是把`Tensor`这六个字符也复制过去 😢

举个例子，比如你复制过来的写法是： `dl_pack = paddle.utils.dlpack.to_dlpack(x)`，那么需要将其改成`dl_pack = x.__dlpack__()`，这样才能调用`Tensor.__dlpack__`这个方法

2024-11-28 07:45 UTC, SCUcookie commented
> > > > > test_dlpack.py
> > > > 
> > > > 
> > > > 能看一下具体报错信息吗？test_dlpack.py
> > > 
> > > 
> > > 就是如果把test_dlpack的内容复制到新的test文件里然后改成Tensor.**dlpack**()每一个都会报错： Traceback (most recent call last): File "/root/Paddle/test/legacy_test/test___dlpack__.py", line 255, in test_to_dlpack_strides_consistency dlpack_v2 = Tensor.**dlpack**()(x_strided) NameError: name 'Tensor' is not defined
> > 
> > 
> > 不好意思我没表述清楚，`Tensor`需要改成你实际的tensor名字，而不是把`Tensor`这六个字符也复制过去 😢
> 
> 举个例子，比如你复制过来的写法是： `dl_pack = paddle.utils.dlpack.to_dlpack(x)`，那么需要将其改成`dl_pack = x.__dlpack__()`，这样才能调用`Tensor.__dlpack__`这个方法

我以为是要求实现Tensor.__dlpack__那种，忘了这个了，谢谢老师

2024-11-28 07:49 UTC, HydrogenSulfate commented
提交代码一定要用pre-commit，否则还得重新过CI：
![image](https://github.com/user-attachments/assets/552bf483-9bc1-47b0-b479-78b8a086bdfd)

2024-11-28 08:05 UTC, SCUcookie commented
> 提交代码一定要用pre-commit，否则还得重新过CI： ![image](https://private-user-images.githubusercontent.com/23737287/390689072-552bf483-9bc1-47b0-b479-78b8a086bdfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODEzNDYsIm5iZiI6MTczMjc4MTA0NiwicGF0aCI6Ii8yMzczNzI4Ny8zOTA2ODkwNzItNTUyYmY0ODMtOWJjMS00N2IwLWI0NzktNzhiOGEwODZiZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOTMzMmU2YWMzZjdmMjkxNjRjZDE2ODZhMmQxNTc0MTI3ZTFlMzQwZTcxOTcyZjQwZTRhOTUzYTVkM2IyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5_MRtB6z36KTP6WvrjnsXxeVUqH39Pz5XistP-naOg)

好的老师，这一版还没改完点成push了，请老师先不用管

2024-11-28 08:34 UTC, SCUcookie commented
> 提交代码一定要用pre-commit，否则还得重新过CI： ![image](https://private-user-images.githubusercontent.com/23737287/390689072-552bf483-9bc1-47b0-b479-78b8a086bdfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODMxMzUsIm5iZiI6MTczMjc4MjgzNSwicGF0aCI6Ii8yMzczNzI4Ny8zOTA2ODkwNzItNTUyYmY0ODMtOWJjMS00N2IwLWI0NzktNzhiOGEwODZiZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTA0MmVlMTBhZTgxOGZlMzk3NGYxYjM0YWUzZDUwYWU4NzFjZWZkYTNjODJhYmUxMGExMWRlNTEwYmUxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWOJwUqA0MKbifXX1qQADbD4vy5KMJsftsMBYC3uAH0)

![image](https://github.com/user-attachments/assets/f624fe02-d999-42d4-b569-445cc19bdb23)
![image](https://github.com/user-attachments/assets/c095b5d7-4b08-4890-8f37-a62a2643abce)
![image](https://github.com/user-attachments/assets/071a0793-c337-4d25-ac0f-6862ef2b63bc)
老师这个文件没改不知道为什么就突然报错了

2024-11-28 09:12 UTC, HydrogenSulfate commented
> > 提交代码一定要用pre-commit，否则还得重新过CI： ![image](https://private-user-images.githubusercontent.com/23737287/390689072-552bf483-9bc1-47b0-b479-78b8a086bdfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODMxMzUsIm5iZiI6MTczMjc4MjgzNSwicGF0aCI6Ii8yMzczNzI4Ny8zOTA2ODkwNzItNTUyYmY0ODMtOWJjMS00N2IwLWI0NzktNzhiOGEwODZiZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTA0MmVlMTBhZTgxOGZlMzk3NGYxYjM0YWUzZDUwYWU4NzFjZWZkYTNjODJhYmUxMGExMWRlNTEwYmUxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWOJwUqA0MKbifXX1qQADbD4vy5KMJsftsMBYC3uAH0)
> 
> ![image](https://private-user-images.githubusercontent.com/103986681/390703363-f624fe02-d999-42d4-b569-445cc19bdb23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzMzYzLWY2MjRmZTAyLWQ5OTktNDJkNC1iNTY5LTQ0NWNjMTliZGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGQ0N2E1NjkyNzZmMDcxNzZlZDNmMTc3ZDUzYWNmYzE5MjcyMDgzNjQzYTU2NDdmNjkxZTgwM2UwMjEyNzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oAJFxz93_6iWSpSHfMTEIOvRaEOoLfxn3W4i3Rah7EE) ![image](https://private-user-images.githubusercontent.com/103986681/390703449-c095b5d7-4b08-4890-8f37-a62a2643abce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzNDQ5LWMwOTViNWQ3LTRiMDgtNDg5MC04ZjM3LWE2MmEyNjQzYWJjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODY1YmQ4ZTY3YmUzNDFhZTgzYjQyMjU4ZTgwMTI3NmIwNmExNjAzZWNmOWYxM2EzNWU3YzBhYjVhMzY3NWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vk1SZ2bxFr07QiR3dA0gtuYz1RyNfJHFmERZtXt-42s) ![image](https://private-user-images.githubusercontent.com/103986681/390703509-071a0793-c337-4d25-ac0f-6862ef2b63bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzNTA5LTA3MWEwNzkzLWMzMzctNGQyNS1hYzBmLTY4NjJlZjJiNjNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWU0NGEwNjhkZGIwNjRiOTFjNTNjNThmMDg5NTlhMGQ2YzA4MjUxOWVmYTI0ZjRmM2ZjZDZmYzhiMzhjMWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kiY9llObzpQsiyG2EzLBBy5jHRKDMNejKncZv56A-nQ) 老师这个文件没改不知道为什么就突然报错了

应该是有其他同学在这个文件里添加了`__dlpack_device__`的单测，然后你合并一下上游的develop分支就可以了应该

2024-11-28 09:14 UTC, SCUcookie commented
> > > 提交代码一定要用pre-commit，否则还得重新过CI： ![image](https://private-user-images.githubusercontent.com/23737287/390689072-552bf483-9bc1-47b0-b479-78b8a086bdfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODMxMzUsIm5iZiI6MTczMjc4MjgzNSwicGF0aCI6Ii8yMzczNzI4Ny8zOTA2ODkwNzItNTUyYmY0ODMtOWJjMS00N2IwLWI0NzktNzhiOGEwODZiZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTA0MmVlMTBhZTgxOGZlMzk3NGYxYjM0YWUzZDUwYWU4NzFjZWZkYTNjODJhYmUxMGExMWRlNTEwYmUxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qWOJwUqA0MKbifXX1qQADbD4vy5KMJsftsMBYC3uAH0)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103986681/390703363-f624fe02-d999-42d4-b569-445cc19bdb23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzMzYzLWY2MjRmZTAyLWQ5OTktNDJkNC1iNTY5LTQ0NWNjMTliZGIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGQ0N2E1NjkyNzZmMDcxNzZlZDNmMTc3ZDUzYWNmYzE5MjcyMDgzNjQzYTU2NDdmNjkxZTgwM2UwMjEyNzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oAJFxz93_6iWSpSHfMTEIOvRaEOoLfxn3W4i3Rah7EE) ![image](https://private-user-images.githubusercontent.com/103986681/390703449-c095b5d7-4b08-4890-8f37-a62a2643abce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzNDQ5LWMwOTViNWQ3LTRiMDgtNDg5MC04ZjM3LWE2MmEyNjQzYWJjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODY1YmQ4ZTY3YmUzNDFhZTgzYjQyMjU4ZTgwMTI3NmIwNmExNjAzZWNmOWYxM2EzNWU3YzBhYjVhMzY3NWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vk1SZ2bxFr07QiR3dA0gtuYz1RyNfJHFmERZtXt-42s) ![image](https://private-user-images.githubusercontent.com/103986681/390703509-071a0793-c337-4d25-ac0f-6862ef2b63bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNTIsIm5iZiI6MTczMjc4NTA1MiwicGF0aCI6Ii8xMDM5ODY2ODEvMzkwNzAzNTA5LTA3MWEwNzkzLWMzMzctNGQyNS1hYzBmLTY4NjJlZjJiNjNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwOTEwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWU0NGEwNjhkZGIwNjRiOTFjNTNjNThmMDg5NTlhMGQ2YzA4MjUxOWVmYTI0ZjRmM2ZjZDZmYzhiMzhjMWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kiY9llObzpQsiyG2EzLBBy5jHRKDMNejKncZv56A-nQ) 老师这个文件没改不知道为什么就突然报错了
> 
> 应该是有其他同学在这个文件里添加了`__dlpack_device__`的单测(#69632)，然后你合并一下上游的develop分支就可以了应该

好的老师

2024-11-29 02:53 UTC, HydrogenSulfate reviewed
覆盖率没通过，看起来需要再加几个单测
![image](https://github.com/user-attachments/assets/2ab4acbe-9fac-4c85-8177-c0b966039bca)
这些报错也需要通过单测触发来覆盖，伪代码如下：

``` py
with self.assertRaises(错误类型，如TypeError):
    此处触发对应类型的报错代码
```
这样能测试报错能否正常触发

2024-11-29 03:06 UTC, SCUcookie commented
> 覆盖率没通过，看起来需要再加几个单测 ![image](https://private-user-images.githubusercontent.com/23737287/390946998-2ab4acbe-9fac-4c85-8177-c0b966039bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDk3NTksIm5iZiI6MTczMjg0OTQ1OSwicGF0aCI6Ii8yMzczNzI4Ny8zOTA5NDY5OTgtMmFiNGFjYmUtOWZhYy00Yzg1LTgxNzctYzBiOTY2MDM5YmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZTkwY2RmNzJjMWU0YjA1N2ExYzY2NjYwMDZmODcyNTkxZTQyNjdmMThmMzg0Zjg1ZjVjMTI3ZTFmMTdhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QHgLTBuTzmq_-eahS343B3UO3-ftJqdZkafODVCxT9U) 这些报错也需要通过单测触发来覆盖，伪代码如下：
> 
> ```python
> with self.assertRaises(错误类型，如TypeError):
>     此处触发对应类型的报错代码
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/23737287/390947916-1ac7a26c-ec21-43d6-b891-a4fde503d76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDk3NTksIm5iZiI6MTczMjg0OTQ1OSwicGF0aCI6Ii8yMzczNzI4Ny8zOTA5NDc5MTYtMWFjN2EyNmMtZWMyMS00M2Q2LWI4OTEtYTRmZGU1MDNkNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NzY5Yjc1MzU5ZDU0NDA4YTRmMDE5ZTczMmEzNjI5ZGJlODY0OTc1NWEyMWE0NjQ5YmQ4OTQ5OGMzMTUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mtp1DVfm4VVDI9nih5tCMJsCIZFN9r6sp9s2VWKxwMU)
> 
> 这样能测试报错能否正常触发

好的老师

2024-11-29 13:34 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack_basic.py
哦忘了dlpack不支持XPU了，还麻烦每个单测类的上方加上下面这个装饰器，否则Kunlun-bxcheck会挂
<https://github.com/PaddlePaddle/Paddle/blob/682bd54efbeeab59f18ab7a398791cc2fd31c351/test/dygraph_to_static/test_cast.py#L205-L211>

2024-11-30 10:04 UTC, SCUcookie commented on test/legacy_test/test_dlpack_basic.py
好的

2024-12-03 02:59 UTC, SigureMo commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
`__dlpack__` 和 `__dlpack_device__` 都删掉，property 才加到这里

2024-12-03 03:15 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
> +                    stream.wait_event(event)
这里还麻烦补充一个stream的单测吧，新建stream可以参考：`paddle.device.Stream`: <https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/device/Stream_cn.html#stream>

2024-12-03 03:15 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack_basic.py
> +
此处添加一个单测，不显式调用`__dlpack__()`进行转换，以及与numpy
``` py
...
x = paddle.randn([10, 10]).cpu()
pd_y = paddle.from_dlpack(x)
np_y = np.from_dlpack(x)

# pd_y和np_y一致性检查

...
```

2024-12-03 03:15 UTC, SCUcookie commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
好的

2024-12-03 03:20 UTC, SCUcookie commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
但是__dlpack_device__也要删吗

2024-12-03 03:21 UTC, SigureMo commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
删，`__dlpack_device__` 不是方法吗？

2024-12-03 03:41 UTC, SCUcookie commented on test/legacy_test/test_dlpack_basic.py
> +
好的

2024-12-03 09:54 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
```suggestion
```

2024-12-03 09:54 UTC, HydrogenSulfate commented on python/paddle/base/dygraph/tensor_patch_methods.py
这里得添加上`__dlpack__`：https://github.com/PaddlePaddle/Paddle/blob/89abbdc24df505d582f1a9b3d94f05a9f5caf20e/python/paddle/base/dygraph/tensor_patch_methods.py#L1415-L1423

2024-12-03 09:55 UTC, HydrogenSulfate commented
改完可以本地编包安装测试一下，不然提交的PR的测试也会挂掉

2024-12-03 09:56 UTC, SCUcookie commented on python/paddle/base/dygraph/tensor_patch_methods.py
好的

2024-12-03 09:57 UTC, SCUcookie commented on python/paddle/base/dygraph/tensor_patch_methods.py
>              '__dlpack_device__',
哦哦因为这是别的同学提交的我不确定我能不能改

2024-12-03 09:59 UTC, SCUcookie commented
> 改完可以本地编包安装测试一下，不然提交的PR的测试也会挂掉

好的老师我之前测试过了可能不全

2024-12-03 10:02 UTC, HydrogenSulfate commented
> > 改完可以本地编包安装测试一下，不然提交的PR的测试也会挂掉
> 
> 好的老师我之前测试过了可能不全

如果只是python的修改，可以直接改源码(site_packages/paddle/下的对应文件的代码)进行测试，不用重新编包安装。

2024-12-03 10:10 UTC, SCUcookie commented
> > > 改完可以本地编包安装测试一下，不然提交的PR的测试也会挂掉
> > 
> > 
> > 好的老师我之前测试过了可能不全
> 
> 如果只是python的修改，可以直接改源码(site_packages/paddle/下的对应文件的代码)进行测试，不用重新编包安装。

好的老师

2024-12-03 10:43 UTC, SCUcookie commented on test/legacy_test/test_dlpack_basic.py
> +
这个单测一直遇到tensor找不到__dlpack_device__，但是我查看代码也是最新的
![image](https://github.com/user-attachments/assets/2e4853d7-bbac-4ff3-8853-2eeb3371b359)

2024-12-03 10:47 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack_basic.py
> +
> 这个单测一直遇到tensor找不到__dlpack_device__，但是我查看代码也是最新的 ![image](https://private-user-images.githubusercontent.com/103986681/391930070-2e4853d7-bbac-4ff3-8853-2eeb3371b359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjMxMDEsIm5iZiI6MTczMzIyMjgwMSwicGF0aCI6Ii8xMDM5ODY2ODEvMzkxOTMwMDcwLTJlNDg1M2Q3LWJiYWMtNGZmMy04ODUzLTJlZWIzMzcxYjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMDQ2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTcwOTYxZmRmMjA1OWI2NmMyOGYxYTM0YWY1YjBkNjg1OTdjYTNkZDBiOTAwNmEyNzNjYmVmMDBjYTk2M2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A_QPwsYq6cfSYEvKr26vZi9B0kvgYi8SfZj41gSxODI)

先确认下本地代码是没问题的，我这里是能正常调用的。
![image](https://github.com/user-attachments/assets/0414ac9d-db56-432d-86b5-47b2a351cd56)

2024-12-04 02:35 UTC, HydrogenSulfate commented on test/legacy_test/test_dlpack_basic.py
> +            self.assertTrue(s2.query(), "Stream s2 did not complete all tasks.")
1. 这个单测不对，并没有测试到`__dlpack__`接收一个`stream`参数的case，应该这样调用：`dlpack_capsule = x.__dlpack__(s1)`

2024-12-04 04:58 UTC, SCUcookie commented on test/legacy_test/test_dlpack_basic.py
> +            self.assertTrue(s2.query(), "Stream s2 did not complete all tasks.")
好的老师

2024-12-05 02:46 UTC, SigureMo approved these changes
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20230418/u1f30a/u1f30a_u1f43e.png" width="14" alt="🐾"/>

2024-12-05 02:52 UTC, luotao1 approved these changes

2024-12-05 02:55 UTC, HydrogenSulfate approved these changes
LGTM

2024-12-05 02:55 UTC, merged