[CodeStyle][Typos][C-[32-38]] Fix typos (compatiblity,compability,compitable,Compitable,compatable,compling,comple,complition,complext,compsite)
PaddlePaddle/Paddle pull request #69847
Opened 2024-11-30 10:07 UTC by rich04lin

### PR Category

User Experience

### PR Types

Devs

### Description

Fix:

- compatiblity
- compability
- compitable
- Compitable
- compatable
- compling
- comple
- complition
- complext
- compsite

2024-11-30 11:44 UTC, SigureMo requested changes

2024-11-30 11:44 UTC, SigureMo commented on python/paddle/tensor/creation.py
> +                'complete128',
```suggestion
                'complex128',
```

上面都 complex64 了，这能改错？

2024-11-30 11:49 UTC, rich04lin commented on python/paddle/tensor/creation.py
> +                'complete128',
我以为任务里面给的正确拼写就一定是正确的，思考了一下还是按照任务给的改的

2024-11-30 15:24 UTC, SigureMo approved these changes, later dismissed
LGTMeow <img src="https://www.gstatic.com/android/keyboard/emojikitchen/20240530/u1f4bb/u1f4bb_u1f43e.png" width="14" alt="🐾"/>

2024-12-02 06:01 UTC, SigureMo commented
需要解决冲突

2024-12-02 11:11 UTC, rich04lin commented
> 需要解决。

已解决

2024-12-02 11:51 UTC, SigureMo approved these changes

2024-12-03 02:49 UTC, merged