【SCU】【Paddle Tensor 规范化二期】为any添加复数类型支持
PaddlePaddle/Paddle pull request #70013
Opened 2024-12-06 07:35 UTC by wwwuyan

### PR Category
User Experience 

### PR Types
New features

### Description
any添加复数类型支持

2024-12-06 07:54 UTC, HydrogenSulfate commented on paddle/phi/kernels/cpu/reduce_any_kernel.cc
> +  }
建议为AnyFunctor添加复数特化模板，这样应该不需要添加上述的判断代码

2024-12-06 08:08 UTC, HydrogenSulfate approved these changes
另外请添加对应的单测到Paddle/test/legacy_test/test_reduce_op.py，参考TestAnyXXOp，添加TestAnyComplexOp即可

2024-12-06 08:08 UTC, HydrogenSulfate requested changes
另外请添加对应的单测到Paddle/test/legacy_test/test_reduce_op.py，参考TestAnyXXOp，添加TestAnyComplexOp即可

2024-12-06 10:41 UTC, HydrogenSulfate commented on paddle/phi/kernels/cpu/reduce_any_kernel.cc
根据ops.yaml，any的kernel应该是any，而不是any_raw，可以尝试修改paddle/phi/kernels/reduce_any_kernel.cc

2024-12-06 11:15 UTC, wwwuyan commented on paddle/phi/kernels/cpu/reduce_any_kernel.cc
好的

2024-12-09 09:02 UTC, HydrogenSulfate reviewed
还麻烦解决一下冲突

2024-12-10 11:07 UTC, HydrogenSulfate approved these changes
LGTM

2024-12-10 11:07 UTC, merged