Add transpiler for multi devices
PaddlePaddle/Paddle pull request #7354
Opened 2018-01-09 08:49 UTC by reyoung

* Also make parallel_do support places

2018-01-09 08:50 UTC, reyoung commented on paddle/framework/init.cc
> -  google::InitGoogleLogging(prog_name.c_str());
glog do not store the program name. Must use strdup to create a new buffer.

2018-01-09 08:51 UTC, reyoung commented on paddle/operators/parallel_do_op.cc
> +      if (input_param == kPlaces) {
Places do not have gradient.

2018-01-09 08:51 UTC, reyoung commented on python/paddle/v2/fluid/framework.py
> +    def to_ctor_kwargs(self):
Used by `Block::clone_var`

2018-01-09 18:57 UTC, wangkuiyi requested changes
Thanks for this PR. Is there a design doc for it? I am not sure do we need a transpiler for multiple devices.

2018-01-10 03:03 UTC, reyoung commented
> Is there a design doc for it? I am not sure do we need a transpiler for multiple devices.

The transpiler is useful for multi-devices unittests. We can use the same configuration and use transpiler to transpile it to multi-devices and test the outputs are exactly the same.

If we do not implement a multi-device transpiler before, the unittests must write two methods which are basically the same.

If we are not sure whether we need a transpiler for multiple devices, I can direct implmenet the unittests without transpilers. This PR can be holded now.

2018-01-10 12:07 UTC, tonyyang-svail commented on python/paddle/v2/fluid/transpilers/multi_devices.py
> +                               device_count=0):
is `data_layer` in `parallel_do`'s `sub_block`?

2018-01-10 12:11 UTC, typhoonzero commented on python/paddle/v2/fluid/transpilers/multi_devices.py
> +def transpile_to_multi_devices(program,
We have several transpilers, are we going to all implement as a function or add some base class?

2020-05-22 06:38 UTC, closed without merging