add rank_cost layer
PaddlePaddle/Paddle pull request #9253
Opened 2018-03-20 10:37 UTC by wangsouc

add rank_cost layer, which supports rank_loss op

2018-03-20 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=9253) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Paddle?pullRequest=9253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Paddle?pullRequest=9253) it.</sub>

2018-03-20 11:46 UTC, luotao1 commented
Does this PR fix #9237?

2018-03-21 08:55 UTC, lcy-seso requested changes
请将代码移至models repo，然后再进行code review。

2018-03-21 08:55 UTC, lcy-seso commented on python/paddle/fluid/layers/nn.py
> +    """
添加的layer helper会自动生成官网上的文档。请按照[API注释标准](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md)补充文档。

2020-05-22 06:38 UTC, closed without merging