Add the automatic update of submodules in cmake.
PaddlePaddle/Paddle pull request #951
Opened 2016-12-19 09:58 UTC by Xreki

增加了submodules.cmake，其中可以：
1. cmake时通过`-DWARPCTC_ROOT=...`设置warpctc头文件ctc.h的路径
2. 在`WARPCTC_ROOT/include`和`${PROJECT_SOURCE_DIR}/warp-ctc/include`目录下都没有找到头文件'ctc.h'时，执行命令`git submodule update --init -- warp-ctc`，自动下载submodule。

2016-12-19 15:01 UTC, qingqing01 commented
LGTM

2016-12-20 08:01 UTC, gangliao commented on CMakeLists.txt
> +include(submodules)
名字叫submodules，以后的第三方模块意思是都写里面？

2016-12-20 08:05 UTC, gangliao commented on cmake/submodules.cmake
> +  if(NOT WARPCTC_INCLUDE_DIR)
是不是可以不用`FindWarpCTC()`?

```cmake
if(EXISTS ${PROJECT_SOURCE_DIR}/.gitmodules)
execute_process(
       COMMAND ${GIT_EXECUTABLE} submodule update --init -- warp-ctc
       WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
       OUTPUT_VARIABLE GIT_OUTPUT
       RESULT_VARIABLE GIT_RESULT)
       message(STATUS ${GIT_OUTPUT})

if(${GIT_RESULT})
...
else()
fatal...
endif()
endif()
```

另外modules一次性  --recursive 有什么区别？

2016-12-20 09:46 UTC, reyoung reviewed
另外，wrapCTC应该放到thrid_party里面，而不是根目录里面。

2016-12-20 09:46 UTC, reyoung commented on cmake/submodules.cmake
> +if(EXISTS ${PROJECT_SOURCE_DIR}/.gitmodules)
PROJECT_SOURCE_DIR => ${PROJ_ROOT}

2016-12-20 09:46 UTC, reyoung commented on cmake/submodules.cmake
> +    message(STATUS ${GIT_OUTPUT})
CHECK GIT_RESULT is ok

2016-12-20 11:36 UTC, Xreki commented on cmake/submodules.cmake
> +  if(NOT WARPCTC_INCLUDE_DIR)
我其实对于这个GIT_RESULT做了挺多次实验，发现有时候，执行`git submodule update --init -- warp-ctc`并没有把warp-ctc拉下来，返回结果一直都是0。

2016-12-20 11:38 UTC, Xreki commented on cmake/submodules.cmake
> +if(EXISTS ${PROJECT_SOURCE_DIR}/.gitmodules)
ok

2016-12-20 12:02 UTC, Xreki commented
@reyoung 我想warp-ctc也是应该放在某个子目录下。但是感觉warp-ctc更像plugin而不是third_party，因为warp-ctc是一个可选的功能，当不用到这个功能，就不需要编译warp-ctc本身，而这不会影响paddle其他功能的使用。

2016-12-20 22:15 UTC, wangkuiyi requested changes

2016-12-20 22:15 UTC, wangkuiyi commented on paddle/cuda/include/hl_warpctc_wrap.h
> +#include "ctc.h"
这里是不是还是原来的写法（`#include "warp-ctc/include/ctc.h"）更清晰，能体现出头文件到底在哪里。

2016-12-20 22:15 UTC, wangkuiyi commented on cmake/submodules.cmake
> +  if(NOT WARPCTC_INCLUDE_DIR)
这里可否用 @gangliao 在 https://github.com/gangliao/CodeCoverageCMake/blob/master/cmake/third_party.cmake 这里使用的 `ExternalProject_Add`，而不是自己写代码去 git pull warp-ctc 呢？

2016-12-21 02:12 UTC, Xreki commented on paddle/cuda/include/hl_warpctc_wrap.h
> +#include "ctc.h"
增加了一个WARPCTC_ROOT的cmake选项，原意是如果用户机器上已经安装过warp-ctc，则可以直接使用已经安装好的这个版本。看是否需要支持这种情况吧。

2016-12-21 02:27 UTC, Xreki commented
@wangkuiyi 我尝试过`ExternalProject_Add`这个功能，不过写的比较简单
```bash
ExternalProject_Add(warp-ctc
    PREFIX ${PROJECT_SOURCE_DIR}/warp-ctc
    GIT_REPOSITORY "https://github.com/baidu-research/warp-ctc.git")
```
也可以指定某次commit或者tag。
这样设置，会在make的时候自动下载然后编译warp-ctc。考虑到以下两点：
1. 若使用`ExternalProject_Add`，那似乎也就没有必要添加submodule了。
2. 因为有的用户也许根本不需要使用warp-ctc这个功能，所以我认为warp-ctc应该作为一个可选的组件。在编译paddle之前，强制编译warp-ctc，若warp-ctc编译失败，则会阻塞paddle的编译。

**要不要在编译paddle的时候自动编译warp-ctc**，这个问题也曾经和 @gangliao @luotao1 讨论过。
关于`ExternalProject_Add`的使用，我再查一下吧。

2016-12-21 03:00 UTC, reyoung commented
> 我想warp-ctc也是应该放在某个子目录下。但是感觉warp-ctc更像plugin而不是third_party，因为warp-ctc是一个可选的功能，当不用到这个功能，就不需要编译warp-ctc本身，而这不会影响paddle其他功能的使用。

third_party是引第三方库的标准做法和标准目录结构。如果不是特别必要，还是大家咋弄咱咋弄比较好。


另外，单说plugin这个东西，和动态库以及运行时载入动态库的含义并不一致。关于plugin这个东西，一般会认为是具有统计的接口(interface)的一些不同动态库实现，这些动态库实现可以在运行时载入，卸载。为程序增加和删除功能。重点还是得接口一致，所以和这个ctc的实现不太一样。

可能的plugin的文章:

* http://www.drdobbs.com/cpp/building-your-own-plugin-framework-part/206503957
* http://www.pt-framework.org/htdocs/plugins.html
* http://doc.qt.io/qt-5/qpluginloader.html

2016-12-23 09:56 UTC, closed without merging

2016-12-23 09:57 UTC, Xreki commented
@gangliao 将使用cmake的ExternalProject_Add功能统一实现。